### ISSUE TITLE
Tooltip doesn't work?

### ISSUE THREAD

**Issue by iwh718** [edvin/tornadofx#1001]
button{
...
tooltip("hello")
}

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by edvin** [comment]
It's impossible to say what you're doing wrong since you don't post a complete code example, but here is one that works:

```kotlin
class MyView : View() {
    override val root = stackpane {
        setPrefSize(800.0, 600.0)
        button("Click me") {
            tooltip("Hello")
        }
    }
}
````

If you don't get a tooltip when you hover and hold the mouse still over the button, I would suspect there is something wrong with your JavaFX version, so try the latest :)

**Comment by iwh718** [comment]
@edvin  thanks,it Worked,Before the mouse didn't stay so long time


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by edvin** [comment]
Great :)
