### ISSUE TITLE
How to make the child nodes automatically fill the parent node

### ISSUE THREAD

**Issue by iwh718** [edvin/tornadofx#1002]
I want the listview width as well as the parent node

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by edvin** [comment]
Again, you need to post the piece of code that doesn't do what you want, as this would happen in most cases, like for example this one:

```kotlin
class MyView : View() {
    override val root = stackpane {
        setPrefSize(800.0, 600.0)
        listview(observableListOf("One", "Two", "Three"))
    }
}
```

We do however have a function called `fitToParentSize()` which you could call on the ListView to make it's preferred size bind to the parents size.

**Comment by iwh718** [comment]
@edvin  Thank you for your reply, my English is not very good, so the document some difficult, then I ask you to this. 😊


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by iwh718** [comment]
@edvin 好了＾０＾，谢谢你。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by edvin** [comment]
别客气
