### ISSUE TITLE
Style ListView scrollbars

### ISSUE THREAD

**Issue by AbduazizKayumov** [edvin/tornadofx#1003]
How to style vertical scrollbars of ListView? I couldn't find any sample code for tornadofx. I can style listview itself, but not its scrollbars:
```
style {
         backgroundColor = MultiValue(arrayOf(Paint.valueOf(Theme.colorBackground)))
         backgroundInsets = MultiValue(arrayOf(box(0.px)))
         borderColor = MultiValue(arrayOf(box(Color.TRANSPARENT)))
         borderWidth = MultiValue(arrayOf(box(0.px)))
         padding = box(0.px)
         // Should there be scrollbar stylable lambda?
         scroll_bar.style {  ...?...  }
}
```
I know, it can be styled with CSS, how about having a nice lambda similar to the above example?

**Comment by edvin** [comment]
You just need to nest the right selectors, no magic or special lambdas needed here. Remember, the convention for type safe stylesheet selectors is camel-case, which is automatically converted to lowercase + dash, eg  `scrollBar`.

**Comment by AbduazizKayumov** [comment]
Thank you for quick response, regarding to the right selectors, could you please show an example in a simpler form, let's say for this CSS (for `listview`)
```
-fx-border-width: 0px;
.scroll-bar:horizontal .track,
.scroll-bar:vertical .track{
             -fx-background-color :transparent;
             -fx-border-color :transparent;
             -fx-background-radius : 0.0em;
             -fx-border-radius :2.0em;
 }
```
