### ISSUE TITLE
Launching from commandline

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#101]
I am looking for the best way of starting a tornadofx application from the commandline:
````mvn -Dexec.java -Dexec.mainClass=?````

The solution I came up with works, but is this what we want?
````
fun main(args: Array<String>) {
    Chart().main(args)
}

class Chart : App() {
    override val primaryView = chartview::class

    fun main(args: Array<String>) {
        launch(*args)
    }
}
````

Comments please :)

**Comment by ronsmits** [comment]
Answering my own question after tip from @edvin 

````
fun main(args: Array<String>) {
    Application.launch(Chart::class.java)
````
or
````
fun main(args: Array<String>) {
    Application.launch(Chart::class.java, *args)
````

**Comment by edvin** [comment]
JavaFX exposes these parameters through the `parameters` property of the `Application` instance. In a TornadoFX app you can get to the `Application` instance through the `app` property available to Views.

Note that this object has both a `raw` and a `named` property for easier access depending on the format of your parameters.

**Comment by SamBagdan** [comment]
Thank you!

**Comment by Danilo-Araujo-Silva** [comment]
How can we do that with gradle?
