### ISSUE TITLE
line {...} doesn't work correctly

### ISSUE THREAD

**Issue by Dron-elektron** [edvin/tornadofx#1010]
Properties "startX" and "startY" seems to be broken. Looks like (0, 50), but not (50, 50) as start point. Same strange behaviour with "polyline".

![jl9lV7D](https://user-images.githubusercontent.com/3470142/59104463-52b1c000-893a-11e9-8287-e09c2001037c.png)

OS: Windows 10
JDK: 1.8.0_181
Kotlin version: 1.3.31
TornadoFX version: 1.7.17

**Comment by ruckustboom** [comment]
`VBox` is a layout manager, and as such will reposition its children. You either need to use a parent that won't, or manually reposition it.

**Comment by Dron-elektron** [comment]
I tried to use this code with stackpane and group:

`class MainView : View("TornadoFX Test") {
	override val root = stackpane {
		group {
			line {
				startX = 50.0
				startY = 50.0
				endX = 150.0
				endY = 100.0
			}
		}
	}
}`

Now it works, thx, my bad :D

**Comment by ruckustboom** [comment]
Glad it's working. `group` is indeed a parent that doesn't lay out its children.
