### ISSUE TITLE
fragment in a modal window does not have a title

### ISSUE THREAD

**Issue by Romanow88** [edvin/tornadofx#1017]
With JavaFX 11+ window title can be set only after window is visible

-> Stage.titleProperty()
```java

 @Override
                protected void invalidated() {
                    if (getPeer() != null) {
                        getPeer().setTitle(get());
                    }
                }
```

And the peer gets set on doVisibleChanging which is called when the Window.showing property is changed to true.

Some tinkering with the order of binding / setting the title is in order to be compatible with 11+.

**Comment by edvin** [comment]
Is this change documented or could it just be a bug in JavaFX 11+?

**Comment by Romanow88** [comment]
Looking at the release notes for JFX 11 and 12 (https://github.com/javafxports/openjdk-jfx/blob/jfx-11/doc-files/release-notes-11.md and https://github.com/javafxports/openjdk-jfx/blob/jfx-12/doc-files/release-notes-12.md) I cannot find any mention of this, so it's possibly a bug. Will try to report to bugs.openjdk.java.net

**Comment by edvin** [comment]
Thank you :) Better to get it fixed there :) We can of course do a workaround in the mean time if this is not resolved quickly.

**Comment by Romanow88** [comment]
OK, while trying to write a small app that reproduces the issue it seems that I have a timing issue. I'm trying to access the window title before JFX actually manages to set it... 

Writing something like works fine.
```java
runLater {
   title = "Title"
   runLater {
      //use the title here to get the HWND 
   }
}
```
