### ISSUE TITLE
How to include the no main manifest attribute in tornadofx jar 

### ISSUE THREAD

**Issue by sinmusystems** [edvin/tornadofx#1019]
Hi! I have build and package my tornafofx app in jar using the maven plugin, but when I start run the output target jar, it prompted me no main manifest attribute, in tornadofx-maven-project-1.0.jar.  Could you please advise?

**Comment by edvin** [comment]
There is nowhere near enough information in your post to debug this :) We'd need to see the deployment descriptor at the very minimum. Did you infact configure the maven plugin to start a main method that in turn starts your TornadoFX Application?

**Comment by sinmusystems** [comment]
![图片](https://user-images.githubusercontent.com/19265323/60249502-8e1b2b00-98f7-11e9-8f63-6be1f1172d8f.png)

**Comment by sinmusystems** [comment]
thanks for your kind reply.  do you mean the kotlin-maven-plugin in the pom file

**Comment by edvin** [comment]
No, you need to configure maven with a plugin that will actually inject the main method to run into the manifest. Perhaps a better solution is to look at FXLauncher, which will also give you a native installer and automatic updates for your app: https://github.com/edvin/fxlauncher

**Comment by sinmusystems** [comment]
![图片](https://user-images.githubusercontent.com/19265323/60249990-69738300-98f8-11e9-9161-b5e01be81b1c.png)

**Comment by ctadlock** [comment]
Closing as answered
