### ISSUE TITLE
Clean up for cellFormat

### ISSUE THREAD

**Issue by phiSgr** [edvin/tornadofx#1023]
In [`SmartTableCell`](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/TableView.kt#L71), several things are cleaned up when the item is updated.

In my use case, I want the background colour to depend on some dynamic value so I used [`bindClass`](https://github.com/phiSgr/cassandra-akka-event-viewer/blob/master/src/main/kotlin/com/github/phisgr/eventviewer/views/EventsView.kt#L107). However that needs to be cleaned up and disposed when the item is updated.

So I created a [helper class](https://github.com/phiSgr/cassandra-akka-event-viewer/blob/master/src/main/kotlin/com/github/phisgr/eventviewer/util/TableCellWithCleanUp.kt) to accept clean up callbacks.

Is there a way to accomplish the same goal without extending TornadoFX?

**Comment by edvin** [comment]
If you bind to a property you shouldn't have to clean it up at all, just create a nested `select` or `bind` expression against the `itemProperty`, or even better, use an `ItemCellFragment` and make the binding against your `ItemViewModel`. Much cleaner solution IMO.

**Comment by phiSgr** [comment]
Thanks for replying. I mostly spend time on the backend, so there are many new concepts for me. I am pretty sure I used your library wrong somewhere in my code.

In this case, if I understand your comment correctly, my two options are:

1. Create a new `Property` that depend on the `seqNr` and the `modificationState`. Then in `cellFormat` I can set the `style` to `null` or a new value.
The drawback is then I lose the type-safe CSS, and there's the additional code of combining the two pieces of information into one object.

2. Create a subclass of `TableCellFragment` that does its own styling.
I feel it is too much trouble to create a new class just to show a number with changing background colour.

I'll keep using my callbacks for now.

**Comment by edvin** [comment]
Option 1 is a one liner and option 2 is a cleaner solution for lots of reasons. Your call :)
