### ISSUE TITLE
tornadofx.ItemViewModel: #item and itemProperty an should be nullable

### ISSUE THREAD

**Issue by jschneider** [edvin/tornadofx#1025]
The initial value may be null. Therefore the property itemProperty may contain null. But it has the type ObjectProperty<T>.
I think this should be "ObjectProperty<T?>" - and of course item should be of type "T?".

**Comment by edvin** [comment]
This has been discussed many times before in other areas of the framework, and we've come to the conclusion that it's more convenient to keep it as "T". There were also some issues, I don't remember exactly what, but bottom line is that changing to "T?" does not work well.

**Comment by jschneider** [comment]
Ok. While I don't get it, I have to accept it of course.

I am just reporting this, since I run into a NPE. Which I do not like ;-)

**Comment by edvin** [comment]
Hehe, I understand. Every time it's been brought up it has been for good reason :)
