### ISSUE TITLE
Binding issue

### ISSUE THREAD

**Issue by halimpuckjava** [edvin/tornadofx#1027]
hi

i start with tornadofx but i have issue with binding

```
data class User (val userName: String = "",
                 val password: String = "")

class UserModel : ItemViewModel<User>() {
    val name = bind(User::userName)
    val password = bind(User::password)
}

class FormView : View() {
    override val root by fxml<VBox>("/form.fxml")
    val username by fxid<TextField>()
    val password by fxid<TextField>()
    val btnValide by fxid<Button>()

    val model by inject<UserModel>()

    init {
        model.item = User()

        username.bind(model.name)
        password.bind(model.password)

        btnValide.action {
            //model.commit()
            println(model.item)
        }
    }
}
```

so when print model.item (user), i see nothing in console (username & password is empty), even if i dicomment 'model.commit()' console still empty ?

**Comment by edvin** [comment]
Don't use a data class - the values in that object is immutable, so there is no way for the framework to write back into ut. Define your user class with observable properties instead:

```kotlin
class User(username: String = "", password = "") {
    val usernameProperty = SimpleStringProperty(username)
    var username by usernameProperty

   val passwordProperty = SimpleStringProperty(password)
   var password by passwordProperty
}
```

When that's working, consider skipping FXML, it holds no advantages over the much smoother type safe builders :)

**Comment by halimpuckjava** [comment]
thanks

i see the idea is bind the UserModel properties (name & password) to User properties (usernameProperty & passwordProperty) and not for simple fieldls
