### ISSUE TITLE
VBoxes generated by method render wrong

### ISSUE THREAD

**Issue by bareq** [edvin/tornadofx#1028]
If I create VBoxes by method called inside hbox{}, then they are presented vertically, but when I declare these Vboxes in hbox{} directly they are shown correctly - horizontally. Is it a bug or am I doing something wrong?

```
class BlockSelectionView : View() {
    private val controller: BlockSelectionController = BlockSelectionController(this)

    override val root = vbox {
        prefHeight = 650.0
        prefWidth = 800.0
    }

    init {
        root += hbox {
            selectedBlocks()
            availableBlocks()
        }
    }


    private fun selectedBlocks(): VBox {
        return vbox {
            label("Selected blocks")
        }
    }

    private fun availableBlocks(): VBox {
        return vbox {
            label("Available blocks")
        }
    }
}
```

<img width="272" alt="Screenshot 2019-07-16 at 11 05 02" src="https://user-images.githubusercontent.com/6032614/61281230-97dad480-a7b9-11e9-9be6-126d02d288ff.png">

```
class BlockSelectionView : View() {
    private val controller: BlockSelectionController = BlockSelectionController(this)

    override val root = vbox {
        prefHeight = 650.0
        prefWidth = 800.0
    }

    init {
        root += hbox {
            vbox {
                label("Selected blocks")
            }
            vbox {
                label("Available blocks")
            }
        }
    }
}
```

<img width="228" alt="Screenshot 2019-07-16 at 11 07 02" src="https://user-images.githubusercontent.com/6032614/61281395-dbcdd980-a7b9-11e9-93b5-74dd95f65680.png">

**Comment by QingMings** [comment]
You need use `add()` method 
```kotlin
    override val root = vbox {
        prefHeight = 650.0
        prefWidth = 800.0
    }

    init {

        root += hbox{
//            vbox {
//                label("aaa")
//            }
//
//            vbox {
//                label("bbb")
//            }

            // use  `add()` 
            add(selectedBlocks())
           add( availabelBlocks())
        }
    }

    private fun selectedBlocks(): VBox {
        return vbox {
            label("aaa")
        }
    }

    private fun availabelBlocks(): VBox {
        return vbox {
            label("bbb")
        }
    }

```

**Comment by bareq** [comment]
Thanks :), but why is a method from my previous post possible? hbox{} shouldn't force me to use `add()`?

**Comment by edvin** [comment]
You must consider that the builders work on whatever context they are in, and will add what they build to it's parent. When you create a function inside a View and call a builder (like `vbox` or `hbox` in your case), the builder functions are actually called on the View itself, which will automatically forward the built components to the root object. Instead of having to pass in the parent, consider adding your functions as extension functions instead. This way they will automatically be called on the receiver:

```kotlin
class BlockSelectionView : View() {
    override val root = vbox {
        prefHeight = 650.0
        prefWidth = 800.0
        selectedBlocks()
        availableBlocks()
    }


    private fun EventTarget.selectedBlocks() = vbox {
        label("Selected blocks")
    }

    private fun EventTarget.availableBlocks() = vbox {
        label("Available blocks")
    }
}
```
