### ISSUE TITLE
How to use desktoppanefx in tornadofx to create MDI form

### ISSUE THREAD

**Issue by amasahara** [edvin/tornadofx#1032]
I try use desktoppanefx from [https://github.com/aalmiray/desktoppanefx](https://github.com/aalmiray/desktoppanefx) but seem it not work for me, i can not start new form
This is my code
import javafx.scene.control.Label
import org.kordamp.desktoppanefx.scene.layout.DesktopPane
import org.kordamp.desktoppanefx.scene.layout.InternalWindow
import tornadofx.*

class MainView : View(appName) {
    private var desktopPane = DesktopPane()
    private var countForm = 0
override val root = borderpane {
top {
            menubar {
                        menu("New Form") {
                              item("New Form 1").action {
                                    val window = InternalWindow(
                                            "window-$countForm",
                                            FontIcon("mdi-application:20"),
                                             "Title " + countForm++,
                                           Form1Fragment().root)
                                   desktopPane.addInternalWindow(window)
                              }
                        }
            }
center{
            desktopPane
        }
}
}

**Comment by edvin** [comment]
In your `center` block you are just writing the name of a variable (`desktopPane`), you are not adding it to the center :)

Either write `add(desktopPane)` or assign it to center: `center = desktopPane`.

You should also never instantiate UIComponents manually like you do with `Form1Fragment`. Use either `add()`, `find()`.

**Comment by amasahara** [comment]
thanks for your help, i did it
