### ISSUE TITLE
Suggestion: Add a scrollable = yes parameter to builders.

### ISSUE THREAD

**Issue by ngppgn** [edvin/tornadofx#1035]
Right now, when you want to define, say a scrollable image (to use the example of the guide) yo need to write
`scrollpane {
    imageview("somefile.png")
}`
So you're adding some noise and an indent level just to say that the imageview is scrollable. We'd gain in succintness and readability if we have an overload or default parameter so we could do this:
`imageview("somefile.png", scrollable = yes)`

**Comment by ruckustboom** [comment]
I don't think that's a good idea. It would make the DSL vague. For example:
```kotlin
vbox {
    imageview("somefile.png", scrollable = true) {
        vAlign = ALWAYS
    }
}
```
Would not do what you want. There would be no clear way to access the scroll pane. Basically you're trading extremely surprising (and frustrating) behavior for "prettier" code.

**Comment by edvin** [comment]
I must agree with @ruckustboom - a main selling point of the builders is that you can see and reason about the UI hierarchy just by looking at the code. Not being able to access the scrollpane in any intuitive way is another tell tale sign of a bad idea here :)

**Comment by ctadlock** [comment]
Agree; closing.
