### ISSUE TITLE
Suggestion: Add a singlefield builder.

### ISSUE THREAD

**Issue by ngppgn** [edvin/tornadofx#1036]
Right now, it seems having a field {} builder outside a fieldset{} builder results in exceptions being thrown when I attempt to run the app. For the cases where we want just a single field instead of a set of fields, it'd be nice to have a `singlefield { ... }` which basically compiled to `fieldset { field { .... } }`.

**Comment by ruckustboom** [comment]
If all you want is a single field, why are you using the form builder? This sounds like a likely XY problem to me. Could you provide an example of what you are trying to achieve?

**Comment by edvin** [comment]
I believe @ngppgn is just trying to type less :) Hehe

No, this isn't a good idea, again it would hide the real hierarchy.

**Comment by ctadlock** [comment]
Answered; closing
