### ISSUE TITLE
how to get table data without databinding

### ISSUE THREAD

**Issue by amasahara** [edvin/tornadofx#1037]
i try to get data from excel and show it into tableview
`actionEvents().map {
                        danhMucDVKTController.loadFromExcel().map { danhMucDVKT ->
                            DanhMucDVKTModel().apply {
                                item = danhMucDVKT
                            }
                        }.observable()
                    }.subscribe {
                        table.items.clear()     //clear table items data
                        table.items.addAll(it)  //add data from excel
                        table.selectionModel.clearSelection()
                        table.requestFocus()
                    }`
after that i try to save data to database but when i call table.items, value always is 0 so how to get table items without binding data

**Comment by edvin** [comment]
Post a working sample app so we can see exactly what's going wrong. Also, bind an observable list to the tableview, don't manipulate `table.items` directly.

**Comment by amasahara** [comment]
Here is my full view code

`class DanhMucDVKTFragment : Fragment() {
    private val danhMucDVKTController: DanhMucDVKTController by inject()
    private val eventController: EventController by inject()
    private var btnXemDanhMuc: Button by singleAssign()
    private var btnCapNhatDanhMuc: Button by singleAssign()
    private var btnChonFile: Button by singleAssign()

    private var table: TableView<DanhMucDVKTModel> by singleAssign()

    override val root = borderpane {
        top {
            buttonbar {
                addClass(fontSize16px, fontFamily)

                //reload data
                btnXemDanhMuc = button("Reload Data") {
                    actionEvents().map { Unit }.subscribe(eventController.refreshDanhMucDVKT)
                }

                //save table data to database
                btnCapNhatDanhMuc = button("Cập nhật danh mục") {
                    actionEvents().map { table.items.asSequence().filterNotNull().map { it }.toSet() }
                            .subscribe(eventController.saveDanhMucDVKT)
                }

                //load data from excel
                btnChonFile = button("Choose.....") {
                    actionEvents().map {
                        danhMucDVKTController.loadFromExcel().map { danhMucDVKT ->
                            DanhMucDVKTModel().apply {
                                item = danhMucDVKT
                            }
                        }.observable()
                    }.subscribe {
                        table.items.clear()     //clear table
                        table.items.addAll(it)  //add data from excel 
                        table.selectionModel.clearSelection()
                        table.requestFocus()
                    }
                }
            }
        }

        center {
            tableview<DanhMucDVKTModel> {
                isEditable = true
                scrollpane {
                    column("STT", DanhMucDVKTModel::STT)
                    column("Mã", DanhMucDVKTModel::maDVKT)
                }
                columnResizePolicy = SmartResize.POLICY

                tableFilter.executeFilter()

                eventController.refreshDanhMucDVKT.startWith(Unit)
                        .flatMapSingle {
                            danhMucDVKTController.loadAll.toList()
                        }.subscribeBy(
                                onNext = {
                                    items = it.observable()
                                },
                                onError = { alert(Alert.AlertType.ERROR, "Error get data from database", it.message ?: "").show() }
                        )

                table = this
            }
        }

        //handler save data into database
        val saveData = eventController.saveDanhMucDVKT
                .map { table.items }
                .flatMapSingle { lstDMDVKT ->
                    val dialog = Alert(Alert.AlertType.CONFIRMATION, "Lựa chọn hình thức lưu dữ liệu",
                            ButtonType("Thêm", ButtonBar.ButtonData.YES),
                            ButtonType("Lưu và xóa", ButtonBar.ButtonData.OK_DONE),
                            ButtonType("Bỏ qua", ButtonBar.ButtonData.CANCEL_CLOSE))

                    //add data don't remove data in database
                    dialog.toMaybe().filter { it == ButtonType.YES }
                            .map { lstDMDVKT }
                            .flatMapSingle {
                                danhMucDVKTController.createList(it)
                            }.toObservable().toSet()

                    //remove data in database before add data
                    dialog.toMaybe().filter { it == ButtonType.OK }
                            .map { lstDMDVKT }
                            .flatMapSingle {
                                danhMucDVKTController.delete()
                                danhMucDVKTController.createList(it)
                            }.toObservable().toSet()
                }.publish()

        saveData.subscribe(eventController.saveDanhMucDVKT)

        //add data into datase
        eventController.saveDanhMucDVKT
                .map { Unit }
                .subscribe(eventController.refreshDanhMucDVKT)

        saveData.connect()

        //delete data
        eventController.deleteDanhMucDVKT
                .map { Unit }
                .subscribe(eventController.refreshDanhMucDVKT)

    }
}`

**Comment by edvin** [comment]
Create your observable list as a field member of the class, and create the tableview and bind to that list using the tableview builder (it takes the observable list as an argument).

Also stop using `singleAssign` or even create field members for ui components. That is very seldom needed. You should communicate through events or state instead of accessing the ui components directly.

If you bind your tableview to the list, then all you need to do is to make sure that the list has data, and the tableview will show those data.

**Comment by amasahara** [comment]
thanks for your help, my project has been work
