### ISSUE TITLE
binding pojo's

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#104]
I was looking at the [BeanPathAdapter](https://ugate.wordpress.com/2012/07/30/javafx-programmatic-pojo-expression-bindings-part-iii/) to be able to bind pojo's to views. Is there a plan or vision to have this in tornadofx?

**Comment by edvin** [comment]
For POJO's we could create some kind of wrapper observables that can write back to the POJO and possibly flush changes from the POJO back to the UI. It would also be possible to support automatic bidirectional binding if the POJO is a JavaBean (PropertyChangeSupport), but this pattern is quite dated and AFAIK not widely used, so we'll skip that part until someone has a genuine need for it.

I'll create an initial implementation shortly and report back here.

**Comment by ronsmits** [comment]
Concerning the bidirectionality. As PropertyChangeSupport is not often used a `refresh` method would work quite well too.

**Comment by edvin** [comment]
Absolutely. Is `refresh` a good word? I though about `flush`, but refresh might be better.

**Comment by ronsmits** [comment]
`flushing` indicates emptying, which it is not doing I just kinda like the word `refresh` or `refreshFromPojo` that one is ugly but more explicit in describing what it does

**Comment by edvin** [comment]
OK, first attempt! Consider this POJO:

```java
public class JavaPerson {
    private Integer id;
    private String name;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String toString() {
        return "JavaPerson{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
```

Now you can bind to the properties in two ways, either a type safe way where you reference the getter and setter methods, or a shorter way where you supply the property name and type. Refresh can be called on the binding to update the value from the POJO:


```kotlin
class PojoView : View() {
    override val root = VBox()
    val person = JavaPerson()

    init {
        person.id = 1
        person.name = "John Doe"

        val idProperty = observable(person, JavaPerson::getId, JavaPerson::setId)
        val nameProperty = observable(person, "name", String::class)

        with (root) {
            hbox {
                label("Id")
                textfield(idProperty, IntegerStringConverter())
            }
            hbox {
                label("Name")
                textfield(nameProperty)
            }
            hbox {
                button("Save") {
                    setOnAction {
                        println(person)
                    }
                }
                button("Update from POJO") {
                    setOnAction {
                        person.id = 666
                        idProperty.refresh()
                    }
                }
            }
        }
    }

}```

![](http://i.imgur.com/jO7cFKa.png)

**Comment by ronsmits** [comment]
Looks nice, I will test it out tonight with the POJO's I am working with

**Comment by edvin** [comment]
Perfect! Comment here or close if you're happy :)

**Comment by ronsmits** [comment]
it works, and I will close the ticket as the usecase is fulfilled. however........

Especially with larger classes (think JPA entities) the boilerplate to setup all the properties could get large. Yes, this can be solved by an intellij plugin. I will think more on this

**Comment by edvin** [comment]
Unless you need to refresh changes from the POJO, you could always inline it:

```kotlin
textfield(observable(person, "name", String::class))
```

That's really not that bad, I think you need to supply those three values at a bare minimum. Alternatively of course:

```kotlin
textfield(observable(person, Person::getName, Person::setName)
```

There is definitely stuff that can be done to reduce the boiler plate further, I'll think about this a little and present some suggestions.

**Comment by edvin** [comment]
We could always add an extension function on `Any`, then you can write:

```kotlin
textfield(person.observable<String>("name"))
```

**Comment by edvin** [comment]
Just did, the above syntax is now possible, along with:

```kotlin
textfield(person.observable(Person::getName, Person::SetName)
```

@thomasnield If you can make a heading for this in the guide, I can fill in some key points if you like? :)

**Comment by thomasnield** [comment]
Just saw this, sorry been hammering through my notifications. I'm trying to figure out where this fits...

**Comment by thomasnield** [comment]
I have an empty "Part III - Utilities" where various tools and miscellaneous stuff will be categorized into different sections. I'd show this as a variants in the Builders section but I think this is slightly special-case... almost appendix material. 

I'll tell you what, just throw a markdown file in that "Part III - Utilities" folder and we can figure out where it fits after I finish the builders and document the utilities.

**Comment by edvin** [comment]
Great, thanks Thomas! Will add it later today :)

**Comment by hamboomger** [comment]
The code above works fine, but what if I have POJO with collection as a field:
```
class Person {
    var friends = mutableListOf<Person>()
}
class PersonModel : ItemViewModel<Person>() {
    var friends = bind { item?.observable(Person::friends) }
}
```
In this case I'm getting an exception:
```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to javafx.collections.ObservableList
```
I tried to use the observable() extension method of the `List` interface instead:
```
class PersonModel : ItemViewModel<Person>() {
    var friends = bind { item?.friends.observable() }
}
```
But in this case I got compilation error: `Type inference failed. Please try to specify arguments explicitly`. I tried to set generic types explicitly, but unfortunately without success :(

**Comment by edvin** [comment]
That would be something ugly like:

```kotlin
class PersonModel : ItemViewModel<Person>() {
    var friends = bind { SimpleListProperty<Person>(FXCollections.observableArrayList(item?.friends ?: emptyList())) }
}
```

I can't stress enough that you shouldn't keep fighting observable properties if you're writing JavaFX applications. It just makes your life harder with no benefit.

**Comment by hamboomger** [comment]
Thank you for your fast answer :+1: I wanted to keep POJO's and properties separately because I use JPA entities, but that's enough for me. You are right, I can't fight them forever, so it's time to use `@Transitent` fields. 
P.S. @edvin , your framework is awesome)

**Comment by edvin** [comment]
Thanks :) `@Transient` seems to work fine, even though it's cumbersome. JPA should ignore immutable fields automatically IMO.
