### ISSUE TITLE
Type Safe CSS doesn't work with scrollbar

### ISSUE THREAD

**Issue by kokanrin** [edvin/tornadofx#1042]
class Styles : Stylesheet() {
    init {
        scrollBar {
            unitIncrement = 100.px
            blockIncrement = 100.px
        }
    }
}

**Comment by edvin** [comment]
You have not demonstrated any issues here, please submit a complete code example showing the issue.

**Comment by kokanrin** [comment]
I want to scroll more than default
```
class MyApp : App(TestView::class,Styles::class)

class TestView : View("My View") {
    override val root = borderpane {
        center {
            scrollpane {
                maxHeight = 10.0
                vbox {
                    label("test1")
                    label("test2")
                    label("test3")
                    label("test4")
                    label("test5")
                    label("test6")
                    label("test7")
                    label("test8")
                    label("test9")
                    label("test10")
                }
            }
        }
    }
}

class Styles : Stylesheet() {
    init {
        scrollBar {
            unitIncrement = 200.px
            blockIncrement = 200.px
        }
    }
}
```

**Comment by edvin** [comment]
This has nothing to do with Type Safe CSS, but rather that the ScrollPaneSkin will recalculate and overwrite the configured increment when the component updates. Have a look in `updateVerticalSB` and `updateHorizontalSB`. You can verify this by forcing an increment change by looking up the scroll bars inside the pane, set the `unitIncrement` property and observing that the new increment is momentarily in effect, until you resize, move or interact with the scrollpane in any other way, and you'll see that it resets to the calculated `unitIncrement` instead.

**Comment by kokanrin** [comment]
Thanks a lot!
