### ISSUE TITLE
Kotlin: Cannot access class 'javafx.scene.Node'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by decapo01** [edvin/tornadofx#1050]
Just trying this out as a beginner and get this error.  

```Kotlin: Cannot access class 'javafx.scene.Node'. Check your module classpath for missing or conflicting dependencies```

Here is my code

```
import tornadofx.*

class HelloWorld : View(){

    override val root = vbox {
    }
}

fun main(args: Array<String>) {
    println("Hello, World")
}
```

The compile error is on the ```View()```

**Comment by edvin** [comment]
It sounds like you're using Java 9 or later with TornadoFX 1, which only supports Java 8.

**Comment by decapo01** [comment]
My target version for kotlin is 1.8 and my current selected version on my system is also 1.8.  I do have java 11 on my system but everything I'm seeing in intellij is using 8.

**Comment by edvin** [comment]
The target version doesn't matter as long as you're running J11. It's evident from the error message that you're infact using a J11 JVM to run the app, since J8 doesn't know what module classpath is :)

**Comment by decapo01** [comment]
Actually I got it working and I was using version 1.8....this is a little nasty but you should add it to you guide/documentation.

Javafx doesn't come with open-jdk (which is what I'm using) so you have to install openjfx.

On ubuntu (the os I'm using) you can do this with the command
```sudo apt install openjfx```

HOWEVER when I did this it installed openjfx 11 and obviously still didn't work.  So I found this bug report here https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1799946 and used
```sudo apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2```

After that everything compiles.  I'm surprised this hasn't come up before.

**Comment by edvin** [comment]
Thanks for reporting back. Hopefully this will be useful for others as well until we're all on TornadoFX 2.0 :)

**Comment by ndon55555** [comment]
@edvin This may or may not be interesting, but I started a project on Java 8 while using TornadoFX and made a huge leap to Java 12 and it still works (even in CI). Although, this could be because I'm not really using the more advanced features of TornadoFX

**Comment by edvin** [comment]
JavaFX after version 8 made several changes to package names etc, so there is no way that's going to work as you start using more functions and components. You can however switch over to the RC of TornadoFX 2.0 if you want to see how Java 12/JavaFX 12 performs with TornadoFX :)

**Comment by asterixorobelix** [comment]
@edvin where can I get hold of the TornadoFX 2.0 RC? Preferably as a Gradle dependency

**Comment by edvin** [comment]
It's in the Sonatype OSS Repo :) https://oss.sonatype.org/content/repositories/snapshots/no/tornado/

**Comment by asterixorobelix** [comment]
@edvin I'm encountering some issues with a test intellij/gradle project. If you could assist, I would be happy to do a PR on the documentation so that others can get up and running quickly.

![Screenshot 2019-08-22 at 11 30 03](https://user-images.githubusercontent.com/20531795/63503673-36043d80-c4d0-11e9-8e8b-dd4e4a603766.png)

```
java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

My build.gradle for a test app:
```
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.41'
    id 'org.openjfx.javafxplugin' version '0.0.8'
}

group 'asterixorobelix.tornadofx'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    mavenCentral()
}

javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls' ]
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    implementation 'no.tornado:tornadofx:2.0.0-SNAPSHOT'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}
compileKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

**Comment by brightonc12** [comment]
i was having the same problem. i had openjdk 1.8, and it was unable to locate the class paths. the solution for me was to uninstall the openJdk and download and install the Oracle jdk 1.8 and it worked perfectly.

**Comment by edvin** [comment]
You can run OpenJDK if you like, but that doesn't come with JavaFX so you have to install it separately.

**Comment by nbharat97** [comment]
I am also facing the same issue although I am using java 8, anyone up with a working solution ?

**Comment by SchweinchenFuntik** [comment]
append log-file and example code? and settings build (maven - `pom.xml`, gradle - `build.gradle[.kts]`)
