### ISSUE TITLE
how to config tornadofx live views app via gradle

### ISSUE THREAD

**Issue by amasahara** [edvin/tornadofx#1051]
I create app by using grade and i try to add run of tornadofx but not successful, it can't see MyApp. Seem create app by maven will be better than gradle for liveviews
![Untitled](https://user-images.githubusercontent.com/5392719/62926780-60bf0980-bddf-11e9-83e0-f095525b69fa.png)

**Comment by ctadlock** [comment]
This is more of a Gradle question than a tornadofx couple. 

Checkout the Gradle docs here:
https://docs.gradle.org/current/userguide/application_plugin.html

And the live view param reference here:
https://github.com/edvin/tornadofx/wiki/Application-Startup
