### ISSUE TITLE
How to make splashscreen with progressbar

### ISSUE THREAD

**Issue by amasahara** [edvin/tornadofx#1054]
I try to create an SplashScreen and i want to show it after i upload excel file into my tableview. I don't know how to make it close when excel finish load and update message when it read excel file
My code for SplashScreen view:

    class SplashScreen : View("Please wait") {
    val status: TaskStatus by inject()

    override val root = vbox(4) {
        alignment = Pos.CENTER
        setPrefSize(300.0, 100.0)
        visibleWhen { status.running }
        style { borderColor += box(Color.LIGHTGREY, Color.TRANSPARENT, Color.TRANSPARENT, Color.TRANSPARENT) }
        label(status.title).addClass(Styles.splashScreen)
        progressbar(status.progress)
        label(status.message).addClass(Styles.splashScreen)
    }

    override fun onDock() {
        thread {
            Thread.sleep(8000) //which way i can do to change this thread
            runLater {
                close()
                primaryStage.show()
            }
        }
    }
   }

action for button choose excel file

     btnChonFile = button("", uploadGlyph) {
                    useMaxWidth = true
                    tooltip(toolTipUpload)

                    action {
                        val fileChooser = FileChooser()

                        //load old directory
                        if (file != null) {
                            val existDirectory = file!!.parentFile
                            fileChooser.initialDirectory = existDirectory
                        }

                        fileChooser.title = "Open file"
                        fileChooser.extensionFilters.addAll(FileChooser.ExtensionFilter("Excel File", "*.xlsx", "*.xls"))

                        //open dialog to choose file
                        file = fileChooser.showOpenDialog(null)

                        if (file != null) {
                            find<SplashScreen>().openModal(stageStyle = StageStyle.UNDECORATED)
                            runAsync {
                                updateTitle("Get data from excel file")
                                updateMessage("Reading ...")
                                updateProgress(1, 10)
                                danhMucController.loadFromExcel(file!!).map { danhMucDVKT ->
                                    updateMessage("Updating...")
                                    updateProgress(9, 10)
                                    DanhMucDVKTModel().apply {
                                        item = danhMucDVKT
                                    }
                                }.observable()
                            } ui {
                                lstDanhMucModel.clear()
                                lstDanhMucModel.addAll(it)
                            }
                        }
                    }
                }

Controller for read data from excel and retun an ObservableList, and how to put message and progress into this class

      //Get data from excel file 
     @Throws(IOException::class)
      fun loadFromExcel(file: File): ObservableList<DanhMucDVKT> {

        val lst = FXCollections.observableArrayList<DanhMucDVKT>()
        var isErrorMaNhom9324 = false
        var isErrorDonGiaAX = false

        val fis = FileInputStream(file.absolutePath)

        // we create an XSSF Workbook object for our XLSX Excel File
        val workbook = getWorkbook(fis, file.absolutePath)
        // lấy sheet đầu tiên
        val firstSheet = workbook.getSheetAt(0)

        val count = firstSheet.lastRowNum

        val iterator = firstSheet.iterator()

        while (iterator.hasNext()) {
            val nextRow = iterator.next()
            val danhMucDVKT = DanhMucDVKT()
            val cellIterator = nextRow.cellIterator()

            if (nextRow.rowNum != 0) {
                while (cellIterator.hasNext()) {
                    val nextCell = cellIterator.next()
                    val columnIndex = nextCell.columnIndex

                    //kiểm tra xem dịch vụ kí thuật có được phép sử dụng hay không
                    when (columnIndex) {
                        0 -> {
                            danhMucDVKT.STT = getCellValue(nextCell).toString().toDouble().toInt()
                        }
                        1 -> {
                            danhMucDVKT.maDVKT = getCellValue(nextCell).toString()
                        }
                        2 -> {
                            danhMucDVKT.maAX = getCellValue(nextCell).toString()
                        }
                        3 -> {
                            danhMucDVKT.tenDVKT = getCellValue(nextCell).toString()
                        }
                        4 -> {
                            danhMucDVKT.tenAX = getCellValue(nextCell).toString()
                        }
                        5 -> {
                            danhMucDVKT.maGia = getCellValue(nextCell).toString()
                        }

                        6 -> {
                            danhMucDVKT.donGia = getCellValue(nextCell).toString().toDouble()
                        }
                        7 -> {
                            //thực hiện kiểm tra xem giá ánh xạ có tồn tại hay không nếu không thì cập nhật đơn giá qua
                            if (getCellValue(nextCell).toString() == "") {
                                danhMucDVKT.giaAX = danhMucDVKT.donGia
                                isErrorDonGiaAX = true
                            } else {
                                danhMucDVKT.giaAX = getCellValue(nextCell).toString().toDouble()
                            }
                        }
                        8 -> {
                            danhMucDVKT.quyetDinh = getCellValue(nextCell).toString()
                        }
                        9 -> {
                            danhMucDVKT.congBo = getCellValue(nextCell).toString()
                        }
                        10 -> {
                            danhMucDVKT.maCSKCB = getCellValue(nextCell).toString()
                        }

                        11 -> {
                            if (getCellValue(nextCell).toString() == "") {
                                danhMucDVKT.maNhom9324 = 0
                                isErrorMaNhom9324 = true
                            } else {
                                danhMucDVKT.maNhom9324 = getCellValue(nextCell).toString().toInt()
                            }
                        }
                        12 -> {
                            danhMucDVKT.hieuLuc = getCellValue(nextCell).toString()
                        }
                        13 -> {
                            danhMucDVKT.ketQua = getCellValue(nextCell).toString()
                        }
                        14 -> {
                            danhMucDVKT.lyDoTuChoi = getCellValue(nextCell).toString()
                        }
                    }
                }
                lst.add(danhMucDVKT)
            }
        }

        workbook.close()
        fis.close()

        if (isErrorMaNhom9324) {
            errorAlert("Có lỗi trong quá trình import excel", "Lỗi mã nhóm 9324, vui lòng kiểm tra lại file excel")
        }
        if (isErrorDonGiaAX) {
            errorAlert("Có lỗi trong quá trình import excel", "Lỗi đơn giá ánh xạ trống sẽ lấy từ đơn giá qua, vui lòng kiểm tra lại file excel")
        }

        //thực hiện việc xóa dòng nếu như hiệu lực bằng Không
        lst.removeIf {
            it.hieuLuc == "Không"
        }

        return lst
    }

**Comment by ctadlock** [comment]
There is way too much code here. If you create the simplest example possible it would allow other to help you better.
