### ISSUE TITLE
How to use 'inherit' with Type-safe CSS ?

### ISSUE THREAD

**Issue by Mr-Po** [edvin/tornadofx#1055]
css:

`-fx-background-color: inherit;`

————————
type-safe css:

`backgroundColor += Paint.valueOf("inherit")`

I tried to write that(↑), but it was wrong.

**Comment by edvin** [comment]
You can use unsafe/raw:

```kotlin
unsafe("-fx-background-color", raw("inherit"))
```

`unsafe` lets you use any key you want and raw makes sure the value is not quoted.

**Comment by Mr-Po** [comment]
thanks for your help , the problem was solved.
