### ISSUE TITLE
FxTask does not expose properties for succeeded / failed / cancelled 

### ISSUE THREAD

**Issue by Romanow88** [edvin/tornadofx#1058]
Currently FxTask and by extension the TaskStatus object does not allow to handle/distinguish between success / failure / cancel. All these events are delegated only to the completed property / finally function.

Proposal is to add properties or handlers for the success / failure / cancel events.

**Comment by Romanow88** [comment]
Also, FxTask and TaskStatus are final, so no way to add this functionality via sub-classes.

**Comment by edvin** [comment]
Good idea! Would you be able to submit a PR?

**Comment by Romanow88** [comment]
Sure, that's the plan.

**Comment by Romanow88** [comment]
Seems that there already exists a way to do this, by using the `Task.setOnCancelled` and the appropriate wrappers defined in `Async.kt`

I got confused by the finally method on the FXTask. Going to harmonize those.

**Comment by ctadlock** [comment]
Closing as resolved
