### ISSUE TITLE
Need Spinner Builder

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#106]
We are missing another `Node` builder, the `Spinner` control. I'm documenting for myself when I find time later. But anybody can feel free to jump on it. 

https://dzone.com/articles/javafx-numbertextfield-and

**Comment by t-boom** [comment]
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Spinner.html

**Comment by edvin** [comment]
Spinner can be initialized in many ways, so we need to be careful:

https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Spinner.html#constructor.summary

Seems we need to overload this one, possibly with `Number` ranges, items and valueFactory.

**Comment by edvin** [comment]
I added all possible combinations with the defaults from the corresponding value factory :)

```kotlin
fun Pane.spinner(min: Int, max: Int, initialValue: Int, amountToStepBy: Int = 1, op: (Spinner<Int>.() -> Unit)? = null): Spinner<Int> {
    val spinner = Spinner<Int>(min, max, initialValue, amountToStepBy)
    return opcr(this, spinner, op)        
}

fun Pane.spinner(min: Double, max: Double, initialValue: Double, amountToStepBy: Double = 1.0, op: (Spinner<Double>.() -> Unit)? = null): Spinner<Double> {
    val spinner = Spinner<Double>(min, max, initialValue, amountToStepBy)
    return opcr(this, spinner, op)        
}

fun <T> Pane.spinner(items: ObservableList<T>, op: (Spinner<T>.() -> Unit)? = null): Spinner<T> {
    val spinner = Spinner<T>(items)
    return opcr(this, spinner, op)        
}

fun <T> Pane.spinner(valueFactory: SpinnerValueFactory<T>, op: (Spinner<T>.() -> Unit)? = null): Spinner<T> {
    val spinner = Spinner<T>(valueFactory)
    return opcr(this, spinner, op)        
}
```

**Comment by thomasnield** [comment]
Awesome, this looks great. I'll sit down and mess with this when I get to a computer.

**Comment by edvin** [comment]
I used the spinner builders myself today, seems to work :) Should we close this issue or do you want to play with it a little more first, Thomas? :)

**Comment by thomasnield** [comment]
If you are happy with it I know your judgement is good : )

**Comment by edvin** [comment]
Hehe, OK, I'll close it :) Trying to close everything outstanding so I can start working on the docs :)

**Comment by thomasnield** [comment]
Just reviewed this. Looks great! Thanks @edvin for doing this. Sorry I'm behind this week, I'm just about caught up on my backlog of things at work.

**Comment by edvin** [comment]
Great! And don't be sorry, we play with this when we have the time :)
