### ISSUE TITLE
ItemViewModel and a collection of properties

### ISSUE THREAD

**Issue by Warkst** [edvin/tornadofx#1061]
Let's say I have a POJO that has a collection of properties:

```kotlin
class MyPojo(){
    val stuffMappingProperty = SimpleMapProperty<String, SimpleDoubleProperty>(...)
    val stuffMapping by stuffMappingProperty
    ...
}
```

How would I go about making an `ItemViewModel<MyPojo>` that has bindings for each entry in `stuffMapping`? I've tried binding the map property (`bind(MyPojo::stuffMappingProperty)`) but that adds a binding for the map as a whole, not for each of the `SimpleDoubleProperty` instances... For convenience, you may assume that the list of keys in `stuffMappingProperty` is known at the time that the `ItemViewModel` is instantiated.

**Comment by Warkst** [comment]
Hmmmmm, perhaps I should add a bit more context:

I was able to get it to work with the given code:

```kotlin
keys.forEach{ key ->
    val boundProp = bind {
        item?.stuffMapping?.get(key)
    }
    boundMapping[key] = boundProp
```

However, this is simplified. In my project, I was using `SimpleObjectProperty<Double?>` (to be able to store `null` values, which `SimpleDoubleProperty` can't do), and this was giving me *a lot* of trouble with the `bind` function. However, digging through the issues here, I seem to have found that I can just define the property as `SimpleObjectProperty<Double>` and it will still be nullable (thx java! /s) - but this seems to solve the problem as well...

**Comment by Warkst** [comment]
You know what, never mind, I think that changing `Double?` to `Double` solves *all* my problems. Even binding directly to the map (and then using `.select{...}` to select the "nested" properties (by fetching them from the map by key)) seems to be working. Thx Edvin, your framework is pretty damn amazing.

**Comment by edvin** [comment]
Thank you @Warkst :)
