### ISSUE TITLE
hope to support to jfoenix

### ISSUE THREAD

**Issue by Stars-One** [edvin/tornadofx#1062]
hello,i like the tornadofx view builder with kotlin.It is so useful and effective.But it does't support other library.

I like this,the code is so clean
```
override val root = vbox {
        button("Press Me") {
            textFill = Color.RED
            action { println("Button pressed!") }
        }
    }
```
but when use other libary,must use `+=` ,like this
```
override val root = vbox {
       //JFXButton is a control which extends button and is from the Jfoenix libray 
        this+=JFXButton("btn")
    }
```

**Comment by edvin** [comment]
Well, that's the beauty of this approach - it's extremely easy to make builders for other libraries. Have a look at https://github.com/edvin/tornadofx-controlsfx, which is one such library for ControlsFX. You can use exactly the same approach for JFoenix :)

**Comment by gtnarg** [comment]
You might also want to check out  https://github.com/bkenn/KFoenix

**Comment by edvin** [comment]
Oh, cool @gtnarg :)

**Comment by Stars-One** [comment]
@gtnarg Thanks so much. It is so great!
