### ISSUE TITLE
How to convert xml string to JsonModel

### ISSUE THREAD

**Issue by amasahara** [edvin/tornadofx#1063]
I try to read an XML string to JsonModel but don't know how to do it. My code:

xml string: 

< Person > 
          < name > Thanh < /name >
          < age > 20 < /age >
< /Person >     

My viewmodel

   class Person : JsonModel{
      val nameProperty = SimpleStringProperty()
      var name by nameProperty

      val ageProperty = SimpleStringProperty()
      var age by ageProperty

   override fun updateModel(json: JsonObject) {
        with(json){
            name= string("name") ?: ""
            age= string("age") ?: ""
        }
}
}

**Comment by edvin** [comment]
There is nothing in TornadoFX that will help you with parsing XML, so you'll have to parse it using JAXB or something else and then assigning the values to your Person model.
