### ISSUE TITLE
INFO: Installing CSS url handler, since it was not picked up automatically

### ISSUE THREAD

**Issue by JJScrivener** [edvin/tornadofx#1075]
Hello,

I am very new to Kotlin and Tornadofx so I am sorry if this is a silly question. I am doing the most simple example from the Tornadofx guide part 1: 3. Components. It runs fine and I get the same output, a window with a button and a label but I keep getting the following in the Run log.

Sep. 18, 2019 6:38:52 PM tornadofx.Stylesheet$Companion detectAndInstallUrlHandler
INFO: Installing CSS url handler, since it was not picked up automatically

What I did was create a Kotlin JVM project in Intellij, then I went to the settings and added the Tornadofx library from the JAR file before following the instructions in the guide. I am using Java11, Intellij IDEA 2019.2.2 Community edition, Tornadofx 1.7.19. I saw an identical issue with someone else running Java9 and apparently the issue was because Tornadofx didn't support Java9.

Like I said it actually seems to work just fine I just wish it didn't have that red text in the Run log. If this is a normal thing and I have wasted everyone's time I am very sorry.

**Comment by edvin** [comment]
TornadoFX 1 is only compatible with Java 8, so you're bound to run into issues this way. You can try the 2.0.0-SNAPSHOT release (https://oss.sonatype.org/content/repositories/snapshots/no/tornado/tornadofx/2.0.0-SNAPSHOT/) if you're using Java 9 or later :)

**Comment by JJScrivener** [comment]
Thank you for your quick response. I had a feeling it was something simple like that.
