### ISSUE TITLE
work on jdk 11

### ISSUE THREAD

**Issue by SchweinchenFuntik** [edvin/tornadofx#1080]
in the jdk10 branch, I did not find some functionality of the main branch:
`observaleListOf`, `doubleProperty`, `stringProperty` etc.
Is this conceived or not transferred from the main branch? I plan to switch to jdk11 by forking the repository and revision such places.

**Comment by SchweinchenFuntik** [comment]
also how do you look at adding kotlin contracts?

**Comment by edvin** [comment]
None of the changes made to the main branch has been ported to the jdk10 branch yet. A great deal of work is needed here, though it should be fairly easy to do. If anyone have time to help out with this, we would get to the official 2.0 release a lot quicker!

Status of Kotlin contracts: https://github.com/edvin/tornadofx/issues/939

**Comment by SchweinchenFuntik** [comment]
I will be happy to help you.

**Comment by edvin** [comment]
Great, that would be fantastic!
