### ISSUE TITLE
Replace `compile` dependency scope in examples with `implementation`

### ISSUE THREAD

**Issue by CommanderTvis** [edvin/tornadofx#1081]
`compile` dependency scope is deprecated now, it would be nice to replace it with `implementation` in README example. I think that there's not so many Gradle 2 users.

**Comment by edvin** [comment]
What examples are you referring to? :) I don't use Gradle myself, so I don't follow it closely, but feel free to submit a PR for updated config.

**Comment by CommanderTvis** [comment]
this one
![image](https://user-images.githubusercontent.com/38042667/65617029-38354c80-dfe6-11e9-9115-c48a603bb522.png)
:)

**Comment by CommanderTvis** [comment]
i'll submit, yep

**Comment by edvin** [comment]
Ah, that one :) I'll fix it right away, hang on!

**Comment by edvin** [comment]
Done :)
