### ISSUE TITLE
How to send image or file via post request?

### ISSUE THREAD

**Issue by saqi7022** [edvin/tornadofx#1083]
Hi, 
can you please show how could an image or file to sent via post request.

**Comment by edvin** [comment]
You can send any kind of data, and for images, an `InputStream` is probably your best choice:

```kotlin
api.post("/some/path", stream)
```

Remember to either `consume()` the result or extract whatever data the server sends in the response.

**Comment by saqi7022** [comment]
thank you edvin for being super quick. :) wasn't expecting that
ok i got how to send files to server.
if you could help, not directly related to tornadofx, I know to read file from website using enctype="multipart/form-data" and save file to server.
how could i do similar with torndofx + springboot
i would be very gratefull.  
thanks in advance

**Comment by edvin** [comment]
As discussed on SO, I believe the best approach here would be to use the Apache HttpClient API directly, since it's already on the classpath. Alternatively Base64 encode the image data in the json payload, though it is not suited for large data sets.
