### ISSUE TITLE
Does it work in kotlin/native?

### ISSUE THREAD

**Issue by okkkkk1232** [edvin/tornadofx#1089]
I just wonder if it works on Kotlin/Native ? If it's not i hope it will be implemented. Or if it is impossible then yaa. Can i just know please???

**Comment by edvin** [comment]
TornadoFX is an API layer on top of JavaFX, so for TornadoFX to work on Kotlin Native, JavaFX would need to work on it as well. That's not the case unfortunately :)

**Comment by rsglobal** [comment]
In order to implement your idea, JavaFX should be ported to kotlin at first and later to kotlin/native.
You can propose this to JavaFX community ( http://mail.openjdk.java.net/mailman/listinfo/openjfx-dev )

**Comment by okkkkk1232** [comment]
thats too bad
