### ISSUE TITLE
Any plans to be inline with openJFX

### ISSUE THREAD

**Issue by meshpaul** [edvin/tornadofx#1092]

**Comment by edvin** [comment]
What do you mean?

**Comment by meshpaul** [comment]
See JFX related fixes https://github.com/javafxports/openjdk-jfx/blob/jfx-13/doc-files/release-notes-13.md#release-notes-for-javafx-13.

**Comment by edvin** [comment]
Still not sure what you're asking. TornadoFX 2.0 is targetting JDK10/11+, and should run against OpenJFX 13.

**Comment by meshpaul** [comment]
I am sorry unless I am mistaken does tornado FX uses javaFX?

**Comment by edvin** [comment]
That's correct. You can report any issues with compiling/running against OpenJFX 13, or submit PR's :)

**Comment by meshpaul** [comment]
Ok
