### ISSUE TITLE
TableView Builder?

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#11]
Do you think it is possible to create a `TableView` builder? I think it would go nicely with the `TableView` extensions already present. I can put in a PR and try to work out the details if needed, unless somebody has a faster vision than me on how to do it.

```
tableview {
        items = getMyItems()
        addColumn<ReportItem,String>("Category") { it.value.name }
        addColumn<ReportItem,BigDecimal>("Week") { it.value.weekTotal }
}
```

**Comment by edvin** [comment]
That should be doable :) I'll give it a go during the next week. I'm on vacation though, so I might not get it done before the week after.

**Comment by thomasnield** [comment]
Okay, have a nice vacation! if I have time I may put in a PR just to attempt getting involved in this project. But no worries.

**Comment by edvin** [comment]
Let me know if you wan't to give this a go as well, @thomasnield ? :)

**Comment by thomasnield** [comment]
I think I'm gonna. Maybe tonight, or sometime this week.

**Comment by thomasnield** [comment]
I've got a few ideas. I'm going to review the `TableView` API and plan this carefully over the next few days.

**Comment by edvin** [comment]
Ouch, I just had to give this a crack, actually needed it today. I found a way to avoid repeating the table type argument, so you can write:

```kotlin
tableview<ReportItem> {
    items = getMyItems()
    column<String>("Category") { it.value.name }
    column<BigDecimal>("Week") { it.value.weekTotal }
}
```

It really bothered me to repeat `ReportItem` on every column line. I'm gonna check in my implementation soon, take a look and let me know what you think. Nothing is final, so we can play with it until we get it right :)

`addColumn` is called `column` in the builder, to align it with the rest of the syntax. To avoid repeating `ReportItem` on every column line I had to subclass TableView. This kind of breaks with the rest of the builders, but I think this might be a migration path to add even nicer syntax to builders over time.

What do you think?

**Comment by thomasnield** [comment]
At first glance this looks really good. Kind of what I envisioned. I'll play with it today. And ditto on the column type parameters. Btw do we want to include cell and row rendering factories too?

**Comment by edvin** [comment]
Yes! I already made `cellFormat`: https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Nodes.kt#L113

**Comment by edvin** [comment]
(If `cellFormat` is too simplistic, we'll change it :)

**Comment by thomasnield** [comment]
Part of me thinks we should also have a builder for an entire `TableColumn<R,T>` and manipulate it.

**Comment by thomasnield** [comment]
Okay cool! I'll play with this today because I'm building a UI at work.

**Comment by edvin** [comment]
Sweet! I'll close the ticket, since the feature is implemented, but let me know if we need to change it, or if you have suggestions for cellFactory/columnFactory related improvements :)

**Comment by thomasnield** [comment]
Okay will do.. can't wait to play around with this.

**Comment by thomasnield** [comment]
I like it. Very slick. 

```kotlin
class MainApp : App() {
    override val primaryView = MainView::class

    class MainView : View() {
        override val root = GridPane()

        init {

            with(root) {
                tabpane {
                    gridpaneConstraints {
                        vhGrow = Priority.ALWAYS
                    }
                    tab("Report", GridPane()) {
                        this += ReportTable.create().gridpaneConstraints {
                            vhGrow = Priority.ALWAYS
                        }
                    }
                    tab("Data", GridPane()) {
                        tableview<String> {
                            gridpaneConstraints {
                                vhGrow = Priority.ALWAYS
                            }
                            items = FXCollections.observableArrayList("Alpha","Beta","Gamma","Delta","Epsilon","Zeta","Eta")
                            column<String>("String") { ReadOnlyStringWrapper(it.value) }
                            column<Int>("Length") { ReadOnlyObjectWrapper<Int>(it.value.length) }
                                    .cellFormat {
                                        if (it ==4) {
                                            style = "-fx-background-color:#8b0000; -fx-text-fill:white"
                                            text = it.toString()
                                        }
                                        else {
                                            text = it.toString()
                                        }
                                    }
                        }
                    }
                }
            }
        }
    }
}
```

<img width="187" alt="screen" src="https://cloud.githubusercontent.com/assets/7420801/13227696/8261e658-d95d-11e5-80ea-6ae527a01fd2.png">

I might be fixating beyond what is already a great solution, but here are some possible ideas:

1. Maybe we can add a `tablecolumn()` factory to access an intermediary builder to set both the value and render factories? Kind of like the gridpane.

2. If we want to display only static, non-`ObservableValue` data, maybe we can eliminate the need to create intermediary `ReadOnlyxxxWrapper`  and have the library do it. 

I haven't thought either through comprehensively yet though.

**Comment by thomasnield** [comment]
I'm just trying to think if there is a more elegant way to nest the `cellFormat`, but the more I think about it, this seems to be the optimal way.

**Comment by thomasnield** [comment]
But taking care of generating `ReadOnlyxxxWrapper` instances might be very worthwhile.

**Comment by thomasnield** [comment]
I don't know if I'm approaching this effectively, just to get rid of creating `ReadOnlyxxxWrapper`. I suppose the other option is to add an extension to all types and call it `toBinding()`, just to quickly make anything a single-value `ObservableValue`. 

```kotlin
class FXTableView<S> : TableView<S>() {
    fun <T> column(title: String, valueProvider: (TableColumn.CellDataFeatures<S, T>) -> ObservableValue<T>): TableColumn<S, T> {
        val column = TableColumn<S, T>(title)
        column.cellValueFactory = Callback { valueProvider(it) }
        columns.add(column)
        return column
    }
    fun <T> columnStatic(title: String, valueProvider: (TableColumn.CellDataFeatures<S, T>) -> T): TableColumn<S, T> {
        val column = TableColumn<S, T>(title)
        column.cellValueFactory = Callback { StaticBinding(valueProvider(it)) }
        columns.add(column)
        return column
    }
}

private class StaticBinding<T>(val fixedValue: T): ObservableValueBase<T>(),Binding<T> {

    override fun getValue(): T = fixedValue

    override fun dispose()= throw UnsupportedOperationException()

    override fun getDependencies(): ObservableList<*>? = throw UnsupportedOperationException()

    override fun invalidate() = throw UnsupportedOperationException()

    override fun isValid() = true

}
```

Usage

```
 tab("Data", GridPane()) {
                        tableview<String> {
                            gridpaneConstraints {
                                vhGrow = Priority.ALWAYS
                            }
                            items = FXCollections.observableArrayList("Alpha","Beta","Gamma","Delta","Epsilon","Zeta","Eta")
                            columnStatic<String>("String") { it.value }
                            columnStatic<Int>("Length") { it.value.length }
                                    .cellFormat {
                                        if (it ==4) {
                                            style = "-fx-background-color:#8b0000; -fx-text-fill:white"
                                            text = it.toString()
                                        }
                                        else {
                                            text = it.toString()
                                        }
                                    }
                        }
                    }
```

**Comment by edvin** [comment]
Looks good! But ofcourse we can do better :))

I might have an idea about how to overload the column function to set static values (by static values, . Need to put kids to bed and make supper, be back in a bit :)

Could you try to explain in detail what you mean by 1.?

**Comment by edvin** [comment]
I found a way that you can write:

```kotlin
    column<String>("Name", static = { it.value.name })
```

.. and still use the old syntax for observable values, either one of these:

```kotlin
    column<String>("Name",  { it.value.name })
    column<String>("Name")  { it.value.name }
```

It works, don't know what you think of the syntax, but it gives a non-verbose way of accessing non-observable values.

Implementation is like this:

```kotlin
class FXTableView<S> : TableView<S>() {
    fun <T> column(title: String, static: ((TableColumn.CellDataFeatures<S, T>) -> T)? = null, observable: ((TableColumn.CellDataFeatures<S, T>) -> ObservableValue<T>)? = null): TableColumn<S, T> {
        val column = TableColumn<S, T>(title)
        column.cellValueFactory = Callback {
            if (observable != null)
                observable(it)
            else if (static != null)
                SimpleObjectProperty<T>(static(it))

            throw RuntimeException("You must supply either static or observable value provider")
        }
        columns.add(column)
        return column
    }
}
```

What do you think? Just playing with options :)

**Comment by edvin** [comment]
I just used SimpleObjectProperty for now to get the point across btw :)

**Comment by thomasnield** [comment]
I actually kind of like this. A little subtle but that is kind of what we are going for. Do you think `static` is the right parameter name? Might confuse Java devs so I'm kind of rethinking that.  Maybe `fixedval`?

**Comment by edvin** [comment]
You're right, static is all wrong. Also, it kind of bothers me that it has to do the if for every invocation. Don't think it matters performance-wise though. Let's try to come up with a better name first :)

**Comment by thomasnield** [comment]
Yeah we can probably just use `SimpleObjectProperty`. I think I overcomplicated by creating my own `Binding`, unless internal immutability is important (which maybe it is). I think we can also use `ReadOnlyObjectWrapper` if needed.

That did bother me too for the `if`. There's got to be a more fluent way to specify that behavior. Also, isn't it kind of silly JavaFX forces us to re-implement the text on the rendering? Maybe we can take care of that too.

**Comment by edvin** [comment]
Hmm.. I don't feel completely comfortable with this approach, there has to be a better way. Oh, and yes, we should provide better defaults for just setting a text value.

Gotta run now, will look more at this tomorrow :)

**Comment by thomasnield** [comment]
Here's some candidates from me: `fixedVal`, `singleVal`, `immutableVal`...

**Comment by thomasnield** [comment]
Okay sounds good.

**Comment by edvin** [comment]
I believe I found an acceptable solution. If you have non-observable fields with getters/setters in your domain object, you can now simply do:

```kotlin
column("Category", ReportItem::category)
```

Notice the lack of _any_ type parameters :)

I also found a similar solution if you have observable values exposed as functions, like item.categoryProperty():

```kotlin
column("Category", ReportItem::categoryProperty)
```

Again, no type arguments :)

This last little gem came at the price of reflection, but atleast I avoided need for `kotlin-reflect` on the classpath. Also, it was actually impossible to implement that last part in Kotlin, had to resort to a helper function written in Java.

Please let me know if you see a better way of doing this, but I have a good feeling about this one :) @thomasnield  @hastebrot

**Comment by thomasnield** [comment]
This is pretty awesome! So this will work with immutable fields with only getters too? 

I'm not big on reflection but considering JavaFX already uses it heavily, and the convenience and simplicity of this API, I think this is a good solution.

**Comment by edvin** [comment]
Good catch, just added support for immutable data structures as well :)

As a result of this, there is now also a function available to turn any member into an observable that will write back to the member if it's writable :)

```kotlin
class MyClass {
    val id = 43
    val idProperty = observable(this, MyClass:id) // type will be ReadOnlyObjectProperty<Int>

    var id = 43
    val idProperty = observable(this, MyClass:id) // type will be ObjectProperty<Int>
}
```

**Comment by thomasnield** [comment]
That is pretty slick. I'm going to use this heavily in the next few days. But this is looking awesome.

**Comment by edvin** [comment]
Cool! Let me know if you run into problems!

**Comment by thomasnield** [comment]
I guess we'll wait a few days before we release? I can beta-test this if that's the case.

**Comment by edvin** [comment]
Absolutely. I would like to get in some more features as well before the next release.

**Comment by thomasnield** [comment]
I will probably help drive that because I'm building a pretty demanding JavaFX application in Kotlin over the next two weeks.

**Comment by edvin** [comment]
Perfect :)

**Comment by thomasnield** [comment]
I've got some enhancement ideas, especially for cell formatting on a `TableView`. For one it would be nice for a given `TableView<S,R>` to have access to the `S` item rather than just the `R` for a given `cellFormat()` operation. 

I don't know how to do this so I posted a SO question. 
http://stackoverflow.com/questions/35661981/javafx-getting-entire-row-item-for-cellfactory

**Comment by edvin** [comment]
I believe it already has. I remember I though that it would be important to have access to the item, or I would have chosen another approach for the `cellFormat` interface. But hey, we could add a `getItem()` extension function maybe? I hope I answered the SO question correctly :)

**Comment by edvin** [comment]
Just got back from dinner and Deadpool and it's already midnight here, so I will pick up again tomorrow morning and try to work on documentation a little. Good night :))

**Comment by thomasnield** [comment]
Haha it was an amusing movie. Thanks, and you were right. I accepted your answer. Good night!
