### ISSUE TITLE
Clipboard functions

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#110]
Using the clipboard in JavaFX is a little verbose. Setting a simple string is somewhere along the lines of:

```kotlin
Clipboard.getSystemClipboard().setContent(ClipboardContent().apply { putString("mystring) })
```

Setting other data types can be even more verbose. Let's create a nicer syntax for using the clipboard. We need to make sure that we don't hide any features.

**Comment by ronsmits** [comment]
ROFL I have this code :)

**Comment by edvin** [comment]
Sweet! Will you create a PR? :)

**Comment by ronsmits** [comment]
Need to clean it up a bit, but I will, There is still the PR open for preferences btw

**Comment by edvin** [comment]
I'll get on it ASAP :)

**Comment by edvin** [comment]
Let me know if you're too busy Ron, then I can add this instead :)

**Comment by edvin** [comment]
`Component` now have a `clipboard` property that can be used like this:

```kotlin
// Copy a string to the clipboard
clipboard.putString("Hello Clipboard")

// Copy a custom data object
clipboard.put(MyDataFormat, myValue)

// Copy files
clipboard.putFiles(myFiles)
```

It's important to remember that each of these functions clear everything on the clipboard. To set data in multiple formats in one go, do:

```kotlin
clipboard.setContent {
    putString("Hello Clipboard")
    clipboard.put(MyDataFormat, myValue)
}
```
