### ISSUE TITLE
Giant Tooltip boxes

### ISSUE THREAD

**Issue by MGlolenstine** [edvin/tornadofx#1103]
![image](https://user-images.githubusercontent.com/9406770/67165568-fac6a380-f386-11e9-9e6c-5e54e9043ca4.png)
This is what I get after supplying imageview with the tooltip.
Example:

```
parent.add(imageview(category.getString("avatarUrl")){
    fitHeightProperty().bind(32.toProperty())
    fitWidthProperty().bind(32.toProperty())
    tooltip(category.getString("name")) {
        showDelay = Duration.seconds(0.0)
        hideDelay = Duration.seconds(0.0)
    }
})
```

Above picture depicts tooltip appearing after hovering over an imageview.

**Comment by edvin** [comment]
I imagine that’s due to the size of the picture and fitToX not doing what you expect. Can you post a runnable code sample?

**Comment by MGlolenstine** [comment]
You might be onto something.
The runnable sample I just created works perfectly fine.
![image](https://user-images.githubusercontent.com/9406770/67165716-e84d6980-f388-11e9-86ce-c61d66f59b57.png)
So the 
```
fitHeightProperty().bind(32.toProperty())
fitWidthProperty().bind(32.toProperty())```
are a probable cause, but I thought that it wouldn't spread onto the child.
There's also another question, which I've asked on [stackoverflow](https://stackoverflow.com/questions/58476207/how-to-load-an-image-with-fixed-size-in-tornadofxs-imageview)

**Comment by MGlolenstine** [comment]
Ok, found the problem. I was using the following piece of code in the Styles class.
```
root {
    prefWidth = 800.px
    prefHeight = 600.px
}
```
