### ISSUE TITLE
Class 'wu.seal.demo.app.MyApp' not found in module 'DevToolsFX'

### ISSUE THREAD

**Issue by wuseal** [edvin/tornadofx#1106]
As show below：
![image](https://user-images.githubusercontent.com/9211902/67376540-e5d05700-f5b6-11e9-8ad1-6da8992cd7ce.png)
But I could run the app by this way:
![image](https://user-images.githubusercontent.com/9211902/67376587-ff719e80-f5b6-11e9-9326-10baebcbe659.png)
What happend? anything wrong with the plugin?
I am using `IntelliJ Idea 2019.2.3

Also Class is really here:
![image](https://user-images.githubusercontent.com/9211902/67376778-4790c100-f5b7-11e9-84cf-4e5dd4e39ce5.png)

**Comment by wuseal** [comment]
@edvin

**Comment by edvin** [comment]
Can you upload the whole project?

**Comment by SchweinchenFuntik** [comment]
helps me choose a `use classpath module` with `main`

**Comment by wuseal** [comment]
@SchweinchenFuntik Yes! That works, Thanks very much!
![image](https://user-images.githubusercontent.com/9211902/68205476-66ef0b80-0005-11ea-8366-bcdc4acaca8a.png)

**Comment by SchweinchenFuntik** [comment]
but liveview does not work, not sure if this is due to this

**Comment by edvin** [comment]
What do you mean by "does not work"?

**Comment by SchweinchenFuntik** [comment]
@edvin recompiling a file does not update View

**Comment by edvin** [comment]
Are you talking about the Live Views feature? For that to work you need to check the Live Views checkbox and make sure you run in debug mode. If you're recompiling files and restarting the app and don't see your changes, that means that your compiled files are not ending up in the folder you're running the app from. I've personally never seen anything like that happen, but would not be an issue with the framework but rather an issue with the Gradle plugin I would presume.
