### ISSUE TITLE
Form Builders

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#111]
Business applications are often form heavy, and JavaFX does not have any layouts that lends itself perfectly to forms without a lot of tweaking. I'd like to introduce a specialized version of the TornadoFX-Controls Forms component into TornadoFX, with both FXML support and Type Safe Builders.

**Comment by thomasnield** [comment]
I'd like to see this. Forms are pretty cumbersome.

**Comment by edvin** [comment]
Here is a small sample, more information coming:

```kotlin
class FormTests : View() {
    override val root = Form()

    init {
        importStylesheet(Styles::class)

        with (root) {
            fieldset("Personal Information") {
                field("Name") {
                    textfield()
                }

                field("Birthday") {
                    datepicker()
                }
            }

            fieldset("Address") {
                field("Street") {
                    textfield()
                }

                field("Zip / City") {
                    hbox {
                        textfield() {
                            maxWidth = 75.0
                        }
                        textfield()
                    }
                }

                field {
                    button("Save")
                }
            }
        }
    }
}

class Styles : Stylesheet() {
    init {
        select(form) {
            padding = box(15.px)
        }
    }
}
```

![](http://i.imgur.com/VF0vThD.png)

**Comment by thomasnield** [comment]
Wow! Very clean : ) this beats nesting VBox and Hbox instances

**Comment by edvin** [comment]
Oh, and it's much more. The legend and labels supports icons, and the labelPosition attribute will determine if the labels are above or to the left of the inputs. Additionally, it supports "responsive" layout, by switching to vertical label positioning when the form width is decreased below a configurable width.

**Comment by thomasnield** [comment]
I wish I had this a week ago. Nice work! When will it be ready for release?

**Comment by edvin** [comment]
Haha :) I have one small niggle to straighten out and then I'll run through the tests I have for TornadoFX-Controls. Should be done in a couple of days, maybe even tonight :)

**Comment by edvin** [comment]
OK, it's finished now :) I had to do the old fake pane trick because Field is not a Pane. It's a control, because it needs to change behavior depending on labelPosition (some times it behaves like a hbox, other times like a vbox), and Control makes it much easier to position children on it. I'll rewrite it so that it's a pane tonight, but the usage will be exactly the same.

**Comment by thomasnield** [comment]
Documenting this right now in the guide, under _Layouts and Menus_ section

**Comment by edvin** [comment]
Thank you! I suspect this will receive some feature requests once people start using it, by the way. It's complete, but even more boiler plate can be squashed for some use cases :)
