### ISSUE TITLE
java.lang.NoClassDefFoundError: javafx/application/Application

### ISSUE THREAD

**Issue by wuseal** [edvin/tornadofx#1114]
When I give the distribution to another one to run, It will be broken, And then what I can do to fix it,
In my mac, It works well.
![image](https://user-images.githubusercontent.com/9211902/68298644-d7b12900-00d4-11ea-8530-93e99f833a6e.png)
@edvin 
```
Error: Could not find or load main class wu.seal.demo.app.MyApp
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```
And Their Environment is Java8
Also in my Linux VM with java11 run with the same problem.
Is there any quick method to let others could run my tornadofx app?

I had also let others to run these command lines:
```
wget http://fxldemo.tornado.no/fxlauncher.jar
java -jar fxlauncher.jar
```
But with the same Error

It seems that `javaFx` is hard for using for others.

**Comment by wuseal** [comment]
No solution for this? or I may give up using tornadofx:disappointed_relieved:

**Comment by edvin** [comment]
You're giving way to little information to debug this. You say it runs on your machine, but not when you "give" it to someone else, without saying how you distribute it. It seems like you're using fxlauncher. If the fxlauncher binary runs on your machine, I'm pretty sure it will run on other machines (with the same os) without modification. Not sure what the issue is, but you need to give us more info to be able to debug it. What about uploading what you are distributing, for example?

**Comment by wuseal** [comment]
@edvin this is my distribution.
[DevToolsFX.zip](https://github.com/edvin/tornadofx/files/3828396/DevToolsFX.zip)

**Comment by wuseal** [comment]
Sorry, I thought this is a very common easy issue but I can't find any solution, Maybe others' OS miss the JavaFX Runtime, but I can't find a fit way to install JavaFx Runtime. Should others need to install java runtime also need to install JavaFX Runtime Environment? If so, that's hard for others to use javaFX application.

**Comment by edvin** [comment]
A TornadoFX 1 based application requires Java 8 and JavaFX, just like any other JavaFX based application. If you install OpenJDK you will also need to install OpenJFX. For TornadoFX 2, the situation is the same, but Java 13 doesn't include JavaFX, so it must be included with your application.

If you're going to distribute your app to non-developers, you need to wrap it in an installer, or provide clear installation instructions. That's what FXLauncher is for - it allows you to distribute a binary for each platform you want to support, and this binary will make sure to install all required dependencies, like the Java and JavaFX runtimes needed for your app.

**Comment by wuseal** [comment]
@edvin Tks for your detail instruction! Let me research FXLauncher later 😃
