### ISSUE TITLE
openInternalWindow offsets root node, and main-window does not re-render

### ISSUE THREAD

**Issue by EvenAR** [edvin/tornadofx#1115]
Hi! When using `openInternalWindow` in my app, I experience some strange behaviour. Firstly, the view that calls `openInternalWindow` is offset to the top left corner. When i try to resize the window, the background (blue area) does not update - even though I have set `modal = false`. 
Before I run `openInternalWindow`, the background resizes fine.
 
1. initial view
![image](https://user-images.githubusercontent.com/5177099/68341060-ed7c1980-00e7-11ea-8726-2102e8b88057.png)

2. "Open internal window" clicked:
![image](https://user-images.githubusercontent.com/5177099/68341083-f967db80-00e7-11ea-8205-b91678a5c63e.png)

3. Main window resized:
![image](https://user-images.githubusercontent.com/5177099/68341371-988cd300-00e8-11ea-9b77-fdfacc267e13.png)

This is my code:
```kt
import javafx.scene.paint.Color
import tornadofx.*

class InternalWindowTestApp : App(InternalWindowTest::class)

class InternalWindowTest : View("Test-app") {
    override val root = borderpane {
        setPrefSize(400.0, 300.0)
        top(MenuBar::class)
        center(CenterView::class)
    }
}

class MenuBar : View() {
    override val root = menubar {
        menu("File") {
            menu("Connect") {
                item("Facebook")
            }
        }
    }
}

class CenterView : View() {
    override val root = hbox {
        button("Open internal window") {
            action {
                openInternalWindow<MyInternalWindow>(modal = false)
            }
        }
        style {
            backgroundColor += Color.LIGHTBLUE
        }
    }
}

class MyInternalWindow : View("Internal window") {
    override val root = form {
        button("Close") {
            action {
                close()
            }
        }
    }
}
```

If I don't split top and center into two views, the center view stays at the correct place. However, resizing the window still doesn't re-render the background. 
```kt
import javafx.scene.paint.Color
import tornadofx.*

class InternalWindowTestApp : App(InternalWindowTest::class)

class InternalWindowTest : View("Test-app") {
    override val root = borderpane {
        setPrefSize(400.0, 300.0)
        top {
            menubar {
                menu("File") {
                    menu("Connect") {
                        item("Facebook")
                    }
                }
            }
        }
        center {
            hbox {
                button("Open internal window") {
                    action {
                        openInternalWindow<MyInternalWindow>(modal = false)
                    }
                }
                style {
                    backgroundColor += Color.LIGHTBLUE
                }
            }
        }
    }
}

class MyInternalWindow : View("Internal window") {
    override val root = form {
        button("Close") {
            action {
                close()
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/5177099/68342090-21f0d500-00ea-11ea-92a5-229c068ca9a7.png)

**Comment by edvin** [comment]
Hi Even, I confirm that I see the same behavior, and I think I know what's causing it. The way internal window is implemented is kind of hacky, but I believe we'll be able to work around it. Will have a look asap!

**Comment by edvin** [comment]
The issue seems to be that the internal window doesn't know how to deal with borderpanes, or any other parent container where the children aren't merely placed in a child list. Might add specific support for borderpane, or do something smarter.

**Comment by edvin** [comment]
I've fixed part 1 of your issue by making InternalWindow aware of BorderPane, will commit a fix for it momentarily.

**Comment by edvin** [comment]
I was also able to make the node we are covering resize correctly, so I believe this issue is fully resolved. Can you try with the latest snapshot?

**Comment by EvenAR** [comment]
Sorry for the late reply. Works as expected with the latest snapshot. Many thanks, @edvin :)

**Comment by edvin** [comment]
Perfect, thanks for reporting back Even :)
