### ISSUE TITLE
Bug with group and bindChhildren

### ISSUE THREAD

**Issue by kostya05983** [edvin/tornadofx#1118]
Hello, @edvin 
I use group and bindChildren, in FXCollections.observableList I have three elements, but bind only one.
For example:
```kotlin
val test = FXCollections.observableArrayList(
"Test", "Test1", "Test2"
)

override val root: Parent = stackpane {
        group {
          children.bind(test) {
              button("Ttt")
          }
       }
}
```
But if I use flowPane instead of group, all will be ok.
Maybe do I miss something?

**Comment by edvin** [comment]
There is no bug :) `Group` doesn't lay out it's children like most of the other layout containers, but instead rely on you specifically positioning each node. It's simply the wrong layout container for buttons :)

**Comment by kostya05983** [comment]
Thanks for explanation.
