### ISSUE TITLE
Easier navigation of View to Node and Node to View

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#112]
The root Node of a View is connected to that View for the life cycle of the View. To make it easier to navigate between a Node and it's view, and also to find all Views connected to any children under a Node, we need the following functions:

```kotlin
// Find all UIComponents matching the specified type
inline fun <reified T : UIComponent> Parent.findAll(): List<T>
inline fun <reified T : UIComponent> UIComponent.findAll(): List<T>

// Find the first UIComponent matching the specified type
inline fun <reified T : UIComponent> Parent.find(): T?
inline fun <reified T : UIComponent> UIComponent.find(): T?
```

**Comment by edvin** [comment]
A convenienc function to add a view to the root node of another view will also be added:

```kotlin
view1 + view2
```

**Comment by thomasnield** [comment]
Interesting, so is the concept kind of like the [`Storyboard` and `Segue`](https://developer.apple.com/library/ios/recipes/xcode_help-IB_storyboard/Chapters/StoryboardSegue.html) in iOS programming?

**Comment by edvin** [comment]
Not really, this is much simpler, and just gives access to what is already there. But when you mention those things, maybe it's time to look at what can be done with regards to application flow :)

**Comment by thomasnield** [comment]
Application flow might be helpful although this project has somewhat streamlined that already. But formally investigating opportunities might yield something. It would be kind of nice to create established flows from one screen to another...

**Comment by edvin** [comment]
Yes, that's a very commonly asked question. So both embedding Views and switching between Views should be even simpler. Will let this stew and write some documentation in the mean time :)

**Comment by edvin** [comment]
The navigation functions are added. I think maybe we need a custom `Workbench` component that can help further, I have some ideas and will create a separate issue later.
