### ISSUE TITLE
A problem of using task or FxTask

### ISSUE THREAD

**Issue by Stars-One** [edvin/tornadofx#1120]
I meet a problem of using task.

Like this
```
task(null,?){
   ....
}
```
I have learned Java and I am a beginner of kotlin.I don't know how to set the second parameter.

I have to see the document and know its type is a function(`func: FXTask<*>.() -> T`).

could you give me a simple example to use this?

Thanks so much!

**Comment by edvin** [comment]
There is normally no need to call `task` directly. Instead you probably want to just call `runAsync { doSomeWork() } ui { updateResultOnUiThread() }`. You'll find more usage examples in the guide :)

**Comment by Stars-One** [comment]
@edvin 
OK,get it.

I want to create a view about downloading.I want to implement remove the node when the task is finished.

Are there some easy ways to remove the node from VBox or other pane?

**Comment by edvin** [comment]
Yes, just call `Node.removeFromParent()` from the `ui {}` callback :)

**Comment by Stars-One** [comment]
I want to update UI by my bean class.Following code is the implement of javafx.

I would like to accomplish the same function in kotlin.But the method `updateValue` does not exist.How can I accomplish my function?
```
//DownloadingItem is a bean data
Task<DownloadingItem> task = new Task<DownloadingItem>() {
	@Override
	protected DownloadingItem call() throws Exception {
		//downloadData method will return a result
		for (int i = 0; i < 10; i++) {
			DownloadingItem item = downloadData(i);
			updateValue(item);
		}
		return null;
	}

	@Override
	protected void updateValue(DownloadingItem value) {
		//do some operate  of updating UI
	}
};
new Thread(task).start();
```

**Comment by edvin** [comment]
You can call `updateProgress` inside `runAsync`. Also read up on `TaskStatus`: https://edvin.town/tornadofx-runasync-with-taskstatus/

**Comment by Stars-One** [comment]
I saw your course video.It is useful,But there's something special about my situation.

I will get steadily new data by the call of the method named `downloadData()`.The data class that I get has other properties except `title`,`message`,`progress`.

Although I can use the class `Task<T>` and open a thread to Implement my function,I would like to use your way `runAsync` to implement it.

**Comment by edvin** [comment]
If you need to update an observable from a background thread, simply wrap the mutation code in `runLater`, like this:

```kotlin
runAsync {
    while (somestate) {
        doSomeHeavyWork()
        runLater {
            someStateObject.setSomeProperty(v)
        }
    }
}
```

**Comment by Stars-One** [comment]
thanks,it works
