### ISSUE TITLE
onLeftClick and onRightClick not triggering

### ISSUE THREAD

**Issue by drekbour** [edvin/tornadofx#1121]
`onLeftClick` helper relies on method `it.isPrimaryButtonDown()` when it should rather rely on `it.button = MouseButton.PRIMARY`. Ditto `onRightClick`.

https://openjfx.io/javadoc/13/javafx.graphics/javafx/scene/input/MouseEvent.html#isPrimaryButtonDown()

**Comment by edvin** [comment]
Nice catch. I understand the distinction, but I'm curious what situations it actually makes a difference in? Will merge in any case, as your proposed solution is more correct.

**Comment by drekbour** [comment]
IsXButtonDown is usually false after a 'click' event (mouse-down then mouse-up).
I think it's meant for use in the same manner as other modifiers (ctrl, alt etc). I tested this by holding primary button down then clicking the secondary:

Button = RIGHT, isPrimaryButtonDown = true, isSecondaryButtonDown = false

**Comment by edvin** [comment]
Thanks :)
