### ISSUE TITLE
runAsyncWithProgress with nullable return type

### ISSUE THREAD

**Issue by HoldYourWaffle** [edvin/tornadofx#1128]
The `runAsyncWithProgress` function is currently (1.7.19) defined as:

```
fun <T : Any> Node.runAsyncWithProgress(progress: Node, op: () -> T): Task<T>
```

The `Any` bound on `T` prohibits me from using nullable types like `String?`. This is very inconvenient when the operation can have a 'null result' (by being cancelled for example).

I noticed that `runAsync` *does* support nullable values, is there a reason for this difference or is it some kind of oversight? I couldn't find anything in the source code that would cause issues with possibly-null values.

**Comment by edvin** [comment]
I don't believe it would be a problem to allow nullable types. Submit a PR and I'll merge :)
