### ISSUE TITLE
Calling importStylesheet outside of app initilization is a no-op

### ISSUE THREAD

**Issue by radicaled** [edvin/tornadofx#113]
It seems that the only place you can call `importStylesheet` successfully is inside the `init` block of your class that inherits `App`. So, if you try to group your stylesheet imports with your controls (so no control = no stylesheet), nothing seems to happen.

I'm not sure if that's the desired behavior and undocumented, or if it's just a bug.

**Comment by edvin** [comment]
Calling `importStylesheet` will only have impact on any window opened after the import has been called. It would be possible to alter the call so that it pertained to the active View for example. You say you want to group these with your controls, can you give an example?

**Comment by radicaled** [comment]
> Calling importStylesheet will only have impact on any window opened after the import has been called. 

Ahh. Calling it in the init block is probably too late, then.

> You say you want to group these with your controls, can you give an example?

I have a custom `StackList` control, which is basically a list of items, `StackListItem`, with varying indentations.

```
- Folder 1
  - Document 1
  - Document 2   
```

Inside the StackList control my init block looked something like this:

```kotlin
init {
   importStylesheet(Styles.StackList)
   with(root) { /* ... */ }
}
```

Something similar for `StackListItem` occurred as well. My thought was that I could at group styles logically with their usage by controls, and if I never instantiated a control I'd never deal with the style parsing, but I'm not sure if that's a serious performance concern or not.

**Comment by edvin** [comment]
JavaFX already has a mechanism to support styles per control, and it's possible to utilise this even for TornadoFX Type Safe Stylesheets:

```kotlin
class DangerButton : Button("Danger!") {
    init {
        addClass(dangerButton)
    }
    override fun getUserAgentStylesheet() = DangerButtonStyles().base64URL.toExternalForm()
}

class DangerButtonStyles : Stylesheet() {
    companion object {
        val dangerButton by cssclass()
    }

    init {
        select(dangerButton) {
            backgroundInsets = box(0.px)
            fontWeight = FontWeight.BOLD
            fontSize = 20.px
            padding = box(10.px)
        }
    }
}
```

Does this work for you?

**Comment by edvin** [comment]
@thomasnield I added this to the Wiki as well:

https://github.com/edvin/tornadofx/wiki/Type-Safe-CSS#control-specific-stylesheets

If you can tell me where you think it belongs in the guide, I'll try to add it there as well :)

**Comment by edvin** [comment]
This also spawned a related thought:

[Type Safe CSS For plain JavaFX](https://github.com/edvin/tornadofx/issues/115)

**Comment by radicaled** [comment]
Does this work with the live reloading of CSS? If so, it's a good solution!

**Comment by thomasnield** [comment]
Hi @edvin, fortunately I'm close to starting the type-safe CSS chapter. I have a feeling that I'll be getting to it by the end of this week, and minimum I'll need your help to proofread it.

**Comment by edvin** [comment]
Cool @thomasnield - I'm ready :)

@radicaled No I don't think it will work with the reload feature right now, but I'm sure I can make it work :) Will check ASAP and get back to you.

**Comment by edvin** [comment]
Yes, it works as long as you start your app with `--dev-mode` or `--live-views --live-stylesheets` :)
