### ISSUE TITLE
inc and dec operator for numeric property types

### ISSUE THREAD

**Issue by HoldYourWaffle** [edvin/tornadofx#1131]
The numeric property types (`SimpleIntegerProperty`, `SimpleDoubleProperty`) have a bunch of operators defined for them, but `inc` and `dec` are missing.

I would add them myself but I can't figure out what superclass they should be added to. I noticed the other operators were defined as extensions for `IntegerExpression` (and its equivalents), but these functions suddenly return an `IntegerBinding` (or an equivalent).

After fiddling around for a couple of minutes I couldn't get it working, so I decided to just create an issue so someone with more knowledge about this codebase (or bindings for that matter) can pick up.

**Comment by ruckustboom** [comment]
We originally had those functions, but we removed them as it turns out they violate the contract for `inc` and `dec`:

> The `inc()` and `dec()` functions must return a value, which will be assigned to the variable on which the `++` or `--` operation was used. **They shouldn't mutate the object on which the `inc` or `dec` was invoked.**

_Emphasis added_

**Comment by edvin** [comment]
Thanks for the clarification @ruckustboom. I'll close the issue.
