### ISSUE TITLE
cann't see the view that add to vbox after pressing a button

### ISSUE THREAD

**Issue by Stars-One** [edvin/tornadofx#1133]
I make my view named `MyView`,it extends the class named `View`

I want to add a view in the vbox after pressing a button,but it does't work.

I use this way like following code
```
override val root = hbox {
	button("add view"){
		action{
			println("done this")
			this@hobx+=MyView()
		}
	}
}
```
The console prints the message,but my view no show in the interface.

If i use this way,I can see my view
```
override val root = hbox {
	this+=MyView()
}
```
how to solve this problem?

**Comment by edvin** [comment]
`button("add view").action { add<MyView>() }` :)

**Comment by Stars-One** [comment]
well,I try it,it works.
there are some new problems for me.
### first
I want to get the input string from a dialog.
how to build and get the input string from the dialog that has a textfield?
### second
The class `MyView` can acept a string type parameter.how to convery the input string and new the instance of class `MyView`?
### third
I want to use method `runAsync` to start a background task after adding view.what should i do?

**Comment by edvin** [comment]
Please read the guide, I believe everything you ask about is already covered there. Reading it will give you a much better grasp of the framework :) 

https://edvin.gitbooks.io/tornadofx-guide/

**Comment by Stars-One** [comment]
well,I try my best to read the document,but can't find the way to resolve my question.
it is confusing that the main view will refresh when I add a node or view by the action of button which is in the dialog.

like this:
```
class DownloadedView : View("My View") {
    var listView by singleAssign<VBox>()
    override val root = vbox {

        button {
            action {
                dialog {
                    button {
                        action {
                            listView.add(textfield {  })
                            close()
                        }
                    }
                }

            }
        }
        listView = vbox{

        }
    }
}
```
maybe it is the method `close`  cause the question,I think.
