### ISSUE TITLE
data binding when using eBean ORM

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#1140]
using ebean how can i bind itemModelView with model 

```
@Entity
class Person(

):Model(){
    @Id var id:Long=0
    var name:String?=null
    var title :String?=null

    val idProperty = SimpleLongProperty(0)
    val nameProperty = SimpleStringProperty()
    val titleProperty = SimpleStringProperty()

    companion object Find : PersonFinder()
}

class PersonModel():ItemViewModel<Person>(){
    val name= bind {item?.nameProperty  }
    val title=bind {item?.titleProperty  }
}
```
the problem is the data lost and can't binding to model 
it work if i replace
    var name:String?=null
by 
    var name by property<String>()
but by doing that eBean didn't add the column to table

thanks

**Comment by zeljkosh** [comment]
I think you can find solution in the guide Also you can take a look at hibernate example on edvins github. If that does not work take a look at this `https://slar.se/tornadofxexposed-pt-3-adding-editing-and-removing-rows.html`.
it uses jetbains exposed to persist data, but you can get an idea how to solve the issue you are having.

**Comment by mostfa-ayad** [comment]
thak you for responding 
this is work for me 
```
@Entity
class Person(

):Model(){
    @Id var id:Long=0
    var name:String?=null
    var title :String?=null

    companion object Find : PersonFinder()
}

class PersonModel():ItemViewModel<Person>(){
    val name= bind(Person::name)
    val title=bind(Person::title)
}
```

**Comment by zeljkosh** [comment]
Im glad you found solution. You can close the issue now, i think.
cheers
