### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by el1jaC** [edvin/tornadofx#1142]
Is this project alive and can we use it for our software?

**Comment by TheJhonny007** [comment]
If you want to know if a project is alive look at its commit history. The last commit was 12 days ago which means that it is still active.

If you want to use JDK9+ you need to use the snapshot releases from the JDK10 branch.

**Comment by edvin** [comment]
Yeah, the project is absolutely alive. TornadoFX is pretty mature at this point. The biggest outstanding issue is porting to JDK 13+. The work is mostly done, what's missing is simply testing. We have a fully functional 2.0.0-SNAPSHOT release out there, but we need more feedback before releasing 2.0. I myself am quite busy at the moment, but I'll eventually pick up the slack. In the mean time, you shouldn't be afraid to use TornadoFX. I'm here to solve any arising important issues, and there is also a very competent and helpful community around the project.

**Comment by zeljkosh** [comment]
This issue can be closed now i think
