### ISSUE TITLE
Implementing a "slow bind" or "refreshable property" for semi-realtime updates

### ISSUE THREAD

**Issue by HoldYourWaffle** [edvin/tornadofx#1144]
*Disclaimer: this is my first time dealing with JavaFX or Observables in general, so this could be a very stupid question. I'm writing this very late in the evening with English not being my native language, so please bear with me through the couple of inevitable mistakes...*

I'm trying to build a UI that shows the progress of a processing task. There are a couple of variables that represent the progress, like elapsed time, current speed, average speed, etc.
In my original implementation these were `SimpleXProperty`-properties in my model, which I then bound to the labels in my view. However, this approach comes with a very hefty performance cost since these "progress variables" are updated (on the UI-thread) tens of thousands times per second.

I can't slow down these updates (that would slow down the processing itself), so I need a way to slow down the UI-updates. In other words: I need a not-automatically-updated `Binding`: I want to automatically update the values in the UI, but not after every single change.

I don't even remember everything I've tried anymore, but my most promising attempts were messing with the invalidation of a `Binding` (sadly the UI didn't seem update automatically) and using a second "buffer property" like this (pseudo-code):

```kt
var progress = 0;
val progressUI = SimpleIntegerProperty(0);
label.text.bind(progressUI);

runAsync { interestingProcess() } // this updates the 'progress' variable

timeline {
    this += KeyFrame(Duration.ZERO, EventHandler {
        // Synchronization of the UI props
        progressUI.set(progress);
    });

    this += KeyFrame(Duration.seconds(0.2)); // update frequency

    cycleCount = Animation.INDEFINITE;
}
```

Thread-safety issues in this example aside, this approach seems to *work*, but it feels very wrong.
I have to define each property twice (one primitive and one observable) and synchronize them manually in the event handler. This is a lot of boilerplate (especially when dealing with thread-safety) for what I'd think be a not-uncommon use-case.
The use of a timeline (as suggested by [this stackoverflow answer](https://stackoverflow.com/a/9966213/10434371)) for periodic scheduling also feels kindof "backwards", but I can see why it makes sense.

I tried to create a wrapper object to reduce boilerplate, but I ran into problems with the various non-generic (but structurally equivalent) superclasses of the primitive `SimpleXProperty` classes. (For example, both `SimpleIntegerProperty` and `SimpleLongProperty` boil down to a `Property<Number>` instead of their native variants.)

Is there a better way to handle this problem? I feel like I'm missing something very obvious here, since I can't be the first one with this issue. Sadly, after several days of searching I still haven't found a solution.

My latest "hunch" is to use the commit/rollback properties of `ViewModel`, but that doesn't feel right either.
Unfortunately the [guide page](https://edvin.gitbooks.io/tornadofx-guide/part1/11.%20Editing%20Models%20and%20Validation.html) on this topic is kind of confusing to me. To me it looks like everything up to "ItemViewModel" is written as if `PersonModel` extends plain `ViewModel`, but it already extends `ItemViewModel`. Using a plain `ViewModel` is never explained other than that it's used "for more complex situations". The example-code doesn't seem to match up with the text, but maybe that's just me.

**Comment by edvin** [comment]
Don't make this so complicated, just simply update the ui variables once a second. No need to create any elaborate mechanism for this, a simple variable to keep track of the last time you updated is all you need. Wrap the update inside `runLater {}`.

**Comment by HoldYourWaffle** [comment]
There's a high chance I'm too far down the rabbit hole to see the simplicity of your solution, but what would the difference between your proposal and my listed example be?
As far as I can tell the 'ui variables' is the `progressUI` variable in my example and the periodic update (on the event thread) is handled by the timeline. Could you maybe give a (pseudo-code) example?

I really appreciate your help and I'm very sorry if I'm missing something obvious here, I just can't get it to 'click' in my head so to say.

**Comment by edvin** [comment]
You didn't post the code in `interestingProcess()`, but I suspect you're updating `progressUI` all the time. This is bad, as the change will be syncronized on the UI thread. Instead of using yet another UI mechanism to keep track of changes, just make sure you only write to the `progressUI` variable once every 200 ms. This can be done as simple as holding a variable with the value of epoc milliseconds since the last update and checking if the new current vs the last recorded larger than 200 before updating `progressUI` again. When you do, wrap the update in `runLater { }`.

**Comment by ctadlock** [comment]
Yes if you can’t control the rate of data updates then you need to build a process that samples the data and then updates the ui. The problem and solution should not be moved to the ui layer.

Closing
