### ISSUE TITLE
Animating drawer (how drawer works)

### ISSUE THREAD

**Issue by zeljkosh** [edvin/tornadofx#1149]
I am having trouble figuring out how exactly does drawer functions, 

[https://i.imgur.com/fTkpjYv.png](url)

here is an imagine in which i opened drawer with a button in it and the button itself is in a VBox.

My question is , how to animate drawer opening, and is it possible ? I can animate vbox, or button, but the opening of the drawer itself is instant.
Also in scenic view there is "ExpandedDrawerContentArea" and i am not sure what that is, it does not appear to be a node, it just somehow wraps my root node in it.

My question is, is there a way to animate the opening of the drawer ? instead of just popping out, that in slowly opens itself.

**Comment by edvin** [comment]
There is no support for animating the drawer open/close I'm afraid. It wouldn't be too hard to add though.

**Comment by zeljkosh** [comment]
It also uppears the ExpandedDrawerContentArea is of type VBox. 
im closing the issue , thank you
