### ISSUE TITLE
Type safe stylesheets for plain JavaFX (Java)

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#115]
With small modifications we could make the type safe stylesheets available for plain Java based JavaFX applications. The syntax would be something like this:

```java
public class Styles extends Stylesheet {

    public JavaStyles() {
        select("label", s -> {
            s.setBackgroundColor(BLACK);
            s.setFontSize(30);
        });
    }
```

To use the stylesheet, you would need to to initialize the CSS URL Handler and import the stylesheet like this:

```java
public class VanillaApp extends Application {
    public void start(Stage stage) throws Exception {
        // Install URL Handler
        App.installCSSUrlHandler();

        // Create main scene
        Label label = new Label("Hello world");
        Scene scene = new Scene(label);
        stage.setScene(scene);

        // Add the stylesheet
        scene.getStylesheets().add(new Styles().getBase64URL().toExternalForm());

        // Business as usual
        stage.show();
    }
}

```

The string "label" could be replaced with the builtin label cssclass like this:

```java
select(Stylesheet.Companion.getLabel(), s -> {
    s.setBackgroundColor(Color.BLACK);
    s.setFontSize(30, px); // Specify unit is also possible
});
```

To define your own type safe classes (optional, you can use strings if you want), you would do:

```java
public static final CSSClass myForm = new CSSClass("myForm");

select(myForm, s -> {
    s.setBackgroundColor(Color.BLACK);
    s.setFontSize(30);
});
```

This would generate the following stylesheet:

```css
.my-form {
    -fx-background-color: rgba(0, 0, 0, 1);
    -fx-font-size: 30px;
}
```

Documentation here:

https://github.com/edvin/tornadofx/wiki/Type-Safe-CSS

To make this worthwile for Java users we can improve the syntax further so it looks more like the Kotlin alternatives where possible.

What do you think, would there be any interest in this?

**Comment by mikehearn** [comment]
Might be a nice on-ramp. 

You can use @JvmStatic to move things from companion objects to the normal place Java devs would expect to find such things. It makes no difference to the Kotlin side.

**Comment by edvin** [comment]
Yeah, I did that with a couple of functions to try it out, and it seems to work OK. I also needed to add a small functional interface and overload the select functions in CssBlock. Shouldn't interfere with the Kotlin side at all :)

**Comment by edvin** [comment]
A Java dev could also write the stylesheet with the Kotlin syntax, even if the rest of the app is written in plain Java. This step would just require that he or she adds the Kotlin compiler plugin to the build system.

**Comment by edvin** [comment]
After looking at this more closely, we decided that the syntax can be improved a great deal if we fork it and reimplement parts of it for Java. We'll shelve this for now, and get back to it if there is substantial interest. I think this feature can be completed in a couple of days work though.
