### ISSUE TITLE
Stylesheet not applying to button control

### ISSUE THREAD

**Issue by DallasP9124** [edvin/tornadofx#1150]
I have gone through the page on how to apply css classes programmatically by extending the Stylesheet class. The problem I am having, and I'm sure the solution to correct this is simple, is that when applying the stylesheet to the app, like so:

```kotlin
open class MainApp : App() {
    private var mainWindow: MainWindow? = null
    private lateinit var springContext: AnnotationConfigApplicationContext

    init {
        importStylesheet(Styles::class) // <---- HERE
        reloadStylesheetsOnFocus()
    }
    ...
    private fun showMain() {
        try {
            this.mainWindow = springContext.getBean(MainWindow::class.java)
        } catch (e: BeansException) {
            if (mainWindow == null) {
                LOG.error("Failed to instantiate main window.", e)
                stop()
            }
        }
        val stage = Stage()
        stage.title = "Eve Ore Bust"
        stage.scene = Scene(this.mainWindow?.root)
        stage.isMaximized = true
        stage.isResizable = true
        stage.show()
        stage.toFront()
    }
}
```
With my style class:
```kotlin
class Styles : Stylesheet() {

    companion object {
        val navigation by cssclass()
    }

    init {
        navigation {
            button {
                backgroundColor += Color.RED
                textFill = Color.GREEN
                selected {
                    backgroundColor += Color.BLUE
                }
            }
        }
    }
}
```

And attempt to apply the **navigation** reverence to a button:
```kotlin
class NavMenu : View("Navigation View") {

    override var root = vbox()

    private val btnGeneral = button {
        addClass(Styles.navigation) // <---- HERE
        padding = Insets(5.0, 10.0, 5.0, 10.0)
        imageview("/images/icons/gear.png") {
            fitHeight = 25.0
            fitWidth = 25.0
        }
        alignment = Pos.CENTER_LEFT
        useMaxWidth = true
        graphicTextGap = 20.0
        text = "General"
    }

    init {
        with(root) {
            maxWidth = 150.0
            minWidth = 150.0
            add(btnGeneral)
    }
}
```

The style does not get applied to the button. However, the style properties will display when I apply those style properties directly in the button body.

The **NavMenu** is being added to my main view by:
```kotlin
@Component
class MainWindow @Autowired constructor(
    private val viewModel: MainWindowViewModel
) : View("Main Window") {
    override val root = vbox()

    @PostConstruct
    fun postConstruct() {
        ...
        with(root) {
            ...
            gridpane {
                visibleWhen { loggedIn }
                row {
                    constraintsForRow(0).apply {
                         percentHeight = 100.0
                    }
                    add(NavMenu()) // <---- HERE
                }
            }
        }
    }
}
```

**Comment by edvin** [comment]
In your MainApp class you're manually creating a stage and showing it, completely bypassing the TornadoFX lifecycle. Imported styles are automatically applied to TornadoFX managed stages, and will naturally not affect anything you do outside the framework. The approach you're taking here suggests that you haven't read the guide or seen much TornadoFX examples. I strongly suggest you start with the guide :)

Half the code in your example is not necessary, and you're severely over complicating things/using bad practices like manually instantiating Views, not using builders, using outdated/wrong syntax. Not sure how you came up with all this, but please please please start with the guide or ask for help in the Slack channel perhaps. Sorry for being harsh, but this hurts my eyes :)

**Comment by DallasP9124** [comment]
I have read through the guide plenty, I am just used to other paradigms of development and am not used to fluid methodologies like TFX. I only instantiated one view, most of this syntax was taken from examples I have found all over and honestly don't see what is so wrong with it. The MainApp does what it does because I wanted a splash screen but found no easy way to do it the way I needed it to using the TFX lifecycle.
Hardly any of the code has kdocs so going to a guide that has the minimal material isn't as helpful as you think it is so cut me some slack. And what is so outdated or wrong about the syntax anyway?

**Comment by edvin** [comment]
Give me some time and I'll go through your examples and highlight the issues I see (hopefully later today), and explain what should be done differently. Almost every line in your code examples are sub optimal, except for the stylesheet which looks fine :) I figured you hadn't looked much at the guide since it shouldn't contain any code like this and on the contrary provides plenty of best practice examples.

**Comment by DallasP9124** [comment]
Ok I would appreciate that. I went back through a lot of what I had and just stripped out all the Spring autowire stuff and replaced with **di()** and **inject()**. It took me a while to grasp the separation of Spring DI and TFX DI, at least the injection and supply part. I got the stylesheet to apply after that and was able to see where I messed up.

If possible, do you think you could an example of how to do splash screens using TFX in your guide?

**Comment by edvin** [comment]
Sorry for not getting back to you, things are a bit crazy for me time wise :) Yes, I could do that. Is your use case that you need to do some heavy initialization before you can show the user interface, and you want to show either progress or a "please wait" screen that shows while the initialization completes?

**Comment by edvin** [comment]
PS: You might find the login screen example interesting: https://www.youtube.com/watch?v=Jyuf4xn0oy4

Probably not exactly what you're looking for, but it might give you some pointers :)

**Comment by DallasP9124** [comment]
No problem, I totally get it. Essentially just that yes. Lots of data checks, pulling, updating, etc. The splash screen concept I think is what drew me away from starting things up correctly because I was migrating from **Java+JavaFx** to **Kotlin+TFX**. Ill take a look at ^, thank you!

Sorry for another request lol but would it be possible to put a *disclaimer* or *important* note in regards to the stylesheet part of the guide and how the view(s) **must** be part of TFX lifecycle, ie. not manually created? Unless you think it is very obvious already and I wasn't paying attention haha. 

Other than all that I think you can close this issue! I think I am getting the concepts understood now and I got the stylesheet to apply!

**Comment by edvin** [comment]
Sweet! I want to quickly mention that JavaFX has a splash-screen mechanism built in, but that's mostly to be able to show a screen while the platform itself is loading. Nowadays that's so fast, so I wouldn't bother with that, but instead use the TornadoFX ways of loading and showing views.

A nice decoupled way of showing a splash screen would be to set the splash screen as the main view of the app, then subscribe to an event which the controller can emit when it's done loading. The splash view can then either close and show the real main view, or replace itself with it and force a resize. If you don't want to look into the EventBus at this stage, you can also observe a property which is exposed in a ViewModel so that the controller can update that when init is done.

An _important_ note is a good idea - tell you what, why don't you try to pull the guide-project, make the change and submit a PR? You might run into other situations where you feel that the guide is lacking as well, so you can check in here and then update the guide with your findings perhaps? Any help is greatly appreciated!

**Comment by edvin** [comment]
The concept I'm talking about would look like this:

```kotlin
class MyApp : App(Splash::class, Styles::class) {
    val initController: InitController by inject()

    override fun start(stage: Stage) {
        super.start(stage)
        initController.doHeavyInitWork()
    }
}

object InitComplete : FXEvent()

class InitController : Controller() {
    fun doHeavyInitWork() {
        runAsync {
            println("I'm just procrastinating...")
            Thread.sleep(5000)
        } ui {
            fire(InitComplete)
        }
    }
}

class Splash : View("Please wait...") {
    override val root = stackpane {
        label(title)
    }

    override fun onDock() {
        subscribe<InitComplete> {
            close()
            find<MainView>().openWindow()
        }
    }
}

class MainView : View("Welcome") {
    override val root = stackpane {
        label("You're logged in!")
    }

    override fun onDock() {
        currentStage?.requestFocus()
    }
}
```

That's a complete runnable example (except for the stylesheet) with a very minimalistic UI :) Please ask if any of the code is unclear of if you have any questions about how/why this works.

**Comment by DallasP9124** [comment]
The example is perfect! I can easily incorporate that into my current setup, thank you! And yes I will pull the docs and just makes some PR's where I think it could help. I enjoy writing documentation! Thanks for all your help @edvin!

**Comment by edvin** [comment]
Thank you, Dallas :) I'm closing the issue for now. Will be good to get some fresh eyes on the guide!
