### ISSUE TITLE
Views for drawer

### ISSUE THREAD

**Issue by bykka** [edvin/tornadofx#1155]
Hi, how to extract a drawer item to the separated class?
I would like to have something like this
```
with(leftDrawer) {
    item("Users") {
         UsersView()
    }
}
```

**Comment by Evgen25176542** [comment]
Do you want to extract a view ?
```
class MainView : View() {
    private val subView: SubView by inject()

    override val root =  drawer {
        item("Backup Tasks") {
            this += subView
        }
    }
}
```

**Comment by bykka** [comment]
Thank you, works like a charm

**Comment by edvin** [comment]
If you don't need a reference to the View in the calling class you would simply do:

```kotlin
drawer { 
   item<UsersView>()
}
```

The title for the drawer is automatically picked up from the UsersView.
