### ISSUE TITLE
New release of tornadofx

### ISSUE THREAD

**Issue by AlbRoehm** [edvin/tornadofx#1156]
Hey, I wanted to ask if it's possible to make a new release with the latest changes to the main branch. I'm currently using the 1.7.20 snapshot, which has some nice fixes and stuff, but it would really be too nice to have a non-modifying version instead of a snapshot.

**Comment by edvin** [comment]
Absolutely, 1.7.20 will be in Maven Central within the hour :) Will perform the release procedure on GitHub tonight.

**Comment by AlbRoehm** [comment]
Thanks for fast response. I really appreciate your work.

**Comment by edvin** [comment]
My pleasure :) Thanks for your feedback!
