### ISSUE TITLE
vertical cell border is gone when formatting a tableview cell with cellFormat()

### ISSUE THREAD

**Issue by Albert1001** [edvin/tornadofx#1157]
I encountered a strange issue when formatting a tableview cell with cellFormat(). The column borders of empty rows are missing. As illustrated in the following image, the vertical borders between column ID and Name of rows 5, 6, 7 are missing. 
![image](https://user-images.githubusercontent.com/12740728/73719650-046bef80-475b-11ea-8a36-b3346e1ff4bb.png)

The source code of the view is also quoted below. 

```kotlin
class HelloWorld : View() {
    private val persons = listOf(
            Person(101,"Samantha Stuart",LocalDate.of(1981,12,4)),
            Person(102,"Tom Marks",LocalDate.of(2001,1,23)),
            Person(103,"Stuart Gills",LocalDate.of(1989,5,23)),
            Person(104,"Nicole Williams",LocalDate.of(1998,8,11))
    ).asObservable()

    override val root = vbox{
        tableview(persons) {
            readonlyColumn("ID",Person::id) {
                cellFormat{
                    text = "0x%x".format(it)
                }
            }
            readonlyColumn("Name", Person::name)
            readonlyColumn("Birthday", Person::birthday)
            readonlyColumn("Age",Person::age)
        }
    }
}
```
Is there anything wrong with it? Thanks a lot.

**Comment by edvin** [comment]
Thanks for reporting this. I've committed a fix now, it's available in 1.7.21-SNAPSHOT :)
