### ISSUE TITLE
[FxRecyclerView]a better way to complish a list of many tasks,like download list

### ISSUE THREAD

**Issue by Stars-One** [edvin/tornadofx#1158]
[FxRecyclerView](https://github.com/Stars-One/FxRecyclerView)

hello edvin,I create a view named FxRecyclerView and based in the scroll pane.

It can easily to add a view to a view.

I want to add it to your project,but it is failed when I build your tornadofx project.

I don't know this view is good or bad,so please tell me your suggestion when you read the readme of my view.

I would provide you a soure code which has english comment if you think FxRecyclerView is not bad.And you can put it in your tornadofx project.

Thanks.

**Comment by ctadlock** [comment]
I dont think application specific views should be included in the framework project. Glad you are building with tornadofx though!
