### ISSUE TITLE
2.0.0-SNAPSHOT: Cannot access class 'javafx.concurrent.Task'

### ISSUE THREAD

**Issue by adstotz** [edvin/tornadofx#1159]
Just tried updating to JDK 11, JFX 11, and TornadoFX 2.0.0-SNAPSHOT. After upgrading my gradle.build file, including the JFX Gradle Plugin, and adding the following modules:
```
javafx {
        version = '11'
        modules = [ 'javafx.base', 'javafx.controls', 'javafx.graphics', 'javafx.swing' ]
}
```
I'm getting the following exception:
> Cannot access class 'javafx.concurrent.Task'. Check your module classpath for missing or conflicting dependencies.

This occurs on a line of code calling `runAsync{}`.

Is this a bug in the upcoming JFX11 support?

**Comment by edvin** [comment]
It seems like JavaFX isn't on your classpath. Double check the resolved classpath to see if that's the case. PS: You might as well go for Java 13 and JavaFX 13.

**Comment by ctadlock** [comment]
Closing; likely user issue.

**Comment by adstotz** [comment]
Yes, it was an issue with my hierarchical build files. Sorry, forgot to report back to this thread. TornadoFX 2 is working well for me so far. Kudos to the team supporting this. It's a great package.
