### ISSUE TITLE
Please, please use monospace font at the main webpage

### ISSUE THREAD

**Issue by vlsi** [edvin/tornadofx#1167]
I mean the following sample at https://tornadofx.io

Can you please use monospace font?
It would be super cool if you used [JetBrains Mono font](https://www.jetbrains.com/lp/mono/)

PS. My wild guess would be the screenshot comes from Google Presentations, and if you are using Google Presentations to display code, it can use a monospace font, however, it is not set by default.

<img src="https://tornadofx.io/img/forms-sample.png">

**Comment by edvin** [comment]
Done, thanks for the tip!

**Comment by edvin** [comment]
Btw, the screenshot is just snipped right out of IntelliJ IDEA :)

**Comment by vlsi** [comment]
Thanks for the quick fix, however,

a) The image looks blurry (macOS, retina) :-/  You might want to use https://plugins.jetbrains.com/plugin/9406-code-screenshots for taking high-resolution screenshots.
b) Code formatting looks a little bit odd: there's double space after `root` in `val root  = form {`
c) `LoginForm` is marked as "unused" (gray) by IDEA. It would probably make sense to mark it used for the purpose of the screenshot :)

**Comment by edvin** [comment]
The plugin won't include the screenshot of the actual app, and I'm a bit pressed for time. If you have time to embed the app in the code screenshot I'd be very grateful :)

<img width="1374" alt="code-sample" src="https://user-images.githubusercontent.com/977035/74642980-4726c200-5174-11ea-8bca-4cda3885a250.png">

Code needed to generate screenshot:

```kotlin
import tornadofx.*
import javafx.beans.property.SimpleStringProperty
import javafx.geometry.Orientation.VERTICAL

class User {
    val usernameProperty = SimpleStringProperty()
    var username by usernameProperty

    val passwordProperty = SimpleStringProperty()
    var password by passwordProperty
}

class UserModel : ItemViewModel<User>() {
    val username = bind(User::usernameProperty)
    val password = bind(User::passwordProperty)

    fun login() {

    }
}

val x = LoginForm()

class LoginForm : View("Login") {
    val user = UserModel()

    override val root = form {
        fieldset(title, labelPosition = VERTICAL) {
            field("Username") {
                textfield(user.username).required()
            }
            field("Password") {
                passwordfield(user.password).required()
            }
            buttonbar {
                button("Log in") {
                    isDefaultButton = true
                    enableWhen(user.valid)
                    action { user.login() }
                }
            }
        }
    }
}
```

I manually dragged the window to the left to reposition the validation popup after first filling both fields, then deleting the username.
