### ISSUE TITLE
CSS Box with Optional Sides

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#117]
I noticed in the `CSS.kt` file that all arguments for a `CssBox<T>` are required for all four sides. Perhaps we can make them optional when we only want to style one or some of the sides? 

```kotlin
open class CssBox<T>(val top: T, val right: T, val bottom: T, val left: T) {
    override fun toString() = "${toCss(top)} ${toCss(right)} ${toCss(bottom)} ${toCss(left)}"
}
```

**Comment by edvin** [comment]
I think @t-boom already mentioned this on Slack, but I'll reiterate here for completeness:

`CssBox` should never be instantiated. There are overloaded versions of the `box` function to support this:

```kotlin
fun <T> box(all: T) = CssBox(all, all, all, all)
fun <T> box(vertical: T, horizontal: T) = CssBox(vertical, horizontal, vertical, horizontal)
fun <T> box(top: T, right: T, bottom: T, left: T) = CssBox(top, right, bottom, left)
```

**Comment by thomasnield** [comment]
Okay no more problem. I'm going to go through CSS source code today and start understanding its internals a little better while I document it.

**Comment by edvin** [comment]
Ask if you get stuck. Some of it is a bit intricate!

**Comment by thomasnield** [comment]
I have noticed that. I'll let you know when I do!
