### ISSUE TITLE
NPE when trying get recourse if no resource with this name is found

### ISSUE THREAD

**Issue by ZebanNikolay** [edvin/tornadofx#1170]
I use this function 
```kotlin
class ResourceLookup(val component: Any) {
    operator fun get(resource: String): String = component.javaClass.getResource(resource).toExternalForm()
    ...
}
```
Because `getResource(String name)` function may return null, I may get NPE
```java
     /** @return      A  {@link java.net.URL} object or {@code null} if no
     *              resource with this name is found
     */
    public java.net.URL getResource(String name)
```
And also should be changed return type in the same functions for example
`fun url(resource: String): URL`  -> `fun url(resource: String): URL?`

**Comment by edvin** [comment]
This was done to make the code nicer to work with. It would be possible to create a ResourceLookup subclass that returns nullable values if you want/need to deal with that, but resources on the classpath seldom/never change as your app is running, so an NPE here can be seen as a bug - either you supplied the wrong filename or you didn't supply the file :)

**Comment by ZebanNikolay** [comment]
Ok, It’s strange to me, because I don’t expect this behavior (I expect the same behavior like JavaFX provides) and there isn’t any documentation which tells me that. Anyway I get your point so I'll close this issue ))
