### ISSUE TITLE
Can not bind multiple css with bindClass

### ISSUE THREAD

**Issue by jihun-bang** [edvin/tornadofx#1171]
Currently bindClass can only bind one CssRule.

example.

// Stylesheet
class ButtonStyles : Stylesheet() {
    companion object {
        val on by cssclass()
        val off by cssclass()
        val green by cssclass()
    }
}

//button
with(btn) {
    bindClass(ButtonStyles.on)
}

I want to use on style and green style at the same time as binding.
Please tell me how.

**Comment by edvin** [comment]
You can repeat `bindClass` several times:

val state = SimpleObjectProperty(ButtonStyles.on)
val color = SimpleObjectProperty(ButtonStyles.green)

```kotlin
button {
  bindClass(state)
  bindClass(color)
}
```

Now you can change the value of the properties and the styles will update.
