### ISSUE TITLE
How to undock all views from a workspace?

### ISSUE THREAD

**Issue by SKeeneCode** [edvin/tornadofx#1179]
As the title asks; is there a way to undock all currently docked views in a workspace?

**Comment by edvin** [comment]
The workspace only has a single docked view at a time. I don't think we added support for having no view docked, so I guess the simplest would be to create a blank view and dock there if you want to remove the current one.

**Comment by SKeeneCode** [comment]
Oh I haven't been clear enough with my question or myself. I realized I meant to close all tabs of a workspace in tabs navigation mode. Then I remembered it is straight forward enough with a clear() call. I'll close this xd
