### ISSUE TITLE
Allow repeated styles

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#118]
Several selectors in JavaFX CSS can take repeated values, such as backgrounds and borders. Currently, most of those selectors can only accept a single value in the CSS DSL. This should be fixed.

I'm not sure how high priority this fix is. I'm putting this task in so we can get around to it eventually.

**Comment by edvin** [comment]
Since we use properties, we can't use varargs to support this I believe. We would either have to break backwards compatibility or introduce a new property for arrays of values, like `backgroundColors` or something. It's a bit unfortunate, but I don't know of another way to evolve into this. What about you, any idea as to what would be the best way to implement it?

**Comment by t-boom** [comment]
Creating new properties would probably be the easiest, but I would actually prefer something that feels a little cleaner (though it would break backwards compatibility).

I would love to be able to use some sort of union type, but I'm not sure the best way to do that in Kotlin. What I'm thinking is something like creating a type `PossiblePlural<T> = T|List<T>` and then using something like `var backgroundColor: PossiblePlural<Paint> by cssprop("-fx-background-color")`. `backgroundColor` could then accept both `c("red", 0.75)` and `listOf(c("red", 0.75), c("green", 0.95), c("blue"))`.

**Comment by t-boom** [comment]
We could also always require a list for all those properties. That would break backwards compatibility and would make the user always define a list, which could be annoying considering the most common use case is to only add a single item, but it would fit into the Kotlin idea of making everything explicit.

**Comment by edvin** [comment]
Sadly there is no union types in Kotlin. There is however another crazy possibility. Take background for example, which is of type `javafx.scene.paint.Paint`. Paint is actually an abstract class, so we could create a MultiPaint subtype that would hold a list of Paint objects. Then we'd just check if `background is MultiPaint` and unwrap it when generating the stylesheet. To assign it, we'd have to do something like:

```kotlin
// Single
background = Color.RED

// Multiple
background = multi(Color.RED, Color.BLUE, Color.GREEN)
```

**Comment by edvin** [comment]
We could maybe use an operator function instead of the `multi` function name.

**Comment by t-boom** [comment]
That would work for the background color, but what about for borders, margins, padding, etc? That could grow to a fair amount of code.

**Comment by edvin** [comment]
We could introduse an interface with a type parameter and put the code there. Wouldn't add much weight I think, just some subclasses with no code.

**Comment by t-boom** [comment]
That's probably true

**Comment by edvin** [comment]
Let's try it and see how it goes :) I will give it a go later today.

**Comment by thomasnield** [comment]
Sorry guys I am finally catching up with this. As stated earlier I'm a bit of a pragmatist too who hasn't done much CSS. 

What would be the effect of giving multiple colors to the background? Will it blend the colors? That just seems odd JavaFX would allow this rather than just specifying the exact color you're trying to get.

Where else would this pattern be used?

**Comment by edvin** [comment]
You can also set one or more values for backgroundInsets, so that you can create an object hat has multiple colored borders, and then finally the last color for the rest of the background :)

**Comment by edvin** [comment]
It is explained in some detail here:

https://jojorabbitjavafxblog.wordpress.com/2011/07/11/javafx-2-0-css-styling-part-1/

**Comment by edvin** [comment]
Try this code:

```kotlin
class TestView : View() {
    override val root = HBox()

    init {
        root.style {
            backgroundColor = multi(Color.YELLOW, Color.BLUE, Color.RED)
            backgroundInsets = multi(box(10.px), box(20.px), box(30.px))
        }
    }
}
```

**Comment by thomasnield** [comment]
Ah I think I'm starting to see. Logging in to play with this right now

**Comment by thomasnield** [comment]
Okay I get. Thanks. Didn't know you could do that. I'll hold off documenting that stuff until you all are happy with it. There's probably a lot of CSS functionality that would be hard to cover comprehensively. I might put stuff like this in the Appendix.

**Comment by edvin** [comment]
I don't think we need to cover every css property, but if we settle on this syntax we need to tell users that properties that accepts multiple values can be assigned a single value using `prop += value` and multiple values using `prop = multi(value1, value2)`. Let's hear what @t-boom has to say about the syntax first :)

**Comment by thomasnield** [comment]
okay sounds good. Btw I'm having some complications with this. Switch over to Slack to see what I'm trying to reconcile with the new snapshot.

**Comment by edvin** [comment]
Done :)

**Comment by edvin** [comment]
@t-boom Are you happy with this? Should we for this approach and close the ticket?

**Comment by t-boom** [comment]
Yeah, looks good to me. Good job by the way. It ended up much cleaner than I expected.

**Comment by edvin** [comment]
Cool! Closing :)
