### ISSUE TITLE
Add EventListener reference to onChange 's lambda argument

### ISSUE THREAD

**Issue by cpdyj** [edvin/tornadofx#1181]
Focus this declartion: `addListener(ChangeListener<? super T> listener);`
Because Kotlin SAM has no way to get lambda object(in this scene is `ChangeListener`).
And looks they don't want to make any change(Ref: [Is “this” accessible in SAMs? - Language Design](https://discuss.kotlinlang.org/t/is-this-accessible-in-sams/1477/3)).
The best way is add a parameter to `onChange`'s return value or add to it's lambda's parameter?

Thank you.

**Comment by SchweinchenFuntik** [comment]
```
val observableList = observableListOf<String>()
observableList.addListener(ListChangeListener { event -> 
    // code
 })
```

**Comment by cpdyj** [comment]
Thank you for your reply, I found method like this. But I think maybe we
can use a better way to do it.

在 2020/3/11 21:46, Funtik 写道:
