### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by Broeckelmann** [edvin/tornadofx#1182]
https://edvin.gitbooks.io/tornadofx-guide/part1/12.%20TornadoFX%20IDEA%20Plugin.html is the 12 topic, but says 13 in the title ;)

**Comment by Broeckelmann** [comment]
Also in https://edvin.gitbooks.io/tornadofx-guide/part1/7.%20Layouts%20and%20Menus.html at the end is maybe an unfinished TODO.

**Comment by SchweinchenFuntik** [comment]
more correct to create there: [guide](https://github.com/edvin/tornadofx-guide)

**Comment by edvin** [comment]
If you have time, please submit a PR :)

**Comment by Broeckelmann** [comment]
Sorry was away, i created a PR for the typo. But I don't know about the TODO I'm just starting out, really nice project btw :+1:
