### ISSUE TITLE
readonlycolumn and internal classes

### ISSUE THREAD

**Issue by ayedo** [edvin/tornadofx#1184]
First of all: thank you for your great work on tornadofx. I have enjoyed working with the library so far!

I've defined `internal classes`, and want to use them together with readonlycolumns. The columns are shown correctly, but the sorting is broken.

```
inline class ProcessId(val value: Int)

data class PortBinding(val proccessId: ProcessId, ....)

readonlyColumn("Process", PortBinding::processId).cellFormat {
    text = it.value.toString()
}
```

How can I set the type for this column to Int? Currently I'm using a workaround: I created an Int property just for this call to type the column correctly to Int. I have the feeling there must be a more elegant solution to this.

Does anyone have experience with this?

**Comment by SchweinchenFuntik** [comment]
if you have problems with sorting (if you understand correctly), then the inline class should implement the comparator, you must also understand that boxing will most likely be there, which is not good

**Comment by ayedo** [comment]
thank you for your help! it worked :)
