### ISSUE TITLE
TornadoFX Guide link is down

### ISSUE THREAD

**Issue by Zhuinden** [edvin/tornadofx#1190]
https://edvin.gitbooks.io/tornadofx-guide/ <-- inaccessible

**Comment by edvin** [comment]
It's working good for me, tested both yesterday and today.

**Comment by TuringTux** [comment]
Also inaccessible for me (and I have been able to access it in the past). Additionally, it seems like all other gitbooks.io sites are down as well (I've tested a handful random sites).

I think they are using Cloudflare, maybe it's a Cloudflare problem?

**Comment by edvin** [comment]
Seems like there is some kind of network issue somewhere. Good call on just using the sources of the guide. You could even just pull them down and work with them locally, nice to have everything searchable from within IntelliJ even :)

**Comment by TuringTux** [comment]
Thanks for the suggestion - I've pulled the sources and think I'll have a quick look around whether there are some automatic markdown rendering and linking tools. Be right back, building the documentation from scratch today :smile:

**Comment by edvin** [comment]
I believe IntelliJ has a built in Markdown viewer, or it's a plugin at least :) Handy to have it locally in case you find spelling errors or want to amend anything. PRs are most welcome!

**Comment by TuringTux** [comment]
> I'll have a quick look around whether there are some automatic markdown rendering and linking tools.

I actually found a nice working alternative called [mdBook](https://github.com/rust-lang/mdBook):

1. Install mdBook
2. Use `$ mdbook init` to create a new book (actually, we only need the generated `book.toml`)
3. Execute `$ rm -r src` to remove the source directory
4. Clone the Guide repo to be the new `src` directory (`$ git clone https://github.com/edvin/tornadofx.git src`)
5. Adjust `SUMMARY.md` - mdBook doesn't seem to like the file names containing spaces, so I came up with the following hack: Open `SUMMARY.md` and replace all the matches of the regex `\((.*) (.*)\)` with `($1%20$2)` (you have to do this multiple times). This will replace all spaces in the link paths with the URL escape `%20`.
6. Execute `$ mdbook build`
7. The `book` directory now contains a working build of the guide

**Comment by TuringTux** [comment]
@edvin Would it be possible to rename the guide files from e.g. `12. TornadoFX IDEA Plugin.md` to `12._TornadoFX_IDEA_Plugin.md` (and update the links) to remove the spaces problem?  If yes, I'd be happy to do so, because then mdBook would work as well.

Or would this break the GitBooks renderer?

**Comment by bykka** [comment]
Have the same issue in Norway(Stavanger). The Internet provider is Lyse.

**Comment by TuringTux** [comment]
Still not working for me either. And not limited to the TornadoFX guide, as it seems.
Maybe someone should contact GitBooks?

**Comment by edvin** [comment]
Can you guys check if you can reach the guide at https://docs.tornadofx.io/?

**Comment by Zhuinden** [comment]
Yes, this works for me

**Comment by vitalyzhakov** [comment]
@edvin , hello!
Thanks for you work!

May be close this issue, as PR was merged?
