### ISSUE TITLE
ClassCastException in saving config 

### ISSUE THREAD

**Issue by Stars-One** [edvin/tornadofx#1191]
I use the config to save some data,but it throw a ClassCastException.
```
config["flag"] = true
config.save()
```

**Show the exception:**
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at java.util.Properties.store0(Properties.java:834)
	at java.util.Properties.store(Properties.java:818)
	at tornadofx.ConfigProperties.save(Component.kt:81)
	at com.starsone.demo.view.MainView$root$1$1.invoke(MainView.kt:10)
	at com.starsone.demo.view.MainView$root$1$1.invoke(MainView.kt:5)
	at tornadofx.ControlsKt.label(Controls.kt:838)
	at tornadofx.ControlsKt.label$default(Controls.kt:312)
```

well,it is a so small bug,but I think you should do the cast operation in your tornadofx rather than let user to do the cast operation,like this

```
config["flag"] = true.toString()
config.save()
```

**Comment by edvin** [comment]
The `config` object has built in converters, please use `config.boolean("flag", true)`. The `config` object extends `java.util.Properties`, which in turn extends `Hashtable<Object,Object>`, so it's still possible to shoot yourself in the foot in all the ways enabled by the classes we extend :)

**Comment by Stars-One** [comment]
> The `config` object has built in converters, please use `config.boolean("flag", true)`. The `config` object extends `java.util.Properties`, which in turn extends `Hashtable<Object,Object>`, so it's still possible to shoot yourself in the foot in all the ways enabled by the classes we extend :)

it does't work,I found the properties file not have the key and value.It only has the comment.

**Comment by SchweinchenFuntik** [comment]
Myself ran into this problem, I wanted to prepare a PR, maybe next week I will do it

**Comment by edvin** [comment]
Aha :) Thanks, reopened it now :) Should be easy to implement for the supported data types.

**Comment by SchweinchenFuntik** [comment]
solution:

```
operator fun Configurable.set(key: String, value: Boolean) { this[key] = value.toString() }
operator fun Configurable.set(key: String, value: Int) { this[key] = value.toString() }
// ....primirtive types

// here you need to look at https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Component.kt#L71
operator fun Configurable.set(key: String, value: Any) { this[key] = value.toString() }
```

**Comment by edvin** [comment]
There is no need to create extension functions when we have the actual class available :)

**Comment by SchweinchenFuntik** [comment]
@edvin you will merge the changes into the master, or should I make a separate PR

**Comment by edvin** [comment]
Could you make a PR? Sorry to bother you with this, don't have much computer time these days

**Comment by SchweinchenFuntik** [comment]
no problem, but a little later
