### ISSUE TITLE
TornadoFx Reload apps from controller

### ISSUE THREAD

**Issue by arvinrasheda** [edvin/tornadofx#1194]
excuse me I want to ask, how do I reload the Tornadofx app from the controller?

**Comment by SchweinchenFuntik** [comment]
this is not a trivial job, what kind of application restart do you need? If only JavaFX runtime is already easier. If you need to reset states, then `Scope` will probably help here.

**Comment by arvinrasheda** [comment]
I see, I just want to reset the state when the conditions are logged out. but i tried several ways in java fx it didn't work

**Comment by edvin** [comment]
Use ItemViewModel and store state in that. Easy to rollback to defaults also.

**Comment by ctadlock** [comment]
^ that will work. 

Another solution GoToTags uses is to have a bootstrap app that loads your jar; this is often needed anyways. What we do is the the Java app returns a special process exit code (1000) and the wrapping app listens for that exit code and if it sees 1000, it restarts the app. In our case that app is written in .NET.

**Comment by ctadlock** [comment]
Closing as answered.

**Comment by arvinrasheda** [comment]
> ^ that will work.
> 
> Another solution GoToTags uses is to have a bootstrap app that loads your jar; this is often needed anyways. What we do is the the Java app returns a special process exit code (1000) and the wrapping app listens for that exit code and if it sees 1000, it restarts the app. In our case that app is written in .NET.

thanks btw
