### ISSUE TITLE
How to prevent onChange being re-applied many times when removing/adding an item in ListView?

### ISSUE THREAD

**Issue by SKeeneCode** [edvin/tornadofx#1197]
So I have a listview and I've been trying to sort it alphabetically, as well as have it update and rearrange itself when one of its items is edited (So changing a "aaa" to "zzz" should move it immediately down the list)

Firstly I discovered I need to call `ListView::refresh` for the change in the name to appear, so I bind that to the name property as you can see below.

```
    private fun createPageTagListView(listToObserve: ObservableList<TagModel>): ListView<TagModel> {
        return listview(listToObserve) {
            this.items.sorted(Comparator.comparing<TagModel, String> { it.name })
            cellFormat {
                graphic = HBox().apply {
                    alignment = Pos.CENTER
                    label(it.name)
                }
                it.nameProperty.onChange {
                    println("test")
                    listView.refresh()
                }
            }
        }
    }
```

Now the problem is getting the listview re-organizing itself to remain in alphabetical order, as while the cell will reflect the name change the position in the list will not. Unless I am mistaken I've found I am required to remove and re-add the item from the list the listview is using for it to be repopulated correctly in the right order. So if I do this:

```
            cellFormat {
                val model = it
                graphic = HBox().apply {
                    label(model.name)
                }
                model.nameProperty.onChange {
                    listToObserve.remove(model)
                    listToObserve.add(model)
                    // we lost selection when removing
                    listView.selectionModel.select(model)
                    listView.refresh()
                }
            }
```

This works but by adding a print statement to the onChange listener it seems the onChange is re-added and is triggered by subsequent edits. This clearly is causing a run-away effect and after changing the item only a few times it's been triggered thousands of times, freezing my app.

The question is, how can I ensure the nameProperty contains only one, the same onChange listener even when it is re-added? This is probably something simple but I am scratching my head here!

**Comment by ruckustboom** [comment]
You should use a `FilteredList` wrapper around the base `ObservableList`. You should not be filtering the list manually.

**Comment by SchweinchenFuntik** [comment]
```
val sortedList = this.items.sorted(Comparator.comparing<TagModel, String> { it.name })
sortedList += newItem
```

**Comment by SKeeneCode** [comment]
> ```
> val sortedList = this.items.sorted(Comparator.comparing<TagModel, String> { it.name })
> sortedList += newItem
> ```

Will changing `it.name` here trigger the sorted list to reorder itself? I've been finding that the predicates for sorted/filtered lists only are checked when an item is added, not the item being modified itself.

**Comment by SKeeneCode** [comment]
A bit of googlefu and I believe I have found my answer here: https://stackoverflow.com/questions/27806814/javafx-sortedlist-listen-the-list-changes-and-the-list-items-updated-event

**Comment by ruckustboom** [comment]
Yep, that link answers your question nicely. To sum it up, you would create the underlying list with an extractor (so you'll need the name to be a JavaFX Property), then wrap it (the list) in a `SortedList` and assign the sorted list to the `ListView`, and JavaFX should handle the rest for you.

**Comment by SKeeneCode** [comment]
Thanks @ruckustboom , closing this now!
