### ISSUE TITLE
how to set the css style with percent value,like 50%

### ISSUE THREAD

**Issue by Stars-One** [edvin/tornadofx#1199]
I want to add a circle background to a button,I use the css style,like this
```
fx-background-radius:50%
```
And now I can use this in type css builder
```
backgroundRadius+= box(5.px)
```
And I want to input a percent value,how to do?

**Comment by edvin** [comment]
```kotlin
box(50.percent)
````

 :)

**Comment by Stars-One** [comment]
Copy that!Thanks.
