### ISSUE TITLE
More elegant builders/extension functions for GridPane?

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#12]
Really liking the vision of this library so far. I'm kind of fond of using `GridPane` because it gives a lot of layout control. Although it doesn't add much boilderplate, I wonder if there is a better way than calling `apply()` on a `Node` and then a bunch of static `GridPane` manipulation methods (as shown in bold below). 

<pre>
class MainApp : App() {
    override val primaryView = MainView::class

    class MainView : View() {
        override val root = GridPane()

        init {
            with(root) {
                tabpane {
                    <b>apply {
                        GridPane.setVgrow(this,Priority.ALWAYS)
                        GridPane.setHgrow(this,Priority.ALWAYS)
                    }</b>
                    tab("Report", GridPane()) {
                        row {
                            <b>this += ReportTable.create().apply {
                                GridPane.setHgrow(this, Priority.ALWAYS)
                                GridPane.setVgrow(this,Priority.ALWAYS)
                            }</b>
                        }
                    }
                }
            }
        }
    }
}
</pre>

Perhaps we can add extension methods to `Node` that relate to the `GridPane`? But then again that might be confusing to see an extended `hGrow` property on a `Node` because it is not obvious it relates to the `GridPane`.

**Comment by edvin** [comment]
I only added the `row` builder for GridPane, and quickly moved on to create a `Form` layout for most of the stuff I used GridPane for in the past. Take a look at (https://github.com/edvin/tornadofx-controls/#form-layout) for quick and dirty info. I'm working on writing documentation and a sampler app for the controls in the project (and polishing them), but the `Form` component is really shaping up :)

It will try to finish documentation and examples next week, and blog about this specific component, because I feel it solves many problems much better than `GridPane`. I'm going to add specific builder support for this Form component as well.

I actually thought about the same thing, adding extensions functions to GridPane, but they would seem kind of out of place, so I need to take a step back and look for a better solution for GridPane.

I'll let you know if I can think of a nicer way to solve this :)

**Comment by thomasnield** [comment]
I'm curious to check it out, but I did come up with something. 

```
fun <T: Node> T.constraints(op: (GridPaneConstraint.() -> Unit)): T {
    val gpc = GridPaneConstraint()
    gpc.op()
    return gpc.applyToNode(this)
}

class GridPaneConstraint(
        var columnIndex: Int? = null,
        var rowIndex: Int? = null,
        var hGrow: Priority? = null,
        var vGrow: Priority? = null,
        var margin: Insets? = null,
        var fillHeight: Boolean? = null,
        var fillWidth: Boolean? = null,
        var hAlignment: HPos? = null,
        var vAlignment: VPos? = null)
{
    fun <T: Node> applyToNode(node: T): T {
        columnIndex?.let { GridPane.setColumnIndex(node,it) }
        rowIndex?.let { GridPane.setRowIndex(node,it) }
        hGrow?.let { GridPane.setHgrow(node,it) }
        vGrow?.let { GridPane.setVgrow(node,it) }
        margin?.let { GridPane.setMargin(node,it) }
        fillHeight?.let { GridPane.setFillHeight(node,it) }
        fillWidth?.let { GridPane.setFillWidth(node,it) }
        hAlignment?.let { GridPane.setHalignment(node,it) }
        vAlignment?.let { GridPane.setValignment(node,it) }
        return node
    }
}
```

This is then what it would look like. 

```
class MainApp : App() {
    override val primaryView = MainView::class

    class MainView : View() {
        override val root = GridPane()

        init {

            with(root) {
                tabpane {
                    constraints {
                        vGrow = Priority.ALWAYS
                        hGrow = Priority.ALWAYS
                    }
                    tab("Report", GridPane()) {
                        row {
                            this += ReportTable.create().constraints {
                                vGrow = Priority.ALWAYS
                                hGrow = Priority.ALWAYS
                            }
                        }
                    }
                    tab("Data Entry", HBox()) {
                        hbox {

                        }
                    }
                }
            }
        }
    }
}
```

**Comment by edvin** [comment]
Nice work! But it might still be confusing, because it would not be visible on the call site that you're applying GridPane-constraints. This would also make it impossible to do the same for other kinds of contraints. What about simply calling the function gridpaneConstraints?

**Comment by thomasnield** [comment]
I thought about that. That sounds like a better name. Want me to file a PR?

**Comment by thomasnield** [comment]
And would simply calling the function `gridpaneConstraints` alleviate all your concerns?

**Comment by edvin** [comment]
Absolutely, apart from the name this is a really good idea. Please file a PR, this is a valuable addition, and I think we might use the same approach for other use cases as well. I have some small suggestions for adjustment of the code, but nothing major :)

**Comment by thomasnield** [comment]
Done!

**Comment by edvin** [comment]
Great! I'm a bit torn.. does this fit in Builders or in Nodes. It's not really a builder, so I think `Nodes.kt` might be a better fit. Some quick comments:

- There is no need to use generics in the extension function itself or in the applyToNode function. `node: Node` should do just fine
- The function doesn't need to return anything - or do you see a benefit from that? (Fluent style, but we don't really need that in Kotlin it seems :)

**Comment by edvin** [comment]
Something like:

```kotlin
fun Node.gridpaneConstraints(op: (GridPaneConstraint.() -> Unit)) {
    val gpc = GridPaneConstraint()
    gpc.op()
    gpc.applyToNode(this)
}

class GridPaneConstraint(
        var columnIndex: Int? = null,
        var rowIndex: Int? = null,
        var hGrow: Priority? = null,
        var vGrow: Priority? = null,
        var margin: Insets? = null,
        var fillHeight: Boolean? = null,
        var fillWidth: Boolean? = null,
        var hAlignment: HPos? = null,
        var vAlignment: VPos? = null)
{
    fun applyToNode(node: Node) {
        columnIndex?.let { GridPane.setColumnIndex(node,it) }
        rowIndex?.let { GridPane.setRowIndex(node,it) }
        hGrow?.let { GridPane.setHgrow(node,it) }
        vGrow?.let { GridPane.setVgrow(node,it) }
        margin?.let { GridPane.setMargin(node,it) }
        fillHeight?.let { GridPane.setFillHeight(node,it) }
        fillWidth?.let { GridPane.setFillWidth(node,it) }
        hAlignment?.let { GridPane.setHalignment(node,it) }
        vAlignment?.let { GridPane.setValignment(node,it) }
    }
}
```

What do you think?

**Comment by thomasnield** [comment]
Okay, I'll move it to `Nodes.kt`. I'll remove the generics too. Unless I'm misunderstanding something, I personally think the function might need to return the `Node` though. For instance...

```kotlin
row {
	this += ReportTable.create().constraints {
		vGrow = Priority.ALWAYS
		hGrow = Priority.ALWAYS
	}
}
```

My `ReportTable` is a complex `TableView` I have set up as a separate class. It is helpful to call constraints() on it quickly to configure its layout and just have it return itself for the `row`.

**Comment by edvin** [comment]
Yeah, you're right. You should return the node, so you don't need to do `apply` to add the constraints.

Then I think you might need the generics, or the return type would just be Node. Sorry :)

**Comment by thomasnield** [comment]
Literally was just realizing that...

**Comment by edvin** [comment]
:+1:

**Comment by thomasnield** [comment]
Okay, another commit should be up : )

**Comment by thomasnield** [comment]
Sorry I'm taking up your vacation. You can follow up with this later if you like.

**Comment by edvin** [comment]
Perfect! Merged it and fixed a small typo in the columnRowIndex (columIndex -> columnIndex) - the parameter was never used.

Thanks a lot @thomasnield - now it's time for bed :)) And don't worry. Vacation evenings are perfect for programming :)

**Comment by thomasnield** [comment]
Haha I'm like that too. I can't break away from a computer too long, especially if I've got ideas. Have a good night. Thanks.

**Comment by edvin** [comment]
I just added vboxConstraints and hboxConstraints as well :)

**Comment by thomasnield** [comment]
I was wondering if there was something we could do for that!

**Comment by edvin** [comment]
Feels really nice, just created a table like this:

```kotlin
tableview<CustomerMail> {
    vboxConstraints {
        vGrow = Priority.ALWAYS
    }
    column<String>("Recipient") { it.value.recipientProperty()}
    column<String>("Subject") { it.value.subjectProperty()}
    column<LocalDateTime>("Sent") { it.value.sentProperty()}
}
```

Not many boiler plate chars in that code :)

**Comment by thomasnield** [comment]
That is beautiful. I think this fit into the vision of this library then.

**Comment by edvin** [comment]
I hope so. Even if the implementation should change over time, this is a pretty nice syntax :)
