### ISSUE TITLE
MenuButton missing separator()

### ISSUE THREAD

**Issue by ctadlock** [edvin/tornadofx#1202]
Looks like the separator is added to the parent?

Will submit an MR.

![image](https://user-images.githubusercontent.com/1539397/77996956-77b95a00-72e3-11ea-9405-ed5a5a87837b.png)

**Comment by ctadlock** [comment]
MR ^

Much better...
<img width="196" alt="2020-03-31 00_09_24-Test Window" src="https://user-images.githubusercontent.com/1539397/77997508-645abe80-72e4-11ea-9ea5-80c6d99f8938.png">

**Comment by edvin** [comment]
Merged!
