### ISSUE TITLE
Is there any way to make a TableView "float" over other elements?

### ISSUE THREAD

**Issue by PegasusMKD** [edvin/tornadofx#1207]
I'm using a textfield to search through data, and i'm using a tableview as something of a drodown (tableview instead of dropdown since i'd like to show them multiple fields of the found objects). When I call the tableview, it displaces the data under it. I'd like to make it "float" over the fields.

Is there any way to do that?

**Comment by SchweinchenFuntik** [comment]
You excuse me, of course, but ask such questions to ask in a slack. Here you still need to report errors

**Comment by PegasusMKD** [comment]
Yeah, thought so, didn't see that there's a Slack, thanks.

**Comment by SchweinchenFuntik** [comment]
https://kotlinlang.slack.com/messages/tornadofx/
