### ISSUE TITLE
ModelWrapper

### ISSUE THREAD

**Issue by johnp** [edvin/tornadofx#121]
Hi edvin,

I'm currently refactoring the [ModelWrapper](https://github.com/sialcasa/mvvmFX/wiki/ModelWrapper) from [mvvmFX](https://github.com/sialcasa/mvvmFX) into a Kotlin-native implementation and would like to contribute it to the TornadoFX project if you're interested. It's a bit similar to the DirtyState class from TornadoFX-Controls, although it (usually) wraps KProperties and returns JavaFX properties.
My current implementation turns the example from the mvvmFX ModelWrapper wiki page into this functionally equivalent Kotlin example:

```Kotlin
class PersonViewModel : ViewSingleModel<Person>() {
    val name = wrapper.field(Person::name)
    fun nameProperty() = name

    val familyName = wrapper.field(Person::familyName)
    fun familyNameProperty() = familyName

    val age = wrapper.field(Person::age)
    fun ageProperty() = age
}
```

There are still several design decisions to be made and I'd just like to get you in the loop and post a WIP PR if this is something you could see making its way into TornadoFX.

**Comment by edvin** [comment]
Hi Johannes,

I was actually thinking about reimplementing the DirtyState tracker for TornadoFX, so maybe we can join efforts here :)

I'm extremely busy this week, but I hope to be back to programming before the middle of next week at least. I'm absolutely interested in looking at this closer.

Even if I have little time for actual programming this week, I check in a couple of times each day at least so I can participate in design discussions etc :)

**Comment by edvin** [comment]
By the way, have a look in [Properties.kt](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Properties.kt) - we have might some overlapping functionality there, for example stuff that turns a POJO property into a JavaFX property.

**Comment by johnp** [comment]
Great!
There are some useful things I picked from Properties.kt, but couldn't use directly and had to modify somewhat to be used for the POJO `field()` implementations.

Created PR #122 for further discussion.

**Comment by edvin** [comment]
Just checking in to let you know I haven't forgotten about this, I'm just crazy busy at the moment. Will review shortly :)

**Comment by johnp** [comment]
Thanks for the note, but please take your time. No reason to rush this if there are other matters to attend to.

**Comment by edvin** [comment]
I just had an idea on Slack, but realized you're not there @johnp, so I'll write it here as well :)

I'm wondering if `View` should have a default `ValidationContext` and `ViewModel`. The `validationContext` would be extracted from the `ViewModel`, and it would make it possible for validation to be performed on input fields even if a specific `ViewModel` was not provided for a `View`.

[10:08]  
Then you can simply validate input fields without an underlying `ViewModel` which would make the whole validation framework more accessible for even the smallest of use cases.

[10:09]  
If there's always one `ViewModel` for each View, we wouldn't need to perform the trickery we do to extract the `ViewModel` from the control either.

What do you think? I'd like to try this to see how it feels.

**Comment by edvin** [comment]
I just realised another very nice way to use the VIewModel. If you make the source object a property, and also give it getters and setters to make it easier to use in the `bind {}` statements, you could make sure the ViewModel automatically rebinds when the source object changes:

```kotlin
class UserModel : ViewModel() {
    val userProperty = SimpleObjectProperty(User())
    var user by userProperty

    init {
        rebindOnChange(userProperty)
    }
    
    val login = bind { user.login }
    val password = bind { user.password }
}
```

Notice that this is using the new property syntax. The first two lines of code gives you:

- An observable `Property<User>` called `userProperty` with a default value of an empty `User`
- Getters and setters so you can do `model.user = User()` and `val user = model.user`

In the `init` block we tell the `ViewModel` to automatically rollback any changes when the user object is changed, which will in turn update an input fields that are bound to the `ViewModel`.

**Comment by edvin** [comment]
I'm closing the issue now since I don't see any issues and no negative feedback has been provided. Thank you so much for bringing this @johnp :)
