### ISSUE TITLE
Local storage in tonadofx 

### ISSUE THREAD

**Issue by etiennept** [edvin/tornadofx#1220]
Does it exit a function which store key-value data in client's local computer  with tonadofx

**Comment by edvin** [comment]
Yes, see `config` in the guide: https://edvin.gitbooks.io/tornadofx-guide/part2/Config_Settings_and_State.html

Remember you can also read/write any local file using the standard Java filesystem mechanisms.

**Comment by etiennept** [comment]
Thank you

**Comment by etiennept** [comment]
Does it exit a function which a local database is stored in client's computer with tonadofx
