### ISSUE TITLE
Adding Button in tableview column

### ISSUE THREAD

**Issue by KamilaNowak** [edvin/tornadofx#1226]
Is there a solution to simply add a button into table view column? 

I have defined a simple tableview and I'm trying to figure out how to pass separate button for every tableview row without defining separate JavaFX function which handle all of the operations.

    ```
    tableview<InvoiceSummaryModel> {
            items = invoicesShowcaseController.getCompanyInvoiceSummary()
            columnResizePolicy = SmartResize.POLICY

            column("Invoice number", InvoiceSummaryModel::invoiceNo)
            column("Date", InvoiceSummaryModel::dateOfIssue)
            column("Amount", InvoiceSummaryModel::amount)
            column("Receiver", InvoiceSummaryModel::receiver)
         //column("Link", button { action{ } })
        }
```

**Comment by SchweinchenFuntik** [comment]
there are other options, but you need to describe what kind of behavior you want
```
data class Named(var name: String, var value: Int)

class NamedModel : ItemViewModel<Named>() {
    val name = bind(Named::name)
    val value = bind(Named::value)
}


class T : View() {

    val names = observableListOf(Named("1000", 2), Named("1", 1), Named("2", 2))

    private val nameProperty = stringProperty("")
    private val valueProperty = intProperty(0)

    override val root = borderpane {


        center = tableview(names) {
            column("Name", Named::name)
            // any of the properties
            column("button", Named::value) {
                cellFormat {
                    graphic = button("$it")
                }
            }
        }
    }

}
```

**Comment by KamilaNowak** [comment]
Unfortunately, example above doees not gives me right solution, button does not show in column rows. I am expecting to have a button for every row  and  invoke a method with the data of this actual row.
I expect to have something like that:
![Adnotacja 2020-04-30 084303](https://user-images.githubusercontent.com/47334332/80680249-ae3eec00-8abe-11ea-9d98-844141dcea73.png)

**Comment by edvin** [comment]
That's pretty much exactly what @SchweinchenFuntik does in his example. You can access the item for the row with `rowItem`:

```kotlin
column("Action", Named::value) {
    cellFormat {
        graphic = button("Delete") {
            action {
                println("You deleted ${rowItem.name}")
            }
        }
    }
}
```

**Comment by KamilaNowak** [comment]
I made a mistake in the code. Now it works. Thanks a lot @edvin and @SchweinchenFuntik .

**Comment by edvin** [comment]
Fantastic! Thanks for reporting back :)
