### ISSUE TITLE
TornadoxFX with JFoenix

### ISSUE THREAD

**Issue by halimpuckjava** [edvin/tornadofx#1234]
hi

how use jfoenix ui components with tornadofx

**Comment by SchweinchenFuntik** [comment]
https://github.com/bkenn/KFoenix 
there is one, but abandoned, I thought somehow to fork, but there is no time

**Comment by edvin** [comment]
You don't need any integration library to use JFoenix with TornadoFX. Just like with JavaFX, you can simply instantiate the JFoenix components and add them to any UI container as usual.

**Comment by SchweinchenFuntik** [comment]
@halimpuckjava the issue is closed ?

**Comment by halimpuckjava** [comment]
issue closed
