### ISSUE TITLE
TableView smart column resize

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#124]
Two use cases:

- Resizing select columns to the best width to fit the content, and then distribute the remaining space evenly over the remaining columns.

- Resize columns based on weight to fill the complete width of the TableView.

**Comment by thomasnield** [comment]
Didn't we address this somewhat already? 
https://github.com/edvin/tornadofx/issues/48

**Comment by edvin** [comment]
No, https://github.com/edvin/tornadofx/issues/48 only supports "fit to content" resizing, I want to be able to express different requirements for each column:

- Give col1 50px fixed width
- Give col2 the width it needs based on content
- Give col3 50% width
- Give col4 it's preferred with (weight=1)
- Give col5 double the width of col4 (weight=2)
- Give col6 the remaining width

**Comment by thomasnield** [comment]
Ah I get it. This would actually be VERY helpful.

**Comment by edvin** [comment]
Completed.
