### ISSUE TITLE
Rest client issues

### ISSUE THREAD

**Issue by zeljkosh** [edvin/tornadofx#1253]
i have made yday a question at stackoverflow 
https://stackoverflow.com/questions/62643559/tornadofx-rest-client

I got no answer at all, so i might as well ask here, since googling gave me no results,
When response contains some other info other then json objects UpdateModel just does not work, and it throws null exception.

Is there any way to tell update model how to separate data from that additional info we get from json request.

When i make this request http://dummy.restapiexample.com/api/v1/employees , my app crashes and i get null pointer exception, i assume this 
{"status":"success","data": is the problem.

when i copy objects to the mocky, and just get this in request 

`{"id":"1","employee_name":"Tiger Nixon","employee_salary":"320800","employee_age":"61","profile_image":""}`

it all works.

Am i missing some functionality, or is there some other oversight ?

**Comment by ruckustboom** [comment]
I've added a [potential answer on SO](https://stackoverflow.com/a/62679506/2094298). Unfortunately I can't test the code right now, so I'm not 100% sure I didn't make any mistakes, but it should get you 90% of the way there.
