### ISSUE TITLE
Shortcut combination 

### ISSUE THREAD

**Issue by joaogarrido98** [edvin/tornadofx#1256]
I'm trying  to put shortcuts in the menubar but i want it to appear on the right side of the menuitem, although the shortcut is done and usable the combination does not appear in the ui! 
Anyway to do this?

**Comment by SchweinchenFuntik** [comment]
please provide a minimal example where you add shortcut

**Comment by joaogarrido98** [comment]
Sorry no need, already resolved it! You have to put the combination on the item and not on the shortcut
![dawa](https://user-images.githubusercontent.com/48774418/87047029-d733d980-c1f1-11ea-9262-06095bdf4c49.PNG)
