### ISSUE TITLE
Using wizard in SPA

### ISSUE THREAD

**Issue by N1Knight** [edvin/tornadofx#1259]
Hi, I want to use wizard in same windows as the main program without open a new popup.
I've some problems with this approach.
It's possible to change default behaviour of finish's button to not close the entire program?

**Comment by SchweinchenFuntik** [comment]
please give a minimal example

**Comment by N1Knight** [comment]
I'm afraid for response's delay. I was outsite.

I've my principal view: 

```
class MainView : View("myView") {

    val mainContainer = vbox {
        useMaxWidth = true
        useMaxHeight = true
        alignment = Pos.TOP_CENTER
    }

    override val root = vbox {
        add<MenuView>()
        add(mainContainer)
    }

    init {
        importStylesheet(Styles::class)

        subscribe<ShowNewPacientEvent>  {
            mainContainer.add<FormPacientView>()
        }

        subscribe<ShowNewQueryEvent>  {
            mainContainer.add<WizardView>()
        }
    }

}
```

And my wizard view:

```
class WizardView : Wizard("Search pacient", "New pacient") {
    init {
        add(SearchPacientView::class)
        add(FormPacientView::class, mapOf(FormPacientView.viewParams.IS_WIZARD to true))
    }
}
```

When I close the wizard view, the FormPacientView have still been block to change IsVisible. I suppouse is for "visibleWhen" and other bindings.

Also when I click on "finish" the Wizard close my principal view thus close the entire program.

I try to use `openInternalWindow<WizardView>(modal = false)` But it's the same. When I add FormPacientView it's still blocked.

Any Idea what I doing so bad?

**Comment by SchweinchenFuntik** [comment]
direct access to change the `onFinish` behavior, but you can override `onSave`, and insert `isComplete = false`.

https://github.com/edvin/tornadofx/blob/1e8fdc7158a270fe73ada2cac84d5530b97e8823/src/main/java/tornadofx/Wizard.kt#L181

**Comment by N1Knight** [comment]
That's works but visible block still continue when I close the wizard. I need to reuse formpacientview.

Any suggestion for cancel the binding made by "visibleWhen" inside the wizard?

**Comment by N1Knight** [comment]
Hi!
I solved using a new scope

```
        subscribe<ShowNewQueryEvent>  {
            mainContainer.children.clear()
            mainContainer.add(find(QueryView::class, wizardScope))
        }
```

Thanks.
