### ISSUE TITLE
Cant build tornadofx app via gradle

### ISSUE THREAD

**Issue by aleksanderzagora** [edvin/tornadofx#1260]
Hello! I am an absolute newbie to Kotlin, IntelliJ and TornadoFX. I can't create the TornadoFXproject and don't understand what the error is. Help me please.

IntelliJ ver 2020.1.3

openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

![2020-07-20_10-19-31](https://user-images.githubusercontent.com/14241127/87916382-a7979380-ca73-11ea-9109-2a24f55646d9.png)

![2020-07-20_10-20-36](https://user-images.githubusercontent.com/14241127/87916441-bd0cbd80-ca73-11ea-9af6-c97b473ddcf2.png)

![2020-07-20_10-21-12](https://user-images.githubusercontent.com/14241127/87916480-c85fe900-ca73-11ea-9221-2f82c483c161.png)

**Comment by aleksanderzagora** [comment]
Update:
tornadofx-gradle-project doesn't work.
tornadofx-maven-project is working correctly.

Is it possible to fix this somehow?

**Comment by SchweinchenFuntik** [comment]
The plugin is outdated, but it can be configured manually. A regular grill project (with Kotlin) is created and the Tarnadofx dependency is added, it is also worth adding an application plugin. More details here: https://edvin.gitbooks.io/tornadofx-guide/content/part1/2_Setting_Up.html

**Comment by aleksanderzagora** [comment]
> A regular grill project (with Kotlin) is created and the Tarnadofx dependency is added, it is also worth adding an application plugin.

Does regular grill project mean gradle?

**Comment by SchweinchenFuntik** [comment]
sorry: gradle project.

**Comment by aleksanderzagora** [comment]
> I also threw off examples of a dummy project (`build.gradle`)

Thank you so much! You saved my brain.
