### ISSUE TITLE
How to do this bindings?

### ISSUE THREAD

**Issue by AlexanderMattheis** [edvin/tornadofx#1266]
Hello,
First, you made a great piece of software. I started with TornadoFX two weeks ago and I am really amazed. But I'm a newbie and I want to create something like the 'Model View Controller' pattern and I've got some problems with that idea. I hope you can help me? I'm writing an open source CSV stream viewer and I want to display a range from an arbitrary CSV file. I need to create columns dynamically because I don't know what my CSV file will look like, and that's one thing I can't get to work.

So that is my View:
```kotlin

typealias Row = Map<String, String>

class MainPanelView : View("Big Mommy") {
    private val controller : MainPanelController = MainPanelController(this)

    override val root = borderpane {
       \\ ...
        center = tableview(controller.rows) {
            addClass(MainPanelStyle.tableClass)
        }

       \\ ...
    }
}
```

And this is my controller:

```kotlin
package app.panels.main_panel

import javafx.beans.property.SimpleLongProperty
import javafx.stage.FileChooser
import tornadofx.*
import java.io.File
import java.nio.file.Files
import java.nio.file.Paths
import java.util.function.Supplier
import java.util.stream.Stream
import javax.swing.text.TableView

class MainPanelController(val view: MainPanelView) : Controller() {

    val rows = mutableListOf<Row>().asObservable()
    val separator = ","

    val linesProperty = SimpleLongProperty(0L)

    fun openFile() {
        val fileChooser = FileChooser();
        val file = fileChooser.showOpenDialog(view.currentWindow)
         \\ ...
    }

    private fun loadData(file: File) {
        val linesStreamSupplier: Supplier<Stream<String>> = Supplier { Files.lines(Paths.get(file.path)) }

        val header = getHeaderElements(linesStreamSupplier.get(), separator)
        val rows = mutableListOf<Row>()

        linesStreamSupplier.get().forEach { line ->
            val lineElements = getLineElements(line, separator)
            val mapping = mutableMapOf<String, String>()

            for ((heading, lineElement) in header zip lineElements) {
                mapping[heading] = lineElement
            }

            rows += mapping
        }

        this.rows.setAll(rows)
        linesProperty.value = linesStreamSupplier.get().count()
    }

     \\ ...
}
```

**The first problem:** "Spaghetti Code" - My `Controller` needs access to the `View` since it has to open a `fileChooser` as you can see here `val file = fileChooser.showOpenDialog(view.currentWindow)`. But the `View` also uses the `Controller` to display data as you can see here `tableview(controller.rows)`. I don't think that is clean code.

**The second problem:** Is my main problem - how to generate the columns?
I found something like this here https://github.com/edvin/tornadofx/issues/807
but it did not work and googled around about two hours.
I'd expected that `center = tableview(controller.rows) { ... }` (View) would update automatically if I call this `this.rows.setAll(rows)` in the `Controller`.
But nothing happens, the code the brackets `{ ... }` is not called again or something like this.
You can view my full code here https://github.com/AlexanderMattheis/big-mommy/tree/master/src/main/kotlin/app/panels/main_panel
or here since my master will probably be updated soon
https://github.com/AlexanderMattheis/big-mommy/tree/9e8a92050c12a82197349771149a2d6323997f94/src/main/kotlin/app/panels/main_panel

**Comment by SchweinchenFuntik** [comment]
Hello. Look here https://github.com/edvin/tornadofx/issues/1233

**Comment by SchweinchenFuntik** [comment]
> The first problem: : "Spaghetti Code"

find the answer in https://edvin.gitbooks.io/tornadofx-guide/content/part1/3_Components.html section `Injection Using find () or inject ()`

> The second problem: I

**Comment by AlexanderMattheis** [comment]
The first problem, I think is fully solved. :+1: 
Thank you so much! 

The second problem. Thank you for your links. I'm testing that out.

**Comment by AlexanderMattheis** [comment]
> nd the answer in https://edvin.gitbooks.io/tornadofx-guide/content/part1/3_Components.html section `Injection Using find () or inject ()`.
> 
> PS:
> 
> ```
> class MainPanelController: Controller() {
>     // code
>     fun openFile(currentWindow: Window? = null) {
>         val fileChooser = FileChooser();
>         val file = fileChooser.showOpenDialog(currentWindow)
>     }
> }
> ```
> 
> > The second problem:
> 
> short answer. You need a dynamic model, or completely abandon the model; also google: `javafx tableview dynamic columns`, tornadoFX has no ready-made tools

The first problem, I think is fully solved. +1
Thank you so much!

The second problem. Thank you for your links. I'm testing that out.

**Comment by AlexanderMattheis** [comment]
Thank you.
Problem 2 was also solved. I tried it out now.

Here is the final solution for everyone who wants read in an arbitrary CSV-table:
```kotlin
private fun loadFileInto(file: File, table: TableView<Row>) {
        val linesStreamSupplier: Supplier<Stream<String>> = Supplier { Files.lines(Paths.get(file.path)) }

        val header = getHeaderElements(linesStreamSupplier.get(), separator)
        val rows = mutableListOf<Row>().asObservable()

        linesStreamSupplier.get().forEach { line ->
            val lineElements = getLineElements(line, separator)
            val mapping = mutableMapOf<String, String>()

            for ((heading, lineElement) in header zip lineElements) {
                mapping[heading] = lineElement
            }

            rows += mapping
        }

        linesProperty.value = linesStreamSupplier.get().count()
        populateToTable(rows, table)
    }

    private fun getHeaderElements(linesStream: Stream<String>, separator: String): List<String> {
        val firstLine = linesStream.findFirst()
        return if (firstLine.isPresent) firstLine.get().split(separator) else emptyList()
    }

    private fun getLineElements(line: String, separator: String): List<String> {
        return line.split(separator)
    }

    private fun populateToTable(rows: ObservableList<Row>, table: TableView<Row>) {
        table.columns.clear()
        table.items.clear()

        createHeadings(rows, table)
        createContents(rows, table)
    }

    private fun createHeadings(rows: ObservableList<Row>, table: TableView<Row>) {
        val columns = ArrayList<TableColumn<Row, Any>>()
        val keys = rows.first().keys

        for (key in keys) {
            val column = TableColumn<Row, Any>(key)
            column.cellValueFactory = Callback { param ->
                ReadOnlyObjectWrapper(param.value.get(key))
            }
            columns.add(column)
        }

        table.columns.addAll(columns)
    }

    private fun createContents(rows: ObservableList<Row>, table: TableView<Row>) {
        val contents = rows.minus(rows.first())  // header should not be added
        table.items.addAll(contents)
    }
```

For full code have a look at this commit here d65191929716da58ac253438bcc1fa70263d6b51

**Comment by AlexanderMattheis** [comment]
If you have no suggestions for improvement, then you can close this issue, else I do it as soon as I do log in next time.
