### ISSUE TITLE
JAVA 11: Getting the View by fxml()  return an error.

### ISSUE THREAD

**Issue by AdelDima** [edvin/tornadofx#1268]
Hello, I have JavaFX Application I started to migrate into TornadoFX.
Q: I have an issue when I want to load an FXML file ( I created it before on the JavaFX)

```kt
class LoginView : View() {
override val root:AnchorPane by fxml("/fxml/LoginView.fxml")
}
```
My LoginView.fxml located on `src/main/resources/fxml/LoginView.fxml`
Errore: `component.javaClass.getResource(resource) must not be null`

Note: I am using Maven + Java11 + TornadoFX 1.7.20

**Comment by SchweinchenFuntik** [comment]
Where is the FXML in your project?

**Comment by AdelDima** [comment]
In src/main/resources/fxml/LoginView.fxml

**Comment by AdelDima** [comment]
> Where is the FXML in your project?
In src/main/resources/fxml/LoginView.fxml

**Comment by SchweinchenFuntik** [comment]
you need to make sure that the `sourceSet` is configured correctly in the maven

**Comment by AdelDima** [comment]
> you need to make sure that the `sourceSet` is configured correctly in the maven

```
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                <sourceDir>${project.basedir}/src/main/java</sourceDir>
                            </sourceDirs>
                        </configuration
```>

**Comment by SchweinchenFuntik** [comment]
here you also need to set up resources, I'm not a maven expert, so I won't say exactly how

**Comment by SchweinchenFuntik** [comment]
https://maven.apache.org/plugins/maven-resources-plugin/examples/resource-directory.html

I understand that if you do not create a folder, then it will be by default.

How do you launch your cube?

**Comment by AdelDima** [comment]
> https://maven.apache.org/plugins/maven-resources-plugin/examples/resource-directory.html
> 
> I understand that if you do not create a folder, then it will be by default.
> 
> How do you launch your cube?

Exactly,
`class MyApp: App(LoginView ::class, Styles::class) ` using TornadoFX configuration run.

```kt
 override fun start(stage: Stage) {
        val logins = find(LoginView::class)
        val scene = LoginController.decorator(logins.root, stage)
        stage.scene = scene
        stage.show()
    }
```

**Comment by SchweinchenFuntik** [comment]
why are you redefining start method?

**Comment by SchweinchenFuntik** [comment]
I found the place from where the error falls out, I did not find another similar one: 

1.https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/FX.kt#L114

2. https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Component.kt#L195

3. https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Component.kt#L1325

and I can only make one conclusion - it doesn't find the file.
The reason may be that there is no jar-file, therefore there are no resources either, try to create a jar and run it (I seemed to have a similar problem,  there was a special task in the gradle)

**Comment by AdelDima** [comment]
@SchweinchenFuntik
I redfin it because I used FXMLLoader and the FXML has his own fx: controller, and I use JFXDecorator 
Thank you for your solution, I'll try a similar solution with Maven.

**Comment by SchweinchenFuntik** [comment]
will not work. your View and should be a controller

**Comment by AdelDima** [comment]
- Yes, I have it did not work too.
- This adds the content into a [JFXDecorator](https://github.com/jfoenixadmin/JFoenix)

**Comment by SchweinchenFuntik** [comment]
@AdelDima maybe you don't quite understand how it works.
Below is a ready-made builder and an example of application
https://github.com/bkenn/KFoenix/blob/master/src/main/kotlin/kfoenix/Layouts.kt#L19

**Comment by SchweinchenFuntik** [comment]
i would recommend to run Tornadofx + FXML without JFX first

**Comment by utybo** [comment]
TornadoFX 1.7.10 doesn't support JDK 9+, you should use the snapshot versions https://github.com/edvin/tornadofx/issues/899#issuecomment-488249680

**Comment by SchweinchenFuntik** [comment]
I somehow overlooked that there is Javafx 11

**Comment by AdelDima** [comment]
Thank you, I'll use the snapshot.
