### ISSUE TITLE
Dynamic TableView columns from a result set (kotlin)

### ISSUE THREAD

**Issue by msafarulla** [edvin/tornadofx#1269]
To set the preface: I am a programmer with very limited experience in programming other than COBOL like languages which means I am very new to JVM based programming languages. But I been using python for personal use and am not completely new to modern age programming concepts. Benefit of new bee is expected and please don't shoot down the post.

I am looking to write a query tool. When a query is executed, the data is presented to the user in a table view. So as you can imagine the columns list going to be as dynamic as it can get. Closest I found about dynamic table view creation is here
Dynamic table columns

To write an MVC based query tool, how should the model be created? So that when the data in the table view is updated, it can be updated back to the database and vice versa.

**Comment by msafarulla** [comment]
![image](https://user-images.githubusercontent.com/3927530/91045570-f208b480-e5cb-11ea-8dba-adf4e564f061.png)

To add some more context. Above is how the app looks now. Table emp has very limited number of fields now so I don't have scaling issues to create a TableView and bind it.

**Comment by SchweinchenFuntik** [comment]
you cannot have a model as you have dynamic data.

The first thing that comes to mind is: `Map<String, Property<Any?>>` // column name and observable property

**Comment by msafarulla** [comment]
Do you have a code example that you could share that I could play around to learn this? please

**Comment by SchweinchenFuntik** [comment]
no, I would drop, read about Map

**Comment by AlexanderMattheis** [comment]
May it helps you.
https://github.com/edvin/tornadofx/issues/1266#issuecomment-671041865
https://github.com/AlexanderMattheis/big-mommy

**Comment by msafarulla** [comment]
@AlexanderMattheis That helped. I created a fork off of your repository to make it more Kotlin like for my eyes. 
[here](https://github.com/msafarulla/Dynamic-Table-View)

Could you please give me what exactly happens in the function `getColumns` in line 
`column.cellValueFactory = Callback { ReadOnlyObjectWrapper(key) } `

I am new very new to Java/Kotlin and appreciate your time explaining this.

**Comment by SchweinchenFuntik** [comment]
@msafarulla 
>column.cellValueFactory = Callback { param -> ReadOnlyObjectWrapper(param.value[key]) } 

https://openjfx.io/javadoc/12/javafx.controls/javafx/scene/control/TableColumn.html

> The cell value factory needs to be set to specify how to populate all cells within a single TableColumn.

**Comment by msafarulla** [comment]
Thanks. I think i need to build some basic javaFx knowledge. This guys is awesome. [Java/javaFX 101](https://www.youtube.com/watch?v=FLkOX4Eez6o&list=PL6gx4Cwl9DGBzfXLWLSYVy8EbTdpGbUIG&index=1)
