### ISSUE TITLE
Can't negate Dimensions

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#127]
When using type safe CSS, `roatate = -5.deg` will not compile as `unaryMinus()` is not defined for dimensions.

**Comment by t-boom** [comment]
I'll fix this soon. I'm in the middle of another project at the moment, so I can't take care of it at the moment. I'm just putting this here for future reference.

**Comment by t-boom** [comment]
Note that the current work around is to use `(-5).deg`

**Comment by t-boom** [comment]
Fixed in latest push to css2 branch

**Comment by edvin** [comment]
Perfect. Is it easy to "backport" into the main branch or should we just wait until we merge css2?

**Comment by t-boom** [comment]
It'll be really easy. It will cause a merge conflict on the css2 merge, so just remember to accept everything from css2 when we do end up merging.

**Comment by t-boom** [comment]
I fixed it in master and resolved the merge conflict in css2

**Comment by edvin** [comment]
Perfect! Yes, let's close it.
