### ISSUE TITLE
When I run my tornadofx app . I got this error.

### ISSUE THREAD

**Issue by Leo-Thura** [edvin/tornadofx#1276]
InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to unnamed module @7a5d012c

**Comment by SchweinchenFuntik** [comment]
what version of kotlin and tornadofx?

**Comment by Leo-Thura** [comment]
Kotlin : 1.3.72 , tornadofx : 2.0.0-SNAPSHOT

**Comment by Leo-Thura** [comment]
I run the jar using following command
java --module-path "C:\Path\to\sdk-11\lib" --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics -jar My_jar.jar

**Comment by Leo-Thura** [comment]
When I add the options , --add-opens=javafx.graphics/javafx.scene=tornadofx
But I still get the same error and a new warning .

Unknown module: javafx.graphics specified to --add-opens

**Comment by SchweinchenFuntik** [comment]
https://openjfx.io/ There is an instruction on how to install JavaFX sdk. Alternatively, find a JDK that includes JavaFX.

**Comment by pavlus** [comment]
Same as #1270 and #1217
