### ISSUE TITLE
"webview {}" function missing

### ISSUE THREAD

**Issue by Finnerale** [edvin/tornadofx#128]
The line `fun Pane.webview(op: (WebView.() -> Unit)? = null) = opcr(this, WebView(), op)`
is missing in `tornadofx/src/main/java/tornadofx/Controls.kt` to support the WebView

**Comment by edvin** [comment]
Thank you :) Added now.

**Comment by thomasnield** [comment]
I'll add this to guide with a few other missing controls.

**Comment by edvin** [comment]
Thank you Thomas :))
