### ISSUE TITLE
How to ease prepare app for Windows, Mac and Linux

### ISSUE THREAD

**Issue by markowanga** [edvin/tornadofx#1280]
I look for this few days, I can't see good solution. I tried with fxlauncher but I have errors. Could somebody help me?
Best option will be something which I can use in CI on Jenkins or Gitlab.

**Comment by markowanga** [comment]
Good way will be GitHub Actions too :)

**Comment by SchweinchenFuntik** [comment]
What exactly were the errors with fxlauncher? updates can be sewn into applications. Or you can twist it through the gradle task.

**Comment by markowanga** [comment]
Sorry, my fault -- I had wrong understood how FxLaunch works.
Everything is ok :)
