### ISSUE TITLE
How to stop textfield auto stretching to window edge

### ISSUE THREAD

**Issue by SacaLiviu** [edvin/tornadofx#1289]
How can i make the textfield not autostretch a fixed size and centered in a vbox using stylesheets?
[Here is an example of how its stretching](https://imgur.com/aeMl9T7). 
I'm new to programming and tried centering with 
`alignment=Pos.CENTER` 
but for the love of god i dont know how to make it a fixed size and centered

**Comment by SKeeneCode** [comment]
Try adding `maxWidth = 300.0` to the textField. That should do the trick. There is also a `minWidth` and `prefWidth` to play around with.

Adding also 'hgrow = Priority.NEVER' Will prevent the textField stretching into any available space.

**Comment by SacaLiviu** [comment]
Thanks. That seems to fix it. Ill close the issue now.
