### ISSUE TITLE
Builders for shapes

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#129]
We should provide builders for Shapes, see https://docs.oracle.com/javase/8/javafx/api/javafx/scene/shape/Shape.html.

It would be interesting to explore a drawing DSL around these shapes as well.

**Comment by t-boom** [comment]
Is this just for `Node` based shapes, or would a similar API be designed for `Canvas` drawing?

**Comment by edvin** [comment]
It would certainly be nice to have something similar for Canvas drawing :)

**Comment by thomasnield** [comment]
I just had an epiphany concerning builders for animations.  I'll put in a PR tonight Texas time. 

I also may ask for input on some reactive approaches too, and I think some of them will rely on TornadoFX builders to streamline a bit.

**Comment by edvin** [comment]
Builders for all shapes implemented in `Shapes.kt`

**Comment by thomasnield** [comment]
If you like, you can start documenting the shapes in the guide. I created an empty section "Builders Part VI - Shapes and Animation".

**Comment by edvin** [comment]
Will do :)
