### ISSUE TITLE
Opening the ComboBox shows dropdown in top left corner of screen on initial window load

### ISSUE THREAD

**Issue by ganderson04** [edvin/tornadofx#1295]
As described in the title. Dragging the window slightly or minimising and re-opening the window fix the issue. The issue does not occur while using plain JavaFX. I made a demo application (Windows 10, JDK 11, TornadoFX 1.7.20) to show this occurring, and [this image](https://i.imgur.com/cVPxM2k.png) shows the issue. The application window is in its initial position, slightly above the centre of the screen. 

DemoApp.kt
```
class DemoApp : App() {
    override fun start(stage: Stage) {
        super.start(stage)
        val demoView = DemoView()
        demoView.openWindow()
    }
}
```

DemoView.kt
```
class DemoView : View() {
    override val root = vbox {
        combobox<String>{
            items.setAll("One", "Two", "Three")
        }
    }
}
```

build.gradle.kts
```
plugins {
    kotlin("jvm") version "1.4.10"
    id("application")
    id("org.openjfx.javafxplugin") version "0.0.9"
}
group = "com.github.ganderson04"
version = "1.0-SNAPSHOT"

javafx {
    version = "11.0.2"
    modules("javafx.controls", "javafx.graphics")
}
application {
    mainClassName = "DemoApp"
}
repositories {
    mavenCentral()
}
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.4.10")
    implementation("no.tornado:tornadofx:1.7.20")
    testImplementation(kotlin("test-junit"))
}
tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "1.8"
}
```

**Comment by SKeeneCode** [comment]
Can you try:

`class DemoApp : App(DemoView::class) {
    
}
fun main() {
    launch<DemoApp>()
}

class DemoView : View() {
    override val root = vbox {
        combobox<String>{
            items.setAll("One", "Two", "Three")
        }
    }
}`

Doing it this way does not reproduce the error, although I am using the 2.0.0 snapshot of TornadoFX.

I do not believe the way you are launching your app is the proper way to launch a TornadoFX program. Views should never really be initialised directly.

**Comment by SchweinchenFuntik** [comment]
you are doing very unwisely, tornadofx in the `start` function, executes the code needed to make it work. If you want to override this method you must call `super (stage)` at the very beginning

**Comment by ganderson04** [comment]
@SKeeneCode Thank you for that suggestion, it worked for me on 1.7.20 as well.
@SchweinchenFuntik I do call `super.start(stage)` in my example, but I understand I shouldn't be overriding `start` to open the window now.

I'm going to close this as it was just a misunderstanding on my part.

**Comment by SchweinchenFuntik** [comment]
>  I do call `super.start(stage)`

yes) I didn't notice, you just open the view, and this creates a new window (Stage)
