### ISSUE TITLE
onUndock() is not called for child fragments while onDock() is called.

### ISSUE THREAD

**Issue by mswokk** [edvin/tornadofx#1300]
Expected :
Child Docked
Parent Docked
Parent Undocked
**Child Undocked  ==> This line is missing when run** 

I saw an article that lifecycle methods are called for root scene view only, but onDock is called for children.
Why only onUndock() is not propagated?
Did I miss something?

Here is minimal reproduction code
------------------------------------------------
```
// A child view to add to parent
class ChildFragment : Fragment() {
    override val root = label("Hello")

    override fun onDock() {
        super.onDock()
        println("Child Docked")
    }

    override fun onUndock() {
        super.onUndock()
        println("Child Undocked")
    }
}

// View for root
class ParentView : View() {
    override val root = vbox {
        add(find<ChildFragment>())
    }

    override fun onDock() {
        super.onDock()
        println("Parent Docked")
    }

    override fun onUndock() {
        super.onUndock()
        println("Parent Undocked")
    }
}

// Call
fun main() {
    class MyApp : App(ParentView::class)
    launch<MyApp>()
}
```

**Comment by SKeeneCode** [comment]
A  UIComponent will have its onUndock() [called when its parent changes to another parent or null, but not when it goes from null to parent](https://github.com/edvin/tornadofx/blob/904617a6e2e1582f810eae1ee569c600fcc2498d/src/main/java/tornadofx/Component.kt#L537).


Also, there is no default implementation of onDock() or onUndock() so when extending from View or Fragment there is no need to call super.

**Comment by mswokk** [comment]
@SKeeneCode Thanks for comment. Now I understood why. Even the root view lost its parent, child views are still have its own parent, so onUndock() is not called. For workaround, I just extend the Fragment, View and wrote addAndRemoveWhenUndock(), so that child view can be removed when the root view lost its parent.
