### ISSUE TITLE
Confusion about binding multiple properties

### ISSUE THREAD

**Issue by elliotcm** [edvin/tornadofx#1305]
Hello.

I'm having trouble figuring out how to use a viewmodel with nodes that have multiple properties.  For example, a `Line` has `startX`, `endX` etc, but the section of the guide which deals with viewmodels only seems to give guidance for controls with a single property as its main argument.

Various docs on binding say "most" node builders accept this single argument, but don't say what to do for the ones that don't.

Thanks,
Elliot

**Comment by SchweinchenFuntik** [comment]
if no parameters are specified, the default values will be applied. This is often 0.0

**Comment by elliotcm** [comment]
> if no parameters are specified, the default values will be applied. This is often 0.0

Sure, that wasn't my question though, what I'm unsure on is how to bind to multiple properties.

**Comment by SchweinchenFuntik** [comment]
you bind specific properties to specific properties. See the same `TableVIew`

```kotlin
data class Point(var x: Double = 0.0, var y: Double = 0.0
```

**Comment by elliotcm** [comment]
OK perfect, thanks.  That's the direction I was heading in but only through guesswork, wasn't sure if it was the right approach.

Thanks again.
