### ISSUE TITLE
Is TornadoFX kill?

### ISSUE THREAD

**Issue by christianitus03** [edvin/tornadofx#1306]
Doesn't seem to be any activity here.

**Comment by edvin** [comment]
I'm here, but I don't have any time to work on it. As I've said before, I'm still using it heavily in several projects and will pick up again when I have time unless somebody else steps up. I'm still using it with Java 8 in our projects, so working on 2.0 hasn't been needed for me personally, and TornadoFX is pretty mature/does everything I need it to do as is. Would love to work on this more, but there just isn't any time right now.

**Comment by christianitus03** [comment]
> I'm here, but I don't have any time to work on it. As I've said before, I'm still using it heavily in several projects and will pick up again when I have time unless somebody else steps up. I'm still using it with Java 8 in our projects, so working on 2.0 hasn't been needed for me personally, and TornadoFX is pretty mature/does everything I need it to do as is. Would love to work on this more, but there just isn't any time right now.

Understood. Just asking because I wanted to use this for a Java 11 project. Best of luck

**Comment by edvin** [comment]
The 2.0 branch is fully usable for a Java 11 project, and 2.0 will eventually be the main branch, so you shouldn't be afraid to use it even in production :)

**Comment by christianitus03** [comment]
> The 2.0 branch is fully usable for a Java 11 project, and 2.0 will eventually be the main branch, so you shouldn't be afraid to use it even in production :)

> @christianitus03 I use it in production, in internal company projects (TornadofFX-2.0.0-SNAPSHOT)

I'm unable to build TornadoFX2 for myself, lots of errors that I really can't be bothered with working around/reporting at the moment. Nonetheless, thanks for the info.

**Comment by SchweinchenFuntik** [comment]
you don't need to collect it. You need to connect an additional repository read the readme to the jdk10 branch

**Comment by edvin** [comment]
Yes, as @SchweinchenFuntik wrote, you don't need to compile it yourself, just grab the latest version published to oss.sonatype.org.
