### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by kaushalyap** [edvin/tornadofx#1310]
I see following note in the README

> Important: TornadoFX is not yet compatible with Java 9/10
> 
> Oracle is intending to decouple JavaFX from the JDK. We will wait until the decoupled JavaFX is available and stable before upgrading TornadoFX to support it. As of now there is little value and significant effort involved in updating to JDK 9/10, while there will be an enormous value in updating to the decoupled version.

Although JavaFx is now open sourced but still TornadoFx does not have Java 9/10 support? And activity int he repo is also low.
Is this project discontinued?

**Comment by Stars-One** [comment]
I think it is not.The author of this project has worked to support the jdk9+ ,here is his new project [tornadofx2](https://github.com/edvin/tornadofx2)

**Comment by gagarin55** [comment]
It would be a good idea to put efforts into Compose for Desktop Framework by JetBrains

**Comment by SchweinchenFuntik** [comment]
@Stars-One the author just doesn't work. He is busy now. But there are people who develop

**Comment by kaushalyap** [comment]
I'll close this now since both versions of tonadofx is not that active. It is better to take a look at alternatives like Jetpack Compose Desktop.
