### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by Blazingsteal** [edvin/tornadofx#1313]
Hi 

I've been trying for a while to load a custom font in my tornadofx project but cannot seem to get it to work.
Finding resources about how this works is very limited as well. 
This is the best [example](https://stackoverflow.com/questions/42534552/how-to-load-custom-font-with-typesafe-css) I've found but that doesn't seem to work.

This is what I've tried so far:

I've created a folder called "resources" in which I've placed my fonts.
/src/main/resources/

`        val sourceSansPro = loadFont("/resources/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf", 20.0)!!
`

and setting the font with either:

`font = sourceSansPro`

or

`fontFamily = sourceSansPro.family`

but I cannot compile this.

Error: https://pastebin.pl/view/ae45f620

**Comment by SchweinchenFuntik** [comment]
version tornadofx ? Java 9+ using tornadofx 2.0-SNAPSHOT

**Comment by Blazingsteal** [comment]
Not using Tornadofx 2
Using Tornadofx 1.7.20 with java 8

**Comment by SchweinchenFuntik** [comment]
> with java 8
> at java.base/jdk.internal.reflect.

I see 9+ in the logs. Make sure to compile and run on the same jdk version

**Comment by Blazingsteal** [comment]
I checked and saw that I was using most likely using openJDK 11 to compile. I've made sure I only have java 8 now but I'm still getting an [error](https://pastebin.pl/view/23def2d2).

**Comment by SchweinchenFuntik** [comment]
show a minimal code example where the problem is reproduced

**Comment by ImSamhel** [comment]
Same problem here. Using openjdk 11 and this thing never compiles, not even with paths provided by the IDEA: 

val buttonFont = loadFont("misc/blackops.ttf",18)

It's just the Black Ops One Regular font style's ttf file renamed and put into the misc folder of my project and yet loadFont provided by tornadofx always gives the NullPointerExceptionError.

**Comment by ImSamhel** [comment]
> Same problem here. Using openjdk 11 and this thing never compiles, not even with paths provided by the IDEA:
> 
> val buttonFont = loadFont("misc/blackops.ttf",18)
> 
> It's just the Black Ops One Regular font style's ttf file renamed and put into the misc folder of my project and yet loadFont provided by tornadofx always gives the NullPointerExceptionError.

Well as it seems I was trying to change the style of a button but I have to change the font type of a text in a label to do what I wanted, that way I don't get an error, but the label of the button dissapears.

**Comment by Blazingsteal** [comment]
@SchweinchenFuntik Here's a minimal code example producing the error.

MainView.kt
`package com.example.view

import com.example.Styles
import tornadofx.*

class MainView : View("Hello TornadoFX") {
    override val root = hbox {
        label(title) {
            addClass(Styles.heading)
        }
    }
}
`

Styles.kt
`package com.example

import javafx.scene.text.FontWeight
import tornadofx.Stylesheet
import tornadofx.box
import tornadofx.cssclass
import tornadofx.px
import tornadofx.loadFont

class Styles : Stylesheet() {
    companion object {
        val heading by cssclass()
        val testFont1 = loadFont("SourceSansPro-SemiBold.ttf", 20.0)!!
//        val testFont2 = loadFont("resources/SourceSansPro-SemiBold.ttf", 20.0)!!

    }

    init {
        heading {
            padding = box(10.px)
            fontSize = 20.px
            fontWeight = FontWeight.BOLD
        }
        label {
            padding = box(10.px)
            fontSize = 20.px
            fontWeight = FontWeight.BOLD
            fontFamily = testFont1.family
        }
    }
}`

As @ImSamhel also experienced this results in a NPE when trying to load the font

**Comment by ImSamhel** [comment]
Ye well, whatever I tried to do, It won't load fonts from ttf or otf files :/

**Comment by SchweinchenFuntik** [comment]
> Ye well, whatever I tried to do, It won't load fonts from ttf or otf files :/

what is the path of your files?

**Comment by ImSamhel** [comment]
> > Ye well, whatever I tried to do, It won't load fonts from ttf or otf files :/
> 
> what is the path of your files?
> 
> PS: `val testFont1 = loadFont("/SourceSansPro-SemiBold.ttf", 20.0)!!`

val font = loadFont("/misc/Fontname.ttf", 18.0)!! is what I'm trying to do, but once I try to apply this on a label or text or anything it fails with nullpointerexception

**Comment by SchweinchenFuntik** [comment]
stacktrace

**Comment by ImSamhel** [comment]
[errur.txt](https://github.com/edvin/tornadofx/files/6103735/errur.txt)

**Comment by ImSamhel** [comment]
@SchweinchenFuntik 

Putting fonts into the resource folder really worked. I don't even know why I didn't think about it. It works for me with Java 11 and TornadoFX 1.7.2 . Thank you.

**Comment by Blazingsteal** [comment]
@ImSamhel but what about java 8 ? 
Really dont want to swap to java 9+ just to get this working...

**Comment by Blazingsteal** [comment]
![Screenshot from 2021-03-10 10-10-30](https://user-images.githubusercontent.com/32238392/110605037-00de3f80-8189-11eb-8a62-85a528a4300b.png)
![Screenshot from 2021-03-10 10-11-02](https://user-images.githubusercontent.com/32238392/110605052-03409980-8189-11eb-89ac-e173bfb252ad.png)

Already tried having it in resources folder...
Still gives NPE, guess it's not working with java 8

**Comment by Blazingsteal** [comment]
![Screenshot from 2021-03-10 10-10-30](https://user-images.githubusercontent.com/32238392/110605732-b3ae9d80-8189-11eb-8bf3-d129bcf01bff.png)
![Screenshot from 2021-03-10 10-16-33](https://user-images.githubusercontent.com/32238392/110605741-b5786100-8189-11eb-9887-e920f3906220.png)

Seems as the path to my ttf file wasn't correct and now works as it should as seen in the pictures above.

Embarrassing mistake but happy to not have that issue anymore :)
