### ISSUE TITLE
gridpaneConstraints works not correctly

### ISSUE THREAD

**Issue by liugangnhm** [edvin/tornadofx#1314]
```kotlin
class GridConstrainTestView : View() {
    override val root = gridpane {
        prefHeight = 600.0
        prefWidth = 600.0

        row {

            button("1")
            button("2")
            button("3")
            button("4")
        }

        row {

            button("11111111") {
                gridpaneConstraints {
                    columnSpan = 2
                }
            }
        }
    }
}
```

the row 2 column 1 works fine, 
![image](https://user-images.githubusercontent.com/743845/108956547-db423800-76aa-11eb-89b5-7650f1549cac.png)

but if we add more than 1 columns, gridpaneConstraints  works not well

```kotlin
{
    override val root = gridpane {
        prefHeight = 600.0
        prefWidth = 600.0

        row {

            button("1")
            button("2")
            button("3")
            button("4")
        }

        row {

            button("11111111") {
                gridpaneConstraints {
                    columnSpan = 2
                }
            }

            button("22222222222222222") {
                gridpaneConstraints {
                    columnIndex = 2
                    columnSpan = 2
                }
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/743845/108956660-12b0e480-76ab-11eb-980d-105d29ff2071.png)

**Comment by SchweinchenFuntik** [comment]
you add the button to the second column (in order), you also need to specify in which column to install the button

**Comment by liugangnhm** [comment]
> you add the button to the second column (in order), you also need to specify in which column to install the button

i had added `columnIndex = 2` and it did not work

**Comment by SchweinchenFuntik** [comment]
@liugangnhm I will test the code later. for now just turn on the lines in the grid
