### ISSUE TITLE
useMaxSize/useMaxWidth/useMaxHeight didn't work

### ISSUE THREAD

**Issue by gtf35** [edvin/tornadofx#1322]
I understand useMaxWidth  is the meaning of filling the parent layout:

```
class MainView : View("My View") {
    override val root = stackpane {
        alignment = Pos.TOP_CENTER
        style { backgroundColor += Color.GREEN}

        rectangle {
            height = 88.0
            useMaxWidth = true
            fill = Color.WHITE
        }
    }
}
```

But, white color width is 0:
![image](https://user-images.githubusercontent.com/22125696/112501879-90f4c980-8dc4-11eb-898d-37f025b13532.png)

**Comment by SKeeneCode** [comment]
`useMaxWidth` does not fill the parents layout, it simply sets the `maxWidth` to `Double.MAX_VALUE`

Here is its implementation:

```
var Region.useMaxWidth: Boolean
    get() = maxWidth == Double.MAX_VALUE
    set(value) = if (value) maxWidth = Double.MAX_VALUE else Unit
```

We want something like `fitToParentWidth()` which will bind a regions width property to the parents. However `rectangle` is not a `Region` however `Shape` has got a width property so we can bind it ourselves quickly.

```
 rectangle {
            widthProperty().bind(this@stackpane.widthProperty())
            height = 88.0
            fill = Color.WHITE
        }
```

If this solves the issue, please close it :)

**Comment by gtf35** [comment]
I looked at the source code at the time and found that only the maximum value was set.

I thought that infinity is to fill the parent layout, it seems i was wrong

But, why demo not bind? [demo](https://docs.tornadofx.io/0_subsection/7_layouts_and_menus#stackpane)
![image](https://user-images.githubusercontent.com/22125696/112511658-960a4680-8dcd-11eb-85ad-b7eb6fd4053b.png)

**Comment by SKeeneCode** [comment]
A stackpane is a built in layout with its own built in logic for resizing and laying out children. In the case of a `Stackpane` it will resize any resizeable children (I believe this means any `Region`) to take up as much space as possible in its layout while respecting the limits of that childs maxSize. This is `useMaxHeight/Width = true` for the button in the demo caused the stackpane to let it take up all the space it wanted.

**Comment by gtf35** [comment]
I see, thanks a lot 💕💕💕
