### ISSUE TITLE
DSL for TreeItem

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#133]
I was using ControlsFX and its Breadcrumb control the other day,  which uses TreeItem. I think we need to streamline the TreeItem with its own DSL and show a clear structure of how they are nested. 

https://docs.oracle.com/javafx/2/api/javafx/scene/control/TreeItem.html

**Comment by thomasnield** [comment]
Here's a very simple start. Maybe this is all we need. But perhaps put `treeitem()` as a function wherever it is accepted. 

```kotlin

fun <T> TreeItem<T>.treeitem(value: T? = null, op: TreeItem<T>.() -> Unit = {}): TreeItem<T> {
    val treeItem = value?.let { TreeItem<T>(it) }?:TreeItem<T>()
    treeItem.op()
    this += treeItem
    return treeItem
}

operator fun <T> TreeItem<T>.plusAssign(treeItem: TreeItem<T>) {
    this.children.add(treeItem);
}
```

**Comment by t-boom** [comment]
Java 8 link: https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TreeItem.html

**Comment by thomasnield** [comment]
Ha, I got to stop doing that...

**Comment by edvin** [comment]
Very nice. Yeah, maybe this is all we need. By the way, you set `{}` as a default value for the op - in other places we have used null, so I think we should stick with it, even though your way is kind of nicer since you don't need the null check, but using null consumes less resources.

Since ControlsFX is kind of a de facto standard for JavaFX apps, we would look into providing some builders for those controls directly as well, possibly in a side project down the road :)

**Comment by thomasnield** [comment]
You're right I wasn't thinking of consistency. And I forgot about that regarding null values. I will study the javadoc and then put in a proposed API.

**Comment by edvin** [comment]
I think your implementation is very nice. Some times people need to create a subclass of TreeItem but for most cases this is perfect :)

**Comment by thomasnield** [comment]
I will implement this into the codebase then. I can't really think of anything else that need adding?

**Comment by edvin** [comment]
Me neither :)

**Comment by thomasnield** [comment]
Okay just added this. I also am going to make the CHANGELOG a habit too. Realized I dropped the ball quickly on that.

**Comment by edvin** [comment]
Haha, sweet :) I've been trying to remember it whenever you add some goodies :)
