### ISSUE TITLE
App Needs Constructor Parens on Wiki

### ISSUE THREAD

**Issue by bekwam** [edvin/tornadofx#135]
Hi,

This is a documentation issue on the Wiki.  I think you need a pair of parens after the App in the class HelloWorldApp declaration or provide a constructor member.  I'm using class HelloWorldApp : App() {}.

-Carl

**Comment by edvin** [comment]
Thanks Carl - but what page in the Wiki was this on? The HelloWorldApp is all over the place :)

**Comment by bekwam** [comment]
It's actually in the README file which shows up on the first page of the GitHub project.  See the pull request I created.

**Comment by edvin** [comment]
Ah, sweet :) Thank you, merged now :)
