### ISSUE TITLE
Is this not longer maintained?

### ISSUE THREAD

**Issue by guenhter** [edvin/tornadofx#1359]
Hi, the last commit is almost 2 years ago. Will this not be longer maintained?

**Comment by edvin** [comment]
No, I don't maintain this project anymore. I'm not using it in any actively developed projects, and create most my frontends in SvelteKit these days :)

**Comment by guenhter** [comment]
Thx

**Comment by guenhter** [comment]
@edvin Maybe you can mark the projects you not longer maintain so that people at least know...

**Comment by edvin** [comment]
I have updated the README :)

**Comment by guenhter** [comment]
Thank you. I appreciate that. It is really helpful we have this kind of information on a repo.

**Comment by edvin** [comment]
I agree, my apologies for not adding it sooner :)

**Comment by guenhter** [comment]
You built up a decent community around your project. This is very impressive. 
Do you think it is worth creating a github Group "TornadoFX" where you donate all your TornadoFX related projects to and let the community then maintain it?

**Comment by edvin** [comment]
I'm willing to pass it on to someone who'd commit to working on it for sure :)
