### ISSUE TITLE
Guilde is not available

### ISSUE THREAD

**Issue by bykka** [edvin/tornadofx#1361]
Url https://edvin.gitbooks.io/tornadofx-guide/content/ is not available. It says 401 Unauthorized.

<img width="1669" alt="image" src="https://github.com/edvin/tornadofx/assets/489997/b8e13ddb-c1a1-4c2b-bc29-c4521e3e17a3">

**Comment by edvin** [comment]
It seems to work fine now, perhaps a temporary issue with gitbooks.

**Comment by SchweinchenFuntik** [comment]
@edvin I can't get the link to work, same error.
