### ISSUE TITLE
TableView#useCheckBox() not binding at all

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#140]
Can you guys humor me and create a simple test case showing the `TableView#useCheckBox()` working correctly with an `ObjectProperty<Boolean>`? This has been driving me crazy and I think we are missing something here. 

I've went all over StackOverflow. Only when I returned this custom implementation of `TableCell` does everything work correctly as found in this [SO post](http://stackoverflow.com/questions/7217625/how-to-add-checkboxs-to-a-tableview-in-javafx). 

```java

import javafx.geometry.Pos;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ContentDisplay;
import javafx.scene.control.TableCell;

public class BooleanCell<T> extends TableCell<T, Boolean> {
    private CheckBox checkBox;
    public BooleanCell() {
        checkBox = new CheckBox();
        checkBox.selectedProperty().addListener((observable, oldValue, newValue) -> {
            if(isEditing())
                commitEdit(newValue == null ? false : newValue);
        });
        this.setGraphic(checkBox);
        this.setContentDisplay(ContentDisplay.GRAPHIC_ONLY);
        this.setEditable(true);
        this.setAlignment(Pos.BASELINE_CENTER);
    }
    @Override
    public void startEdit() {
        super.startEdit();
        if (isEmpty()) {
            return;
        }
        checkBox.setDisable(false);
        checkBox.requestFocus();
    }
    @Override
    public void cancelEdit() {
        super.cancelEdit();
        checkBox.setDisable(true);
    }
    public void commitEdit(Boolean value) {
        super.commitEdit(value);
        checkBox.setDisable(true);
    }
    @Override
    public void updateItem(Boolean item, boolean empty) {
        super.updateItem(item, empty);
        if (!isEmpty()) {
            checkBox.setSelected(item);
        }
    }
}
```

**Comment by edvin** [comment]
I can confirm some weirdness, will check it out and get back to you ASAP.

**Comment by edvin** [comment]
The `CheckBoxTableCell.forTableColumn` JavaFX function we're calling simply doesn't pass the column along to the implementation. It seems like a bug in JavaFX. Looking for a workaround.

**Comment by edvin** [comment]
I created our own CheckBoxCell instead. Try now :) I also added an option to make it not editable, just show as checkbox.

**Comment by thomasnield** [comment]
Perfect! Glad to know I'm not crazy. I'll go ahead and test this out...

**Comment by edvin** [comment]
Did it work as expected, Thomas?

**Comment by thomasnield** [comment]
Just got a build onto my work computer... playing with this and the `ViewModel` right now.

**Comment by thomasnield** [comment]
Yep! This works for me! Thanks @edvin, I'll take a look at the `ViewModel` the rest of today. I got a meeting so apologize for delay in advance.

**Comment by andrzejtokarski** [comment]
I've found a very similar behaviour when running:

    import tornadofx.*
    
    class CheckBoxTest : App(CheckBoxTestWindow::class)
    
    class CheckBoxTestWindow: View() {
    
        class SomeViewModel(id: String, ignore: Boolean) {
            var id by property(id)
            var ignore by property(ignore)
        }
    
        val elements = (0..100).map { SomeViewModel(it.toString(), ignore = false) }.toMutableList().observable()
    
        override val root = tableview(elements) {
            column("Id", SomeViewModel::id)
            column("Ignore", SomeViewModel::ignore).useCheckbox(editable = true)
        }
    }
    
To replicate:
Check some checkboxes and scroll them away off the screen. When scrolled back the values are back to false.

**Comment by IARI** [comment]
how is the (not anymore so) new `CheckBoxCell` work now?

**Comment by edvin** [comment]
If you are experiencing problems, please open a new issue where you describe the problem in detail and include code and steps to reproduce.
