### ISSUE TITLE
Update CSS Documentation

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#142]
I know we have dozens of things going on, but the changes to the CSS functionality are a big deal and we should encourage people to use the new syntax. We should update all examples in the README, Wiki, and the guide as soon as possible.

I'll do this by the end of this week, but won't complain if anybody wants to get a head start on at least the README and Wiki.

**Comment by edvin** [comment]
Great initiative, Thomas. I suddenly got a heap of new coding tasks, and I feel I'm on a roll right now, so I'll keep programming for a bit :) Will help out next week if you haven't gotten to it yet though!

**Comment by thomasnield** [comment]
I didn't anticipate you would. The `ViewModel` is yet another killer feature of this framework most likely, so please hammer away on it!  I was hoping @t-boom might if he had the time to at least correct the Wiki.  I'll find time otherwise and dig through the source code and issue #123 so I can document it. I'll take care of this by the end of the week .

**Comment by t-boom** [comment]
I updated the README. I'll look at the wiki now. Did you want me to go through the guide and see if there is anything there as well? I can't edit the guide, so I'll have to let you know here or through issues there.

**Comment by thomasnield** [comment]
Don't worry about the guide yet, just the README and Wiki : ) There is quite a few things I know the CSS chapter needs fixing anyway, so I'll pull you in when I get back on that. But the Wiki will definitely help me correct the guide.

**Comment by thomasnield** [comment]
And thanks! Updating the Wiki will help save a ton of time for me since I need to re-learn it too : )

**Comment by edvin** [comment]
I love working as a team with you guys :) @t-boom you now have commit rights to the Guide as well.

**Comment by thomasnield** [comment]
@edvin Excellent! I was about to ask about that.

**Comment by thomasnield** [comment]
And I'm very glad to be here too : )

**Comment by t-boom** [comment]
I think I got everything in the wiki. I'll read over it all again to make sure I didn't miss anything, but it should be good.

@edvin Thanks

This is one of the best teams I've ever worked with, no matter how informal it may be :smiley:

**Comment by thomasnield** [comment]
Thanks @t-boom! I'll follow up later...

**Comment by edvin** [comment]
The wiki is up to date, is there anything missing from the guide or should we close this issue? :)

**Comment by thomasnield** [comment]
I still see `s()` being used in a few places. We scrapped that completely right? At least we deprecated it if I recall?

**Comment by edvin** [comment]
No it still has to be used when to target different selectors. Let's say you want to target buttons and labels:

```css
s(button, label) {
}
```

**Comment by thomasnield** [comment]
Oh, duh. That makes sense. I'll go ahead and close then for now. It looks good but I'll read again later today.

**Comment by edvin** [comment]
Too bad `,` can't be an operator function, then we could get rid of it :)

**Comment by thomasnield** [comment]
I can see why `,` would mess with the existing Kotlin language though...

**Comment by edvin** [comment]
Yeah, not that's is stopping Scala from doing it, but I'm a big fan of drawing the line somewhere. Scala allows everything, and the results are incomprehensible DSLs because people go crazy with operation overloading. The conservative approach of Kotlin is way safer.

**Comment by thomasnield** [comment]
I agree. Tried to learn Scala but kind of walked away especially after I saw Kotlin. Much more practical and less academic.
