### ISSUE TITLE
Let App accept class parameters

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#148]
When creating an app, the main app class is almost always:

```kotlin
class MyApp : App() {
    override val primaryView = MyView::class

    init {
        importStylesheet(MyStyles::class)
    }
}
```

Would it be a good idea (or even possible) to let `App` accept those values as parameters? Something like

```kotlin
open class App(primaryView: KClass<out View>? = null, vararg stylesheet = KClass<out Stylesheet>) : Application() {
    open val primaryView: KClass<outView> = primaryView ?: DeterminedByParameter::class

    init {
        stylesheet.forEach { importStylesheet(it) }
    }

    ...
}
```

Then you could use

```kotlin
class MyApp : App(MyView::class, MyStyles::class)
```

Of course, the old way would still work fine.

**Comment by t-boom** [comment]
I'm not sure if this would actually provide any benefit. It just popped into my head.

**Comment by edvin** [comment]
I like it a lot. We should embrace everything that reduces boiler plate!

**Comment by t-boom** [comment]
Added

**Comment by edvin** [comment]
Very nice! This release will be just about reducing boiler plate it seems :)

**Comment by t-boom** [comment]
I didn't think about adding an icon. Should that be an option as well?

**Comment by edvin** [comment]
That would be nice.
