### ISSUE TITLE
More TableView column builders

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#152]
There are a couple of use cases that don't seem to be handled easily.

First, there should be a way to handle [nested columns](https://docs.oracle.com/javase/8/javafx/user-interface-tutorial/table-view.htm#CJAFIDEI). Something like

```kotlin
column("Name") {
    column("First", Person::firstNameProperty)
    column("Last", Person::lastNameProperty)
}
```

~~Second, it would be nice if `column()` could take a `(T) -> Binding` as it's second parameter. That way you could have something like~~

~~_`code removed`_~~

There are probably some others, those are just the two I thought of.

**Comment by t-boom** [comment]
@edvin pointed out the latter is already possible, though a bit cumbersome, using the following syntax:

```kotlin
column<Person, String>("Name", Bindings.createStringBinding(
    Callback { "${it.value.firstName} ${it.value.lastName}" },
    it.firstNameProperty,
    it.lastNameProperty
))
```

**Comment by thomasnield** [comment]
What's the status on the nested columns part? I ran into a need for it today. Might put in a PR if no WIP is out there...

**Comment by t-boom** [comment]
I don't think it's been worked on. We all got caught up with other things.

**Comment by edvin** [comment]
I haven't look at it either. Trying to finish up the first iteration of KDBC this weekend, and I'd really like to work on the guide first, but let me know if you need this ASAP and I'll change priorities @thomasnield

**Comment by thomasnield** [comment]
No worries right now, I'll take care of it later or even put it off. I don't need it super urgently yet.

**Comment by thomasnield** [comment]
Started working on nested columns finally. This is what I have for all `TableColumn`-related functions. I couldn't think of any other way than creating a `nestedcolumn()` function to prevent signature clashes. 

```kotlin

/**
 * Create a column with a value factory that extracts the value from the given callback.
 */
fun <S, T> TableView<S>.column(title: String, valueProvider: (TableColumn.CellDataFeatures<S, T>) -> ObservableValue<T>): TableColumn<S, T> {
    val column = TableColumn<S, T>(title)
    column.cellValueFactory = Callback { valueProvider(it) }
    columns.add(column)
    return column
}

/**
 * Create a column using the propertyName of the attribute you want shown.
 */
fun <S, T> TableView<S>.column(title: String, propertyName: String): TableColumn<S, T> {
    val column = TableColumn<S, T>(title)
    column.cellValueFactory = PropertyValueFactory<S, T>(propertyName)
    columns.add(column)
    return column
}

/**
 * Create a nested column with a value factory that extracts the value from the given callback.
 */
fun <S, T> TableColumn<S,T>.column(title: String, valueProvider: (TableColumn.CellDataFeatures<S, T>) -> ObservableValue<T>): TableColumn<S, T> {
    val column = TableColumn<S, T>(title)
    column.cellValueFactory = Callback { valueProvider(it) }
    columns.add(column)
    return column
}

/**
 * Create a nested column using the propertyName of the attribute you want shown.
 */
fun <S, T> TableColumn<S,T>.column(title: String, propertyName: String): TableColumn<S, T> {
    val column = TableColumn<S, T>(title)
    column.cellValueFactory = PropertyValueFactory<S, T>(propertyName)
    columns.add(column)
    return column
}

/**
 * Create a column holding children columns
 */
fun <S> TableView<S>.nestedcolumn(title: String, op: (TableColumn<S,Any?>.() -> Unit)? = null): TableColumn<S,Any?> {
    val column = TableColumn<S, Any?>(title)
    op?.invoke(column)
    columns.add(column)
    return column
}
```

**Comment by edvin** [comment]
Great work! Let me think about this for a short while, maybe we can come up with an even smoother approach. I have an idea that I need to think about a little and then try something. Will get back to you shortly.

**Comment by edvin** [comment]
I have committed a suggestion that gives us this functionality without the need to duplicate the column builders. Basically, the TableView gets a property containing the "target" for new columns added, and the nestedColumns function registers itself as a target for new columns. This would allow us to write:

```kotlin
class NestedTableColumns : View("Nested Table Columns") {
    data class Person(val name: String, val primaryEmail: String, val secondaryEmail: String)

    val people = FXCollections.observableArrayList(
            Person("John Doe", "john@doe.com", "john.doe@gmail.com"),
            Person("Jane Doe", "jane@doe.com", "jane.doe@gmail.com")
    )

    override val root = tableview(people) {
        column("Name", Person::name)
        nestedColumn("Email addresses") {
            column("Primary Email", Person::primaryEmail)
            column("Secondary Email", Person::secondaryEmail)
        }
    }
}
```

![](https://cloud.githubusercontent.com/assets/977035/17839101/59b6896a-67de-11e6-9459-d0fb1eee7e59.png)

**Comment by thomasnield** [comment]
That looks really nice.

**Comment by edvin** [comment]
Should we go with this solution then? It's less to maintain and it supports deep nesting as well.

**Comment by thomasnield** [comment]
I think so let's do it. Thanks for your help on this

**Comment by edvin** [comment]
Great :) Closing!
