### ISSUE TITLE
[Low Priority] Create nice bindings support

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#153]
It would be nice if there was support for nicer creation of bindings. For example, if you wanted to create a full name binding for a `Person` with a `firstNameProperty` and `lastNameProperty`, instead of

```kotlin
Bindings.createStringBinding(
    Callable { "${person.firstName ${person.lastName}" },
    person.firstNameProperty,
    person.lastNameProperty
)
```

you could write

```kotlin
person.stringBinding(person.firstNameProperty, person.lastNameProperty) {
    "${person.firstName ${person.lastName}"
}
```

**Comment by thomasnield** [comment]
Although not using Kotlin, have you looked at Tomas Mikula's work?
https://github.com/TomasMikula/EasyBind

Also with RxJavaFX/RxKotlinFX, you can do the following...

```kotlin
Observable.combineLatest( 
     person.firstNameProperty,
     person.secondNameProperty
) { first,last -> "$first $last" }.toBinding()
```

**Comment by thomasnield** [comment]
It looks like ReactFX has this feature too. 
https://github.com/TomasMikula/ReactFX#combine

**Comment by thomasnield** [comment]
I guess it comes down to how badly we want to reinvent the wheel but using Kotlin syntax, and how much we want to push Rx on folks.

**Comment by thomasnield** [comment]
Sorry that closing was an accident.

**Comment by t-boom** [comment]
Interesting, though it looks like both require exactly two observables. While that is the most common use case, JavaFX bindings are designed to accept an arbitrary amount of observables. You could, for example, create a binding that listens to a first name, last name, middle name, and birthdate property and generate something like `"Alice A. Anderson (23)".

I understand you can use multiple combines in sequence or something, but only having experience with the JavaFX method I can't say which would lead to a cleaner user experience.

**Comment by thomasnield** [comment]
Actually, all the combining operators (e.g. `merge()`, `zip()`, `combineLatest()`, `concat()`, etc) are overloaded to support up to nine Observables of different types. Any more than that it will resort to varargs. Another benefit with all these combining operators is they will merge together in a non-blocking way even if they all are pushing items on different threads.

http://reactivex.io/RxJava/javadoc/rx/Observable.html#merge(rx.Observable,%20rx.Observable)

**Comment by t-boom** [comment]
I didn't realize that. Good to know.

**Comment by thomasnield** [comment]
In my opinion, Bindings (and JavaFX's `ObservableValue` in general) were a step in the right direction, but only solve 5% of the problem. I sometimes wonder why some implementation of Rx wasn't just made part of JavaFX, although I'm pretty sure it is because Oracle knew others would build it. They did the hard part and provided all the hooks via `ObservableValue`, `ObservableList`, etc...

**Comment by thomasnield** [comment]
Hmm I take that back. RxJava was pretty dang hard to build.  Netflix and David Karnok did the labor there, which is probably why Oracle didn't sign up for it.

**Comment by t-boom** [comment]
In that case, it appears my limited understanding of Rx is the limiting factor here.

**Comment by thomasnield** [comment]
Haha put it in your "queue of a dozen things to learn" like every other developer.  But its ROI will pay for itself several times over.

**Comment by t-boom** [comment]
This was added, but do to limitations with type erasure it's implemented as:

```kotlin
stringBinding(person, person.firstNameProperty, person.lastNameProperty) {
    "${person.firstName ${person.lastName}"
}
```
