### ISSUE TITLE
No way for customize App's stage and it's scene properties

### ISSUE THREAD

**Issue by mojtab23** [edvin/tornadofx#155]
I want to do customize some of `stage` and `scene` properties like `scene.height` and `scene.width` I asked this question http://stackoverflow.com/q/38543474/3291867 and now I know that I should override App's `start(stage: Stage)` method but with this method `private fun determinePrimaryView(): KClass<out View>` at `App` class I cannot do this easily (without extra work)
I tried to override it in this way:

```kotlin
 override fun start(stage: Stage) {
        FX.registerApplication(this, stage)

       try {
            // this line has error (Cannot access 'determinePrimaryView': it is 'invisible_fake' in 'MyApp' class )
            val view = find(determinePrimaryView())

            stage.apply {
                // I changed this line from (App.start) method
                scene = Scene(view.root, 800.0, 600.0)
                view.properties["tornadofx.scene"] = scene
                scene.stylesheets.addAll(FX.stylesheets)
                titleProperty().bind(view.titleProperty)
                hookLayoutDebuggerShortcut()
                show()
            }
            FX.initialized.value = true
        } catch (ex: Exception) {
            Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), ex)
        }
    }
```

**Comment by edvin** [comment]
You can change the width of the scene by changing the width of the stage, so simply override `start` and let it do it's job before you change the dimensions:

```kotlin
override fun start(stage: Stage) {
    super.start(stage)
    stage.width = 800.0
    stage.height = 600.0
}
```

If this doesn't meet your requirements we could create an overridable function in `App` that is responsible for creating the scene for the primary view. Let me know if you need this.

**Comment by edvin** [comment]
I just added a function that will let you create the primary scene yourself. This will be in 1.5.3:

```kotlin
override fun createPrimaryScene(view: View) = Scene(view.root, 800.0, 600.0)
```

**Comment by mojtab23** [comment]
Thank you so much, this is good for me.

**Comment by edvin** [comment]
You're welcome :)
