### ISSUE TITLE
Using asyncitems in TableView copies the items

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#157]
If you have a builder that does something like

```kotlin
tableview<Element> {
    whenDocked { asyncItems { elements } }
    ...
}
```

The `elements` list contents are copied into the list. This means you can't delete something from `elements` and have the change show up in the table. This makes sense if the call is to a function, but it `elements` is a lazy loaded property on a controller or something this can get frustrating.

(This is because asyncItems uses `items.setAll(it)` instead of `items = it`.)

There could, however, be downsides to changing the functionality as any existing references to items will no longer work, so the current way may be the best way to do it. If we keep it this way, it may be worth a footnote in the wiki / guide that there is no point holding onto a reference of the value returned in `asyncItems`.

**Comment by t-boom** [comment]
This is because `asyncItems` uses `items.setAll(it)` instead of `items = it`

**Comment by edvin** [comment]
This is by design, because if you have installed a `SortedList` or some other special list as the `items` property, you might not want it overwritten. The list might have it's comparator bound to the `TableView.comparatorProperty` etc.

We could add a boolean `overwrite`option to the `asyncItems` with a default value of false, and do `items = it` when overwrite is true?

**Comment by t-boom** [comment]
That's a possible solution, but I'm not sure if it's even desirable. Pretty much any frustration I can come up with for the current method is easy to fix by simply referring to the items list instead of the elements list.

**Comment by edvin** [comment]
I'm actually not sure I understand your use case. If elements are already loaded, there is no need to wrap it in `asyncItems`. Or is `elements` in the code above a `val` with a `get` function?

**Comment by t-boom** [comment]
Sorry, `elements` is just a placeholder. It can be replaced with anything that returns an `ObservableList<Element>`. I should have made that more clear. The lazy loaded example was something like

```kotlin
whenDocked { asyncItems { controller.elements } }
```

Where the controller has

```kotlin
val elements: ObservableList<Element> by lazy { takeForeverToGetElements() }
```

**Comment by t-boom** [comment]
Actually, is there any reason `asyncItems` takes `ObservableList<T>` instead of `Collection<T>`? If it's just copying the data over, why should it be observable?

**Comment by edvin** [comment]
You are right, we should change that to `Collection<T>`. You should also add yourself to the developers section of `pom.xml` btw :)

**Comment by t-boom** [comment]
Will do :)
