### ISSUE TITLE
CSS Import

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#158]
Just an Idea

It's common to separate CSS files into a base file and have others that specialize (e.g. base.css, viewer.css, dialog.css, etc.) and have them start with `@import url("base.css");`.

It would be nice to have similar functionality for the CSS DSL. We can't do this through inheritance if we want to support multiple imports, but we could have imported classes be passed to the constructor of `Stylesheet`

```kotlin
class DialogStyle : Stylesheet(BaseStyle::class, ModalStyle::class) {
    ...
}
```

I'm not sure what would be the best way to implement this in code. The easiest solution would probably be to add an `@import url("[generated url]");` for each class in the list, but that would mean rerendering each style every time (not a huge deal, but it could be a small performance issue).

**Comment by t-boom** [comment]
If we assume the stylesheet can't change once created, we could have the rendered output and the generated URL be lazy and have the stylesheets be singletons, but that would create a memory overhead, especially with large styles.

**Comment by edvin** [comment]
I don't think it's an issue that the stylesheets are rerendered when they are imported, and since they are programmatic constructs until they are rendered, they can theoretically be changed. If JavaFX supports the `@import url("base.css")` styles, maybe we should just support that with a directive that is rendered as exactly that?

Since ordering matters, you could import your base styles before or after other styles even. This sounds like the most flexible solution, and probably the one with least work. What do you think?

**Comment by t-boom** [comment]
How do you mean?

**Comment by edvin** [comment]
Forget about the ordering bit, when I think about it that's probably not relevant. Your constructor idea is good. I tried a poor man's implementation by changing the Stylesheet constructor to this:

```kotlin
open class Stylesheet(vararg var imports: KClass<out Stylesheet>) : SelectionHolder, Rendered {
```` 

Then I just overrode the render function to add imports first:

```kotlin
    override fun render() = imports.map { "@import url(css://${it.java.name})\n" }.joinToString("\n") +
            selections.joinToString(separator = "") { it.render() }
```

This seems to work great :) You probably want to implement this slightly cleaner, but it worked to test the concept. What do you think, do we need something more advanced or would this cover it?

**Comment by t-boom** [comment]
That's pretty much exactly how I would have done it (possibly adding another `'\n'` at the end of the imports to make it prettier).

Why did you define `imports` as a `var`? Assuming imports will always be at the top of the file, declaring them as a `val` in the constructor would work fine. Is there any reason you'd want to modify the imports when defining the styles? It could make the user thing order matters.

**Comment by t-boom** [comment]
I pushed up a `feature/css-import` branch that has the changes as well as a demo that uses it `tornadofx.testapps.ImportStyles`.

**Comment by edvin** [comment]
Ah, I didn't know about postfix in string joins.. You know all the small Kotlin nuggets :)

The `var` was simply a typo. This looks great. My initial thought was to add imports like a property or selector, so they would render exactly where you wanted them, but that's not necessary.

Will you add an entry to the changelog and merge?

**Comment by t-boom** [comment]
Will do
