### ISSUE TITLE
Type safe CSS doesn't work with background-image

### ISSUE THREAD

**Issue by mikehearn** [edvin/tornadofx#167]
Generated CSS looks like this:

`-fx-background-image: "url("/file.jpg")";`

which is not the correct syntax.

**Comment by t-boom** [comment]
Crap, that was supposed to be a `raw`. I'll have to look and see what's happening.

**Comment by t-boom** [comment]
@mikehearn How are you defining that? Something like `backgroundImage += "url(\"/file.jpg\")"`? Would you prefer if it took a URL directly: `backgroundImage += Url("/file.jpg")`?

**Comment by mikehearn** [comment]
Yeah it takes a string, right?

Should take URI not URL. URL does DNS lookups at inopportune times.

**Comment by t-boom** [comment]
Indeed.

It looks like we would have the same problem with `-fx-image` for `ImageView`s, `-fx-graphic` for `DialogPane`s, and `-fx-border-image-source` for, well, anything with a border. I'll create a fix.

**Comment by t-boom** [comment]
@mikehearn I pushed up a fix. Can you test it?

**Comment by edvin** [comment]
I did some tests myself, seems to be working great.
