### ISSUE TITLE
Unable to close modal fragment windows if block is set to true while calling openModal()

### ISSUE THREAD

**Issue by socketbind** [edvin/tornadofx#172]
Hi,

I have run into an issue while implementing a simple coordinate picker. The coordinate picker is subclassed from Fragment and works similarly as FileChooser from the standard library:

```kotlin
val coordinatePicker = CoordinatePicker()
val coordinate: Coordinate? = coordinatePicker.showPickerDialog(owner)
```
The showPickerDialog() method makes a call to openModal(owner = windowOwner, block = true) then returns the value of its internal coordinate instance representing the current coordinate. Pressing the OK or Cancel button should close the window but calling closeModal() from the onAction event when block is set to true does nothing as modalStage is set to null while the window is open.

I am using the 1.5.5 release. Looking at Fragment::openModal the issue seems to be that the modalStage field is not set because the execution is blocked in an apply lambda:

```kotlin
modalStage = Stage(stageStyle).apply {
    titleProperty().bind(titleProperty)
    initModality(modality)
    if (owner != null) initOwner(owner)

    ... other code ...
    
    if (block) {
        if (FX.reloadStylesheetsOnFocus || FX.reloadViewsOnFocus) {
            thread(true) {
                Thread.sleep(5000)
                configureReloading()
            }
        }
        showAndWait() // delays the assignment when block is set to true
    } else {
        show()
        configureReloading()
    }
}
```

I would like to suggest to make the Stage instance creation separate from the apply call so the blocking lambda does not delay the assignment.

**Comment by edvin** [comment]
Hi and thanks for reporting this. The issue has already been resolved, can you verify that this works as expected with 1.5.6-SNAPSHOT? We will release 1.5.6 next week with this fix :) Let me know if the current fix works for you!

**Comment by socketbind** [comment]
Oh, sorry for that, I should have looked at the code in the repository. 

After switching to a snapshot version it does indeed solve the issue, thank you.

**Comment by edvin** [comment]
Great, thank you again for reporting :)
