### ISSUE TITLE
Error in Wiki

### ISSUE THREAD

**Issue by programaths** [edvin/tornadofx#173]
The page 
[wiki/ViewModel](https://github.com/edvin/tornadofx/wiki/ViewModel) contains an error in the source code example.

The model is defined like this : 
```kotlin
    class PersonModel(var source: Person) : ViewModel() {
        val name = bind { source.nameProperty() }
        val title = bind { source.titleProperty() }
    }
```

You may want to change it to:
```kotlin
    class PersonModel(var person: Person) : ViewModel() {
        val name = bind { person.nameProperty() }
        val title = bind { person.titleProperty() }
    }
```

Since it is used like this :
```kotlin
                // Update the person inside the view model on selection change
                model.rebindOnChange(this) { selectedPerson ->
                    person = selectedPerson ?: Person()
                }
```

**Comment by edvin** [comment]
Thanks for pointing that out. It seems I've used person/source inconsistently. I'll sort it out :)

**Comment by edvin** [comment]
There, fixed :) I was also missing `var` in a couple of places. I'll make sure these changes goes into the upcoming guide as well. Thanks again!

**Comment by edvin** [comment]
The guide has also been updated :)

https://edvin.gitbooks.io/tornadofx-guide/content/11.%20ViewModel%20and%20Validation.html
