### ISSUE TITLE
KotlinObjectProperty

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#177]
This is a discussion to resolve the issues with PR #176

**Comment by t-boom** [comment]
It seems there are two different ideas as to how the `KotlinObjectProperty` is supposed to work. They are:

1. Make an ObjectProperty that has better control over nullability
2. Make an ObjectProperty that is non-nullable

Both have their merits, but both have interesting drawbacks.

**Comment by t-boom** [comment]
# Better Control over Nullability

Solution 1

```kotlin
class KotlinObjectProperty<T>(
        initialValue: T,
        bean: Any? = null,
        name: String = ""
) : SimpleObjectProperty<T>(bean, name, initialValue), ReadWriteProperty<Any, T> {
    override fun get(): T = super.get() ?: defaultValue
    override fun set(value: T) = super.set(value)
    // Required to ensure property.value is not system type
    override fun getValue(): T = super.getValue() ?: defaultValue
    override fun setValue(value: T) = super.setValue(value)
    // Required to make delegation not system type
    override fun getValue(thisRef: Any, property: KProperty<*>) = get()
    override fun setValue(thisRef: Any, property: KProperty<*>, value: T) = set(value)
}
```

The problem with this solution is you can still do `(property as Property<Type>).value = null` which will compile, but will fail when you try to get the value.

Solution 2

```kotlin
class KotlinObjectProperty<T>(
        val defaultValue: T,
        bean: Any? = null,
        name: String = ""
) : SimpleObjectProperty<T>(bean, name, defaultValue), ReadWriteProperty<Any, T> {
    override fun get(): T = super.get() ?: defaultValue
    override fun set(value: T) = super.set(value)
    // Required to ensure property.value is not system type
    override fun getValue(): T = super.getValue() ?: defaultValue
    override fun setValue(value: T) = super.setValue(value)
    // Required to make delegation not system type
    override fun getValue(thisRef: Any, property: KProperty<*>) = get()
    override fun setValue(thisRef: Any, property: KProperty<*>, value: T) = set(value)
}
```

This one seems more robust, but has a subtle failure:

```kotlin
val prop = KotlinObjectProperty<String?>("Test")
val prop2 = SimpleStringProperty("Test 2")

prop.bind(prop2)
prop2.value = null

println(prop.value)
```

What gets printed is `"Test"`, even though null is actually a perfectly valid value for ` KotlinObjectProperty<String?>`.

**Comment by t-boom** [comment]
# Non-Nullable


Solution 1

```kotlin
class KotlinObjectProperty<T>(
        val defaultValue: T,
        bean: Any? = null,
        name: String = ""
) : SimpleObjectProperty<T>(bean, name, defaultValue), ReadWriteProperty<Any, T> {
    override fun get(): T = super.get() ?: defaultValue
    override fun set(value: T) = super.set(value)
    // Required to ensure property.value is not system type
    override fun getValue(): T = super.getValue() ?: defaultValue
    override fun setValue(value: T) = super.setValue(value)
    // Required to make delegation not system type
    override fun getValue(thisRef: Any, property: KProperty<*>) = get()
    override fun setValue(thisRef: Any, property: KProperty<*>, value: T) = set(value)
}
```

The problem with this solution is `(property as Property<Type>).value = null` will compile, but will fail at runtime.

**Comment by slimaku** [comment]
Personally, I would prefer the first solution of the first idea (Better Control over Nullability) because I'd like to be able to have nullable properties, where `null` mean something. (Usually it would mean 'unspecified')

Unfortunatly cases like  `(property as Property<Type>).value = null` are impossible to protect because there is plain old java behind the scene. And for me, if a developper cast an instance (for exemple `property as Property<Type>`), he is taking the responsability to use correctly the casted instance. And in this case, to not assign a null value if the property is not nullable. You can encounter the same kind of limit with pure kotlin : `(listOf(1) as? MutableList<Int>)?.add(2)` will compile, but fail at runtime.

Idealy, I'd like to be able to declare and bind a model like that :
```kotlin
class MyClass {
    val nameProperty = KotlinObjectProperty<String>("")
    var name by nameProperty  // The infered type would be String

    val ageProperty = KotlinObjectProperty<Int?>(null)
    var age by ageProperty // The infered type would be Int?
}
```

with such model the compilator would help me, for exemple : 
```kotlin
val obj = MyClass()
obj.nameProperty.onChange { newValue ->
    // here newValue is asserted as not-null and I would't need to check it's nullity
} 
obj.ageProperty.onChange { newValue ->
    // here newValue is nullable and I would have to check it's nullity
}
```

**Comment by t-boom** [comment]
There is still another issue with that solution:

```kotlin
val prop = KotlinObjectProperty<LocalDate>(LocalDate.now())
val prop2 = SimpleObjectProperty<LocalDate>(LocalDate.MAX)
prop.bind(prop2)
prop2.value = null
println(prop.value.dayOfWeek)  // Will throw NPE
```

Because internally this is done in Java, the value of the `KotlinObjectProperty` can still hold `null`, but the definition tricks the Kotlin compiler into thinking it can't, so `prop.value.dayOfWeek` compiles without a problem. When run though, `prop.value` returns null, causing an NPE.

**Comment by t-boom** [comment]
The advantage of solution 2 is that you will never get an NPE, but when a binding is null, you get the default value, even if null is acceptable.

**Comment by t-boom** [comment]
I may have come up with a fix for solution 2 using the `invoke` hack on a companion object. Let me see if it will work.

**Comment by t-boom** [comment]
Here's a solution that fixes the non-nullable solution:

```kotlin
class KotlinObjectProperty<T : Any>(
        val defaultValue: T,
        bean: Any? = null,
        name: String = ""
) : SimpleObjectProperty<T>(bean, name, defaultValue), ReadWriteProperty<Any, T> {
    override fun get(): T = super.get() ?: defaultValue
    override fun set(value: T?) = super.set(value)
    // Required to ensure property.value is not system type
    override fun getValue(): T = super.getValue() ?: defaultValue
    override fun setValue(value: T?) = super.setValue(value)
    // Required to make delegation not system type
    override fun getValue(thisRef: Any, property: KProperty<*>) = get()
    override fun setValue(thisRef: Any, property: KProperty<*>, value: T) = set(value)
}
```

The advantage of this is, well, it works. If you want a nullable object property, using `SimpleObjectProperty` works just fine:

```kotlin
val dateProperty = SimpleObjectProperty<LocalDate?>(LocalDate.now())
var date by dateProperty  // This is already LocalDate?, not LocalDate!
```

**Comment by t-boom** [comment]
Would it be better to call it `DefaultObjectProperty` or NullSafeObjectProperty`?

**Comment by t-boom** [comment]
See 781e77b for a demonstration

**Comment by edvin** [comment]
Should we close this issue until somebody needs this feature?

**Comment by t-boom** [comment]
Probably a good idea
