### ISSUE TITLE
Allow setting controller in FXML

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#179]
When the `fx:controller` attribute on a view (or fragment) is set the application receives an exception upon creation: `javafx.fxml.LoadException: Controller value already specified.`

I'm not sure how to properly implement this in a way that it still supports FXML defined views that do not have the controller attribute set.

**Comment by edvin** [comment]
You should not set `fx:controller` in the *FXML* file, as the controller is dynamically provided by TornadoFX. Is there a specific reason that you need to set the controller in the FXML file?

**Comment by dominiks** [comment]
Yes, sorry, should have added my reasoning. Setting the controller in the FXML file enabled IntelliJ to check if event handlers are typed correctly and reachable. Helps me to avoid some bugs before I compile. 

Though it's also possible for me to just add the attribute for testing and remove it before running.

**Comment by edvin** [comment]
I see, that is indeed a valid use case. I will investigate how much work it would be to implement a custom FXMLLoader to deal with this.

**Comment by edvin** [comment]
I had a look. The way FXMLLoader is implemented, it has to be known in advance if the FXML file has an `fx:controller` attribute or not if we are to override it. I can come up with a couple of (bad) solutions:

1. Pass in a boolean to the `fxml()` delegate telling it to override the configured `fx:controller` attribute. Basically this would have to be set to true if you set `fx:controller` in your FXML file.

2. Read the FXML file manually first, parse it and remove the `fx:controller` attribute. This is bad for performance reasons. In practice it might not be a big thing though.

I don't really like any of the solutions. I will think about this a little more and get back to you again :)

**Comment by edvin** [comment]
Hmm... An even crazier solution would be to temporarily rename the `FXMLLoader.FX_CONTROLLER_ATTRIBUTE` static final property so it doesn't match `fx:controller` while the loader is running. This could work, but it's not pretty.

**Comment by edvin** [comment]
Changing the `FXMLLoader.FX_CONTROLLER_ATTRIBUTE` value via Reflection is a no-go, since the string is being inlined, so changing it does nothing.

**Comment by edvin** [comment]
I have implemented solution number 1 from above. You can now keep your `fx:controller` attribute, provided that you supply the `hasControllerAttribute` parameter to the fxml call:

```kotlin
override val root: VBox by fxml(hasControllerAttribute = true)`
```

I realize this is probably not the solution you hoped for, but it is the best we can do without duplicating a substantial part of the `FXMLLoader` code, which would be bad for stability going forward.

It should at least let you keep the attribute and enjoy code completion etc, while still being able to use the FXML file with TornadoFX :)

**Comment by dominiks** [comment]
I think this solution is the best I could hope for but a totally automatic one ;) Thank you for your quick response and solution for this minor wish.

**Comment by edvin** [comment]
Good news - I managed to make it without a parameter, by implementing a special `LoadListener`. I have talked to Jonathan Giles at Oracle and he confirms that the LoadListener will be public API in JDK9, so this should be future proof. It will require a signature change for JDK9, but the TornadoFX API will stay the same. Can you confirm this is indeed working for you without the parameter now?

**Comment by edvin** [comment]
Unfortunately, this seems to have unwanted side effects. The controller is beeing set too late, so we have to revert to the `hasControllerAttribute` approach. Very sorry about that, the LoadListener just doesn't give us enough hooks.

**Comment by sathvik87** [comment]
I had the same issue when following the tutorial https://github.com/edvin/tornadofx/wiki/FXML
IntelliJ complained that there is no controller attached. When I attached, app failed with duplicate controller attached. 
It would be nice to add the detail about controller in the wiki for fxml

**Comment by edvin** [comment]
@sathvik87 Agreed - would you care to submit a PR for a change against the guide?

This is the official documentation now:

https://edvin.gitbooks.io/tornadofx-guide/content/part1/10.%20FXML.html

I'll link to this page from the Wiki page.
