### ISSUE TITLE
Vertical Label Position affects TextArea sizing on a form

### ISSUE THREAD

**Issue by gtnarg** [edvin/tornadofx#182]
The following view produces the following output:

```
import javafx.geometry.Orientation
import tornadofx.*


class FormView : View("My Form") {
    override val root = stackpane {
        form{

           fieldset("FieldSet"){

               //labelPosition = Orientation.VERTICAL

                field("Field 1"){
                    textarea() {
                       prefRowCount = 2
                    }
                }

               field("Field 2"){
                   textarea() {
                        prefRowCount = 10
                   }
               }
            }
        }
    }
}
```
![image](https://cloud.githubusercontent.com/assets/1252704/18566827/7a8af58e-7b63-11e6-8f72-422a7b40f9d4.png)

If I set the label orientation to Orientation.VERTICAL  I get the following:

![image](https://cloud.githubusercontent.com/assets/1252704/18566893/bf23cb6c-7b63-11e6-97aa-1dd5af016cc5.png)

Regards,
Grant

**Comment by edvin** [comment]
Thanks for reporting this :) The bug has been fixed and committed to master. It will be in version 1.5.6 which will be released soon. You can try it out by checking out master already now :)

**Comment by edvin** [comment]
This is the result after the fix:

![image](https://cloud.githubusercontent.com/assets/977035/18577068/26d9ee16-7be7-11e6-8184-8181b6282c8f.png)

**Comment by gtnarg** [comment]
Thanks for the quick response!
