### ISSUE TITLE
Dead Link on TypeSafeBuilders Builders.kt

### ISSUE THREAD

**Issue by bekwam** [edvin/tornadofx#187]
Clicking on the Builders.kt link in the first paragraph goes to a 404

**Comment by edvin** [comment]
Thanks, Carl.

Is this in the guide or the wiki? :) We have a separate project for issues with the guide btw: https://github.com/edvin/tornadofx-guide/issues

**Comment by bekwam** [comment]
Wiki > Documentation > TypeSafeBuilders

**Comment by edvin** [comment]
Thanks again :) Fixed now. We split the builders into multiple files so I have updated the reference.
