### ISSUE TITLE
Helper extension functions

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#188]
I've run across a few places where convenience extension functions would be nice:

``` kotlin
fun Node.disabledWhen(binding: ObservableBooleanValue): Node = apply { disableProperty().bind(binding) }
fun Node.visibleWhen(binding: ObservableBooleanValue): Node = apply { visibleProperty().bind(binding) }

fun ObservableList<*>.sizeBinding() = Bindings.size(this)!!
fun ObservableSet<*>.sizeBinding() = Bindings.size(this)!!
fun ObservableArray<*>.sizeBinding() = Bindings.size(this)!!
fun ObservableMap<*, *>.sizeBinding() = Bindings.size(this)!!

fun CheckBox.onChange(op: (Boolean) -> Unit) = selectedProperty().onChange(op)
fun Toggle.onChange(op: (Boolean) -> Unit) = selectedPRoperty().onChange(op)
fun ToggleGroup.onChange(op: (Toggle?) -> Unit) = selectedToggleProperty.onChange(op)

fun <T> ListView<T>.forEach(op: (T) -> Unit) = items.forEach(op)
fun <T> TableView<T>.forEach(op: (T) -> Unit) = items.forEach(op)
```

There may be more in the same vein as these, so we should look through commonly used properties to see if there are similar additions we could create.

**Comment by t-boom** [comment]
I'm not sure if the `sizeBinding` functions are particularly useful since `Bindings.size` is only two characters longer.

**Comment by edvin** [comment]
Great initiative. I will look through some of my apps to see if what I find there as well.

**Comment by edvin** [comment]
I have added the `disabledWhen` and `visibleWhen` along with a few others. The `onChange` additions are great, but I don't know about the `forEach` functions on ListView/TableView - is it normal to access the item control to access the items instead of the item property?

**Comment by edvin** [comment]
I also added `removeWhen` and some others. This declarative approach works great, so I'll continue to add functions in this matter when I see an opportunity.  I think we have covered most of these now, so I'll close.

**Comment by aymen083** [comment]
I suggest to add mangedWhen also on nodes :

fun Node.managedWhen(binding: ObservableBooleanValue): Node = apply { managedProperty().bind(binding) }

**Comment by edvin** [comment]
In my experience, you very seldomly set managed without also setting visible. For that we have the `removeWhen`, which sets both managed and visible. I'll add `managedWhen` for completeness though.
