### ISSUE TITLE
layoutdebugger shows blank screen

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#192]
When you activate the layoutdebugger, your main stage becomes blank and does not show anything anymore. The layoutdebugger still works, but you cannot see what you have selected. This problem exists on Windows, Mac and Linux.

<img width="1235" alt="screenshot 2016-10-20 23 30 18" src="https://cloud.githubusercontent.com/assets/595350/19578707/38a0e4a0-971d-11e6-8de3-2512b5ed75c2.png">

**Comment by edvin** [comment]
The scene beeing debugged is attached to the debugger tree, and therefore it looses it's original parent Node inside the original scene. We must make sure that the parent of the scene.root is not changed.
