### ISSUE TITLE
Screencast to showcase new features in TornadoFX 1.5.7

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#194]
I would like to create one or more screencasts showcasing the following new features:
- Scopes (1.5.8)
- ItemViewModel in a Master/Detail scenario
- ItemListFragment
- replaceView with new transitions
- Mention that the LayoutDebugger is working again

**Comment by thomasnield** [comment]
Awesome!

**Comment by edvin** [comment]
ItemViewModel and Scopes are partially covered [in this screencast](https://www.youtube.com/watch?v=1G1OYBRDSBs). I will add another one tonight covering model-in-scope.
