### ISSUE TITLE
Add CSS substructure classes

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#197]
It looks like I missed a lot of the classes from substructures in the CSS reference. These should be added.

**Comment by t-boom** [comment]
It might be worth also looking through modena.css and see if there are any css elements that aren't documented in the CSS reference.

**Comment by t-boom** [comment]
I've added all the IDs. elements, classes, and pseudo-classes: #221 

I started looking at properties, but it isn't clear which properties are supposed to be colors and which can be any paint, so that will require more digging.

**Comment by edvin** [comment]
I don't think it's worth doing the properties work up front, unless anybody asks for it, especially considering the "documentation" :)

**Comment by edvin** [comment]
You already completed this, since we decided to hold off on the properties until there is a need. Closing.
