### ISSUE TITLE
Default ViewTransition?

### ISSUE THREAD

**Issue by radicaled** [edvin/tornadofx#199]
I've just upgraded to 1.5.7. Currently there are five overloads for `replaceWith`, three of them deprecated. I'm having problems calling a non-deprecated version of `replaceWith` without specfiying a ViewTransition (eg I just want the view to appear, no transition).

The method signature I want, `replaceWith(KClass, ViewTransition?)`, isn't selected in the code snippet below. Instead, it selects one of the deprecated ones, `replaceWith(KClass, (UIComponent, UIComponent, transitionComplete)`:

```kotlin
// Deprecated method called
replaceWith(WorkspaceView::class) 
// not deprecated
replaceWith(WorkspaceView::class, ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.LEFT)) 
// I could do this, but generates a "cast will never succeed" warning
replaceWith(WorkspaceView::class, null as ViewTransition)
// If that's the case, this would be better?
replaceWith(WorkspaceView::class, ViewTransition.Show)
```

I suppose Kotlin is getting confused since the second parameter for all of these are nullable, but I don't know of a way to force it to pick a particular overload in that case.

**Comment by bekwam** [comment]
Hi,

This worked for me.  I declared a variable in Kotlin set to null.  This seemed to give Kotlin enough type information.

var emptyTransition : ViewTransition? = null
replaceWith(view2, emptyTransition)

When I ran the code, it displayed the next screen without any sliding, fading, etc.

**Comment by edvin** [comment]
Thanks for the help @bekwam :) I think we should remove the deprecated overloads and support a one argument version that uses no transition.
