### ISSUE TITLE
Recompile for Kotlin 1.x RCs

### ISSUE THREAD

**Issue by radicaled** [edvin/tornadofx#2]
http://blog.jetbrains.com/kotlin/2016/02/kotlin-1-0-release-candidate-is-out/

> NOTE: as we announced earlier, RC requires all code to be recompiled to make sure no code compiled with older versions is kept around (please recompile even if you were on the EAP version!).

If you're running the latest version of the Kotlin in IntelliJ, it'll complain about the jar being in an unsupported format.

Unrelated: excellent library. Has improved my workflow quite a bit.

**Comment by edvin** [comment]
Thanks for the heads up :) I have released version 1.2.2 with lots of small improvements, including a recompile for Kotlin 1.0.0-rc-1036. It should hit Maven central in about an hour.

Cool that you like it :) I'm using it in production for several applications myself, and I love combining it with https://github.com/edvin/fxlauncher - check it out if it's of interest to you :)
