### ISSUE TITLE
Develop Navigation Service

### ISSUE THREAD

**Issue by bekwam** [edvin/tornadofx#214]
Unify the Stage opening (ex, openModal) and the Transitions (ex, replaceWith) with a Navigations scoped object that contains a goto("target") method.  This is a rough specification.  The target would determine how it should be displayed (ex, separate Stage) and what it needs in terms of data to be initialized.  This initialization might be a standard method that goto() knows about.

**Comment by edvin** [comment]
Could we also consider including parameters for the target? I just answered [this SO ticket](http://stackoverflow.com/questions/41198155/tornadofx-how-to-pass-parameter-to-fragment-on-every-instance/41199311#41199311) and it got me thinking - maybe we should provide parameters, kind of like an HTTP request somehow? I don't know if it belongs in this issue though, it could be a separate feature but possibly leveraged through the Navigation Service.

**Comment by edvin** [comment]
I just committed a first attempt at the params support now.

Here is a View passing a list of items to a fragment:

```kotlin
class SomeView : View() {
    override val root = stackpane {
        val params = "items" to listOf(SomeItem("Item A"), SomeItem("Item B")).observable()
        this += find<SomeViewFragment>(params)
    }
}
```

This is how the fragment can access the params:

```kotlin
class SomeViewFragment : Fragment() {
    val items = params["items"] as ObservableList<SomeItem>

    override val root = tableview(items) {
        column("Name", SomeItem::nameProperty)
    }
}
```

It's not type safe and not for everyone, but I think it would be a nice aid for beginners and possibly some corner cases.

**Comment by edvin** [comment]
Does the `goto` function cover this, or do you want to explore this further?

**Comment by edvin** [comment]
I think we'll close this for now, we have lots of ways to navigate, and with the latest addition of the `goto` and the configurable approach we introduced, I think we're good for now, at least until we have a use case we can't easily support with the current navigation system.
