### ISSUE TITLE
Deprecate TableView#moveXXX() functions to Collections.kt

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#216]
I just added a `ListView<T>.selectWhere()` extension function, and I noticed there are some extension functions for `TableView` I added some time ago that now might belong better in [Collections.kt](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Collections.kt). 

```kotlin
fun <T> TableView<T>.moveToTopWhere(backingList: ObservableList<T> = items, select: Boolean = true, predicate: (T) -> Boolean) {
    if (select) selectionModel.clearSelection()
    backingList.asSequence().filter(predicate).toList().asSequence().forEach {
        backingList.remove(it)
        backingList.add(0, it)
        if (select) selectionModel.select(it)
    }
}

fun <T> TableView<T>.moveToBottomWhere(backingList: ObservableList<T> = items, select: Boolean = true, predicate: (T) -> Boolean) {
    val end = backingList.size - 1
    if (select) selectionModel.clearSelection()
    backingList.asSequence().filter(predicate).toList().asSequence().forEach {
        backingList.remove(it)
        backingList.add(end, it)
        if (select) selectionModel.select(it)

    }
}
```

Should we deprecate and move them? Also, should our `selectWhere()` extension functions possibly target `SelectionModel` as well?

**Comment by edvin** [comment]
That sounds like a good idea.

**Comment by thomasnield** [comment]
I implemented these two extension functions to the Collections.kt file. However, I ended up not deprecating the original two for `TableView` because there is some selection nuance behavior they take care of. 

I'll look into applying `selectWhere()` to the SelectionModel later.

**Comment by edvin** [comment]
Good call! Do they call out to the Collections versions for the move operation?

**Comment by thomasnield** [comment]
Not currently. I didn't want to get greedy in consolidating code because I noticed some selection operations were occurring during the search. I didn't investigate if I could delegate to the Collections version.

**Comment by edvin** [comment]
It's not much code anyway. I can take a look once your done to see if I can figure out a way to consolidate, if not we'll just leave it :)

**Comment by thomasnield** [comment]
Feel free to take a look! I'll close this for now,  I'll look at selection model functions as a separate issue later.

**Comment by edvin** [comment]
I looked at it, it is not worth trying to consolidate anything here, that would just be an extra function call with no added benefit. It's all good :)
