### ISSUE TITLE
Support pseudo-classes with parameters?

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#219]
Modena contains references to the pseudo-class `dir` that takes a parameter (either `rtl` or `ltr` as far as I can tell). For example, on line 1386 there is this selector: `.html-editor-outdent:dir(rtl)`. Do we need to support this `:pclass(params)` syntax? there is no reference to arguments in [the official PseudoClass documentation](https://docs.oracle.com/javase/8/javafx/api/javafx/css/PseudoClass.html), so I'm not sure if it's actually a thing or if the pseudo-class is actually just the literal string `"dir(rtl)"` (which we also don't currently support).

**Comment by edvin** [comment]
I don't think it's worth investigating this until we at least see a use case. Maybe close for now?

**Comment by t-boom** [comment]
Sounds good to me
