### ISSUE TITLE
Update documentation for release 1.3.1

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#22]
I started a new page called `Properties` in the Wiki, where I just documented `singleAssign()`. I'll also add some documentation on builders later. I think we can show several practical examples using the new ones we developed.

**Comment by edvin** [comment]
Perfect! I will try to add the rest of the doumentation for `Properties` tonight. And I'll also link the page into the documentation flow :)

**Comment by thomasnield** [comment]
I think the [Type Safe Builders](https://github.com/edvin/tornadofx/wiki/Type-Safe-Builders) should at least cover the layouts in detail. Perhaps a practical example with a full `View` class would be warranted? I can run with this if needed.

**Comment by edvin** [comment]
That was exactly what I was thinking as well. Please do!

**Comment by edvin** [comment]
I'll start adding the missing pieces to the documentation now. Is there anything else we need to do before releasing 1.3.1?

**Comment by thomasnield** [comment]
I'll add my pieces this morning for the builders documentation.

**Comment by thomasnield** [comment]
I'm pretty thrilled with the product as it is right now, so I think we are in a release-ready stage.

**Comment by edvin** [comment]
Me too. We should brainstorm a little about the future of the product, but I kind of agree - it shouldn't be too big, and it shouldn't force a certain way to build software more than necessary, so at some point it will be about optimization instead of features.

OK, let's add the missing pieces and I'll release tonight or tomorrow :)

**Comment by thomasnield** [comment]
Okay sounds good! Already working on it now...

**Comment by edvin** [comment]
I'll work on the actual release in the meantime, just documented `asyncItems` so I think we're only missing the builders.

**Comment by thomasnield** [comment]
Yeah I'm working on them as we speak, and I'll save them in a few minutes so you can see the work so far.

**Comment by thomasnield** [comment]
Okay I think I'm done. If you feel we need more examples or need a more reference-like structure. Please let me know. I've learned from experience it's best to not over-document things that may change : ) 

(https://github.com/edvin/tornadofx/wiki/Type-Safe-Builders)

**Comment by thomasnield** [comment]
Made some more changes. Started with simpler examples and gradually escalated into more complex ones.

**Comment by edvin** [comment]
Beautiful! So nice with the images to go with the samples as well.

But remember, there is no need for the ReadOnlyStringWrapper thing any more, and the column type parameter is not needed. Actually, the column("Name", DomainObject::value) doesn't use reflection for getters/setters, only for properties, but I think they should be the default in all cases. Better to document the examples like this, and just mention that one can avoid reflection for mobile applications by using column("Name") { it.value.fooProperty() }.

Have to run now, movie with my daughter, back in a couple of hours :)

**Comment by thomasnield** [comment]
You're right, I'll change it to `SimpleStringProperty` since `ReadOnlyStringWrapper` makes no sense to use anymore. I'll make some adjustments on these notes. Have fun!

**Comment by thomasnield** [comment]
I might need to come up with a better example with a better domain object than `String`. Will just have to come up with a data class.

**Comment by edvin** [comment]
Yeah, maybe we should use a Person domain object or something in many of the examples. A Person could have properties of almost every data type. I believe it's a best practise to use properties in domain objects, so the examples should focus on that, and then we could add a section describing how to work with POJO's separately maybe? (Both describing the `Person::id` and the `SimpleIntegerProperty(it.id)` approach).

The Person domain object could start out for example like this:

```kotlin
class Person {
    var id by property<Int>()
    fun idProperty() = getProperty(Person::id)

    var name by property<String>()
    fun nameProperty() = getProperty(Person::name)

    var birthday by property<LocalDate>()
    fun birthdayProperty() = getProperty(Person::birthday)
}
```

To introduce values not backed by properties, we could for example include an age value:

```kotlin
    val age: Int get() = Period.between(birthday, LocalDate.now()).years
```

What do you think?

**Comment by thomasnield** [comment]
I was just thinking the same thing, using a Person object. I'll update the documentation later today to implement those very good thoughts.

**Comment by edvin** [comment]
Great, thanks a lot, Thomas!

**Comment by thomasnield** [comment]
No problem. Off-topic slightly. I haven't done mobile app development in years, so I'm disconnected. But do you think this library has the potential to be adopted heavily on Android and even iOS? Especially as Kotlin is adopted and Android moves to OpenJDK? Just curious what your thoughts are on that.

**Comment by edvin** [comment]
Haha, I actually though about exploring this today. Have you seen Gluon Charm? I would like to explore how TornadoFX can help a Charm based application. I think it would be a very good fit.

**Comment by thomasnield** [comment]
Haha I was just thinking about Gluon and what could be done there. I've done some work with Eugene Ryzhikov and Jonathon Giles on ControlsFX to build a [TableFilter control](https://bitbucket.org/repo/r8xAgM/images/2723253266-screenshot.png). 
They both are heavily involved at Gluon now. If Kotlin really takes off I'd be curious to see how much TornadoFX would become standardized into the stack.

**Comment by edvin** [comment]
That's very intriguing indeed. I think TornadoFX would be a good alternative to AfterburnerFX from Adam Bien, which it seems they use in most of the samples I've seen atleast.

Will start to play with this in the coming days, but first I need to create a Maven Archetype for TornadoFX!

**Comment by thomasnield** [comment]
Awesome! Let me know what comes of that, I'm curious.

**Comment by thomasnield** [comment]
Okay builders documentation is updated.

**Comment by edvin** [comment]
Perfect, good work Thomas! I'll close this ticket now, I think we're all done. Maven Archetype tomorrow for me :) Will let you know what I find out about Charm. I looked at it briefly and they already define View etc, so I'm not sure how to attack it yet. Need to learn more about it first.

**Comment by thomasnield** [comment]
Awesome! Have a great rest of the evening and please keep me posted.
