### ISSUE TITLE
Modal window result support

### ISSUE THREAD

**Issue by Evgen1000end** [edvin/tornadofx#226]
I'm not sure that it is ideologically correct for TornadoFX, but i would like to see the following functionality:
`
val output = find<ModalView>(inputScope).openModal()`

call "openModal" should interrupt the execution thread.
```

class ModalView : WithResultView<OutPutModel>() {
   val input:InputModel by inject()
  
  
   init {
    button("Ok") {
       asOk()  // optional
     }
     button("Cancel") {
       asCancel() //optional
     }
  }  


  //naming should change ofcourse))
  override fun getOnOk():OutputModel {  //optional
     return OutPutModel(...)
  } 
  
override fun getOnCancel():OutputModel { //optional
     return OutPutModel(...)
  } 
}
```

It will be clear and easy to understand.  ModalView will be like a local function (with input and output) and will be return the result at the point of call.

**Comment by edvin** [comment]
`openModal` supports the `block = true` parameter which will make the execution flow wait until the modal is closed. So you can do something like:

```kotlin
val modal = find<ModalView>(inputScope).openModal()
val result = modal.getResult()
```

Would that suit your use case?

**Comment by Evgen1000end** [comment]
Tell me please about View type should use for it? In JavaFX - it's dialog, but i think in TornadoFX should use View or Fragment. For view and fragment "openModal" return "Unit".

**Comment by edvin** [comment]
I'm sorry, I was a bit quick. You must write it like this:

```kotlin
val modal = find<ModalView>(inputScope).apply { openModal() }
val result = modal.getResult()
```

You can perfectly well use the Dialog from JavaFX as well, but if the UI is more advanced than a couple of buttons, a View or a Fragment is a good alternative. We have some support for simple alert dialogs as well:

```kotlin
/**
 * Show an alert dialog of the given type with the given header and content.
 * You can override the default buttons for the alert type and supply an optional
 * function that will run when a button is clicked. The function runs in the scope
 * of the alert dialog and is passed the button that was clicked.
 */
fun alert(type: Alert.AlertType,
          header: String,
          content: String,
          vararg buttons: ButtonType,
          actionFn: (Alert.(ButtonType) -> Unit)? = null): Alert {

    val alert = Alert(type, content, *buttons)
    alert.headerText = header
    val buttonClicked = alert.showAndWait()
    buttonClicked.ifPresent { actionFn?.invoke(alert, buttonClicked.get()) }
    return alert
}
```

If you think this is too clunky we could explore adding support for a more dialog centric approach for sure.

**Comment by Evgen1000end** [comment]
Thank, Edvin!

In this case i do like this:

```
class ModalView : Fragment("My View") {
   val input:InputModel by inject()
   var output:OutPutModel?=null

   init {
    button("Ok") {
       setOnAction {
         output = ... 
         closeModal()
      }
     }
     button("Cancel") {
      setOnAction {
         output = ...  
        closeModal()
      }
     }
  }  

  //should define by himself
  fun getResult() = output
}
```

I think it's correct solution, I think nothing need to improve ^^

**Comment by edvin** [comment]
Perfect :) If you feel we can improve this some how, please reopen this issue :)
