### ISSUE TITLE
center adhocWindow on primaryStage?

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#231]
if the primaryStage has moved on the screen, when opening an adhocWindow the the adhocWindow is centered on the screen, is it possible to center it on the primaryStage?

![image](https://cloud.githubusercontent.com/assets/595350/21953591/fb299a24-da3b-11e6-846e-fcfb4ff9175c.png)

**Comment by edvin** [comment]
We could do that by allowing to pass in a window owner perhaps, like we do for `openModal`. We would need to investigate how we can center a `Stage` above an existing `Window`. Do you know how?

**Comment by edvin** [comment]
Fixed :)
