### ISSUE TITLE
setting StageStyle.DECORATED does not decorate addHocWindow

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#232]
in the InlineFragmentTestApp change the StageStyle.UNDECORATED to StageStyle.DECORATED notice that the addhocWindow stays the same.

**Comment by edvin** [comment]
This seems to work as expected for me:

![image](https://cloud.githubusercontent.com/assets/977035/21954228/b4ec8fde-da4b-11e6-916e-94299ac34ea5.png)
