### ISSUE TITLE
buttonbar in form

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#233]
When using buttons in form they are pulled to the left under the labels
![image](https://cloud.githubusercontent.com/assets/595350/21953713/080de698-da3f-11e6-8c86-c1ad70f17ba3.png)

is it possible to have a "buttonbar" in the form that is configurable for example 
````
form {
  fieldset {
    field("Password") {
      val passfield = passwordfield()
    }
    buttonbar(POS.RIGHT) {
      button("unlock") {
        setOnAction {
        closeModal()
        controller.startIdleTimer()
      }
    }
  }
}
````

**Comment by edvin** [comment]
I've added an option to the `field` builder, so you can do:

```kotlin
field(forceLabelIndent = true) {
    button("unlock")
}
```

I also added a shortcut for this called `buttonbar` like you proposed:

```kotlin
buttonbar {
    button("unlock")
}
```

I will look at adding button position support as well.

**Comment by toplinuxsir** [comment]
But now It's not working  for tornadofx 1.7.8
```
buttonbar(Pos.CENTER_RIGHT) {
    button("unlock")
}
```

**Comment by edvin** [comment]
I think we made a mistake with the initial implementation. The alignment should be set on each button, so try this instead:

```kotlin
buttonbar {
    button("unlock", ButtonBar.ButtonData.RIGHT)
}
```
