### ISSUE TITLE
validate {} not available on textfield()

### ISSUE THREAD

**Issue by chrisr3** [edvin/tornadofx#239]
This is either a code bug or a documentation bug. I am using TornadoFX 1.6.0, and have simplified my code (below):
```
class MyData {
    var name : SimpleStringProperty = SimpleStringProperty("")
}

class MyDataModel : ItemViewModel<MyData>() {
    val name = bind { item?.name }
}

class MyTabView : Fragment() {
    override val root = stackpane {}

    private val model by inject<MyDataModel>()

    private val myConfigView = pane {
        form {
            fieldset("Configuration") {
                field("My Name") {
                    textfield(model.name) {
                        minWidth = 200.0
                        maxWidth = 200.0
                    }
                }
            }
        }
    }

    init {
        root.add(myConfigView)
    }
}
```

The builder here does not allow me to add a `validate {}` clause after the text fields's `maxWidth`. Nor does it support `bindSupported()`. Have I completely misunderstood the documentation chapter "ViewModel and Validation"? Isn't it reasonable to want to validate fields in a fieldset?

**Comment by chrisr3** [comment]
Ref: [Validation with ViewModel](https://github.com/edvin/tornadofx/wiki/ViewModel#validation-with-viewmodel), which claims that the following is legal:
```
field("Name") {
    textfield(model.name) {
        // Manipulate the text field here
        validate {
            if (it.isNullOrBlank()) error("The name field is required") else null
        }
    }
}
```

**Comment by edvin** [comment]
Sorry, this is due to a spelling error in the guide. The function is called `validator` :) I will update the guide ASAP, can you confirm this is working for you?

**Comment by chrisr3** [comment]
Hi, thanks for the reply. I'll check whether `validator{}` works when I'm back at work tomorrow, but I'm also wondering where the `bindSupported()` method is in this case.

**Comment by edvin** [comment]
What do you mean by `bindSupported()`? That's not a TornadoFX or JavaFX construct. What are you trying to do? The textfield is already bound to the model in the builder call.

**Comment by chrisr3** [comment]
Hmm, that's odd. I could have sworn that I read about a function `bindSupported(model)` in the documentation... However, `validator {}` is present and works as expected.

**Comment by edvin** [comment]
Odd :)

About item being null: `model.item` will only every contain a value after you assign an item to it, so your example above is great if you want the view model to have a value initially. If you use the view model for binding towards a selected item in a table for example, you won't need/want to prime it with an item. Committing a view model without an underlying item basically just clears the dirty state. 

You can manually assign a value to a view model using `model.item` as well.

**Comment by edvin** [comment]
I'll close this since the issue was a spelling error in the guide :)
