### ISSUE TITLE
Documentation missing for ItemViewModel<> with selection mode "MULTIPLE"

### ISSUE THREAD

**Issue by chrisr3** [edvin/tornadofx#240]
The documentation for `ViewModel` and `ItemViewModel` seems to assume that `bindSelected()` will only be binding to a single-valued property. There is no documentation for how to bind in the following case:

```
listview(listOf("Harry", "George", "Sally").observable()) {
    selectionModel.selectionMode = MULTIPLE
    ...
}
```

**Comment by edvin** [comment]
It doesn't support it, since the `ItemViewModel` can only hold a single item. We might be able to create somthing by accessing `selectionModel.selectedItems` which is an observable list, if you can describe your use case?

**Comment by chrisr3** [comment]
As per my example, I wish to select one or more of "Harry", "George" or "Sally" for a `SimpleListProperty<String>` , e.g.

```
class MyData {

    val names = SimpleListProperty(listOf<String>().observable())

}
```

The idea is that this list of names will form part of a configuration object for something.

**Comment by edvin** [comment]
Would `names.set(selectionModel.selectedItems)` do what you're looking for?

**Comment by chrisr3** [comment]
Except how can I access the `selectionModel` object when the `listview` is created via a Builder?

**Comment by edvin** [comment]
You can access it directly from inside the builder:

```kotlin
class MyTabView : Fragment() {
    val myData = MyData()

    override val root = listview(listOf("Harry", "George", "Sally").observable()) {
        selectionModel.selectionMode = SelectionMode.MULTIPLE
        myData.names.set(selectionModel.selectedItems)
    }
}
```

**Comment by edvin** [comment]
Also, to be clear; it doesn't matter if the listview is created via a builder or manually. The `root` property of the view will be of type `ListView<String>` in this case, so you can access it as `root.selectionModel` if you like as well, but you'd have to do that after the root is constructed of course. Depending on your use case you might want to hook this up differently though.

**Comment by chrisr3** [comment]
The following does work, thanks:

```
listview(listOf("Harry", "George", "Sally").observable()) {
    selectionModel.selectionMode = SelectionMode.MULTIPLE
    model.item.names.set(selectionModel.selectedItems)
}
```

**Comment by edvin** [comment]
Great :)
