### ISSUE TITLE
Autocomplete extension for combobox

### ISSUE THREAD

**Issue by aymen083** [edvin/tornadofx#251]
Hi,

I created an extension for combox to make it auto completable. It may be interesting to integrate it into tornadoFX. I already use it in a tornadofx project.

This is a link to the code of that extension coded in kotlin : 
https://gist.github.com/aymen083/9c605e1b22ed36e0e48c5f46ac925948

I am not sure that is the best way to do in kotlin may be there is more efficient way to do. I am not an expert in kotlin language.

Thanks
Aymen

**Comment by edvin** [comment]
Hi, and thank you for this.

It looks great!. I'd like a callback where you can return items programmatically based on the current input, and maybe a default implementation that operates on a list like in your example. We would also need a builder for this, with overrides to support a custom callback or just a list. (I can add the builder if you want).

Please file a PR and I'd be happy to include it!

**Comment by aymen083** [comment]
I add comments with modification patch to pull request.
I don't know if you want to close this issue and continue the discussion on the pull request.

**Comment by edvin** [comment]
Just checking in :) I'm having some success with creating a custom skin. I'm using most of your code, but also extending `ComboBoxPopupControl`. I think this might work. Will report back soon.

**Comment by aymen083** [comment]
Very good.

**Comment by edvin** [comment]
I added support for custom `cellFormat` as well, but I don't think it makes sense to support `buttonCell`, since we rely on the TextField to be able to do autocomplete. Does that make sense? It might still be more issues we need to deal with though. Do you have a chance to check it out and see how it works for you now?

**Comment by aymen083** [comment]
I made a look at the implementation. 

It looks ok, but i think we should make a test on the used skin to not alter combobox with modified skin. Maybe add a comment in the documentation that the autocomplete feature modifier the skin of combobox will be sufficient.

I think also that we should add the support for visibleRowCountProperty.

And i found an interesting approach that add filter to combobox without making it editable this can be an enhancement to the actual implementation. It uses a tooltip to show the actual filter text ;
https://github.com/jesuino/javafx-combox-autocomplete

I don't have time right now but i will see if i can make a pull request based on your code to add this feature if the combobox is not editable.

I also wanted to change the implementation to use a FiltredList instead of the filter function which create an array in every call. My idea was to update the predicate in the filteredList after every text modification so the default filter implementation maybe  like this : 
```kotlin
val filtredItems: FilteredList<T> = (comboBox.items ?: FXCollections.emptyObservableList()).filtered { true }
var localFilter = true
var autoCompleteFilter_ : (String) -> List<T> = autoCompleteFilter ?: {
       filtredItems.predicate = Predicate{ current -> comboBox.converter.toString(current).contains(it, true) }
        filtredItems
     }
```
and after to set the list : 
```kotlin
val list = autoCompleteFilter_.invoke(text)
if(!localFilter) comboBox.items = (list as? ObservableList<T>) ?: list.observable()
```
Maybe also we can add an alternative to makeAutocompletable with a callback that provide a predicate : 
```kotlin
fun <T> ComboBox<T>.makeAutocompletable(autoCompletePredecate: ((T) -> kotlin.Boolean)? = null) {
    skin = AutoCompleteComboBoxSkin(this, autoCompletePredecate)
}
```

**Comment by edvin** [comment]
I really like that alternative approach. In fact, if you can make this work, I'd be very interested in adding a feature to TableView based on the same approach, so you can search for and go to lines containing the search expression. It would be pretty easy to connect it to a SortedFilteredList as well. 

I'm swamped now myself, but let me know if you get stuck or if there is something I can help with.

**Comment by edvin** [comment]
Hey! Have you had any time to look at this?

**Comment by aymen083** [comment]
I started a first version but it's not finalized yet. you can take a look at my brache on tornadofx : https://github.com/aymen083/tornadofx

**Comment by edvin** [comment]
OK, no rush. We're doing a release probably during this week so I just wanted to give you a heads up in case you were almost done :) We can always get it in the next.

**Comment by edvin** [comment]
I will close this issue since your PR took care of most of it. If there are more enhancements you'd like to add I think it's better to file more targeted issues or PRs :)
