### ISSUE TITLE
[Question] Shortcuts added to buttons through accelerator function not working

### ISSUE THREAD

**Issue by arturbosch** [edvin/tornadofx#253]
Hi, I'm trying to bind shortcuts to some buttons and textfields by using the accelerator function like this:

```kotlin
hbox {
	alignment = Pos.CENTER
	append(JFXButton("Approve")) {
		prefWidth = 200.0
		accelerator(KeyCodeCombination(KeyCode.A, KeyCombination.SHORTCUT_ANY, KeyCombination.SHIFT_ANY))
		setOnAction { bus.fire(ApproveEvent) }
	}
	append(JFXButton("Reset")) {
		prefWidth = 200.0
		accelerator(KeyCodeCombination(KeyCode.R, KeyCombination.SHORTCUT_ANY, KeyCombination.SHIFT_ANY))
		setOnAction { bus.fire(ResetEvent) }
	}
}
``` 

or 
```kotlin
append(descriptionField) {
	prefWidth = 300.0
	promptText = "Enter task"
	accelerators.put(KeyCodeCombination(KeyCode.N, KeyCombination.SHORTCUT_ANY)) { this.requestFocus() }
	setOnKeyPressed { if (it.code == KeyCode.ENTER) addNewTask() }
}
```

unfortunately this does not work as I expected. 
Only `setOnKeyPressed { if (it.code == KeyCode.ENTER) addNewTask() }` does work when writing in the text field. 

PS: `append` is like `opcr` just as an extention function.

Do I miss something? I'm not very experienced wth javafx. Thx you for your help

**Comment by edvin** [comment]
Hi!

My initial test suggests that this is working as it should. Can you try this minimal sample and see if you get an alert when you hit `Ctrl+F`?

```kotlin
class AccelTest : View() {
    override val root = button("Click me") {
        accelerator(KeyCombination.valueOf("Ctrl+F"))
        setOnAction {
            alert(Alert.AlertType.INFORMATION, "Fire!", "You clicked.")
        }
    }
}
```

There might be somthing funky with your specific key combination. If the above works, try to use the same key combination in your sample. Then try swapping from JFXButton to a normal Button. Let me know what you find.

**Comment by edvin** [comment]
About the textfield -> `accelerators` is currently a Workspace feature, so those wouldn't kick in unless you're docked in a Workspace. I'll see if I can make them work for standalone views as well :)

**Comment by arturbosch** [comment]
Ok, I did several tests.

Your example works. My minimal botton bar test also works. This is the code for the botton bar.
After it I explain what works, what not.

```kotlin
	override val root: Parent = vbox {
		hbox {
			margin = Insets(10.0, 0.0, 20.0, 0.0)
			alignment = Pos.BOTTOM_CENTER
			append(descriptionField) {
				prefWidth = 300.0
				promptText = "Enter task"
				accelerators.put(KeyCodeCombination(KeyCode.N, KeyCombination.SHORTCUT_ANY)) { this.requestFocus() }
				setOnKeyPressed { if (it.code == KeyCode.ENTER) addNewTask() }
			}
			append(addButton) {
				setOnAction { addNewTask() }
			}
		}
		hbox {
			alignment = Pos.CENTER
			append(JFXButton("Approve")) {
				prefWidth = 200.0
//				accelerator(KeyCombination.valueOf("Ctrl+F"))
				setOnAction {
					alert(Alert.AlertType.INFORMATION, "Fire!", "You clicked.")
				}
				accelerator(KeyCodeCombination(KeyCode.A, KeyCombination.SHORTCUT_ANY, KeyCombination.SHIFT_ANY))
//				setOnAction { bus.fire(ApproveEvent) }
			}
			append(JFXButton("Reset")) {
				prefWidth = 200.0
				accelerator(KeyCombination.valueOf("Ctrl+R"))
				setOnAction {
					alert(Alert.AlertType.INFORMATION, "Fire!", "You clicked.")
				}
				accelerator(KeyCodeCombination(KeyCode.R, KeyCombination.SHORTCUT_ANY, KeyCombination.SHIFT_ANY))
//				setOnAction { bus.fire(ResetEvent) }
			}
		}
	}
```

Above code is embedded in a view. If I use the root of this view in the App eg.

```kotlin
class AccelTest : View() {
	override val root = opcr(this, find<BottomBar>().root)
}
``` 

everything works. If I put a container around the opcr function it does not work eg.
```kotlin

class AccelTest : View() {
	override val root = vbox {
		opcr(this, find<BottomBar>().root)
	}
}
```

**Comment by edvin** [comment]
I see. Thanks for this, I'll have a look and implement a fix ASAP, but it could take a couple of days before I get to it.

**Comment by edvin** [comment]
By the way, the `opcr` function is not intended to be used outside of the framework internals, but it has to be public because it's used from certain inline functions. To do `opcr(this, find<BottomBar().root)` like you do above, simply do `add(BottomBar::class)` instead, or even `add(find<BottomBar>())` if you want to add a specific instance.

**Comment by arturbosch** [comment]
Thx you for your work and the tip with opcr :)

**Comment by edvin** [comment]
Np. Just keep this issue open, I'm using it to track improvements for the `accelerators` property :)

**Comment by edvin** [comment]
I'm sorry about this, I totally forgot about the accelerator bug. I just committed a fix so `button.accelerator` also works for buttons inside nested views.

**Comment by edvin** [comment]
I have fixed the `Button.accelerator` so it works in embedded views, and also made sure actions added to the `accelerators` map works from everywhere.

I also threw in a nicer way to configure shortcuts for actions:

```kotlin
shortcut(KeyCombination.valueOf("Ctrl+Y")) {
    doSomething()
}
```

Of course that's too verbose for most situations, so I also added a string version:

```kotlin
shortcut("Ctrl+Y") {
    doSomething()
}
```

I think we have solved all the issues you uncovered. Does this work for you?

**Comment by edvin** [comment]
I also deprecated `Button.accelerator` in favor of `Button.shortcut`. It sounds more pragmatic.

**Comment by arturbosch** [comment]
It works, awesome thx1

**Comment by gharley** [comment]
I'm trying to create a ToolBar component as a separate class that I can then add to my View.  When I was defining the toolbar builder inside my view everything was fine but when I moved the builder into my ToolBar derived component the _shortcut_ method is not defined!?  What am I missing?

toolbar{            
&nbsp;&nbsp;button {
&nbsp;&nbsp;&nbsp;&nbsp;action { FX.eventbus.fire(PaletteEvent(PaletteAction.SMOOTH)) }
&nbsp;&nbsp;&nbsp;&nbsp;graphic = ImageView("smooth32.png")
&nbsp;&nbsp;&nbsp;&nbsp;tooltip("Smooth Palette")
&nbsp;&nbsp;&nbsp;&nbsp;shortcut("Ctrl+Alt+s") // Unresolved reference
&nbsp;&nbsp;}
}

**Comment by QingMings** [comment]
try this 
```kotlin 
  button("Test"){
                    shortcut("Ctrl+Alt+S")
                    setOnAction {

                        println(" print HelloWorld")
                    }
                }
```

**Comment by edvin** [comment]
The reason is that the `shortcut` extension function on `Button` is defined inside `UIComponent`, so if you don't extend `View` or `Fragment`, that function isn't available to you.

The reason is that the shortcut is added to the `accelerators` map in the `UIComponent`, which are handled by that component's `acceleratorListener` . You have two options:

1. Extend `Fragment` instead of ToolBar. I recommend this most of the time, because it gives you access to all the framework features from within your component. There really isn't a downside to it. The `root` node can still be your `ToolBar` and you can use `add` to add it to any `Parent` node, just like you would with your custom Node class.

2. Add your own `EventHandler` to the `scene` to handle the shortcut. That's a lot more work for sure, and you need to make sure to remove the listener when it's no longer needed.

**Comment by gharley** [comment]
Thank you, I was just starting to wrap my head around the fragment idea.  I think that will work for me.

**Comment by edvin** [comment]
I'm sure it will, but let me know if you run into any issues with it :)

**Comment by arvinrasheda** [comment]
how to implement when on focus textfild ?

**Comment by edvin** [comment]
You can observe the focusedProperty of a textfield:

```kotlin
