### ISSUE TITLE
Feature: asyncItems on TreeView

### ISSUE THREAD

**Issue by rerzer** [edvin/tornadofx#256]
Right now it doesn't seem like TreeView supports async loading of items as described in the async task execution wiki entry. Would it be possible for TreeView to also support this?

**Comment by edvin** [comment]
Hi! TreeView is not data driven, so the same technique wouldn't work, so you'd need to do `runAsync { populate´ for now. We're talking about creating a data driven TreeView, and `asyncItems` will for sure be a part of that component if we make it.
