### ISSUE TITLE
ContextMenu on Panes

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#260]
Since panes in JavaFX don't have a property to set a ContextMenu, you have to resort to adding it with `setOnContextMenuRequested` like this:

    setOnContextMenuRequested { e ->
        ContextMenu().apply {
            menuitem("Item") {
                doSomething()
            }
        }.show(this, e.screenX, e.screenY)
    }

I think it would be great to have a shortcut method for this, especially since Fragments usually use a Pane as their root.

**Comment by edvin** [comment]
I actually added this the other day, so it will be in 1.6.3 :) (`contextmenu` builder now works on any Node, not just Control)

**Comment by dominiks** [comment]
Excellent :+1: (I'll find another feature to wish for then ;))

**Comment by edvin** [comment]
Hehe, please do :)
