### ISSUE TITLE
Using Type-Safe CSS to style custom JavaFX control - RichTextFX

### ISSUE THREAD

**Issue by Morosko** [edvin/tornadofx#265]
Like I stated in the [issue ](https://github.com/TomasMikula/RichTextFX/issues/447) at the RichTextFX repo I want to include the [RichTextFX CodeArea](https://github.com/TomasMikula/RichTextFX#styleclassedtextarea) into my TornadoFX project. Somehow the defined css class won't style my text in the CodeArea, but works fine on a normal TornadoFX Text. (further information and code sample in other issue)

Do I have to configure something in TornadoFX for this to work?

**Comment by t-boom** [comment]
It works fine for me:

```kotlin
class RichTextFXTest : App(MainView::class, Keywords::class) {
    class MainView : View("RichTextFX Test") {
        override val root = borderpane {
            top = text("Test").addClass(Keywords.command)
            center = CodeArea().apply {
                paragraphGraphicFactory = LineNumberFactory.get(this)
                richChanges().subscribe { change ->
                    setStyleClass(0, length, "command")
                    println(getStyleAtPosition(length / 2))
                }
            }
        }
    }

    class Keywords : Stylesheet() {
        companion object {
            val command by cssclass()
        }

        init {
            root {
                prefWidth = 600.px
                prefHeight = 400.px
            }
            command {
                fill = Color.RED
                fontSize = 40.px
                fontWeight = FontWeight.BOLD
            }
        }
    }
}
```

![capture](https://cloud.githubusercontent.com/assets/1735659/23671717/78b73f44-0329-11e7-9423-9c6d63017134.PNG)

**Comment by t-boom** [comment]
Note that if you want to be safe against refactoring, you can use `setStyleClass(0, length, Keywords.command.name)` instead of a string literal.

**Comment by edvin** [comment]
I commented on the other issue - can it be that you're simply not loading your Stylesheet? If you do, can you post the code that does it, or your App class that includes it?

**Comment by Morosko** [comment]
@t-boom Thank you very much! In my actual program I named my cssclass "texCommand". I print-lined the name of my css class and found out that TornadoFX changed the name to "tex-command". That's why my string literal "texCommand" didn't work.

**Comment by t-boom** [comment]
Makes sense. Just an FYI, you can actually override the name change using 

```kotlin
val texCommand by cssclass(snakeCase = false)
```

But I still prefer using the `Keywords.texCommand.name` accessor to be safe.
