### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by MarkusAmshove** [edvin/tornadofx#267]
Hello,

I've created a tornado fx project using the gradle template and specified the `reloadViewsOnFocus()`.

The console log is saying that it's replacing components, but nothing is happening.

I've attached a gif to show you what happens. 

Please ask if you need any further info :-)

![2017-03-08_12-32-37](https://cloud.githubusercontent.com/assets/2401875/23702487/c443162c-03fb-11e7-9c70-0be9ff2c539e.gif)

**Comment by edvin** [comment]
This is because you didn't recompile the class before switching back to the app. The reload functionality kicks in, but it's reloading the same version :) Hit `CTRL+F9` and wait until the compilation is done before switching back to the app. Does that work for you?

**Comment by MarkusAmshove** [comment]
Ah you're right, thanks :-)

It's working now.

I thought it did a automatic replace, because I'm used to that from eclipse.

It seems like IntelliJ doesn't support rebuilding while the project is running.

Thank you! :-)

8. März 2017 12:54, "Edvin Syse"  schrieb:
	This is because you didn't recompile the class before switching back to the app. The reload functionality kicks in, but it's reloading the same version :) Hit CTRL+F9 and wait until the compilation is done before switching back to the app. Does that work for you?

**Comment by edvin** [comment]
That's right. There are some shortcuts you can do to mimic Eclipse with regards to this, but I think you're better of just recompiling explicitly :)

**Comment by Dkhusainov** [comment]
Hello. I'm trying this feture and it's not working for me. Neither styles nor views. I recomple the whole project before tabbing. I even tried to delete target folder with compiled classes, it still finds a way to load old classes from somewhere. Specs are: idea 2017.1 community edition, kotlin 1.1.1, tornadofx  1.7.0.

**Comment by edvin** [comment]
This will only work in debug mode, perhaps you didn't run in debug mode?

**Comment by Dkhusainov** [comment]
I figured it out. I had the main module, and a nested module inside the main folder. I ran the latter with it's own working directory(not main project root). After I switched workign directory to root it started workign. Not sure what it was about.

**Comment by edvin** [comment]
Ah, great. I've had similar issues with the Gradle support in IDEA. I don't like it and tend to stick to Maven for that reason. Good to know about this though, now we know what to look for if others run into a similar issue at least.
