### ISSUE TITLE
Updating a fieldset after async task

### ISSUE THREAD

**Issue by andreparodi** [edvin/tornadofx#268]
Hi,

I can't figure out how to "refresh" the view or re-eval the view's root not content. 

basically what i'm trying to do it i have a view which is a fieldset. I have an observable list of models that i iterate in the fieldsset to generate the view. All this works fine when i put some dummy data in the list.

what i really want to do is load the list of fields asynchronously and then update the view if there are any new fields to add. So what I am doing is in a runasync i am requesting this list and in a ui block i am trying to update the observable list of models. But clearly the fieldset is not updating as it would need to re-eval itself with the new list. Can i force the view to redraw itself?

thanks
andre

**Comment by edvin** [comment]
I would recommend one fieldset per item in the model list. Here is an example of a Project Editor that will create a new fieldset for each item in the models list. The button will add another project and update the list of fieldsets. I'm using the following domain object in this example:

```kotlin
class Project(name: String, description: String) {
    val nameProperty = SimpleStringProperty(name)
    var name by nameProperty

    val descriptionProperty = SimpleStringProperty(description)
    val description by descriptionProperty
}
```

First option is to use the `bindChildren` function that will transform the input list into nodes, one per element in the list. This will be kept in sync as the list changes:

```kotlin
class ProjectEditor : View("Project editor) {
    val projects = FXCollections.observableArrayList<Project>()

    override val root = form {
        bindChildren(projects) { project ->
            fieldset {
                field("Name") {
                    textfield(project.nameProperty)
                }
                field("Description") {
                    textfield(project.descriptionProperty)
                }
            }
        }
        button("Add project") {
            setOnAction { projects.add(Project("New name", "New description")) }
        }
    }
}
```

The result will look like this:

![](http://i.imgur.com/HBsIkK9.gif)

Option two would be to manually recreate the fields when the list changes:

```kotlin
class ProjectEditor : View("Project editor") {
    val projects = FXCollections.observableArrayList<Project>()
    val form = Form()

    override val root = borderpane {
        center = form
        bottom {
            button("Add project") {
                setOnAction { projects.add(Project("New name", "New description")) }
            }
        }
    }

    init {
        projects.onChange { createInputs() }
        createInputs()
    }

    fun createInputs() {
        form.clear()

        projects.forEach { project ->
            form.fieldset {
                field("Name") {
                    textfield(project.nameProperty)
                }
                field("Description") {
                    textfield(project.descriptionProperty)
                }
            }
        }
    }
}
```

The end result is mostly the same, but the first method is more efficient as it will only replace changed elements.

I hope this gives you some inspiration. Let me know if I misunderstood your use case :)

**Comment by andreparodi** [comment]
Awesome. Thanks so much for the quick reply. That was exactly what i was after. I wasn't that far off. Was doing a for loop instead of the bindChildren. I had also tried your second method but got stuck because I was trying to reset the value of form which I am not allowed to. Didn't figure out the clear method. 

Thanks for the help and for the great work on this project.

**Comment by edvin** [comment]
Sweet! `clear` is just a shortcut for `children.clear()` really, but the first one is preferable in any case.

**Comment by andreparodi** [comment]
thanks. it was a case of being new to javafx, kotlin and tornadofx. so fighting many fronts. :)
