### ISSUE TITLE
how to integrate the Spring Framework into the TornadoFX project?

### ISSUE THREAD

**Issue by Digiproduct** [edvin/tornadofx#269]
Hello. Tell me, please, how to integrate the Spring Framework into the TornadoFX project? Issue # 79 I saw, but did not understand anything

**Comment by edvin** [comment]
Hi. Third party dependency injection is described briefly in the Guide:

https://edvin.gitbooks.io/tornadofx-guide/content/20.%20Dependency%20Injection.html

@bekwam is working on an example for Spring, so he'll let you know when that page is updated with a complete working example you can use :)

**Comment by ronsmits** [comment]
We should make a small working example maybe? I will see what I can whip up this weekend

**Comment by edvin** [comment]
Very good. It fits perfectly into the samples-project as we talked about.

**Comment by ronsmits** [comment]
Spring-example is added to tornadofx-samples. the magic happens in 

```
class SpringExampleApp : App(SpringExampleView::class) {
    init {
        val springContext = ClassPathXmlApplicationContext("beans.xml")
        FX.dicontainer = object : DIContainer {
            override fun <T : Any> getInstance(type: KClass<T>): T = springContext.getBean(type.java)
        }
    }
}
```

Using the `ClassPathXmlApplicationContext("beans.xml")` the spring container is started up. Then the FX.dicontainer definition makes the context known to tornadoFX so it can be used in tornadoFX classes (like views and controllers) with the `by di()` construct:

```
class SpringExampleView : View() {
    val bean : HelloBean by di()
    override val root = vbox {
        label(bean.helloworld()).paddingAll=20
    }
}
```

**Comment by edvin** [comment]
Great work Ron. Should we keep this issue open until you've added info the the guide, @bekwam?

**Comment by ronsmits** [comment]
I already added the info to the guide

**Comment by edvin** [comment]
Fantastic!

**Comment by Digiproduct** [comment]
Many thanks for the example. Everything worked out

**Comment by gtnarg** [comment]
Just for completeness, if you need to retrieve a bean by name you there is another override available:

```
class SpringExampleApp : App(SpringExampleView::class) {
    init {
        val springContext = ClassPathXmlApplicationContext("beans.xml")
        FX.dicontainer = object : DIContainer {
            override fun <T : Any> getInstance(type: KClass<T>): T = springContext.getBean(type.java)
	    override fun <T : Any> getInstance(type: KClass<T>, name: String): T = springContext.getBean(type.java,name)
        }
    }
}
```
Grant

**Comment by edvin** [comment]
Good catch, @gtnarg :)
