### ISSUE TITLE
Replace Deprecated add() With and() in Wiki

### ISSUE THREAD

**Issue by bekwam** [edvin/tornadofx#270]
This page sets a hover psuedoclass using add() which promptly produces a deprecation warning

https://github.com/edvin/tornadofx/wiki/Type-Safe-CSS

**Comment by edvin** [comment]
Thank you, I've updated the references here and in the guide. The guide is a rewrite of this content, we need to figure out if the guide is missing some parts from the Wiki and then remove the Wiki page and link to the guide instead.

**Comment by edvin** [comment]
We have a separate thread to track needed changes to the CSS docs so I'll close this issue.
