### ISSUE TITLE
TornadoFX uses internal APIs that are encapsulated in Java 9

### ISSUE THREAD

**Issue by mikehearn** [edvin/tornadofx#276]
TornadoFX apps require the following new command line arguments in Java 9:

--add-opens javafx.base/com.sun.javafx.binding=ALL-UNNAMED
--add-opens javafx.controls/javafx.scene.control=ALL-UNNAMED

Is it possible to implement the views engine without these internal APIs?

**Comment by chrisr3** [comment]
Specifically:

```
Caused by: java.lang.IllegalAccessError: class tornadofx.ViewModelKt (in unnamed module @0x10355fee) cannot access class com.sun.javafx.binding.ExpressionHelper (in module javafx.base) because module javafx.base does not export com.sun.javafx.binding to unnamed module @0x10355fee
        at tornadofx.ViewModelKt.getViewModel(ViewModel.kt:380)
        ...
```

and

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private com.sun.javafx.binding.ExpressionHelper javafx.scene.control.TextInputControl$TextProperty.helper accessible: module javafx.controls does not "opens javafx.scene.control" to unnamed module @52430809
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:335)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:278)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:175)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:169)
        at tornadofx.ViewModelKt.getViewModel(ViewModel.kt:379)
        at tornadofx.ViewModelKt.validator(ViewModel.kt:466)
        at tornadofx.ViewModelKt.validator$default(ViewModel.kt:332)
```

**Comment by edvin** [comment]
I think we might even have more occurrences like this. My initial plan was to adopt for JDK 9 when it was GA or at least close to it, but maybe we are better off trying to detect the JDK version and do the right thing based on that. This way we can keep backwards compatibility with JDK8 and not have to release separate versions.

We need to investigate how to support the current functionality in JDK9 anyway, so this is a good place to start.

Are you testing against a Jigsaw enabled version of JDK9? The last time I tried this there were multiple issues, some of them with IDEA, so I held off on it. Hopefully IDEA support for JDK9 is way better now.

**Comment by chrisr3** [comment]
We have a JDK8 application that I tried to run on top of JDK9+160. And trying to compile it from the command line using Gradle/JDK9 was quite painful enough - I did not use IDEA.

**Comment by edvin** [comment]
For this specific use case however, it might be possible to avoid the current (messy) approach and solve this issue in one go. I'll give it a shot during the weekend.

**Comment by edvin** [comment]
I took a look now, and I don't think it's possible to stop relying on the `helper` and keep the current functionality.

There are some alternatives, like tracking the current ViewModel in a ThreadLocal, or tracking the ViewModel reference through the builders, but both of those approaches have (at least) these issues:

- Adding a validator after the builder has run becomes impossible
- FXML would no longer be supported

@mikehearn is it possible to declare `add-opens javafx.base/com.sun.javafx.binding=ALL-UNNAMED` etc in the TornadoFX manifest? If so, would this be an acceptable solution?

**Comment by chrisr3** [comment]
The current JDK9 manifest documentation is [here](http://download.java.net/java/jdk9/docs/technotes/guides/jar/jar.html#JAR_Manifest). And my own experience with the new `Add-Opens` and `Add-Exports` attributes is that they're only used when executing JARs via `java -jar <JAR>`.

**Comment by edvin** [comment]
That sounds like a no go, then. Not sure how we should attack this.

**Comment by chrisr3** [comment]
Raise a bug/feature request against JDK9?

**Comment by edvin** [comment]
I don't know if this would fly. We're utilizing a "back door" in JavaFX to do what we do, so the argument for a JDK change is pretty thin.

We could of course request a change to JavaFX properties, but I'm not hopeful that would fly either.

**Comment by mikehearn** [comment]
Can you describe what this code is doing in a bit more detail? I can see it's using reflection to crawl through the JavaFX internals but I don't really grok what the Property.viewModel extension is actually doing? Is it widely used?

**Comment by edvin** [comment]
It tries to find the target of a bound property. This target needs to be related to a ViewModel somehow, so we can add the validator to the correct validation context.

I realize this isn't a sufficient explanation, but I got an idea while training, so instead of boring you with this, I'll try an alternative solution.

Will report back in a bit. If this doesn't work I'll explain the motivation behind the current implementation.

**Comment by edvin** [comment]
Sorry it took so long, I'm a little behind schedule with everything these days :) I have committed a fix that removes the need for that awful reflection/private API code.

All framework tests pass and I have tested some of my bigger applications, but I need to test more in the coming days to be sure I didn't break anything. Can you check if this works with JDK without specifying `add-opens` now?

As I mentioned, I suspect there are other similar cases but this should hopefully resolve this particular problem.

**Comment by edvin** [comment]
I know you're busy, but I've confirmed that at least this issue with JDK9 is solved. Unfortunately there are others, so we are talking about a fork for JDK9/TornadoFX 2.0. I'll close this issue for now and open a new issue for the 2.0 fork later.
