### ISSUE TITLE
Application Not Executing

### ISSUE THREAD

**Issue by sur2548** [edvin/tornadofx#277]
![capturea](https://cloud.githubusercontent.com/assets/7479773/24035397/648d3de4-0b1b-11e7-82d7-861408ac36b7.PNG)

**Comment by edvin** [comment]
If you upgraded TornadoFX, make sure you clean and rebuild your project. (`Build -> Rebuild project`).

If this doesn't solve your problem, please supply more details about your environment, like build system, how you run this application etc.

**Comment by sur2548** [comment]
![s](https://cloud.githubusercontent.com/assets/7479773/24037983/92f36ca8-0b25-11e7-8860-05e9c51768e9.PNG)

**Comment by edvin** [comment]
Can you post your `build.gradle` file, as text?

**Comment by sur2548** [comment]
buildscript {
    ext.kotlin_version = '1.1.1'

    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: "kotlin"

repositories {
    mavenLocal()
    mavenCentral()
}

apply plugin: 'application'

dependencies {
    compile 'no.tornado:tornadofx:1.7.0'
    testCompile 'junit:junit:4.12'
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
}

jar {
    manifest {
        attributes(
                'Class-Path': configurations.compile.collect { it.getName() }.join(' '),
                'Main-Class': 'com.example.demo.app.MyApp'
        )
    }
    from (configurations.compile.collect { entry -> zipTree(entry) }) {
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }
}

**Comment by edvin** [comment]
The build file looks good. I'm no Gradle expert, and I don't know why it would fail in `startScripts` seeing as you have no start scripts defined. I think the issue here is that your run configuration is using the wrong module. Can you open the run configuration and check the `Use class path of module` setting? It should be the `tornadofx-gradle-project_main` module.

**Comment by sur2548** [comment]
![captures](https://cloud.githubusercontent.com/assets/7479773/24060400/18c2b8a4-0b79-11e7-9b12-cd496544c5f2.PNG)

I tried but still not working

**Comment by edvin** [comment]
Can you try to add the following to your `build.gradle` and execute the build again?

```groovy
apply plugin: "application"
mainClassName = 'com.example.demo.app.MyAppKt'
```

**Comment by sur2548** [comment]
If I run it through gradle, it worked but not through the run configuration

![capturea](https://cloud.githubusercontent.com/assets/7479773/24073250/9cf1c38a-0c1a-11e7-8383-c7413e94adb1.PNG)
