### ISSUE TITLE
LoadException on fx:include Unit Test

### ISSUE THREAD

**Issue by bekwam** [edvin/tornadofx#279]
Getting a LoadException when running composedFormFXML

I reproduced this on 2 machines

javafx.fxml.LoadException: 
/media/carl/Extra%20Drive%201/git/tornadofx/target/test-classes/tornadofx/tests/ComposedFormSearch.fxml:8
/media/carl/Extra%20Drive%201/git/tornadofx/target/test-classes/tornadofx/tests/ComposedForm.fxml:12
...
Caused by: java.lang.IllegalArgumentException: FXML not found for class tornadofx.tests.ComposedFormSearchController

**Comment by edvin** [comment]
`ComposedFormSearchController` is not an existing class, maybe you have some pieces of code left in your local copy that are not checked in?

**Comment by bekwam** [comment]
I reset my branch to the latest which didn't include the unit test.  We'll revisit this when deciding what to do with FXMLLoader in order to support nested fxml.
