### ISSUE TITLE
Create a Maven Archetype for TornadoFX

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#28]
The archetype should create a minimal sample application and set up all dependencies.

I don't have much Gradle experience, but if there is a similar construct, we should provide an archetype for Gradle as well.

**Comment by thomasnield** [comment]
I was just going to inquire about Gradle. I've used Gradle heavily but I'm definitely not a power user with it. From my research it looks like there might be a solution. http://stackoverflow.com/questions/11524790/gradle-counterpart-to-maven-archetype

**Comment by edvin** [comment]
Sweet, if I can do gradle init in the maven project and that's it, then I really only need to create one archetype. Will get this going early next week. Now it's pizza and Elementary :) Have a nice day, evening here already :)

**Comment by thomasnield** [comment]
You too man.

**Comment by edvin** [comment]
I was just about to start on this, but I'm not completely sure what the quickstart project should include. Some kind of "hello world" application, preferable with atleast one view and one controller, and some meaningful interaction between the two. Any ideas?

**Comment by thomasnield** [comment]
This is stuff I've never really messed with before. You probably know more than me on this subject but I can take a look and hack through it later this week if needed.

**Comment by edvin** [comment]
OK, I'll ping you when I have a complete archetype up and running. Getting close, but the last couple of days have been really busy at work :(

**Comment by thomasnield** [comment]
Yeah me too. Let me know if there anything I can do to help and I'll likely get to it this weekend.

**Comment by edvin** [comment]
The archetype is now fully functional, but I need some inspiration or ideas about what kind if minimal app it should include. I want to atleast use a controller and maybe a model object and do a callout to some kind of public json api and populate a listview etc. Do you know of any public json api's?

**Comment by thomasnield** [comment]
I've used JSON rarely since most applications i build are highly internalized and don't communicate over web or network.@hastebrot?

**Comment by edvin** [comment]
Walked the dog, got an idea :) The delicious.com feed seems like an OK fit. I'll mock something up :)

**Comment by thomasnield** [comment]
Okay awesome!

**Comment by edvin** [comment]
The archetype is almost ready. I need to get 1.3.2 released with the stuff from @picoworm and then make some changes to the archetype before I push it to Maven Central.

**Comment by thomasnield** [comment]
Cool. Let me know if you need any help. I'm following up on some items now.

**Comment by edvin** [comment]
All changes incorporated, and the archetype is already in maven central. I'll add some info to the README right now. The archetype must be propagated to the `archetype-catalog.xml` in the root of the central maven repo before it's usable, I think that will happen tomorrow, so it would be great if we can release 1.3.2 today or tomorrow :) We can add documentation after the release, as long as we mention all changes in the CHANGELOG. That way we can use the changelog as a todo list for adding documentation :)

**Comment by thomasnield** [comment]
I'll be online shortly to follow up. Running some errands.

**Comment by edvin** [comment]
Cool! Feel free to delegate to me if needed :)

**Comment by thomasnield** [comment]
Okay cool! I'll update builder docs later but can you update change log with my changes (if you have not already?)

**Comment by edvin** [comment]
Sweet, I'll add everything to the changelog :)
