### ISSUE TITLE
replaceWith causes contents to have a negative layout

### ISSUE THREAD

**Issue by rwhite226** [edvin/tornadofx#283]
Here is a sample of what I'm talking about https://github.com/rwhite226/tornadofx-test
When using replaceWith on a view if the contents of the new view are bigger than the current window get get negative layout coordinates (left and above the current window). If you resize the window before switching it works as expected.

**Comment by edvin** [comment]
I can confirm that I see the same behavior, and also that it doesn't happen if you switch view without a view transition. I haven't yet investigated what's causing it, or if it applies to all layout containers.

**Comment by edvin** [comment]
I've pushed a fix for this by adding `scene.window.sizeToScene()` after the root assignment:

```kotlin
transition.call(this, replacement) {
    scene.root = it as Parent
    scene.window.sizeToScene()
}
```

This fixes the issue _and_ makes sure the new root has enough space. The question is if this is the desired behavior. We have multiple options:

1. Add an option to allow the user to specify if `sizeToScene` should be performed
2. Only size to scene if the new parent has a preferredSize larger than the current scene size
3. Some combination of 1 and 2

What do you think @t-boom?

**Comment by t-boom** [comment]
My vote would be to just add it as a Boolean parameter on replace with, defaulted to false.

We could do an enum to allow for different options, but then the question is how granular you want to get. What if the new parent is taller but narrower? Does that count as bigger or smaller? I get the feeling the developer will know whether they want the stage to resize, so a Boolean seems like enough to me.

**Comment by edvin** [comment]
The thing is that the fix I added also solves the original issue described at the top - after the replace animation is done, a larger replacement node will be offset and rendered with negative x, y coordinates. Resizing the view doesn't bring them it to 0, 0.

I tried wrapping the replacement node in a StackPane and that brings it back to 0, 0 when you resize. I don't quite understand why it requires that extra StackPane to successfully resize, but the `sizeToScene` call takes care of it.

I agree about adding the boolean with default false though, but we could make it a function callback so you can decide case-by-case perhaps?

**Comment by edvin** [comment]
I went with your suggestion @t-boom - added a `sizeToScene` parameter to `replaceWith`. @rwhite226 - I think you have a good solution to your use case now. Whenever you want to replace a top level view and neeed the scene to resize to the new view's size, pass `true` or even `sizeToScene = true` to `replaceWith` :)
