### ISSUE TITLE
DataGrid: maxCellsInRow complement

### ISSUE THREAD

**Issue by bvolkmer** [edvin/tornadofx#287]
Hey,

it would be nice to have a complement for maxCellsInRow resulting in limiting the rows and expand through horizontal scrolling. Maybe also a property to disable vertical scrolling entirely.

Greetings,

**Comment by edvin** [comment]
Hi! I have added a `maxRows` property which if set will take precedence over the `maxCellsInRow` if needed.

Vertical scrolling can be disabled by making sure the DataGrid has enough vertical space, or you can wrap it in a ScrollPane where you disable the vertical scrollbar :)
