### ISSUE TITLE
Rest client fails with absolute URI

### ISSUE THREAD

**Issue by Xfel** [edvin/tornadofx#289]
If I specify an absolute URI (Starting with "http" or similar) as the target for a rest operation, I get an error:
`java.lang.IllegalArgumentException: URI is not absolute`.

Turns out, the method `Rest.getURI` does not recognize absolute URIs passed to it, prepending a `/` and making it unusable.

**Comment by edvin** [comment]
Thank you for reporting this. I have committed a fix to master now. Can you check it works for you with the latest snapshot?

**Comment by Xfel** [comment]
Yes, that works.

**Comment by edvin** [comment]
Perfect. I will release 1.7.1 with this fix shortly, possibly today.
