### ISSUE TITLE
Dependency injection question

### ISSUE THREAD

**Issue by andreparodi** [edvin/tornadofx#295]
Hi,

I would like to add a class to the dependency injection context and be able to look it up by it's parent abstract class. eg:
abstract class Shape() : Component(), Injectable {}
class Rectangle() : Shape()

in some controller I would like to do:
val shape: Shape by inject()

in my App class I would like wire an instance of rectangle into the container:
scope.set(Rectangle())

looking at the impl of set method it looks like it's registering the instance of rectangle in a map using class as the key. 

Anyway the above solution is not working as it is showing and error in the injection of shape: InstantiationException. Which is normal if it's trying to instantiate it. 

Is this something supported? Maybe if set had an extra parameter which is the interface/abstract class under which you want to register the object it would work.

thanks
andre

**Comment by edvin** [comment]
Hi! Does this work for you?

```kotlin
FX.getComponents(scope).put(Shape::class, Rectangle())
```

**Comment by andreparodi** [comment]
Works perfect. Thanks for that. 

Should probably have figured that out myself.

**Comment by edvin** [comment]
Great! We could add an overload for `Scope.set`, but I don't know if it's a common requirement. If so, I'd gladly accept a PR.
