### ISSUE TITLE
Node.toggleGroup NPE in 1.7.1

### ISSUE THREAD

**Issue by ykrasik** [edvin/tornadofx#296]
This started happening as of 1.7.1
By looking at the code - 
```
fun Node.togglebutton(text: String = "", group: ToggleGroup? = getToggleGroup(), selectFirst: Boolean = true, op: (ToggleButton.() -> Unit)? = null) =
        opcr(this, ToggleButton(text).apply {
            if (group != null) toggleGroup = group
            if (toggleGroup.selectedToggle == null && selectFirst) isSelected = true
        }, op)
```

`if (group != null) toggleGroup = group` will assign a toggleGroup if it is given as input, but if it isn't (defaults to null) - the next line `if (toggleGroup.selectedToggle...` will produce a NPE

**Comment by edvin** [comment]
Hi! Sorry about that. I have committed a fix. Does it work for you now? If not, can you post the code that fails?

**Comment by ykrasik** [comment]
I'm sorry, but I can't test it unless you release it to maven, I don't have a local clone :) The fix you committed seems correct though, I'm just waiting for the artifact now.

**Comment by edvin** [comment]
Here you go :)

https://oss.sonatype.org/content/repositories/snapshots/no/tornado/tornadofx/1.7.2-SNAPSHOT/

**Comment by ykrasik** [comment]
Confirmed working, thank you!
