### ISSUE TITLE
javavfx-ports/android compatibility

### ISSUE THREAD

**Issue by bvolkmer** [edvin/tornadofx#299]
Hey,
I'm using this with JavaFx-Ports/javafx-mobile-plugin on android. As the android sdk is missing some classes, I had to remove some lines of code to make it work.
I have a working branch in my [fork](https://github.com/bvolkmer/tornadofx/tree/android) (I pulled your master branch this evening).
When you compare, you will see that I out-commented mainly two things:

1. All awt imports and depending code, which, as far as I can see, is only for tray icon support.
2. All the Logger. This is most probably a problem in my build config or the javafx-mobile-plugin, as I use the same Logger in my own code. But I couldn't find a solution by now. This might need some independent testing.
(The mobile-plugin has an unresolved issue, not packing the dependency resources into the android apk. This might be a connected issue)

Also, since last json additions, I need an extra dependency declaration for javax.json in my project despite being declared in tornadofx. Maybe also connected to the mobile-plugin issue.

But the first thing with the awt tray icon could be packed in an artifact, so that it can be added if needed but if not won't break the android compatibility. Or and android artifact, excluding the awt parts. I'm not into the maven build-system, but I have seen such things before.

Greetings

*Edit:* Merge wasn't pushed at time of writing, but is now.

**Comment by edvin** [comment]
What is the result of the AWT inclusion? Does it fail at runtime or compile time? Can you describe the error you get?

**Comment by bvolkmer** [comment]
```
Rejecting re-init on previously-failed class java.lang.Class<tornadofx.App$setOnAction$1>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/event/ActionListener;
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.event.ActionListener" on path: DexPathList[[zip file "/data/app/.../base.apk"],nativeLibraryDirectories=[/data/app/.../lib/arm, /data/app/.../base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
...
Rejecting re-init on previously-failed class java.lang.Class<tornadofx.App$setOnMouseClicked$1>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/event/MouseAdapter;
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.event.MouseAdapter" on path: DexPathList[[zip file "/data/app/.../base.apk"],nativeLibraryDirectories=[/data/app/.../lib/arm, /data/app/.../base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
```
.. and so on at runtime.
This basically because the ArtVM used in android 5+ and the DalvikVM before, haven't the same set of classes as the jvm. F.e. JavaFX and AWT are missing. JavaFX can be provided by javafx-ports library, but does not contain AWT. The UI is working so far, but the logs are filled with missing classes exceptions.
I think the exception isn't at compile time, as javafx-mobile-plugin compiles the main code platform-independent with the oracle-jdk and just android-dependent code with the android sdk.

**Comment by edvin** [comment]
One possible solution would be to create an artifact with the interface for the classes/methods we use from AWT. You would just need to include `no.tornado.tornadofx-android-compat` or something like that. It's very few, so it wouldn't be many kbs. I can try to create such an artifact so you can test perhaps?

**Comment by edvin** [comment]
Try to install the following file into your local repo with this command:

```shell
mvn install:install-file -Dfile=tornadofx-android-compat-1.0.zip -Dversion=1.0 -Dpackaging=jar -DgroupId=no.tornado -
DartifactId=tornadofx-android-compat
```
Then you add the following dependency to your project and try to recompile:

```xml
<groupId>no.tornado</groupId>
<artifactId>tornadofx-android-compat</artifactId>
<version>1.0</version>
```

If it works, I can deploy this artifact to Maven Central. I might have missed a couple of definitions, let me know if you get any error messages.

[tornadofx-android-compat-1.0.zip](https://github.com/edvin/tornadofx/files/923426/tornadofx-android-compat-1.0.zip)

**Comment by pwittchen** [comment]
@bvolkmer Just being curious. Why are you using JavaFx on Android? Is there any specific use case, which could not be achieved with Android SDK itself?

**Comment by edvin** [comment]
I can't answer for him, but there are multiple valid reasons for doing so, one being a single code base for iOS/Android/Desktop.

**Comment by pwittchen** [comment]
@edvin I know. I just would like to know this particular use case because using JavaFx on Android is not so common :). I also heard that such approach can be used for developing games, which works both on desktop and mobile.

**Comment by edvin** [comment]
This is basically Glueon's business model and the reason they made javafx-ports, so maybe they provide further insight to their reasoning on their website. A good starting place might be http://gluonhq.com/products/mobile/javafxports/

**Comment by bvolkmer** [comment]
@pwittchen The cross-platform, one code base thing is exactly reason I had in mind. Its actually an "try-new-things-out"-project, so nothing serious. Another argument I'm seeing now while dev is, that the desktop build-process is much faster than the android. So I'm mainly run-and-fail on desktop build and if I get the wanted/running result, I just have to test once if it also runs on android. ~10s against ~1m per build on my system, plus the independence from an android emulator.

@edvin This is working thanks. Only the Logging Problem remains, which I just tracked down to 
`java.util.function.Supplier`, which seems to be also missing on android. This is only few time used, when you log, like `log.fine{"..."}` or `log.fine({"..."})` using curly braces. You could use the attached patch or add Supplier to the compat artifact.

[Remove_java_util_function_Supplier_usages.txt](https://github.com/edvin/tornadofx/files/923587/Remove_java_util_function_Supplier_usages.txt)

**Comment by edvin** [comment]
Great, I will release the compat library to Maven Central and apply the path :)

**Comment by edvin** [comment]
Update: `tornadofx-android-compact` is in Maven Central and the patch is committed. You can try it using the next snapshot build of TornadoFX which will be pushed to https://oss.sonatype.org/content/repositories/snapshots/no/tornado/tornadofx/ in about 40 minutes.

**Comment by huangyg11** [comment]
@bvolkmer would you mind posting your sample project about how to integrate tornadofx with javafxports?  Thanks!

**Comment by edvin** [comment]
+1 - that would be interesting to see :)

**Comment by bvolkmer** [comment]
https://github.com/bvolkmer/PaiMan - still in the master branch

As said before, it nothing serious. I stalled the javafxport version in favor for an native android client, as tornadofx more and more depends on java8, which isn't available on older android versions (according to https://developer.android.com/about/dashboards/index.html over 90% of the market share). So this is a bigger problem. I don't expect @edvin to fix all this and go back to java7 dependencies, just to make the unlikely javafx+android possible. I was maintaining an own fork of tornadofx in the end, but it never really worked on older devices. It is quite outdated by now. On android 7+ it however worked fine, even with the upstream version, thanks to above patch.

**Comment by edvin** [comment]
Thanks for the update and info @bvolkmer :)
