### ISSUE TITLE
Delegates for JavaFX Properties

### ISSUE THREAD

**Issue by hastebrot** [edvin/tornadofx#3]
I wonder if we could simplify the creation of `Property` fields and related methods somehow. In Java the general structure of a read-write property is (raw version):

~~~java
private Property<T> fooProperty;
public Property<T> fooProperty() { return fooProperty; }
public void setFoo(T value) { /* lazy create property object and set value */ }
public T getFoo() { /* lazy create property object and get value */ }
~~~

This could be expressed in Kotlin as:

~~~kotlin
private val fooProperty by lazy { SimpleObjectProperty<T>() }
fun fooProperty() = fooProperty
var foo: T
    get() = fooProperty.get()
    set(value) = fooProperty.set(value)
~~~

In `#javafx` on kotlinlang.slack.com I wrote an incomplete implementation using Kotlin's delegated properties to simply this code. It could look like this:

~~~kotlin
var foo by lazyProperty { SimpleObjectProperty<T>() }
fun fooProperty() = foo.internalProperty
~~~

(This is an excellent framework. Good work.)

**Comment by hastebrot** [comment]
Or is there a better approach in `tornadofx.Component`?

**Comment by edvin** [comment]
I think that's a great idea. There is nothing in `tornadofx.Component` to support this yet. Would you like to provide an implementation or should I give it a go?

I just added property binding support to builders btw, so you can write textfield(customer.nameProperty) and have it automatically bound. This suggestion would further reduce boilerplate, so I'm all for it!

**Comment by hastebrot** [comment]
>Would you like to provide an implementation or should I give it a go?

I'll create a PR with my implementation. `by lazyProperty()` needs some more thought, but a simple `by property()` should easy.

**Comment by edvin** [comment]
OK, let's try that first. Maybe `property` could use reified generics so that it could automatically create a  SimpleObjectProperty of the given type? That way you could write:

```kotlin
val foo by property<T>()
```

or

```kotlin
val foo: T by property()
```

It should also support a constructor that takes a value. I think there should be no need for the caller to instantiate the actual property.

Let's put it in `Properties.kt` - it doesn't belong in `Component`, as it is also is also applicable to model objects, which do not extend `Component`.

**Comment by hastebrot** [comment]
PR #4 contains a basic implementation and some test cases. I've added `junit` and `kotlin-test` to the Maven dependencies.

**Comment by edvin** [comment]
Nice, that looks very good. No need for reified generics, I'm not all that familiar with the Kotlin type system - seems they were not needed. I'll have a closer look tomorrow and then merge the PR.

What issues did you face when trying to implement lazyProperty?

**Comment by hastebrot** [comment]
>I'll have a closer look tomorrow and then merge the PR.

I like to add some more test cases. Should be ready until tomorrow.

>What issues did you face when trying to implement lazyProperty?

I used `by lazy { ... }` from Kotlin stdlib for the internal property field. And a custom class for a delegated field for the getter and setter that contains a reference to the internal property field. This reference caused the lazy field to loose its laziness.

Seems the best solution is to copy-paste parts of the `lazy()` code into `lazyProperty()`, or to find a way to reuse the existing code.

**Comment by edvin** [comment]
> I like to add some more test cases. Should be ready until tomorrow.

OK, I'll wait until you're finished :)

Regarding lazy: Better if we find a way to avoid duplicating the code/reuse the `lazy` function in the stdlib. I haven't quite grasped why the lazy field would loose its laziness, I'll investigate a little myself as well, as soon as I find some time, probably tonight.

**Comment by hastebrot** [comment]
>I haven't quite grasped why the lazy field would loose its laziness

~~~kotlin
@Test
fun `property() in combination with lazy()`() {
    val fixture = object {
        private val stringProperty by lazy {
            println("in lazy lambda expr")
            SimpleObjectProperty<String>()
        }

        val string by property(stringProperty)
    }
}
~~~

Using the reference to `stringProperty` for the `string` field, will immediately call the lazy lambda. We can see this using the `print()` statement. Unfortunately the Kotlin compiler doesn't allow variables from the outside in `lazy {}`, to enable us to automatically test this behaviour.

(Note: I've added `property(Property<T>)` into `Properties.kt`.)

Alex Hart from `#javafx` proposed adding a `property(Lazy)` method. I'll need to investigate this further.

>You can preserve laziness by implementing a ReadOnlyPropertyDelegate which takes a Lazy<T> as an argument, and delegates this to a val within your delegate class, for example.  (Or, alternatively, a LazyPropertyDelegate which takes a codeblock, and passes that to lazy())

**Comment by hastebrot** [comment]
The Kotlin compiler has some issues with method names that use backticks. 

>Invalid class name (must be a fully qualified class name in internal form)

It works with normal function names.

**Comment by edvin** [comment]
Maybe we should focus on getting the property delegate right first, and then play with the lazy version?

I noticed that the fxProperty val is private - how do you plan to create the property accessor?

```kotlin
var foo by lazyProperty { SimpleObjectProperty<T>() }
fun fooProperty() = foo.fxProperty // <- Is not accessible
```

Maybe just make it public?

**Comment by hastebrot** [comment]
>Maybe we should focus on getting the property delegate right first

Right. I'll focus on this first.

**Comment by hastebrot** [comment]
Hmm, we should allow properties to be initialized with `null`. I changed `T` to `T?` in `PropertyDelegate`.

**Comment by edvin** [comment]
I had a closer look at it now, in in it's current state it doesn't seem to be very useful.

Maybe I'm dense here, but even though it wraps a `SimpleObjectProperty`, it only exposes a `ReadWriteProperty`, so there is no way to bind to it or listen to changes. For this, the `PropertyDelegate` would have to extend `SimpleObjectProperty`.

What is it this version solves for you in it's current state?

**Comment by edvin** [comment]
I had a closer look at it now, in in it's current state it doesn't seem to be very useful. (Just deleted my last comment, I brainfarted a little :)

Sorry for beeing dense, but I don't see how this can be used to deliver something close to the example you gave at the top of the issue.

What is it this version solves for you in it's current state? Can you show me some code examples?

**Comment by edvin** [comment]
Or spesifically, how do you get to the fxProperty to do bindings and listeners?

```kotlin
var id by property(42) // All good
fun idProperty() = ? // How to get to the property?
```

**Comment by edvin** [comment]
I found one (ugly) way of doing it.

Define a library function that can extract the fxProperty
```kotlin
inline fun <reified T> T.fxProperty(): Property<T> = (this as PropertyDelegate<*>).fxProperty as Property<T>
```

Then you can write:

```kotlin
var id by property(42) // All good
fun idProperty() = id.fxProperty()
```

**Comment by edvin** [comment]
The least sucky option I've found so far is:

```kotlin
class Customer : PropertySupport {
    var id by property(42)
    fun idProperty() = fxProp(Customer::id)
}
```

It's type safe, but it requires that you implement an interface in your class to use it. The implementation, ugly as it is:

```kotlin
interface PropertySupport {
    fun <T> fxProp(prop: KMutableProperty1<*, T>): ObjectProperty<T?> {
        // avoid kotlin-reflect dependency
        val field = javaClass.getDeclaredField("${prop.name}\$delegate")
        field.isAccessible = true
        val delegate = field.get(this) as PropertyDelegate<T>
        return delegate.fxProperty as ObjectProperty<T?>
    }
}
``` 

Do you have any better options? :)

**Comment by edvin** [comment]
It's possible to avoid the interface by slightly changing the callsite to:

```kotlin
fun idProperty() = fxProp(this, Customer::id)
```

The all we need is a package level function in the library:

```kotlin
fun <T> fxProp(owner: Any, prop: KMutableProperty1<*, T>): ObjectProperty<T?> {
    // avoid kotlin-reflect dependency
    val field = owner.javaClass.getDeclaredField("${prop.name}\$delegate")
    field.isAccessible = true
    val delegate = field.get(owner) as PropertyDelegate<T>
    return delegate.fxProperty as ObjectProperty<T?>
}
```

**Comment by edvin** [comment]
Hmm.. it's getting closer :)

```kotlin
fun idProperty() = fxProp(Customer::id)
```

I think this might be tolerable. Implementation of the library function:

```kotlin
fun <T> Any.fxProp(prop: KMutableProperty1<*, T>): ObjectProperty<T?> {
    // avoid kotlin-reflect dependency
    val field = this.javaClass.getDeclaredField("${prop.name}\$delegate")
    field.isAccessible = true
    val delegate = field.get(this) as PropertyDelegate<T>
    return delegate.fxProperty as ObjectProperty<T?>
}
```

**Comment by hastebrot** [comment]
>What is it this version solves for you in it's current state? Can you show me some code examples?

It reduced the code from

~~~kotlin
private val fooProperty = SimpleObjectProperty<String>
fun fooProperty() = fooProperty
var foo: T
    get() = fooProperty.get()
    set(value) = fooProperty.set(value)
~~~

to

~~~kotlin
private val fooProperty = SimpleObjectProperty<String>
fun fooProperty() = fooProperty
var foo = property(fooProperty)
~~~

**Comment by edvin** [comment]
Yeah that helps. With my little hack above it can be further reduced to two lines and even less code, so we could support both approaches. Or is the hack to ugly to include?

**Comment by hastebrot** [comment]
Using reflection could be very slow on mobile devices. At least we have an approach to access the backing field of the Kotlin property.

**Comment by edvin** [comment]
Absolutely. I don't know if I like the function name `fxProp` - any better suggestions?

If not, I'll leave it and prepare to release 1.3.0. Will be good to get the coordinate change done :) Let me know if I can be of any assistance with regards to the Builder testing you talked about, btw.

**Comment by hastebrot** [comment]
>any better suggestions?

`fxProp` and `fxList` could be names for properties and observable lists. But I'm not a big fan of abbreviations in APIs. What about `simpleProperty()` (and later `observableList()`)?

**Comment by edvin** [comment]
`simpleProperty` would be a misnomer since it can potentially wrap any subclass of `Property<T>`.

Since what the function does is extract a JavaFX property from a KMutableProperty, maybe we could call it getProperty? Your implementation stays, so you can choose to use it like you wrote:

```kotlin
private val fooProperty = SimpleObjectProperty<String>()
fun fooProperty() = fooProperty
var foo = property(fooProperty)
```

Or you can choose to be lazy and write:
```kotlin
var id by property<Int>()
fun idProperty() = getProperty(ClassName::id)
```

The first way should be the preferred because of speed and "less magic".

**Comment by edvin** [comment]
I'll close this and go for the suggested approach :) Will release 1.3.0 shortly.

**Comment by edvin** [comment]
I just changed the type from `T?` to `T`, because the properties created with the delegates cannot be assigned to various JavaFX constructs in it's original state. The tests still pass, and a property delegate can still house null values, so I see no down side. Let me know if I'm mistaken :)

**Comment by edvin** [comment]
I just documented this now: https://github.com/edvin/tornadofx/wiki/Properties

Is this in line with what you're thinking @hastebrot ?
