### ISSUE TITLE
Integrate modena.css "tricks"?

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#302]
While working on my JavaFX application I stumbled upon two very helpful but apparently undocumented features for the standard css of JavafX.

# 1
When wrapping controls in a `ScrollPane` JavaFX (the modena style actually) adds some borders to the pane which I found very unexpected and unwanted since other panes don't add borders:

![borders](https://cloud.githubusercontent.com/assets/109005/25127537/7fc84110-2436-11e7-95e2-7f623a7b6c74.PNG)

After a quick search I found the "secret" way to remove these borders is to add the style class `edge-to-edge` to the scrollpane:

![edge-to-edge](https://cloud.githubusercontent.com/assets/109005/25127681/1f9ecbaa-2437-11e7-95e0-a1a965b66d37.PNG)

Would it make sense to integrate this as a boolean flag for the scrollpane builder?

# 2 

By setting the `-fx-base` color you can tint buttons, similar to the button styles in themes like bootstrap:

![basecolor](https://cloud.githubusercontent.com/assets/109005/25128114/c3d2656e-2438-11e7-8ddd-573116baca39.PNG)

I have added a custom `cssproperty` for my application but I thought this might be of interest for others and a good addition to the standard set of properties.

**Comment by t-boom** [comment]
As far as number 2 goes, we looked at adding modena properties a while back in #197, but decided to hold off for a number of reasons. First of all, there isn't any clear documentation, so it can be difficult to tell the expected type of a property (`Color` vs `Paint`, etc.). We also had discussions in slack about what would happen if the user was using a different base stylesheet, and if we should possibly have multiple included stylesheets for common bases. Long story short, it was put on hold as lower priority than many other things, and will probably come back when we look more into "TornadoFX 2".

**Comment by edvin** [comment]
I'm all for adding number 1 :) Do you want to make a PR or should I just add it?

About number 2, I think @t-boom knows best. I see value in having an easy way to make custom colored buttons. If we're not completely sure about the property type we could start defensive with `Color` perhaps?

**Comment by t-boom** [comment]
We could add `base` as a property since I'm about 98% sure it is a color, but it would be the exception instead of the rule (I'm sure many of modena's tricks can be added, but should probably be done in a modena specific style-sheet).

**Comment by edvin** [comment]
OK, so we add `base` and maybe create a `ModenaStylesheet` that people can extend if they need?

**Comment by mikehearn** [comment]
I use the -fx-base trick all the time. With -fx-base and some padding, you get a rather Twitter Bootstrap-esque theme. I want to make a JavaFX CSS theme that modifies Modena to make it look webbish, as I've done it several times before and keep rewriting the same stuff in each project.

**Comment by t-boom** [comment]
@edvin I lilke the idea. but it could be a user experience issue. I would expect a `ModenaStylesheet` to have rules and properties for at least a majority (if not all) of modena's customization, but that takes us back to the original problem of not knowing what they all are and what types they can take.

**Comment by dominiks** [comment]
@edvin I'm fine with you adding it.

**Comment by edvin** [comment]
@t-boom Yeah, you're right. Will you add `baseColor` then?

@mikehearn Would you be willing to share that bootstrappish stylesheet? Maybe we could turn it into a type safe stylesheet and make it easy for people to configure colors and extend it?

**Comment by t-boom** [comment]
Sure thing

**Comment by t-boom** [comment]
Added

**Comment by edvin** [comment]
I added a `var` to `ScrollPane`:

```kotlin
edgeToEdge = true
```

You can also inspect the var to see if the class is set, or even set it to false to remove the class.

**Comment by dominiks** [comment]
Good solution, thank you all.
