### ISSUE TITLE
Provides a timeout setting   in  Rest()

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#306]
I'm using `Rest()`  in my controller 
```kotlin 

class   MyController :Controller(){
    
    val api:Rest by inject()
    
}
```

I don't know how to set the request timeout
The default timeout is too long，
I want to set 5 seconds。
Is there a way to set?

**Comment by edvin** [comment]
You can configure the read time out for the default provider by using a `requestInterceptor` and casting the request to `HttpURLRequest` before yo operate on it.

```kotlin
api.engine.requestInterceptor = {
    (it as HttpURLRequest).connection.readTimeout = 5000
}
```

You can configure the `connectionTimeout` of the `HTTPUrlConnection` object above in the same way.
