### ISSUE TITLE
Layout Debugger  KotlinNullPointerException

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#309]
This error occurred when I clicked on the tree node

![image](https://cloud.githubusercontent.com/assets/22107668/25328418/58441d5c-290a-11e7-8619-5cee95f72306.png)

**Comment by dominiks** [comment]
Fortunately, this has been fixed in 1.7.4-SNAPSHOT.

**Comment by QingMings** [comment]
thanks :)
