### ISSUE TITLE
Fragment should not be injectable

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#31]
It's possible to inject `Fragment`. This leads to unexpected behavior because every field access will yield a new instance of the fragment. I propose to add an interface `Injectable` to `View` and `Controller` and change the `inject` delegate to only accept injectable types.

**Comment by thomasnield** [comment]
I was wondering about that earlier, considering `Fragment` is not a singleton.

**Comment by edvin** [comment]
Just pushed this commit now. Bumped version number to 1.3.2. This fixed a couple of potential bugs for me in one of my apps that has about 100 Fragments :)
