### ISSUE TITLE
add a enter key event for Wizard

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#310]
When I complete the current page, Press enter to the next page
When I  complete all page , Press enter to finish the Wizard

**Comment by edvin** [comment]
You can add the following code inside your Wizard's init block:

```kotlin
// Enter completes current page and goes to next, finishes on last
root.addEventFilter(KeyEvent.KEY_PRESSED) {
    if (it.code == KeyCode.ENTER) {
        if (allPagesComplete.value) {
            currentPage.onSave()
            onSave()
            close()
        } else if (currentPageComplete.value && canGoNext.value) {
            next()
        }
    }
}
```

Does that work the way you expect it to?

**Comment by edvin** [comment]
I also added this as a property, so in TornadoFX 1.7.4 you'll be able to simply do:

```kotlin
enterProgresses = true
```

**Comment by edvin** [comment]
Made an adjustment based on @ronsmits' feedback so it allows enter in textareas. Ctrl+Enter in a textarea will still progress.

**Comment by QingMings** [comment]
Great!
