### ISSUE TITLE
Create delegate for ObservableList

### ISSUE THREAD

**Issue by eiswind** [edvin/tornadofx#312]
I need to expose my ObservableListProperty as a MutableList, so that other Frameworks can work with it by reflection. I worked around by creating it like this:

`
var permissions: MutableList<Permission>?

        get() = permissionsProperty.get()

        set(value) = permissionsProperty.set(FXCollections.observableArrayList(value))

    private val permissionsProperty by lazy { SimpleListProperty<Permission>() }

    fun permissionsProperty() = permissionsProperty
`

is there any more elegant way to specify the type of the var ?

**Comment by edvin** [comment]
There is no delegate for this, but you can simplify the setter a little:

```kotlin
var permissions: MutableList<Permission>? 
    get() = permissionsProperty.get(); 
    set(value) = permissionsProperty.set(value?.observable())
```

If you use this pattern a lot however, you could include this `mutableList` delegate function:

```kotlin
fun <T : Any> mutableList(listProperty: Property<ObservableList<T>?>) = object : ReadWriteProperty<Any, MutableList<T>?> {
    override fun getValue(thisRef: Any, property: KProperty<*>): MutableList<T>? = listProperty.value
    override fun setValue(thisRef: Any, property: KProperty<*>, value: MutableList<T>?) {
        listProperty.value = value?.observable()
    }
}
```

You would then define the `permissions` var like this:

```kotlin
var permissions by mutableList(permissionsProperty)
```

You can optionally include the type as well if you like:

```kotlin
var permissions: MutableList<Permission>? by mutableList(permissionsProperty)
```

Does that help?

**Comment by eiswind** [comment]
Thanks a lot. That really helps. Never created a delegate before.

**Comment by edvin** [comment]
My pleasure :)
