### ISSUE TITLE
Replacing fragments is not unsubscribing the event

### ISSUE THREAD

**Issue by niteesh19** [edvin/tornadofx#313]
Consider this:
There is a view with multiple instances of a fragment but with different datasets.
Now I reload all fragment instances based on an event in the main view. 
I do this by:
{{code-snippet}}

`borderpane{`
`subscribe<RefreshFragment> {`
`    center.replaceWith(vbox { add(MyFragment::class, someNewParams) })`
`}`
`}`
This works fine.

Now similarly, inside the MyFragment itself, I have an event and a subscriber. When the event is triggered inside one of the fragments, all the other fragment instances subscribers get called, which is expected. BUT the previous replaced fragments are also getting subscribed. These fragments are not in the view as I replaced them with a newer Fragment. 
For eg, if I have 3 fragments , the subscribe method gets called 6 times.

Can someone help me solve this?

**Comment by edvin** [comment]
I suspect the reason this is happening is that you never undock any of your MyFragment instances. You never remove them from their parent, which would trigger undock and subsequently unsubscription.

The reason you never undock is that you dock each fragment in a new vbox:

```kotlin
center.replaceWith(vbox { add(MyFragment::class, someNewParams) })
```

So when you call replaceWith again, the vbox you created looses it's parent allright, but MyFragment is still attached to that vbox, and therefore is still docked. Change your code to:

```kotlin
center.replaceWith(find(MyFragment::class, someNewParams))
```

This should resolve the issue. If you need the vbox, just add it once, and call `replaceWith` on the first child of that vbox instead. Does that make sense?

**Comment by niteesh19** [comment]
Yea even I suspected the problem that I dock each fragment in a new vbox, but when I do this 
`center.replaceWith(find(MyFragment::class, someNewParams))`
the other instances of the same fragment get undocked. 
Somehow behaving a bit weirdly for me as I might have messed up the components.
Thanks for the GotoViewApp.
Will try that approach and let you know if it works.

**Comment by edvin** [comment]
Are you sure `MyFragment` is a `Fragment` and not a `View`? That's the only explanation I can think of if those fragments gets removed when you do replaceWith.

If this is not the case, are you able to create a simple app that shows the problem?

**Comment by niteesh19** [comment]
Yes they are Fragments only. Ok let me create a simple app. Will take some time as have other pending tasks.. may be 4-5 hrs. Thanks for your prompt response.

**Comment by edvin** [comment]
Great :) We'll get to the bottom of this :)

**Comment by niteesh19** [comment]
Hi, Sorry for the late reply.
I have attached a simple app that shows the problem. 
PFA ReplaceFragments.txt which is actually a .kt file.
[ReplaceFragments.txt](https://github.com/edvin/tornadofx/files/969629/ReplaceFragments.txt)

First problem Scenario is :
First double click on any of the rows on either table.. in the console you will see "Subscribed SelectedPerEvent!!" twice .. which is expected as there are two instances of a fragment.
Now toggle the radio button and then again double click the row. Now we see "Subscribed SelectedPerEvent!!" 4 times. .. this increases for every toggle you do.

Second problem is a basic one actually where when you click on the "Action" button on either fragment instances, I want to see the output of "Subscribed SyncEvent!!" twice. But it happens only once. Is this because I am not using any tableview object / operation. Just a little confused on why a simple fire could not be subscribed for both instances.

**Comment by edvin** [comment]
The first issue is as we discussed because the fragments you create never loose their parent, so they are never undocked. I will look into if we can detect a disconnect up the parent chain, but I'm not sure that's adviceable. As a workaround, I suggest changing this:

```kotlin
center {
    hbox {
        add(MyFragment::class, hashMapOf("itrTableData" to getPersonBasedOnFilter(selectedGender)))
        add(MyFragment::class, hashMapOf("itrTableData" to getPersonBasedOnFilter(selectedGender)))
    }
}
subscribe<RefreshFrag> { event ->
    println("Subscribed RefreshFrag!!")
    center {
        hbox {
            add(MyFragment::class, hashMapOf("itrTableData" to getPersonBasedOnFilter(event.gender)))
            add(MyFragment::class, hashMapOf("itrTableData" to getPersonBasedOnFilter(event.gender)))
        }
    }
}
```

To this:

```kotlin
center {
    hbox {
        add(MyFragment::class, hashMapOf("itrTableData" to getPersonBasedOnFilter(selectedGender)))
        add(MyFragment::class, hashMapOf("itrTableData" to getPersonBasedOnFilter(selectedGender)))
        subscribe<RefreshFrag> { event ->
            println("Subscribed RefreshFrag!!")
            clear()
            add(MyFragment::class, hashMapOf("itrTableData" to getPersonBasedOnFilter(event.gender)))
            add(MyFragment::class, hashMapOf("itrTableData" to getPersonBasedOnFilter(event.gender)))
        }
    }
}
```

Basically you subscribe to the `RefreshFrag` event inside the already built hbox that you put in the center, and clear all children before you add the new children to it.

It looks weird to be to redeclare `center` twice, and this gets rid of the issue as well.

For the second problem, just mentioning the fragment seems to make the event subscription react twice. I haven't had time to look into this yet, but you can confirm that you get two callbacks if you change it to:

```kotlin
    init {
        subscribe<SyncEvent> {
            println("Subscribed SyncEvent!! ${this@MyFragment}")
        }
    }
```

Will look more closely at this ASAP.

**Comment by edvin** [comment]
I fixed the missing event subscription, it was actually a faulty equals/hashCode implementation in FXEventRegistration. If you have time to check against 1.7.5-SNAPSHOT I think you'll find everything working as it should now :)

**Comment by niteesh19** [comment]
Thanks. Got it working :)

**Comment by edvin** [comment]
Great, thanks for getting back to me :)
