### ISSUE TITLE
SmartResize on TreeTableView

### ISSUE THREAD

**Issue by HaasJona** [edvin/tornadofx#316]
Hi, I'm using the SmartResize policy on `TableView`s, and it works great, but I was wondering if there were also support for `TreeTableView`s and if not if this could be added?

Wiki link: https://github.com/edvin/tornadofx/wiki/TableView-SmartResize

**Comment by edvin** [comment]
OK, I added an initial version, activate with `smartResize()`. I deliberately copied a lot of the code from the table view version, as I suspect we will need to make small customizations in many places for it to be perfect. Check it out and let me know how it works for you :)

**Comment by HaasJona** [comment]
Thanks, I will try.

**Comment by HaasJona** [comment]
Works great, thank you.
