### ISSUE TITLE
We need some more builders

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#32]
I'll go ahead and take care of this one this week, but I notice a few type-safe builders might need to be added. I'll keep adding to this list as I continue using TornadoFX for a project this week.

- `scrollpane()`
- `flowpane()`
- `tilepane()`
- `anchorpane()`
- `listview()`

**Comment by thomasnield** [comment]
It might be interesting to add extensions for [ControlsFX](http://fxexperience.com/controlsfx/) as well for a separate project, but I don't know if that would be worthwhile at the moment. Let's finish this library first.

**Comment by edvin** [comment]
Perfect! Yeah, let's try to get to a feature complete state, and then look for extensions to other libraries. Optional dependencies are a good route to go. I was wondering about making HttpClient optional, default to using HttpUrlConnection via an interface, and then adding a complete implementation for HttpClient as well. Not everyone uses Rest, so it might be a bit assumptious to include it as per default.

**Comment by thomasnield** [comment]
Yeah I've never designed a library with optional dependencies before, but I think they are nice to use and worth exploring. That sounds like a good route for `HttpUrlConnection`.

**Comment by hastebrot** [comment]
@edvin +1 for having HTTP/REST stuff as optional dependency. Some people also prefer okhttp/retrofit for REST APIs.

You guys are very productive and I haven't even finished TestFX documention.

**Comment by edvin** [comment]
Great, I'll take that into account when I define the REST integration layer. No worries @hastebrot - just really glad you're still with us :)

**Comment by thomasnield** [comment]
I may add some simplified constraint arguments for `GridPane`, `VBox`, and `HBox`. The `Insets` can be pretty verbose. 

So instead of...

```kotlin
hboxConstraints { margin = Insets(0.0,5.0,0.0,0.0) }
```

You can choose to express it as...

```kotlin
hboxConstraints { marginRight = 5.0}
```

**Comment by edvin** [comment]
I like that!

**Comment by thomasnield** [comment]
Awesome, I'll go ahead and add put these on my todo as well.

**Comment by thomasnield** [comment]
You know what else would be awesome? Builders for Menus and MenuItems!

**Comment by thomasnield** [comment]
You know what else would be awesome? Builders for Menus, Submenus, and MenuItems!

**Comment by thomasnield** [comment]
Yeah, I think MenuItem and menus could be a candidate for builders. I always avoided them because I disliked the code involved. But this would be clean and visibly structured with builders.

http://docs.oracle.com/javafx/2/ui_controls/menu_controls.htm
