### ISSUE TITLE
Rest don't have PATCH method

### ISSUE THREAD

**Issue by edipo2s** [edvin/tornadofx#320]
Apache http-client 4.5.3 has already support to PATCH method.

**Comment by edvin** [comment]
Thanks for reporting :) I have committed support for PATCH now, for both the default Rest engine implementations (Apache HttpClient and HttpURLConnection)

**Comment by edipo2s** [comment]
Very Nice, thanks

**Comment by edvin** [comment]
We'll release 1.7.5 with this patch (pun intended) next week :)
