### ISSUE TITLE
SmartResizePolicy flickers

### ISSUE THREAD

**Issue by HaasJona** [edvin/tornadofx#321]
I've a TableView at the center of a borderlayout with smart resize enabled. When resizing the window, the Table flickers annoyingly. Here is a video of the issue: https://gfycat.com/CorruptJollyAfricanbushviper

Relevant code (probably not really special):

                    tableview(workflowModel.elements) {
                        column("Name", MetaModelObject::nameProperty)
                        column("Benutzer", MetaModelObject::ownerProperty)
                        column("Beschreibung", MetaModelObject::commentProperty).formatter(Formatters::formatLongString)
                        column("Änderungsdatum", MetaModelObject::changeTimeProperty).formatter(Formatters::formatInstant)
                        column("Definition", Workflow::workflowDefinition)
                        columnResizePolicy = SmartResize.POLICY
                    }

**Comment by edvin** [comment]
Thanks for reporting this. I probably won't have time to look at this right now, but I'll get to it as soon as possible.

**Comment by edvin** [comment]
Could you possibly create a small/complete test app that displays the problem? I did a quick test and couldn't recreate with any of my existing tables.

**Comment by HaasJona** [comment]
This is enough to reproduce for me:

```kotlin
import javafx.beans.property.SimpleStringProperty
import javafx.collections.FXCollections
import tornadofx.*

class TestView : View("My View") {
    override val root = borderpane {
        center {
            val list = FXCollections.observableArrayList<String>()
            list.add("xxxxxxxxxx".replace("x","Hello "))
            list.add("xxxxxxxxxx".replace("x","World "))
            tableview(list) {
                column("Length", String::length)
                column<String, String>("Contents", {SimpleStringProperty(it.value)})
                column("Length", String::length)
                columnResizePolicy = SmartResize.POLICY
            }
        }
    }
}
```

**Comment by t-boom** [comment]
I can replicate the issue. It looks like if you resize slowly, every other pixel is setting the contents box to min width, which results in the apparent flickering.

**Comment by edvin** [comment]
I see the same. Perhaps the retrieved with is 0 for every other pulse or something like that. It might be enough to not resize when width is zero.

**Comment by edvin** [comment]
Actually, we already do: `if (contentWidth == 0.0) return false`

**Comment by edvin** [comment]
It seems to have to do with the delta that is calculated when column headers are dragged.

**Comment by edvin** [comment]
I think I got it. Can you try it out now?

**Comment by t-boom** [comment]
I tried it out, and can confirm it's fixed, but you probably want to wait to see if @HaasJona sees the same.

**Comment by edvin** [comment]
Thank you @t-boom :)

**Comment by HaasJona** [comment]
I can confirm that it's fixed in the current snapshot version.

**Comment by edvin** [comment]
Perfect, will release 1.7.5 with this fix shortly.
