### ISSUE TITLE
How to pass Rest parameters?

### ISSUE THREAD

**Issue by tezine** [edvin/tornadofx#322]
Hi, I'm starting to play around TornadoFX and it's amazing! 
Unfortunately, I'm not able to find samples beyond the ones you provide in your GitHub. 
For instance, how can I pass parameters to a rest call? I mean, how can I do something like: 

var params = Json.createObjectBuilder().add("login", "mylogin");
api.get("/v1/SEmpresasUsuarios/GetByID/1", params).one().toModel<EEmpresaUsuario>()

By the way, JsonModelAuto simplified my life, but I couldn't find any doc about it. 
Regards/Bruno.

**Comment by edvin** [comment]
Hi! You're nearly there. Remember that `Json.createObjectBuilder` creates a `JsonObjectBuilder`, but what you need is a `JsonObject`. Simply call `.build()` on the first line and `params` will be a `JsonObject` instead.

By the way, TornadoFX also has a `JsonBuilder` which both simplifies the initialization and also accept null values, so it's a lot more lenient. You can therefor write the above as:

```kotlin
var params = JsonBuilder().add("login", "mylogin").build()
api.get("/v1/SEmpresasUsuarios/GetByID/1", params).one().toModel()
```

You should check out the guide and read the *JSON and REST* chapter:

https://edvin.gitbooks.io/tornadofx-guide/content/19.%20JSON%20and%20REST.html

If you feel there are specifics missing, please create an issue and I'd love to elaborate :)

**Comment by tezine** [comment]
Thanks for the help, but I need to pass REST query params. 
This way, params are sent as paypload, not as REST query params. 
If I modify my server function to POST operation, it works fine. 
I'm trying to send REST query params in a GET operation. 
Is it possible or I create an issue?

**Comment by edvin** [comment]
I'm not sure I understand what you mean. Changing to POST shouldn't change anything other than the verb AFAIK. Can you show me how you want the HTTP request to look?

If you're talking about HTTP query params, there is nothing in the framework right now that will turn a JSON object into URL encoded query parameters, but I'm sure we could add support for that. Please illustrate how you want the complete HTTP request to look like, and please clarify how it currently differs when you change from GET to POST :)

**Comment by tezine** [comment]
It's the same as http query params. You can find some info about it at https://www.soapui.org/rest-testing/understanding-rest-parameters.html#1-3-QUERY-Parameters.
In case you want a reference, there's an excellent library for dotnet called flurl( http://tmenier.github.io/Flurl/). It might be usefull. Their api are simple and extremely flexible. Since I have more experience on dotnet, I just don't know if it's feasible to create something like using kotlin.

**Comment by edvin** [comment]
I know what http query parameters are :) 

To pass query parameters, simply append them to the uri:

```kotlin
api.get("/v1/SEmpresasUsuarios/GetByID/1?login=mylogin", params).one().toModel()
```

The parameters will not be url encoded, so you need to do that yourself.

The API you propose (using a JsonObject as a backing store for the query parameters) is a bad fit IMO, since JsonObject is hierarchical. I think a `Map<String, Any?>` would be a better fit.

I would like to extend the api with a `params` parameter which takes a `Map<String, Any?>` and encodes it correctly and appends it to the URI.

**Comment by edvin** [comment]
I've added a function that will turn a Map into a query string, so you can now do:

```kotlin
val params = mapOf("login" to "mylogin")
api.get("/v1/SEmpresasUsuarios/GetByID/1${params.queryString}").one().toModel()
```

**Comment by tezine** [comment]
Thank you Edvin! You saved my life. :-)

**Comment by edvin** [comment]
Great! :)
