### ISSUE TITLE
Support async HTTP

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#323]
Support HttpClient async HTTP

**Comment by edvin** [comment]
Do you have a suggestion for the API?

**Comment by QingMings** [comment]
maybe   callbacks  when  request success  or error ...(I'm a newbie, for kotlin ,Maybe you have a better way)

**Comment by edvin** [comment]
I think we need a broader plan for this, and in any case I think this is a feature best saved until JDK9, where we can rely on the new http client that comes with it :)

**Comment by edvin** [comment]
Oh, I forgot to mention - we do support callbacks,though not async. Check out the rest chapter in the guide:

https://edvin.gitbooks.io/tornadofx-guide/content/19.%20JSON%20and%20REST.html#intercepting-calls
