### ISSUE TITLE
JsonModelAuto boolean values not deserialized

### ISSUE THREAD

**Issue by kastork** [edvin/tornadofx#324]
In 1.7.5-SNAPSHOT (as of 47fd47ed9d991ff91614591546372151fe470601)

Boolean values that were serialized to a file by `JsonModelAuto` are deserialized to `null` by `JsonModelAuto`

The other day on slack when you announced improvements to `JsonModelAuto` this seemed to be working.  At that time, if memory serves, the Boolean values serialized to the strings "true" or "false", now the serialize to `true` or `false` (unquoted in the JSON).

Running the debugger over this, it turns out that when reading, at line 340 of `Json.kt`, the matcher for the boolean does not match when it seemingly should.

```
when (it.returnType.javaType) {
    Boolean::class.java -> (it as KMutableProperty1<Any?, Boolean?>).set(this, json.bool(it.name))
```

**Comment by edvin** [comment]
Can you show me the definition of the field that is failing?

**Comment by edvin** [comment]
I needed to add both of these to cover the different ways Kotlin interprets the types:

```kotlin
Boolean::class.javaPrimitiveType -> (it as KMutableProperty1<Any?, Boolean?>).set(this, json.bool(it.name))
Boolean::class.javaObjectType -> (it as KMutableProperty1<Any?, Boolean?>).set(this, json.bool(it.name))
```

**Comment by kastork** [comment]
I think that got it.  Works in my app also.
