### ISSUE TITLE
The select()-function for ObservableValues does not notice a change of the outer property

### ISSUE THREAD

**Issue by ferrugo** [edvin/tornadofx#326]
The select function that can be used on `ObservableValue`s does not fire a property change if the `ObservableValue` changes. This differs from the behaviour of the Easybind library which can be seen by executing the following example:

```
import javafx.beans.property.SimpleObjectProperty
import javafx.beans.property.SimpleStringProperty
import org.fxmisc.easybind.EasyBind
import tornadofx.select

class A(s : String) {

    val text = SimpleStringProperty(s)
}

fun main(args: Array<String>) {

    val a = SimpleObjectProperty(A("1"))

    val tornadofxSelected = a.select { it.text }
    val easybindSelected = EasyBind.select(a).selectObject { it.text }

    tornadofxSelected.addListener {
        observableValue, old, new ->
        println("Tornadofx selected property change: " + old + " -> " + new)
    }

    easybindSelected.addListener {
        observableValue, old, new ->
        println("Easybind selected property change: " + old + " -> " + new)
    }

    a.value.text.set("2")
    a.value = A("3")
}
```

Running this program yields the folling output (Using TornadoFX 1.7.4 and Easybind 1.0.3):

```
Easybind selected property change: 1 -> 2
Easybind selected property change: 2 -> 3
Tornadofx selected property change: 1 -> 2
```

Both bindings fire a property change if the inner property (text) changes, but only Easybind fires a property change if the outer property (a) changes. I find the behaviour of Easybind to be more useful, as I want a UI element to be updated on every change. However, I have not found a way to create a bidirectional binding using the Easybind `select()`. Therefore, having the TornadoFX `select()` implement the Easybind behaviour would be really useful for me.

**Comment by edvin** [comment]
Thanks for reporting this. I have committed a fix to allow the select binding to listen to changes to the outer property as well. Can you confirm that it is working as expected?

**Comment by ferrugo** [comment]
Thank you for your fast response to this issue. I can confirm that the `select()` function now works as expected in the example code as well as in my actual project.

Btw: Great library!

**Comment by edvin** [comment]
Thank you, glad to hear it :) We will release 1.7.5 tomorrow with this fix :)
