### ISSUE TITLE
Introduce a enum-class for standard status codes in the Rest-Controller

### ISSUE THREAD

**Issue by nimakro** [edvin/tornadofx#330]
I was just looking at the `Rest-Controller` code and I was wondering if we shouldn't add an enum-class which supports the standard status codes, defined in the `HTTP-Protocol`. 
This would have the advantage to writing something like this:
```kotlin
        if (response.statusCode == BAD_REQUEST) ..
```
instead of that:
```kotlin
        if (response.statusCode == 400) ..
```
I think this would be a nice little improvement and make the code a bit more readable?
If you guys agree I will write a PR.

**Comment by edvin** [comment]
I like the idea of including these, but if you make them an enum we need another strategy for comparing the response status code to that enum, since the status code is an int. Do you have a suggestion for dealing with that?

**Comment by edvin** [comment]
I have a suggestion:

Define the enum inside `Response`:

```kotlin
        enum class Status(val code: Int) {
            Continue(100), SwitchingProtocols(101), Processing(102),
            OK(200), Created(201), Accepted(202), NonAuthoritativeInformation(203), NoContent(204), ResetContent(205), PartialContent(206), MultiStatus(207), AlreadyReported(208), IMUsed(226),
            MultipleChoices(300), MovedPermanently(301), Found(302), SeeOther(303), NotModified(304), UseProxy(305), TemporaryRedirect(307), PermanentRedirect(308),
            BadRequest(400), Unauthorized(401), PaymentRequired(402), Forbidden(403), NotFound(404), MethodNotAllowed(405), NotAcceptable(406), ProxyAuthenticationRequired(407), RequestTimeout(408), Conflict(409), Gone(410), LengthRequired(411), PreconditionFailed(412), PayloadTooLarge(413), URITooLong(414), UnsupportedMediaType(415), RangeNotSatisfiable(416), ExpectationFailed(417), IAmATeapot(418), MisdirectedRequest(421), UnprocessableEntity(422), Locked(423), FailedDependency(424), UpgradeRequired(426), PreconditionRequired(428), TooManyRequests(429), RequestHeaderFieldsTooLarge(431), UnavailableForLegalReasons(451),
            InternalServerError(500), NotImplemented(501), BadGateway(502), ServiceUnavailable(503), GatewayTimeout(504), HTTPVersionNotSupported(505), VariantAlsoNegotiates(506), InsufficientStorage(507), LoopDetected(508), NotExtended(510), NetworkAuthenticationRequired(511),
            Unknown(0)
        }
```

Then add a `status` val inside `Response`:

```kotlin
val status: Status get() = Status.values().find { it.code == statusCode } ?: Status.Unknown
```

It allows you to do:

```kotlin
if (response.status == BadRequest) { ... }
```

I will commit it so you can play with it. Let me know what you think!

**Comment by nimakro** [comment]
Hy @edvin sorry for replying so late was gone the whole day yesterday. I think your solution works perfectly and was exactly what I had in mind ;-). I will close this issue since it is resolved. Thanks again.

PS: The only thing I am not so sure of is the formatting of your enums but that's just a personal preference ;-)

**Comment by edvin** [comment]
Great! I've "always" been an uppercase enum kind of guy myself, but lately I just feel like it's shouting. With the neat Kotlin syntax it looks too heavy in my mind :)

**Comment by nimakro** [comment]
Yeah I think that's fine but. The thing I was thinking about was that I just had to scroll to the right a lot to see all the enum's but I can see why you were doing it (Grouping of the enums I supose ?)  ;-)

**Comment by edvin** [comment]
Yeah, I grouped them by type, but that shouldn't matter while using them. Content assist will still help us out :) If it makes it easier to read I have no issues with rearranging them, it was just convenient while I wrote it.

**Comment by nimakro** [comment]
Yeah, that's what I figured, I think we will leave it for now since it has no impact for using it. I actually want to add some documentation in the code, sometime so I might rearrange stuff then and sent you a PR and you can let me know what you think ;-)

**Comment by edvin** [comment]
Thank you, that would be great. I try to add inline docs to new functions that are not 100% self explanatory myself, but there is a significant amount of work to be done to document everything.
