### ISSUE TITLE
Stage in the App View Not Set on onDock()

### ISSUE THREAD

**Issue by bekwam** [edvin/tornadofx#331]
The onDock() method is like the onShown handler.  However, it's called before the onBeforeShow() and doesn't have a valid Stage object.  This only applies to the View of an App and not to Views created by openWindow().

See the NPE from the main View's onDock.  Note that the onDock of the openWindow() target works.

import javafx.stage.Stage
import tornadofx.*

class MPopupView : View("MPopup") {
    override val root = label("hello, world");
    override fun onDock() {
        println("on dock $this")
        (root.scene.window as Stage).minWidth = 480.0
        (root.scene.window as Stage).minHeight = 320.0
    }
}

class MMainView : View("MMain") {
    override val root = button("press me") {
        action {
            find<MPopupView>().openWindow()
        }
    }
    override fun onDock() {
        println("on dock $this")
        (root.scene.window as Stage).minWidth = 480.0
        (root.scene.window as Stage).minHeight = 320.0
    }
}

class MApp : App(MMainView::class)

**Comment by edvin** [comment]
The `onDock` call of the primary view is triggered by `App.createPrimaryScene` because the `UIComponent` detects that a scene is being assigned. I propose to mute docking during setup of the primary view and calling `onDock` manually when everything is set up.

**Comment by edvin** [comment]
Does this work as expected with HEAD?
