### ISSUE TITLE
[Feature Request] Add a programmatic approach to expand/collapse DrawerItem

### ISSUE THREAD

**Issue by Nandiin** [edvin/tornadofx#332]
The `Drawer` and `DrawerItem` is very useful supplementary to JavaFX controls, but one may expect more flexibility.

For now, the toggle button which controls the expand/collapse is declared `internal` and `DrawerItem::expanded` is a read-only property. So there is no natural way to toggle the drawer item content programmatically. One may iterate through `items` of the `Drawer::buttonArea` and then get the button and do some toggling, but this is somehow hack-y. 

Perhaps making `DrawerItem::expanded` a `Property<Boolean>` would make things easier.

**Comment by edvin** [comment]
Good call. I exposed the `selectedProperty` of the button and also a variable for it like this:

```kotlin
val expandedProperty = button.selectedProperty()
var expanded by expandedProperty
```

Is that OK for your use case?

**Comment by edvin** [comment]
I'll close the issue as this seems to be working good :)
