### ISSUE TITLE
Nicer way to access @FXML properties in View

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#34]
To access `@FXML` injected properties in a View you have to use the `lateinit` keyword:

```kotlin
@FXML lateinit var name: TextField
```

This is a bit ugly, and the field is not immutable. It would be preferable to create an immutable field and get rid of the `@FXML` annotation as well:

```kotlin
val name: TextField by fxid()
```

The old syntax would ofcourse still work, since it's already provided by the default `FXMLLoader`.

**Comment by thomasnield** [comment]
You could also use `singleAssign()` but this approach looks cleaner.

**Comment by edvin** [comment]
Maybe I misunderstood you, but `singleAssign()` doesn't perform the actual lookup, which is what we would need `fxid()` to do :)

**Comment by edvin** [comment]
Looking at an implementation now :)

**Comment by edvin** [comment]
Ah, you meant keep the `@FXML` annotation and use singleAssign()? That's interesting..

**Comment by thomasnield** [comment]
Yeah exactly. But I like the idea of that other delegate too. I don't use FXML that much so I'm probably not the best judge as to which is most intuitive, but JavaFX devs might be used to the annotations : )

**Comment by edvin** [comment]
It worked out real nicely. Now you can choose the syntax you like best:

```kotlin
@FXML lateinit var name: TextField
val name: TextField by fxid()
val name by fxid<TextField>()
```

**Comment by edvin** [comment]
A side effect of this feature is that the `FXMLLoader` used to load `root` is available as `fxmlLoader`. This makes it easy to inspect the FXML, find the location of the view declaration etc.

**Comment by thomasnield** [comment]
Cool, I like it. It is simpler and always nice to allow a small set of options.

**Comment by edvin** [comment]
Two of the options are ofcourse just a side effect of options in Kotlin itself. I've already started obsessing over which of the two versions I like best.. hehe :)

**Comment by thomasnield** [comment]
The more I look at it, I do like the fxId() more. Annotations can look ugly on top of the lateinit and mutability. It's worthwhile to rid all the above with a delegate.

**Comment by edvin** [comment]
That's what I feel as well!
