### ISSUE TITLE
GridPane Row Height Problem

### ISSUE THREAD

**Issue by spartajet** [edvin/tornadofx#340]
Hi,Sir.Good afternoon. I have question about the GridPane Row height setting.
As we design by scene builder we can write this xml
```
<columnConstraints>
        <ColumnConstraints halignment="CENTER" hgrow="SOMETIMES" percentWidth="80.0"/>
        <ColumnConstraints halignment="CENTER" hgrow="SOMETIMES" percentWidth="20.0"/>
    </columnConstraints>
    <rowConstraints>
        <RowConstraints vgrow="NEVER" prefHeight="30"/>
        <RowConstraints vgrow="SOMETIMES"/>
        <RowConstraints vgrow="NEVER" prefHeight="50"/>
        <RowConstraints vgrow="NEVER" prefHeight="35"/>
    </rowConstraints>
```
We can control both column and row layouts.
But, in TornadoFx, I read the book and I can only find `constraintsForColumn ()` to control column, I can not find some api method like `constraintsForRow` to control row. 
So, I want to know I could I get it. 
Thank you !!!

**Comment by edvin** [comment]
I think you can use the `gridpaneConstraints` function for this. The guide is not updated to include this information yet it seems :)

**Comment by spartajet** [comment]
But I can not find `percentHeight` in `gridpaneConstraints `

**Comment by edvin** [comment]
That's a column constraint, so you can set the `percentHeight` and `percentWidth` properties with the `gridpaneColumnConstraints` function:

```kotlin
gridpaneColumnConstraints {
    percentWidth = 42.0
    percentHeight = 42.0
}
```

**Comment by QingMings** [comment]
`percentWidth`  in `ColumnConstraints`
and `percentHeight ` in `RowConstraints`

**Comment by edvin** [comment]
You're right, and it seems to be missing. We would need to add it. Unfortunately, I never use the GridPane myself and have little experience with it.

@bekwam - when you have time, perhaps you can help me with this? I feel like the GridPane configuration in TornadoFX is a bit messy, but it might just be because I don't understand it fully.

**Comment by bekwam** [comment]
Hi,

Try this test app which builds a pair of GridPanes.  The first block uses constraints to define fixed row and column sizes.  The second block uses constraints to define percentage-based sizes.

    class GridPaneTestMainView : View("GridPane Test App") {

        override val root = hbox {

            vbox {
                label("Fixed Size")
                gridpane {

                    isGridLinesVisible = true

                    row {
                        label("(0,0)")
                        label("(0,1)")
                        constraintsForRow(0).prefHeight = 50.0
                    }
                    row {
                        label("(1,0)")
                        label("(1,1)")
                        constraintsForRow(1).prefHeight = 50.0
                    }
                    row {
                        label("(2,0)")
                        label("(2,1)")
                        constraintsForRow(2).prefHeight = 50.0
                    }

                    constraintsForColumn(0).prefWidth = 100.0
                    constraintsForColumn(1).prefWidth = 200.0
                }
            }

            vbox {
                label("Percentage")
                gridpane {

                    isGridLinesVisible = true

                    row {
                        label("(0,0)")
                        label("(0,1)")

                        constraintsForRow(0).percentHeight = 25.0
                    }
                    row {
                        label("(1,0)")
                        label("(1,1)")

                        constraintsForRow(1).percentHeight = 25.0
                    }
                    row {
                        label("(2,0)")
                        label("(2,1)")

                        constraintsForRow(2).percentHeight = 25.0
                    }

                    constraintsForColumn(0).percentWidth = 25.0
                    constraintsForColumn(1).percentWidth = 75.0

                }
            }

            vgrow = Priority.ALWAYS
            spacing = 40.0
            padding = Insets(40.0)
        }
    }

**Comment by nimakro** [comment]
@edvin @bekwam what's the status on this can we close?

**Comment by edvin** [comment]
It seems to me that @bekwam demonstrated how this works. I'll close the issue - please reopen if I'm mistaken.
