### ISSUE TITLE
Uncatchable exception with awaitUntil

### ISSUE THREAD

**Issue by AlexP11223** [edvin/tornadofx#342]
In code like this

```
import javafx.beans.property.SimpleBooleanProperty
import tornadofx.*
import kotlin.concurrent.thread


class MMainView : View("MMain") {
    val falseFlagProperty = SimpleBooleanProperty(false)
    var falseFlag by falseFlagProperty

    override val root = borderpane {  }

    override fun onDock() {
        thread {
            Thread.sleep(2000)
            runLater {
                null!!
            }
        }

        try {
            falseFlagProperty.awaitUntil()

            println("Hi")
        } catch (ex: Throwable) {
            println("Error")
        }
    }
}

class MApp : App(MMainView::class)
```

the exception is shown in the output and UI, but none of the print statements are executed. 

I guess it is somehow related to the nested event loop.

I use `awaitUntil` in automated tests and it means that they can pass even when exception is thrown (of course sometimes asserts will still fail after that, or in some cases it is possible to save and rethrow exception later, but it makes the code more complicated/unreliable, so it would be good to fix that). By the way, as far as I can see in JUnit tests (with JfxRunner, #336) assertions after `awaitUntil` are still executed, unlike the print statements here.

**Comment by edvin** [comment]
I think this is as designed and how it should be. The `falseFlagProperty()` is never set to true, so the execution never proceeds below that point. It has nothing to do with the exception really. The `awaitUntil` function never throws an exception either, so it would never enter the `catch` block. This seems just the way it should be to me :)

Do you agree, or am I missing something?

**Comment by edvin** [comment]
I don't think it's the responsibility of await to catch exceptions happening elsewhere. As I understand it, it isn't wrapping the code that happens while we are waiting in the nested event loop, so there is no way for it to catch it. You'd have to catch that elsewhere, and as you pointed out, the `Thread.setDefaultUncaughtExceptionHandler` is probably the easiest. In fact, we could create a wrapper that temporarily reassigns the uncaught handler, perhaps?

**Comment by AlexP11223** [comment]
> I don't think it's the responsibility of await to catch exceptions happening elsewhere

Since it's named "await", I would expect it to behave similarly to Kotlin coroutines and C# async/await, which afaik do bubble up the exception (at the least C#, haven't tried coroutines yet) :)

**Comment by edvin** [comment]
Sounds fair, but unfortunately I don't think it's technically possible.

**Comment by edvin** [comment]
I will close this issue as I can't think of a way to actually implement it, and I'm also pretty sure that it is the result of the actual executing code to catch any exceptions. If you can come up with a way to actually make this possible we could look more closely at the implications.
