### ISSUE TITLE
SortedFilteredList replaces underlying list with filtered items when used in tableview and column title is clicked to sort rows

### ISSUE THREAD

**Issue by doitian** [edvin/tornadofx#344]
It seems sorting uses `setAll` and the implementation of `SortedFilteredList` will forward `setAll` to underlying list.

**Comment by edvin** [comment]
Ah. I did intend for the SortedFilteredList to be editable by writing into the backing list, but not for it to overwrite it entirely. I think `setAll` should be a noop. Will look into it shortly.

**Comment by edvin** [comment]
I believe `setAll` should throw `IllegalStateException` as per the comments in `Collections.add`. Need to run some tests before I make the change though.

**Comment by edvin** [comment]
It looks like simply returning `false` is the best solution. I'm committing the change now, can you confirm that this is working as intended?

**Comment by doitian** [comment]
checking it

**Comment by doitian** [comment]
verified, worked as expected

**Comment by edvin** [comment]
Thank you :)
