### ISSUE TITLE
Json  support resolve multiple keys to the same field

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#350]
functionally similar to Gson 
example :
`@SerializedName(value = "createDate", alternate = {"creation_date", "creation_time","time"}) `
json keys `creation_date`,`creation_time`,`time` Any one of them can mapping to my model filed `createDate`

![image](https://user-images.githubusercontent.com/22107668/27371660-416a18f4-5694-11e7-9e86-adb4bfcb4d27.png)

**Comment by edvin** [comment]
The `JsonModel` in TornadoFX requires you to explicitly extract the values, so you can do this pretty easily:

```kotlin
override fun updateModel(json: JsonObject) {
    creationTime = datetime("creation_date") ?: datetime("time")
}
```

The JsonModelAuto does not support any such functionality so you would have to use this explicit approach, which is always a good idea anyway.

**Comment by QingMings** [comment]
Well, I mean, add an extension method for `javax.json.JsonObject`，
like this 
``` kotlin
fun <T> javax.json.JsonObject.mulitkeys(vararg keys:String,impl:(key:String)->T):T{
     var sk=""
    keys.takeWhile { isNotNullOrNULL(it) }.forEach { k-> sk=k }
    return impl(sk)
}
```
and  use it in mymodel like this 
``` kotlin 
override fun updateModel(json: JsonObject) {
        with(json){
            createDate=mulitkeys("creation_date","creation_time","time"){key ->  bigdecimal(key)}
          }
    }
```

**Comment by edvin** [comment]
Aha, I see! Let me play with that for a second...

**Comment by edvin** [comment]
It looks like we can augment the existing functions so they accept varargs. Will get back to you with an implementation ASAP.

**Comment by edvin** [comment]
You can now write:

```kotlin
createDate = bigdecimal("creation_date","creation_time","time")
```

**Comment by QingMings** [comment]
perfect.  Thanks  👍
