### ISSUE TITLE
Error Build jar file

### ISSUE THREAD

**Issue by ProALiOnLine** [edvin/tornadofx#352]
Hi ..
when build jar file from Artifacts and setting MAINFEST.MF As

Manifest-Version: 1.0
Main-Class: test.app.MyApp
 
and When implemented jar file the error appeared

no main manifest attribute

Thank You

**Comment by ProALiOnLine** [comment]
I Found The Solution by change MAINFEST.MF file location like this

Make sure your MANIFEST.MF is in:

src/main/resources/META_INF/

NOT

src/main/java/META_INF/

**Comment by edvin** [comment]
Why do you create the manifest manually? What build system are you using?

**Comment by ProALiOnLine** [comment]
I did not create the manifest manually just create folder resources and change path 
from  src/main/java/META_INF/
to  src/main/resources/META_INF/ 
by Intellij IDEA

**Comment by edvin** [comment]
OK :) So you're just using IDEA to built your project? To have reproducible builds you should consider using Maven or Gradle :)
