### ISSUE TITLE
ModelView with list binding

### ISSUE THREAD

**Issue by aymen083** [edvin/tornadofx#353]
Hi,

I have an problem withTonadoFx plugin when generating viewModel with a list.
I got an error on : 
```kotlin
 val exampleSubOjects = bind { SimpleObjectProperty(item?.exampleSubOjects) }
```
And i didn't get how to make it correct can you help me please.

I have a have a difference in reading boolean from json with old property syntax i can make : 
```kotlin
 testbool = boolean("testbool")
```
But now i have to put the default value : 
```kotlin
testbool = boolean("testbool") ?: false
```

By the way i have some strange behavior when using the plugin the convert all properties to TornadoFX properties on this example : 
```kotlin
class Example(var testString : String,var testbool : Boolean) 
```
I get : 
```kotlin
class Example(var testString : String,var testbool : Boolean) {
    val testStringProperty = SimpleStringProperty()
    var testString by testStringProperty
}
```
I have the TornadoFX support Version: 1.7.7.1.

This is the complete exemple : 
```kotlin
class Example : JsonModel {
    val testStringProperty = SimpleStringProperty()
    var testString by testStringProperty

    val testboolProperty = SimpleBooleanProperty()
    var testbool by testboolProperty

    val exampleSubOjects = FXCollections.observableArrayList<ExampleSousObject>()

    override fun updateModel(json: JsonObject) {
        with(json) {
            testString = string("testString")
            testbool = boolean("testbool") ?: false
            exampleSubOjects.setAll(getJsonArray("exampleSubOjects").toModel())
        }
    }

    override fun toJSON(json: JsonBuilder) {
        with(json) {
            add("testString", testString)
            add("testbool", testbool)
            add("exampleSubOjects", exampleSubOjects.toJSON())
        }
    }
}

class ExampleModel : ItemViewModel<Example>() {
    val testString = bind(Example::testStringProperty)
    val testbool = bind(Example::testboolProperty)
    val exampleSubOjects = bind { SimpleObjectProperty(item?.exampleSubOjects) }
}


class ExampleSousObject : JsonModel {
    val testProperty = SimpleStringProperty()
    var test by testProperty

    override fun updateModel(json: JsonObject) {
        with(json) {
            test = string("test")
        }
    }

    override fun toJSON(json: JsonBuilder) {
        with(json) {
            add("test", test)
        }
    }
}
```

Thx
Aymen NOUIRA

**Comment by edvin** [comment]
Hi! I will release a new version (1.7.8) of the plugin today with fixes for these issues. Let's walk through them:

1. `val exampleSubOjects = bind { SimpleObjectProperty(item?.exampleSubOjects) }`

This should now be rendered as `val exampleSubOjects = bind(Example::exampleSubOjects)`

2. The `boolean("testbool")` json function returns `Boolean?`. You can either call `getBoolean("testbool")` which returns `Boolean`, or you can change the definition of the accessor to allow it to be null: `var testbool: Boolean? by testboolProperty`

3. `class Example(var testString : String,var testbool : Boolean) ` should now render corectly as:

```kotlin
class ExampleModel : ItemViewModel<Example>() {
    val testString = bind(Example::testString)
    val testbool = bind(Example::testbool)
}
```

**Comment by aymen083** [comment]
Thank you very match for tour reactivity.

**Comment by edvin** [comment]
My pleasure, and thanks for reporting. The new plugin version is published now.
