### ISSUE TITLE
How to display both javanese and emoji inside a table cell?

### ISSUE THREAD

**Issue by huangyg11** [edvin/tornadofx#357]
In a table cell, I have some text containing some emoji and javanese. And the text is dynamically loaded from database.  I can use different fonts to display either one well but not both.

Can I add multiple fonts to a cell or divide the text to different node and apply different font each.

**Comment by edvin** [comment]
You can set the `graphic` property of a cell inside of `cellFormat` and create multiple nodes where each node can use a different font. Something like:

```kotlin
column("Name", Person::nameProperty).cellFormat {
    graphic = hbox(10) {
        label() { }
        label() { }
    }
}
```

**Comment by huangyg11** [comment]
Actually, it is the `Person::nameProperty` contains special chars. So it is something like this ?

    column("Name", "").cellFormat {
       divide nameProperty to parts by unicode catolog
        graphic = hbox(10) {
            for parts in parts
            label() { part}

**Comment by edvin** [comment]
If `part` is just a string, you need to assign it to the label, so it would be something like:

```kotlin
for parts in parts
        label(part)
```
