### ISSUE TITLE
Table useCheckbox with the new model syntax

### ISSUE THREAD

**Issue by aymen083** [edvin/tornadofx#359]
Hi,

When using new syntax for model : 
```kotlin
class Example {
    val boolTestProperty = SimpleBooleanProperty()
    var boolTest by boolTestProperty 
}
```

I can't use the method useCheckbox in columns in an editable table : 

```kotlin
tableview(exampleList) {
            isEditable = true
            column("boolTest ", boolTest::group).useCheckbox()
        }
```

The boolean is not optional any more and the method signature useCheckbox doesn't match :  

```kotlin
fun <S> TableColumn<S, Boolean?>.useCheckbox(editable: Boolean = true): TableColumn<S, Boolean?> {
    setCellFactory { CheckBoxCell(editable) }
    if (editable) {
        Platform.runLater {
            tableView?.isEditable = true
        }
    }
    return this
}
```

Thx

**Comment by edvin** [comment]
Make sure you reference the property, not the accessor in the column definition and you should be good:

```kotlin
column("Booltest", Example::boolTestProperty).useCheckbox()
```

@t-boom Do you think we could account for both nullable and non-nullable Booleans in the useCheckbox function somehow? As long as one reference JavaFX properties this shouldn't be an issue, but for non-JavaFX Properties this might be confusing.

**Comment by aymen083** [comment]
Thanks for the response :+1: 

So for other property type like string is recommended to use the suffixed property attribute or the other one ?

Thanks.

**Comment by edvin** [comment]
Well, that depends on what you want to do. But remember that the accessor `var boolTest by boolTestProperty` is not observable, and hence cannot be used to create a bidirectional binding between itself and a UI node. Using the Properties greatly simplifies the work needed to be done to maintain a consistent state between your UI and data.

**Comment by aymen083** [comment]
Thx for reponse i get it.
