### ISSUE TITLE
How to access modalStage in a fragment?

### ISSUE THREAD

**Issue by huangyg11** [edvin/tornadofx#360]
In a fragment opened by the main view, I tried to access modalStage in  init block and onDock callback. Neither works.  In init block, it give me null exception, and the onDock callback seems not been called.

**Comment by edvin** [comment]
Ondock should be good, can you post a small sample that triggers the error?

**Comment by huangyg11** [comment]
I tested it again, onDock was called.

What I want to do is placing the fragment in the left-up corner of screen. But the code is not working. The fragment is placed in the middle of screen. 

    override fun onDock() {
        val visualBounds = Screen.getPrimary().visualBounds
        with(modalStage!!) {
            width = visualBounds.width / 2
            height = visualBounds.height
            x = visualBounds.minX
            y = visualBounds.minY
        }
    }

**Comment by huangyg11** [comment]
setting the x in on dock not work. But if I set it in ui thread, it works.

        runAsync {
            controller.loadInfo() // run for several seconds
        } ui {
            modalStage!!.x = 0.0
        }

**Comment by edvin** [comment]
I will get back til you with a solution when I get to a computer :)

**Comment by edvin** [comment]
You should already be on the UI thread in `onDock`, so I suspect that `onDock` is simply called to early for what you want to do. Looking at better solutions now.

**Comment by edvin** [comment]
What's happening here is that the framework is resizing the window after `onDock` is called, so your changes are overridden.  I have committed a fix so that the window is now resized before `onDock` is called, so that your changes will no longer be overriden in 1.7.9.

A simple solution right now is to wrap your code in `runLater`, so that it will run after the framework has resized the window:

```kotlin
override fun onDock() {
    runLater {
        val visualBounds = Screen.getPrimary().visualBounds
        with(modalStage!!) {
            width = visualBounds.width / 2
            height = visualBounds.height
            x = visualBounds.minX
            y = visualBounds.minY
        }
    }
}
```

If you have the chance - can you also try with the latest HEAD to see if you can remove the `runLater` call and still get the same result?

**Comment by huangyg11** [comment]
runLater works well. And I changed dependency to 1.7.9-snapshot in gradle, it doesn't work. No idea whether it is related to my configuration causing wrong jar downloaded

**Comment by edvin** [comment]
The snapshot with the fix hasn't been published yet, so you either need to build from source or wait until after 16:00 CEST :) If you have a chance to try again tonight that would be great!

**Comment by huangyg11** [comment]
the latest snapshot works!  Thanks!
