### ISSUE TITLE
Documentation required

### ISSUE THREAD

**Issue by jschneider** [edvin/tornadofx#361]
Hey, 

thanks for your great work. I am taking a first look at tornadofx and it looks really promising.
Unfortunately most of the classes and functions are not documented yet. I think this would be very helpful for your fellow users if there were a little bit of documentation for each class.

**Comment by edvin** [comment]
Hi and thanks for your kind words :) We elected to gather documentation in the Guide for now, but we have discussed that we would like to add documentation in code as well. It's not being prioritized right now, but we will definitely get around to it down the line. For now, start with the Guide, and join us on Slack if you have any questions. We're usually very quick to get back to you.

Guide: https://www.gitbook.com/book/edvin/tornadofx-guide/details
Slack: https://kotlinlang.slack.com/messages/

**Comment by DrFornax** [comment]
Could you please explain how to join slack? It looks like this is only possible if I have a jet brains account? I have also several questions concerning the documentation. Thank you very much.

**Comment by nimakro** [comment]
Hey @DrFornax you can go to this url http://slack.kotlinlang.org/ and sign up with your e-mail address.
Once signed up, you can join the #tornadofx channel.

**Comment by DrFornax** [comment]
Thank you very much. This was very helpful :-)

**Comment by nimakro** [comment]
No problem and you are very welcome. We looking forward to all your questions on #tornadofx channel!
