### ISSUE TITLE
Writing to app.config from a component writes to the Component's config file instead

### ISSUE THREAD

**Issue by akbcode** [edvin/tornadofx#362]
I'm calling `app.config.save()` from the Controller but it saves to Controller.properties instead of app.properties. Here's a small program that demostrates the problem.

```
fun main(args: Array<String>) {
    Application.launch(TestApp::class.java, *args)
}

class TestApp: App(TestView::class)

class TestView: View("Test") {
    val controller: TestController by inject()

    override val root = hbox {
        button("Saves to App Config").action(controller::rightSave)
        button("Saves to Controller config").action(controller::wrongSave)
    }
}

class TestController: Controller() {
    fun wrongSave() {
        app.config.set("a" to 1)
        app.config.set("b" to 2)
        app.config.save()
    }

    fun rightSave() {
        with(app) {
            config.set("a" to 1)
            config.set("b" to 2)
            config.save()
        }
    }
}
```

`save` and `set` are extension functions on `Properties` defined in `Configurable`. Since both `App` and `Component` implement `Configurable`,  and extension functions are resolved statically, the this object passed to save is the Controller instead of the app. I need to use with(app) to ensure that the right save is called.

This should at least be documented if not fixed.

**Comment by edvin** [comment]
Thanks for reporting this. That's the first time extension functions has bit us in my experience :)

I have committed a fix, could you try it to see if it works for you? You might need to rebuild your whole project.

**Comment by akbcode** [comment]
Thanks, that fixed it for me.
