### ISSUE TITLE
cellFormat for ListView and ComboBox?

### ISSUE THREAD

**Issue by cksolomon** [edvin/tornadofx#364]
I am migrating our code from Tornado FX 1.5.7 to 1.7.8.  What happened to the cellFormat function for ListView and ComboBox? Does it need to be called in a different manner? It appears that the cellFormat function is only available to the receiver types TableColumn, TreeTableColumn, and TreeView.

`combobox<String> {
	cellFormat {
	}
}`
`listview<String> {
	cellFormat {
	}
}`

![image](https://user-images.githubusercontent.com/26065177/28168299-3d951154-67a4-11e7-934b-f3d0b4753d9c.png)

**Comment by edvin** [comment]
That exact code is still valid. Perhaps you forgot to change to jvmTarget 1.8 in your project?

More info in the release notes for 1.7.1: https://github.com/edvin/tornadofx/releases/tag/v1.7.1

If this doesn't solve your problem, could you create a minimal sample that fails to compile?
