### ISSUE TITLE
nullableParam fix?

### ISSUE THREAD

**Issue by tieskedh** [edvin/tornadofx#369]
To start, I read about nullableParam and tried something out.
If the "quirk" in Kotlin was that the defaultValue could not be returned,  if the parameter is nullable, the following code fixes the problem.

```kotlin   
 inline fun <reified T> Component.param2(defaultValue: T? = null): ReadOnlyProperty<Component, T> = 
    object : ReadOnlyProperty<Component, T> {
    override fun getValue(thisRef: Component, property: KProperty<*>): T {
        val nullable = property.returnType.isMarkedNullable
        val param = thisRef.params[property.name] as? T
        if (param == null) {
            if (defaultValue!=null) return defaultValue
            if (nullable) return defaultValue as T
            throw IllegalStateException("param for name [$property.name] has not been set")
        } else {
            return param
        }
    }
}
```

If not, what exactly is the quirk?

**Comment by edvin** [comment]
I honestly can't remember, but I didn't know about `isMarkedNullable` and as far as I can see, this solves the issue! Do you want to submit a PR that replaces `param` and marks `nullableParam` as deprecated? Thank you for this!

**Comment by edvin** [comment]
PS: You could delay the call to `property.returnType.isMarkedNullable` until you actually use it :)
