### ISSUE TITLE
Add SequentialTransition, ParallelTransition Builders

### ISSUE THREAD

**Issue by bekwam** [edvin/tornadofx#373]
To run a sequence of timeline() objects, you need to add them to a plain JavaFX class "SequentialTransition".  Make a builder for SequentialTransition and a builder for ParallelTransition.  I think these should also influence the play flag passed into the timeline() builder.

This code is an example of how the JavaFX classes are used today.

`class STTest : View("My View") {

    val r1 = Rectangle(20.0, 20.0, Color.RED)
    val r2 = Rectangle(20.0, 20.0, Color.YELLOW)
    val r3 = Rectangle(20.0, 20.0, Color.GREEN)
    val r4 = Rectangle(20.0, 20.0, Color.BLUE)

    override val root = vbox {

        button("Animate") {
            setOnAction {

                val t1 = timeline(false) {
                    keyframe(Duration.seconds(0.5)) {
                        keyvalue(r1.translateXProperty(), 50.0, interpolator = Interpolator.EASE_BOTH)
                    }
                }
                val t2 = timeline(false) {
                    keyframe(Duration.seconds(0.5)) {
                        keyvalue(r2.translateXProperty(), 100.0, interpolator = Interpolator.EASE_BOTH)
                    }
                }
                val t3 = timeline(false) {
                    keyframe(Duration.seconds(0.5)) {
                        keyvalue(r3.translateXProperty(), 150.0, interpolator = Interpolator.EASE_BOTH)
                    }
                }
                val t4 = timeline(false) {
                    keyframe(Duration.seconds(0.5)) {
                        keyvalue(r4.translateXProperty(), 200.0, interpolator = Interpolator.EASE_BOTH)
                    }
                }

                val st = SequentialTransition()
                st.children += t1
                st.children += t2
                st.children += t3
                st.children += t4

                st.play()
            }
        }
        pane {
            add(r1)
            add(r2)
            add(r3)
            add(r4)
        }
    }
}`

**Comment by edvin** [comment]
I've added `sequentialTransition` and `paralellTransition` builders which will autoplay by default (with an option to not play). It also makes sure to not play the added timelines automatically. You can use it like this:

 ```kotlin
class MyView : View() {
    val r1 = Rectangle(20.0, 20.0, Color.RED)
    val r2 = Rectangle(20.0, 20.0, Color.YELLOW)
    val r3 = Rectangle(20.0, 20.0, Color.GREEN)
    val r4 = Rectangle(20.0, 20.0, Color.BLUE)

    override val root = vbox {
        button("Animate").action {
            sequentialTransition {
                timeline {
                    keyframe(0.5.seconds) {
                        keyvalue(r1.translateXProperty(), 50.0, interpolator = Interpolator.EASE_BOTH)
                    }
                }
                timeline {
                    keyframe(0.5.seconds) {
                        keyvalue(r2.translateXProperty(), 100.0, interpolator = Interpolator.EASE_BOTH)
                    }
                }
                timeline {
                    keyframe(0.5.seconds) {
                        keyvalue(r3.translateXProperty(), 150.0, interpolator = Interpolator.EASE_BOTH)
                    }
                }
                timeline {
                    keyframe(0.5.seconds) {
                        keyvalue(r4.translateXProperty(), 200.0, interpolator = Interpolator.EASE_BOTH)
                    }
                }
            }
        }
        pane {
            add(r1)
            add(r2)
            add(r3)
            add(r4)
        }
    }
}
```
