### ISSUE TITLE
Animation Enhancements

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#374]
Ideas for animation enhancements form slack

> **Edit**: Moved relative animation helpers to #395.

# Point Helpers

Add an `infix fun Number.p(y: Number) = Point2D(this.toDouble(), y.toDouble())`

Also maybe add an `infix fun Point2D.z(z: Number) = Point3D(x, y, z)`

# Play Animations Helpers

We could add some functions like these

```
fun Iterable<Animation>.playSequential(op: (SequentialTransition.() -> Unit)? = null) = SequentialTransition().apply {
    children.setAll(toList())
    op?.invoke(this)
    play()
}

fun Iterable<Animation>.playParallel(op: (ParallelTransition.() -> Unit)? = null) = ParallelTransition().apply {
    children.setAll(toList())
    op?.invoke(this)
    play()
}
```
> Should we check if the `Iterable`s are already `Collection`s?

# Animation Chain Infixes

We could add some simplified infix function for sexy animation chaining.

```
infix fun Animation.and(animation: Animation) = ParallelTransition(this, animation)
infix fun Animation.then(animation: Animation) = SequentialTransition(this, animation)
```
I'd also recommend adding the following to enhance these without adding extra object creation overhead:
```
infix fun ParallelTransition.and(animation: Animation) = apply { children += animation }
infix fun SequentialTransition.then(animation: Animation) = apply { children += animation }
```

**Comment by t-boom** [comment]
We should probably go through these and see if there are places we can replace `Double`s with `Number`s. I know `rotate` and `fade` both take `Double`s for their target values.

**Comment by edvin** [comment]
Good idea. I dit something similar to Nodes earlier and that worked out great.

**Comment by t-boom** [comment]
There are a number of other transitions we may want to add support for:
- [FillTransition](https://docs.oracle.com/javase/8/javafx/api/javafx/animation/FillTransition.html)
- [PathTransition](https://docs.oracle.com/javase/8/javafx/api/javafx/animation/PathTransition.html)
- [PauseTransition](https://docs.oracle.com/javase/8/javafx/api/javafx/animation/PauseTransition.html)
- [StrokeTransition](https://docs.oracle.com/javase/8/javafx/api/javafx/animation/StrokeTransition.html)

**Comment by t-boom** [comment]
I've started working on this task. If anyone wants to pick up on it while I'm offline, you can checkout my branch ([feature/animation-enhancements](https://github.com/edvin/tornadofx/tree/feature/animation-enhancements)).

I've added the "Play Animation Helpers" and the "Animation Chain Infixes". I also started on the "Other Transitions", but haven't handled reversing for them (I left TODOs).

**Comment by t-boom** [comment]
The Double -> Number fix is implemented, as is the reversing for the 4 new transitions.

@edvin 2 Questions:
1. Did you decide the `p` infix function for `Point2D` was what you wanted?
2. I get the feeling the relative animation helpers are going to be a larger undertaking since I'm not sure the best way to handle setting the values at the right time. Should we separate that out into a separate issue and commit the changes for rest?

**Comment by edvin** [comment]
Great!

1. Not sure, maybe `p` is too vague. Maybe  'x` or `xy` is better?
2. Good plan!

**Comment by t-boom** [comment]
Either way works for me. I don't tend to use infix functions, so I would probably do something like
```kotlin
fun point(x: Number, y: Number) = Point2D(x.toDouble(), y.toDouble())
fun point(x: Number, y: Number, z: Number) = Point3D(x.toDouble(), y.toDouble(), z.toDouble())
```
but the infix functions do feel more TFXy. I'll do `xy` for now, and we can discuss if something else would be better before actually merging.

**Comment by edvin** [comment]
It's great to support both styles, and I think we can live with `xy`. Pretty sure it will never clash with anything at least :)

**Comment by t-boom** [comment]
Added `xy` helper for `Point2D`

**Comment by t-boom** [comment]
I believe this issue can be closed now. Is that correct?

**Comment by edvin** [comment]
Absolutely, stellar work as always, Matthew!
