### ISSUE TITLE
Issue with generic property bindings

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#383]
There's an extra `?` in [Properties.kt:211](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Properties.kt#L211).

The line should be changed to

```
operator fun <T> Property<T>.setValue(thisRef: Any, property: KProperty<*>, value: T?) = setValue(value)
  Notice removed '?' here ^
```

I'm having trouble getting TornadoFX to build on my local machine for some reason, so hopefully someone else can take care of this.

**Comment by edvin** [comment]
Thank you, fixed :))
