### ISSUE TITLE
DataGrid inconsistent update behaviour

### ISSUE THREAD

**Issue by PvdBerg1998** [edvin/tornadofx#385]
DataGrid does not update its items when they are removed from a bound data collection.

It's also inconsistent, it seems that the first removal succeeds, after that nothing happens.
The cells update to their correct contents when clicking on them.

Sample code:
```Kotlin
scrollpane() {
	content = datagrid(data) {
		cellFormat { x -> ... }
	}
}

fun x()
{
	data.remove( ... )
}
```

I haven't tested if the scrollpane makes a difference.
Note that you can swap the datagrid with a listview - which works fine.

Switching cellFormat to cellCache makes no difference.

**Comment by edvin** [comment]
Does it only fail when you remove from the bound list, or if you remove from the items property of the datagrid as well? As small runnable sample would be great, but I'll try to investigate myself in the meantime.

**Comment by edvin** [comment]
Ah, I see what's going on. Working on it now :)

**Comment by edvin** [comment]
I have committed a fix now, so that the itemsPropertyChangeListener is correctly called. Does it work for you now?

**Comment by PvdBerg1998** [comment]
Appears to be fixed :)
