### ISSUE TITLE
DataGrid does not set a new selected item after removing one

### ISSUE THREAD

**Issue by PvdBerg1998** [edvin/tornadofx#386]
- Say I have 3 items,
- I have the first one selected.
- Now I remove the first one from the bound list
- so the items move back 1 spot.

The selection highligher stays on the first item, which is now what was node 2. The selectedItemProperty should update, but it does not. To compare with `listView` once again: there the property does get updated.

**Comment by edvin** [comment]
This was actually partially fixed when we did https://github.com/edvin/tornadofx/issues/385. The only difference is if you delete the item that's selected. Right now no item would be selected, but we could make it so that the item in front of it if any is selected.

**Comment by PvdBerg1998** [comment]
I'd prefer if the dataGrid reselected the same index, because then you can keep on removing the same index without having to reselect it manually every time. I agree it should only happen in SelectionMode.SINGLE.

**Comment by edvin** [comment]
I agree! Committed a fix for it now :) Thanks for reporting these issues :)
