### ISSUE TITLE
ItemViewModel's bind methods should accept properties that return nullable values

### ISSUE THREAD

**Issue by DaanVandenBosch** [edvin/tornadofx#389]
E.g. (a single question mark was added to the signature):

```kotlin
inline fun <reified N : Any, ReturnType : Property<N>> bind(property: KProperty1<T, N?>, autocommit: Boolean = false, forceObjectProperty: Boolean = false): ReturnType
            = bind(autocommit, forceObjectProperty) { item?.let { property.get(it).toProperty() } }
```

This small change makes the following compile and makes working with immutable data classes easier:

```kotlin
data class Thing(val amount: Int?,
                 val imageUrl: String?)

class ThingModel : ItemViewModel<Thing>() {
    val amount = bind(Thing::amount)
    val imageUrl = bind(Thing::imageUrl)
}
```

Also, is there a more lightweight way to wrap an immutable data class that could be null? One solution I was using before was this:

```kotlin
fun <S, T> ObservableValue<S>.binding(prop: KProperty1<S, T?>): Binding<T>
        = Bindings.createObjectBinding<T>(Callable { value?.let { prop.get(it) } }, this)

data class Thing(val name: String)
val thing = SimpleObjectProperty<Thing>()
label(thing.binding(Thing::name))
```

**Comment by edvin** [comment]
Great, this change seems to have no side effects other than allowing nullable property values. I'll make the change now. 

As for the wrapping issue I think that's light weight enough. We could add that function as an overload to the `objectBinding` functions we already have perhaps.

**Comment by DaanVandenBosch** [comment]
After playing with the existing *Binding functions I think it's best to leave things as they are. It's a little more verbose than I'd like but this way everything maps clearly to JavaFX. Writing `thing.stringBinding { it?.name }` isn't that bad.

You could add a version like below but that will break existing code.
```kotlin
fun <T> ObservableValue<T>.stringBinding(op: (T) -> String?): StringBinding
        = Bindings.createStringBinding(Callable { value?.let(op) }, this)

thing.stringBinding(Thing::name) // Works now
thing.stringBinding { it?.name ?: "default value" } // Will call the above and thus won't work correctly anymore ("default value" won't be set when value is null)
```

Adding overloads just for KProperties seems a bit limited and adding more function names doesn't seem like a good idea either. I'll close the issue and thanks for adding the question mark. ;)
