### ISSUE TITLE
Should all convenient functions return the node it was called on?

### ISSUE THREAD

**Issue by nimakro** [edvin/tornadofx#390]
For example `addClass` allows to do the the following `val awesomeNode = somenode().addClass()`.
This is currently not possible with `visibleWhen` since it is not returning any thing. I have the case where I create a `Node` where I only want to set the visible property.
@edvin Would it be oky for you, if I change this.

**Comment by edvin** [comment]
Yes, if a function makes sense to use in a place where it isn't encapsulated with a builder lambda it absolutely makes sense that it returns itself. I've tried to make sure that it returns the specific type so you don't loose the ability to call any other functions on it after the first call.

**Comment by nimakro** [comment]
Oky, will try to go through the code this weekend and update were needed.

**Comment by edvin** [comment]
Thank you!
