### ISSUE TITLE
Memoryleak with FX.Companion.applyStylesheetsTo()

### ISSUE THREAD

**Issue by HaasJona** [edvin/tornadofx#391]
The `stylesheets` ObservableList in FX.kt has `ListChangeListener`s that hold strong references to the `Scene`. This causes memory leaks because the `Scene`s and their content will not be garbage collected anymore.

Screenshot from VisualVM heap dump analyzer:

![screenshot](https://user-images.githubusercontent.com/4310707/28707914-7f913812-737a-11e7-95f2-d6a04fadd115.png)

**Comment by edvin** [comment]
You're right, good catch! Would you like to submit a PR with a weak reference for this instead?

**Comment by HaasJona** [comment]
I tried fixing this but I can't compile to test my changes:

```
[INFO] --- kotlin-maven-plugin:1.1.3-2:compile (compile) @ tornadofx ---
[INFO] Kotlin version 1.1.3-2 (JRE 1.8.0_141-b16)
[INFO] Compiling Kotlin sources from [/home/jh/IdeaProjects/tornadofx/src/main/java]
[INFO] Module name is tornadofx
[ERROR] /home/jh/IdeaProjects/tornadofx/src/main/java/tornadofx/Component.kt: (5, 16) Unresolved reference: deploy
[ERROR] /home/jh/IdeaProjects/tornadofx/src/main/java/tornadofx/Component.kt: (97, 52) Unresolved reference: HostServicesFactory
```

**Comment by edvin** [comment]
Are you using OpenJDK? You need Oracle JDK, could that be it?

**Comment by HaasJona** [comment]
Yeah, nevermind. I used the right JDK and it compiles now. Testing now.
