### ISSUE TITLE
Forms broke with 1.7.9

### ISSUE THREAD

**Issue by TheJhonny007** [edvin/tornadofx#401]
- ~~The title of fieldsets isn't shown anymore~~
- the spacing between the field name and the field content is 0

**Comment by edvin** [comment]
This has already been resolved, can you check that the latest snapshot release fixes the issue you're seeing?

**Comment by TheJhonny007** [comment]
The fieldset does now show the Title, but the spacing is still not right. As you can see there is no space between the longest field and its item.


![login](https://user-images.githubusercontent.com/9581540/29115379-c54cc232-7cf7-11e7-9366-63acb4395ba3.PNG)

**Comment by edvin** [comment]
I just checked a test app in the framework, and the padding is correct there. Can you show me the exact code used to render this form?

**Comment by TheJhonny007** [comment]
```kotlin
class LoginView : Fragment("Login") {

	val model = ViewModel()
	val nameProperty = model.bind { SimpleStringProperty() }
	val passwordProperty = model.bind { SimpleStringProperty() }

	override val root = form {
		fieldset("Login") {

			field("Name") {
				textfield(nameProperty) {
					promptText = "Name"
				}.required()
			}

			field("Passwort") {
				passwordfield(passwordProperty) {
					promptText = "Passwort"
				}.required()
			}
		}

		buttonbar {
			button("Login") {
				isDefaultButton = true
				enableWhen { model.valid }

				action {
					//do stuff
				}
			}

			button("Schließen") {
				isCancelButton = true

				action {
					Platform.exit()
				}
			}
		}
	}
}
```

**Comment by edvin** [comment]
I see it in your sample. Investigating now :)

**Comment by edvin** [comment]
I see it, this is another side effect of the same PR that caused the other issue. Fixing it now.

**Comment by edvin** [comment]
Done. I think we'll do another release very soon. Can you use a snapshot in your app in the meantime?

**Comment by TheJhonny007** [comment]
Yeah that is no problem.

**Comment by TheJhonny007** [comment]
When do you publish the snapshot?

**Comment by edvin** [comment]
Normally at 16:00 GMT every day, but I'll push one right now :)
