### ISSUE TITLE
FXML not found

### ISSUE THREAD

**Issue by nihiluis** [edvin/tornadofx#405]
Did I perhaps forget to setup something? No clue whatsoever. Appreciate any input

erreur
`java.lang.IllegalArgumentException: FXML not found for class com.bob.lol.MainView in ./root.fxml`

code
```kotlin
class MainView : View("Hi") {
    override val root: HBox by fxml("./root.fxml")
    val label: Label by fxid()
    val actionButton: Button by fxid()

    init {
        println("viewing")
    }
}
```

root.fxml
```
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.control.Button?>
<?import javafx.scene.layout.VBox?>


<VBox maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/8.0.92" xmlns:fx="http://javafx.com/fxml/1">
   <children>
      <Button mnemonicParsing="false" text="Button" fx:id="actionButton" />
   </children>
</VBox>
```

Picture of the jar with root.fxml at the bottom
https://i.imgur.com/0z11MzQ.png

**Comment by edvin** [comment]
`./root.fxml` would mean "root.fxml in current directory", but what you want is "/root.fxml" which means "root.fxml in root".

Please not that this has nothing to do with TornadoFX, just how Java interprets the class path.

**Comment by nihiluis** [comment]
oops. my bad

**Comment by edvin** [comment]
Hehe, I'm actually glad that you posted this, now we have it documented for others as well :)
