### ISSUE TITLE
Browsable API docs?

### ISSUE THREAD

**Issue by Valloric** [edvin/tornadofx#409]
Thanks for creating TornadoFX! I'm still exploring options for Kotlin + JavaFX for a new app, but TornadoFX already seems like the most sensible choice.

The Guide is great as is the Wiki, but I can't seem to find any hosted API docs for TornadoFX. (I'd like to explore the methods on types that are introduced in the Guide.)

[Javadoc.io shows a weird JavaDocTrap class and nothing else.](https://www.javadoc.io/doc/no.tornado/tornadofx/1.7.7) I understand that Kotlin (which I have very little experience with) has KDoc instead of JavaDoc which might be making your life more difficult.

I could also be completely blind and you have API docs hosted somewhere and I can't find it, but if it's there, it's well hidden: searching for the words API/JavaDoc/KDoc yields no interesting links [on the main Wiki page](https://github.com/edvin/tornadofx/wiki/Documentation) or in the README or in the Guide.

**Comment by TheJhonny007** [comment]
There is no JavaDoc/KDoc yet. You have to look in the Guide or the Wiki.

**Comment by edvin** [comment]
@Valloric Not much of the actual code is documented yet, but luckily, not all parts even need documentation. Most of them builders for example, follow the same pattern. Once you've had a look at the sources, most of it will be pretty easy to read.

A great help however, is to have the source code available in IDEA, and to step into the functions to peek around when needed. If you find functions that are not immediately clear, please add issues with "missing documentation for method x" and we'll get right on that :)

Once we have a little more documentation in the sources, we could publish it. Right now it would just look silly I'm afraid :)

**Comment by edvin** [comment]
KDocs are now published daily to https://tornadofx.io/dokka/tornadofx/tornadofx/index.html :)

**Comment by Valloric** [comment]
This is great, thank you!

**Comment by edvin** [comment]
Sorry for the delay, and thanks again for bringing this up :)
