### ISSUE TITLE
SmartResize greatly reduces the performance and causes freezing

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [edvin/tornadofx#411]
I'm using a `TableView` which has 8 columns, and has `SmartResize` policy set. The table's `items` collection is constantly set with new collections of 20+ items. Each time the `items` is set, the application freezes for a little longer, until, eventually, it freezes completely. The CPU gets completely utilized, and that's what causes the freeze (not the memory usage). It would probably be hard to reproduce this on more capable CPUs, but the issue is still there on weaker CPUs.

I've reproduced this behavior with both real-life usage (having a property of a ViewModel bound as `items`), and artificial usage (creating a 40-item list, and then assigning it to `items`).

With `SmartResize` enabled, CPU utilization would spike to 100% every time the `items` is set, but when disabled, the spikes are barely noticeable.

In these cases, when the table's items are being frequently replaced, should `SmartResize.POLICY.requestResize` be used instead of setting the policy directly?

**Comment by edvin** [comment]
I'm aware that SmartResize is heavy for older machines, but unfortunately the current approach is bound to be a little heavy. I'd have to get plugged in deeper into the toolkit to get significantly better performance. That's possible, but not in any near time frame. There might be things we can do to cache or skip calculations in the current form as well, but unfortunately I won't have time to look at this for a few months at the earliest.

**Comment by edvin** [comment]
This has finally been resolved :)
