### ISSUE TITLE
css class is not applied

### ISSUE THREAD

**Issue by vertexpipeline** [edvin/tornadofx#416]
I following tutorial about type-save markup, but i can'not apply markup to class. 
[App](https://github.com/vertexpipeline/AllStorage_Client/blob/master/src/main/kotlin/com/vertexpipeline/allstorage/client/kotlin/app/ClientApp.kt)
[Stylesheet](https://github.com/vertexpipeline/AllStorage_Client/blob/master/src/main/kotlin/com/vertexpipeline/allstorage/client/kotlin/stylesheet/StorageExplorerStylesheet.kt)
[View](https://github.com/vertexpipeline/AllStorage_Client/blob/master/src/main/kotlin/com/vertexpipeline/allstorage/client/kotlin/view/StorageExplorerView.kt)
How can i solve it?

**Comment by t-boom** [comment]
You are creating your app with the `AppView` view and `Styles` style sheet, but the view you linked here is `StorageExplorerView` and the style sheet is `StorageExplorerStylesheet`.

If you change your app to this it should work:
```kotlin
class ClientApp : App(StorageExplorerView::class, StorageExplorerStylesheet::class){
    init {
        reloadStylesheetsOnFocus()
    }
}
```

**Comment by vertexpipeline** [comment]
Thanks, But where was it written in book?

**Comment by vertexpipeline** [comment]
Oh. I see this change in example. But it needs to be accented more.

**Comment by t-boom** [comment]
It says [right in the guide](https://edvin.gitbooks.io/tornadofx-guide/content/3.%20Components.html)

> But first, extend App to create your own implementation and **specify the primary view as the first constructor argument**.

_emphasis added_

**Comment by vertexpipeline** [comment]
No. i said about [this page](https://edvin.gitbooks.io/tornadofx-guide/content/6.%20CSS.html)
>First, load the MyStyle stylesheet into your application.
But nowhere was said that i must add Style::class into constructor

**Comment by t-boom** [comment]
It shows it in the box directly below
> First, load the MyStyle stylesheet into your application.
> ```kotlin
> class MyApp: App(MyView::class, MyStyle::class) {
>     init {
>         reloadStylesheetsOnFocus()
>     }
> }

**Comment by vertexpipeline** [comment]
no. you don't get. Everyone understand, that you must include only `reloadStylesheetsOnFocus()`, but not `MyStyle::class`

**Comment by vertexpipeline** [comment]
i'am too

**Comment by t-boom** [comment]
You are right, I don't get it. I'm still confused on what was unclear (which is ironic when you think about it).

> Everyone understand, that you must include only `reloadStylesheetsOnFocus()`, but not `MyStyle::class`

Can you elaborate on that statement? I'm not sure what you're saying. You don't need to include `reloadStylesheetsOnFocus`. It's just useful for debugging, and what part isn't clear that you must include `MyStyle::class` to get the styles to work?

Sorry if I'm missing something obvious. Maybe someone else can weigh in.

**Comment by vertexpipeline** [comment]
I've written change in guide repository. Thanks
