### ISSUE TITLE
RealWorld Frontend

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#417]
_Not really an issue, but I thought I'd create one to keep track of this if anyone gets time to implement it._

Ilya Ryzhenkov (@orangy) posted an interesting idea. He's making the backend for the [RealWorld example app][realworld] in [Ktor][ktor], and was wondering if anyone wanted to make a frontend for it in TornadoFX. It could be a fun project, as well as a way to show off.

Useful links:
- [GitHub project][realworld-github]
- [Frontend instructions][frontend]
- [API][api]
- [Demo][demo]

[realworld]: https://realworld.io/
[ktor]: http://ktor.io/
[realworld-github]: https://github.com/gothinkster/realworld
[frontend]:https://github.com/gothinkster/realworld-starter-kit/blob/master/FRONTEND_INSTRUCTIONS.md
[api]: https://github.com/gothinkster/realworld/tree/master/api
[demo]: http://gothinkster.github.io/conduit/index.html

**Comment by gbui** [comment]
Hello, I started working on a frontend in TornadoFX, and this is what I have so far:
![Screenshot](https://user-images.githubusercontent.com/28683068/29746566-28ac8364-8a93-11e7-8ae6-15039543ea7c.png)
I put the code in [this gist](https://gist.github.com/gbui/943a579b4614f376c6f1e0214207fece), and it would be great if anyone could give some feedback. I'm not too experienced with TornadoFX, and I'm wondering if I can do anything better.

**Comment by edvin** [comment]
@gbui I looked at your code and it looks very clean. I can't think of much to improve, you've really nailed it IMO :) The only thing I could think of is that if you want to avoid the `lateinit var` for `pageView` you could have fired an event instead of calling `openPage`, and handle the replacement inside of the PageView vbox. It wouldn't add much clarity though, your code is perfectly fine as it is. Good job!

About `rem` - I'll defer to our resident CSS hero, @t-boom :)

**Comment by t-boom** [comment]
`rem` isn't a valid `LinearUnit`. The `Dimension.LinearUnit` is a class I created to handle JavaFX's `<length>` values. As you can see in [the official JavaFX CSS reference](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html#typelength), the only valid units are `px`, `mm`, `cm`, `in`, `pt`, `pc`, `em`, `ex`, and percentages.

**Comment by gbui** [comment]
@edvin Thanks, I actually thought my code was a bit messy, haha.

@t-boom Ah, okay, I wasn't sure if `rem` was a valid unit in JavaFX.

**Comment by ronsmits** [comment]
The gist looks really clean, well done. I do notice (and this is not your thing that I notice it) that the addClass calls feel like boilerplate @edvin would it be possible to do a ```label("title", class1, class2)``` construct?

**Comment by ronsmits** [comment]
The gist looks really clean, well done. I do notice (and this is not your thing that I notice it) that the addClass calls feel like boilerplate @edvin would it be possible to do a ```label("title", class1, class2)``` construct?

**Comment by gbui** [comment]
@ronsmits Thanks; I'm not sure if you can still say that about the code I have now 😅  And yes, the addClass calls feel like boilerplate, but it doesn't bother me much.

Also for anyone who's interested, here's what I have now:
![Screenshot](https://user-images.githubusercontent.com/28683068/29999950-7141dec2-900f-11e7-8993-d2b33a7c9b30.png)

**Comment by edvin** [comment]
Your UI is coming along nicely! If you complete or get further to completion before JavaOne, perhaps I could include a screenshot in my talk?

Unfortunately we can't add CssRule varargs parameter to label without breaking backwards compatibility, at least not in a meaningful way, so I think we'll have to live with writing addClass for now :)

**Comment by gbui** [comment]
Thank you! I would be honored to have this included in your talk, although I'm not what would count as "further to completion." (I'll still try to get as much done as possible though!)

As for writing addClass, I can live with that.

**Comment by edvin** [comment]
@gbui Great! Ping me once you feel you're done and I'll include it. @thomasnield We could even use this in your demo section if you want :)

**Comment by gbui** [comment]
Hello, sorry for replying so late; I hadn't been working on this as much as I would have liked to. I don't expect this to be squeezed into your talk, but I'll still give an update on my progress so far.

* Updated the UI to look more like https://demo.productionready.io
* Added an API controller that interacts with https://conduit.productionready.io/api/ and gets articles and tags to be shown on the Home page (I spent more time on this than I should have... On the bright side it will be much easier to implement functionality)

Here are some screenshots:

![Home Screenshot](https://user-images.githubusercontent.com/28683068/31053900-bbbf3280-a65b-11e7-9fdc-c4734465b888.png) | ![Sign In Screenshot](https://user-images.githubusercontent.com/28683068/31053901-bbc50c82-a65b-11e7-98c7-4a096a2ee06b.png)
:---:|:---:
![Sign Up Screenshot](https://user-images.githubusercontent.com/28683068/31053902-bbccbf2c-a65b-11e7-8233-b167d7f7f6b4.png) |
