### ISSUE TITLE
Get updated value from parameter

### ISSUE THREAD

**Issue by allnex** [edvin/tornadofx#418]
I have a pane that depending the button the user clicks, it replaces its children with some fragment or other. Using `find()` I pass a `ComboBox<String>` as a parameter, but when updating the selected item of the ComboBox, it doesn't update the value in the fragment.

Replacing the content:

```kotlin
container.replaceChildren(find(Cards::class, mapOf("list" to list)))
```

I tried to use this code in the fragment class:

```kotlin
private val list: ComboBox<String> by param()
private val selected = list.selectedItem!!
```

```kotlin
private val list: ComboBox<String> by param()
private val selected = list.selectionModelProperty().value.selectedItem
```

but the value is always the selected item when changing the content.

How can I get the current selected item of the ComboBox?

Thanks.

**Comment by edvin** [comment]
In theory this should work, as long as `Cards` is a `Fragment` and not a `View`, but it's a brittle and not very elegant solution.

I recommend using injected ViewModels instead, and even binding the selected item of the ComboBox to a property in the ViewModel. Exactly how to go about that would depend on your existing code and your use case.

I suggest familiarizing yourself with the ViewModel by reading the guide. If you want to post a small but complete sample that showcases the problem you're facing now, I could suggest the quickest solution, even without using best practices :)
