### ISSUE TITLE
TableView Builder- function-driven columns?

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#42]
Hey a piece of my code broke with the 1.3.2 release. Do we still support creating columns off functions? How would I do this now?

```kotlin
categories.subscribe { cat->
     column<ValuedTextFlow>(cat) { it.value.sumForCategory(cat) }
}
```

**Comment by thomasnield** [comment]
Found out what I had to do. A lot of the implicit generic functionality vanished. 

```kotlin
categories.subscribe { cat->
     column<ValuedTextFlow>(cat) { cdf: CellDataFeatures<Category,Int> -> cdf.value.sumForCategory(cat) }
}
```

**Comment by edvin** [comment]
Yes, we do, but since @picoworm removed the `FXTableView` class, you now have to supply both type parameters to the column function if you do "adhoc" binding like this. See no way to work around it in the Kotlin type system. Try `column<TableItemType, ColumnItemType>` - does that resolve it?

**Comment by thomasnield** [comment]
Yep, that works too. I think I can live with specifying the types for these extreme cases I don't run into that often Thanks!

**Comment by edvin** [comment]
Yeah, I figured that's the best option as well. I'll try to mention this in the docs atleast :)

**Comment by picoworm** [comment]
Please try to change generic parameter type to notnull and test it. It works for me

See changes at
https://github.com/picoworm/tornadofx/commit/8b47f1b160776a96a93075f10d0820751fc4e715

**Comment by picoworm** [comment]
try this way

categories.subscribe { cat->
     column(cat) { it.value.sumForCategory(cat) }
}

**Comment by thomasnield** [comment]
Yeah it does not work that way. It cannot infer the `it`. That's not a big deal though. I rarely have to dynamically create columns using parameterized functions.

**Comment by thomasnield** [comment]
Okay I'll try it later...
