### ISSUE TITLE
Error when using properties

### ISSUE THREAD

**Issue by matthjes** [edvin/tornadofx#421]
Hi,

I'm trying to understand how `ViewModel` is used in tornadofx by reading chapter 11 of the gitbook. Right at the beginning there is this code snippet:

    val nameProperty = SimpleStringProperty(this, "name", name)
    var name by nameProperty

This does not compile in my code, I get the following error:

    Property delegate must have a 'getValue(Model, KProperty*>)' method. None of the following functions is suitable.
        getValue() defined in javafx.beans.property.SimpleStringProperty
    Property delegate must have a 'setValue(Model, KProperty*>, [ERROR : Type from delegate])' method. None of the following functions is suitable.
        setValue(String!) defined in javafx.beans.property.SimpleStringProperty

Am I missing something here?

**Comment by alvr** [comment]
Maybe the guide is outdated, but for me, using this works:

```kotlin
val nameProperty = SimpleStringProperty(this, "name", name)
var name by property(nameProperty)
```

**Comment by matthjes** [comment]
Thank you, it's working now. Seems like the gitbook is outdated. 

FYI: [Here](https://edvin.gitbooks.io/tornadofx-guide/content/11.%20Editing%20Models%20and%20Validation.html) is the chapter (sub-chapter: "A typical use case").

**Comment by edvin** [comment]
The guide is not outdated, the syntax from the guide should be used. The reason for the compile error is that you're missing two imports, namely `tornadofx.getValue` and `tornadofx.setValue`.  It's a good idea to import `tornadofx.*`  in every file to avoid confusion.

I'll make sure to mention this in the guide if it's not there already :)

**Comment by edvin** [comment]
The guide has been updated with a specific mention of the import.

**Comment by matthjes** [comment]
Ok, now it's working with the original code :)

It wasn't clear that I need to import `tornadofx.*` in my model class, so mentioning this or extending the code example would be helpful.

The import is listed in the second code block in "A typical use case", but as I'm using separated classes it wasn't clear to me.

**Comment by edvin** [comment]
There is a specific note about it now :)
