### ISSUE TITLE
JFXBadge style class not loaded

### ISSUE THREAD

**Issue by zellus** [edvin/tornadofx#422]
I attempted to use JFXBadge from JFoenix in a TornadoFX project. The JFoenix demo by itself does run fine with the expected styling. After porting the 'Icons' demo to the TornadoFX project, the JFXBadge does not show any trait of the JFoenix styling. 
My impression is that 
` badgePane.getStyleClass().add("badge-pane");`
in JFXBadge.java is completely ignored. Is this the intended behaviour?

**Comment by edvin** [comment]
TornadoFX doesn't mess with applied styles, so there must be something else going on here. Can you post a minimal sample project showcasing the issue?

**Comment by zellus** [comment]
Is the following fxml and class sufficient or shall I provide a gradle project? 

`import com.jfoenix.controls.JFXBadge
import javafx.scene.input.MouseButton
import javafx.scene.layout.StackPane
import tornadofx.*


class Icons : View("IconsView") {

    override val root: StackPane by fxml()

    val badge1: JFXBadge by fxid("badge1")

    init {
        badge1.setOnMouseClicked { click ->
            var value = Integer.parseInt(badge1.text)
            if (click.button == MouseButton.PRIMARY) {
                value++
            }
            badge1.text = value.toString()
        }
    }
}`

`<?xml version="1.0" encoding="UTF-8"?>

<?import com.jfoenix.controls.*?>
<?import com.jfoenix.transitions.hamburger.HamburgerBackArrowBasicTransition?>
<?import com.jfoenix.transitions.hamburger.HamburgerBasicCloseTransition?>
<?import com.jfoenix.transitions.hamburger.HamburgerNextArrowBasicTransition?>
<?import com.jfoenix.transitions.hamburger.HamburgerSlideCloseTransition?>
<?import de.jensd.fx.glyphs.fontawesome.FontAwesomeIconView?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.layout.*?>
<?import javafx.scene.layout.StackPane?>
<StackPane fx:id="root" xmlns:fx="http://javafx.com/fxml/1"
           xmlns="http://javafx.com/javafx/null">
    <VBox maxWidth="400" maxHeight="400">

        <Label styleClass="title-label">Badge Icons</Label>
        <HBox spacing="20" style="-fx-padding: 0 0 0 50;">
            <children>
                <JFXBadge fx:id="badge1" position="TOP_RIGHT" text="1"
                          styleClass="icons-badge">
                    <StackPane style="-fx-padding: 10;">
                        <FontAwesomeIconView glyphName="STAR" size="2em"
                                             styleClass="icon"/>
                    </StackPane>
                </JFXBadge>
            </children>
        </HBox>
    </VBox>
</StackPane>`

**Comment by edvin** [comment]
Please provide a Gradle project. Can you also confirm that this exact FXML loaded in a vanilla JavaFX application works?

**Comment by edvin** [comment]
Great, thanks for reporting back :)
