### ISSUE TITLE
No builder for tab

### ISSUE THREAD

**Issue by ppareit** [edvin/tornadofx#426]
In my code I have
`var tabs: TabPane by singleAssign()`
Assume it is correctly initialized.
Now I can do
`tabs.add(textarea { ... })`
But I would expect a builder for Tab to work like this:
```kotlin
tabs += tab {
  text = "Tab title"
  content = textarea { ... }
}
```
What would be the idiomatic way to write the above in tornadofx?

**Comment by edvin** [comment]
First of all, builders never require you to add them to their parent manually, the `tabs +=` is done automatically :)

This is the way to create tabs with adhoc content:

```kotlin
tab {
    textarea()
}
```

However, if your tab has a lot of content and functionality, consider creating a View or Fragment for it instead. Then the title will also be pulled from the uicomponent directly:

```kotlin
tab(MyTabView::class)
```

I also question the need to save a reference to the TabPane itself in a variable, that's seldom needed in my experience. Try to use events to react to tab changes, or bind functionality to observable values if needed.

**Comment by ppareit** [comment]
Good points.
Though, I'm working on a simple document interface application. I need to add a tab to a tabpane whenever a menu (New) is called. You probably mean that I should have a model in which there is an observable list that lists all open documents?

**Comment by edvin** [comment]
It sounds like what you want is to define a Subscriber to an event inside of the TabPane builder:

```kotlin
class NewDocumentEvent(val doc: Document) : FXEvent()

class TabPaneTest : View("TabPane Test") {
    override val root = tabpane {
        // One tab added by default
        tab("Some tab") {
            textarea("Some text")
        }

        // Add tabs on demand when NewDocumentEvent is emitted
        subscribe<NewDocumentEvent> { event -> 
            tab("New doc") {
                textarea(event.doc.someProperty)
            }
        }        
    }
}
```
Are more robust strategy would be to create a View for the document editor that is to become the tab, and create a new scope for the View where you insert new the Document. Then you'd do `tab(documentEditor)` to add the tab for the new document. DocumentEditor would be the View that you `find` in the new Scope you create.

**Comment by ppareit** [comment]
That is a clean solution, and in my menu action I write
```kotlin
action { fire(NewDocumentEvent("foo")) }
```

**Comment by edvin** [comment]
That sounds good to me :))
