### ISSUE TITLE
onUndock not called

### ISSUE THREAD

**Issue by ppareit** [edvin/tornadofx#427]
In the following case, onUndock is not called:

```kotlin
import tornadofx.*

class TestView : View() {
    override val root = label("                ")

    override fun onDock() {
        println("onDock called")
    }

    override fun onUndock() {
        println("onUndock called")
    }
}
```
Assume the TestView is the main window of the application. I want thus to detect when the window is closed. This for instance to save the size of the window as a preference.

**Comment by edvin** [comment]
Even when a Window is closed, the View is not disconnected from it's parent. I see that there is room for confusion here and that it really wouldn't be far fetched to assume that onUndock was called when a Window is closed.

I've added a callback for the View currently docked in the primary stage, so your code above should now also output "onUndock called".

I'll look into doing the same for other Windows when they are closed.

**Comment by edvin** [comment]
OK, I've committed a fix that makes sure onUndock is called on the current scene root when Windows are closed.
