### ISSUE TITLE
Hot reload limited to main module

### ISSUE THREAD

**Issue by jeremee** [edvin/tornadofx#428]
Of course "hot reload" feature works like a charm when the application files are located in the gradle main module.
But it does not seem to work inside a module while it prints `tornadofx.FX$Companion replaceComponent` & `Reloaded [Scene] MyView@447dbf4e`.

It would be very nice to reload any application even in a "complex" structure.

Related to the closed issue: https://github.com/edvin/tornadofx/issues/267

**Comment by edvin** [comment]
I think this is due to IDEA not replacing those files correctly. I don't think there is anything we can do in the plugin to alleviate this, but I'm sure we'll be able to figure it out. Could you set up a project that illustrates the issue so it's easier to investigate?

**Comment by jeremee** [comment]
It is clearly due to an IDEA behavior, the problem was that sometimes I get a message like: `MyAppName: 0 classes reloaded`in the event log.

After a lot of tests I understood the "logic": after stepping during a debug session, the classes reload mechanism will not see my code updates.

So it's all ok on tornadofx side, I close the issue.
thanks!

**Comment by edvin** [comment]
Thanks for the update :)
