### ISSUE TITLE
Easy access to application resources

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#44]
Lot's of JavaFX API's takes resources as an `URL` or the `toExternalForm` of an URL. To retrieve a resource url one would typically write something like:

```kotlin
val myAudioClip = AudioClip(MyView::class.java.getResource("/sounds/mysound.wav").toExternalForm())
```

I propose adding a `resources` object to `Component` which can retrieve the external form url of a resource like this:

```kotlin
val myAudiClip = AudioClip(resources["/sounds/mysound.wav"])
```

If you need an actual `URL` it can be retrieved like this:

```kotlin
val myResourceURL = resources.url("/sounds/mysound.wav")
```

Resources are relative to the `Component` so access to a resource in the same package as the component would simply be `resources["mysound.wav"]`.

**Comment by edvin** [comment]
Implemented. Documentation [here](https://github.com/edvin/tornadofx/wiki/Resources).

**Comment by thomasnield** [comment]
I like it. I've written similar utilities in Java before so glad it is here.
