### ISSUE TITLE
Need a mechanism to refresh views between automated tests

### ISSUE THREAD

**Issue by lunivore** [edvin/tornadofx#441]
Because there's only one instance of a view, it makes it very hard to run automated tests against a TornadoFX app. (I'm using Cucumber-JVM with JUnit.)

Re-running the same app twice results in a "this panel has already been added as root" exception (the workaround I found being to replace the root in the window before closing it).

Worse, even if I do restart a completely fresh edition of the app, the view is still populated by the previous test's data.

I'm adding a feature to clear down my app, which I can use between tests, but I shouldn't have to. Please can we have a way to make views not be singletons, or at least to get a new instance in a new copy of the app? Thanks!

(I'll attach the link to my code as soon as it's ready.)

**Comment by edvin** [comment]
There is already a way to deal with this, it's called `Scope` :)

https://github.com/edvin/tornadofx-guide/blob/master/14.%20Scopes.md

Does this work for you?

**Comment by lunivore** [comment]
Ah! That looks as if it might.  Thanks! Will give it a try and report back.

**Comment by edvin** [comment]
Great! We should include information about this with regards to testing in the Guide, so if you want to post some code once you have it working, I could include it as an example :)

**Comment by lunivore** [comment]
That worked, superb! I'm not sure how you'd do it through the traditional launching mechanism / the one that's in your guide, though. I have an automation tool that initializes the platform and launches apps for me, so it was easy to add the scope to my app:
```

val myApp = MyApp()
myApp.scope = Scope()
```

Then all you have to do is start it with a new stage. That did the trick.

If it's OK with you, I'd like to leave this open until this is added to the guide.  It could just be a small sentence where you talk about creating the app, e.g.: "If you need more than one instance, see 'Scope'". I was able to work it out from the page you linked.

**Comment by edvin** [comment]
Great to hear! OK, we'll leave this open until I or someone else add it :)

**Comment by edvin** [comment]
I've added information about testing with Scopes to the bottom of the Scopes chapter in the guide :)
