### ISSUE TITLE
CollectionPropertyDelegates

### ISSUE THREAD

**Issue by TheJhonny007** [edvin/tornadofx#446]
I stumbled upon a problem which may be solved by delegates. I have a JPA entity class

```kotlin
@Entity
class JPAObservableMapClass(initialMap: MutableMap<String, String> = mutableMapOf()) {
	@get:ElementCollection
	var map: MutableMap<String, String> = initialMap

	@get:Transient
	val obervableMap: ObservableMap<String, String> = FXCollections.observableMap(map)
}
```

In my case Hibernate initializes the `map` field and my `observableMap` loses its reference to the `map` field, because Hibernate reinitializes the `map` field with a new Instance every time the `map` is updated by Hibernate.

I am not familiar with delegates, so I ask: Is it possible to solve the problem with delegates? So every time Hibernate updates my `map` my observers of `observableMap` get notified? Maybe it can be solved with `MapProperty` instead of `ObservableMap`?

The same problem exists for `Set` and `List` aswell.

**Comment by edvin** [comment]
If the setter for `map` is called, you'd need to change the observableMap instance as well, right? If you just want to create a new observableMap when someone accessed `observableMap, just do:

```kotlin
val obervableMap: ObservableMap<String, String> get() = FXCollections.observableMap(map)
```

But if you need to keep the same instance of ObservableMap, but it should suddenly observe another map, you'd need to create a custom ObservableMap, and also override the setter for `var map`.

**Comment by TheJhonny007** [comment]
I thought there may be a way to create delegates for observable collections like for normal properies:

```kotlin
@Entity
class JPAObservableMapClass(initialMap: MutableMap<String, String> = mutableMapOf()) {

	@get:Transient
	val obervableMap: ObservableMap<String, String> = FXCollections.observableMap(initialMap)

	@get:ElementCollection
	var map: MutableMap<String, String> by observableMap
}
```

I think if that is possible it could be a generally good addition for interaction with APIs which don't support observable collections.

**Comment by edvin** [comment]
Ah, now I think I understand :)

Try adding this code to the same file and see if your code above compiles:

```kotlin
operator fun <K, V> MapProperty<K, V>.getValue(thisRef: Any, property: KProperty<*>) = value
operator fun <K, V> MapProperty<K, V>.setValue(thisRef: Any, property: KProperty<*>, value: ObservableMap<K, V>?) = setValue(value)
```

If this is what you want, I can add it to the framework.

**Comment by edvin** [comment]
I think this isn't doable due to type erasure. Will give it a couple of more shots later today.

**Comment by TheJhonny007** [comment]
I myself will look into it. Put earliest at sunday. Maybe I can find a way.

**Comment by TheJhonny007** [comment]
#454

**Comment by edvin** [comment]
I ran into some problems and had to uncomment them for now. Will look at it more closely as soon as I have time.

**Comment by TheJhonny007** [comment]
That is werid it seems to work flawless for me.

**Comment by edvin** [comment]
You're right, it was something else in my code. I've reinstated them now :)

**Comment by philipbjorge** [comment]
@edvin -- They are still commented out?
https://github.com/edvin/tornadofx/commit/190c3fef66a3e1627130e561564299e39438b57c

**Comment by edvin** [comment]
They continue to create issues, I'll comment them back in locally and see if I can pinpoint the issue this time. Sorry about this.

**Comment by edvin** [comment]
One issue I see right away is that it opens up the possibility of NPEs, and also makes it impossible to check if a delegated var for a List property is null. However, this is more in line with the rest of the property delegates, so it might make sense. Trying to determine how much problems it will cause with backwards compatibility.

**Comment by edvin** [comment]
Consider this test:

```kotlin
    class TestClass {
        val myListProperty = SimpleListProperty<String>()
        var myList by myListProperty
    }
```

You might test to see if the list is empty like this:

```kotlin
val test = TestClass()
assertTrue(test.myList.isEmpty())
```

This will fail with:

java.lang.IllegalStateException: value must not be null
	at tornadofx.PropertiesKt.getValue(Properties.kt:206)

**Comment by edvin** [comment]
That's the only issue I can find now, and I think it's worth aligning these with the rest of the delegates. Hereby committed :)

**Comment by TheJhonny007** [comment]
I may have a better way of dealing with this special case of Collection properties. But it may be overkill.
For my own project I started implementing [this](https://github.com/TheJhonny007/tornadofx/tree/master/src/main/java/tornadofx/observablecollections/list) which implements `ObservableList` and `ListProperty` in a way, that you can retrieve the observable list as well as the backing list (which is not possible with the standart implementation). This would more closely copy the behaviour of other properties, where `set(value)` would be of the same type as `get() : value`

So in the example of Hibernate it could look like this:

```kotlin
    @Entity
    class HibernateClass {
        @get:Transient
        val personListProperty = SimpleBasicListProperty<String>()

        @get:ElementCollection
        val personList by personListProperty
    }

    @Test 
    fun listTypeCheck() {
        val listHolder = HibernateClass()
        listHolder.list = PersistentBag()
        assert(listHolder.list is PersistentBag)
    }
```

This would allow interop with all libraries, which require a certain collection to be returned like Hibernate, Jackson etc.

The only downside is that if the collection gets modified via the field access there would be no notification. Example:

```kotlin
    class ListHolder {
        val listProperty: BasicListProperty<String> = SimpleBasicListProperty<String>()
        var list: MutableList<String> by listProperty
    }

    fun test() {
        val listHolder = ListHolder()
        listHolder.list = mutableListOf()
        
        listHolder.listProperty.onChange { println("Change") }
        listHolder.list.add("Test") // no ChangeEvent will fire
        listHolder.listProperty.invalidate() // event must be manually fired
    }
```

Because of this behaviour all operations should be performed on the property if possible and only if the backing field is really needed the field should be accessed.

I only implemented List completely so far, because I didn't need the others yet, but if Edvin thinks this would be a good fit for TornadoFX for interop with other libraries I could implement Set and Map as well.
