### ISSUE TITLE
Style the root accent color with type-safe CSS

### ISSUE THREAD

**Issue by carltonwhitehead** [edvin/tornadofx#448]
I'd like to adjust the accent color defined by modena.css using type-safe CSS builder. It seems there was a [prior decision](https://github.com/edvin/tornadofx/issues/197#issuecomment-269014914) to defer that until it was requested.

```kotlin
class CustomView : View("Accent Override") {
  override val root = HBox()
  init {
    with (root) {
      style {
        accentColor = Color.RED
      }
    }
  }
}
```

**Comment by carltonwhitehead** [comment]
It looks like it would be a one line change near https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/CSS.kt#L557

Is there anything else to it?

Can I send you a PR?

**Comment by carltonwhitehead** [comment]
In the mean time, I found `unsafe(key: String, value: Any)` and I was able to accomplish what I wanted with it, despite feeling unclean.

**Comment by edvin** [comment]
Please send the PR, hopefully Matthew will verify it when he finds time :)
