### ISSUE TITLE
Extending tornadofx.View or tornadofx.Component.View

### ISSUE THREAD

**Issue by glhf** [edvin/tornadofx#45]
Can't understand issue because my view class extend abstract View thas located in Component.kt
But on compile get the message below:
> Kotlin: Type of 'primaryView' is not a subtype of the overridden property 'public abstract val primaryView: kotlin.reflect.KClass<out tornadofx.View> defined in tornadofx.App'

Maybe somethig wrong with artifacts that gradle get for me from MavenCentral and something are not 'up-to-date' 
(versions compile 'no.tornado:tornadofx:1.3.2'  'no.tornado:tornadofx-controls:1.0'  'no.tornado:fxlauncher:1.0.6')

**Comment by edvin** [comment]
Hi! The correct import is `tornadofx.View`. `Component.kt` only defines the `tornadofx` package.

Make sure your rootView declaration looks like this:

```kotlin
override val primaryView = YourView::class
```

Did you base this off the `tornadofx-samples` project? I just found that is was heavily outdated, so I just commited changes for TornadoFX v1.3.2.

I'm not sure what's causing your issue but I would very much like to find out. Would it be possible for you to upload the project so I can take a look? If you don't want to post it public, you can email me at es@syse.no if you like. I'll get right back to you!

Alternatively you could also try the new quickstart archetype and see how that goes:

```bash
mvn archetype:generate -DarchetypeGroupId=no.tornado \
  -DarchetypeArtifactId=tornadofx-quickstart-archetype \
  -DarchetypeVersion=1.0.1
```

**Comment by glhf** [comment]
https://github.com/glhf/messager/blob/kotlin-master/src/main/kotlin/com/glhf/messager/vk/EntryPoint.kt

**Comment by glhf** [comment]
Unfortunately can't use quick start archetype because I'm try provide migration from JavaFx (with Afterburner fx framework) to kotlin with tornadofx. But yes I'm based my aptemps on the tornadofx-samples

**Comment by edvin** [comment]
Ah :) Just change `:` to `=`:

Instead of:

```kotlin
override val primaryView: Main::class
```

The correct syntax is:

```kotlin
override val primaryView = Main::class
```

**Comment by glhf** [comment]
my fail! Tnx for your reply and your time!

**Comment by edvin** [comment]
No problem. PS: Your `main.fxml` needs to be moved from `resources/main.fxml` to `resources/com/glhf/messager/vk/Main.fxml` to be picked up by the `fxml()` delegate :)
