### ISSUE TITLE
How to create splash screen using tornadofx?

### ISSUE THREAD

**Issue by anidotnet** [edvin/tornadofx#455]
Can someone point me to one example of how to display a splash screen using tornadofx before loading the main view?

**Comment by t-boom** [comment]
Would you mind asking this question on [StackOverflow](https://stackoverflow.com/questions/ask?tags=tornadofx)? It's a better platform for Q&A, and is more discoverable for others that may have this question later.

**Comment by anidotnet** [comment]
Honestly these days I don't favour SO anymore.

**Comment by anidotnet** [comment]
[Here](https://stackoverflow.com/questions/46187319/how-to-create-splash-screen-in-tornadofx) is the question on SO.

**Comment by edvin** [comment]
I've answered the SO question :)
