### ISSUE TITLE
Builders functions "Unresolved refference" 

### ISSUE THREAD

**Issue by JNordik** [edvin/tornadofx#46]
Hi.
I can not run the code from this [example](https://github.com/edvin/tornadofx/wiki/Type-Safe-Builders#a-vbox-containing-two-hbox-components).
Error is **"Unresolved refference"** for hbox, label and textfield.
![error](https://cloud.githubusercontent.com/assets/17687748/13655994/63634c6e-e674-11e5-9da9-2bf743e7f588.png)

**Comment by thomasnield** [comment]
How exactly are you setting up the dependency?

**Comment by JNordik** [comment]
Via maven archetype.
[https://github.com/edvin/tornadofx#generate-a-quickstart-application-with-maven](https://github.com/edvin/tornadofx#generate-a-quickstart-application-with-maven)

**Comment by edvin** [comment]
It looks like IDEA won't help you resolve the imports for the builders, so first try to add them manually. In fact, you can import `tornadofx.*` so that the whole thing looks exactly like this:

```kotlin
import javafx.geometry.Insets
import javafx.scene.layout.VBox
import tornadofx.*

class MyView : View() {

    override val root = VBox()

    init {
        with(root) {
            hbox {
                label("First Name") {
                    hboxConstraints { margin = Insets(5.0) }
                }
                textfield {
                    hboxConstraints { margin = Insets(5.0) }
                    useMaxWidth = true
                }
            }
            hbox {
                label("Last Name") {
                    hboxConstraints { margin = Insets(5.0) }
                }
                textfield {
                    hboxConstraints { margin = Insets(5.0) }
                    useMaxWidth = true
                }
            }
        }
    }
}
```

If IDEA is still complaining, please try to run this from the command line with `mvn jfx:run`. Make sure you're on the latest IDEA and that you have the latest kotlin plugin installed. There was some issues with a build of IDEA a while back where the kotlin plugin wouldn't update, so you had to update the whole IDE manually.

Please let me know what you find, OK?

**Comment by thomasnield** [comment]
Yeah I noticed that as well regarding the Kotlin plugin. Double-SHIFT, search for "plugins" screen, and update it there.

**Comment by edvin** [comment]
In the specific case I'm talking about, it was not actually possible to update the plugin from the IDE, you had to do a fresh install. This was some time prior to the Kotlin 1.0 release.

**Comment by JNordik** [comment]
I am using the latest version of the IDEA and Kotlin plugin.
Intellij 15.0.4
![1](https://cloud.githubusercontent.com/assets/17687748/13669245/3f403536-e6d3-11e5-9a20-10a9216f49ef.png)
Problem when im changing VBox on ToolBar.
![2](https://cloud.githubusercontent.com/assets/17687748/13669286/829acad0-e6d3-11e5-8abf-3bfbb843388c.png)

**Comment by edvin** [comment]
ToolBar doesn't extend `Pane`, so the builders don't apply to it directly. Wrap everything in `children {}` to work around this:

```kotlin
with(root) {
    children {
        hbox {
            ...
        }
    }
}
```

We'll look for a way to avoid this small niggle :)

**Comment by thomasnield** [comment]
Yeah we should add a builder for toolbar possibly.

**Comment by JNordik** [comment]
Ohh, thank you for your help. Its working :)

**Comment by edvin** [comment]
You're welcome :)
