### ISSUE TITLE
Something wrong with "columnResizePolicy = SmartResize.POLICY"

### ISSUE THREAD

**Issue by ChenShiyu2** [edvin/tornadofx#460]
I am doing  ["tornadofx-samples"](https://github.com/edvin/tornadofx-samples/tree/master/itemviewmodel/withFXproperties) exercise.

   After started the application, when I change the selection between the items in PersonList view, I found the application slowing down constantly. Then I close the window by click the window's close-button, the application is still running in the background with infinite warning
 **"javafx.scene.CssStyleHelper calculateValue 
warning: Could not resolve '-fx-table-cell-border-color' while resolving lookups for '-fx-border-color' from rule '*.table-cell' in stylesheet jar:file:/F:/Java/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss"** !!

  Then I delete the sentence "columnResizePolicy = SmartResize.POLICY" in the PersonEditor.kt file, everything goes well.

**Comment by edvin** [comment]
Thanks for reporting this. I can see the same thing. Will start working on this on Monday.

**Comment by edvin** [comment]
I found and fixed the bug now :) Will push a new snapshot to sonatype if you want to check it out right now.

**Comment by edvin** [comment]
I have released TornadoFX 1.7.11 with this fix :)

**Comment by ChenShiyu2** [comment]
Thanks for your working. ^^

**Comment by edvin** [comment]
My pleasure. Thanks for reporting, finally we got a real test case for the performance issue :) We've heard about issues with this before but never been able to reproduce :)
