### ISSUE TITLE
Referring to CSS property in another property causes chain of Exceptions that crashes the app

### ISSUE THREAD

**Issue by renatoathaydes** [edvin/tornadofx#477]
This CSS object:

```kotlin
class Styles : Stylesheet() {
    init {
        root {
            baseColor = Color.DARKSLATEGRAY
            prefWidth = 300.px
            prefHeight = 120.px
        }
        text {
            stroke = baseColor
        }
    }
}
```

Causes the app to not start up due to a large chain of Exceptions. I will not even post it as it's huge and probably won't help you, just run and see for yourself.

I get that using `baseColor` in that position may not work due to whatever implementation detail, but it does look to me like it should work, after all `baseColor` is set and then just used elsewhere later!

**Comment by ruckustboom** [comment]
Long story short, that won't work because `baseColor` isn't set for `text`. (I know that would work in CSS, but the type safe CSS DSL in TornadoFX isn't CSS, it generates CSS. There isn't really a clean way to do what you want in a type safe way.)

Luckily this is raw Kotlin code, so you can define your own variables and use them in your Styles.

```kotlin
class Styles : Stylesheet() {
    companion object {
        val themeColor = Color.DARKSLATEGRAY
    }
    init {
        root {
            baseColor = themeColor
            prefWidth = 300.px
            prefHeight = 120.px
        }
        text {
            stroke = themeColor
        }
    }
}
```

**Comment by ruckustboom** [comment]
If your goal is to reference `-fx-base`, you should look into the `unsafe` and `raw` CSS DSL commands, but I'd still just recommend defining your own variables.

**Comment by renatoathaydes** [comment]
I'm sorry but I think this is a bug in your CSS generator. There's no good reason why this shouldn't work.

**Comment by renatoathaydes** [comment]
I haven't looked at your code, but having implemented a number of DSLs myself, I would think this is trivial to implement.

Just make sure to run the closures eagerly, so that by the time the `root` method returns, `baseColor` is set and can be used in the next block.

I guess you mention mixins because you're doing some kind of magic that forbids eager evaluation of the closures?

**Comment by ruckustboom** [comment]
The problem with that approach is we can't know ahead of time what selectors will be influenced by other selectors, so we have to store the properties of each selector independently. Sure, we could add special handling for `root`, but it would be a lot of additional overhead, and wouldn't help in any other similar circumstance. The mixins aren't magic. Actually, under the assumption that we store each selector's properties separately, they are super simple. If we take away that assumption, they would not be.

Please feel free to look at the code and submit any suggestions.

**Comment by renatoathaydes** [comment]
Cool, I will have a look. This could definitely be improved.

**Comment by renatoathaydes** [comment]
Each time I open a block in a `Stylesheet` class, I create a `tornadofx.CssSelectionBlock`. Each one of these instances contains a property for every single possible CSS property because it extends `tornadofx.PropertyHolder`.

This design is quite wasteful and allows lots of things that make no sense to happen: for example, it's possible to set `baseColor` at any level?!

Do I understand it correctly?

What was the rationale behind doing things this way?

**Comment by ruckustboom** [comment]
That's what I was talking about above with storing each selector's properties separately. Among other things, it makes mixins easy. And yes, you can set `baseColor` at any level, even in JavaFX CSS. If you do, it will theme everything within that selection using that base color, while anything outside the selection will use the root base color. This leads to the issue I mentioned where we can't know ahead of time which selectors will be influenced by which other selectors.

I am no CSS expert, and I just designed the DSL in the way that made sense to me. If you can think of a better way, that would be awesome. We're always looking for ways to make TornadoFX better, and I promise not to get too offended with you harshing on my code 😆.

---

Just a heads up, there is a feature we've talked about previously that we want to add to the CSS DSL that we haven't gotten around to yet. Basically, we have this idea where there will be a base `Stylesheet` class that will define selectors and properties global to JavaFX. From that we could derive other stylesheets that would be specific to various base user agent stylesheets, such as a `ModenaStylesheet` that selectors and properties defined in `modena.css`, or `CaspianStylesheet` for 'caspian.css`. It would also make it really easy for library developers to include a root stylesheet that works with their custom stuff (such as if someone made a material design library, or for ControlsFX). Please keep that in mind when you're digging into this.

**Comment by ruckustboom** [comment]
Also, if you're thinking about contributing to TornadoFX (or even just using it), I would highly recommend joining the TornadoFX channel in the Kotlin slack. I'll send you an invite.

**Comment by renatoathaydes** [comment]
The problem with the design is having a field for each property when that is completely unnecessary. You only need a setter for most things (that doesn't take any memory, unlike fields). Because you probably will have hundreds of CSS rules, that's an important concern. Also, this will not break the mixin stuff as they don't seem to use fields, only a map, to store the properties.

Anyway, I fixed the worst problem, which was the infinite loop in the error handler.

Fixing the actual issue of not being able to refer to a property set earlier will be harder as it will involve changing the design.

**Comment by ruckustboom** [comment]
> You only need a setter for most things

I don't believe this is true. In your code snipped `stroke = baseColor`, you need a getter.

**Comment by renatoathaydes** [comment]
Hehe, I almost added "... and a getter for a few built-in selectors" :)

**Comment by ruckustboom** [comment]
Yeah. The problem is, `baseColor` isn't built in. It's defined in modena, and users can use any CSS for user agent stylesheet (modena is just the default). That's part of the reason we had the idea I mentioned about deriving stylesheets.

**Comment by ruckustboom** [comment]
@renatoathaydes Can this issue be closed? I don't think there is anything left to be solved beyond a full redesign / rewrite of the CSS DSL, but that's out of the scope of this issue.

**Comment by ruckustboom** [comment]
By the way, if you have ideas for a redesign, submit them and we can put a `v2` flag on them.

**Comment by renatoathaydes** [comment]
@ruckustboom sure, let's close it... unfortunately I never got the time to work on a re-design attempt. Hope you can keep things working well with the current design.
