### ISSUE TITLE
IDEA Plugin link broken

### ISSUE THREAD

**Issue by Torbilicious** [edvin/tornadofx#478]
The Link to the IDEA Plugin in the Documentation appears to be broken.

It points to 
https://edvin.gitbooks.io/tornadofx-guide/content/13.%20TornadoFX%20IDEA%20Plugin.html

but should point to
https://edvin.gitbooks.io/tornadofx-guide/content/part1/12.%20TornadoFX%20IDEA%20Plugin.html

**Comment by edvin** [comment]
Hi! What documentation are you referring to? Can you link to the page that contains the broken link?

We did a guide refactoring the other day, so I'm guessing the issue is in the guide perhaps?

**Comment by Torbilicious** [comment]
https://github.com/edvin/tornadofx/wiki/Documentation
at the bottom

**Comment by edvin** [comment]
Ah, thanks! I've remove the links and added a note at the top about discontinuing the Wiki in favor of the [guide](https://www.gitbook.com/book/edvin/tornadofx-guide/details).

**Comment by Torbilicious** [comment]
thanks!
