### ISSUE TITLE
Change `Rendered` to use a StringBuilder instead of returning a String

### ISSUE THREAD

**Issue by renatoathaydes** [edvin/tornadofx#481]
The implementation of CSS rendering is extremely inefficient.
It creates a lot of Strings separately, then merges them together by appending them one by one, then finally turns the result into a byte-array while at the same time holding on to the original String, causing not only a CPU bottleneck, but a memory bottleneck.

The best solution would be to build the CSS with a single StringBuilder by passing it into each `Renderable` (or whatever the more appropriate name for this interface would be).

CSS stylesheets can grow quite large and numerous for a professional application, and spending hundreds of milliseconds rendering it would make it impossible to use type-safe stylesheets for a snappy app.

**Comment by edvin** [comment]
Closing, as investigation showed that this didn't help and that the culprit was long instantiation time due to massive amount of delegate functions.

**Comment by renatoathaydes** [comment]
Agree that it didn't solve the problem because the bottleneck was elsewhere, but I think these changes will still make `Renderable` a lot faster... I hope to get some time to investigate this further sometime soon!

**Comment by edvin** [comment]
OK! Very happy that you're taking the time to look into this :)
