### ISSUE TITLE
An ItemViewModel doesn't commit the changes of a nullable field into the item

### ISSUE THREAD

**Issue by chinzen** [edvin/tornadofx#485]
That might be just a mistake of mine, yet still...

When I create an ItemViewModel like that:
```kotlin
class Entity {
    var field: String? = null
}

class EntityModel : ItemViewModel<Entity> {
    val field = bind(Entity::field)

    constructor(item: Entity) {
        this.item = item
    }
}
```

And then try to `commit()` the changes, for example:

```kotlin
val entityModel = EntityModel(item = Entity())
entityModel.field.value = "some value"
entityModel.commit()
assertTrue(entityModel.item.field == null)
```

I end up with a null.

While if I change the line `var field: String? = null` to `var field: String = ""` the `commit()` works perfectly fine.

If that behavior is expected, then I believe an exception on the binding `val field = bind(Entity::field)` would be quite useful.

I have created a [repository](https://github.com/chinzen/tornadofx-test) with a working example: [an app example](https://github.com/chinzen/tornadofx-test/blob/master/src/main/kotlin/app.kt) and the [test case from above](https://github.com/chinzen/tornadofx-test/blob/master/src/test/kotlin/EntityModelTest.kt).

**Comment by edvin** [comment]
I believe this was reported and fixed just a few days ago. Can you try with the latest snapshot at oss.sonatype.org?

**Comment by chinzen** [comment]
Sure.

But because there is no official instruction for gradle, I'm not sure I've done everything correctly. [My commit to the build.gradle](https://github.com/chinzen/tornadofx-test/commit/5b8ea234d7e254ff8eaac921bb7538aafdd2241d).

The problem does persist with that configuration.

**Comment by edvin** [comment]
Your Gradle config is correct. The fix was actually rolled back as it introduced more problems than it solved. If possible, use observable properties in your Entity for now, that's the use case the ViewModel was created for handling, although sopport for Pojo/Poko has been added to some degree.

Due to work with Java 9 conversion this has a pretty low priority now, at least for me, but we can leave the issue open so perhaps others can contribute. Sorry about that :)

**Comment by genobis** [comment]
@chinzen, @edvin

I believe I nailed it ;) long strony short, in that case bind invocation falls to KProperty instead of KMutableProperty, so it was just treated lik a read-only field, but without any obvious errors or compilation warnings.

Pull request #493

**Comment by edvin** [comment]
Oh wow, that's fantastic news! I will look this over and merge soon!

**Comment by genobis** [comment]
@edvin sure thing :)

The fastest way to find what's going on is to comment out that new `bind` variant from `ViewModel.kt` and then running `poko_commit()` test from `ViewModelTest.kt`. Note which `bind` variants are called from `PersonPokoModel` in the same file. Anyway, test should fail.

Then uncomment it and run the test again. This time it should succeed. Again, take note which `bind` variants are called this time.

Of course I could have missed something - let me know if I got it wrong, a review is always welcome :)

**Comment by edvin** [comment]
Merged :) Good job!
