### ISSUE TITLE
What is the best practice for creating customized UI component?

### ISSUE THREAD

**Issue by aceyin** [edvin/tornadofx#498]
Hi all, i am new to JavaFX and tornadofx, and now i need to create some highly customized UI components(including submit button, text input field, password input field, datetime picker, dropdown selector etc) shown as the picture bellow:

![image](https://user-images.githubusercontent.com/482266/31642551-33c84dbe-b2b1-11e7-8faf-02fed5607593.png)

so, what is the best practice for creating these components? 
my question includes:
1. which super class my customized UI component should extend?
2. is there any existing example in tornadofx?
3. can i use bootstrap in my case? and if yes, how can i use bootstrap?

thanks

**Comment by edvin** [comment]
There really isn't anything TornadoFX specific to this process, but I have two recommendations:

1. Don't create a custom control unless you really need to. To add custom functionality to a Button or a TextField, install a custom skin instead.

2. If you really need a custom control, consider extending the `Control` class. For more layout centric components you might extend a layout instead, or simply `Pane`.

To learn more about custom components, consider reading this brilliant book:

https://www.amazon.com/Mastering-JavaFX-Controls-Oracle-Press-ebook/dp/B00L3TF02K

Also check out these videos:

https://www.youtube.com/watch?v=L9xtOhdSx6k

https://www.youtube.com/watch?v=7PPcM0E5yQw

**Comment by genobis** [comment]
@aceyin I think you can achieve desirable results with some clever [JavaFX CSS](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html). You could, for example, create `HBox`, then add `Label`, `TextField`, and a `Button` and with some custom styling have just what you need - that styled `HBox` container could pretend to be a custom, complex component.

Some inspiration - a stunning example by Jasper Potts: http://fxexperience.com/2011/12/styling-fx-buttons-with-css/

By the way, there *are* some [JavaFX ports of Bootstrap](https://github.com/aalmiray/bootstrapfx). If you know it, it may be worth a shot.

Good luck!

**Comment by aceyin** [comment]
@edvin @genobis many thanks.
i will read the topics you both provided and try the suggestions

**Comment by aceyin** [comment]
i found one open source project : controlsfx which did a lot of work for customizing JavaFX UI compoents. i also noticed your team are working on controlsfx-tornadofx project, that's a great project, hope tornadofx can provide the kotlin version quickly :D

**Comment by genobis** [comment]
@aceyin Remember, it's all JVM, there will never be _kotlin_ version of controlsfx, just some helpers and builders for tornadofx. Nothing stops you from using controlsfx in kotlin, with (or without) tornadofx already, like that:

```kotlin
    Platform.runLater { Notifications.create().text("Yay!") }
```

The beauty of Kotlin lies in **full** interoperability with existing Java libs. So go ahead, give it a try :)

**Comment by aceyin** [comment]
@genobis got, thanks :)
