### ISSUE TITLE
Name of Maven artifact

### ISSUE THREAD

**Issue by hastebrot** [edvin/tornadofx#5]
If the Java packager is used to deploy the JavaFX application the Jarfile artifact is named `fx-1.2.2.jar`. Could we rename the Maven artifact from `fx` to `tornadofx` for clearity?

**Comment by edvin** [comment]
Absolutely, I've changed the `finalName` build property to *tornadofx-${version}*.

**Comment by edvin** [comment]
I just tested this change, and I'm afraid it doesn't change the final build name when the artifacts are deployed. I think the only workaround would be to change the maven coordinates :(

**Comment by hastebrot** [comment]
That's unfortunate. To relativize this, there are a lot of artifacts with name duplications, "org.jetbrains.kotlin: kotlin-stdlib:1.0.0" and "org.hamcreste:hamcrest-core:1.3" and "org.testfx:testfx-core:4.0.0".

**Comment by edvin** [comment]
I could release the next version as `no.tornado:tornadofx:1.2.4`. Kind of hate the fact that there would be junk lying around in the maven repos, but I guess it's worth it, and it's much better to do it now than later down the line I guess.

What do you think? Go for it?

**Comment by hastebrot** [comment]
Maybe `no.tornado:tornadofx:1.3.0` to make a semantic distinction. I don't know. It's better now than later.

**Comment by edvin** [comment]
That sounds like a good idea. I've prepared this for the next release, but I would like to settle the property issue before I push it.
