### ISSUE TITLE
How use BorderRadius Stylesheet()?

### ISSUE THREAD

**Issue by nihiluis** [edvin/tornadofx#504]
how can I use BorderRadius here?

```kotlin
        val flat = mixin {
            backgroundColor += Color.TRANSPARENT
            borderColor += box(all = Color.BLACK)
            borderRadius += box(all = Dimension<Int>.)
        }
```

**Comment by ruckustboom** [comment]
There are a number of extension properties for dimensions. You can use them like `25.px`, `0.5.in`, `(someVariable * 2).em`, etc.

**Comment by ruckustboom** [comment]
There are a few examples in [the guide](https://edvin.gitbooks.io/tornadofx-guide/content/part1/6.%20CSS.html)
