### ISSUE TITLE
Tornadofx thread pool behavior

### ISSUE THREAD

**Issue by anidotnet** [edvin/tornadofx#507]
It would be good if you expose some mechanism to override tornadofx's default thread pool factory. By default all threads are non-daemon threads, where as I want them to be all daemon threads. With current api I can't find a way to achieve it. (The reason behind, my applications does not exit as soon as I close it. It takes around 1 min to close, whereas I have not scheduled in long running job)

**Comment by edvin** [comment]
Good call, this is definitely needed!

**Comment by edvin** [comment]
I've added a `ThreadPoolConfig` object so that you can configure this for example in the `init` block of your app class:

```kotlin
ThreadPoolConfig.daemonThreads = true
```

Does that work for you?

**Comment by edvin** [comment]
I'd also like to investigate the viability of setting this as true by default.

**Comment by bekwam** [comment]
Does System.exit() close your application quicker?

**Comment by anidotnet** [comment]
Can we not add another boolean parameter in ```runAsync()``` method, where true means it will create daemon thread and false will create non-daemon one?

Something like this?

```kotlin
fun <T> task(daemon: Boolean = true, taskStatus: TaskStatus? = null, func: FXTask<*>.() -> T): Task<T> =
        FXTask(taskStatus, func = func).apply {
            setOnFailed({ Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), exception) })
            if (daemon) daemonThreadPool.execute(this)
            else threadPool.execute(this)
        }

fun <T> runAsync(daemon: Boolean = true, status: TaskStatus? = null, func: FXTask<*>.() -> T) = task(daemon, status, func)
```

**Comment by bekwam** [comment]
I think =false might be a better default since you might use a non-daemon Thread to complete a shutdown operation or finish up an operation.  That way, if you call Platform.exit() or close the last window your app won't exit immediately and leave the currently running or ending operations in a bad state.

**Comment by AlmasB** [comment]
+1 for `ThreadPoolConfig.daemonThreads` being `false` by default, as discussed by above comment. 

Regards API allowing `task` and `async` to run as daemon, I'd suggest `taskDaemon` or `daemonTask`, same goes with `async`. The motivation being to lift the boolean parameter off the call, since in calls `runAsync(true, ...)` and `task(false, ...)` it is not immediately clear from the context what the boolean parameter refers to.

**Comment by edvin** [comment]
@AlmasB I don't think that's a big issue in Kotlin since we have named parameters.

**Comment by AlmasB** [comment]
@edvin Fair enough. 

On a different note, the functions (whichever API naming approach is taken) are likely to be a better option than `ThreadPoolConfig.daemonThreads`. As pointed out by @anidotnet the obvious use case is when both daemon and non-daemon threads are used in an app. Instead of switching the flag, one can then do:

```
runAsync(daemon = true) {

}

runAsync(daemon = false) {

}
```

**Comment by edvin** [comment]
Agreed. If we can add the parameter without breaking the API we will :) I’ll pick this up again tomorrow and give it a shot!

**Comment by AlmasB** [comment]
I'll see if I can get a PR by end of today

**Comment by edvin** [comment]
Even better! Thank you :)

**Comment by anidotnet** [comment]
Didn't check that @AlmasB has already submitted a PR for the same :(.

Anyway, on a separate note @edvin are you in favour of supporting a shutdown hook which can take care of shutting down non-daemon executor? In my own app I have created something similar which is very handy in such scenario. Let me know if you want it to be added.

It is like below:

```kotlin
object ShutdownExecutor {
    // a task executor to run some routines before
    // graceful shutdown of JVM

    private var taskList = ArrayList<ShutdownTask>()

    init {
        Runtime.getRuntime().addShutdownHook(Thread {
            // create the shutdown hook
            commenceShutdown()
        })
    }

    fun registerTask(task: ShutdownTask) {
        // add the task to a list
        taskList.add(task)
    }

    fun registerTask(task: () -> Unit) {
        // add the task to a list
        taskList.add(object : ShutdownTask {
            override fun execute() {
                task()
            }
        })
    }

    private fun commenceShutdown() {
        // run the task from list before shutdown
        taskList.forEach { it.execute() }
    }
}

@FunctionalInterface
interface ShutdownTask {
    fun execute()
}

fun shutdownAndAwaitTermination(pool: ExecutorService, timeout: Int) {
    synchronized(pool) {
        // Disable new tasks from being submitted
        pool.shutdown()
    }
    try {
        // Wait a while for existing tasks to terminate
        if (!pool.awaitTermination(timeout.toLong(), TimeUnit.SECONDS)) {
            synchronized(pool) {
                pool.shutdownNow() // Cancel currently executing tasks
            }
            // Wait a while for tasks to respond to being cancelled
            if (!pool.awaitTermination(timeout.toLong(), TimeUnit.SECONDS)) {
                logger.error { "Executor did not terminate" }
            }
        }
    } catch (ie: InterruptedException) {
        // (Re-)Cancel if current thread also interrupted
        synchronized(pool) {
            pool.shutdownNow()
        }
        // Preserve interrupt status
        Thread.currentThread().interrupt()
    }
}

```
and it can be used like

```kotlin
ShutdownExecutor.registerTask {
        shutdownAndAwaitTermination(threadPool, 1)
}
```

**Comment by edvin** [comment]
Yeah this sounds like a good idea. I wonder if we should give access to the thread pools in suck a callback?

**Comment by anidotnet** [comment]
We should not give access to thread pool, they should remain internal. As we have only 2 tfx thread-poosl, we can create 2 new functions which will register the shutdown callback to shutdown hook. User does not need to have access to thread pool, they just need to call those method passing a timeout value as necessary. 

The example I provided was from my own application, of course in a library we can not use it as is. Let me know your thoughts.

**Comment by edvin** [comment]
We could give access to the remaining threads though, but unless there is a use case it's probably better to expose as little as possible. If you have time to create this, please do :) I was thinking about doing a release tomorrow, if you can make it within the next 24h we'll be able to get it into the release! No rush though if you can't make it.

**Comment by anidotnet** [comment]
I'll try to make it into the time. One more thing, do you want ShutdownExecutor to be a public api or internal?

**Comment by edvin** [comment]
Great! As long as we can do what we need to I think we should keep it internal for now.

**Comment by anidotnet** [comment]
I need to provide a bit modification over my PR, if you are still up for it. The modification is as follows:

Instead of this (current)

```kotlin
fun terminateExecutorsBeforeShutdown(timeoutMillis: Long) {
     beforeShutdown {
         awaitTermination(tfxThreadPool, timeoutMillis)
         awaitTermination(tfxDaemonThreadPool, timeoutMillis)
     }
 }
```
I think it should be better like

```kotlin
fun terminateExecutorsBeforeShutdown(timeoutMillis: Long) {
       awaitTermination(tfxThreadPool, timeoutMillis)
       awaitTermination(tfxDaemonThreadPool, timeoutMillis)
}
```
Let user chose when to call, before shutdown or at any given time. Let me know your thought, I can give you a quick PR.

**Comment by edvin** [comment]
Please do :)

**Comment by edvin** [comment]
Merged :) Thanks a lot!
