### ISSUE TITLE
Fragment with a result

### ISSUE THREAD

**Issue by AlmasB** [edvin/tornadofx#511]
This is a question / proposal. In the past I've used a small extension of a `Fragment` when I needed to a get a result from a short-lived fragment.

Use case: the user opens a modal fragment, enters some data, closes the fragment, the data is now available where the user opened the fragment.

What I used to do:

```
abstract class ResultFragment<T>(title: String) : Fragment(title) {
    // this should be private
    lateinit var fn: (T) -> Unit

    protected fun closeWithResult(result: T) {
        fn.invoke(result)
        close()
    }
}

fun <R, S : ResultFragment<R>> openFragment(fragmentClass: KClass<S>, fn: (R) -> Unit) {
    val fragment = find(fragmentClass)
    fragment.fn = fn
    fragment.openModal(block = true)
}
```

User class:

```
class AddAssignmentFragment : ResultFragment<Assignment>("Add Assignment")
```

Usage:

```
val assignments = ...

button("Add Assignment") {
    action {
        openFragment(AddAssignmentFragment::class, { assignments.add(it) })
    }
}
```

I don't _quite_ remember why I needed this extension but I believe the motivation behind it was
that with the current approach in order to get back the data from the fragment we first need to instantiate the fragment and / or pass a specific parameter via injection?

**Comment by edvin** [comment]
Use scopes instead. Simply create a new scope, inject your viewmodel into the scope, then open the fragment in the new scope. The fragment modifies the viewmodel, and the data is available at the call site where you created the scope :)

**Comment by AlmasB** [comment]
Cheers 👍

**Comment by edvin** [comment]
Let me know if you can't get it to work smoothly and I'll create a sample :)

**Comment by Awais16** [comment]
Sample will help beginners 😅

**Comment by NiranjanShah** [comment]
Agree with Awais, sample will help beginners.

feel very energetic to use the new technology, however kindly provide adequate documentation with samples for various scenarios.

I would suggest to take a sample application which must cover login to reporting functionality.

**Comment by edvin** [comment]
Sure, here is a complete example demonstrating how you can pass parameters between scopes. This is all covered in the guide, we can't give examples of everything, but all the knowledge you need to perform these operations are described in the guide. If you want to supply a demo application to the tornadofx-samples project, a PR is most welcome :)

```kotlin
class DemoApp : App(MainView::class)

class Person {
    val nameProperty = SimpleStringProperty()
    var name by nameProperty
}

class PersonModel : ItemViewModel<Person>(Person()) {
    val name = bind(Person::nameProperty)
}

class MainView : View("Person list") {
    val people = FXCollections.observableArrayList<Person>()

    override val root = borderpane {
        center {
            tableview(people) {
                column("Name", Person::nameProperty)
                smartResize()
            }
        }
        bottom {
            hbox(spacing = 10) {
                button("Add...").action {
                    // Create a new model and set some default values
                    val newPerson = PersonModel()
                    newPerson.name.value = "New name"
                    // Create a new scope and inject the PersonModel into that scope
                    // You can also add other objects that could work as parameters for the PersonEditor
                    val newScope = Scope(newPerson)

                    // Find the PersonEditor in the new scope and open a modal - wait for the result
                    find<PersonEditor>(newScope).openModal(block = true)

                    // Insert the edited Person into the table in this View
                    // You could access any object in the scope of the editor from here
                    people.add(newPerson.item)
                }
            }
        }
    }
}

class PersonEditor : Fragment("Person Editor") {
    val person: PersonModel by inject()

    override val root = form {
        fieldset {
            field("Name") {
                textfield(person.name).required()
            }
        }
        button("Save and close") {
            isDefaultButton = true
            action {
                person.commit {
                    close()
                }
            }
        }
    }
}
```

**Comment by edvin** [comment]
I don't understand what you mean - the complete Person object is already passed to `onUserSelect` function as a parameter. You can just wrap that in a viewmodel and pass to the PersonEditor, then any changes committed to that viewmodel will be immediately visible in the table.
