### ISSUE TITLE
rest post function

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#513]
hello
thanks for this good framework
it's amazing 

i read your tutorial  in rest and json
i can't  do post  operations and  it not in the tutorial
how can id do this

**Comment by edvin** [comment]
Hi! Post is done using the `post` function on the `Rest` class:

```kotlin
val resultAsJson = api.post("url", json).one()
```

If your domain objects implement `JsonModel` you can even do:

```kotlin
val resultAsMyObject = api.post("url", myObject).one().toModel()
```

Does that make sense?

**Comment by mostfa-ayad** [comment]
hi 
i try  using this method  put it's didn't work with me 
i test my api  by rest client  and it work perfect
but using tornado  no thing happen   
     println(   api.post("articles",article.toJSON()).status)
this return  ----->   BadRequest

**Comment by edvin** [comment]
Just calling `post` doesn't end the response. You need to call either `consume()`, `one()` or `list()` first.

**Comment by mostfa-ayad** [comment]
thanks alot  , it's  work

**Comment by edvin** [comment]
Great, thanks for getting back to me :)
