### ISSUE TITLE
Force ui callback to run on UI thread

### ISSUE THREAD

**Issue by anidotnet** [edvin/tornadofx#514]
Currently ```ui{}``` callback of ```runAsync``` does not guarantee to run on UI thread always. If the ```runAsync``` is called from UI thread, then only ```ui{}``` call back runs on UI thread, otherwise it just simply run on calling thread, which is kind of misnomer.

In my use case, a ```runAsync``` is being invoked from EventBus subscriber, which run in background thread. The ```ui``` block of it, is supposed to render an image in an image view. Sometimes, it is just blank as ```ui``` block is not running on UI thread. 

I end up calling it like

```kotlin
runAsync {
 // network call
      runLater {
           // ui call
      }
}
```
I may be missing something here, or we need to enforce the rule to run ```ui``` callback to run on UI thread.

**Comment by edvin** [comment]
Good catch! Wonder why it has never bitten me before :)

We could augment `success` to something like:

```kotlin
infix fun <T> Task<T>.success(func: (T) -> Unit) = apply {
    Platform.runLater {
        setOnSucceeded {
            if (Platform.isFxApplicationThread()) {
                func(value)
            } else {
                runLater { 
                    func(value)
                }
            }
        }
    }
}
```

Or.. we could only do this for `ui` and make a distinction between `success` and `ui`. What do you propose?

**Comment by anidotnet** [comment]
Let us honor the name. Let ```success``` run on the calling thread and ```ui``` on UI thread. That seems logical to me. Moreover, it will not break existing code. If you agree, I can submit a PR in a next hour or so.

**Comment by anidotnet** [comment]
I am a little bit confused now. I just now checked the code for ```success``` and ```ui```.

```kotlin
infix fun <T> Task<T>.ui(func: (T) -> Unit) = success(func)

infix fun <T> Task<T>.success(func: (T) -> Unit) = apply {
    Platform.runLater {
        setOnSucceeded { func(value) }
    }
}
```
According to it, ```ui``` block should run in UI thread, as ```success``` runs on UI thread. But in my case it does not run on UI thread with guarantee. I am confused. But I can assure that my ```ui``` block was not updating ImageView all the time, but when I run it like below it was populating:

```kotlin
runAsync {
 // network call
      runLater {
           // ui call
      }
}
```
Any ideas?

**Comment by anidotnet** [comment]
My bad. Further investigation reveals that culprit was my local maven repo. It got some corrupted snapshot version of tfx. Once I cleaned it, it worked like a charm with latest master. Who knew!! 

Anyway I am keeping this issue open for a little bit longer, just in case it resurfaces, but ideally it should not. Extremely sorry for wasting your time. :(

**Comment by edvin** [comment]
Be adviced, the code you posted above just shows that `setOnSucceeded` is called on the UI thread. That's needed to avoid exceptions, because there is a check for it in JavaFX. However, as I understand it, JavaFX also makes sure to call the success callback on the UI thread. I think this means that there is no issue with the framework with regards to this.

Why do you feel that `runAsync` in `Component` cause problems?

**Comment by anidotnet** [comment]
I don't know when I call it from a fragment, I am not sure which one is it calling - the one from Component or from Async.kt? Moreoever, the component's ones do not have the daemon extension also.

**Comment by edvin** [comment]
We should add the async parameter to the one in Component as well. We can't really deprecate it, as it will be hard to hit the right one, I think we just need to inform about this and remove it. I don't want to do this in this release, since it contains so much refactoring, but we could target it for the next release.

**Comment by anidotnet** [comment]
Good call. We can remove them in coming release.

**Comment by anidotnet** [comment]
Still very few times facing the issue, but unable to create any mcve. Only if I call the ui code from ```runLater``` it works with 100% guarantee. Really no idea what causing it. If I print ```Platform.isFxApplicationThread()``` inside ```ui``` block, it always prints true, but still image fails to render sometimes.

**Comment by edvin** [comment]
Huh.. This is supposed to be enforced by JavaFX itself, so there might be a bug in the JDK. Perhaps it's solved in JDK9. I suggest just wrapping this call that fails in `runLater` for now. It has never bitten me, and you can actually see that you're on the correct thread, so maybe it's just a timing issue? Calling `runLater` again will make sure the call is delayed, so maybe that's what's "fixing" it?

**Comment by anidotnet** [comment]
Your explanation seems logical. It might be a timing issue after all.
