### ISSUE TITLE
Typo in SmartResize function name `weigthedWidth`

### ISSUE THREAD

**Issue by NLBuescher** [edvin/tornadofx#520]
So I noticed a typo in the function `weigthedWidth` in [SmartResize.kt](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/SmartResize.kt#L276-L282), while using the smart resizing feature of tables.

The function is currently called "weig**th**edWidth", but it should be called "weig**ht**edWidth". the T and the H are flipped from what they should be.

**Comment by edvin** [comment]
Thanks! I committed a fix for it now :)

**Comment by jakubgwozdz** [comment]
sample no.tornadofx.fxsamples.withpojo.view.EntryView wants this update too :)

**Comment by edvin** [comment]
No it seems it was corrected there, but the column builder for immutable properties was renamed a while back, so I committed a fix for that (`readonlyColumn`)
