### ISSUE TITLE
How to set title/owner in confirm() / alert()?

### ISSUE THREAD

**Issue by jschneider** [edvin/tornadofx#522]
Hi guys,

I would like to set the title (javafx.scene.control.Dialog#titleProperty) of a confirmation dialog (that one in the decoration window).
I couldn't find a way at the moment.
Is this possible?

Also I couldn't find a way to set the owner in the confirm() method. But it is possible with alert.

**Comment by edvin** [comment]
Thanks for reporting! I've added `title` and `owner` parameters to all dialog builders :)
