### ISSUE TITLE
Applying `SmartResize.POLICY` causes InvocationTargetException

### ISSUE THREAD

**Issue by mdomasevicius** [edvin/tornadofx#524]
I ran into an issue where by setting `columnResizePolicy = SmartResize.POLICY` I cause a recoverable exception of sorts. App still runs but the exception is presented.

Here is a snippet:

>java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at tornadofx.SmartResizeKt$resizeColumnsToFitContent$doResize$1.invoke(SmartResize.kt:366)
	at tornadofx.SmartResizeKt$resizeColumnsToFitContent$doResize$1.invoke(SmartResize.kt)
	at tornadofx.SmartResizeKt.resizeColumnsToFitContent(SmartResize.kt:374)
	at tornadofx.SmartResizeKt.resizeColumnsToFitContent$default(SmartResize.kt:361)
	at tornadofx.SmartResizeKt.resizeCall(SmartResize.kt:412)
	at tornadofx.SmartResize.call(SmartResize.kt:43)
	at tornadofx.SmartResize.call(SmartResize.kt:41)
	at javafx.scene.control.TableView.setContentWidth(TableView.java:1623)

Usual suspects:

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

```
javac 1.8.0_121
```

[Can check out the whole project on github](https://github.com/mdomasevicius/tabby-2/blob/cfb68d8368954a171a80cebdad6a239176f61f56/src/main/java/lt/hadex/tabby2/ItemListView.kt#L65)

**Comment by edvin** [comment]
You're doing several weird things here.

First, `fitToParentSize` is not intended to be used with table columns, so remove those. What are you trying to express with this?

Combining `resizeColumnsToFitContent()` with smart resize is also weird, since smart resize will do that for you already (unless you configure the columns to use another strategy), so remove those calls as well.

By the way, you can configure smart resize just by calling `smartResize()` inside the TableView, no need to assign to `columnResizePolicy` manually.

If it still fails when you have removed all those calls, try importing the sources for TornadoFX and set a breakpoint on line 366 in SmartResize.kt. It looks like the reflective call to `resizeColumnToFitContent` fails for one or more columns. Try running the expression manually in the debugger and look at the stack trace. If the issue isn't immediately obvious, post that stack trace here and tell me for which column it happens, and we'll figure it out.

**Comment by mdomasevicius** [comment]
I am trying to make table column taking up all available space withing `tableView` so that all of the space wold be used up. I removed all the calls as per your suggestion:

```
tableview<Item>(FXCollections.observableArrayList(mapTableContent.values)) {
                    column(bundle.getString("item.table.name"), Item::name)
                    column(bundle.getString("item.table.art"), Item::art)
                    column(bundle.getString("item.table.factoryArt"), Item::factoryArt)
                    column(bundle.getString("item.table.photo"), Item::imageUri)

                    smartResize()
                    enableCellEditing()
                    fitToParentSize()
                }
```

What did I learn:

![image](https://user-images.githubusercontent.com/20511486/32418924-baa0b92e-c27a-11e7-8068-dd02b9902439.png)

NPE is the target - so ok let's move to `NativeMethodAccessorImpl`

![image](https://user-images.githubusercontent.com/20511486/32418970-58956238-c27b-11e7-8ea6-c3a4a0b5f2cc.png)

Moving on to `TableViewSkin#resizeColumnToFitContent`

![image](https://user-images.githubusercontent.com/20511486/32419031-40283ec2-c27c-11e7-9aa7-63cb2dfd2ec9.png)

The header is `null`, as far as I can see happens for column[0].

**Comment by edvin** [comment]
If you remove `smartResize()` - did all column header labels actually get a value?

**Comment by mdomasevicius** [comment]
They do even if I leave `smartResize()` 

![image](https://user-images.githubusercontent.com/20511486/32419387-b7d72bf4-c281-11e7-816b-950bc5c5022e.png)

**Comment by edvin** [comment]
Can you provide a normal build.gradle file for your project so I can run it? I'll figure it out much easier that way :)

**Comment by mdomasevicius** [comment]
What is wrong with one in my app [repo](https://github.com/mdomasevicius/tabby-2) ?

**Comment by edvin** [comment]
You have a Kotlin version of the build file (build.gradle.kts), and IDEA won't recognize it for some reason.

**Comment by mdomasevicius** [comment]
Here is a [link](https://github.com/mdomasevicius/tabby-2/tree/gradle/groovy-dsl) to the project using groovy DSL. I think kotlin dsl version did not work due to `.idea` folder present in the project :)

**Comment by edvin** [comment]
I got it working when I deleted .idea folder, but I need the database it seems.

**Comment by edvin** [comment]
Once you remove all those weird/unneeded calls, it works as expected:

```kotlin
tableview<Item>(FXCollections.observableArrayList(mapTableContent.values)) {
    column(bundle.getString("item.table.name"), Item::name)
    column(bundle.getString("item.table.art"), Item::art)
    column(bundle.getString("item.table.factoryArt"), Item::factoryArt)
    column(bundle.getString("item.table.photo"), Item::imageUri)

    smartResize()
    enableCellEditing()
}
```

Also bear in mind that `enableCellEditing()` is a call on `TableView`, not on `TableColumn`.

**Comment by mdomasevicius** [comment]
Thanks for support.

**Comment by edvin** [comment]
You're welcome. Did you figure out how to get the layout to behave like you wanted to?
