### ISSUE TITLE
navigate betwen subviews

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#532]
hello 
 i want the user when select an view  see a table and when he select to edit or view details of an item or add new move to the details view and he can return to the table again 
is the drawer the best for this
i using the drawer but i can't set the default view  
![screenshot_2017-11-10_20-25-13](https://user-images.githubusercontent.com/10268036/32672801-2a44bba8-c655-11e7-814b-6a9f13651a21.png)

**Comment by edvin** [comment]
You have several options, depending on how you want your ui to look like. Most of them involve reacting to the user selection using the `onUserSelect` callback inside of `TableView`.

You should create a ViewModel for the items in the table, and inject this model inside the view where you have the table:

```kotlin
val selectedItem: MyItemModel by inject()
```

Then make sure the value inside of the model changes when the user changes selection:

```kotlin
tableview {
   ...
   bindSelected(selectedItem)
}
```

Now you just have to show a view that also injects the `MyItemModel` so it can get to the selected instance. Next you must decide how you want the view to show up.

If you're using the Workspace, do `workspace.dock<ItemEditor>()` and if you want to open a new window, you do `find<ItemEditor>().openModal()`. You can also replace the current View with the new View using `replaceWith<ItemEditor>()`. To navigate back in such a scenario, simply do `replaceWith<TheViewWithTheTable>()`.

Hope this gives you some ideas. Everything is possible, and even easy, once you decide on the navigation paradigm you want to use :)

**Comment by mostfa-ayad** [comment]
thanks alot 
i create a viewModel  and using the value of selected item in the details view  
i want the user when prees the addNew button all values of selected model 
to be empty to using in add new item to the list
i can't do this by assign new object becuse using val

**Comment by edvin** [comment]
Create a med scope and open the editor in that scope. Read the scope chapter in the guide to understand how scopes work :)

**Comment by mostfa-ayad** [comment]
i will do thanks alot for help

**Comment by mostfa-ayad** [comment]
hello again , please be  be patient 
i use an scope to intilize my model value  
and assign model property to textefield  
when i use model item to save values  it still  null   

`fun open(account: Account) {
        val editScope = Scope()
        val model = AccountModel()
        model.item = account
        setInScope(model, editScope)
        openInternalWindow<AccountEditor>(editScope)
    }`

`
class AccountEditor : Fragment("My View") {
    val controller:AccountController by inject(DefaultScope)
    val model:AccountModel by inject()
    var code:TextField by singleAssign()
    var name:TextField by singleAssign()
    var save:Button by singleAssign()
    var edit:Button by singleAssign()
    init {

    }

    override val root = vbox {
        hbox {
            label("code")

            code=textfield(model.code){

                editableProperty().set(controller.editMode)
            }

        }
        hbox {
            label("name")

            name=textfield(model.name){

                editableProperty().set(controller.editMode)
            }

        }
        hbox {
            save = button("save") {
                disableProperty().set(!controller.editMode)
                action {
                    var account: Account = Account()
                    if (controller.isNew) {


                        controller.insertAccount(model.item)

                    } else {

                        controller.updateAccount(model.item)
                    }
                    println(model.item)
                    controller.editMode = false
                    controller.isNew = false
                    onRefresh()
                }
                println(model.item.code)
                println(model.item.name)

            }
            edit = button("edit") {
                visibleProperty().set(!controller.isNew)
                disableProperty().set(controller.editMode)
                action {
                    controller.editMode = true
                    controller.isNew = false
                    onRefresh()
                }

            }
        }
    }

    override fun onRefresh() {
        code.editableProperty().set(controller.editMode)
        name.editableProperty().set(controller.editMode)
        save.disableProperty().set(!controller.editMode)
        edit.disableProperty().set(controller.editMode)
    }

}
`

**Comment by edvin** [comment]
There are many things I can't test in this app, since you didn't provide the Account, AccountModel and controller class. Can you post a complete working sample?

Also, there is no need to save each input field in a value using singleAssign just to set the editableProperty, and you certainly don't need to do this on every refresh. Just make sure `controller.editMode` is an observable boolean and bind the editable state directly inside of the builder. I also just added `TextInputControl.editableWhen`, so you can say `editableWhen(controller.editMode)` from the next release.

**Comment by mostfa-ayad** [comment]
[account.zip](https://github.com/edvin/tornadofx/files/1470049/account.zip)

**Comment by edvin** [comment]
The reason you don't see your updated values is that you don't call `model.commit` before inspecting the values. This is what flushes the changes in the UI back into your item. You also had forgot an `action` handler for one of your buttons. To clean up your app and get rid of the need to recalculate in `onRefresh`, change your controller to contain observable properties for the edit and new state, like this:

```kotlin
    val isNewProperty = SimpleBooleanProperty()
    var isNew by isNewProperty

    val editModeProperty = SimpleBooleanProperty()
    var editMode by editModeProperty
```

Also, move the manipulation of these states to the update and insert calls in your controller:

```kotlin
    fun insertAccount(account: Account) {
        try {
            println(api.getURI(path))
            api.post(path, account.toJSON()).consume().ok()
            editMode = false
            isNew = false
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    fun updateAccount(account: Account) {
        api.put("$path/${account.code}",account.toJSON()).consume().ok()
        println(account.toJSON())
        editMode = false
        isNew = false
    }
```

Now you can clean up your account editor by using the form layout, and binding to the state properties in your controller. I've also fixed the missing commit, and removed some redundant state changes. I also included the `editableWhen` function to clean it up further.

```kotlin
// This function is in the next version of TornadoFX
fun TextInputControl.editableWhen(predicate: ObservableValue<Boolean>) = apply {
    editableProperty().bind(predicate)
}

class AccountEditor : Fragment("Account Editor") {
    val controller: AccountController by inject(DefaultScope)
    val model: AccountModel by inject()

    override val root = form {
        fieldset {
            field("code") {
                textfield(model.code) {
                    editableWhen(controller.editModeProperty)
                }
            }
            field("name") {
                textfield(model.name) {
                    editableWhen(controller.editModeProperty)
                }
            }

            buttonbar {

                button("save") {
                    enableWhen(controller.editModeProperty)
                    action {
                        model.commit {
                            var account: Account = Account()
                            if (controller.isNew) {
                                controller.insertAccount(model.item)
                            } else {
                                controller.updateAccount(model.item)
                            }
                            println(model.item)
                        }
                    }
                }
                button("edit") {
                    removeWhen(controller.isNewProperty)
                    disableWhen(controller.editModeProperty)
                    action {
                        controller.editMode = true
                    }
                }
            }
        }
    }
}
```

I hope this gives you a better overview of how to leverage observable properties, and also of course understanding the viewmodel a little better.

**Comment by mostfa-ayad** [comment]
![image](https://user-images.githubusercontent.com/10268036/32774022-af445238-c933-11e7-85fb-91f401486992.png)

**Comment by edvin** [comment]
`import tornadofx.*` :)

**Comment by mostfa-ayad** [comment]
thanks alot :)

**Comment by edvin** [comment]
You're welcome :)
