### ISSUE TITLE
alert  resize the workspace

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#534]
hello 
using the workspace in fullscreen  the alert resize the workspace

 var aleart= Alert(Alert.AlertType.CONFIRMATION,"delete ?")
        var result:Optional<ButtonType> = aleart.showAndWait()
        if(result.get()== ButtonType.OK){
            controller.deleteAccount(controller.selectedAccount.item)
            onRefresh()
        }

**Comment by edvin** [comment]
I don't understand what you mean. Can you provide a complete application that showcases the issue?

**Comment by mostfa-ayad** [comment]
my problem i make  alert  to worning the user when abutton press 
 when the  alert open and the app in  fullscreen  it minmize the app  
i think the problem whit my OS 
i use  openSUSE  os  when i try my app in windows working without any problem

**Comment by nimakro** [comment]
I will close this issue due inactivity. @mostfa-ayad  feel free to reopen the issue with a little app that showcases your issue.
