### ISSUE TITLE
Center a component in (form-fieldset-field)

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#535]
Hello, I am using the form, field and fieldset components to enter data. But when I add 2 RadioButton I want them to be in the center, I try to use the "alignment" property but it does not solve my problem.
This is the code that I have:

```
form {
  fieldset{
         field {
             this += JFXRadioButton("Empresa")
             this += JFXRadioButton("Persona")
          }
         field {
             this += JFXTextField()
          }
   }
}
```

![imgradio](https://user-images.githubusercontent.com/22163898/32765352-fa13aa36-c8d7-11e7-9f56-41ad5e6dd7b9.png)

Regards!

**Comment by edvin** [comment]
To center components inside of a field, just add an hbox with center alignment:

```kotlin
class MainView : View() {
    override val root = form {
        fieldset {
            field("Radios") {
                hbox(alignment = Pos.CENTER) {
                    radiobutton("Radio 1")
                    radiobutton("Radio 2")
                }
            }
        }
    }
}
```

**Comment by TioCoding** [comment]
But then, what would be the difference between using normal containers (vbox, hbox, etc.) compared to the use of form, fielset and field?

**Comment by edvin** [comment]
They give you form like layouts for free and includes many features that are hard to do yourself by nesting hbox/vbox containers. Read about it in the guide :)

**Comment by TioCoding** [comment]
Ok thank you, at the beginning it's a bit confusing, but little by little I understand it. regards :grin:

**Comment by edvin** [comment]
It can be a lot to deal with at once, but when you get the hang of it it's going to be both easy and effective!
