### ISSUE TITLE
Is there a support for messaging?

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#536]
Hello, I would like to know if there is any way to integrate an application with ActiveMq or RabbitMq. I currently use SpringBoot for this task, but I wanted to know if. TornadoFx has support or in the future plans to implement it?

**Comment by edvin** [comment]
I don't think the framework needs any special support to be able to work with ActiveMq or RabbitMq. What did you have in mind?

**Comment by TioCoding** [comment]
As I saw, it already has integrated support for Rest. I thought I could have a messaging client like (RabbitMq, etc.). Once I read about MQTT.fx, for Javafx applications that function as an MQTT client. I thought it would be nice to have a messaging client integrated in "TornadoFx"

**Comment by TioCoding** [comment]
In addition to working directly, it is too much configuration. That's why I chose to use SpringBoot, to integrate it with the RabbitMq client.

**Comment by edvin** [comment]
I'm not sure it requires any particular integration, since TornadoFX mainly deals with the UI. We do have an http client, since that's a very common requirement for a UI application. You can use SpringBoot with TornadoFX, so I'm not exactly sure what you hope to gain from integration with TornadoFX?

**Comment by TioCoding** [comment]
Currently real-time applications are more common, so I see that need. However I have no problem with integrating it with SpringBoot, it was just an idea that came to my mind and I wanted to share it 😄

**Comment by edvin** [comment]
OK :) Update the issue if you can come up with a concrete plan as to what TornadoFX can help with :)

**Comment by TioCoding** [comment]
It's okay, taking advantage of the quick answers. Is there any limitation of your Rest client that has TornadoFx integrated, compared to a framework like Retrofit?

**Comment by edvin** [comment]
I'm not aware of any limitations, and I'm happy to add features if you need them. That said, there is nothing problematic about using an external http client instead :)

**Comment by TioCoding** [comment]
Ok, thank you very much for the clarification 😄
