### ISSUE TITLE
how to Inject view in another class with spring?

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#537]
Hello, I'm using the MVP and Spring design pattern, now I'm trying to inject a view into a presenter, but it can not. I try with this line code:

```
package com.clario.ClarioDesktopApp.presenter

import com.clario.ClarioDesktopApp.view.cliente.ClienteScreen
import org.springframework.stereotype.Component

@Component
class ClientePresenter{

    private val clienteScreen: ClienteScreen by inject() // Unresolved reference: inject

}
```
also try with "by di()" but not the same I have the same error.

They only work if my class extends from Controller or View. Is it required to extend these classes to be able to inject?

**Comment by edvin** [comment]
`inject` is a function available on `Component`. You can use `find` though. I think you might run into issues with this approach. External di is not meant to be mixed with your UI, so you're in uncharted waters. Not sure what you hope to gain by using Spring instead of the built in dependency injection mechanism?

**Comment by TioCoding** [comment]
Well, I'm migrating an application, and in this I have integrated Spring-Framework, that's why my query. But if you tell me that I can replace the Spring-Framework injections by TornadoFx Component, I will try this solution.
Thank you very much.

**Comment by edvin** [comment]
It's fine to use external DI, but you probably shouldn't involve UI components with externally injected controllers, that doesn't make so much sense. If your externally injected controllers contains references to UI components, try to replace them with state properties instead :)

**Comment by edvin** [comment]
You need to configure the injector to let it know how to locate your spring beans. This is described in the guide:

https://github.com/edvin/tornadofx-guide/blob/master/part2/Dependency%20Injection.md

**Comment by TioCoding** [comment]
I have it configured correctly, the problem as I say is label(helloBean.textName()), if I comment that line works perfectly. But I want to know how I can use instead of the tornadofx controller, use a Kotlin class annotated with Component with spring

**Comment by edvin** [comment]
The injection is lazy, so if `helloBean.textName()` is the first interaction with `helloBean`, it makes sense that the stack trace originates from that line. The code you have that configures the injection doesn't seem to have run at that point, so you might have put it in the wrong place. Post a complete example project if you can't figure it out :)

**Comment by TioCoding** [comment]
Hello, this is the project, the settings are in "MyApp", my view "MainTestView" and my presenter of spring "MainTestViewPresenter"

https://github.com/TioCoding/TornadoFxTest

Regards :smile:

**Comment by gtnarg** [comment]
Change the following declaration in MainTestViewPresenter

   ```
 //private val mainTestView =  find(MainTestView::class)
 private val mainTestView: MainTestView by lazy {
        find(MainTestView::class)
 }
```

**Comment by TioCoding** [comment]
Thanks for the response, this solved my problem, but I have one last question. I'm using a method to load the information, the method is called mainTestViewPresenter.loadData (), this method is executed when MainTestView is created:
```
init{
        with(root){
            top {
                label(mainTestViewPresenter.textName())
            }
            center {
                button("Push") {
                    setOnAction {
                        mainTestViewPresenter.callPrint()
                    }
                }
            }
        }
        mainTestViewPresenter.loadData() // Load information
}
```
And my mainTestViewPresenter looks like this:

```
@Component
class MainTestViewPresenter {

//  private val mainTestView = find(MainTestView::class)
    private val mainTestView: MainTestView by lazy {find(MainTestView::class)}
    
fun textName(): String = "Juan Junior"

    fun callPrint() {
        println("call print My Bean: ${1 + 2}")
        mainTestView.printOtherMessage()
    }

// This method, when it finishes loading information, uses a MainTestView method to add it.
    fun loadData(){
        FX.log.info("Load data ....")
        mainTestView.printOtherMessage() // StackOverflowError
    }
}
```

The problem now is that an infinite loop is created and gives a StackOverflowError.

I solved it by putting the runLater when executing the method `runLater{mainTestView.printOtherMessage()}` 

I would like to know if this solution is ok? Or if there is a better solution to implement it. Thank you.

**Comment by gtnarg** [comment]
This is how you should handle async tasks like loading data

```
fun loadData(){
    runAsync {
        FX.log.info( "Load data ....")
    }  ui {
        mainTestView.printOtherMessage()
    }
}
```

**Comment by gtnarg** [comment]
I don't see why you need your Presenter to be instantiated by Spring.  I would be inclined to make it a Controller and let TornadoFx handle it's creation (eg.  MainTestViewPresenter:Controller).  Any external services (eg. to load data) can still be inject by Spring.  I use Spring Boot as well but I let TornadoFx wire all of the view components and I only inject other services into the TornadoFx components using `by di()` with Spring.

**Comment by TioCoding** [comment]
The reason why I chose to create MainTestViewPresenter with Spring, is because I need to use the Spring Profiles system. For example, I have this approach:

My interface Interactor:
```
interface CargoInteractor {
    fun findAllCargo()
}
```

My implementation for dev profile, in this case I am using retrofit:
```
@Component
@Profile("dev")
class CargoInteractorImpl : CargoInteractor{

    @Autowired
    private lateinit var cargoPresenter: CargoPresenter
    @Autowired
    private lateinit var cargoRest: CargoRest

    override fun findAllCargo() {
        cargoRest.findAll().observeOn(JavaFxScheduler.platform())
                .subscribeOn(Schedulers.newThread())
                .observeOn(JavaFxScheduler.platform())
                .subscribe({ result -> cargoPresenter.operationFindListSuccess(result) },
                        { error -> error.printStackTrace() })
    }
}
```

My implementation for offline profile, i use it to develop without having to connect to the internet:
```
@Component
@Profile("offline")
class CargoOfflineInteractorImpl : CargoInteractor{

    @Autowired
    private lateinit var cargoPresenter: CargoPresenter

    override fun findAllCargo() {
        cargoPresenter.operationFindListSuccess(listOf(Cargo(...),Cargo(...),Cargo(...),...))
    }
}
```
And finally, I use the profile I want with `-Dspring.profiles.active=offline`

For this reason, I have used Spring and not TornadoFx Controller. But, is there any way to do this same implementation using only TornadoFx with the Controller?
