### ISSUE TITLE
How to use the "find()" method of the View class

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#538]
Hello, I am trying to find a tag for your identification in a view, but I would like to know how to use it. 

`var labelName = view.find...... // How to use?`

Thank you.

**Comment by edvin** [comment]
Are you asking how to locate a certain node inside of a View? If so, you can use the `select` function on `Node` which allows you to locate a component based on a style class or id.

**Comment by TioCoding** [comment]
Okay thank you very much.
But I have another query, I'm using a ListView and an adapter (similar to the function of RecyclerView with Android), my doubt is that I'm building my elements with the following class:

```
class ClienteItemScreen : HBox(){
    init {
        with(this) {
              /*.... Body ....*/
        }
    }
}

```
And everyone has a new record, I think the instance  `ClienteItemScreen()`

My question is, if I do extend my Fragment() class, how do I recover a different instance, every time I have a new record in my ListView?

**Comment by edvin** [comment]
You should use the `ListItemFragment` for this :)  Every time a fragment is reused for a cell, the `itemProperty` of the fragment will change. You should wrap the itemFragment in a ViewModel, so that your ui inside the fragment can be bound to the ViewModel.

**Comment by TioCoding** [comment]
Hello thank you very much, have an example on this particular case?

**Comment by edvin** [comment]
Yeah, there is one in my todoapp: https://github.com/edvin/todomvc/blob/master/src/main/kotlin/todomvcfx/tornadofx/views/TodoItemFragment.kt

**Comment by TioCoding** [comment]
Thanks for your example. But at what point is the ViewModel used?

**Comment by edvin** [comment]
Line 12: `val todo = TodoItemModel(itemProperty)`

This is where the magic happens. The `TodoItemModel`'s properties can be bound to the UI, and the underlying item for this fragment will automatically be changed out as the fragment is used to render cells representing different items. See? :)

**Comment by TioCoding** [comment]
But TodoItemModel extend of ItemViewModel and no of ViewModel.

**Comment by edvin** [comment]
Yes, and ItemViewModel extends ViewModel. This is because it is only wrapping a single item at a time, and as such it provides some extra convenience functions over ViewModel. I don't quite understand your concern? :)

**Comment by TioCoding** [comment]
My concern is more to understand the concept of ItemViewModel and ViewModel. I do not want to make the mistake of using a tool without understanding its functionality thoroughly. Thank you very much for the answers, I will put into practice these concepts :smile:

**Comment by edvin** [comment]
Great :) Be sure to read the chapter in the guide about editing models!

**Comment by TioCoding** [comment]
Thanks, could you pass me a direct link? I can not find this section

**Comment by edvin** [comment]
Sure, this page goes in depth about the differences between ViewModel and ItemViewModel as well:

https://edvin.gitbooks.io/tornadofx-guide/content/part1/11.%20Editing%20Models%20and%20Validation.html

**Comment by TioCoding** [comment]
Thank you very much
