### ISSUE TITLE
Differences between ItemViewModel and ViewModel

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#539]
Hi, me again. I'm doing a form and I see examples where you use ViewModel and other ItemViewModel, and I would like to know what is the difference between them? when to use ViewModel and when the ItemViewModel.

_(I do not find documentation on the Wiki about this, so I ask around here.)_

Thank you

**Comment by edvin** [comment]
The guide specifies that the ItemViewModel is used to wrap a single item, and is the most common one. ViewModel is mostly used for either adhoc bindings or as a "controller" of sorts in MVC. You should read the guide, the Wiki is being phased out as we move all the info over to the guide :)
