### ISSUE TITLE
Injection support in the `App` class

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#54]
It would be convenient to be able to inject resources into the `App` class, for easier configuration of resources before the app is started. An example would be configuration of the `Rest` interface. Instead of using `find(Rest::class)` one could inject a rest member in the normal way and configure it in `init`.

**Comment by thomasnield** [comment]
I actually had this challenge earlier without realizing it. This definitely would be helpful.

**Comment by edvin** [comment]
I just checked in an implementation. Do you have time to test it before we release @thomasnield ?

**Comment by thomasnield** [comment]
Sure. To save time, what exactly do I do?

**Comment by edvin** [comment]
I just updated the [`REST Client API` Wiki page](https://github.com/edvin/tornadofx/wiki/REST-Client) with an example:

```kotlin
class MyApp : App() {
    val api: Rest by inject()

    init {
        api.baseURI = "http://contoso.com/api"
    }
}
```

Basically, inject any controller in the App Class, configure a value or something in the `init` function, and check that the property is indeed changed when your application has started :)

**Comment by thomasnield** [comment]
Okay cool, the injection seems to work for me. 

Don't mean to digress, I struggled to use the `Controller` injection a few weeks back perhaps because I was doing something wrong. The thing is RxJava and its inversion of control might have called for a different injection pattern. I'll dig up my example later and file it as an issue.

**Comment by edvin** [comment]
That's interesting, let me know when you have the example, would love to take a look at it. I also updated some README examples that used outdated syntax. Preparing release now.
