### ISSUE TITLE
Change ListCell in ListCellFragment

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#541]
Hi, I'm using the ListCellFragment and it's great. But I have a question, by default it uses the ListCell, but I can replace it with an external component such as the JFXListCell from JFoenix. Is there any way to do this?

Regards :smile:

**Comment by edvin** [comment]
No, unfortunately not. But if you're serious about using JFoenix with TornadoFX, you could create a small library that both provides builders for the components in JFoenix as well as make some modifications to SmartListCell to accomodate this :)

**Comment by TioCoding** [comment]
I understand, I thought there was some way to replace it, anyway I'm trying to modify the ListView.kt class but it gets a bit complicated. Any help on how to get the result I want?

**Comment by edvin** [comment]
You can copy the SmartListCell class and make it extend JFXListCell, then create your own `jfxFragment` builder that does the same as the default, but instantiates a JFXSmartListCell that you create :)

**Comment by TioCoding** [comment]
Hi, I almost made it, but I found a few problems. First this is what I did:
- Create my JFXListView class and copy the following 2 methods.
1. Modify JFXSmartListCell that extends from JFXListCell.
2. Modify cellFormat to jfxCellFragment
```
package com.clario.ClarioDesktopApp.util

import com.jfoenix.controls.JFXListCell
import javafx.collections.ObservableMap
import javafx.scene.control.ListCell
import javafx.scene.control.ListView
import javafx.util.Callback
import tornadofx.*
import kotlin.reflect.KClass

@Suppress("UNCHECKED_CAST")
open class JFXSmartListCell<T>(val scope: Scope = DefaultScope, listView: ListView<T>?, properties: Map<Any,Any>? = null) : JFXListCell<T>() {
    /**
     * A convenience constructor allowing to omit `listView` completely, if needed.
     */
    constructor(scope: Scope = DefaultScope, properties : Map<Any,Any>? = null) : this(scope, null, properties)

    private val smartProperties: ObservableMap<Any,Any> = listView?.properties ?: HashMap(properties.orEmpty()).observable()
    private val editSupport: (ListCell<T>.(EditEventType, T?) -> Unit)? get() = smartProperties["tornadofx.editSupport"] as (ListCell<T>.(EditEventType, T?) -> Unit)?
    private val cellFormat: (ListCell<T>.(T) -> Unit)? get() = smartProperties["tornadofx.cellFormat"] as (ListCell<T>.(T) -> Unit)?
    private val cellCache: ListCellCache<T>? get() = smartProperties["tornadofx.cellCache"] as ListCellCache<T>?
    private var cellFragment: ListCellFragment<T>? = null
    private var fresh = true

    init {
        if (listView != null) {
            properties?.let { listView.properties?.putAll(it) }
            listView.properties["tornadofx.cellFormatCapable"] = true
            listView.properties["tornadofx.cellCacheCapable"] = true
            listView.properties["tornadofx.editCapable"] = true
        }
        indexProperty().onChange {
            if (it == -1) clearCellFragment()
        }
    }

    override fun startEdit() {
        super.startEdit()
        editSupport?.invoke(this, EditEventType.StartEdit, null)
    }

    override fun commitEdit(newValue: T) {
        super.commitEdit(newValue)
        editSupport?.invoke(this, EditEventType.CommitEdit, newValue)
    }

    override fun cancelEdit() {
        super.cancelEdit()
        editSupport?.invoke(this, EditEventType.CancelEdit, null)
    }

    override fun updateItem(item: T, empty: Boolean) {
        super.updateItem(item, empty)

        if (item == null || empty) {
            textProperty().unbind()
            graphicProperty().unbind()
            text = null
            graphic = null
            clearCellFragment()
        } else {
//            FX.ignoreParentBuilder = FX.IgnoreParentBuilder.Once
            try {
                cellCache?.apply { graphic = getOrCreateNode(item) }
            } finally {
//                FX.ignoreParentBuilder = FX.IgnoreParentBuilder.No
            }
            if (fresh) {
                val cellFragmentType = smartProperties["tornadofx.cellFragment"] as KClass<ListCellFragment<T>>?
                cellFragment = if (cellFragmentType != null) find(cellFragmentType, scope) else null
                fresh = false
            }
            cellFragment?.apply {
                editingProperty.cleanBind(editingProperty())
                itemProperty.value = item
                cellProperty.value = this@JFXSmartListCell
                graphic = root
            }
            cellFormat?.invoke(this, item)
        }
    }

    private fun clearCellFragment() {
        cellFragment?.apply {
            cellProperty.value = null
            itemProperty.value = null
            editingProperty.unbind()
            editingProperty.value = false
        }
    }

}

fun <T, F : ListCellFragment<T>> ListView<T>.jfxCellFragment(scope: Scope = DefaultScope, fragment: KClass<F>) {
    properties["tornadofx.cellFragment"] = fragment
    if (properties["tornadofx.cellFormatCapable"] != true)
        cellFactory = Callback { JFXSmartListCell(scope, it) }
}

```

- The first error here is that in the line "FX.ignoreParentBuilder = FX.IgnoreParentBuilder.Once" gives error (Can not access' ignoreParentBuilder ': it is internal in' Companion), for that I have commented.

Now when I try to use it, it forces me to enter the Scope parameter, which seems strange to me because one is already assigned to it.

![screenshot at 2017-11-17 18_52_35-iloveimg-cropped](https://user-images.githubusercontent.com/22163898/32974211-63e90a10-cbca-11e7-9be3-5f73592e771c.png)

In the end just to try the step the same parameter that is "DefaultScope" just to test and this is the result I have

`jfxCellFragment(DefaultScope,ClienteItemFragment::class)`

And my final result is this:

![screenshot at 2017-11-17 18_54_37-iloveimg-cropped](https://user-images.githubusercontent.com/22163898/32974224-881f2cfc-cbca-11e7-8806-b63d7ac6d98d.png)

![screenshot at 2017-11-17 18_54_51-iloveimg-cropped](https://user-images.githubusercontent.com/22163898/32974229-8e7a4f28-cbca-11e7-966f-af552a0570ed.png)

![screenshot at 2017-11-17 18_54_56-iloveimg-cropped](https://user-images.githubusercontent.com/22163898/32974234-91678782-cbca-11e7-9971-cf4aa6bcb41c.png)

Print me to the method toString(), what am I doing wrong?

**Comment by TioCoding** [comment]
For the moment I'm going to use the one I have by default. in the future I will try if I can resolve the compatibility with JFoenix, anyway thanks for the help :grin:
