### ISSUE TITLE
Approach of DataClass, ClassProperties and Class ItemViewModel

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#542]
Hi, I would like to know if the approach I am using is correct when using these classes.

I have my classes that I use to send and receive data, which at the same time is my business logic, i have them declared in a data class: 

```
data class Client(val id: Int? = null, val name: String? = null, val username: String? = null)
```

The second class that I have, is one where all the attributes are but with properties, this is the one used to display the values ​​on the screen:

```
class ClientItem(client: Client) {

    var id by property(client.id)
    fun idProperty() = getProperty(ClientItem::id)

    var name by property(client.name)
    fun nameProperty() = getProperty(ClientItem::name)

    var username by property(client.username)
    fun usernameProperty() = getProperty(ClientItem::username)
}
```

And finally I have the extending class of ItemViewModel

```
class ClientItemModel : ItemViewModel<ClientItem>() {
   val id = bind { item?.idProperty() }
   val name = bind { item?.nameProperty() }
   val username = bind { item?.usernameProperty() }
}
```

(And if I need to use ListCellFragment, I have to create another class)

```
class ClientItemModelFragment(property: ObjectProperty<ClientItem>) : ItemViewModel<ClientItem>(itemProperty = property) {
   val id = bind { item?.idProperty() }
   val name = bind { item?.nameProperty() }
}
```

Now my question is this. This approach that I have is correct? I'm doing good or bad, some advice to improve it. 
Thank you very much

**Comment by edvin** [comment]
I'm not sure why you want both a Client and a ClientItem - why not combine them?

In any case, you should use the new property syntax and binding syntax as described in the guide. Where did you see this syntax? If we still have docs describing this syntax we should really update :)

Properties are defined like this:

```kotlin
val idProperty = SimpleIntegerProperty()
var id by idProperty
```

Bindings are defined like this:

```kotlin
val id = bind(Client::idProperty)
```

**Comment by TioCoding** [comment]
Well, you can choose to declare it in a "Data Class", and be able to take advantage of its methods like the "copy ()" method. But I think it's better to combine it and avoid creating more classes. About the code I was guided by the documentation and examples of tornadofx-samples. Now the rest, ClientItemModel and ClientItemModelFragment are correct?

Try only to use ClientItemModelFragment () but I need to pass a property as parameter to the constructor, and that's why I can not inject it.

**Comment by TioCoding** [comment]
I am looking at the examples of tornadoFx, and I would like to know what is the difference between these two cases: 

First case:
`data class Category(val title: String, val index: Int)`

```
class CategoryView : View() {
    override val root = tableview<Category> {
        column("title", Category::title).weigthedWidth(1.0)
        column("index", Category::index).weigthedWidth(4.0)
        columnResizePolicy = SmartResize.POLICY
    }
}
```
Second case:

```
class Category{
    val titleProperty  = SimpleStringProperty()
    var title by titleProperty

    val indexProperty  = SimpleIntegerProperty()
    var index by indexProperty
}
```
```
class CategoryView : View() {
    override val root = tableview<Category> {
        column("title", Category::titleProperty).weigthedWidth(1.0)
        column("index", Category::indexProperty).weigthedWidth(4.0)
        columnResizePolicy = SmartResize.POLICY
    }
}
```
I have seen several examples where they use the two types of implementation. What is the difference between the two? in one that uses properties of attributes and the other where it does not use it (a pure DataClass). When to use the properties? In what cases are they necessary? Thank you

**Comment by edvin** [comment]
The data class is an immutable structure, good for passing stuff around, not so good for manipulating it in a UI. If I create a domain class that is meant to be manipulated from a UI, I always go with the properties. It also makes the ItemViewModel approach much easier, as I don't have to manually override `onCommit` and construct and assign a new instance to `item`.

The property approach also makes sure that changes to your domain objects are automatically reflected in UI elements like the TableView in your example above.

**Comment by TioCoding** [comment]
Thanks for the reply, I am trying to create a class with your recommendation, but I have an error that is this:

![captura de pantalla de 2017-11-19 20-38-24](https://user-images.githubusercontent.com/22163898/32998514-cfd6d1ee-cd69-11e7-8289-8cc708032a8e.png)

What is causing the error?

**Comment by TioCoding** [comment]
I had to import "import tornadofx. *". Thanks for the help and its recommendations :+1:
