### ISSUE TITLE
Chart Builders

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#55]
I may take this one but I'll probably save it for a future release. 

It may be helpful to create builders for [JavaFX Charts](https://docs.oracle.com/javase/8/javafx/user-interface-tutorial/charts.htm).

![](https://docs.oracle.com/javase/8/javafx/user-interface-tutorial/img/pie-fruits.png)

I think it may have some similarities with how `TreeView` and `TreeTableView` were handled, but it should not be as hard.

**Comment by edvin** [comment]
Very good initiative @thomasnield ! We'll target this for 1.4.1 then.

**Comment by thomasnield** [comment]
Sounds good. I will need this for applications at work so I will hopefully do this fairly quickly in the next week or two.

**Comment by edvin** [comment]
Perfect. I find myself avoiding charts because it's a bit cumbersome in the JavaFX API. The implementation is sound, but it's all a bit verbose. We'll make this a slick addition to TornadoFX :)

**Comment by thomasnield** [comment]
Absolutely. If the verbosity of `TreeView` and `TreeTableView` were tamed in TornadoFX, we can certainly handle the charts.

**Comment by edvin** [comment]
I added a PieChart builder to `Charts.kt' (for now until we decide on (https://github.com/edvin/tornadofx/issues/57)). To create the exact chart for the image above you would write:

```kotlin
piechart("Imported Fruits") {
    data("Grapefruit", 12.0)
    data("Oranges", 25.0)
    data("Plums", 10.0)
    data("Pears", 22.0)
    data("Apples", 30.0)
}
```

It's also possible to manipulate a node for a given data item in two ways. Firstly, `data()` returns the `PieChart.Data` item, and the `data()` function also takes an optional operation as it's third argument:

```kotlin
data("Apples", 30.0) {
    node.addEventHandler(MOUSE_PRESSED) {
        // Do something with the Apples node on key press
    }
}
```

Populating the data from a `Map<String, Double` is also possible:

```kotlin
val data = mapOf(
    "Grapefruit" to 12.0,
    "Oranges" to 25.0,
    "Plums" to 10.0,
    "Pears" to 22.0,
    "Apples" to 30.0
)

piechart(title) {
    data(data)
}
```

**Comment by edvin** [comment]
Added LineChart builder as well. Since most of the other Charts extend XYChart, the work done here completes most of the work for the other supported charts. Now it's mostly a matter of adding the rest of the builders that instantiates the different chart types, and looking for other ways to improve the API. To create the first chart in the [JavaFX LineChart tutorial](https://docs.oracle.com/javase/8/javafx/user-interface-tutorial/line-chart.htm)  you would do:

```kotlin
linechart("Stock Monitoring, 2010", NumberAxis(), NumberAxis()) {
    series("My portfolio") {
        data(1, 23)
        data(2, 14)
        data(3, 15)
        data(4, 24)
        data(5, 34)
        data(6, 36)
        data(7, 22)
        data(8, 45)
        data(9, 43)
        data(10, 17)
        data(11, 29)
        data(12, 25)
    }
}
```

**Comment by edvin** [comment]
Hmm.. adding multiple series is done easily like this:

```kotlin
    series("Portfolio 1") {
        data(1, 23)
        data(2, 14)
        data(3, 15)
        data(4, 24)
        data(5, 34)
        data(6, 36)
        data(7, 22)
        data(8, 45)
        data(9, 43)
        data(10, 17)
        data(11, 29)
        data(12, 25)
    }
    series("Portfolio 2") {
        data(1, 10)
        data(2, 5)
        data(3, 8)
        data(4, 74)
        data(5, 50)
        data(6, 40)
        data(7, 60)
        data(8, 55)
        data(9, 40)
        data(10, 56)
        data(11, 59)
        data(12, 90)
    }
```

Even though it is easy, and not much boiler plate, there must be a better way to add multiple series in one go... Let's see what we can do...

**Comment by edvin** [comment]
I think I found a good way. Implemented a small helper class called `Multiseries` and a wrapper, so now you can write:

```kotlin
multiseries("Portfolio 1", "Portfolio 2") {
    data(1, 23, 10)
    data(2, 14, 5)
    data(3, 15, 8)
    ...
}
```

**Comment by edvin** [comment]
Also added builders for AreaChart, BubbleChart, ScatterChart, BarChart and StackedBarChart.

Let me know how this works for you @thomasnield !

**Comment by thomasnield** [comment]
Nice! I did not anticipate this would get done so quickly. Alright, ill check it out today.

**Comment by edvin** [comment]
I added [documentation](https://github.com/edvin/tornadofx/wiki/Charts) as well.

**Comment by thomasnield** [comment]
I like this, really elegant especially with multi-series.

![seal_of_approval](https://cloud.githubusercontent.com/assets/7420801/14065943/9c90c3c2-f402-11e5-9c4e-41d447be505a.jpg)

**Comment by thomasnield** [comment]
One question. In your documentation, for example consistency be:

```kotlin
 multiseries("Portfolio 1", "Portfolio 2") {
                    data("Jan", 23, 10)
                    data("Feb", 14, 5)
                    data("Mar", 15, 8)
}
```

**Comment by edvin** [comment]
Nicely spotted, fixed :)

**Comment by thomasnield** [comment]
Okay awesome, I haven't tested anything beyond the pie chart and bar series, but this is cool. It takes so little code. We should try to release this asap too in my opinion.

**Comment by edvin** [comment]
Indeed! We can push 1.4.1 with the chart feature once you are satisfied with it. Nice seal btw :) Hehe

**Comment by thomasnield** [comment]
haha yes, my "seal of approval". It rendered too large hence why I removed it. But I got it resized.

![seal_of_approval](https://cloud.githubusercontent.com/assets/7420801/14066040/ae517a54-f405-11e5-9782-bdec9dac9b7b.jpg)
