### ISSUE TITLE
ItemViewModel for insert and update object in one View

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#552]
Hi, I'm using the ItemViewModel and I have a problem, i have a view where I can enter new objects, and modify the ones that are on my list.
At the beginning, if the first thing I do is try to enter a new object it works perfectly, but if I select an item from my listView, and then try to register a new object, it returns the attributes null.

This is my implementation that I have of my model:
```
class CargoModel : ItemViewModel<Cargo>(Cargo()) {
    val id = bind(Cargo::idProperty)
    val inicial = bind { item?.nombre?.get(0).toProperty() }
    val nombre = bind(Cargo::nombreProperty)
    val descripcion = bind(Cargo::descripcionProperty)
}
```
added in the constructor an instance of Cargo(), to be able to enter a new object of a form.
But I also need the object to be able to modify a selected object.

Inject my ItemViewModel:
`private val cargoModel: CargoModel by inject()`

and in my listView

```
this += JFXListView<Cargo>().apply {
      mListViewCargo = this
      cellFragment(CargoItemFragment::class)
      filterListCargo.bindTo(this)
      items = filterListCargo
      bindSelected(cargoModel) //Bind Selection
}
```
The problem arises when I select a ListView element and then clean the selection with `mListViewCargo.selectionModel.clearSelection()`. I delete the selection to enter a new record, but at the time of making the confirmation, the values of the object throws me null.

How could I adapt my ItemViewModel to register new objects and also modify them?

**Comment by edvin** [comment]
You should create a new scope and put a copy of the viewmodel to be edited in that scope so that it doesn't interfere with the `bindSelected` changes:

```kotlin
action {
    val newScope = Scope(CargoModel(cargoModel.item))
    find<YourEditor>(newScope).openWindow()
}
```

**Comment by TioCoding** [comment]
Thanks for the reply, but my View does not use dialogs. 
In a view, I have the list along with my form, since I can press a button (My add new button), my `CargoModel` object, create a new scope, and if I press another button to cancel (Button to cancel adding a new operation) return to its previous state and bindSelected work normally.

**Comment by edvin** [comment]
The concept is the same, just create a single extra scope for the form view and set the item of the ViewModel instead of finding and opening a new window. Remember to find the form view in that separate scope.

**Comment by TioCoding** [comment]
i'm try this:
```
vbox{
  hbox {
    add(CargoListItemScreen::class)
    add(find<CargoFormScreen>(Scope(CargoModel()))) // new scope
  }
  hbox {
    button("add")
    button("cancel")
    button("edit")
  }
}
```
But the bindSelection of my listView, stops working.

**Comment by TioCoding** [comment]
This is my class CargoListItemScreen

```
private val cargoModel: CargoModel by inject()

stackpane {
       this += JFXListView<Cargo>().apply {
          mListViewCargo = this
          cellFragment(CargoItemFragment::class)
          bindSelected(cargoModel) // BindSelected
      }
}
```
And this is my class CargoFormScreen

```
private val cargoModel: CargoModel by inject()


fieldset("Informacion del cargo") {
                field {
                    this += JFXTextField().apply {
                        promptText = "Nombre"
                        isLabelFloat = true
                        bind(cargoModel.nombre)
                    }
                }
                field {
                    this += JFXTextArea().apply {
                        promptText = "Detalle"
                        isLabelFloat = true
                        bind(cargoModel.descripcion)
                       }
                 }
}

```

**Comment by TioCoding** [comment]
There will not be an example, where you can enter new records and also modify them in the same form?

**Comment by TioCoding** [comment]
I found a solution, but I do not know if it is the best. I explain the solution to have an answer and recommendation. More than anything to know if the approach is correct

I inject two models in my form view, then i create two methods :

```
val cargoModelPlus: CargoModel by inject(Scope(CargoModel())) //To add an object
val cargoModelEdit: CargoModel by inject() //To edit an object

.
.
.
// If my view is in the edit state
fun fieldEditFormat(){
        txtNombre.bind(cargoModelEdit.nombre)
        txtDescripcion.bind(cargoModelEdit.descripcion)
}
// If my view is in the add state
fun fieldPlusFormat(){
        txtNombre.bind(cargoModelPlus.nombre)
        txtDescripcion.bind(cargoModelPlus.descripcion)
}
```
Finally, 
- Execute the method `fieldEditFormat()` if I want to edit some record and commit my object `cargoModelEdit`, 
- Execute the `fieldPlusFormat()` method if I want to add a new record and confirm my `cargoModelPlus` object,

If there is something wrong, please let me know Thank you.

**Comment by TioCoding** [comment]
I am solving this problem by creating 2 instances of ViewModel, anyway I would like to know if there is another better solution.

#555

**Comment by edvin** [comment]
That's not half bad actually, just creating a new scope while you inject it. You don't need to instantiate the ViewModel though, it will be instantiated by the framework when needed in the new scope.

**Comment by osmaymoya** [comment]
Hi, I try to do it in an example project but not work.
My MainView




`class MainView : View("Hello TornadoFX") {
    companion object {
        val logger: Logger = LoggerFactory.getLogger(MainView::class.java)
    }
    private val controller : MainController by di()
    private lateinit var table: TableView<Users>
    private val model : UsersModel by di()
    override val root = vbox {
            gridpane{
                row{
                    label("USUARIOS") {
                        gridpaneConstraints {
                            marginTopBottom(5.0)
                            marginLeftRight(5.0)
                        }
                    }
                    button("Nuevo") {
                        gridpaneConstraints {
                            marginTopBottom(5.0)
                            marginLeftRight(5.0)
                        }
                        action {
                            //logger.info("${model.item?.id ?: "nulo"}")
                            val newScope = Scope(UsersModel())
                            find(UserNewEdit::class, newScope).openWindow()
                            table.items.setAll(controller.getUsers())
                        }
                    }
                }
                row {
                    table = tableview (controller.getUsers()) {
                        title = "Usuarios"
                        useMaxWidth = true
                        gridpaneConstraints {
                            marginTopBottom(5.0)
                            marginLeftRight(5.0)
                            columnSpan = 2
                        }
                        column("ID", Users::id)
                        column("Usuario", Users::username)
                        column("Nombre", Users::name)
                        column("Apellido", Users::lastname)
                        column("Estado", Users::active).cellFormat {
                            style {
                                if (it) {
                                    text = "Activo"
                                    textFill = javafx.scene.paint.Color.GREEN
                                } else {
                                    text = "Inactivo"
                                    textFill = javafx.scene.paint.Color.RED
                                }
                            }
                        }
                        contextmenu {
                            item("Editar").action {
                                logger.info("Editando Usuario (Id=${model.id.value})")
                                find(UserNewEdit::class).openWindow()
                                table.items.setAll(controller.getUsers())
                            }
                        }
                        // Update the person inside the view model on selection change
                        bindSelected(model)
                    }
                }
            }
    }
}
`
My UserNewEdit
`
class UserNewEdit : View("Datos de Usuario") {
    companion object {
        val logger: Logger = LoggerFactory.getLogger(UserNewEdit::class.java)
    }
    private val model : UsersModel by di()
    private val controller : MainController by di()
    override val root = form{
        fieldset{
            hbox {
                label("Usuario:")
                textfield(model.username)
            }
            hbox {
                label("Nombre:")
                textfield(model.name)
            }
            hbox {
                label("Apellido:")
                textfield(model.lastname)
            }
            hbox {
                checkbox("Estado")
            }
        }
        hbox {
            button("Salvar"){
                enableWhen(model.dirty)
                action{
                    model.commit()
                    controller.saveUser(model)
                    close()
                }
                //

            }
            button("Cancelar"){
                action{
                    logger.info("Model.id = ${model.id.value}")
                    close()
                }
            }
        }
    }
}`

Note: I use Spring to inject.
