### ISSUE TITLE
Use custom classloader for loading ResourceBundle

### ISSUE THREAD

**Issue by ClockVapor** [edvin/tornadofx#553]
I'm integrating a TornadoFX app into an existing application via OSGi, but in a custom way that doesn't follow [this guide](https://github.com/edvin/tornadofx/wiki/OSGi). Doing this causes classloader issues with loading resources, but I am able to work around that by doing this to use the OSGi classloader: `Thread.currentThread().contextClassLoader = javaClass.classLoader`

However, this doesn't work for getting `Component.messages` because the resulting `ResourceBundle.getBundle()` call uses `getLoader(Reflection.getCallerClass())` to get an incorrect classloader, and so it doesn't find my `View`'s corresponding `.properties` file.

Is there a better way for me to do this, or, if not, could a way to specify a custom classloader to load `Component.messages` be implemented?

**Comment by edvin** [comment]
I've made a change so that the bundle is fetched using the class loader that defined the Component subclass. Can you try with tornadofx-1.7.13-SNAPSHOT and see if it works correctly now?

**Comment by ClockVapor** [comment]
Yep, works perfectly! Thanks for the quick reply and fix!

**Comment by edvin** [comment]
Great :))
