### ISSUE TITLE
How to inject two ItemViewModel of the same type

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#555]
Hello, how could I do if I want to inject two ItemViewModel of the same type in a view, but differentiate them by name:

My ItemViewModel class:
```
class ItemModel : ItemViewModel<Item>(Item()) {
    val id = bind(Item::idProperty)
    val nombre = bind(Item::nombreProperty)
}
```
My View class:
```
val itemModelFirst: ItemModel by inject()
val itemModelSecond: ItemModel by inject()
```
My Controller class:
```
val itemModelFirst: ItemModel by inject() //They are the same object
val itemModelSecond: ItemModel by inject() //They are the same object
```

**Comment by edvin** [comment]
There can only be one instance of a ViewModel in a single scope. What you can do is create a Controller or a third ViewModel that holds the two other instances. Does that make sense?

**Comment by TioCoding** [comment]
Could you make an example to understand it better?

**Comment by edvin** [comment]
It would be something like:

```kotlin
class State : ViewModel() {
    val first = ItemModel()
    val second = ItemModel()
}
```

Then you simply inject the `State` component and you have access to two models of the same type.

**Comment by nimakro** [comment]
@TioCoding Did this solve your problem? Will close for now feel free to reopen if you have further questions regarding the issue. You can also join our [slack](https://kotlinlang.slack.com/?redir=%2Fmessages%2Ftornadofx) channel for quick questions.
