### ISSUE TITLE
OnDragDropped does not work!

### ISSUE THREAD

**Issue by mourabraz** [edvin/tornadofx#556]
Hello! I need some help with a test of Drag and Drop implementation. I have looked for solution in all places but unsuccessfully. 

I believe there are some problems in tornadoFX because the events OnDragEntered and OnDragExited works fine but not the OnDragDropped.  

My code is:

```
           text("DROP HERE") {
                setOnDragEntered { event ->
                    println("setOnDragEntered")
                }
                setOnDragDropped { event ->
                    println("onDragDropped")
                }

                setOnDragExited { event ->
                    println("setOnDragExited")
                }
            }
```

println("setOnDragEntered") and println("setOnDragExited") works fine but the println("onDragDropped") never happens.

I am new in tornadoFX and Kotlin and my english is ugly (I know). Please give some help to make the dropped event works.

Thanks a lot...

**Comment by edvin** [comment]
This has nothing to do with TornadoFX, just wrong usage of the drag/drop events. Here is a complete application that allows you to drag text and drop it on the text component (just on the text component though)

```kotlin
class DNDApp : App(DNDView::class)

class DNDView : View() {

    override val root = stackpane {
        paddingAll = 200
        
        text("DROP HERE") {
            setOnDragOver { event ->
                if (event.dragboard.hasString())
                    event.acceptTransferModes(*event.dragboard.transferModes.toTypedArray())
                event.consume()
            }
            setOnDragDropped { event ->
                text = event.dragboard.string
                event.isDropCompleted = true
                event.consume()
            }
        }
    }
}
```

Bottom line: You need to accept the transfer in the `onDragOver` callback.

**Comment by mourabraz** [comment]
Dear edvin... you are amazing!

You did a spectacular job with tornadoFX and You still help with simple things. I hope someday I can help you too. 

Thank you so much.

**Comment by edvin** [comment]
Thank you, that means a lot :)
