### ISSUE TITLE
TableView column boolean field detection

### ISSUE THREAD

**Issue by LAP2** [edvin/tornadofx#560]
Hi.

I just tried to build table view from java pojo bean with boolean field and default bool getter naming with is
`... = tableview(model.list) {
    column(...) // <= this one is ok cause it getter name with get
    column("My bool", MyClass::isSomethingBoolean)
}
`
and i got an empty column cause you try to extract field name like this:

> `@JvmName("pojoColumn") fun <S, T> TableView<S>.column(title: String, getter: KFunction<T>): TableColumn<S, T> {
    val propName = getter.name.substring(3).let { it.first().toLowerCase() + it.substring(1) }
    return this.column(title, propName)
}`

and for "is" getters it wouldn't work fine.
I had avoid it by using field naming column function like
`code("My bool", "somethingBoolean")` but the work of previous variant isn't look right.

**Comment by edvin** [comment]
This should be easily solved by checking if the getter.name starts with "is" followed by an upper case letter.

**Comment by LAP2** [comment]
Yep probably, could you just lable this issue like a bug or something?

**Comment by edvin** [comment]
Done. I asked if somebody wanted to supply a PR for this in the Slack channel. If nobody has time, I'll add it during the next days :)

**Comment by LAP2** [comment]
Deal. Many thx.

**Comment by edvin** [comment]
I added the following check to determine the property name:

```kotlin
val startIndex = if (getter.name.startsWith("is") && getter.name[2].isUpperCase()) 2 else 3
val propName = getter.name.substring(startIndex).decapitalize()
```

**Comment by LAP2** [comment]
Cool. Thx Edvin. Probably this issue could be closed now.

**Comment by edvin** [comment]
Thanks :) Did it work for you?

**Comment by LAP2** [comment]
Yep. I had checked it, from snapshot build. It seems to work fine.
