### ISSUE TITLE
UTF-8 property files are not supported when working with ResourceBundle

### ISSUE THREAD

**Issue by Romanow88** [edvin/tornadofx#565]
I know that this is Java's standard behavior as described in ```java.util.Properties#load(java.io.InputStream)```. But seeing that TornadoFX already uses a specific control (FXResourceBundleControl) for the purpose of loading the FX.messages - it would be nice to support UTF-8 property file format. 

It's actually easy to do under the hood, it's a one line change in Messages.kt:42

```
                }?.use { FXPropertyResourceBundle(InputStreamReader(it, StandardCharsets.UTF_8)) }
```

I can submit a pull request for that, but IDK if having this behavior as the default is OK with you guys, or do you want to have it configurable. And if the latter - how does one configure it? A prop on the FX class?

**Comment by edvin** [comment]
Let's make it the default :) PR is most welcome.

**Comment by Romanow88** [comment]
@edvin any idea when the next version will be available via maven? If it's close - would save me a hassle of deploying a self built jar to artifactory.

**Comment by edvin** [comment]
We publish snapshots to oss.sonatype.org every day - I'll push this right now, so just include sonatype as as snapshot repo in your build and reference tornadofx-1.7.14-SNAPSHOT and you should be good to go. There is an example of how to do this in the README file :)

**Comment by dominiwe** [comment]
I ran into this problem when trying out [internationalization](https://docs.tornadofx.io/0_subsection-1/internationalization) and XML files don't seem to be supported. I'm not sure if it is handled differently under the hood but the `messages["someUtf8Prop"]` pattern ends up not displaying certain characters correctly.

**Comment by Romanow88** [comment]
@dominiwe Edvin marked the project as not maintained some time ago. Your best option is to either search for a different library or fork and fix yourself.

For what it's worth, internationalization works for us with directly accessing `messages["someProp"]`. Check that the bundle `.property` files are `UTF-8` encoded.

**Comment by dominiwe** [comment]
Thank you for the quick reply @Romanow88 
I'm sorry for bumping an old issue, thank you for clarifying that the project is unmaintained. My school unfortunately forced me to use it.

For anyone coming across the issue, here is how I changed the encoding of my file:

```bash
# check encoding
file -bi Messages_es.properties
# text/plain; charset=iso-8859-1

# change encoding
iconv -f ISO-8859-1 -t UTF-8//TRANSLIT Messages_es.properties -o Messages_es.properties
```

Do not edit the file with the Intellij IDEA though.
