### ISSUE TITLE
ItemViewModel: after model.commit() yields "model.item" = null ???

### ISSUE THREAD

**Issue by Yadarma** [edvin/tornadofx#567]
Dear Edvin, I tried the following code but the item is always null and not set
Model.kt
```
data class User(val username: String, val password: String)

class UserModel : ItemViewModel<User>() {
    val username =bind{item?.username?.toProperty()}
    val password = bind{item?.password?.toProperty()}
}
```
View.kt
```
 form {
            fieldset("Enter your credentials", FontAwesomeIconView(FontAwesomeIcon.USER)) {
                field("Login ID") {
                    textfield(model.username).required()
                }
                field("Password") {
                    passwordfield(model.password).required()
                }
            }
            button("Login") {
                action {
                    model.commit()
           ***    val user = model.item
                    if (user == null) {
                        println("it's NULL")
                    }
                }
                enableWhen(model.valid)
            }
        }
```

Could you help me explaining why "***" line always null ????? Thanks!

**Comment by edvin** [comment]
You need to assign something to the ViewModel's `item` property. Since you're using an immutable data class, there is no way to update it, so you have to override `onCommit` of the ViewModel and create a new User, populated with the values from the facade properties in the ViewModel. Also note that you're using outdated syntax for binding. Here is a working ViewModel:

```kotlin
data class User(val username: String, val password: String)

class UserModel : ItemViewModel<User>() {
    val username = bind(User::username)
    val password = bind(User::password)

    override fun onCommit() {
        item = User(username.value, password.value)
    }
}
```

**Comment by Yadarma** [comment]
It worked like charm. Thanks till the end of world dude!
If I changed the data class fields to "var", I still have to override "onCommit" ????
In your video and wiki tutorials you never "override onCommit()"
Thanks again so much

**Comment by edvin** [comment]
My pleasure. The reason I never need to override onCommit is that I bind against an object with observable values (javafx properties if you will). I also set an item into the ViewModel at one stage. This item will then be updated with the properties from the ViewModel on commit, so the item stays the same, but the values change.

**Comment by Yadarma** [comment]
Thanks for the enlightenment  👍
