### ISSUE TITLE
Temporarily disable the bindSelected(...) of the ListView

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#569]
Hello, I would like to know how I can temporarily disable the bindSelected(model), so that it does not automatically pass the data to my TextFields. 
I like the functionality of `bindSelected(model)`, but my form is sometimes in a state to save a new object, and when I select my "listView", I change the data to the selected object.
I tried to change the `txtName.bind(model.name)` property of the TextFields when I want to save a new object, but it still changes the values of my TextFields.
For example:
If I want to save a new object:
```
fun statusSave(){
     txtName.bind(modelAction.plus.name) // I execute it only when I want to save a new object
}
```
If I want to edit an existing object:
```
fun statusEdit(){
     txtName.bind(modelAction.edit.name) // This is by default when you start the form
}
```
Any help, to solve this problem?

Thank you.

**Comment by TioCoding** [comment]
I have an instance of ViewModel, where inside I have two instances of my Model

```
class ClienteItemModelAction : ViewModel() {
    val plus = ClienteItemModel(SimpleObjectProperty<Cliente>(Cliente()))
    val edit = ClienteItemModel(SimpleObjectProperty<Cliente>())
}
```
And my listview is related to the edit instance:

```
private val clienteModel : ClienteItemModelAction by inject()
.
.
.
listView(){
    bindSelected(clienteModel.edit)
}

```

**Comment by edvin** [comment]
Instead of using bindSelected, listen to the selectionModel.selectedItemProperty and update the model.item with that value only when it suits you.

**Comment by TioCoding** [comment]
Thanks for the response, this helped me solve my problem. :+1:

**Comment by edvin** [comment]
Good to hear :)
