### ISSUE TITLE
Due to how kotlin handles nullability in extracting return for a where clause - a kotlin null pointer may happen in Resource bundle loading

### ISSUE THREAD

**Issue by Romanow88** [edvin/tornadofx#571]
Offender - FXResourceBundleControl:36. We return null here but the return type of the method is ResourceBundle, which is not nullable. This will cause a kotlin.KotlinNullPointerException when returning a null value. I know that this is a minor issue but it caused me a bunch of pain and hunting for the actual reason that the bundle was not loading. 

I will submit a PR with a fix.

**Comment by edvin** [comment]
Good call, thanks - awaiting the PR.
