### ISSUE TITLE
Hot reload issue

### ISSUE THREAD

**Issue by kibarms** [edvin/tornadofx#576]
I'm applied [this video](https://www.youtube.com/watch?v=HbPngSnvaWQ) step by step on my example project but I could not apply this features in my project. 

> I'm installed TornadoFX Intellij Idea plugin (1.7.14)

```
fun main(args: Array<String>) = Application.launch(App::class.java, *args)
class App : tornadofx.App() {
    
    override val primaryView: KClass<out UIComponent>
            = MainView::class
    
    override fun createPrimaryScene(view: UIComponent)
            = Scene(view.root, 613, 353)
            .apply {
                FX.primaryStage.centerOnScreen()
                FX.primaryStage.icons.add(0, Image(File(DIR_UI.path + "\\logo.png").toURI().toString()))
            }
    
    init {
        reloadViewsOnFocus()
        reloadStylesheetsOnFocus()
    }
    
}

class MainView : View(MAIN_TITLE) {
    val loadingProperty = SimpleBooleanProperty(true)
    val loading by loadingProperty
    
    override val root = pane {
        style { stylesheets += MAIN_STYLE }
        
        borderpane {
            fitToParentSize()
            
            center {
                vbox {
                    alignment = Pos.CENTER
                    spacing   = 30.0
                    progressbar {
                        val (sW, sH) = getScreenSize()
                        setPrefSize(sW / 2, sH / 10)
                        visibleWhen { loadingProperty }
                        effect = DropShadow(10.0, 1.0, 1.0, Color.BLACK).apply { input = Reflection() }
                    }
                    label { text = "Loading..." }
                }
            }
        }
    }
}
```

**Another problem is when I was use `TornadoFX` library then `Intellij Idea` starts getting laggy.  I've tried the invalide caches etc. (I've tried this library intellij idea v2016.3.2 and v2017.3.2) Any idea?** 

```
Ara 23, 2017 2:06:16 AM tornadofx.FX$Companion replaceComponent
INFO: Reloaded [Scene] presenter.MainView@b871173
Ara 23, 2017 2:06:22 AM tornadofx.FX$Companion replaceComponent
INFO: Reloaded [Scene] presenter.MainView@1475ed25
Ara 23, 2017 2:06:38 AM tornadofx.FX$Companion replaceComponent
INFO: Reloaded [Scene] presenter.MainView@6b150b99
```
> Tornadofx 1.7.14
> Kotlin 1.2.10
> IntelliJ IDEA 2017.3.2
> Build #IU-173.4127.17, built on December 19, 2017
> JRE: 1.8.0_152-release-1024-b8 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

**Comment by edvin** [comment]
What do you mean by "it doesn't work"? What are you trying to achieve, and what happens when you run the app?

You can't use `getScreenSize()` in the initialization of your View, since the scene isn't attached at this point. You could however override `onDock` and perform the calculations there.

**Comment by kibarmusti** [comment]
Sorry for my due to insufficient narration. `getScreenSize()` is my project static method for get os window screen size. I forget to add details here and that method run away the my eye. 
I will check again after you say thank you 👍
