### ISSUE TITLE
Pattern matching on Observable<String>

### ISSUE THREAD

**Issue by VarunBarad** [edvin/tornadofx#579]
I think it would be really nice to provide a Regex pattern matching on `TextField`s `textProperty`.

The code implementation of this would be very simple. I think something like below should work fine.

```kotlin
fun ObservableValue<String>.matches(pattern: Regex): BooleanBinding {
    return booleanBinding {
        it?.matches(pattern) ?: false
    }
}
```

**Comment by edvin** [comment]
That sounds useful indeed. Do you want to supply a PR perhaps?

**Comment by ronsmits** [comment]
If this is for `TextField` mainly then maybe the new `filterInput` would help?

```
field("sys") { textfield(entry.sys) {
 filterInput { it.controlNewText.isInt() && it.controlNewText.toInt() < 255 } 
} }
```

**Comment by VarunBarad** [comment]
@ronsmits This can be used anyplace where an `ObservableValue<String>` is involved. `TextField` was the place where I happened to need it.

**Comment by VarunBarad** [comment]
@edvin I definitely would like to supply a PR. Is it ok if I do it in a day or two?

**Comment by edvin** [comment]
@VarunBarad Absolutely, no rush :)

**Comment by VarunBarad** [comment]
@edvin I have forked and made the changes in my fork. Which branch should I send the PR to?

**Comment by edvin** [comment]
Great! Straight to main :)

**Comment by VarunBarad** [comment]
Done. Thanks for bearing the delay. 🙏

**Comment by edvin** [comment]
Merged! Thank you :)
