### ISSUE TITLE
Tooltip Builders

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#58]
Very minor, and primarily documenting for when I get around to it. We might want a add a Tooltip builder to Node.

http://docs.oracle.com/javafx/2/ui_controls/tooltip.htm

I'm curious if there is a way to streamline a "ToolTip" containing a Node, although I am sure there is q dialog in some form that does this...

**Comment by thomasnield** [comment]
Okay got it. 

```kotlin
button("Press me") {
    tooltip("Press this button")
}
```

**Comment by edvin** [comment]
Perfect! Release is under way. Could you add an example to the builders docs?

**Comment by thomasnield** [comment]
For sure. Haha you're right we are definitely going to need to make an ebook.

Sent from my Windows Phone
________________________________

**Comment by edvin** [comment]
Yeah, maybe we should start working on an outline for that soon :)

**Comment by thomasnield** [comment]
If you need help let me know.
________________________________

**Comment by thomasnield** [comment]
If you want to create the repository I can go ahead and start fleshing it out a little bit.

Sent from my Windows Phone
________________________________
From: Thomas Nield<mailto:thomasnield@live.com>
Sent: ‎3/‎28/‎2016 9:43 AM
To: edvin/tornadofx<mailto:reply@reply.github.com>; edvin/tornadofx<mailto:tornadofx@noreply.github.com>
Subject: RE: [tornadofx] Tooltip Builders (#58)

If you need help let me know.
________________________________

**Comment by edvin** [comment]
That would be perfect! I'm emailing you since it's a bit off topic for that thread :) What should we call it? tornadofx-book?

-- 
Med vennlig hilsen

Edvin Syse
Utvikler
SYSE AS

T: +4733349700
W: https://www.syse.no/

**Comment by thomasnield** [comment]
It might be a good idea to license it correctly in case we decide to self publish later as a book. We should structure as both a reference as well as an example oriented guide. We can even document patterns such as interoperating with RxJavaFX and ReactFX.
________________________________
From: Thomas Nield<mailto:thomasnield@live.com>
Sent: ‎3/‎28/‎2016 9:45 AM
To: Thomas Nield<mailto:thomasnield@live.com>; edvin/tornadofx<mailto:reply@reply.github.com>; edvin/tornadofx<mailto:tornadofx@noreply.github.com>
Subject: RE: [tornadofx] Tooltip Builders (#58)

If you want to create the repository I can go ahead and start fleshing it out a little bit.

Sent from my Windows Phone
________________________________
From: Thomas Nield<mailto:thomasnield@live.com>
Sent: ‎3/‎28/‎2016 9:43 AM
To: edvin/tornadofx<mailto:reply@reply.github.com>; edvin/tornadofx<mailto:tornadofx@noreply.github.com>
Subject: RE: [tornadofx] Tooltip Builders (#58)

If you need help let me know.
________________________________

**Comment by thomasnield** [comment]
Oops sorry I did not realize I was emailing on the GitHub thread too.

How about tornadofx-reference, tornadofx-guide, tornadofx-manual, intro-to-tornadofx... just to name a few. I kind of like the first few.

Sent from my Windows Phone
________________________________
