### ISSUE TITLE
Combobox with item selected by default

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#583]
I would like to know how I can do to have selected a default item in my combobox, when I used the bind () method, for example:

```
val clienteItemModel: ClienteItemModel by inject()
.
..
...
this += JFXComboBox<Cargo>().apply {
   bind(clienteItemModel.cargo)
   promptText = "Cargo"
   minWidth = 120.0
   items = colaboradorPresenter.listCargos()
}
```

Now I want you to always have an element selected when you start the application, before I used the method `selectionModel.selectFirst()`, but when I use the bind (...), it no longer has any effect.

Thanks for dedicating time to TornadoFx and happy 2018 :)

**Comment by edvin** [comment]
Set the value in clienteItemModel.cargo :)
