### ISSUE TITLE
onDock & onUndock with bindComponents

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#584]
When adding components to a layout via `bindComponents` adding and removing items will not call `onDock` and `onUndock` on the fragments. Though I'm not sure if it is actually suppposed to call them I'd find it very helpful for bindings cleanup.

Example:

```kotlin
package tornadofx.testapps

import javafx.collections.FXCollections.observableArrayList
import tornadofx.*

class BindComponentsTest : View("My View") {

    private val people = observableArrayList("Alice", "Bob")

    override val root = borderpane {
        top {
            hbox {
                button("+").action { people.add("Charlie")}
                button("-").action { people.remove("Bob")}
            }
        }
        center {
            vbox {
                bindComponents(people, { ItemFragment(it) })
            }
        }
    }
}

class ItemFragment(val item: String): Fragment() {
    override val root = label(item)

    override fun onDock() { println("$item is docked") }
    override fun onUndock() {println("$item undocked") }
}
```

**Comment by edvin** [comment]
I agree, it should definitely be called, this is a bug.

**Comment by edvin** [comment]
Actually, this is a bug in your code. You're not supposed to instantiate Fragments manually. This results in that the component life cycle is bypassed. You need to use `find` or `inject` to instantiate your fragments. In this case, `find` makes most sense. You can use parameters to pass the label if you don't want to set up a new scope for each component. Required changes:

```kotlin
class ItemFragment: Fragment() {
    val item: String by param()
    override val root = label(item)

    override fun onDock() { println("$item is docked") }
    override fun onUndock() {println("$item undocked") }
}
```

Now just use find and pass the `item` parameter:

```kotlin
bindComponents(people, { find<ItemFragment>(mapOf(ItemFragment::item to it)) })
```

**Comment by edvin** [comment]
This makes me think I might have made the same mistake in an example or two. If you have seen this somewhere, please let me know so I can correct it.

**Comment by dominiks** [comment]
Ah I see. I had a feeling that directly instantiating might be somewhat wrong when there already is an alternative syntax to get instances of fragments. Thanks for your help!

**Comment by edvin** [comment]
My pleasure :)
