### ISSUE TITLE
How to bind a ListView with an attribute that is a list of an ItemViewModel

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#586]
Hello, how could I do to bind a observableList to a ListView? for example, this is my ItemViewModel:

```
class ClientItemModel : ItemViewModel<Client>() {
   val name = bind(Client::nameProperty)
   val phones = bind(Client::phonesProperty) // This is a SimpleListProperty<Phone>()
}
```
And my "Form" is this:

```
class CustomerForm : View() {
    val model : ClientItemModel by inject()

    override val root = form {
        fieldset("Personal Information", FontAwesomeIconView(USER)) {
            field("Name") {
                textfield(model.name)
            }
        }

        fieldset("List Phones")) {
            field {
                listview{
                   cellFragment(PhoneItemFragment::class) // Custom cell
                   items = model.phones  // this gives error Required: ObservableList<Almacen!>! Found: Property<ObservableList<Almacen!>!>
                }
            }
        }
    }

}
```
I try with `items = model.phones.value` but it does not show the phone list in my `ListView` when I select a client.

**Comment by edvin** [comment]
What you want to do is to bind the `model.phones` property to the `itemsProperty` of the ListView. You can actually just pass the list property to the listview builder constructor:

```kotlin
listview(model.phones)
```

If you simply assign to items, you don't tell the framework to make a binding, you're just assigning a list to the listview. See? :)

**Comment by TioCoding** [comment]
Thanks for the response, in my case I use an external component that is the JFXListView, and I have binding it in this way:
```
this += JFXListView<Phone>().apply{
      cellFragment(PhoneItemFragment::class)
      itemsProperty().bind(model.phones)
}
```

But when I select a client I get an exception:

```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.clario.ClarioDesktopApp.bean.entity.clario.Phones
	at com.clario.ClarioDesktopApp.bean.model.PhoneItemModel$namePhone$1.get(PhoneItemModel.kt) ~[classes/:na]
	at com.clario.ClarioDesktopApp.bean.model.PhoneItemModel$$special$$inlined$bindProperty$1.invoke(ViewModel.kt:543) ~[classes/:na]
	at com.clario.ClarioDesktopApp.bean.model.PhoneItemModel$$special$$inlined$bindProperty$1.invoke(ViewModel.kt:513) ~[classes/:na]
	at tornadofx.ViewModel$rollback$1.invoke(ViewModel.kt:259) ~[tornadofx-1.7.14.jar:na]
...
..
.
```
And it only appears when I add the `cellFragment(PhoneItemFragment::class)` to my ListView

What is this error producing and how to solve it?

My PhoneItemViewModel and PhoneItemFragment is the same as any other.

**Comment by edvin** [comment]
I think I'd need to see a working minimal sample to figure this one out :)

**Comment by TioCoding** [comment]
Checking the code and doing several tests, I realized that the problem is Jackson's, I'm trying to solve it. I think a Pojo of TornadoFx  does not integrate very well with Jackson when it comes to Serialize observableList()
