### ISSUE TITLE
Using the EventBus in tests

### ISSUE THREAD

**Issue by dominiks** [edvin/tornadofx#589]
I am playing around with the EventBus and have one of my model classes fire an event to notify a Fragment of a change and that works very well. But when I have a unit test for my model class and the event gets fired I get the exception:

```
Exception in thread "main" java.lang.IllegalStateException: Toolkit not initialized

	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
	at javafx.application.Platform.runLater(Platform.java:83)
	at tornadofx.EventBus.fire(EventBus.kt:114)
```
The event is fired via `FX.eventbus.fire()`.

At the moment I only use the events with UI elements as consumers so I could get away with disabling event firing when FX is not initialized but I might want to use events in other ways in the future.

Is there a way one can use the eventbus without creating a stage and everything?

**Comment by dominiks** [comment]
One workaround I found it to instantiate a `JFXPanel` before the test to have the JavaFX platform initialized. Not very elegant but workable if there's no better solution.

**Comment by ronsmits** [comment]
I dont know if this helps but tornadofx runs tests using testfx. I quickly wrote a unit test that sends and receives an event:

```
package app

import javafx.stage.Stage
import org.junit.Test
import org.testfx.api.FxToolkit
import tornadofx.*

object testEvent : FXEvent()
class EventTest {

    val primaryStage: Stage = FxToolkit.registerPrimaryStage()

    @Test
    fun sendAndReceiveEvent(){

        val bus = EventBus()

        val controller = object : Controller(){
            init {
                println("controller is setup")
                subscribe<testEvent> {
                    println("testEvent received")
                }
                fun fireEvent() = fire(testEvent)
            }
        }
        controller.fire(testEvent)
    }
}
```

**Comment by edvin** [comment]
JavaFX constructs require the initialization, so doing either `FxToolkit.registerPrimaryStage()` or instantiating a `JFXPanel` is basically what you have to do.

**Comment by dominiks** [comment]
Great, thanks guys! I'll use the JFXPanel then for tests that don't require any UI.
