### ISSUE TITLE
Injection patterns for reactive models?

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#59]
I have found the injection model to feel strangely backwards when used with reactive programming. I am using [RxKotlinFX](https://github.com/thomasnield/RxKotlinFX), which is backed by [RxJava](https://github.com/ReactiveX/RxJava) and [RxJavaFX](https://github.com/ReactiveX/RxJavaFX). 

Here's a little theory that might be driving this, and forgive me if I'm wrong on any assumptions. I'm not an expert on MVC at all. 

Traditional imperative models would have the `View` _pull_ items from the `Controller`, which would lazily trigger instantiating the `Controller`. But a reactive model is likely to _push_ items from the `Controller` to the `View`. It is an inversion of control. 

So it is a little awkward to inject a `Controller` into a `View`, when really the `View` should be injected into the `Controller`. Otherwise, with the current injection pattern the `View` will actually be doing all the work and not the `Controller`. 

If I'm not making any sense, try to think about migrating the reactive logic below from the `View` to the `Controller`. Unless I'm missing something, you might realize there is no way to accomplish this without a lot of messy initialization and anti-patterns to interop the two.

```kotlin

class MyApp: App() {
    override val primaryView = MyView::class
}

class MyView: View() {

    override val root = VBox()

    val controller: MyController by inject()

    var countLabel: Label by singleAssign()
    var button: Button by singleAssign()
    var itemsList: ListView<String> by singleAssign()

    init {
        with(root) {
            button = button("Increment")
            countLabel = label("")
            itemsList = listview()
        }

        //everything else below needs to move to the Controller

        //increment number on countLabel every time button is pressed
        button.actionEvents()
                .map { 1 }
                .startWith(0)
                .scan { x,y -> x + y }
                .map { it.toString() }
                .subscribe { countLabel.text = it }

        //subscribe items into itemsList
        controller.items.subscribe { itemsList.items.add(it) }
    }
}

class MyController: Controller() {
    val items = Observable.just("Alpha","Beta","Gamma","Delta","Epsilon")
}
```

**Comment by thomasnield** [comment]
Or, so the `Controller` does not know too much about the `View` via reverse injection, what needs to happen is the "input" `Observable` like `button.ActionEvents()` needs to be passed as an argument to the `Controller` on its initialization. Then the `Controller` will provide an "output" `Observable` with the number increments that the `View` can subscribe to the `countLabel`.

By this logic, the `View` should handle all subscribing. But there might be a need to for the `View` to provide the input `Observables`.

**Comment by thomasnield** [comment]
Okay I think I might have figured this out. 

```kotlin
class MyApp: App() {
    override val primaryView = MyView::class
}

class MyView: View() {

    override val root = VBox()

    val controller: MyController by inject()

    var countLabel: Label by singleAssign()
    var button: Button by singleAssign()
    var itemsList: ListView<String> by singleAssign()

    init {
        with(root) {
            button = button("Increment")
            countLabel = label("")
            itemsList = listview()
        }

        controller.incrementInputs = button.actionEvents()

        //populate itemsList
        controller.items.subscribe { itemsList.items.add(it) }

        controller.increments.subscribe { countLabel.text = it.toString() }
    }
}

class MyController: Controller() {

    var incrementInputs: Observable<ActionEvent> by singleAssign()
    val items = Observable.just("Alpha","Beta","Gamma","Delta","Epsilon")

    val increments: Observable<Int>
        get() = incrementInputs
                .map { 1 }
                .startWith(0)
                .scan { x,y -> x + y }
}
```

I kind of realized the `Controller` cannot know the `View` too much, and inverse dependency injection might ruin the separation of control. But using the `singleAssign()` might provide a safe way to do late initialization and pass arguments for that operation later.

I may close this but curious if you have any thoughts.

**Comment by edvin** [comment]
Hehe, my head is spinning a bit right now, and I haven't quite grasped the issue you're having yet. I don't know if this is helpful, but a `View` is really a `ViewController`. I like to think about it like this: The actual view is the root node, sometimes built in code, other times imported from FXML.

Traditionally the controllers contain business logic and remoting calls, and anything that mutates the UI stays in the View, or ViewController if you wish. Most of the code in your Controller is really ViewController related. Putting that aside for bit, you could easily put view logic in controllers, and even have them instantiate the view. The only reason for doing that would be code reuse though, or else you might just keep everything in the view controller.

By the way: Views can actually be injected in controllers, there is nothing wrong with that since they are singletons. I do this for example in my `LoginController` which pops up the login UI when needed.

Would it be possible for you to create a complete project with this code and a deployment descriptor (either Maven or Gradle) so I can play with it? Not knowing RxJava and friends it's a bit hard to guess what everything does without "touching" it :)

**Comment by edvin** [comment]
By the way, I just noticed that you use `singleAssign` for the ui nodes, but you do actually assign these values in `init`, so it should be legal. To illustrate, this compiles just fine:

```kotlin
    val countLabel: Label
    val button: Button
    val itemsList: ListView<String>

    init {
        button = root.button("Increment")
        countLabel = root.label("")
        itemsList = root.listview()
    }
```

The problem seems to be that using `with` makes the compiler believe that the values are not initialized in the constructor after all. Wonder if there is a workaround for this.. hmm...

**Comment by thomasnield** [comment]
Ah, interesting digression... yeah I just did a `singleAssign()` out of habit haha. But I wonder if there is a better way to get around that. Is that just the nature of lambdas?

**Comment by thomasnield** [comment]
Okay, I put out a test project with this example set up. I guess what I'm trying to figure out is "what is the best injection pattern?" I would definitely play with reactive when you get a chance. I'd be curious how you would apply it. 

https://github.com/thomasnield/rxtornadofx_test

**Comment by thomasnield** [comment]
And sorry haha, I was kind of thinking out loud while I was posing this question.

**Comment by edvin** [comment]
Cool! I think it's time to make TornadoFX reactive friendly. But I'm not gonna hurry this, I need to understand it properly so we don't make any critical mistakes. First dinner, then Batman vs Superman, then I'll play more with this in the evening :) hehe

**Comment by thomasnield** [comment]
I've been hesitating to see that movie, let me know if it is any good and maybe I'll drag my brother. And if you study RxJava, that [GitHub book](https://github.com/Froussios/Intro-To-RxJava) I pointed out earlier is very good. Have a good evening!

**Comment by edvin** [comment]
Will keep you posted :))

**Comment by edvin** [comment]
Some initial comments.

To me, it seems like `incrementInputs` and `increments` belongs in the View, not in the Controller. They do not contain business logic, and are tightly bound to the view. That leaves just the items in the controller, which seems perfectly fine to me. Note that I might not understand this correctly yet, so correct me if I'm wrong :)

Next, a question: Why would you use `Observable.just` to define a list of items instead of just going with an `ObservableList`? Adding the values to the list is more verbose, and you can't update the list and have the result reflected in the ListView.

Next, this:

```kotlin
increments.subscribe { countLabel.text = it.toString() }
```

Sure, it's reactive, but not very declarative. To me it seems more intuitive to bind the `countLabel.textProperty` to an expression created from the list. Pseudo code (since I don't know how that would be done with the data types from RxJava):

```kotlin
countLabel.textProperty().bind(increments.asStringBinding)
```

I'm guessing you do it like this because it's a pattern or best practice - can you explain?

Sorry if this is a bit off topic, just trying to wrap my head around this :)

**Comment by edvin** [comment]
Heh, I just noticed - your first example is how I would do it, my comments are for the second example :)

**Comment by edvin** [comment]
In the first example, I only dislike `controller.items.subscribe { itemsList.items.add(it) }` for reasons explained above. The separation of conserns seems 100% correct.

This thing is a bit verbose:

```kotlin
 button.actionEvents()
                .map { 1 }
                .startWith(0)
                .scan { x,y -> x + y }
                .map { it.toString() }
                .subscribe { countLabel.text = it }
```

Maybe there is or should be a way to convert a stream to a counter or accumulator directly, something like:

```
button.actionEvents().counting().subscribe { countLabel.text = it }
```

**Comment by thomasnield** [comment]
No problem, and technically you are right this is a bit contrived and for such static data your suggestions are valid. 

Let's make a few assumptions to make it less contrived:

1) Let's pretend the business logic is much more complicated for all the above to the point it would be ideal to separate.

2) Let's say "Alpha", "Beta", "Gamma", etc are maintained in an `Observable` and can come from a database, an XML file, user inputs from elsewhere, etc. 

3) Let's say a lot more complicated operations happened between the button action events and the 

For the increment stuff, it may seem verbose but it is doing a heck of a lot of work. It is mapping button `ActionEvent`s to 1's, starting it with 0, and accumulating to sums via `scan()`. The `scan()` is different than `count()` because the `count()` operator blocks until all emissions are done and `onCompleted()` is called. The `scan()` allows you to "accumulate" emissions in some arbitrary way but emit the running total for each emission.

**Comment by thomasnield** [comment]
Your point for a proposed operator (which I think you called `counting()`) is one of the great things about using RxJava and Kotlin. You can easily add your own own operators to `Observable` via extension functions, rather than having to use `compose()` or `lift()` in Java. This is why I wanted to get you involved in RxKotlinFX, because we can do some really cool stuff here.

```kotlin
fun main(args: Array<String>) {
    val strings = Observable.just("Alpha","Beta","Gamma","Delta","Epsilon")
    strings.counting().subscribe { println(it) }
}

fun <T> Observable<T>.counting() =  map { 1 }.startWith(0).scan { x,y -> x + y }
```

**OUTPUT:**
```
0
1
2
3
4
5
```
I just realized I don't need the `startWith()`. For some reason I assumed the `scan()` required a minimum of two emissions. I think I was wrong and this works just fine.

**Comment by thomasnield** [comment]
I know this seems a bit contrived, and I'll give you more examples later. Here is zipping which "zips" emissions from two or more Observables together.

```kotlin
fun main(args: Array<String>) {
    val strings = Observable.just("Alpha","Beta","Gamma","Delta","Epsilon")
    val numbers = Observable.range(1,6)

    Observable.zip(strings, numbers, {s,i -> s + "-" + i.toString()})
        .subscribe { println(it) }
}
```
**OUTPUT:**
```
Alpha-1
Beta-2
Gamma-3
Delta-4
Epsilon-5
```

It does not have to be data that is emitted. It could be events as well from UI controls. When you combine, merge, zip, filter, reduce, and do dozens of other operations on streams of events and data, it is a very powerful concept.

**Comment by thomasnield** [comment]
Here's another contrived, although demonstrational, example. 
You can use flatMap() to replace button ActionEvent emissions with another Observable of random Ints, which you can collect into a List and push to the Subscriber.

class MyApp: App() {
    override val primaryView = MyView::class
}

class MyView: View() {

    override val root = VBox()

    var button: Button by singleAssign()
    var itemsList: ListView<Int> by singleAssign()


    init {
        with(root) {
            button = button("Import Data")
            itemsList = listview()
        }

        button.actionEvents()
                .flatMap { buildData().toList() } //returns Observable<List<Int>>
                .subscribe { itemsList.items.setAll(it) }
    }

    fun buildData(): Observable<Int> = Observable.range(0,random(20))
            .map { random(1000) }
}

private val rnd = Random()
private fun random(max: Int) = rnd.nextInt(max + 1)
Although this is pretty instant, say it takes awhile to build that List<Int> of random numbers. You can get concurrent very quickly, and can take this "data building" off the UI thread and onto an IO one, and then put it back on the UI thread when its done. 
button.actionEvents()
        .observeOn(Schedulers.io())
        .flatMap { importData().toList() }
        .observeOnFx()
        .subscribe { itemsList.items.setAll(it) }
I know you are a fan of JSON which I've not done much of, but I use databases and SQL directly a lot. I use RxJava-JDBC heavily, to turn queries into Observables. https://github.com/davidmoten/rxjava-jdbc
Let me know if you have any questions. It's an entirely new way of thinking, but it is a very powerful, composable way of modeling data and events.

Date: Sun, 27 Mar 2016 16:06:07 -0700

**Comment by thomasnield** [comment]
Just had a realization today. Maybe hot Observables that are the result of UI events should strictly be on the View. The Controller may likely only contain cold Observables to emit data, and are joined to the hot Observables on the View side. 

If this Observation is right, there is no need for "hot input" Observables to be passed

**Comment by edvin** [comment]
With my limited knowledge of reactive patterns, this seems entirely reasonable to me :)

**Comment by thomasnield** [comment]
Yes, I'll post an example later as I continue thinking through this. But I think there is a possibility MVC might not always be the appropriate pattern for reactive applications. I know there are others like MVVM and MVP. This will be an interesting case study.

**Comment by edvin** [comment]
I'm positive we can find a good fit for reactive applications, once we find the sweet spot for them. I'll read more about this while you explore. Feel free to email me directly if you want to discuss or get further insights into this!

**Comment by thomasnield** [comment]
I think I'm overthinking this quite a bit. I've done a few experiments and I think I'm expecting too much from the `Controller` in a reactive setting. 

The code I had earlier I believe is acceptable. I think a "good design" might entail this: 
- Cold data-driven Observables reside in the `Controller`
- Hot Observables derived from UI events on `View` should stay on the `View`
- The `Controller` can hold hot Observables when it acts as an "event bus" of sorts between Views

```kotlin
class MyApp: App() {
    override val primaryView = MyView::class
}

class MyView: View() {

    override val root = VBox()

    val controller: MyController by inject()

    var countLabel: Label by singleAssign()
    var button: Button by singleAssign()
    var itemsList: ListView<String> by singleAssign()

    init {
        with(root) {
            button = button("Increment")
            countLabel = label("")
            itemsList = listview()
        }
        button.actionEvents()
                .map { 1 }
                .startWith(0)
                .scan { x,y -> x + y }
                .map { it.toString() }
                .subscribe { countLabel.text = it }

        //subscribe items into itemsList
        controller.items.subscribe { itemsList.items.add(it) }
    }
}

class MyController: Controller() {
    val items = Observable.just("Alpha","Beta","Gamma","Delta","Epsilon")
}
```

**Comment by edvin** [comment]
OK! I agree the above code looks clean and doesn't present any problems that I can see. The View is supposed to contain view logic, so events emitted by the ui should be manipulated there. I'll revisit this once I get more reactive experience and look for ways to optimize :)
