### ISSUE TITLE
Is there a forum for TornadoFX community ?

### ISSUE THREAD

**Issue by vlipovetskii** [edvin/tornadofx#592]

**Comment by nimakro** [comment]
Hey @vlipovetskii,
the short answer is no.
But there are a few options to interact with the community:

- The #tornadofx channel on [Slack](https://kotlinlang.slack.com) is probably the easiest and quickest way to interact with the core developers and other people of the community.
- [StackOverflox](https://stackoverflow.com/search?q=%23tornadofx) is also a good place to ask general questions which could be useful to other. Don't forget to add the #tornadofx tag to your question.

Regards Micah
