### ISSUE TITLE
SortedFilteredList in multiples view

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#594]
Hello, I have a SortedFilteredList that I use in different views, the first view has a ListView where I use the property property items and I add the SortedFilteredList:

```
private val filterListCargo = cargoPresenter.listCargo() // Data
...
..
.
this += JFXListView<Cargo>().apply {
      cellFragment(CargoItemFragment::class)
      filterListCargo.bindTo(this)
      items = filterListCargo
      selectionModel.selectedItemProperty().onChange { cargoPresenter.selectCargo(it) }
}
```

And in another view I have a `comboBox` where I use the same items in the same way:

```
this += JFXComboBox<Cargo>().apply {
      bind(colaboradorItemModel.cargo)
      isLabelFloat = true
      promptText = "Cargo"
      items = cargoPresenter.listCargos() // Data
}
```

Everything works fine, but when I use the `filterWhen` method of the `filterListCargo` it filters the data of my `ListView` and my `ComboBox`. But I just want you to filter the data in my `ListView`.

One solution would be to work each one with different instances, but when I use a single instance, the data in my Combobox and my ListView are automatically modified each time I want to edit a record.

Any recommendation for this type of case.
Thank you.

**Comment by edvin** [comment]
Return a normal observablelist from cargoPresenter.listCargos() and wrap that in two different instances of SortedFilteredList, one for each control :)

**Comment by TioCoding** [comment]
Thank you very much, I can already work the same information in different views. :smile:
