### ISSUE TITLE
change view in workspace

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#597]
hello 
when using replacewith to change view  i still using the first view workspace action

```
class MyWorkspace : Workspace("My View",navigationMode = NavigationMode.Tabs) {

    init {
        add(MainMenu::class)
        root.nodeOrientationProperty().set(NodeOrientation.RIGHT_TO_LEFT)
        root.useMaxSize

    }
}
```
move from first view to the second  still using the first view workspace actions 
```
override fun onCreate() {
        controller.isNew=true
        controller.editMode=true
        replaceWith(UserEditor::class, ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.LEFT))
    }
```
move from second to first replace the all workspace
```
override fun onDock() {
        with (workspace) {
            button("Add Customer").action {
                this.replaceWith(find(UserList::class))
            }
        }
    }
```

**Comment by edvin** [comment]
This is not the way to use the Workspace. You should call `dock()` to replace views in the Workspace. Calling `replaceWith` on the workspace would remove the workspace container that is actually keeping track of the docked views.

**Comment by mostfa-ayad** [comment]
i konw That but i want open the new view in the same tab dock() method open new tab
