### ISSUE TITLE
EditModel inconsistencies

### ISSUE THREAD

**Issue by kastork** [edvin/tornadofx#598]
It is possible I'm doing something I shouldn't be doing, but I'm observing what I believe to be unexpected behaviors from tableviews with an EditModel.

1. When using checkbox cell editors, the only one that works is in the first row.
2. After editing a cell and pressing ENTER, the dirty flag is present, but the value has actually been committed.
3. After editing a cell and pressing TAB, I would expect the same behavior as ENTER.  However, the value is temporarily changed without a dirty flag, and committing results in revert to original value.
4. After editing a cell, if you then click another cell to edit, the previous cell reverts to original value.  I would expect this action to behave like ENTER.

I've created a small project that demonstrates my observations.  
https://github.com/kastork/checkbox-selection-reproducer

Is this all because I've done something incorrectly?

**Comment by edvin** [comment]
Something is definitely not right here, but first, let me clarify a couple of things:

3. This is the default behavior for JavaFX TableView. Only enter will commit the value. Moving to another cell effectively works as rollback, but it takes effect when editing is cancelled.

4. This is also default behavior for JavaFX TableView. I think these were horrible decisions by the JavaFX Team, but it is what it is.

Looking at the issues related to the EditModel now :)

**Comment by edvin** [comment]
Now to address rollback/commit:

This feature works by tracking the changed values. I was not able to find a way to change actually intercept the values and prevent them from being written, so changes are made to your objects when you edit them, just like it would have if you didn't have the dirty tracking feature turned on.

However, if you hit rollback you will see that the dirty items will get their old values back. This was unfortunately the only way I could make this work.

**Comment by kastork** [comment]
- The commit/rollback behavior I think, as you say, is not worth attempting to change.

- I'll look at trying to keep the edit upon leaving the cell by any means -- Maybe the way we did it for spinners not long ago.  Meanwhile, since it is the default JavaFX behavior, I suppose this, too, may not be worth trying to fix.

For both of the above, I wonder how to help users understand.  The behavior on loss of focus really is a "principal of least surprise" violation.

The rollback behavior kind of adds support to the idea of having a way to track the dirty state of the entire table so you could activate a rollback / commit buttons or menu items only when it is appropriate, though I know this could create performance problems for very large tables.

**Comment by edvin** [comment]
I agree with all of that. It's a pity about these decision, they really do surprise everyone. I think we should mention this in the guide. Are you up for a small PR to the guide? :)

There is still something funky here with the changes in the first row vs the rest, so I'm investigating that now.

**Comment by edvin** [comment]
Ah, I found an issue. A while back I added `Node.index` as a val, and that backfired. This index was used instead of the column index :) That is probably the reason while row 0 acted differently.

**Comment by kastork** [comment]
I'll put the guide edits on my todo list  :)

Weren't there plans to completely revamp the guide, not using gitbook?  Where is that work taking place?

**Comment by edvin** [comment]
Yes, we talked about it, but nothing has been done yet :)
