### ISSUE TITLE
Ambiguous "TableView.column()" extension signature

### ISSUE THREAD

**Issue by SackCastellon** [edvin/tornadofx#599]
### Code:
``` kotlin
class StockReport : Fragment() {
    override val root: BorderPane by fxml()
    private val table: TableView<Material> by fxid()

    init {
        table.apply {
            column("Code", Material::codeProperty) { prefWidth = 125.0 } // Error
            column("Group", Material::groupProperty) { prefWidth = 100.0 } // Error
        }
    }
}
```
``` kotlin
class Material {
    val codeProperty = SimpleStringProperty("")
    var code: String by codeProperty

    val groupProperty = SimpleStringProperty("")
    var group: String by groupProperty
}
```
### Problem:
IntelliJ is not able to determine which of the following methods to call:

- [`TableView<S>.column(String, KProperty1<S, T>, TableColumn<S, T>.() -> Unit): TableColumn<S, T>`](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/ItemControls.kt#L585-L590)
- [`TableView<S>.column(String, KProperty1<S, ObservableValue<T>>, TableColumn<S, T>.() -> Unit): TableColumn<S, T>`](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/ItemControls.kt#L603-L608)

This only happens when passing properties of type _ObservableValue_, for example, this code gives no error:
``` kotlin
class StockReport : Fragment() {
    override val root: BorderPane by fxml()
    private val table: TableView<Material> by fxid()

    init {
        table.apply {
            column("Code", Material::code) { prefWidth = 125.0 } // Error
            column("Group", Material::group) { prefWidth = 100.0 } // Error
        }
    }
}
```

**Comment by edvin** [comment]
I have an idea about what's going on. Can you try to change `column("Code", Material::codeProperty) { prefWidth = 125.0 }` to `column("Code", Material::codeProperty).apply { prefWidth = 125.0 }`?

**Comment by SackCastellon** [comment]
Yes, I also thought about that but then there is no point in having this method if you can never use it, right?
[`TableView<S>.column(String, KProperty1<S, ObservableValue<T>>, TableColumn<S, T>.() -> Unit): TableColumn<S, T>`](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/ItemControls.kt#L603-L608)

**Comment by edvin** [comment]
Absolutely, I was just testing a theory. The method probably stopped being accessible when we introduced support for readonly property references. I'm looking for ways to avoid renaming that, but if I can't find another solution I'll rename that to `readonlyColumn` or something like it to make the observable column builder accessible again.

**Comment by edvin** [comment]
I've renamed the culprit and pushed the change. Do you mind testing if this solves the issue for you?

**Comment by edvin** [comment]
Sorry, I made things worse :) Hang on, will let you know when you can test.

**Comment by edvin** [comment]
There :) Not convinced we'll keep readonlyColumn like this, so I'll look for a better solution. In the mean time this should resolve the issue.

**Comment by SackCastellon** [comment]
It works fine! 👍

**Comment by tieskedh** [comment]
It's not possible to change this.
The reason is that if Kotlin doesn't choose for the more specific generic itself.
I posted it on discuss.kotlinlang.org: https://discuss.kotlinlang.org/t/most-specific-function-with-generics-in-inline-function/6681

**Comment by edvin** [comment]
Thanks for the info and your effort, Thijs. I'll close this issue, as TornadoFX 1.7.15 was released with the`readonlyColumn` function. If support for more specific generics are added to Kotlin we will deprecate this function and reimplement it as `column`.
