### ISSUE TITLE
FX resource leak

### ISSUE THREAD

**Issue by rwhite226** [edvin/tornadofx#602]
In the app I'm working on I have a plugin system (somewhat like osgi) where each plugin has it's own classloader/jars. When a plugin stops all resources and classes should be freed. Unfortunately with tornadofx there are some roadblocks. The FX class has two ThreadLocal variables inheritParamHolder , and inheritScopeHolder which hold onto instances of a plugins classes even after that plugin has stopped. Right now I'm reflecting into them to remove them, but it would be nice if they where either public or their was a "shutdown" method to call on the FX class to remove them.

**Comment by edvin** [comment]
Thanks for reporting. I've made sure that these two are cleared when App.stop() is run. Does that solve the issue for you?

**Comment by rwhite226** [comment]
@edvin That should work, thanks.
