### ISSUE TITLE
How to set combobox css 

### ISSUE THREAD

**Issue by toplinuxsir** [edvin/tornadofx#603]
How to set combobox css ?
```
     comboBoxPopup {
            textFill = c("#0000FF")
        }
        comboBox {
            textFill = c("#0000FF")
        }
        comboBoxBase {
            textFill = c("#0000FF")
        }
```

It does not work

**Comment by edvin** [comment]
Take a look at the JavaFX 8 CSS Reference for information about the CSS structure of a combobox:

https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html#combobox

Generally you should use Scenic View or the built in Layout Debugger to look at the structure of the UI and the nodes classes to determine which selectors to target.

**Comment by toplinuxsir** [comment]
Thanks !

**Comment by edvin** [comment]
My pleasure :)
