### ISSUE TITLE
Visual styling of added buttons in workspace toolbar

### ISSUE THREAD

**Issue by kastork** [edvin/tornadofx#609]
The guide suggests using FontAwesomeIconView's when adding buttons to the toolbar. But when doing what the guide suggests, the icon-only styled buttons are not sized/aligned properly with respect to the default buttons. 

In some examples, I've seen the use of a function that looks something like this...

```
fun icon(icon: FontAwesomeIcon,
         color: Color = Color.STEELBLUE,
         size: Int = 24) = FontAwesomeIconView(icon)
	.apply { glyphSize = size; fill = color }
```

Which you then call to set the graphic for, say , a button.

```
	button("Run") {
		addClass("icon-only")
		graphic = icon(FontAwesomeIcon.PLAY_CIRCLE, c("#818181"), 17)
		// ...
```

The framework could provide a function like this that also adjusts the FontAwesomeIconView or applies a class so it aligns and sizes properly with the toolbar buttons.  But it is obviously also desirable to avoid having TFX depend on FontAwesome.  So maybe this is strictly a matter for the guide.

**Comment by edvin** [comment]
I think this is good to have in the guide. I've thought about library for FontAwesome icons that work better with Kotlin/TornadoFX though...

**Comment by nimakro** [comment]
I think we should keep the `FontAwesome` dependencies out of tfx, but we could create a separate lib like @edvin suggested.

**Comment by nimakro** [comment]
I will close for now till somebody has time to work on this.
