### ISSUE TITLE
reload combox data source in editable table after start

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#610]
hello 
have acolumn in table  editing using comboBox with a list of items 

                    
  ```
column("account", DailyLine::account) {
                                useComboBox(accounts){
                                    setOnEditStart {
                                    }
                                }
                            }

```
his list  can be changed in the source after the table is start  and  i want to reload the data 
i try to reload the data and refresh the table but this didn't change the list data

```
fun refresh(){
        accounts=accountController.loadAccounts()
        linesTable.refresh()
}
```

**Comment by edvin** [comment]
Do accounts.setAll(accountController.loadAccounts()) instead :) And if `loadAccounts` involves IO, please do `runAsync { accountController.loadAccounts() } ui { accounts.setAll(it) }`.

**Comment by mostfa-ayad** [comment]
you see it's simple  :)
thank you

**Comment by edvin** [comment]
Hehe, you're welcome :)
