### ISSUE TITLE
[Help/Way] Controls CSS properties

### ISSUE THREAD

**Issue by NiranjanShah** [edvin/tornadofx#617]
1. How to change the row colour when it is selected (currently focused)
2. How to find out the available properties for the controls for changing the styles.
3. Change the colours of alternative rows of table

**Comment by edvin** [comment]
Consult the JavaFX CSS reference and play around with Scenic View to get a better feel for how JavaFX CSS works:

https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html
http://fxexperience.com/scenic-view/
