### ISSUE TITLE
Table Row Select

### ISSUE THREAD

**Issue by NiranjanShah** [edvin/tornadofx#618]
1. onUserSelect does not fire unless and until user clicks (mouse click) on one of the row.

[Guide]

is the below current way to select a row manually or is there any better way

**table.selectionModel.select(table.selectionModel.selectedIndex - 1)**

**Comment by edvin** [comment]
That's certainly one way to do it, but make sure you guard against navigating to a non existent row.

**Comment by NiranjanShah** [comment]
What about the first point 

**onUserSelect does not fire unless and until user clicks (mouse click) on one of the row.**

**Comment by edvin** [comment]
That's the point of the function. You can optionally configure how many clicks is required. What do you want to achieve? If want to bind a viewmodel to the selected element, use `bindSelected`.

**Comment by NiranjanShah** [comment]
When the users starts using arrow key (without using mouse, on init focus is set on tableview) and moves to second row and if he clicks enter **onUserSelect** should get fired, however it is not happening so.

Scenario

In the TableViewSortFilterTest , I have coded the below, however the output "User selected" is not coming.

To simulate it, explicitly (thru code) put focus on table view (tableview.requestfoucs() and click "ENTER" key, the onUserSelect does not fired.


** onUserSelect {
             println("User Selected")
            } **

**Comment by edvin** [comment]
I just confirmed that it does indeed fire, so if it doesn't fire for you, please create a complete View that demonstrates the issue.

**Comment by edvin** [comment]
To be clear, I also tested with your specific change to TableViewSortFilterTest and that works as well.
