### ISSUE TITLE
EventBus can fire on background thread (Not Application UI Thread)?

### ISSUE THREAD

**Issue by toplinuxsir** [edvin/tornadofx#619]
EventBus can fire on background thread (Not Application UI Thread)?

**Comment by edvin** [comment]
Yes, create your event as `MyEvent : FXEvent(runOn = EventBus.RunOn.BackgroundThread)`.

**Comment by toplinuxsir** [comment]
.RunOn.BackgroundThread meaning : The subscriber callback run on background thread , not the thread which fire the event
?

**Comment by toplinuxsir** [comment]
I want to fire the event on background thread , but I can not find the way

**Comment by edvin** [comment]
I'm not sure I understand why that matters. The contract lets you specify on what thread the event is delivered, and you can fire the event from any thread. Why do you need the fire to happen on another thread than the one you're currently on? If for some reason you really need it to fire on a background thread and you're currently on the ui thread, just wrap it in `runAsync { fire(event) }`, but please explain why that matters? :)

**Comment by toplinuxsir** [comment]
I have a background thread to read data from other device ,when data arrive , then fire the event to the UI, and display the data .

**Comment by edvin** [comment]
Then the default configuration of an FXEvent will do exactly that. If `runOn = ApplicationThread`, you can fire from anywhere and the event will be delivered on the UI thread.
