### ISSUE TITLE
Provide convenience for filtered/sorted list data in TableView

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#62]
Sorting data in a TableView basically requires you to juggle three different observable lists. The workflow is as follows:

1. Create a list of the actual table data (`tableData`)
2. Create a `FilteredList` that wraps `tableData` (`filteredData`)
3. Create a `SortedList` that wraps the `filteredData` and binds its `comparatorProperty()` to the TableView's `comparatorProperty()`
4. Update the `filteredData.predicate` when ever the filtering conditions change

It would be convenient to be able to express all this with a single statement.

**Comment by hastebrot** [comment]
I've created a `TransformatedListContext` [1] in Groovy a while ago (the gist includes an implementation, `main` method and specification tests). It allows to have a `masterList` and a `targetList`. Maybe this gives some hints on how to implement this for TornodoFX, maybe my approach is suboptimal, I had to be very careful with weak references in the observable list.

[1] https://gist.github.com/hastebrot/efe0a4d39e054730f8090ef9facfe050

**Comment by edvin** [comment]
Thanks! I'm working on an implementation right now, I'll see if I can glean some ideas from your list :)

**Comment by edvin** [comment]
I commited `SortedFilteredList` now. It is a delegate for an `ObservableList<T>`, and wraps the data in the way described in the top of this issue. You can connect it to a `TableView` or `ListView` like this:

```kotlin
val table = TableView<Person>()
val data = SortedFilteredList(persons).bindTo(table)
```

It can also be used ad hoc. Filter the data by updating the predicate:

```kotlin
data.predicate = { it.age > 18 }
```

Special support is added to update the predicate based on an `Observable`. This is extremely handy for `TextField` based filtering. Let's pretend that `Person` has a `matches(query: String): Boolean` function. With this, you can perform live filtering very easily:

```kotlin
textfield {
    promptText = "Filter query"
    data.filterWhen(textProperty(), { query, item -> item.matches(query) } )
}
```

The same technique can be used for selection based on a `ComboBox` or similar.

**Comment by edvin** [comment]
I noticed something that might be confusing while I was writing a test for this:

```kotlin
val data = SortedFilteredList(persons)
data.predicate = { it.name.contains("Stu")}
Assert.assertEquals(2, data.filteredItems.size)
```

This works, but one might expect that `data.size` was two, instead of `data.filteredItems.size`. An alternative approach would be to delegate from the sortedList instead, but that would mean that you would have to assign items to it via `data.items`. Don't know what's the least confusing option.

**Comment by edvin** [comment]
It was definitely better that the `SortedFilteredList` is in fact sorted and filtered. Commited a fix. The test is now:

```kotlin
val data = SortedFilteredList(persons)
data.predicate = { it.name.contains("Stu")}
Assert.assertEquals(2, data.size)
```

**Comment by edvin** [comment]
Added a simple test:

```kotlin
    data class Person(val name: String, val age: Int)

    val persons = FXCollections.observableArrayList(
            Person("Samantha Stuart", 34),
            Person("Tom Marks", 42),
            Person("Stuart Gills", 17),
            Person("Nicole Williams", 27))

    @Test
    fun filterTest() {
        val data = SortedFilteredList(persons)
        data.predicate = { it.name.contains("Stu")}
        Assert.assertEquals(2, data.size)
    }
```

**Comment by thomasnield** [comment]
This is pretty convenient. It always felt odd doing all that work to created sorted and filtered lists.

**Comment by edvin** [comment]
It seems to work great, though it is one of the very few wrapper classes in TornadoFX. I liked the idea of just extending existing API's, but that's not always possible :)
