### ISSUE TITLE
Use and() instead as it's clearer

### ISSUE THREAD

**Issue by jerlowliu** [edvin/tornadofx#623]
add(hover){
      backgroundColor += Color.ALICEBLUE
 }

How to use?

**Comment by edvin** [comment]
I don't understand the question?

**Comment by tieskedh** [comment]
In Kotlin a deprecation can often be replaced by a quick-fix.
In this case it's also the case.
When you do, you get the following code:

```
and(hover){
    backgroundColor += Color.ALICEBLUE
}
```

I hope I helped.
