### ISSUE TITLE
Async run never stops

### ISSUE THREAD

**Issue by ValeriusGC** [edvin/tornadofx#625]
When I use runAsync {..} i see then process stay in memory after closing the app. Why?

![default](https://user-images.githubusercontent.com/3320861/35917066-85351494-0c2e-11e8-9dde-42fbcbfdf5d6.png)

**Comment by edvin** [comment]
I'm not sure I understand what you mean. You say that you see the process stay in memory after closing - so the app doesn't exit, is that it? Please supply a minimal running sample if possible.

**Comment by ValeriusGC** [comment]
[Here is the sample.](https://gist.github.com/ValeriusGC/9ee5d5b00ee9ba5f4fe7ca26761d0eeb)

All is easy. When I close application it remains running as we can see thru red square button named 'stop' - it is active. This abnormality happens only when i use `runAsync` and vanishes when i remove it.

**Comment by ValeriusGC** [comment]
[I recorded this behaviour ](https://youtu.be/h19JjAZ-_zQ)
[for another sample](https://gist.github.com/ValeriusGC/e9201f78b21cc3c8758a8a1467899306)

**Comment by edvin** [comment]
This bug was fixed a while back - what version are you running against?

I tested now with tornadofx-1.7.15-SNAPSHOT and it exits correctly.

By the way, you can launch with `launch<MyApp>(args)` instead in your `main` function :)

**Comment by edvin** [comment]
Oh, and by the way, we have built ins for padding, so instead of `padding = Insets(5.0)` you can say `paddingAll = 5` :)

**Comment by ValeriusGC** [comment]
Ohhh, my maven can not resolve nor `'tornadofx-1.7.15-SNAPSHOT'`,  nor `'1.7.15-SNAPSHOT' `
Please give correct artefact ID...

**Comment by edvin** [comment]
Artifact ids are the same, but they are not in maven central, you need to include oss.sonatype.org as a snapshot repo in your build, info on the README page for the project.

**Comment by ValeriusGC** [comment]
well, i tested just now with 1.7.14 and it seems all is ok....

**Comment by edvin** [comment]
Great :) 1.7.15 will be out this week as well.
