### ISSUE TITLE
Allow additional configuration when opening a window with openWindow and openModal

### ISSUE THREAD

**Issue by Romanow88** [edvin/tornadofx#626]
Provide a way to modify a Scene created by Component#openWindow and Component#openModal before it is shown. 

For example: position on the screen / screens, full-screen, etc. 

I will try to provide a PR in the coming days for this.

**Comment by edvin** [comment]
What's wrong with overriding `onDock`?

**Comment by Romanow88** [comment]
You are quite right, that can be used, although it can be done only on a per view class basis.

Also, I am used to closures after creating nodes for config that I assumed that not having that for the window was just something that was just missed.

**Comment by edvin** [comment]
You can pass a configuration op to the find function actually, so this might fit your use case:

```kotlin
find<MyView>() {
    whenDocked { 
        // configure here
    }
    openModal()
}
```
If not, supply a code sample that illustrates what you find cumbersome and we'll see if we need to add something here :)

**Comment by Romanow88** [comment]
Was not aware that find accepts a closure. That works fine, thanks!

**Comment by edvin** [comment]
Great :) If you feel that the syntax is cumbersome we can for sure look for alternatives :)
