### ISSUE TITLE
EventTarget.plusAssign not correct compile

### ISSUE THREAD

**Issue by lightway82** [edvin/tornadofx#633]
```
class MyView : View() {
    override val root = VBox()
    init {
        with(root) {
           this += Button("Press Me")
        }
    }
}
```
Compilation error!
 Type inference failed: fun <T : UIComponent> EventTarget.plusAssign(type: KClass<T>): Unit
cannot be applied to receiver: VBox  arguments: (Button)

For some reason, the compiler chooses the version of "plusAssign" with the KClass <T> parameter instead of the Node !!!

kotlin version 1.2.21

**Comment by edvin** [comment]
You probably imported `java.awt.Button` instead of `javafx.scene.control.Button`. But why on earth are you writing the code this way? This is how it should be written:

```kotlin
class MyView : View() {
    override val root = vbox {
        button("Press me")
    }
}
```

**Comment by lightway82** [comment]
import javafx.application.Application
import javafx.scene.control.Button
import javafx.scene.layout.VBox
import tornadofx.*

fun main(args: Array<String>){
    Application.launch(MyApp::class.java, *args)
}

class MyApp: App(MyView::class)

class MyView : View() {

    override val root = VBox()

    init {
        with(root) {
           this += Button("Press Me")
        }
    }
}

Very strange, I installed the TornadFX plug-in for Idea and after rebooting everything worked!

**Comment by edvin** [comment]
OK. In any case, please don't use that syntax :) See my previous post :)

**Comment by lightway82** [comment]
Ок :)
