### ISSUE TITLE
Inline property bindings randomly stop working

### ISSUE THREAD

**Issue by wulf0r** [edvin/tornadofx#638]
I have this data class called ImageOptions that I want bound to checkboxes. I don't really want to use JavaFX properties because to be honest they are disgusting, even with the nice syntax that tornadofx adds. So I am doing this:
```
class ImageOptionsForm : Fragment() {
    val imageProcessor: ImageProcessor by param()
    private val imageOptions = imageProcessor.imageOptions

    val bindingChromaKey = imageOptions.observable(ImageOptions::chromaKey)

    override val root = hbox {
            checkbox("chromaKey",bindingChromaKey)
            checkbox("Chromakey with Hitscan", imageOptions.observable(ImageOptions::chromaKeyWithHitScan))

            button("Vorschau").action {
                println("${imageOptions}")
                imageProcessor.processAll()
            }
    }
}
```
And when I use the checkboxes and press the button a bunch of times I can see that the second binding for ImageOptions::chromaKeyWithHitScan stop working apparently randomly. 

ImageOption is a plain old Kotlin data class with both booleans being contructor params

**Comment by bekwam** [comment]
Can you try making a class reference (ex, "val bindingChromaHitScan") for the second checkbox?   I wonder if the handler might be GCed as in this post.

http://bekwam.blogspot.com/2015/08/invalidationlistener-not-called.html

**Comment by wulf0r** [comment]
If I do it that way (the same way as bindingChromaKey ) then I can't get it to stop working anymore. Also if I take out the image processing it takes a lot longer to stop working which would support the theory that GC is involved

**Comment by edvin** [comment]
Yeah, pretty sure @bekwam is correct. Another down side to fighting the nature of JavaFX. UI components are meant to be used with observable values, and hacks like this just makes it harder on yourself IMO.

**Comment by bekwam** [comment]
We usually bind JavaFX properties to UI properties.  For example, binding "name : StringProperty" to "txtName.textProperty()".  A consequence of this is that the JavaFX properties are usually in a class and a collection that stay around in terms of references.  Similarly, you have the immutable reference to the observable for bindingChromaKey which is available for the life of the fragment.

The hitscan observable can fall out of scope and become eligible for garbage collection.

**Comment by wulf0r** [comment]
Thanks for the help guys, I appreciate it. I take your point about fighting the nature of JavaFX. Will reconsider the use of properties.

**Comment by edvin** [comment]
Great explanation, @bekwam :) Yeah, have another look at properties, I don't think they will get in your way much, but they will be a great help when wiring up your UI's. One thing is avoid the bugs, but many of the builders simply require or at least works a lot better with properties.

**Comment by wulf0r** [comment]
It's just the endless repeating of what is already know that's annoying about them. I can't believe nobody made a lombok style bytecode generator for them yet ;)

Is this okay for keeping the properties? (It works for now but it's not like in the docs so maybe I am missing something again :)

```
data  class ImageOptions(
    var autoRotate : Boolean = true,
    var scale : Boolean = true,
    var sharpen : Boolean = true,
    var scaleWidth : Int = 667,
    var scaleHeight : Int = 1000,
    var chromaKey : Boolean = false,
    var chromaKeyWithHitScan :Boolean = false,
    var backgroundPortrait : SchnieselImage = SchnieselImage.from(File("testui/background_portrait.jpg")),
    var backgroundLandscape :SchnieselImage = SchnieselImage.from(File("testui/background_landscape.jpg"))
){

    val chromaKeyWithHitScanProperty = observable(ImageOptions::chromaKeyWithHitScan)
    val chromaKeyProperty = observable(ImageOptions::chromaKey)
    val sharpenProperty = observable(ImageOptions::sharpen)


    companion object {
        val NOP = ImageOptions(false, false, false, 0, 0, false, false)
    }


    override fun toString(): String {
        return "ImageOptions(autoRotate=$autoRotate, scale=$scale, scaleWidth=$scaleWidth, scaleHeight=$scaleHeight, chromaKey=$chromaKey, chromaKeyWithHitScan=$chromaKeyWithHitScan)"
    }

}
```

**Comment by edvin** [comment]
You can create your class just like you did and use the idea plugin to automatically convert the properties into javafx properties at the click of a button.

**Comment by wulf0r** [comment]
I saw this but unfortunately it crashes my intellij. It probably wasn't a great idea to learn all three of kotlin+javafx+tornadofx in a new IDE intellij at the same time. I am running into a lot of walls :D

Thanks again, for your help, for making tornadofx which is really cool as well as your videos on youtube which have been invaluable :)

**Comment by edvin** [comment]
Haha, that can be a lot to take on for sure. I was able to reproduce the crash actually, so something is wrong with the plugin. You can get around the bug by not giving default values, and then adding them in after the conversion :)
