### ISSUE TITLE
Redux and TornadoFX ?

### ISSUE THREAD

**Issue by Lakedaemon** [edvin/tornadofx#649]
Hello, 
Is there a nice way to make TornadoFX play nice with the redux api ?

I found ReduxFX on the internet, but this is a Java library. I would like to implement a kotlin solution, if possible.

For the store library, I'm using https://github.com/pardom/redux-kotlin
Best regards, 
Olivier

**Comment by edvin** [comment]
I think the redux pattern is in direct contradiction with how JavaFX is created (in many areas), and probably not a good idea. I'm aware of efforts to implement this pattern using JavaFX, but you end up working against the toolkit and missing out on some of it's most important strengths. I don't see redux  as interesting (or at all a good idea) for TornadoFX :)

**Comment by Lakedaemon** [comment]
I see. Thanks for the explanation. This is why I didn't find many links for this stuff on the internet

I'm hoping to implement a multi-platform kotlin app (jvm + android, ios through native ?, browser) app that decouple app state from the ui. So, I'll probably have to forsake the strenghts of JavaFX to only enjoy what is common on all these plaftforms, sadly... :/

**Comment by edvin** [comment]
You absolutely don't need redux for that :) Take a look at this multi platform kotlin app which also has a TornadoFX implementation:

https://github.com/MarcinMoskala/KotlinAcademyApp

**Comment by Lakedaemon** [comment]
Thanks for the pointer. I'll look at that and reevaluate my needs. Many thanks :)

**Comment by edvin** [comment]
Happy to help. If you end up using TornadoFX for the desktop version you should join us on Slack if you need help under way. I'm curious as to how you ended up with the impression that you needed redux to share state between multiplatform apps though.. or did I misunderstand you?

**Comment by Lakedaemon** [comment]
Sure, I'll do. I still want to use tornadoFX if I can.

I have been doing android app development the last 6 years and for my apps, I was using presenters and a library that changed views depending on which state the app was in (working solution but not completely satisfying, there are a lot of things and complexity that you have to handle concerning app state and view state restoration for android, considering an app can be destroyed or put in the background at any time). 

For my next projects, I would like to have 
- 1 source of truth for app state in the pure kotlin layer (responsible for saving/restoring it)
- use this to drive the ui scene changes
- let the ui layer handle the view state saving/restoration (for android, this might not be necessary for other platforms)
- have simple presenters and have views as dumb as they can get  (especially if I have toi implement that for many platforms), handling only ui related stuff

So I was thinking that that (redux-like) immutable state and reducers  might help me achieve a simpler architecture while solving all my issues

**Comment by edvin** [comment]
That should all be pretty easy to achieve with TornadoFX :) In fact I think you'll find solutions for most of those in the sample I linked to. If something is missing be sure to join us on Slack and we'll help you through it :)
