### ISSUE TITLE
readonly csspseudoclass?

### ISSUE THREAD

**Issue by ethanmdavidson** [edvin/tornadofx#650]
I would like to apply styling (grey background) to all textfield elements that are readonly. I can accomplish this by creating a stylesheet like this:
```Kotlin
class MyStyle: Stylesheet() {
	companion object {
		val readOnly by cssclass()
		val readOnlyColor = c("#d3d3d3")
	}
	
	init {
		readOnly {
			backgroundColor += readOnlyColor
		}
	}
}
```
but this requires me to addClass(MyStyle.readOnly) on every readonly text field, and it ends up like:

```Kotlin
textfield().addClass(MyStyle.readOnly).bind(myProperty, readonly=true)
```
which bugs me because then I have to say twice that it's readonly. (MyStyle.readOnly and readonly=true)

It seems like I should be able to do something like this:
```Kotlin
class MyStyle: Stylesheet() {
	companion object {
		val readOnlyColor = c("#d3d3d3")
	}
	
	init {
		s(textField) {
			and(readonly) {
				backgroundColor += readOnlyColor
			}
		}
	}
}
```
but there is no readonly csspseudoclass in CSS.kt. In the JavaFX css spec, there is a readonly pseduoclass defined for [TextInputControls](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html#textinputcontrol).

I also tried using the "editable" pseudoclass, but that didn't seem to have any effect (styling was not applied to any fields regardless of their readonly designation in the binding)

What is the proper way to apply styling to all elements which are readonly?

I'm new to JavaFX and Kotlin so it's very possible that I'm missing something.

**Comment by edvin** [comment]
This looks like an oversight on our part, but luckily you can add the pseudoclass to your stylesheet like this:

```kotlin
val readonly by csspseudoclass()
```

@ruckustboom Can you see a reason not to include this pseudoclass by default?

**Comment by ethanmdavidson** [comment]
Unfortunately, that doesn't appear to be working either. I think there might be an issue in JavaFX because the css reference lists the "readonly" pseudoclass under TextInputControls, but the [TextInputControls javadoc](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TextInputControl.html#editableProperty) lists "editable" and not "readonly", so that seems strange (unless I misunderstand and these are two separate things). Additionally, even when I use the "editable" pseudoclass it has no effect even when I explicitly call setEditable(true) on the textField. I know the selector is working correctly because the "hover" pseudoclass works as expected. Is there an example that uses these pseudoclasses? If not I'll try to knock together a demo tonight.

**Comment by edvin** [comment]
When you set editable to false, the textfield automatically gets the `readonly` pseudoclass. You don't need to specify the `readonly` parameter to bind, and in fact you should not use bind at all, since the textfield builder accepts the property to bind against. All you need to do is:

```kotlin
textfield(myProperty) {
    isEditable = false
}
```

The textfield will now have the `readonly` pseudo class, so the selector from your stylesheet will be applied.

**Comment by ethanmdavidson** [comment]
Awesome, that works perfectly for me. I'm going to leave this open for the issue of it not being in the default set, but the workaround you provided solves my problem so you can close it if you want.

**Comment by edvin** [comment]
Great! I'm awaiting feedback from @ruckustboom - there might be a reason for it not being added by default :)

**Comment by ruckustboom** [comment]
It looks like it was just an oversight on my part (or, if there was a good reason, I no longer remember it), and it looks like there may be several others (e.g. `cancel` for buttons). We may want to go through and see what else is missing. Should we create another task for that?

**Comment by ruckustboom** [comment]
Actually, come to think of it, I may have collected the pseudoclasses from `modena.css` instead of the official docs for some reason, so, in addition to missing some from the docs, we may have included some not in the docs but used by modena.

**Comment by edvin** [comment]
Sweet, thanks for the clarification. I added `readonly` and `cancel` now. If you have time we can add another task to look through the rest :)

**Comment by edvin** [comment]
#653 is merged, so we have both a fix and a workaround in place :) Great work!
