### ISSUE TITLE
StageStyle.TRANSPARENT

### ISSUE THREAD

**Issue by azkdev** [edvin/tornadofx#651]
I can't create transparent window for my new app.
Is StageStyle.TRANSPARENT working properly ?

```
class CircleArt : App(MainView::class) {
    override fun start(stage: Stage) {
        stage.isResizable = false
        stage.centerOnScreen()
        stage.initStyle(StageStyle.TRANSPARENT)
        super.start(stage)
    }
}
```

I need transparent background for below window.

![](https://i.imgur.com/6STcfuI.png)

Sorry for my English and thank you in advice ;)

**Comment by edvin** [comment]
There is actually 3 pieces to this puzzle:

1. Set the stage style to StageStyle.TRANSPARENT
2. Set the scene.fill to Color.TRANSPARENT
3. Set the backgroundColor of the main view root node to Color.TRANSPARENT

Here is a complete example:

```kotlin
class MainView : View("Main View") {
    override val root = stackpane {
        setPrefSize(200.0, 400.0)
        style {
            backgroundColor += Color.TRANSPARENT
        }
        label("Welcome")
    }
}

class TransparentApp : App(MainView::class) {
    override fun start(stage: Stage) {
        stage.initStyle(StageStyle.TRANSPARENT)
        super.start(stage)
    }

    override fun createPrimaryScene(view: UIComponent) = super.createPrimaryScene(view).apply {
        fill = Color.TRANSPARENT
    }
}
```

**Comment by azkdev** [comment]
Thank you.
This is working perfectly.
