### ISSUE TITLE
Unpredictable behaviour of node with imageview inside

### ISSUE THREAD

**Issue by ValeriusGC** [edvin/tornadofx#654]
Why this code
```java
override val root = vbox {
    imageview {
        image = Image("/pics/godmode.jpg")
    }
}
```
leads to
![image](https://user-images.githubusercontent.com/3320861/36831890-34d8d156-1d4b-11e8-87e7-4fa9cdf3f464.png)

but **that code**
```java
override val root = vbox {
    imageview("/pics/godmode.jpg") { }
}
```
leads to
![image](https://user-images.githubusercontent.com/3320861/36831948-757e8548-1d4b-11e8-96bc-76813a4921f4.png)

and **that code**
```java
override val root = vbox {
    imageview("/pics/godmode.jpg") { }
    button("Button") {}
}
```
leads to
![image](https://user-images.githubusercontent.com/3320861/36831990-a2752584-1d4b-11e8-81e6-b19cdb999a56.png)

**Comment by edvin** [comment]
It's not unpredictable at all :) The reason is that our `imageview` builder will lazy load the image, while your code is actually blocking the UI thread while loading the image, which normally is not a good idea to do. You can pass `lazyload = false` to the `imageview` builder to achieve the same effect, but that's discouraged for obvious reasons :)

**Comment by ValeriusGC** [comment]
Aaaa! Got it, thanxxx, Edvin. There are cases when the image should be shown immediately, e.g. on the splash-screen, so `lazyload` must be set to `false` then.

***
BTW,  it would be coolest thing to have the API doc... In my **IntelliJ IDEA** i see only that:
![image](https://user-images.githubusercontent.com/3320861/36884120-8458cc30-1e00-11e8-8510-d55ccf61b732.png)

I think that it would eliminated huge part of simple questions, wouldn't it?

**Comment by edvin** [comment]
Even for a splash screen it would be best to avoid this, as you actually freeze the UI while loading the image. You have two options if you want to do it right:

1. Hard code the splash screen size to the size you know the image will be.
2. If you need to adapt to different sizes, add a listener to the loading process of the image and resize after it's done.

Most splash screens I've seen actually require you to supply a spesific size image, so even option 1 would be OK in most situations I think :)

**Comment by ValeriusGC** [comment]
Thanks a lot for advise, it's very kind of you. Look, Edvin, along with a stream of issues and questions there are many useful recipes are born. How would to accumulate them in some kinda 'Book of recipe', or something that is powered with tags or keywords... I suspect that this framework has many more artifacts and hidden treasures that we can understand via reading laconic documentation...

**Comment by edvin** [comment]
I'm glad you asked. We actually want to add a third part to the [guide](https://edvin.gitbooks.io/tornadofx-guide/) to collect recipies like this. I guess we just need to get the initiative started. I will set up a Part 3 right away, a PR against the guide (https://github.com/edvin/tornadofx-guide) would be most welcome!

**Comment by ValeriusGC** [comment]
well ok, will do some PR for that one.

**Comment by edvin** [comment]
Fantastic, thanks :) Part 3 and a snippets file is added to the project now :)
