### ISSUE TITLE
(QUESTION) Canvas example.

### ISSUE THREAD

**Issue by azkdev** [edvin/tornadofx#655]
Hi edvin,
Can you show us an expressive example of using canvas with animations.
I can't figure it out, so a little example is welcome.

Help me to solve this little puzzle. Thank you in advice ;)

**Comment by edvin** [comment]
The only Canvas related support in TornadoFX is the `canvas` builder. Apart from that, you have to deal with the Canvas API as it is, though with Kotlin syntax :)

**Comment by azkdev** [comment]
Oh, I see.  
Thank you.  
Now I know how to implement canvas.  
Question closed.
