### ISSUE TITLE
Beans are such a royal PITA, can they be simplified further?

### ISSUE THREAD

**Issue by yay** [edvin/tornadofx#657]
Making beans and using them is such an error-prone and repetitive process I wrote some functions to help with this:

```kotlin
import kotlin.reflect.KClass
import kotlin.reflect.full.declaredMemberProperties

// Takes a data class definition and produces one for the bean.
fun getFxBeanDefinition(klass: KClass<*>): String {
    val indent = " ".repeat(4)
    val kclassProps = klass.declaredMemberProperties
    val beanConstructor = kclassProps.map { prop ->
        "${indent}${prop.name}: ${prop.returnType.toString().split(".").last()}"
    }
    val beanProps = kclassProps.map { prop ->
        "${indent}var ${prop.name}: ${prop.returnType.toString().split(".").last()} by property(${prop.name})\n" +
        "${indent}fun ${prop.name}Property() = getProperty(${klass.simpleName}Bean::${prop.name})\n"
    }
    return "open class ${klass.simpleName}Bean(\n" +
        beanConstructor.joinToString(",\n") + "\n) {\n" +
        beanProps.joinToString("\n") + "}"
}

// Takes a data class and creates a tableview creation code
// that uses the bean generated by the above function.
fun getFxBeanTableView(klass: KClass<*>): String {
    val beanName = "${klass.simpleName}Bean"
    val indent = " ".repeat(4)

    return "tableview(listOf<$beanName>().observable()) {\n" +
        klass.declaredMemberProperties.map { prop ->
            "${indent}column(\"${prop.name.capitalize()}\", $beanName::${prop.name}Property)"
        }.joinToString("\n") +
        "\n}"
}

// Takes a data class and generates a method that transforms it to a corresponding bean.
fun getBeanMaker(klass: KClass<*>): String {
    val indent = " ".repeat(4)

    return "fun ${klass.simpleName}.to${klass.simpleName}Bean() =\n" +
        "$indent${klass.simpleName}Bean(\n" +
        klass.declaredMemberProperties.map { prop ->
            "$indent$indent${prop.name} = this.${prop.name}"
        }.joinToString(",\n") +
        "\n$indent)"
}
```

For example, given this class:

```
data class DayChartPoint(
    val date: Date,
    val open: Double,
    val high: Double,
    val low: Double,
    val close: Double,
    val volume: Long,
    val unadjustedVolume: Long,
    val change: Double,
    val changePercent: Double,
    val vwap: Double,
    val label: String,
    val changeOverTime: Double
)
```

we can now generate:

```
open class DayChartPointBean(
    change: Double,
    changeOverTime: Double,
    changePercent: Double,
    close: Double,
    date: Date,
    high: Double,
    label: String,
    low: Double,
    open: Double,
    unadjustedVolume: Long,
    volume: Long,
    vwap: Double
) {
    var change: Double by property(change)
    fun changeProperty() = getProperty(DayChartPointBean::change)

    var changeOverTime: Double by property(changeOverTime)
    fun changeOverTimeProperty() = getProperty(DayChartPointBean::changeOverTime)

    var changePercent: Double by property(changePercent)
    fun changePercentProperty() = getProperty(DayChartPointBean::changePercent)

    var close: Double by property(close)
    fun closeProperty() = getProperty(DayChartPointBean::close)

    var date: Date by property(date)
    fun dateProperty() = getProperty(DayChartPointBean::date)

    var high: Double by property(high)
    fun highProperty() = getProperty(DayChartPointBean::high)

    var label: String by property(label)
    fun labelProperty() = getProperty(DayChartPointBean::label)

    var low: Double by property(low)
    fun lowProperty() = getProperty(DayChartPointBean::low)

    var open: Double by property(open)
    fun openProperty() = getProperty(DayChartPointBean::open)

    var unadjustedVolume: Long by property(unadjustedVolume)
    fun unadjustedVolumeProperty() = getProperty(DayChartPointBean::unadjustedVolume)

    var volume: Long by property(volume)
    fun volumeProperty() = getProperty(DayChartPointBean::volume)

    var vwap: Double by property(vwap)
    fun vwapProperty() = getProperty(DayChartPointBean::vwap)
}

fun DayChartPoint.toDayChartPointBean() =
    DayChartPointBean(
        change = this.change,
        changeOverTime = this.changeOverTime,
        changePercent = this.changePercent,
        close = this.close,
        date = this.date,
        high = this.high,
        label = this.label,
        low = this.low,
        open = this.open,
        unadjustedVolume = this.unadjustedVolume,
        volume = this.volume,
        vwap = this.vwap
    )

iexSymbolTable = tableview(listOf<DayChartPointBean>().observable()) {
     column("Date", DayChartPointBean::dateProperty)
     column("Open", DayChartPointBean::openProperty)
     column("High", DayChartPointBean::highProperty)
     column("Low", DayChartPointBean::lowProperty)
     column("Close", DayChartPointBean::closeProperty)
     column("Volume", DayChartPointBean::volumeProperty)
     column("Change", DayChartPointBean::changeProperty)
     column("ChangePercent", DayChartPointBean::changePercentProperty)
     column("ChangeOverTime", DayChartPointBean::changeOverTimeProperty)
     column("Label", DayChartPointBean::labelProperty)
}
```

Then finally do:

```
runAsyncWithProgress {
     IexApi.getDayChart("AAPL").map { dayChartPoint ->
          dayChartPoint.toDayChartPointBean()
     }
} ui { beanList ->
     iexSymbolTable.items = beanList.observable()
}
```

It's easier now, but fundamentally it still feels unnecessarily complicated.

I wonder if there's a better way to do it already or plans to try to improve it?

**Comment by edvin** [comment]
This functionality is already built into the TornadoFX IDEA Plugin. Simply Alt-Enter (Meta-Enter) on a class name and choose "Convert all properties to TornadoFX Properties" and the class will be reorganized automatically. You can also convert individual properties. It even recognizes data class properties and constructor defined properties.

There is also a quick fix for adding table columns to a TableView, as long as the type parameter to TableView is given, or can be extracted from the list property via the tableview builder constructor.

Moreover, you are using the old syntax for properties, which is just ugly and cumbersome to create. The new syntax, which is described in the guide and used by the IDEA plugin by default is much nicer :)

**Comment by yay** [comment]
Thank you. It's much easier this way indeed!

I only can't make the plugin add the columns to the view I create, the IDE doesn't show a hit for that.

For example:

<img width="685" alt="screen shot 2018-03-04 at 16 28 46" src="https://user-images.githubusercontent.com/1799756/36946150-651d7c1a-1fc9-11e8-8729-ac1de6891bdc.png">

The table view above was defined manually, and I'm trying to auto-generate the columns for the one below by pressing Alt-Enter on the `tableview`, and only see these options:

<img width="374" alt="screen shot 2018-03-04 at 16 32 14" src="https://user-images.githubusercontent.com/1799756/36946165-a9d18e14-1fc9-11e8-90bd-0a4a294dc547.png">

**Comment by edvin** [comment]
I just tested this and it worked as expected for me. Can you post a complete runnable sample I can play with to figure out why it doesn't trigger correctly in your case?

**Comment by yay** [comment]
Ah, bummer. It looks like inside an annotation processor I can only see Kotlin classes compiled to their Java counterpart, and using Kotlin's own reflection is not possible there, which makes things difficult :\

**Comment by yay** [comment]
I just ran into what seemed like a weird issue: https://stackoverflow.com/questions/50376608/how-to-get-previous-table-cell-value-inside-cells-updateitem-method-in-javafx/50376889?noredirect=1#50376889

Turns out
```kotlin
class Foo {
    val barProperty = SimpleDoubleProperty()
    var bar by barProperty
}
```
isn't enough. It should be
```
class Foo {
    val barProperty = SimpleDoubleProperty()
    fun barProperty() = barProperty
    var bar by barProperty
}
```

If the `fun barProperty() = barProperty` part is missing, updating the value of bar (for example, `(tableRow.item as Foo).bar++`) won't produce a visible change in the table view without manually refreshing it. Replacing a Foo instance with another one that has its `bar` value change will make the view to auto-refresh, but then it won't be possible to get the old value of the cell.

**Comment by yay** [comment]
Or rather
```kotlin
class Foo {
    val _barProperty = SimpleDoubleProperty()
    fun barProperty() = _barProperty
    var bar by _barProperty
}
```
so that we can still do
`column("Bar", Foo::barProperty)`

**Comment by yay** [comment]
Another minor thing is that properties in the generated class go in reverse order, compared to the original class.

**Comment by gtnarg** [comment]
The documentation indicates the following:

class Bar {
    var foo by property<String>()
    fun fooProperty() = getProperty(Bar::foo)
}

Especially as you start working with TableView and other complex controls,
you will likely find this pattern helpful when creating model classes, and
this pattern is used in several places throughout this book.

Regards,
Grant

On Thu, May 17, 2018 at 1:36 PM, Vitaly Kravchenko <notifications@github.com

**Comment by yay** [comment]
Ah, yeah, I remember seeing this pattern too.

Well, that's not what the plugin generates anyway. So everything I said pretty much still applies.

**Comment by yay** [comment]
Also, I didn't use JMH, but maybe in this case I don't have to:

```
class Foo {
    val barProperty = SimpleDoubleProperty()
    fun barProperty() = barProperty
    var bar by barProperty

    var baz by property<Double>()
    fun bazProperty() = getProperty(Foo::baz)
}

fun main(args: Array<String>) {
    val foo = Foo()
    foo.bar = 40.0
    foo.baz = 42.0

    for (i in 0..10) {
        val barTime = measureNanoTime {
            for (i in 0..1000_000) {
                val bar = foo.barProperty()
            }
        }
        println("bar time: $barTime")

        val bazTime = measureNanoTime {
            for (i in 0..1000_000) {
                val baz = foo.bazProperty()
            }
        }
        println("baz time: $bazTime")
    }
}
```

My results are as follows:
```
bar time: 6140188
baz time: 305468147
bar time: 4835881
baz time: 229540529
bar time: 78
baz time: 177066072
bar time: 79
baz time: 350360667
bar time: 79
baz time: 139698052
bar time: 80
baz time: 209936234
bar time: 71
baz time: 382601347
bar time: 68
baz time: 129627237
bar time: 41
baz time: 122897555
bar time: 52
baz time: 124245613
bar time: 47
baz time: 123397556
```

**Comment by yay** [comment]
If you replace `1000_000` with `10_000_000` the difference shrinks to "only" 3 orders of magnitude :)

**Comment by edvin** [comment]
You should use the syntax the plugin uses, the one @gtnarg posted is the old syntax. The new is faster and better :) It works if you update `(tableRow.item as Foo).barProperty)` with a new value, right?

**Comment by edvin** [comment]
I'm not sure what you're doing in your code, but I can assure you that the new syntax is indeed enough to update the TableView when you give a new value through the `var`:

```kotlin
class Foo(name: String, num: Int) {
    val nameProperty = SimpleStringProperty(name)
    var name by nameProperty

    val numProperty = SimpleIntegerProperty(num)
    var num by numProperty
}

class FooTest : View() {
    val foos = FXCollections.observableArrayList<Foo>(
            Foo("Foo 1", 1),
            Foo("Foo 2", 2),
            Foo("Foo 3", 3)
    )

    override val root = borderpane {
        center {
            tableview(foos) {
                column("Name", Foo::nameProperty)
                column("Num", Foo::numProperty)
            }
        }
        bottom {
            buttonbar {
                button("Set Foo 2 num to 42").action {
                    foos[1].num = 42
                }
            }
        }
    }
}
```

If you're using the pattern above, everything should work. If it doesn't for you, please post a minimal code sample that displays the issue you're having :)

**Comment by yay** [comment]
Sorry that this got somewhat off topic :) and thank you for posting your sample.

I figured out the reason - it doesn't work, if I don't use the DSL. Here is my minimal example:

```kotlin
// Only the column created using DSL updates.
class Entity(size: Double) {
    val sizeProperty = SimpleDoubleProperty(size)
    var size by sizeProperty
}

// Both columns update.
// class Entity(size: Double) {
//     val _sizeProperty = SimpleDoubleProperty(size)
//     fun sizeProperty() = _sizeProperty
//     var size by _sizeProperty
// }

class TestView : View() {
    val entities = FXCollections.observableArrayList<Entity>(Entity(5.0))
    override val root = vbox {
        tableview(entities) {
            // DSL column
            column("Size", Entity::sizeProperty)
            
            // Old school column
            val sizeColumn = TableColumn<Entity, Double>("Size")
            sizeColumn.cellValueFactory = PropertyValueFactory<Entity, Double>("size")
            columns.add(sizeColumn)
        }
    }

    init {
        launch {
            while(isActive) {
                delay(1000)
                runLater {
                    entities.first().size += -1.0 + Math.random() * 2.0
                }
            }
        }
    }
}

class TestApp: App(TestView::class)

fun main(args: Array<String>) {
    Application.launch(TestApp::class.java, *args)
}
```

Ideally, beans should work with both DSL and non-DSL code. As far as I can tell, my non-DSL code is perfectly valid, but could be wrong, I'm still quite new to JavaFx :)

**Comment by bekwam** [comment]
Do you want to deconstruct the TableView so that you can use the JavaFX style?

`        val entities = mutableListOf<Entity>()
        val tv = TableView<Entity>(entities.observable())
        add( // add to container root object
                tv
        ) 
        val sizeColumn = TableColumn<Entity, Double>("Size")
        sizeColumn.cellValueFactory = PropertyValueFactory<Entity, Double>("size")
        tv.columns.add( sizeColumn )`

**Comment by yay** [comment]
Sure, I can remove DSL from everywhere and use just the `by` infix function in the `Foo` bean, but the table won't update.

**Comment by bekwam** [comment]
Is this what you're looking for?  There's no builder function and the button action will update an Entity's contents and add an Entity to the TableView

```kotlin
class TableTestView : View("Table Test") {

    val globalEntity = Entity(3.0)

    override val root = vbox {

        val entities = mutableListOf(
                Entity(1.0),
                Entity(2.0),
                globalEntity
        ).observable()

        val tv = TableView<Entity>(entities)
        add(
                tv
        )
        val sizeColumn = TableColumn<Entity, Double>("Size")
        sizeColumn.cellValueFactory = PropertyValueFactory<Entity, Double>("size")
        tv.columns.add( sizeColumn )

        button("Update Table") {
            setOnAction {
                globalEntity.size = 5.0
                entities.add(Entity(100.0))
            }
        }
    }
}

**Comment by edvin** [comment]
You need to create beans with getter/setter and function for each property if you want to use `PropertyValueFactory` that takes a string as property name, but why on earth would you want to use that? We have much better constructs inside the `column` builder. If you really have a valid use case for using the `PropertyValueFactory` with a string parameter, you'd have to adhere to the (pointless) javafx style property rules.

**Comment by yay** [comment]
I don't like that I have to use strings there either. It's just that I haven't found a way to pass a custom `cellFactory` to the `column` builder. So I did it the old school way:

```kotlin
TableColumn<Entity, Double>("Size").apply {
    setCellValueFactory { it.value.sizeProperty().asObject() }
    setCellFactory {
        ChangeBlinkTableCell<Entity, Double>(naturalOrder(), { "%.2f".format(it) })
    }
    table.columns.add(this)
}
```

I can create my own `column` builder that allows this, and I probably will eventually. For now I see that `setCellValueFactory { it.value.sizeProperty.asObject() }` works perfectly and I much prefer that to the strings based approach.

**Comment by yay** [comment]
@bekwam It only updates because you are also adding an entity to the list, as well as changing the size property of the entity already in the list. If you only do that latter, the tableview won't update. Thank you, though.

@edvin Thank you for your valuable comments. I will now close this, as I wasn't able to reproduce the original issue (probably was a single time IDE quirk).

**Comment by bekwam** [comment]
You're right. I need a property for my example.

**Comment by edvin** [comment]
You misunderstand the context of the builder @yay :) When you do  `column() { ... }`, you're operating on the TableColumn instance, so you can set your cellfactory there:

```kotlin
column("Name", Person::nameProperty) {
    setCellFactory { ... }
}
```
That being said, when you need custom cell factories you should look into the TableCellFragment instead. It's much more robust and powerful than a cell factory.
