### ISSUE TITLE
Performance anomaly in Bean const 

### ISSUE THREAD

**Issue by wulf0r** [edvin/tornadofx#659]
Hi Guys,

I am having a /weird/ issue in my bean. The constructor is always taking a glacial 1300ms (and I can feel that in the app, that's why I went looking):

Here is my bean:

```kotlin
data class Product( val images: ObservableList<ArtikelImage>) {
    enum class State {new}

    val nameProperty =  SimpleStringProperty()
    var name by nameProperty

    val idProperty = SimpleIntegerProperty()
    var id by idProperty
     // JsonAutoModel
    val spec: Spec by lazy {
        Performance.meassureAndReport("Spec const") {
            Spec()
        }
    }

    val imageOptions = ImageOptions()

    val fullNameProperty =  Bindings.concat(idProperty, " ", nameProperty)
    val fullName by fullNameProperty



    val isValid by lazy {
        Performance.meassureAndReport("isValid Bind") {
            spec.isValid().and(images.sizeProperty.greaterThan(0).and(nameProperty.isNotBlank()) )
        }
    }

    val state = State.new

}
```

I already cleanned it up a bit, previously I was using the alternative property style but there was no change.

So I am calling this from the Controller like

```kotlin
val product = Performance.meassureAndReport("produkt const") {
         Product(images)
}
```

And I get as a result:

> 2018-03-05 14:15:19,570 INFO [JavaFX Application Thread] (TornadoFXUtil.kt:23) produkt const took 1350 ms
> 2018-03-05 14:15:19,572 INFO [JavaFX Application Thread] (TornadoFXUtil.kt:23) Spec const took 0 ms
> 2018-03-05 14:15:19,656 INFO [JavaFX Application Thread] (TornadoFXUtil.kt:23) isValid Bind took 3 ms

I am not even sure this is related to tornadofx at all. Does anyone have a hint?

Thanks in advance and kind regards

**Comment by edvin** [comment]
Before I investigate, I want to make sure that this happens every time you initialize this bean in the same JVM? It's not just something that happens the first time, as the JavaFX environment initializes?

**Comment by wulf0r** [comment]
I was just investigating that actually. Yeah, the time goes down to about 500 ms when I create the next Product. Still long but much faster. Strange

**Comment by edvin** [comment]
I think you need to rip away one piece at a time to determine what's causing the delay. Alternatively, post a complete example so I can compile and run it, and I'll take a look myself :)

**Comment by nimakro** [comment]
Closing due inactivity
