### ISSUE TITLE
Issues with Property Calls and TableView

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#66]
I'm doing some home projects and testing out some functionality. I've got a really odd compilation error with IDEA when using some Property delegates with a `TableView`. 

Here is my domain class 

```kotlin
class ParsedTransaction(
        val transactionDate: LocalDate,
        val memo: String,
        val amount: BigDecimal

    ) {

    var categoryId: Int by property<Int>()
    var categoryIdProperty = getProperty(ParsedTransaction::categoryId)

    var accountId: Int by property<Int>()
    var accountIdProperty = getProperty(ParsedTransaction::accountId)

    var isTransfer: Boolean by property(false)
    var isTransferProperty = getProperty(ParsedTransaction::isTransfer)

    fun writeToDb() = db.update("INSERT INTO HARD_TRANSACTION (CATEGORY_ID,ACCOUNT_ID,TRANSACTION_DATE,AMOUNT,MEMO,TRANSFER_IND) VALUES (?,?,?,?,?,?)")
        .parameters(categoryId,accountId,transactionDate,amount,memo,isTransfer)
        .count()
}
```

Here is my `TableView` 

```kotlin
tableview<ParsedTransaction>() {
                isEditable = true
                column("TRANS DATE",ParsedTransaction::transactionDate)
                column("MEMO",ParsedTransaction::memo)
                column("AMOUNT",ParsedTransaction::amount)
                column("ACCOUNT ID", ParsedTransaction::accountIdProperty)
                column("IS TRANSFER",ParsedTransaction::isTransferProperty)
            }
```

It is a little difficult to get a self-contained runnable example. But does anything stand out that might cause the problem? stacktrace is attached also...

[stacktrace.txt](https://github.com/edvin/tornadofx/files/201015/stacktrace.txt)

**Comment by thomasnield** [comment]
Also if I strike these two columns and comment them out, everything works fine. Also confirmed that this does not happen with just the delegates but even `SimpleIntegerProperty` as well. 

```kotlin
column("ACCOUNT ID", ParsedTransaction::accountIdProperty)
column("IS TRANSFER",ParsedTransaction::isTransferProperty)
```

**Comment by thomasnield** [comment]
Yep, I'm having issues with even this simple, self-contained example.

```kotlin
class MyApp: App() {
    override val primaryView = MyView::class
}

class MyView: View() {

    override val root = VBox()

    init {
        with(root) {
           tableview<MyItem>() {
               isEditable = true
               items.setAll((1..10).map { MyItem(it) }.toList())
               column("NUMBER",MyItem::numberValueProperty)
               column("STRING",MyItem::stringValueProperty)
           }
        }
    }
}

class MyItem(numberValue: Int) {
    var numberValue: Int? by property<Int?>(numberValue)
    var numberValueProperty = getProperty(MyItem::numberValue)


    var stringValue: String? by property<String?>()
    var stringValueProperty = getProperty(MyItem::stringValue)
}
```

**Comment by edvin** [comment]
On it, will check right away and get back to you :)

**Comment by edvin** [comment]
The problem is that you did not define your JavaFX properties correctly. You're supposed to have a getter and setter for the value and a function that exposes the property, but you have a getter and a setter for the value AND a getter and a setter for the property, but no function that exposes the property.

Simply change `var numberValueProperty = getProperty(MyItem::numberValue)` to `fun numberValueProperty() = getProperty(MyItem::numberValue)` to be in compliance with the JavaFX properties spec, and everything should work :)

You're now hitting this column function:

```kotlin
column(title: String, prop: KProperty1<S, T>)
```

But you'd want to hit this:

```kotlin
TableView<S>.column(title: String, observableFn: KFunction<ObservableValue<T>>)
```

This one is supposed to match a getter/setter for a normal property, but in your case it matches a getter/setter for an observable.

I'll see if I can add an error message when this happens to avoid further confusion :)

For completeness, here is the correct way to define the JavaFX properties:

```kotlin
class MyItem(numberValue: Int) {
    var numberValue: Int? by property<Int?>(numberValue)
    fun numberValueProperty() = getProperty(MyItem::numberValue)

    var stringValue: String? by property<String?>()
    fun stringValueProperty() = getProperty(MyItem::stringValue)
}
```

**Comment by thomasnield** [comment]
Okay awesome, I forgot about this. Will check right now.

**Comment by edvin** [comment]
Since this happens at compile time, there is nothing I can do to provide a better explanation in the exception, but we could mention it in the docs :) Sorry for my clumsy explanation above, that was hard to articulate at this hour :) hehe

**Comment by edvin** [comment]
Side note: You don't need to add the type argument to the `property` declaration since it can be inferred from the type declaration. I've updated the answer above. Less code :)

**Comment by thomasnield** [comment]
Excellent, everything works now. Sorry for false alarm.

**Comment by edvin** [comment]
It was a very valuable lesson to learn, so I'm glad you stumbled upon it. Now we can warn users in the documentation, and I'll try to find a way to avoid the confusion all together. But first, a little sleep :)

**Comment by thomasnield** [comment]
Exactly what I was thinking, I'll document that clearly. Have a good night : )

**Comment by edvin** [comment]
You too, Thomas :)
