### ISSUE TITLE
Question: how can we remove default buttons from workspace?

### ISSUE THREAD

**Issue by Awais16** [edvin/tornadofx#666]
Hi, 
I plan to use workspace container and rather than disabling I wish to remove default buttons how it is done?

plus : community questions are preferred as issues or stackoverflow q's 😅 ?

**Comment by Awais16** [comment]
from Workspace source: root contains header toolbar whose items can be manipulated.

`root.header.items.remove(0,6)`

**Comment by edvin** [comment]
You can also remove them by name, they are defined like this in Workspace:

```kotlin
    var refreshButton: Button by singleAssign()
    var saveButton: Button by singleAssign()
    var createButton: Button by singleAssign()
    var deleteButton: Button by singleAssign()
    var backButton: Button by singleAssign()
    var forwardButton: Button by singleAssign()
```

Questions here is fine :)

**Comment by Awais16** [comment]
Thanks yes thats better.
`root.header.items.remove(deleteButton)`
but earlier I was trying
`deleteButton.removeFromParent()` 
I guess this method has nothing to do with the view hierarchy but events.

**Comment by edvin** [comment]
Maybe you called `deleteButton.removeFromParent()` before it was connected? Try doing it in `onDock`. Anyways, using `header.items.remove` is probably clearer as well.
