### ISSUE TITLE
How to open second window on button click

### ISSUE THREAD

**Issue by Trancever** [edvin/tornadofx#670]
Hello guys, i have a problem with creating second window. I want it to show on button click but I can't find information in docs. Can you help a little bit?

**Comment by edvin** [comment]
```kotlin
button("Open second window").action {
    find<OtherView>().openModal()
}
```

**Comment by Trancever** [comment]
Thanks a lot.

**Comment by edvin** [comment]
My pleasure. Did you read the guide? This should be covered there :)

**Comment by Trancever** [comment]
Yeah, maybe not all the content but first few sections I read and I didn't see oit mentioned. Thanks for help, issue can be closed if you want :)
