### ISSUE TITLE
Modal and internal windows are stop to close (suddenly)

### ISSUE THREAD

**Issue by ValeriusGC** [edvin/tornadofx#671]
It seems it has been working earlier (in january).
But suddenly i can not close it... 

```java
        button("Press me") {
            action {
                find(MyFragment::class).openModal(stageStyle = StageStyle.UTILITY)
                // It works here but i need some work before closing.
                close()
                runAsync {
                    println("sleepeng ${Thread.currentThread().name}")
                    // Emulates work
                    Thread.sleep(2000)
                    println("awaked")
                } ui {
                    println("about to close ${Thread.currentThread().name}")
                    // no any reaction
                    find(MyFragment::class).close()
                    // no any reaction
                    close()
                }
            }
        }

```

**Comment by edvin** [comment]
I'm not sure I understand exactly what issue you're facing, but I think what you want is to assign the myfragment instance to a variable so you can operate on it later:

```kotlin
val myFragment = find<MyFragment>()
myFragment.openModal()
...
myFragment.close()
```

**Comment by ValeriusGC** [comment]
Thanx, it works. 
Seems my issue was based on wrong understanding of documentation (see snippet below)

`Any Component opened using openModal(), openWindow() or openInternalWindow() can be closed by calling closeModal(). It is also possible to get to the InternalWindow instance directly if needed using findParentOfType(InternalWindow::class).`

**Comment by edvin** [comment]
Yes, but you didn't use `findParentOfType()`, which allows you to traverse up the hierarchy to find a certain view type. `find` just instantiates or retrieves an instance of a view, not coupled to the current hierarchy. Remember, fragments aren't singletons, so calling `find` will return a new instance every time.

**Comment by ValeriusGC** [comment]
You are right. Need to be more attentive, thanxxxx...
