### ISSUE TITLE
[Help needed] Getting selected cell content

### ISSUE THREAD

**Issue by abishai** [edvin/tornadofx#674]
I have a table with enableCellEditing(), I want to implement 'copy cell contents to clipboard' shortcut, however I double checked selectionModel and found no methods how to do this. I can get entire row, position of cursor (row, column), but no cell value and no transition from column number to properties mapping.

I've asked the same question on SO and got no replies yet. May I ask you to give me some hints?
Thanks.

**Comment by abishai** [comment]
Found the way, eventually
`			shortcut("Ctrl+C") {
				if (!selectionModel.isEmpty) {
					Clipboard.getSystemClipboard().putString(selectedColumn?.getValue(selectedItem).toString())
				}
			}`

**Comment by edvin** [comment]
TornadoFX has a built in clipboard helper as well :)
