### ISSUE TITLE
Changing chart plot background color

### ISSUE THREAD

**Issue by wambambizzle** [edvin/tornadofx#676]
I've been looking into the level of customization on the default charts. Doing some research on the oracle site I saw that there is a `chart-plot-background` attribute that can be used to change a charts plot background. However tornadofx doesn't seem to have a corresponding css prop like it does for `backgroundColor` or `backgroundImage` for example. 

Is there a way to utilize the `chartPlotBackground` style class that I am unaware of (found in the CSS.kt file)? Any feedback is greatly appreciated!

**Comment by ruckustboom** [comment]
`chart-plot-background` isn't an attribute, it's part of the substructure of the `XYChart`. If you want to set the background, you can do something like this:

```
chartPlotBackground {
    backgroundColor += c("red")
}
```

**Comment by wambambizzle** [comment]
Thank you @ruckustboom. We ended up utilizing the `lookup` function like:
`lookup(".chart-plot-background").style { backgroundColor += Color.TRANSPARENT }`
