### ISSUE TITLE
Is it possible to track the changes of my objects with ObservableList.onChange() function

### ISSUE THREAD

**Issue by sobolevstp** [edvin/tornadofx#680]
Hi everyone,
the goal is to track the changes of table items. For instance, I want to know all modified items in TableView.
I try to do it next way but it doesn't work for me:
```    
...
        someObservableList.onChange { change ->
            while (change.next()) {
                if (change.wasUpdated()) {
                    println("doSomething")
                }
            }
        } 
...
```
Could you suggest me how I can do it or maybe there is some another approach to get all modified items inside TableView since a data was loaded?

**Comment by edvin** [comment]
This will not track changes on properties of instances in your list. For that, you'd need to attach listeners to every property of every element, which is not a good idea. I think you should rethink the use case for this, and maybe look at other places to attach your listener logic, like for example on an UI component instead. This would for sure be very heavy.

**Comment by sobolevstp** [comment]
Ok, I will take it into account.
Thanks!
