### ISSUE TITLE
SortedFilteredList problem when sorting (again)

### ISSUE THREAD

**Issue by bkursawe** [edvin/tornadofx#681]
I use TornadoFX 1.7.15 and got the same problem as in issue #344. A quick look in the sources showed me, that the changes you made in July 2017 have disappeared (the fix "setAll = false" is missing).

So the old problem appears, that sorting a filtered list overwrites the underlying list.

**Comment by edvin** [comment]
You're right. Sorry about this, not quite sure why it was changed, but I think I'll make it a configurable option this time.

**Comment by nimakro** [comment]
@edvin @bkursawe any updates can we close this issue?

**Comment by edvin** [comment]
I'm adding a `setAllPassThrough` property to `SortedFilteredList` and defaulting it to `false` so that this behavior can be tuned. Will close the issue when I have committed.

**Comment by gtnarg** [comment]
I just upgraded from 1.7.16 to 1.7.18-SNAPSHOT and my tableview backed by a SortedFilteredList is suddenly blank.  Would it make sense to throw an exception if setAll is called when setAllPassThrough is false?  Right now it is a silent noop?  I see in #344 you made the decision that returning false was a better solution - could you elaborate?
