### ISSUE TITLE
runAsyncWithProgress throws when invoked inside toolbar

### ISSUE THREAD

**Issue by yay** [edvin/tornadofx#687]
<img width="347" alt="screen shot 2018-03-29 at 21 34 37" src="https://user-images.githubusercontent.com/1799756/38106886-159a1bd8-3399-11e8-85b6-343a040c4275.png">

1) Press ENTER inside the text field -> text field disappears
<img width="347" alt="screen shot 2018-03-29 at 21 34 41" src="https://user-images.githubusercontent.com/1799756/38106897-1b5a9750-3399-11e8-9a44-4053a0b6419c.png">
2) Press ENTER inside the text field again -> some weird stuff happens -> exception is thrown
<img width="347" alt="screen shot 2018-03-29 at 21 34 46" src="https://user-images.githubusercontent.com/1799756/38106934-385822c8-3399-11e8-8bb1-bc608de1efc1.png">

Fails:
```kotlin
import javafx.event.EventHandler
import javafx.scene.input.KeyCode
import tornadofx.*

class MyView : View() {
    override val root = toolbar {
        label("Symbol:")
        textfield {
            onKeyReleased = EventHandler { key ->
                if (key.code == KeyCode.ENTER) {
                    runAsyncWithProgress {
                        Thread.sleep(1000)
                    }
                }
            }
        }
    }
}
```

Works fine (only replaced `toolbar` with `hbox`):
```kotlin
import javafx.event.EventHandler
import javafx.geometry.Insets
import javafx.geometry.Pos
import javafx.scene.input.KeyCode
import tornadofx.*

class MyView : View() {
    override val root = hbox {
        label("Symbol:")
        textfield {
            onKeyReleased = EventHandler { key ->
                if (key.code == KeyCode.ENTER) {
                    runAsyncWithProgress {
                        Thread.sleep(1000)
                    }
                }
            }
        }
    }
}
```

In this second example that uses `hbox` instead of `toolbar` the correct behavior can be seen: both times the text field momentarily disappears (replaced with a spinner) then reappears after a 1 second delay, without throwing.

**Comment by ruckustboom** [comment]
This looks like an issue with the way `EventTarget.removeFromParent()` is defined. I believe if we remove the special handling for `ToolBar` in the `Node` branch it should work fine, as `EventTarget.getChildList()` already handles `Toolbar`.

**Comment by edvin** [comment]
Thanks, @ruckustboom - I merged your fix now :)

**Comment by kastork** [comment]
This fix seems to have introduced #696

**Comment by edvin** [comment]
The issue here is not with removeFromParent, but rather with runAsyncWithProgress. It doesn't add the children in the correct spot for Toolbar I think.

**Comment by edvin** [comment]
What's happening here is that runAsyncWithProgress adds/removes items from the inner HBox of Toolbar, instead of from the items property of the toolbar itself. removeFromParent actually does what it's supposed to.

**Comment by edvin** [comment]
I committed a fix now, best of both worlds :)
