### ISSUE TITLE
Consider special support for JsonProperty<T>

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#69]
I'm contemplating a special kind of `Property<T>` that knows how to convert itself to and from JSON, for even tighter integration with `JsonModel`. We could support a new property delegate called `jsonProperty` to make it easy to generate these.

No details yet, don't even know if it's a good idea, just creating the issue and will let it stew for a while.

**Comment by thomasnield** [comment]
Haven't done much JSON but I was just thinking if something like that could be done. That would be helpful if the delegate can be done.

**Comment by edvin** [comment]
Yeah, a delegate would help. I think the main value of such a property is the ability to specify data type conversion somehow. We already have automatic conversion of data, so the value of this might be too slim though.

**Comment by edvin** [comment]
I will close this for now, the current usage pattern is quite good, and I can't really find a way to do this that would provide much of a benefit.
