### ISSUE TITLE
OSGi bundle pack link is broken

### ISSUE THREAD

**Issue by javadch** [edvin/tornadofx#690]
The [link](https://tornadofx.io/#felix) to the zip file containing the OSGi bundles is broken.

**Comment by edvin** [comment]
Sorry this took so long. I finally got around to fixing it. The fix consists of:

- Updating the felix library version (and support libraries)
- Updating my JavaFX 8 OSGi support library to include another package
- Updating JSON Impl library to version 1.1.2
- Adding JSON API library version 1.1.2
- Deploying JAVAFX 8 OSGI to Maven Central (should be there within the our)
- Deploying the web page with the new references, which should now build the correct package

**Comment by javadch** [comment]
I'll test in on weekend and let you know the result.
