### ISSUE TITLE
Not all images load correctly

### ISSUE THREAD

**Issue by martmists** [edvin/tornadofx#691]
Example of working images:

- [Anything imgur](https://i.imgur.com/59kIAS3.jpg)
- [Anything github](https://avatars1.githubusercontent.com/u/16361449?s=88&v=4)

Not working:

- [Discordapp](https://cdn.discordapp.com/avatars/161866631004422144/755c3d7df73a34998ea0438c6ca8f12a.png?size=1024)
- [Third-party hosts](https://owo.whats-th.is/211e93.png)
- [Wikimedia websites](https://ahost.bulbagarden.net/content/bulbapedia-mobile.png)

The issue is simple; It's not displaying, and no errors are given in console.

**Comment by edvin** [comment]
You're not saying how you're loading the images, but if you're relying on JavaFX's built in way of loading images in ImageView/Image, then this is probably due to these services not accepting requests from the User Agent presented by HTTPURLConnection by default. You must then load these images yourself and supply the input stream to the Image or ImageView.

**Comment by martmists** [comment]
The image is fetched using Okhttp: 

```kotlin
// Made one-liner so I dont have to paste a bunch of code
// url is an okhttp3.HttpUrl 
val stream = OkHttpClient().newCall(Request.Builder().url(url).build()).execute().body()!!,byteStream()
imageview(Image(stream))
``` this displays nothing at all

**Comment by martmists** [comment]
Managed to fix it by using the JavaFX ImageView instead

**Comment by edvin** [comment]
Good. You should never load external resources like this anyway, without at least checking the return code and content type of the payload :)

**Comment by martmists** [comment]
I just really don't want to have all 900 images in my source tree ^^"

**Comment by edvin** [comment]
Then you should consider hosting them yourself, so you know that the user agent is accepted, and that you can expect a uniform response/loading time for the images. Also remember to take into account that images must be loaded asynchronously, and that your app should handle the images not loading at all. Lots to think about when using external resources :)
