### ISSUE TITLE
SimpleListProperty<.>() Error "value must not be null"

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#695]
Hi, I'm trying to make a query through MyBatis, but I'm having a problem with a List. This is my Bean Object:

```
class Salon {
    val idProperty = SimpleIntegerProperty()
    var id by idProperty

    val mesaListProperty = SimpleListProperty<Mesa>()
    var mesaList by mesaListProperty // This produces the error
}
```
```
class Mesa {

    val idProperty = SimpleIntegerProperty()
    var id by idProperty

    val nroMesaProperty = SimpleIntegerProperty()
    var nroMesa by nroMesaProperty

}
```

This is my `Salon` object mapped on MyBatis

```
<resultMap id="mapSalon" type="Salon">
        <id property="id" column="id_salon"/>
        <collection property="mesaList" ofType="Mesa">
            <id property="id" column="id_mesa"/>
            <result property="nroMesa" column="nro"/>
        </collection>
    </resultMap>
```

Everything runs perfect, but when I make a query where it returns a list of "Mesa", this error occurs:
```
Caused by: java.lang.IllegalStateException: value must not be null
	at tornadofx.PropertiesKt.getValue(Properties.kt:212)
```
Which brings me exactly to my MutableList property of `Salon`
` var mesaList by mesaListProperty // This produces the error `

And the class that produces the error is the following
Class: tornadofx.Properties (line : 212)
`operator fun <E> ObservableListValue<E>.getValue(thisRef: Any, property: KProperty<*>): MutableList<E> = value`

Why does this error occur? I thought it was the fault of the MutableList class, but when I changed the initialization of my property to this:

` var mesaList = mesaListProperty.toMutableList()`

I work perfectly, but that's not the way it should be, how can I solve this problem? It's the only type of property (SimpleListProperty()) that is causing me problems.

Regards :)

**Comment by edvin** [comment]
`SimpleListProperty` expects it's value to be an ObservableList, and myBatis doesn't know how to initialize such as list.

It might work if you populate the value of the list property first:

```kotlin
val mesaListProperty = SimpleListProperty<Mesa>(FXCollections.observableArrayList())
```

Now myBATIS might see that there is already a list there it can use, since `SimpleListProperty` does indeed implement the `List` interface. If that doesn't work, you'd need specialized getters and setters that accept setting a list, and converts it to an observable list:

```kotlin
    var mybatisMesaList: MutableList<Mesa>?
        get() = mesaListProperty.get()
        set(value) {
            mesaListProperty.value = value?.observable() ?: observableList()
        }
```

**Comment by TioCoding** [comment]
The first solution was enough to solve the problem

`val mesaListProperty = SimpleListProperty<Mesa>(FXCollections.observableArrayList())`

Thank you very much ;)

**Comment by edvin** [comment]
Glad to be of help :)
