### ISSUE TITLE
workspace ondock() buttons repeats

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#696]
hello 
i using workspace on tabs mode 
with every view i using the onDock() method to add  dynamic elements

my problem is when i open or choose tab the dynamic elments added to the workspace toolbar
and when change a new tab the last tab dynamic elments not disapperar and the new added
over and over 
[sample.zip](https://github.com/edvin/tornadofx/files/1890400/sample.zip)

**Comment by mostfa-ayad** [comment]
my problem come from using tornadofx  Snapshots  i deleted it from my repositories and every thing ok
please fix it for comming  release

**Comment by kastork** [comment]
I'm seeing this also in the head of master (16 SNAPSHOT)

**Comment by kastork** [comment]
Appears to have been introduced in 52885945f6dd6da2025781ad6e9d020b6cc6ae75

**Comment by kastork** [comment]
![untitled](https://user-images.githubusercontent.com/202288/38638195-5f190b3c-3d82-11e8-9e01-805cbfeb0cc1.gif)

**Comment by edvin** [comment]
Ah, it looks like @ruckustboom missed the toolbar case when he refactored removeFromParent. Nice catch @kastork, I committed a fix now. Please confirm :)

**Comment by edvin** [comment]
Aha, sorry I missed that @ruckustboom. Looking at #687 again now.

**Comment by mostfa-ayad** [comment]
thank you all
