### ISSUE TITLE
Window's full screen icon is not visible on first show (macOS)

### ISSUE THREAD

**Issue by yay** [edvin/tornadofx#701]
For example, if we have the following code to show the view:
`find(ColorView::class).openWindow()`
than the first time we open the window, the titlebar buttons look like this:
<img width="71" alt="screen shot 2018-04-15 at 20 27 41" src="https://user-images.githubusercontent.com/1799756/38781340-f114a6ec-40eb-11e8-81e1-241d8c65d3bb.png">
If we then close the window and open it again, the buttons look like this:
<img width="71" alt="screen shot 2018-04-15 at 20 27 57" src="https://user-images.githubusercontent.com/1799756/38781342-f6e98c7c-40eb-11e8-9d64-bb2ad2e05131.png">

Expected result:
consistent behavior (as on the second picture)

**Comment by edvin** [comment]
Does it only happen with the first window that opens or with every window the first time? Please post a complete app that showcases the issue. Also, what version of OS X and Java are you running with?

**Comment by yay** [comment]
With every window the first time.

Here's the full app:
```kotlin
import javafx.application.Application
import tornadofx.*

class OtherView : View("Colors") {
    override val root = vbox {
        label("Check the title bar buttons.")
    }

    fun setColor(color: String) {
        root.style {
            backgroundColor += c(color)
        }
    }
}

class MainView : View("Main") {
    override val root = vbox {
        toolbar {
            button("Colors").action {
                find(OtherView::class).openWindow()
            }
        }
    }
}

class ColorApp : App(MainView::class)

fun main(args: Array<String>) {
    Application.launch(ColorApp::class.java, *args)
}
```

TornadoFx 1.7.15
macOS 10.12.6
Java 8 update 161

**Comment by edvin** [comment]
This happens after the call to `Stage.initOwner`, which is a JavaFX function, nothing we can control it seems.

**Comment by yay** [comment]
I suspected this might be the case. Thank you for checking.

**Comment by edvin** [comment]
Yeah, I can't see a way we can affect this, but at least we can work around it with the `owner = null` trick if that's viable for your use case :)

**Comment by yay** [comment]
Yep, `owner = null` does the trick. Thanks!
