### ISSUE TITLE
contextmenu builder returns EventTarget instead of ContextMenu instance

### ISSUE THREAD

**Issue by yay** [edvin/tornadofx#702]
<img width="216" alt="screen shot 2018-04-17 at 02 08 20" src="https://user-images.githubusercontent.com/1799756/38839662-71c478fa-41e4-11e8-9d94-34649c053b3f.png">

That's weird, given

<img width="196" alt="screen shot 2018-04-17 at 02 10 35" src="https://user-images.githubusercontent.com/1799756/38839689-93e10598-41e4-11e8-92bc-35a951a7f049.png">

**Comment by edvin** [comment]
Thanks, fixed :)

**Comment by ctadlock** [comment]
Closing; fixed
