### ISSUE TITLE
In TableView, selectionModel.selectedItems contains null values under specific circumstances

### ISSUE THREAD

**Issue by LittleLightCz** [edvin/tornadofx#706]
I came across a quite weird behaviour when using `selectionModel.selectedItems` for later storing of the table content into the clipboard and here is the example code:

```kotlin
package tornadofx.bug

import javafx.application.Application
import tornadofx.*


class TableValue(var value: Int)

class TableViewBug: View() {

    val tableData = (1..5).map { TableValue(it) }.toMutableList().observable()

    override val root = vbox {
        tableview(tableData) {
            shortcut("Ctrl+C") {
                selectionModel.selectedItems.forEach {
                    if (it == null) warning("Table value is null!")
                }
            }

            multiSelect(true)

            readonlyColumn("Value", TableValue::value)
        }
    }

}

class TableViewBugApp : App(TableViewBug::class)

object Runner {
    @JvmStatic
    fun main(args: Array<String>) {
        Application.launch(TableViewBugApp::class.java)
    }
}
```

Steps to reproduce the issue:
1. Select exactly values 1 and 2
2. Hit Ctrl+C [nothing happens yet]
3. After that, select only value 3
4. Hit Ctrl+C again and now you should get the null warning

**Comment by edvin** [comment]
This works without a glitch for me. TornadoFX doesn't really mess with the selectionmodel, so this might be a bug in your JavaFX implementation. What version are you using, on what OS?

**Comment by LittleLightCz** [comment]
I've just updated to: `8.0.171-b11` and it seems the problem is gone! :-)

Thanks for your help and also thanks a lot for creating this amazing framework ;-)

**Comment by edvin** [comment]
Thanks, and good to hear that you figured it out :)
