### ISSUE TITLE
I have a good suggestion about UI component

### ISSUE THREAD

**Issue by yancheng199287** [edvin/tornadofx#707]
I discover a open source project JFoenix，it is more beautiful UI, I want add it to tornadofx，but  need extend function,  I  want your team add this project, just like component of tornadofx. What do you think?

**Comment by edvin** [comment]
Several users have used JFoenix with TornadoFX, it works fine. You should join us on Slack to discuss how others have done it. You can add your own builder functions the same way we've added ours - look at the source code to see how it's done.

**Comment by nimakro** [comment]
Brian Kennedy created some extension functions [KFoenix](https://github.com/bkenn/KFoenix) so you can use JFoenix integrates nicely with tfx
