### ISSUE TITLE
How to handle multimedia?

### ISSUE THREAD

**Issue by XanderEmu** [edvin/tornadofx#708]
I'd like to create a desktop app using Kotlin/TornadoFX and I need to do some multimedia-related stuff with it like:

- playing it
- decrypting in on the fly (because of that I'd like to be able to manipulate input buffer on the fly)

I already figured it all out using web and electron as browser's multimedia API is pretty rich nowadays

Then I tried to achieve it with Java/Kotlin and I'm stuck as I didn't really find much in a world of Java's multimedia frameworks. JMF seems at least old if not dead. JavaFX has it's media player but it's API seems to be very limited. Ther's vlcj which is promising but it's GPL (and also dead I think).

I'm kinda new to Java. How do people handle multimedia in Java world?

**Comment by edvin** [comment]
I don't do much multimedia myself, so all I can tell you is that TornadoFX doesn't have any special support for it.

**Comment by fiberstar** [comment]
i'm also developing multimedia software using javafx. recently meet the same problems. i'm using the vlcj, it works, but the performance is low. i decide deeply modify it.

**Comment by edvin** [comment]
This is purely a JavaFX issue, as TornadoFX has no special support for multimedia. You can use any JavaFX API from TornadoFX, but that's about it.
