### ISSUE TITLE
Inconsistent Builder Naming Conventions?

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#71]
Was doing some documentation for the guide and I saw a few builders that were not all lowercase like the rest of the controls.

```kotlin
progressBar()
progressIndicator()
titledPane()
```

@edvin I think you said that you'd prefer all builders to be lowercase. Do these count?

**Comment by edvin** [comment]
Yeah, I think we should keep them all lowercase. Will you change them or should I? :)

**Comment by thomasnield** [comment]
I'll do it. I finished documenting Section 1 Part 2 in the guide but I held up on these until I confirmed : )

**Comment by thomasnield** [comment]
Okay done.

**Comment by edvin** [comment]
Perfect!
