### ISSUE TITLE
How to drag a row to another row's position in TableView

### ISSUE THREAD

**Issue by sushiduli** [edvin/tornadofx#710]
Hi

   I find that I can drag and drop column.but  when I try to drag row, it has no action.what should I do to achieve the effect.

Br

**Comment by edvin** [comment]
I added a sample app with DND reordering to the framework. It's not perfect, but the basics are there and it's working at least :)

https://github.com/edvin/tornadofx/blob/master/src/test/kotlin/tornadofx/testapps/TableViewDNDTest.kt
