### ISSUE TITLE
Add support for optional "Cancel" confirmation on wizard

### ISSUE THREAD

**Issue by SackCastellon** [edvin/tornadofx#712]
### Problem
I think that support for a custom cancellation confirmation in the wizard is something necessary. Imagine you have a 5+ pages wizard and you filled all the information, but on the last page, you misclick the cancel button and you lose all the data you inputted. You would wish you were asked if you were sure.

### Proposed solution
Add a `isCanceled` property and a `onCancel()` function:

```kotlin
/**
 * Specifies whether the wizard can be safely closed
 */
var isCanceled = true

/**
 * This function is called when the cancel button is pressed, but before closing the wizard.
 */
open fun onCancel() {
    isCanceled = true
}
```

The `onCancel()` function would be called before closing the wizard. Then the wizard will only be closed if `isCanceled` is `true` ([Wizard.kt#L164-L167](https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Wizard.kt#L164-L167))
```kotlin
button(type = ButtonBar.ButtonData.CANCEL_CLOSE) {
    textProperty().bind(cancelButtonTextProperty)
    action {
        onCancel()
        if (isCanceled)
            close()
    }
}
```

### Example
```kotlin
override fun onCancel() {
    confirmation(
        "Confirmation",
        "Do you really want to lose your progess?",
        ButtonType.YES, ButtonType.NO
    ) {
        isCanceled = it == ButtonType.YES
    }
}
```

### Compatibility
This change should not break any existing code because by default the wizard is closed on pressing the cancel button as always.

**Comment by edvin** [comment]
Good suggestion, thanks. I've implemented it slightly different. When the cancel button is clicked, the `onCancel` function is called. The default implementation calls `cancel()`, which closes the wizard. In the future the `cancel` function might do more things to clean up on cancel.

You would now override `onCancel` like this:

```kotlin
override fun onCancel() {
    confirm("Confirm cancel", "Do you really want to loose your progress?") {
        cancel()
    }
}
```

**Comment by SackCastellon** [comment]
Perfect, good work 👌
