### ISSUE TITLE
How can I change scope when I inject with inject by di()

### ISSUE THREAD

**Issue by osmaymoya** [edvin/tornadofx#713]
Hello, I  use Spring to dependency inject, but I need to change the scope and not find how can I do this.
`private val model : UsersModel by di()`

this is in my UserNewEdit view, that when is need to insert I try to get a new scope but not work
`val newScope = Scope(UsersModel())`
                            `find(UserNewEdit::class, newScope).openWindow()`

**Comment by osmaymoya** [comment]
I have solve the problem injecting UserModel using inject() from tornado and controller, service and repository using by di()
`private val model : UsersModel by inject()`

**Comment by osmaymoya** [comment]
This is a very small project to learn about tornadoFX and integration with Spring. This is a main view to show a list of users 

 class MainView : View("Hello TornadoFX") {
    companion object {
        val logger: Logger = LoggerFactory.getLogger(MainView::class.java)
    }
    private val controller : MainController by di()
    private lateinit var table: TableView<Users>
    private val model : UsersModel by inject()
    override val root = vbox {
            gridpane{
                row{
                    label("USUARIOS") {
                        gridpaneConstraints {
                            marginTopBottom(5.0)
                            marginLeftRight(5.0)
                        }
                    }
                    button("Nuevo") {
                        gridpaneConstraints {
                            marginTopBottom(5.0)
                            marginLeftRight(5.0)
                        }
                        action {
                            //model.rebind {  }
                            //logger.info("${model.item?.id ?: "nulo"}")
                            val newScope = Scope(UsersModel())
                            //find(UserNewEdit::class, newScope).openWindow()
                            openInternalWindow(view = UserNewEdit::class, scope = newScope)
                            table.items.setAll(controller.getUsers())
                        }
                    }
                }
                row {
                    table = tableview (controller.getUsers()) {
                        title = "Usuarios"
                        useMaxWidth = true
                        gridpaneConstraints {
                            marginTopBottom(5.0)
                            marginLeftRight(5.0)
                            columnSpan = 2
                        }
                        column("ID", Users::id)
                        column("Usuario", Users::username)
                        column("Nombre", Users::name)
                        column("Apellido", Users::lastname)
                        column("Estado", Users::active).cellFormat {
                            style {
                                if (it) {
                                    text = "Activo"
                                    textFill = javafx.scene.paint.Color.GREEN
                                } else {
                                    text = "Inactivo"
                                    textFill = javafx.scene.paint.Color.RED
                                }
                            }
                        }
                        contextmenu {
                            item("Editar").action {
                                logger.info("Editando Usuario (Id=${model.id.value})")
                                openInternalWindow(view = UserNewEdit::class)
                                //find(UserNewEdit::class).openWindow()
                                table.items.setAll(controller.getUsers())
                            }
                            item("Eliminar").action {
                                logger.info("Eliminando Usuario (Id=${model.id.value})")
                                controller.deleteUser(model)
                                //find(UserNewEdit::class).openWindow()
                                table.items.setAll(controller.getUsers())
                            }
                        }
                        // Update the person inside the view model on selection change
                        bindSelected(model)
                    }
                }
            }
    }
}

I can insert a new user or edit  and this is a UserNewEdit view

class UserNewEdit : View("Datos de Usuario") {
    companion object {
        val logger: Logger = LoggerFactory.getLogger(UserNewEdit::class.java)
    }
    private val model : UsersModel by inject()
    private val controller : MainController by di()
    override val root = form{
        fieldset{
            hbox {
                label("Usuario:")
                textfield(model.username)
            }
            hbox {
                label("Nombre:")
                textfield(model.name)
            }
            hbox {
                label("Apellido:")
                textfield(model.lastname)
            }
            hbox {
                checkbox("Estado")
            }
        }
        hbox {
            button("Salvar"){
                enableWhen(model.dirty)
                action{
                    model.commit()
                    controller.saveUser(model)
                    close()
                }
                //

            }
            button("Cancelar"){
                action{
                    logger.info("Model.id = ${model.id.value}")
                    close()
                }
            }
        }
    }
}
when I inject the UserModel by di() in UserNewEdit, view always was the same object, but when inject with by inject() , in new scope create e new object

I don´t know why I can´t mark a block of code.

**Comment by gtnarg** [comment]
In general if you are using Spring - it's responsibilities are to inject
components/services outside of the view layer (e.g.. persistence).

TornadoFx related components (eg. Controller, ViewModel, Scope) should be
injected by TornadoFx

**Comment by nimakro** [comment]
I will close this issue since it sounds like @osmaymoya your figured out a solution that works for you. If you have more questions feel free to open a new issue or join us on [Slack](https://kotlinlang.slack.com)
