### ISSUE TITLE
DSL Slider IntProgression?

### ISSUE THREAD

**Issue by Exerosis** [edvin/tornadofx#715]
Might be a good reason for the current method but I was thinking it would be pretty slick to add an overload like this:
```
fun slider(range: IntProgression, etc etc) {
    slider(range.first, range.last) {
        minorTickCount = range.step
    }
}

//Used like
slider(0..99 step 25) {
    isShowTickMarks = true
    isSnapToTicks = true
    valueProperty().rxBind(valueObservable)
}
```

**Comment by edvin** [comment]
I like it! Will you submit a PR? :)

**Comment by SiebelsTim** [comment]
I think this is unintuitive. I expect `slide(0..100 step 30)` to only let me select `0, 30, 60, 90, 100`. 
If I understand correctly, the above solution adds 25 minor tickmarks between every major tickmark.

My suggestion would need to implement a listener that snaps to every 30th item. However, I think this could be irritating that it does more than the other overload.
Another solution would be to disallow usage of `step`.

**Comment by edvin** [comment]
Thank you @SiebelsTim - I merged your PR now.
