### ISSUE TITLE
workspace tabview mode problem

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#718]
hello
using workspace tabview mode  
i use this code for add new tab

`workspace.dock<UserView>()`

and this is the approach i use for my view
```
class UserView : View("Users View") {
    val controller:UserController by inject()
    val model: UserModel by inject()
    val listView:UserList by inject()
    override val savable = model.editModeProperty
    override val creatable=!model.editModeProperty

    init {
        controller.users.setAll(controller.loadUsers())
    }
    override val root=stackpane {
        add<UserList>()
        add<UserEditor>()
        connectWorkspaceActions()
    }
    override fun onCreate() {
        model.item=User()
        model.isNew=true
        model.editMode=true
        model.editor=true

    }
    override fun onSave() {
        model.commit() {

            if (model.isNew) {

                model.item = controller.insertUser(model)
                println(model.item.toJSON())
            } else {
                controller.updateUser(model)
            }
        }
    }

    override fun onDock() {
        with(this.workspace) {
           button("list"){

                disableWhen(model.editorProperty.not())
                action {
                model.editor=false
                initModel()
                }
            }
            button("edit") {
                    disableWhen(model.editModeProperty)
                    action {
                        model.editMode = true
                        model.editor=true
                    }
                }
            }
        }


    fun initModel(){
        model.editMode=false
        model.isNew=false
    }

    override fun onRefresh() {
        listView.refresh()
    }


}
```

if tabview is have one tab and i close it and open this tab again it don't work
i must open another tab and open the tab i want

another thing when i close tab i want to deleted not just closed from view
because when closing tab and open again it load the last data 
thanks alot

**Comment by edvin** [comment]
Can you post a working sample app so I can test this behavior? A preliminary test doesn't show any problems for me. If you close and reopen a View, you'll get the same state, since view is a singleton. Either turn it into a Fragment, or do whatever cleanup you need in `onDock`. Alternatively, use a new scope when you reopen the view.

**Comment by mostfa-ayad** [comment]
this is a sample with one view  when i open it in tab and close it 
i can't open again  and the workspace toolbar is still have the buttons added from this view
[sample.zip](https://github.com/edvin/tornadofx/files/1971787/sample.zip)

**Comment by edvin** [comment]
Thanks. I haven't used tabbed mode much myself, so I'm thinking that the undock callback is not fired when you close the tab. Investigating now.

**Comment by edvin** [comment]
I've committed a fix for this issue now. Thanks again for providing me with a test case :)

**Comment by mostfa-ayad** [comment]
You are welcome,  thank you
