### ISSUE TITLE
Plans for layout managers?

### ISSUE THREAD

**Issue by felislynx-silae** [edvin/tornadofx#726]
Hi, as a person who writes mostly apps for Android, while writing desktop app, i'm missing here in TornadoFX a proper layout manager.
Writing good looking, responsive layout is possible without any issues on Android. But doing that on JavaFX is... pain in the a**. It would be awesome to have equivalent of ConstraintLayout/RelativeLayout or for lists RecyclerView here in TornadoFX. Do you think this could be possible?

**Comment by edvin** [comment]
There are no plans for a new layoutmanager in TornadoFX, but maybe MigLayout satisfies your needs? If so, I'd be interested in looking at a TornadoFX API on for it, unless their API is already neat :)

I do agree that JavaFX really is missing a great layout manager that takes responsive layouts into account, but I just don't have the time to pursue it myself. If you (or anybody else) would be interested in heading up such an effort, a PR for it would be most welcome. I know that it's a lot of work creating something good from scratch, unless we could find a way to fork or reuse parts of another layout manager, for example those you mention?

**Comment by felislynx-silae** [comment]
MigLayout is a little more intelligent grid layout. It's not near a Relative/Constraint layout at all :). Unfortunately i don't have that much time (and javafx knowledge) to create new layout manager. Thank you for answer.
