### ISSUE TITLE
Question : how to inject in a View a View Model mock with setInScope

### ISSUE THREAD

**Issue by alexandrenavarro** [edvin/tornadofx#728]
Question : how to inject in a View a View Model mock with setInScope?

My usecase :
I want to make a unit test for a View made tornadofx with a ViewModel by inject() inside (a MVVM pattern).
I did a unit test with testfx.
First I setInScope(mockOfMyViewModel)
After I created my view where my class should be injected.
The problem is the name of the class with the mock is not the same of the real class to inject, so it does not work because your registry of View* are made by class name.

1) First question, is there a way to do it with the tornadofx (via Scope or any method)?
If yes tell me?

If not, I modified a very little tornado FX.kotlin, mainly 
fun <T : ScopedInstance> setInScope(value: T, scope: Scope = DefaultScope) = FX.getComponents(scope).put(kclass, value)
-> 
fun <T : ScopedInstance> setInScope(value: T, scope: Scope = DefaultScope) = FX.getComponents(scope).put(value.javaClass.kotlin, value)
and so I can do in my test
setInScope(mockCountryListViewModel, kclass = CountryListViewModel::class)
This is sample I did if you want to see https://github.com/alexandrenavarro/tornadofx-sample/blob/master/src/test/kotlin/com/github/alexandrenavarro/tornadofxsample/CountryListViewTest.kt

2) Are you ok this new feature, you can merge the PR https://github.com/edvin/tornadofx/pull/727 ?

Thanks in advance to answer to the 2 questions please.

**Comment by edvin** [comment]
Very good idea, I like it :) Merging now

**Comment by alexandrenavarro** [comment]
Thanks
