### ISSUE TITLE
runAsyncWithProgress removes parent node

### ISSUE THREAD

**Issue by elexx** [edvin/tornadofx#730]
Hello,
I observed a strange behavior of `runAsyncWithProgress`. It works fine, when using it like with `action {runAsyncWithProgress {...} }` but does unexpected things in the second case.

```kotlin
class AsyncTest : View("My View") {
    override val root = vbox {
        buttonbar {
            button("Button 1") {
                action {
                    runAsyncWithProgress {
                        Thread.sleep(5000)
                    }
                }
            }

            button("Button 2 ").action {
                runAsyncWithProgress {
                    Thread.sleep(5000)
                }
            }
        }
    }
}
```
Button 1 clicked:
![my view_001](https://user-images.githubusercontent.com/221837/40277085-8dd9d752-5c19-11e8-918a-cf97193642dc.png)

Button 2 clicked:
![my view_002](https://user-images.githubusercontent.com/221837/40277086-8e1b2e00-5c19-11e8-98ed-8a6b17576310.png)

**Comment by edvin** [comment]
That's not unexpected at all, as in the second case you call `runAsyncWithProgress` on the `ButtonBar`, not on the `Button`.  Remember, you already closed the button builder, and you're back in the scope of the `ButtonBar :) The `action` function call doesn't re-enter the button builder scope.

**Comment by elexx** [comment]
Ahh I see.
So I either have to go with the first sample or extract the button as field and call `btn.action { ...}` or use some custom extension function like
```kotlin
fun ButtonBase.btnScopedAction(op: ButtonBase.() -> Unit) = setOnAction { op() }
```
or 
```kotlin
inline fun <T : ButtonBase> T.btnScopedAction(crossinline op: T.() -> Unit) = setOnAction { op() }
```

**Comment by elexx** [comment]
Oh sorry. Forgot to close this issue :)

**Comment by edvin** [comment]
I would skip the btnScopedAction and go for `actionWithProgress` instead :)
