### ISSUE TITLE
Passing Parameters to Views

### ISSUE THREAD

**Issue by LPeco** [edvin/tornadofx#731]
Hi, I am new to Tornado Fx and I am reading the official guide, but when trying this:

fun editCustomer(parametro:String) {
    find<CustomerEditor>(mapOf(CustomerEditor::customer to parametro)).openWindow()
}

class CustomerEditor:Fragment() {
    val customer: String by param()
    override val root = vbox {}
}

The find statement generates the error:
None of the following functions can be called with the arguments supplied.

I have changed the parameter for a String (instead of Customer), and I added the root to the Fragment (in the example of the guide it is not).

Why is this error generated?

Thank you very much.

**Comment by edvin** [comment]
You need to pass the type parameter to `find` to tell it what UIComponent you would like it to find:

```kotlin
find<CustomerEditor>(mapOf(CustomerEditor::customer to parametro)).openWindow()
```

That said, scopes are almost always preferred to passing parameters this way, so look into scopes when you feel comfortable with this approach.

**Comment by LPeco** [comment]
Sorry, I believe that the previous code does not copy it correctly.

The complete code is the following, but it still shows the same error.

package lap.com

import tornadofx.App

class EjemploVista:App(ejemploVistaParametros::class)

class ejemploVistaParametros: View() {
    var nombrePersona:String = ""

    override val root = vbox {
        title = "Vista con parámetros"

        label("Etiqueta de la vista")
        nombrePersona = "Pedro"
        editCustomer(nombrePersona)
    }
}

fun editCustomer(parametro:String) {
    find<CustomerEditor>(mapOf(CustomerEditor::customer to parametro)).openWindow()
}

class CustomerEditor:Fragment() {
    val customer: String by param()
    override val root = vbox {}
}

**Comment by edvin** [comment]
Your `editCustomer` function is defined outside the `ejemploVistaParametros` class, and there you don't have access to `find`. Move it inside the class or move it to a controller if you like.

**Comment by nimakro** [comment]
Close due inactivity @LPeco feel free to reopen the issue if @edvin suggestions did't solve your problem.
