### ISSUE TITLE
Tab builder with only the last child

### ISSUE THREAD

**Issue by jordaorodolfo** [edvin/tornadofx#732]
Hello there! First of all, marvelous framework: light and elegant. It truly helps a lot to circumvent some of the javaFX quirks. Now, let's move to our problem!

## What is happening?
The tab builder, inside the tab builder, only shows the last cuild added via the DSL. For instance, if I use the very first example given in the [guide](https://edvin.gitbooks.io/tornadofx-guide/content/part1/7.%20Layouts%20and%20Menus.html):

    tabpane {
      tab("Screen 1", VBox()) {
        button("Button 1")
        button("Button 2")
      }
    }

my View generated tab only contains the "Button 2" button. Unsurprisingly, switching the order brings up only the "Button 1" button.

## How to reproduce
Set up  a minmal working example of tornadoFX (can be the archetype) with version 1.7.15 and tornadoFX-controls version 1.0.4 and create a simple view containing a tabpane such as the example mentioned here or/and the  [guide](https://edvin.gitbooks.io/tornadofx-guide/content/part1/7.%20Layouts%20and%20Menus.html) and open this view.

## Extra information
I am not using much of the javaFX goodies that are supposed to help the data-centric parts of the App flow easier, such as Observables and Properties: I create them ever so often to set the items of my widgets and them add some event listeners to these widgets to transmit any user info back. Why this extra effort you ask? Simply because the "core" logic of the App is shared between an Android application and the FX application, so that they can both seamlessly use this core logic to communicate with the server.

I think this is enough info to try and see if the problem also happens in other setups, but if necessary, I can provide more specific info, such as the classes used, to pinpoint this  weird error.

All the best.

**Comment by edvin** [comment]
Hi, and thanks for the reporting. The guide is actually wrong. The second parameter to the `tab` builder is not the parent node, it's an optional `tag` which can be used to locate the tab later. The tab is contructed like any other builder, by specifying the node hierarchy inside of it. Since you can only specify a single parent node for the tab content, the last node you add will be left. The correct syntax is therefore:

```kotlin
tab("Screen 1") {
    vbox {
        button("Button 1")
        button("Button 2")
    }
}
```

I will update the guide.

**Comment by jordaorodolfo** [comment]
Wow. that was one quick answer @edvin ! Thanks a lot. I think this can be closed then, since it is more about a certain lag of the documentation with the lastest builds.

Best regards.

**Comment by edvin** [comment]
Yeah, the docs are updated now as well :)

**Comment by edvin** [comment]
Oh nice @thomasnield! I should really put in some work on the guide as well. If you see something missing and want to delegate, let me know!
