### ISSUE TITLE
Maintain the status of the checkbox in ListView

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#733]
Hello, I'm having a problem with the status of a checkbox in a ListView, what I want to achieve is that you can select the options that the user wants, and then get the list of the selected ones, this is my ListCellFragment:

```
class IvaProductoItemFragment : ListCellFragment<IvaClario>() {
    private val ivaClarioItemModel = IvaClarioItemModel().bindTo(this)
    override val root = hbox {
        spacing = 10.0
        this += JFXCheckBox().apply {
            selectedProperty().bindBidirectional(ivaClarioItemModel.selectProductoIva)
        }
        label(ivaClarioItemModel.nombre)
        label(" - ")
        label(ivaClarioItemModel.value)
   }
}
```
My itemmodel:
```
class IvaClarioItemModel: ItemViewModel<IvaClario>() {

    val nombre = bind(IvaClario::name)
    val value = bind(IvaClario::value)

    /*attempt to maintain the state*/
    val selectProductoIva = SimpleBooleanProperty(false)
}
```
And finally my ListView:
```
// IvaList contains 50 items
listview(IvaList) {
     cellFragment(IvaProductoItemFragment::class)
}
```
The problem arises when I select a checkbox, and then I use the scrollbar to raise or lower the ListView, they start to automatically select checkbox that I had not used, and the checkbox that I mark is not selected anymore.

How do I solve this problem?

I want to be able to maintain the status of a CheckBox, and not alter other Items in the ListView.

Finally, I would like to be able to add a filter with a TextField, how could I integrate it maintaining the status of the CheckBox?

Thanks :))

**Comment by kururu-abdo** [comment]
hello edvin
am using intellij 2018.2
tornadofx 1.7.17
i set all dependencies
but after try to Run a project
this exception appear in output console
java.lang.Reflection.InvocationTargetExeption

please help me

**Comment by edvin** [comment]
You made a couple of mistakes:

1. You must make sure that your model bind towards observable properties in your domain object. You didn't actually post your domain object code so I'm guessing here, based on naming conventions.

2. Your selected property exists only inside your model, and this is not backed by any property from the underlying IvoClario object. So when a model is reused for another cell, it is still using that local selected-property. One solution is just to bind towards a selected property in the domain object.

Please also make sure to post a complete code example, it makes it much quicker to test your code and I don't have to guess about how you've done things. I can't really reproduce your exact environment for that reason, but here is a complete working sample:

```kotlin
class IvaClario {
    val nameProperty = SimpleStringProperty()
    var name by nameProperty

    val valueProperty = SimpleStringProperty()
    var value by valueProperty

    val selectedProperty = SimpleBooleanProperty()
    var selected by selectedProperty

    override fun toString() = "$name - $value"
}

class IvaProductoItemFragment : ListCellFragment<IvaClario>() {
    private val ivaClarioItemModel = IvaClarioItemModel().bindTo(this)

    override val root = hbox {
        spacing = 10.0
        checkbox(property = ivaClarioItemModel.selected)
        label(ivaClarioItemModel.nombre)
        label(" - ")
        label(ivaClarioItemModel.value)
    }
}

class IvaClarioItemModel : ItemViewModel<IvaClario>() {
    val nombre = bind(IvaClario::nameProperty)
    val value = bind(IvaClario::valueProperty)
    val selected = bind(IvaClario::selectedProperty, autocommit = true)
}

class MainView : View() {
    val ivaList = FXCollections.observableArrayList<IvaClario>()

    init {
        // Create random data
        repeat(100) {
            ivaList.add(IvaClario().apply {
                name = "Name $it"
                value = "Value $it"
            })
        }
    }

    override val root = borderpane {
        center {
            listview(ivaList) {
                cellFragment(IvaProductoItemFragment::class)
            }
        }
        bottom {
            buttonbar {
                button("What's selected?").action {
                    builderWindow("Selected items") {
                        val selectedItems = ivaList.filter { it.selected }.observable()
                        listview(selectedItems)
                    }
                }
            }
        }
    }
}
```

**Comment by TioCoding** [comment]
Thanks for the response, it has helped me a lot, sorry for not having given so much information :disappointed:  . I will try to be more precise in the future.

**Comment by edvin** [comment]
No problem :)
