### ISSUE TITLE
SingleViewApp for demos and small apps

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#74]
More and more issues post code samples with a view. It would be nice if these code samples were runnable as an application, without the need for extending the App class and wrapping the View etc. I propose adding a SingleViewApp with is both a View and and App in one to make it easier to very write small standalone applications.

**Comment by t-boom** [comment]
That would be awesome for testing things out, especially when it comes to submitting issues.

**Comment by edvin** [comment]
It's because of your scrollpane PR I decided we need this :) The problem with this is that both View and App are abstract classes, so SingleViewApp can't extend them both. Will need to tinker with this a bit to find a nice solution with the absolute minimal amount of boilerplate.

**Comment by t-boom** [comment]
I take it if you create an `View` with an embedded `object: App` it wouldn't run... (I don't know)

Something like

```kotlin
class SingleViewApp : View() {
    object app : App() {
        override val primaryView = SingleViewApp::class
    }

    override val root = VBox()

    init {
        with(root) {
            label("Test")
        }
    }
}
```

**Comment by thomasnield** [comment]
To be honest I've never really been bothered creating an `App` and `View` to run an application. I find it more than satisfactory I can put both in a single Kotlin file. 

```kotlin
class MyApp: App() { 
    override val primaryView = MyView::class
}
class MyView: View() {
    override val root = VBox()
}
```

I find that is satisfactory enough for me, but I suppose it could be convenient. I suppose you'll have to create a separate `SingleViewApp` type that forces you to override a `root` just like a `View`.

**Comment by edvin** [comment]
It's something along the lines of what Thomas posted here I want to achieve. I'm testing some theories now...

**Comment by edvin** [comment]
Hehe, I got it down to this:

```kotlin
class MySingleApp : SingleViewApp(HBox(Label("Hello world")))
```

It requires adding an interface currently called `ViewComponent´ which in turn View will inherit from. This makes it possible for a class to be both an App and a View in the same go.

**Comment by thomasnield** [comment]
I like it. Then an `init` block can be used to populate it.

**Comment by edvin** [comment]
Yes. It won't support FXML though, and that might be confusing, but it still holds value for simple test cases. I did run into some problems when testing the required underlying change with some of my apps, so I'm not sure this will be possible yet.

**Comment by edvin** [comment]
Ah, the problem was that the change is not binary compatible, so it requires a rebuild. It is source compatible though. I think we can live with that.

**Comment by edvin** [comment]
I just commimted it. Could you check if it works OK for you, Thomas? Interested to know if your existing app blows up before you rebuild as well.

**Comment by edvin** [comment]
Haha, I managed to check in all the required changes, but not the SingleViewApp class itself. I'm on my way to Oslo but I'll try to access my office computer and push the changes tonight.

**Comment by thomasnield** [comment]
I'll test it out later today and let you know!

**Comment by edvin** [comment]
There! SingleViewApp is commited. It's actually quite simple:

```kotlin
abstract class SingleViewApp(override val root: Pane) : App(), ViewContainer {
    override val primaryView = javaClass.kotlin
    override val titleProperty = SimpleStringProperty()
}
```

**Comment by t-boom** [comment]
Is there a way to have the root be generic? For example:

```kotlin
class ControlsTest : SingleViewApp(VBox(), "Controls Test") {
    init {
        with(root) {
            prefHeight = 400.0
            prefWidth = 400.0
            // TODO: Set root VBox spacing

            hyperlink("Test")
            passwordfield("password")
        }
    }
}
```

Inside the `with(root)` block, root is a `Pane` and not a `VBox`, so I can't just say `spacing = 5.0`.

**Comment by edvin** [comment]
Ah, yes ofcourse. I'll fix as soon as I get to a computer :)

**Comment by edvin** [comment]
Fixed. Unfortunately, to make this possible I had to remove the override val from the constructor, so usage is now a bit closer to a normal View. I added support for a stage title as well:

```kotlin
class MyApp : SingleViewApp("Hello world") {
    override val root = BorderPane()
}
```

Now `root` will be of type `BorderPane` when you access it from `init`.

**Comment by thomasnield** [comment]
I tired this, it works great for me. I can see why this could come in handy now.

**Comment by edvin** [comment]
Guys, I've identified several problems with the SingleViewApp class, and without going into too much detail, this class forces us to make the framework more complex in some key areas, and there are special caveats to using it. Because of this, I'm convinced this was I mistake on my part and I'd like to remove it completely. Would it be missed?

**Comment by thomasnield** [comment]
A little, but can definitely live without it.

**Comment by edvin** [comment]
Maybe I can find a way for a View to bootstrap an application with a single line of code. That would bring us closer to the functionality SingleViewApp had, but without any of the caveats :)

**Comment by t-boom** [comment]
I agree with @thomasnield. The extra efficiency is nice, but not in the end it really only saves around 5 lines of code, so it's not worth crippling TornadoFX's progress over. Honestly, you could just define a snippet that auto generates the code for you.

**Comment by edvin** [comment]
Good! I removed it and will release 1.4.5 now, some critical bugfixes with regards to the new reload functionality :)

**Comment by edvin** [comment]
I have an even sweeter idea (pun intended, read on :), but I don't know how much work it would be: I'm thinking of creating an IDEA plugin that knows how to "run" a View, much the same way that unit tests are runnable, with a small play icon in the gutter. I'd also like this plugin to have project templates for Gradle/Maven/Standalone etc. Further, it could create fxproperties in domain objects, and lots of other goodies to speed up development!

**Comment by thomasnield** [comment]
I think an IDEA plugin sounds pretty cool. If we can add templates and configurations that would be useful and legit.

**Comment by edvin** [comment]
Cool :) I hope to create it in a way that makes it easy to contribute new functionality to it. We could even include a bunch of snippets that can be auto-created, and features like creating code for a TableView with automatic column definitions for all properties in a domain object etc.

I'm just dreaming still, need to figure out how this is done :)

**Comment by t-boom** [comment]
That would be pretty epic
