### ISSUE TITLE
CSS raw syntax issue

### ISSUE THREAD

**Issue by Yadarma** [edvin/tornadofx#741]
I would like to incorporate this css into TonadoFX?

 /* make the scrollbar a little wider */
    ::-webkit-scrollbar {
        width: 16px;
    }
    ::-webkit-scrollbar-track  {
        background-color: white;
    }
    /* the slider or "thumb" has some rounded edges and a shadow and it's a little translucent */
    ::-webkit-scrollbar-thumb {
        border-radius: 6px;
        box-shadow: inset 0 0 6px rgba(0,0,0,0.5); 
        background: rgba(159,216,239,0.8);
    }
    /* I don't like the scrollbar to be so tiny on large documents - hence I set a minimum height */
    ::-webkit-scrollbar-thumb:vertical {
        min-height: 100px;
    }
    /* Use a more translucent slider when the window is inactive */
    ::-webkit-scrollbar-thumb:window-inactive {
        background: rgba(159,216,239,0.2); 
    }

**Comment by ruckustboom** [comment]
Could you explain what your issue is?

**Comment by Yadarma** [comment]
Thanks for your attention. I am trying to increase the width of webview scrollbar. Besides lots of time I am trying to find the Torndaofx equivalent syntax for Javafx CSS syntax e.g. `::-webkit-scrollbar-thumb:window-inactive {
background: rgba(159,216,239,0.2);
}`

**Comment by ruckustboom** [comment]
In JavaFX, scrollbars are styleable just like anything else, so webkit-style pseudo-elements aren't needed. There are a number of articles online on how to style them ([here is an example](https://stackoverflow.com/questions/48048943/javafx-8-scroll-bar-css)).

If you are talking about scrollbars withing the webview's HTML, that would work the same as any CSS you inject.
