### ISSUE TITLE
openModal() : Dialog does seem to receive key events

### ISSUE THREAD

**Issue by ToninoB** [edvin/tornadofx#742]
A View started with openModal() does not seem to process key events at all, excepted for the escape key that closes the dialog as expected.

e.g.:
find(Dialog1View::class).openWindow(stageStyle = StageStyle.UTILITY, modality = Modality.APPLICATION_MODAL, escapeClosesWindow = true, owner = null, block = false, resizable = false)

Any attempt at installing a key event handler fails : nothing happens when keys  are pressed.

On the other sid, mouse events can be properly handled.

**Comment by edvin** [comment]
Can you show me how you attach the event handler?

**Comment by ToninoB** [comment]
Thank you for your quick anwser.

This dialog is a simple View using FXML. The root is built with a Pane:

class Dialog1View : View("Dialog 1") {
   override val root : Pane by fxml()    	    // Main view
   private val dialogPane: Pane by fxid()
}

The key event handler is either attached by the FXML mechanism:

<Pane fx:id="dialogPane" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" onKeyPressed="#handleOnKeyPressed" onMousePressed="#handleOnMousePressed" ...etc... </Pane>>

fun handleOnKeyPressed(event: KeyEvent) {
 println(event.character)
----
}

Either through the method setOnKeyPressed() in one init{} block:

init {
        dialogPane.setOnKeyPressed { event ->
            println("Dialog1View: " + event.character)
        }
}

This two techniques work as expected if used inisde the main application View but not the DialogView (that is opened from the main View)

**Comment by edvin** [comment]
I'm not seeing a difference. Are you sure you added some inputs to the dialog you opened in the modal? You might not get key events otherwise. Here is a complete runnable example. Please change it to fail when opened in a modal :)

```kotlin
class MainView : View() {
    override val root = pane {
        button("Show Dialog").action {
            find<Dialog1View>().openModal()
        }
    }
}

class Dialog1View : View("Dialog 1") {
    override val root: Pane by fxml()

    override fun onDock() {
        root.addEventFilter(KeyEvent.KEY_PRESSED) {
            println("Key pressed: " + it.code)
        }
    }
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.control.TextField?>
<?import javafx.scene.layout.Pane?>
<Pane xmlns="http://javafx.com/javafx/8.0.112" xmlns:fx="http://javafx.com/fxml/1">
    <TextField/>
</Pane>
```

PS: No need to create yet another variable for the root of the view :)

**Comment by ToninoB** [comment]
Thanks but this solution does not help.
I forgot to tell you  that I also tried to add a TextField before, to not avail.
The DialogView  does get the mouse events but not the key ones.

Another odd behavior : when attached to the main application window pane, a key events handler catch all keystrokes but the space bar, which is filtered out.
I am currently using javaFX8 with the last TornadoFX build.

**Comment by edvin** [comment]
I just ran this code and it works fine. Are you saying that the exact code above doesn't emit events for you? In that case it looks like something on your computer is broken. What version of Oracle JDK are you using?

**Comment by ToninoB** [comment]
1.8.0. 152
I tried some months ago JDK9, but got one compatibiliy issue with... the key events handling !

Another clue: the key events are passed if I use openInternalWindow() instead of openModal().

By the way, are you the creator of TornadoFX ? This framwork is fantastic. I started working with it one year ago after having struggled with javaFX alone for months. I would have gave up the project without this great tool.

**Comment by edvin** [comment]
TornadoFX is not yet compatible with JDK9. We'll switch over once JavaFX is decoupled from the JDK, so that we don't have to do the same job twice :)

Did you run my exact code or some derivative? I wonder if there is a nuance here getting lost in translation :)

Yes, I'm the initial creator of the framework :) So happy to hear that it's helping you :) We'll get this sorted as well, but I've looked at the code and I see no place where we do anything but add event filters, and never mark any events as consumed, so I'm stumped at the moment :)

**Comment by ToninoB** [comment]
Well, congratulations. I hope your work will be very successful.
Of course, I did not use the entire set of functionnalities your libray offers, but overall, it proved to be very convenient to use and above all reliable.  The View model allows the quite easy creation of custom UI objects, an almost impossible task wtih JavaFX alone. I rely also a lot on the EventBus messaging service with I found faster than expected.

**Comment by edvin** [comment]
Great :) The EventBus is extremely light weight, as most things in TornadoFX, so performance shouldn't be an issue :)

**Comment by ToninoB** [comment]
I  did not use your entire code, only the relevant sections.
This  might be a JavaFX only problem.

**Comment by edvin** [comment]
OK. Try to run my exact code. If that works, create a standalone, complete sample that showcases the issue so I can run that and check.

**Comment by ToninoB** [comment]
I found the culprit. This trouble can happen with any View using FXML.
There must be at least one button or similar object (e.g checkbox) declared inside the FXML for the key events to be received by the main window pane.

This layout will not work :
<AnchorPane prefHeight="400.0" prefWidth="600.0"  xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1">
</AnchorPane>

This one will:
<AnchorPane prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1">
  <children>
      <Button layoutX="74.0" layoutY="138.0" mnemonicParsing="false"  />
  </children>
</AnchorPane>

And indeed, the dialog box I was trying to debug has only AnchorPanes for injected Views.

Note that the space bar keystroke is still not catched by the attached handler.
All other keystrokes are properly detected.

Thank you again for your help.

**Comment by ToninoB** [comment]
This layout will not work :
`<AnchorPane`` prefHeight="400.0" prefWidth="600.0" style="-fx-background-color: #2828E0;" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1" />`

This one will:
`
'<AnchorPane prefHeight="400.0" prefWidth="600.0" style="-fx-background-color: #2828E0;" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1">
   <children>
      <Button layoutX="85.0" layoutY="39.0" mnemonicParsing="false" text="Button" />
   </children>
</AnchorPane>`

**Comment by edvin** [comment]
This seems to be a JavaFX limitation and we won't try to mitigate it in TornadoFX, so I'll close the issue. You might want to reconsider using FXML as well, it really doesn't offer any advantages and you end up writing more code compared to our type safe builders :)
