### ISSUE TITLE
Strange problem with setText

### ISSUE THREAD

**Issue by serge-ivamov** [edvin/tornadofx#744]
Hi,

tfField1.text("...
tfLabel1.text("...

didn't works correctly, but

tfField2.setText("...
tfLabel2.setText("...

works good..

```kotlin
import javafx.scene.control.Label
import javafx.scene.control.TextField
import tornadofx.*

/**
 * Created by ares, 30.06.2018 0:00
 *
 *
 */

class TestView : View() {
    override val root = borderpane()

    private lateinit var tfField1: TextField
    private lateinit var tfLabel1: Label

    private lateinit var tfField2: TextField
    private lateinit var tfLabel2: Label

    init {

        with(root) {
            title = "TestView"
            left = vbox {
                tfField1 = textfield("test text field 1")
                tfLabel1 = label("test text field 1")
                button("click me") {
                    action {
                        tfField1.text("more tests 1")
                        tfLabel1.text("more tests 1")
                    }
                }
            }
            right = vbox {
                tfField2 = textfield("test text field 2")
                tfLabel2 = label("test text field 2")
                button("click me") {
                    action {
                        tfField2.setText("more tests 2")
                        tfLabel2.setText("more tests 2")
                    }
                }
            }
        }
    }
} // TestView.class

class TestApp : App(TestView::class) {
} // CallNotifyProtoApp.class

fun main(args: Array<String>) {
    launch<TestApp>(args)
} // main()
```

**Comment by edvin** [comment]
Calling `text()` on a node invokes the `Text` builder. It must not be confused with setting the text property of a node. Please also note that you'd probably almost never call `setText` on a text field, but rather bind the text field to a `StringProperty` and change the `value` of the `StringProperty` instead. I think you would benefit from reading the guide and looking at the examples there.

**Comment by serge-ivamov** [comment]
Thanks, I got it :)

I know about binding, just was confused by Idea's inspection:
"Use property access syntax - can be replaced with Kotlin synthetic properties.

**Comment by edvin** [comment]
Great :) That inspection will convert your code to `tfField2.text = "more tests 2"` - an assignment, not a function call :) I absolutely see how the `text()` builder can be unfortunate/confusing in this case though :)

**Comment by edvin** [comment]
Actually, I'd rather mention that you almost never should manipulate the value of a ui element manually, but rather bind it to an observable property instead. This way you don't need to keep a reference to the ui element, and your code will be easier to read.

**Comment by serge-ivamov** [comment]
Agree, but at prototype stage - direct set can be really usefull.

Btw, really big tnx for tornadofx and your work on this! :)
