### ISSUE TITLE
The alert dialog pops up twice after clicking any button

### ISSUE THREAD

**Issue by Yadarma** [edvin/tornadofx#747]
`
alert(Alert.AlertType.CONFIRMATION, "Inactivation confirmation", "Are you sure to set this user's status inactive?") {
                                    if (result == ButtonType.OK) {
                                        runAsync {
                                            UpdateUser(selectedItem!!.copy(activeStatus = 0L)).execute()
                                        } ui {
                                            resfreshList()
                                        }
                                    } else {
                                        this.close()
                                    }
                                }.showAndWait()`

How can I avoid this duplication ?

**Comment by Yadarma** [comment]
I solved by return@action

**Comment by nimakro** [comment]
Hey @Yadarma,
the reason for the dialog to show up twice, is that the alert builder is calling `showAndWait`by it self (https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Dialogs.kt#L43) and then you are calling it again. So just remove your `showAndWait`call at the end and you should be good to go.
