### ISSUE TITLE
runAsync `finally` equivalent?

### ISSUE THREAD

**Issue by arslancharyev31** [edvin/tornadofx#749]
Good day. I wonder if there is any equivalent of `finally` block for `runAsync` block? For instance:
```Kotlin
runAsync{
    // perform async job
} success {
    // perform success actions
} fail {
    // perform fail actions
} finally {
    // perform common actions, regardless of the callback result,
    // for instance hiding a progress bar, etc...
}
```
If there is no such equivalent, then what would be the most optimal solution to handle these situations?
At the moment the most optimal workaround I see is to extract `finally` block into function and call this function in `success` and `fail` blocks as following:
```Kotlin
fun finalCall(){
    // perform common actions, regardless of the callback result,
    // for instance hiding a progress bar, etc...
}

runAsync{
    // perform async job
} success {
    // perform success actions
    finalCall()
} fail {
    // perform fail actions
    finalCall()
}
```

**Comment by nimakro** [comment]
@arslancharyev31  we currently don't have a `finally`extension function but I think we could add one which would be called either if the task succeeds or fails. I am currently swamped with work but I will try to add it ASP. If you have time we are always happy for PRs. In the mean time you can use your work around and call a function in both success and fail

**Comment by bekwam** [comment]
You can also leverage the completed property.  (Don't forget that you can also bind the Task's running property to a ProgressBar's visible property for the best solution to the specific requirement in your comment.)

```kotlin
class FinallyView : View("Finally App") {

    val running = SimpleBooleanProperty()

    override val root = vbox {

        button("Run") {

            action {

                running.value = true
                runAsync {

                    this.completedProperty.addListener( {
                        _ ->
                            println("completed")
                            running.value = false
                    })

                    println("executing")
                    Thread.sleep(5_000)

                } success {
                    println("succeeded")
                } fail {
                    println("failed")
                }
            }
        }

        label("Running" ) {
            visibleProperty().bind(running)
        }

        padding = Insets(40.0)
    }
}
```

**Comment by arslancharyev31** [comment]
OK, so based on the aforementioned responses, here's a trivial implementation of `finally` block:
```Kotlin
infix fun <T> Task<T>.finally(func: () -> Unit) = (this as FXTask).apply {
		completedProperty.addListener { _ -> func() }
	}
```
However I'm not sure how safe it is to cast `Task` to `FXTask`. Any thoughts?

**Comment by edvin** [comment]
Let's try this:

```kotlin
infix fun <T> Task<T>.finally(func: () -> Unit) {
    if (this is FXTask<*>) {
        completedProperty.onChangeOnce { func() }
    } else {
        throw IllegalArgumentException("finally() called on non-FXTask subclass")
    }
}
```

**Comment by arslancharyev31** [comment]
Thanks @edvin. I wonder if this extension will be in 1.7.17 release?

**Comment by edvin** [comment]
Yes it will :) No, that's not a recursive call, because Kotlin performs a smart cast to FXTask, it will call `FXTask.finally()` instead of calling `Task.finally()` :)

**Comment by arslancharyev31** [comment]
I see. Anyhow, thanks for quick response.
