### ISSUE TITLE
IdeaJ : Run: Edit Configurations: plugin doesn't save App Class value

### ISSUE THREAD

**Issue by ToninoB** [edvin/tornadofx#753]
Ideaj version : 2018 1.5
Tornadofx plugin version : 1.7.14.1

It seems the last Tornadofx plugin for IdeaJ no longer saves the run/debug configuration App Class in the workspace.xml tornadofx section :

> </configuration>
    <configuration name="Main" type="TORNADOFX_RUNCONFIGURATION" factoryName="TornadoFX Configuration Factory" run-type="App" live-views="false" live-stylesheets="false" dump-stylesheets="false">   
      <module name="Test" />
    </configuration>

The field option name="MAIN_CLASS_NAME" value=...
is  missing even if the App Class field has been properly initialized inside the Run/Debug configurations dialog.

A minor issue, because manually adding this field solves the problem. But the previous versions did save it properly.

 @ToninoB

**Comment by SiebelsTim** [comment]
Same as https://github.com/edvin/tornadofx-idea-plugin/issues/57

**Comment by ctadlock** [comment]
^ I think so. Closing.
