### ISSUE TITLE
workspace.dock<>() stops working at commit 207f446f

### ISSUE THREAD

**Issue by kastork** [edvin/tornadofx#755]
This is totally strange.

I have a workspace where in one workspace view, I use a button that is not in the toolbar to dock new workspace view.

```
...
action {
  workspace.dock<MyView>()
}
```

This has been working fine for some months now, and does work fine up until commit 207f446f.

That commit doesn't do anything that should have any effect on this operation, but nevertheless, the view does not get displayed after that point.

As a side note, the warning introduced by that commit is produced when the workspace initially loads -- looks like it is a matter of timing, since the workspace does display sometime after the warning is printed.

**Comment by edvin** [comment]
Could you post a simple demo app with this issue?

**Comment by kastork** [comment]
Sure, https://github.com/kastork/tornadofx-bug775-reproducer

**Comment by edvin** [comment]
OK, I see it. On vacation but will look at it asap. You're doing one weird thing though: `workspace.headingContainer.removeFromParent()` - no need to access `workspace`, since the class you're running the code in _is_ the workspace :) Will get back to you tonight.

**Comment by edvin** [comment]
Another quick hint: You can't dock stuff inside `init` of the Workspace, since the workspace isn't created at that stage. The class is still running the constructor, so if you call `workspace` there, the framework will create yet another workspace. That's why the guide states that you must add the initial view in your App class:

```kotlin
    override fun onBeforeShow(view: UIComponent) {
        workspace.dock<StartView>()
    }
```

**Comment by edvin** [comment]
(It's still a framework bug in here though)

**Comment by edvin** [comment]
Actually, it's not really a bug, but "bad timing" when it comes to the error message .Even if you do `workspace.dock` in `onBeforeShow` the workspace isn't yet shown, which triggers the warning log message. However, it becomes visible shortly after, so no harm done, and everything is working as it should. A bit annoying with that warning message though, thinking about how to avoid it.

**Comment by kastork** [comment]
I've pushed a correction to my reproducer that works with the current head.  Thanks for pointing out the error of my ways.  That workspace class was one of the first tornadofx bits of code I ever wrote and it was nearly a year ago.

I'll close this now.  

Incidentally, the harmless, but odd, invisible workspace warning remains after my correction.

**Comment by edvin** [comment]
I will add a ‘showing’ property to scene so we can avoid the warning as well :)
