### ISSUE TITLE
Textfield delete char string out of range

### ISSUE THREAD

**Issue by lordwho** [edvin/tornadofx#757]
Hey I think this is a bug I cant get my head around this problem it happens when I just create a view with a textfield. and when I then type text into it it is all good but when i hold down the delete char key or just  pressing quickly  I get the following pop up error   

> java.lang.StringIndexOutOfBoundsException: String index out of range: 15
	at java.lang.String.charAt(String.java:658)
	at com.sun.glass.ui.win.WinTextRangeProvider.GetBoundingRectangles(WinTextRangeProvider.java:314)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

I am using java 8 

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>UnitStatus</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <properties>
        <kotlin.version>1.2.51</kotlin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>no.tornado</groupId>
            <artifactId>tornadofx</artifactId>
            <version>1.7.16</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test</artifactId>
            <version>${kotlin.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.197</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.jetbrains.exposed</groupId>
            <artifactId>exposed</artifactId>
            <version>0.10.3</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.17</version>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                        <jvmTarget>1.8</jvmTarget>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jvmTarget>1.8</jvmTarget>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>

        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>
</project>`

**Comment by lordwho** [comment]
btw the index out of range count matches the chars count left in the textfield

**Comment by edvin** [comment]
When you add a textfield in TornadoFX and don't connect any actions to it, it's just a JavaFX textfield. Try the same with a vanilla JavaFX app, you'll probably hit the same bug. Please post your complete code, and I'll help you verify :)

**Comment by edvin** [comment]
Also make sure you use JDK 1.8 u171

**Comment by lordwho** [comment]
Thx Alot! the code is just messy at this point sorry am still  learning :)

app.kt
`package org.example.view

import javafx.beans.property.SimpleBooleanProperty
import javafx.beans.property.SimpleIntegerProperty
import javafx.beans.property.SimpleStringProperty
import javafx.geometry.Pos
import javafx.scene.control.TableView
import javafx.scene.paint.Color
import javafx.scene.text.FontWeight
import jdk.nashorn.internal.objects.annotations.Property
import org.example.Data.ExcelController
import org.example.Data.Products
import org.example.app.Styles
import tornadofx.*
import java.io.IOException
import javax.script.Bindings
import javax.xml.ws.Binding

class CenterView : View("My View") {
    private val ExcelHandler: ExcelController by inject()
    private var content =  mutableListOf<Products>().observable()
    private var oktorun = SimpleBooleanProperty(true)
    val table = TableView<Products>()
    val data = SortedFilteredList(content).bindTo(table)
    private var Accounts =  mutableListOf<String>().observable()



    override val root = borderpane() {

        bottom{
            hbox(10) {

                style{
                    padding = box(10.px)
                    alignment = Pos.CENTER
                }
                hbox(20) {

                    label("Account"){
                        alignment = Pos.BASELINE_CENTER
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.EXTRA_BOLD
                            textFill = Color.GREEN
                        }
                    }
                    textfield {
                        promptText = "Filter"
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                            textFill = Color.PURPLE
                        }
                        data.filterWhen(textProperty()) { query, item ->
                            item.Account!!.contains(query, ignoreCase = true)
                        }
                    }

                }


                button("Import"){
                    addClass(Styles.btmDesign)
                    style{
                       backgroundColor += Color.PURPLE
                        fontFamily = "Comic Sans MS"
                    }
                    useMaxWidth = true
                    enableWhen(oktorun)
                    action {
                        val file = chooseFile(filters = arrayOf())
                        if (file.isNotEmpty()){
                            oktorun.value = false
                            runAsync {
                                ExcelHandler.readExcel(file[0].toString())
                            } ui { loadedText ->
                                content.isEmpty()
                                content.addAll(loadedText.observable())
                                Accounts.addAll(loadedText.map { it.Account }.toList().distinct()
                                        .observable())
                                oktorun.value = true
                            }
                        }




                    }
                }
                vbox{
                    label("Rows ")
                    {
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                        }
                    }
                    label(data.sizeProperty.stringBinding {it.toString()}) {
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                            textFill = Color.GREEN
                        }

                    }
                }


        }



        center{
            style{
                prefWidth = 100.px
                alignment = Pos.CENTER
                padding = box(20.px)
            }
            tableview(data) {
                isEditable = true

                style{

                    fontSize =20.px
                    fontWeight = FontWeight.EXTRA_BOLD
                }
                column("External", Products::ExternalProperty)
                column("ItemRelation", Products::ItemRelationProperty)
                column("Account",Products::AccountProperty)
                column("Price", Products::AmmountProperty)
                column("currency", Products::ValutaProperty)
                column("Date", Products::DateProperty)
                column("Status", Products::StatusProperty)
                enableDirtyTracking()
                columnResizePolicy = SmartResize.POLICY

            }.multiSelect(true)
        }

        right {

        }


    }


}
}

`
MainView.kt
`package org.example.view


import javafx.scene.control.TabPane
import javafx.scene.paint.Color
import javafx.scene.text.FontWeight
import tornadofx.*

class MainView : View() {
    val topview: TopView by inject()
    val centerView: CenterView by inject()
    override val root = borderpane(){
         setPrefSize(1400.0, 700.0)
        top = topview.root
        center = centerView.root
}
}`

TopView.kt

`package org.example.view

import javafx.geometry.Pos
import javafx.scene.paint.Color
import javafx.scene.text.Font
import javafx.scene.text.FontWeight
import javafx.scene.text.TextAlignment
import tornadofx.*

class TopView : View() {
    override val root = borderpane {
        center = textflow {
            textAlignment = TextAlignment.CENTER
            text("UnitStatus"){
                font = Font(32.0)
                fill = Color.PURPLE
                style{
                    fontFamily = "Comic Sans MS"
                    fontWeight = FontWeight.BOLD
                }
            }
            text("DB"){
                font = Font(40.0)
                fill = Color.ORANGE
                style{
                    fontWeight = FontWeight.EXTRA_BOLD
                    fontFamily = "Comic Sans MS"

                }
            }
        }
    }
}

`

CenterView.kt
`package org.example.view

import javafx.beans.property.SimpleBooleanProperty
import javafx.beans.property.SimpleIntegerProperty
import javafx.beans.property.SimpleStringProperty
import javafx.geometry.Pos
import javafx.scene.control.TableView
import javafx.scene.paint.Color
import javafx.scene.text.FontWeight
import jdk.nashorn.internal.objects.annotations.Property
import org.example.Data.ExcelController
import org.example.Data.Products
import org.example.app.Styles
import tornadofx.*
import java.io.IOException
import javax.script.Bindings
import javax.xml.ws.Binding

class CenterView : View("My View") {
    private val ExcelHandler: ExcelController by inject()
    private var content =  mutableListOf<Products>().observable()
    private var oktorun = SimpleBooleanProperty(true)
    val table = TableView<Products>()
    val data = SortedFilteredList(content).bindTo(table)
    private var Accounts =  mutableListOf<String>().observable()



    override val root = borderpane() {

        bottom{
            hbox(10) {

                style{
                    padding = box(10.px)
                    alignment = Pos.CENTER
                }
                hbox(20) {

                    label("Account"){
                        alignment = Pos.BASELINE_CENTER
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.EXTRA_BOLD
                            textFill = Color.GREEN
                        }
                    }
                    textfield {
                        promptText = "Filter"
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                            textFill = Color.PURPLE
                        }
                        data.filterWhen(textProperty()) { query, item ->
                            item.Account!!.contains(query, ignoreCase = true)
                        }
                    }

                }


                button("Import"){
                    addClass(Styles.btmDesign)
                    style{
                       backgroundColor += Color.PURPLE
                        fontFamily = "Comic Sans MS"
                    }
                    useMaxWidth = true
                    enableWhen(oktorun)
                    action {
                        val file = chooseFile(filters = arrayOf())
                        if (file.isNotEmpty()){
                            oktorun.value = false
                            runAsync {
                                ExcelHandler.readExcel(file[0])
                            } ui { loadedText ->
                                content.isEmpty()
                                content.addAll(loadedText.observable())
                                Accounts.addAll(loadedText.map { it.Account }.toList().distinct()
                                        .observable())
                                oktorun.value = true
                            }
                        }




                    }
                }
                vbox{
                    label("Rows ")
                    {
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                        }
                    }
                    label(data.sizeProperty.stringBinding {it.toString()}) {
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                            textFill = Color.GREEN
                        }

                    }
                }


        }



        center{
            style{
                prefWidth = 100.px
                alignment = Pos.CENTER
                padding = box(20.px)
            }
            tableview(data) {
                isEditable = true

                style{

                    fontSize =20.px
                    fontWeight = FontWeight.EXTRA_BOLD
                }
                column("External", Products::ExternalProperty)
                column("ItemRelation", Products::ItemRelationProperty)
                column("Account",Products::AccountProperty)
                column("Price", Products::AmmountProperty)
                column("currency", Products::ValutaProperty)
                column("Date", Products::DateProperty)
                column("Status", Products::StatusProperty)
                enableDirtyTracking()
                columnResizePolicy = SmartResize.POLICY

            }.multiSelect(true)
        }

        right {

        }


    }


}
}
`

and the controller is just a fun that reads Excel. Hope your eyes is okay after all that :)

**Comment by edvin** [comment]
You said you could just create a view with a textfield and trigger this bug. Please submit that code instead of all this :)

**Comment by lordwho** [comment]
Ahh got you !

**Comment by lordwho** [comment]
Okay so i just created a testview and puton a textfield and injected the view to my Centerview borderpane right side and the same thing happens. I know you probly want to javafx example but am sry  i dont know how that works exactly 

java.lang.StringIndexOutOfBoundsException: String index out of range: 10
	at java.lang.String.substring(String.java:1963)
	at com.sun.glass.ui.win.WinTextRangeProvider.GetText(WinTextRangeProvider.java:348)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
``

package org.example.view

import tornadofx.*

class testview : View("My View") {
    override val root = vbox {
        textfield {  }
    }
}
``

**Comment by edvin** [comment]
This works fine for me, no issues. Exactly what version of the JDK are you using?

**Comment by lordwho** [comment]
okay well I am using   NetBeans with JDK 8

**Comment by lordwho** [comment]
but i forgot to mention that it happens kinda randomly but it happens often what i mean is i can for example write 10 chars and delete them all fine while holding down the key but the problem happens 8/10

**Comment by lordwho** [comment]
What Version are you using ?

**Comment by bekwam** [comment]
I ran this on Ubuntu JDK 1.8.0_172.  I'm using Topre but I've never seen a problem like this with any other switch type.

My tests were to add 10 digits then delete, holding the delete key down.  I did the same with backspace.  I also tried putting the cursor in the middle of the textfield.

````
class KeyTestView : View("Key Test") {
    override val root = vbox { textfield {} }
}

class KeyTest : App(KeyTestView::class)

fun main(args: Array<String>) {
    launch<KeyTest>(args)
}
````

**Comment by edvin** [comment]
Try this Java app and see if you get the same issue:

```java
public class KeyTest extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        VBox root = new VBox();
        TextField tf = new TextField();
        root.getChildren().add(tf);
        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }
}
```

**Comment by lordwho** [comment]
Wait a sec  i just tried your kotlin example so and it works fine for me as well but my own example when I put it on my own Center view  it gives the problem. hm i must be a issue with the placement then?

**Comment by bekwam** [comment]
If you post a minimal program that throws your exception, I can try and verify it for you.

**Comment by lordwho** [comment]
This is the borderrpane   
`bottom{
            hbox(10) {

                style{
                    padding = box(10.px)
                    alignment = Pos.CENTER
                }
                hbox(20) {

                    label("Account"){
                        alignment = Pos.BASELINE_CENTER
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.EXTRA_BOLD
                            textFill = Color.GREEN
                        }
                    }
                    textfield {
                        promptText = "Filter"
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                            textFill = Color.PURPLE
                        }
                        data.filterWhen(textProperty()) { query, item ->
                            item.Account!!.contains(query, ignoreCase = true)
                        }
                    }

                }


                button("Import"){
                    addClass(Styles.btmDesign)
                    style{
                       backgroundColor += Color.PURPLE
                        fontFamily = "Comic Sans MS"
                    }
                    useMaxWidth = true
                    enableWhen(oktorun)
                    action {
                        val file = chooseFile(filters = arrayOf())
                        if (file.isNotEmpty()){
                            oktorun.value = false
                            runAsync {
                                ExcelHandler.readExcel(file[0].toString())
                            } ui { loadedText ->
                                content.isEmpty()
                                content.addAll(loadedText.observable())
                                Accounts.addAll(loadedText.map { it.Account }.toList().distinct()
                                        .observable())
                                oktorun.value = true
                            }
                        }




                    }
                }
                vbox{
                    label("Rows ")
                    {
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                        }
                    }
                    label(data.sizeProperty.stringBinding {it.toString()}) {
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                            textFill = Color.GREEN
                        }

                    }
                }


        }`

**Comment by lordwho** [comment]
well okay i will just try that

**Comment by lordwho** [comment]
Okay Okay I lost now it i cant even reproduce the problem in my actual app now this is weird well can we leave this post up for abit  just in case i find the issue if it even is.  cuz am a little confused at this point i havnet changed anything since I tested it like 50 times recompiled every time ofc

**Comment by lordwho** [comment]
Well the problem is happening to me agian now same setup and now it happens in the simple test app as well. it is probly not a problem with the framework then when it is so random. just a last try i made the simple app you asked for and it produce the error for me "atm" :) so if you can find a minute to try it and if you dont see any errors well please close or delete this post. Thanks for you time

`
import javafx.geometry.Pos
import javafx.scene.paint.Color
import javafx.scene.text.FontWeight
import tornadofx.*
class Products(var name: String)

class KeyTestView : View("Key Test") {
    var l = mutableListOf<Products>().observable()
    override val root = borderpane() {
        setPrefSize(1400.0, 800.0)

        center{
            tableview(l) {  }
        }
        bottom{
            hbox(10) {

                style{
                    padding = box(10.px)
                    alignment = Pos.CENTER
                }
                hbox(20) {

                    label("Account"){
                        alignment = Pos.BASELINE_CENTER
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.EXTRA_BOLD
                            textFill = Color.GREEN
                        }
                    }
                    textfield {
                        promptText = "Filter"
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                            textFill = Color.PURPLE
                        }
//
                    }

                }


                button("Import"){
                    addClass(Styles.btmDesign)
                    style{
                        backgroundColor += Color.PURPLE
                        fontFamily = "Comic Sans MS"
                    }
                    useMaxWidth = true
                    action {

                        }




                    }
                vbox{
                    label("Rows ")
                    {
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                        }
                    }
                    label("54654") {
                        style{
                            fontSize = 20.px
                            fontWeight = FontWeight.BOLD
                            textFill = Color.GREEN
                        }

                    }
                }
                }



            }
    }
}

class KeyTest : App(KeyTestView::class)

fun main(args: Array<String>) {
    launch<KeyTest>(args)
}`

**Comment by edvin** [comment]
This works fine for me, so I'll close the issue. Seems to be an issue with your JDK or local environment somehow.
