### ISSUE TITLE
Some More Control Builders

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#76]
As I'm documenting the guide, I'm doing a sweep for more simple controls that probably should be added

~~ToggleButton~~
~~RadioButton~~
~~Slider~~
~~TextFlow~~
~~ChoiceBox~~
~~PasswordField~~
~~Separator~~
~~HyperLink~~
~~ColorPicker~~
~~FileChooser~~
~~Pagination~~
~~HTMLEditor~~

I know the [TextFlow](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextFlow.html) is a lesser-used control, but considering JavaFX lacks html formatting for label text (like Swing) it is helpful to format a string of text with different colors. I use this feature quite a bit to concatenate data with different conditional formatting rules.

Let me know if we want to scratch any of these, and I'll work on adding whatever we wan)

**Comment by thomasnield** [comment]
Of course, if anybody (including newcomers) want to knock some of these out I'll welcome the help. Many of these are pretty easy to implement.

**Comment by edvin** [comment]
Very good initiative! It would be great if some newcomers would like to add a couple of these! I suggest making a comment on this thread before you start with a control to avoid more people working on the same control.

**Comment by edvin** [comment]
I will hold off on https://github.com/edvin/tornadofx/issues/57 until this issue is resolved.

**Comment by thomasnield** [comment]
Good call. We will probably need to do a code freeze in some form when #57 gets implemented.

**Comment by edvin** [comment]
Yeah, but I figure it can be done in a couple of hours, so it should be a huge problem :)

**Comment by t-boom** [comment]
For the `PasswordField`, would want to pass in an initial value (such as a saved password)? This can always be done with `apply { text = value }`, but is it common enough to add an optional parameter to the `Pane.passwordfield` method?

Also, I'm assuming there's no real use case for double binding the text of a password field like there is for a text field, but let me know if I'm wrong.

**Comment by thomasnield** [comment]
Absolutely. Add a default value for the password() function. We try to streamline towards common use cases and that definitely is one.

I agree with that sentiment regarding binding like a text field. Doesn't feel like that would be very common, and I don't think that would encourage secure design.

**Comment by t-boom** [comment]
Sounds good

**Comment by t-boom** [comment]
For the `ToggleButton`, how should grouping be handled? I'm thinking either create a `Pane.togglegroup` method that doesn't add anything to the pane but does return a `ToggleGroup`, or have a toggle group scope of some sort in which toggle buttons can be added to the pane and automatically have the group attached. Of course, nothing is stopping us from doing both.

**Comment by t-boom** [comment]
The second option requires returning something like `Pair<Pane, ToggleGroup>` so we know where to attach the button.

Here's what I have so far:

```kotlin
fun Pane.togglebutton(text: String = "", group: ToggleGroup? = null, op: (ToggleButton.() -> Unit)? = null) = opcr(this, ToggleButton(text).apply { if (group != null) toggleGroup = group }, op)

fun Pane.togglegroup(op: (ToggleGroup.() -> Unit)? = null): Pair<Pane, ToggleGroup> {
    val group = ToggleGroup()
    op?.invoke(group)
    return Pair(this, group)
}

fun Pair<Pane, ToggleGroup>.button(text: String = "", op: (ToggleButton.() -> Unit)? = null) = opcr(first, ToggleButton(text), op)
```

**Comment by t-boom** [comment]
Currently I just have the first option implemented

```kotlin
fun Pane.togglegroup() = ToggleGroup()

fun Pane.togglebutton(text: String = "", group: ToggleGroup? = null, op: (ToggleButton.() -> Unit)? = null)
        = opcr(this, ToggleButton(text).apply { if (group != null) toggleGroup = group }, op)
```

**Comment by t-boom** [comment]
(This problem also applies to `RadioButton`s)

**Comment by thomasnield** [comment]
Cafe internet is not cooperating with me. Give me a moment...

**Comment by thomasnield** [comment]
Okay these are some good points, let me think through this. Hacking my way through this right now.

**Comment by t-boom** [comment]
Just a heads up, I've also tried adding the pane as the userdata of the toggle group (though this pretty much bypasses type safety). My next idea either an extension property or a small class that extends from `ToggleGroup`

**Comment by thomasnield** [comment]
There's got to be cleaner way to do this without the `Pair`. Trying a few things.

**Comment by thomasnield** [comment]
Okay, maybe we need to step back because I think you and I are abstracting `ToggleGroup` into something it is not. Could not, in theory, ToggleButtons in a given ToggleGroup be completely separated?

While it seems natural, we start fighting JavaFX if we treat `ToggleGroup` like its a `Pane` that contains ToggleButtons together.

```kotlin
class MyView: View() {
    override val root = VBox()

    val grp = ToggleGroup()
    init {
        with(root) {

            togglebutton("1").apply {
                toggleGroup = grp
            }

            togglebutton("2").apply {
                toggleGroup = grp
            }

            togglebutton("3").apply {
                toggleGroup = grp
            }
        }
    }
}
```

If that's too repetitive for you, just create an internal extension function for re-usability.

```kotlin
class MyView: View() {
    override val root = VBox()

    val optionGrp = ToggleGroup()
    init {
        with(root) {
            togglebutton("1").addToOptionGrp()
            togglebutton("2").addToOptionGrp()
            togglebutton("3").addToOptionGrp()
        }
    }

    private fun ToggleButton.addToOptionGrp() {
        toggleGroup = optionGrp
    }
}
```

What do you think @edvin?

**Comment by thomasnield** [comment]
By the way, I'll ~~strikethrough~~ controls on the OP list as they get knocked out.

**Comment by edvin** [comment]
I'm here, having a look at togglegroup now :)

**Comment by edvin** [comment]
One suggestion (still thinking though):

```kotlin
class MyView: View() {
    override val root = VBox()

    val optionGrp = ToggleGroup()
    init {
        with(root) {
            togglebutton("1", optionGrp)
            togglebutton("2", optionGrp)
            togglebutton("3", optionGrp)
        }
    }
}
```

**Comment by edvin** [comment]
Hmm... Maybe I'm missing something, but that seems quite simple to implement, and with no major drawbacks as far as I can see :)

**Comment by thomasnield** [comment]
You mean nesting `ToggleButton` builders into a `ToggleGroup` builder?

**Comment by edvin** [comment]
The main thing is that it's easy to understand, and not much boiler plate. Ofcourse we could save "the current toggle group" in a state variable, but I fear it will feel a bit magical.

**Comment by edvin** [comment]
I don't know if it's worth having a toggleGroup builder. Hmm.. I could try to mock up an implementation that does magic, and see how it feels though.

**Comment by thomasnield** [comment]
It certainly would be convenient if there's an elegant way to do it. My guess is it will require creating an extension class or something. But maybe we can use a fake 'Pane' pattern, but I tried that and got a little dizzy.

**Comment by t-boom** [comment]
I've got `Hyperlink` and `PasswordField` done, as well as the non-magic `ToggleButton` and `RadioButton`. I'll submit a PR, and magic `ToggleGroup` stuff can be done later. :)

**Comment by edvin** [comment]
Very nice @t-boom ! I'll try one more thing with ToggleButton, hang on.

**Comment by t-boom** [comment]
Oops, didn't see your message soon enough :)

**Comment by t-boom** [comment]
I can pull the radiobutton and togglebutton code out of the PR

**Comment by edvin** [comment]
I think I have an idea, kind of what @t-boom already suggested:

```kotlin

init {
    with(root) {
        // Create a new togglegroup and assign it to root
        togglegroup() 
        // The togglebutton builder function checks if the node it's added to
        // is associated with a togglegroup, and adds it to that group
        togglebutton("Alice") 

        hbox {
            // Add another togglegroup
            togglegroup()
            // Buttons in the hbox will be added to the second group
            togglebutton("Bob")
        }
    }
}
```

The parent node could populate properties["tornadofx.togglegroup"] with the actual togglegroup. Then we could also add features to Node like `hasToggleGroup` and `getToggleGroup()` etc.

**Comment by thomasnield** [comment]
That is an intriguing idea. I can't think of a way it would backfire so lets go with it. The only drawback I can think of is there is no clear structural relationship between the toggle buttons and the toggle group syntactically, but with some documentation that can quickly be overcome.

**Comment by t-boom** [comment]
Edge case: What if we want to not use a toggle group after one is created (such as Charlie below)?

```kotlin
init {
    with(root) {
        // Create a new togglegroup and assign it to root
        togglegroup() 
        // The togglebutton builder function checks if the node it's added to
        // is associated with a togglegroup, and adds it to that group
        togglebutton("Alice") 

        // I don't want this button in the toggle group
        togglebutton("Charlie")

        hbox {
            // Add another togglegroup
            togglegroup()
            // Buttons in the hbox will be added to the second group
            togglebutton("Bob")
        }
    }
}
```

Another thing to worry about is trying to add to an *earlier* toggle group after one has been created

```kotlin
init {
    with(root) {
        // Create a new togglegroup and assign it to root
        togglegroup() // <- This is Fred
        // The togglebutton builder function checks if the node it's added to
        // is associated with a togglegroup, and adds it to that group
        togglebutton("Alice") 
        // Start a new toggle group
        togglegroup()
        // The togglebutton builder function checks if the node it's added to
        // is associated with a togglegroup, and adds it to that group
        togglebutton("Charlie") 

        // I want to add this one to Fred
        togglebutton("Dave")
        hbox {
            // Add another togglegroup
            togglegroup()
            // Buttons in the hbox will be added to the second group
            togglebutton("Bob")
        }
    }
}
```

**Comment by thomasnield** [comment]
In a way it kind of turns a Pane into a ToggleGroup which I like : )

**Comment by thomasnield** [comment]
Does the toggle group associate with its parent?

**Comment by edvin** [comment]
Saving private Charlie:

```kotlin
togglebutton("Charlie", null)
```

Marry Dave and Fred <3:

```kotlin
val fred = togglegroup()
...
togglebutton("Dave", fred)
```

**Comment by t-boom** [comment]
Ah, simple indeed. I like it :)

**Comment by edvin** [comment]
Cool! Then I think we have a winner. You might as well add it to the PR before I merge? :)

**Comment by thomasnield** [comment]
I agree looks good.

**Comment by edvin** [comment]
I think you can do something like this to solve the togglegroup assignment:

```kotlin
fun Node.getToggleGroup(): ToggleGroup? = properties["tornadofx.togglegroup"] as ToggleGroup?

fun Pane.togglebutton(text: String = "", group: ToggleGroup? = getToggleGroup(), op: (ToggleButton.() -> Unit)? = null) {
    ...
}
```

So, default will be to lookup the group in the current Pane, and a passed null value will override that.

**Comment by edvin** [comment]
This was a good talk, I think we landed on a nice solution. Thanks, guys! :)

**Comment by t-boom** [comment]
Sorry, someone else will have to. Something came up and I have to go (most likely for the rest of the day). My availability this weekend will be sporadic at best, so I don't know if I'll be around to do much more till next week :frowning:

**Comment by edvin** [comment]
No worries, @t-boom :) I'm quite busy this weekend myself, and probably Thomas as well, so either you'll have a look next week, or I can merge and do the rest then if you're still busy. Have a nice weekend!

**Comment by thomasnield** [comment]
I'll see if I can make time to handle the PR in the next day or two. Thanks for getting involved @t-boom. We're glad to have you onboard.

**Comment by thomasnield** [comment]
Okay I merged and made those tweaks to @t-boom's work. Updated list at top of this thread: 5 down, 7 to go.

**Comment by thomasnield** [comment]
I also added `TextFlow` and `Text` builders.

```kotlin
class MyApp: SingleViewApp() {
    override val root = VBox()

    init {
        with(root) {
            text("A TextFlow Demo")
            
            textflow {
                text("Hello") {
                    fill = Color.RED
                }
                text(" World") {
                    fill = Color.BLUE
                    font = Font.font(20.0)
                }
            }
        }
    }
}
```

![](http://i.imgur.com/z9gSAQo.png)

**Comment by edvin** [comment]
Fantastic work!

**Comment by t-boom** [comment]
Just to keep information together: slider and separator are merged in now, and I have a PR for htmleditor.

**Comment by thomasnield** [comment]
Excellent, just crossed those off and I'll follow up with HTMLEditor shortly. Thanks again for spending time on this.

**Comment by t-boom** [comment]
HTMLEditor is now merged as well.

**Comment by t-boom** [comment]
@thomasnield My pleasure. This is an awesome project.

**Comment by edvin** [comment]
I'm adding `chooseFile` in `Dialogs.kt` since the FileChooser is not a UI component. Docs and usage:


> Ask the user to select one or more files from a file chooser dialog. The mode will dictate how the dialog works, by allowing single selection, multi selection or save functionality. The file dialog will only allow files that match one of the given ExtensionFilters.

> This function blocks until the user has made a selection, and can optionally block a specified owner Window.

> If the user cancels, the returned file list will be empty.

```kotlin
// Select multiple files
val filters = arrayOf(FileChooser.ExtensionFilter("Text files", "*.txt"))
val files: List<File> = chooseFile("Select some text files", filters, FileChooserMode.Multi)
println("The user chose $files")

// Present save dialog
val files: List<File> = chooseFile("Save document", filters, FileChooserMode.Save)
if (files.isNotEmpty()) save(files.first())
```

**Comment by edvin** [comment]
Added colorpicker builder with optional initial color an enum to select mode.

```kotlin
colorpicker()

colorpicker(Color.MAROON)

colorpicker(Color.MAROON, ColorPickerMode.MenuButton) {

colorpicker(Color.MAROON, ColorPickerMode.MenuButton) {
    customColors.addAll(Color.BLANCHEDALMOND, Color.AQUAMARINE)
}
```

**Comment by edvin** [comment]
I think that's it :) Any comments, or should we close this issue?

**Comment by thomasnield** [comment]
Nice!!!
