### ISSUE TITLE
Proposal: Remove snake case from CssElementDelegate

### ISSUE THREAD

**Issue by ruckustboom** [edvin/tornadofx#760]
CSS Elements don't use snake case by default as they are usually the class name, so it doesn't really make sense to include the option in the delegate.

Removing it would leave two options

1. Use the property name literally as the default value
2. Always require the user to pass in a name

The first one would be more consistent with how the other rules are defined, but may be pointless as using the proper names may lead to the naming conflicts that kept us from including them in the first place.

**Comment by ruckustboom** [comment]
As it stands now:

```
val rectangle by csselement()  // Becomes `rectangle`
val Rectangle by csselement()  // Becomes `rectangle` (val may conflict with `Rectangle` class)
val myRectangle by csselement()  // Becomes `my-rectangle`
val rectangle by csselement("Rectangle")  // Becomes `Rectangle`
```

With option 1:

```
val rectangle by csselement()  // Becomes `rectangle`
val Rectangle by csselement()  // Becomes `Rectangle` (val may conflict with `Rectangle` class)
val myRectangle by csselement()  // Becomes `myRectangle`
val rectangle by csselement("Rectangle")  // Becomes `Rectangle`
```

With option 2:

```
val rectangle by csselement()  // INVALID
val Rectangle by csselement()  // INVALID (val may conflict with `Rectangle` class)
val myRectangle by csselement()  // INVALID
val rectangle by csselement("Rectangle")  // Becomes `Rectangle`
```

**Comment by edvin** [comment]
I believe option 2 will cause less confusion, and the fix for existing code is simple. Anybody else want to weigh in?

**Comment by ruckustboom** [comment]
I guess there is also the option to just leave the snake case option, but always default it to false. That way the user can override it if they want:

```kotlin
val myRectangle by csselement()  // Becomes `myRectangle`
val myRectangle by csselement(snakeCase = true)  // Becomes `my-rectangle`
```

Granted, if we leave that in, I don't see any advantage over just leaving the current implementation, as it's at least consistent with the other `CSSRule`s.

**Comment by ruckustboom** [comment]
I realize I never actually finished this task. Are you still thinking option 2 would be good Edvin? If so, I'd recommend the change for the jdk10 branch (and thus for TFX 2).

**Comment by edvin** [comment]
Ah, sweet! Yes, option 2 sounds like the best approach. Chucking it right in the jdk10 branch is a good way to go, and we can easily describe this change in behavior in the release docs for 2.0.0. I really need to get my ass moving on the T2 release!! Sorry it's taking so long.
