### ISSUE TITLE
Proposal: TrayIcon event subscription implementation

### ISSUE THREAD

**Issue by spajo** [edvin/tornadofx#761]
Hi!

I recently started tinkering around with TornadoFx and wanted to write an app that shows notification bubbles from TrayIcon. I ran to the problem with event subscription to show notifications. After a few hours of playing around I ended up with something like this: 
```kotlin
trayicon(resources.stream("/icon.png"), "Tornado", autoSize = true) {
    setOnMouseClicked(fxThread = true) {
        showToFront()
    }
    menu("TornadoFX") {
        // menu code
    }

    FX.eventbus.subscribe(event = MyEvent::class, scope = scope,
            registration = FXEventRegistration(eventType = MyEvent::class, owner = null, maxCount = null,
                    action = { displayMessage("test", "test", TrayIcon.MessageType.INFO) }))
}
```

I haven't found any other (prettier/better) way of doing this. I think it would be nice to have subscribe method inside the TrayIcon class, so it would look like subscribe in Controllers or such. 
```kotlin
trayicon(...) {
    subscribe<MyEvent> {
        // do something
    }
}
```
Also it would be nice if ```FX.eventbus``` and ```FXEventRegistration``` had some documentation, I couldn't find it on dokka.

Thanks for such an awesome framework :D
Rafal

**Comment by spajo** [comment]
I guess you could also pass the reference of trayIcon to Controller, like this:
```kotlin
trayicon(...) {
    find(MyController::class).trayIcon = this
}
```
But I think that having subscribe inside the ```trayicon``` would be much more elegant.

**Comment by edvin** [comment]
The EventBus is primarily meant for inter-Component communication, but it can easily be used from anywhere by calling one of the overloaded `subscribe` functions on `EventBus`:


```kotlin
FX.eventbus.subscribe<MyEvent>(null, null, scope) {
    displayMessage("test", "test", TrayIcon.MessageType.INFO)
}
```

The documentation for EventBus is here:

https://github.com/edvin/tornadofx-guide/blob/master/part2/EventBus.md

If you have time, a PR with information about how to use event registration from for example `trayicon` would be much appreciated!

**Comment by spajo** [comment]
Okay, thanks!

When I'll find some time I'll whip something up for sure! I am in the middle of moving, so it could even be a month before I submit anything.

Anyways, thanks I'll close this issue :)
