### ISSUE TITLE
Support for external stylesheets

### ISSUE THREAD

**Issue by otoomey** [edvin/tornadofx#762]
The current implementation of `importStylesheet()` only supports 'internal' stylesheets, i.e. only those located in the resources folder:
```java
fun importStylesheet(stylesheet: String) {
    val css = FX::class.java.getResource(stylesheet)
    if (css != null)
        stylesheets.add(css.toExternalForm())
    else
        FX.log.log(Level.WARNING, "Unable to find stylesheet at $stylesheet - check that the path is correct")
}
``` 
**Why should support for external stylesheets by added?**
I like to use Google Fonts in my projects, which means I need to add a customised stylesheet, from a URL that Google provides, to my scene. Many font providers, especially for icon fonts, require you to do this. Adding support would remove the need for people to download and manually load these stylesheets themselves.

In the current implementation, it is possible to load external stylesheets by calling `FX.stylesheets.add()` yourself, and passing the URL. A more graceful solution would be greatly appreciated, something along the lines of `importExternalStylesheet(). In fact, an asynchronous method, or one that caches the result, would be even better. Loading stylesheets from the web can take a while, freezing the UI thread.

**Comment by edvin** [comment]
We can improve importStylesheet so it detects if an http/https URL is given, and if so loads the external stylesheet async. What do you think?

**Comment by edvin** [comment]
One way of doing that could be to support file:// URLS as well? So still the same function, but it would support classpath, local file and remote hosts.

**Comment by ruckustboom** [comment]
That could work well, especially if there's an overload that accepts a `File` or `Path` that automatically converts the URL.

**Comment by otoomey** [comment]
@edvin Checking for the http/https prefix would probably work, however you would have to make it clear to the user that they absolutely have to provide that prefix in order to load the stylesheet. After all, something like "localhost:8080/assets/styles.css" is technically still a valid URL.

A safer solution would be to create `net.URL` object from the input string. If the string is not a valid url, a `MalformedURLException` will be thrown. This would completely avoid having to create a complex regex pattern to match against. 

@ruckustboom  for files on the local file system, you could do something similar using `io.File`. The `exists()` method will return true if it (surprise) exists. Checking and loading from the resources folder could then be done if both the exception is thrown and the method returns false.

**Comment by bekwam** [comment]
@otoomey A URL needs a scheme.

**Comment by edvin** [comment]
@bekwam is correct, you need to specify a protocol for it to be a URL. Of course we would use existing functionality to validate the URL :) OK, if we agree this is a good idea, I'll try to implement it tonight :)

**Comment by otoomey** [comment]
@bekwam You are right, `net.URL` cannot infer the scheme it seems. I always figured that, since the browser can do it, java's implementation could also do it. My bad.

@edvin Sounds good, look forward to seeing it in the next build! :D

**Comment by edvin** [comment]
I have committed support for `Path` stylesheets as well as any URL with a protocol that Java can resolve, meaning at least `http`, `https` and `file` URLs :)

**Comment by edvin** [comment]
Can we close the issue? :)
