### ISSUE TITLE
should styleClass be a map instead of a list?

### ISSUE THREAD

**Issue by ethanmdavidson** [edvin/tornadofx#766]
The css classes on a node are stored in an ObservableList (Node.getStyleClass()), which means that if you accidentally call addClass(myClass) twice, then your first call to removeClass(myClass) will have no affect on the styling (because List.remove(Object o) only removes the first instance).

I'm not the most experienced with CSS and I wasn't able to find much information on this, but duplicate classes [are apparently valid, though their effect is limited to very specific edge cases](https://stackoverflow.com/questions/8828687/css-does-repeating-the-same-class-on-an-element-change-any-behavior). (Also, I'm not sure if this applies to CSS in JavaFX).

Let me know if I'm not explaining this clearly and I can provide a code example.

Are there any legitimate use cases for having the same class multiple times on the same node? If not, shouldn't it be changed to an ObservableMap?

**Comment by ruckustboom** [comment]
This is fundamental to JavaFX and can't be changed by TornadoFX. You could try submitting an issue to the OpenJFX project, but that would be a huge breaking change and I doubt you'd get much traction.

**Comment by ethanmdavidson** [comment]
Oops, you're right. I didn't pay enough attention when tracing it through.

However, I think the question is still valid, and TornadoFX could still abstract it away.
For example, it could use removeAll() instead of remove()
```kotlin
fun <T : Node> T.removeClass(className: String) = apply { styleClass.removeAll(className) }
```

or by checking if the class already exists in the list before adding it.
It seems like it could be a bad design choice because it changes the expected behavior from JavaFX, but it also feels much more sane to have removeClass() actually remove the class completely. Thoughts?

**Comment by ruckustboom** [comment]
It's not a bad idea actually. I'd recommend opening a separate issue for that (as that is a rather different issue from this one) so it can be discussed there. We could potentially even add a parameter

```
fun <T: Node> T.removeClass(className: String, removeMultiple: Boolean = false) = apply {
    if (removeMultiple) styleClass.removeAll(className) else styleClass -= classname
}
```

**Comment by ethanmdavidson** [comment]
Will do.
