### ISSUE TITLE
lazyPopulate leafCheck is still broken

### ISSUE THREAD

**Issue by altavir** [edvin/tornadofx#773]
[This line](https://github.com/edvin/tornadofx/blob/0cb097babc906d35ea513754f74d9b2ee74193d1/src/main/java/tornadofx/ItemControls.kt#L221) states that `leafCheck` returns true if element is node but [this line](https://github.com/edvin/tornadofx/blob/0cb097babc906d35ea513754f74d9b2ee74193d1/src/main/java/tornadofx/ItemControls.kt#L247) states that element is leaf if `leafCheck` is true, so conditions work in opposite directions for root children and for subnodes, making in impossible to create actual tree.

I think that is should be at least minimally documented what does `true` in `leafCheck` means since it is not obvious from its name.

Only one symbol needs to be changed (`!` in one of the places).

**Comment by edvin** [comment]
Thanks for reporting. I've negated the first check, it should return true if it's a leaf, and not a branch.
