### ISSUE TITLE
Program crashes if use `region` with max width

### ISSUE THREAD

**Issue by freewind** [edvin/tornadofx#778]
```
class HelloWorld : View() {
    override val root = flowpane {
        region { setPrefSize(Double.MAX_VALUE, 0.0) }
    }
}
```

When started, program crashes:

```
2018-08-10 19:53:34.068 java[92700:416158] PersistentUI: CGSGetRegionData returned error 1007 on line 35
2018-08-10 19:53:34.069 java[92700:416158] PersistentUI: CGSGetRegionData returned error 1007 on line 35
java(92700,0x7fff8bbc1340) malloc: *** mach_vm_map(size=3899830308864) failed (error code=4)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
java(92700,0x7fff8bbc1340) malloc: *** mach_vm_map(size=3899830308864) failed (error code=4)
*** error: can't allocate region
```

But the JavaFX version with same code works good.

See the demo: <https://github.com/freewind-demos/tornadofx-region-error-demo>

Update: if you give a smaller version, e.g. `10000.0` to `setPrefSize`, it can work.

**Comment by bekwam** [comment]
Which Java version are you using?

I could not replicate this on Java 8u181 / Ubuntu 18.04.1 LTS.

**Comment by edvin** [comment]
Judging from the stack trace I find it unlikely that this is a TornadoFX bug. I’m thinking that you’re not doing exactly the same in your Java test. Can you post the exact Java code you use to verify?

**Comment by freewind** [comment]
My Java code is here: <https://github.com/freewind-demos/tornadofx-region-error-demo/blob/master/src/main/java/example/JavaHello.java>

```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.FlowPane;
import javafx.scene.layout.Region;
import javafx.stage.Stage;

public class JavaHello extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        FlowPane root = new FlowPane() {{
            Region region = new Region();
            region.setPrefSize(Double.MAX_VALUE, 0.0);
            getChildren().add(region);
        }};
        primaryStage.setScene(new Scene(root, 400, 200));
        primaryStage.show();
    }

}
```

It's working OK with same JDK.

And the versions:

### OS:

OSX 10.13.3

### Java

```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

### Kotlin

`1.2.60`

**Comment by freewind** [comment]
I just rewrite the Java version with Kotlin without TornadoFX, to determine if that's caused by some Kotlin issues: <https://github.com/freewind-demos/tornadofx-region-error-demo/blob/master/src/main/java/example/JavaHello.java>

```
public class JavaHello extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        FlowPane root = new FlowPane() {{
            Region region = new Region();
            region.setPrefSize(Double.MAX_VALUE, 0.0);
            getChildren().add(region);
        }};
        primaryStage.setScene(new Scene(root, 400, 200));
        primaryStage.show();
    }

}
```

But it's working OK

**Comment by bekwam** [comment]
Hi,

I tested this on the Mac and was able to replicate your error messages.  However, my app did not crash.  Once the app started, the width took up the full screen and I was able to manipulate the window by resizing, moving, and closing.

My configuration is as follows.  I ran the app both within the IntelliJ IDE and from the command line as a runnable JAR.

- Java 8u181
- OSX 10.13.2
- Kotlin 1.2.41

One style note if you continue with TornadoFX (this does not fix the error)

Use the assignment rather than the setter for properties like prefWidth and prefHeight.

````
class HelloWorld : View() {
    override val root = flowpane {
        region {
            prefWidth = Double.MAX_VALUE
            prefHeight = 0.0
        }
    }
}

**Comment by bekwam** [comment]
I think this should be closed as a bug with JavaFX as the malloc() error appears to be a problem in JavaFX as well.  

The TornadoFX code in the referenced GitHub repo and the plain JavaFX posted here aren't the same.  For example, this similar-looking TornadoFX code does not produce the error.  Notice the usage of the Scene is the same in the posted JavaFX code.

````
class HelloWorld : View() {
    override val root = flowpane {
        region {
            prefWidth = Double.MAX_VALUE
            prefHeight = 0.0
        }
    }
}

class KotlinHelloWorldApp : App(HelloWorld::class) {
    override fun createPrimaryScene(view: UIComponent) = Scene( view.root, 400.0, 400.0 )
}

fun main(args: Array<String>) {
    launch<KotlinHelloWorldApp>()
}
````

And this plain JavaFX code will produce the error

````
public class JavaHello extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        FlowPane root = new FlowPane();
        Region region = new Region();
        region.setPrefSize(Double.MAX_VALUE, 0.0);
        root.getChildren().add(region);
        root.setPrefSize(400.0, 400.0);

        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }
}

**Comment by freewind** [comment]
@bekwam You're right! Thanks for finding the real cause, it should be a problem of JavaFX. I notice the JavaCode I paste without error has defined the width and height for `Scene`:

```
new Scene(root, 400, 200)
```

Which may avoid this error.

And about the description of `crash`, I may have an inaccurate understand of it, it's not actually not "crash" on my computer too, but the huge error log scared me.

Let's close this issue and thanks!
