### ISSUE TITLE
Window icon gets wiped out after second invocation of openModal()

### ISSUE THREAD

**Issue by LittleLightCz** [edvin/tornadofx#779]
Hi there Edvin,

I probably found a little bug (not sure if in JavaFX or the TornadoFX). Having this code:

```kotlin
import javafx.application.Application
import javafx.scene.image.Image
import javafx.stage.Stage
import tornadofx.*

class PopUpView : View() {
    override val root = label("Hi")
}

class IconTestView: View() {
    private val popUpView by inject<PopUpView>()

    override val root = vbox {
        button("Open").action {
            popUpView.openModal()
        }
    }
}

class IconTest : App(IconTestView::class) {
    override fun start(stage: Stage) {
        stage.icons += Image("https://cloud.githubusercontent.com/assets/7420801/14583409/a385ee70-03e6-11e6-9790-bf7e662d35bb.png")
        super.start(stage)
    }
}

fun main(args: Array<String>) {
    Application.launch(IconTest::class.java)
}
```

1. Click on the button
2. New window opens up and the icon is there
3. Close the opened window and click the button again
4. New window pops up again, but the icon is gone

I have Windows 7, java version "1.8.0_181" and I am using tornadofx 1.7.16

**Comment by bekwam** [comment]
You'll need to set the icons for the Stage created by openModal.  This is working for me on Windows 10 / 8u181 / TornadoFX 1.7.16.

I made some small style changes for the inject, button action, and launch that aren't required for this to work.

````
class PopUpView : View() {
    override val root = label("Hi")
}

class IconTestView: View() {

    private val popUpView : PopUpView by inject()

    override val root = vbox {
        button("Open") {
            action {
                val newStage = popUpView.openModal()
                newStage!!.icons += Image("https://cloud.githubusercontent.com/assets/7420801/14583409/a385ee70-03e6-11e6-9790-bf7e662d35bb.png")
            }
        }
    }
}

class IconTest : App(IconTestView::class) {

    override fun start(stage: Stage) {
        stage.icons += Image("https://cloud.githubusercontent.com/assets/7420801/14583409/a385ee70-03e6-11e6-9790-bf7e662d35bb.png")
        super.start(stage)
    }
}

fun main(args: Array<String>) {
    launch<IconTest>(args)
}

**Comment by LittleLightCz** [comment]
Thanks @bekwam, this led me it could be also done like this (using the more general **FX.primaryStage**):
```kotlin
button("Open") {
    action {
        popUpView.openModal()?.apply {
            icons += FX.primaryStage.icons
        }
    }
}
```

I will try to make a pull request and add this logic to the openModal() and openWindow() as well.

**Comment by LittleLightCz** [comment]
Note: added just to the openModal() since I found out that this is already called by openWindow() :smile:

**Comment by edvin** [comment]
I've committed a fix for this bug now. I couldn't use your PR unfortunately, it resulted in running similar code twice in some situations.

**Comment by LittleLightCz** [comment]
@edvin whoops :grin: thanks a lot for the fix anyway! I will be looking forward for the next release, so that I can use it :-)

**Comment by edvin** [comment]
You can use it already now, the snapshot has been published to sonatype :) I'm back from vacation today and will do a release shortly as well :)
