### ISSUE TITLE
opening window with modality = Modality.NONE does not make it indepent from the caller.

### ISSUE THREAD

**Issue by jordaorodolfo** [edvin/tornadofx#780]
Hello, all!! This issue must be somewhat related to #246 and is definitively related to #769 . Suppose I have a fragment:

    class ServiceListCellFragment() : Fragment() {
        ...
        val serviceDetailView: ServiceDetailView by inject()
        ...

        fun someEvent() {
           serviceDetailView.openWindow(modality = Modality.NONE)
        }
    }

and that `ServiceDetailView` is a `View` subclass. When some event is called and the serviceDetailView is opened (or focused, since it is a singleton), its parent is somehow still related to the `View` that contains the `ServiceListCellFragment()` fragment. Corrected me if I am wrong, but I would have expected that the view, opened only at this point in the code, would have no ties to any other view, so that if I click on the `View` that "owns" the `Fragment` this second `View` would not be obfuscated behind the first one, as well as not being minimized together with the first `View`. At the moment, what happens is this secondary `ServiceDetailView` is minimzed together with the first `View` that owns the `ServiceListCellFragment`, as well as being obfuscated by it.

My TFX version is the last one: 1.7.16. Did I miss the concept altogether? If that is so, How would I go to have the secondary View independent of the first? If that is not possible, how would I most reliably emulate this independence of views, knowing that the end user wants to minimize one portion of it at will?

Thanks a lot!

**Comment by edvin** [comment]
You can pass `owner = null` as a parameter to `openWindow`. That would ensure that there is no connection between them :)

**Comment by jordaorodolfo** [comment]
Thanks a lot @edvin ! Ironically, although you answered really fast, I stumbled upon the owner parameter by accident. I consider this solved by all means, but do you think that this is a mostly sane default behavior? I do not know much of all use cases of TFX, of course, but I highly expected the "free" modality to automatically make the view free from everyone. Thanks anyway!!

**Comment by edvin** [comment]
I understand your point of view, but modality and owner are two separate elements in JavaFX and I believe it’s better to stick with the JavaFX idiocies since TornadoFX is a wrapper on top of it :)

**Comment by jordaorodolfo** [comment]
Totally! Well, at least now I know how to make it bend to my will on this matter. :) Thanks a lot!

**Comment by edvin** [comment]
You’re probably not the first who wondered about this so good to have it documented :)
