### ISSUE TITLE
TableView header columns are shifted when using remainingWidth() + smartResize() + when scrollbar appears

### ISSUE THREAD

**Issue by LittleLightCz** [edvin/tornadofx#783]
This was a bit difficult for me to reproduce, but I finally have an example code :-). When you launch this, the width of the Column A header is a bit bigger than it should be (suspiciously by the similar width which the vertical scrollbar has). When you try to scroll, or when you defocus and focus the window again, it gets fixed immediately.

```kotlin
data class Foo(val a: String, val b: String)

class TableTestView: View() {

    val trigger = SimpleBooleanProperty(false)

    val items = (1..30).map {
        Foo("Value A$it", "Value B$it")
    }.observable()

    override val root = vbox {
        prefWidth = 200.0
        prefHeight = 200.0

        trigger.onChange {
            replaceChildren {
                tableview(items) {
                    readonlyColumn("Column A", Foo::a).remainingWidth()
                    readonlyColumn("Column B", Foo::b)
                    smartResize()
                }
            }
        }
    }

    init {
        launch(JavaFx) {
            delay(1000)
            trigger.set(true)
        }
    }
}

class TableTest : App(TableTestView::class)

fun main(args: Array<String>) {
    Application.launch(TableTest::class.java)
}
```

**Comment by LittleLightCz** [comment]
Whooooh, nice, that was fast! Thanks a lot :-). I confirm the workaround works, however there is a little thing: it seems the table gets rendered "wrong" the first time and then it immediately re-renders correctly - which is noticable and a little bit disturbing for the eye. Do you think it would be possible to make it render with the correct widths on the first shot? Or is it all caused by that scrollbar which appears after the table is (over)filled by data?

**Comment by edvin** [comment]
Ah, I didn't notice that in my code. I'll investigate further!

**Comment by edvin** [comment]
This seems to be a race condition. Simply waiting when applying remedies the error. I can't find a hook or anything to listen to, because no API is exposed from JavaFX. I've reverted the "fix" i made earlier. I think you'll simply have to call `requestResize()` manually in the case where you add a new TableView later than the initial create stage. Sorry about this, but I can't see any way around it with the current TableView API. We already perform some reflection to get the contentWidth value because of missing API.

**Comment by LittleLightCz** [comment]
Ah, alright :-). I will stick with the `requestResize()` for the time being and we will see if this could be fixed in the future.

**Comment by edvin** [comment]
Thanks :) Closing the issue for now.
