### ISSUE TITLE
Integrate DI

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#79]
This is probably more a discussion piece then an issue or request. And it might get long :) so please bear with me.
Disclaimer

>  javafx and desktop development is even after 30 years still quite new to me, I usually write large scale backends.

I am writing a javafx implementation of keepass. All communication is done using the Guava EventBus. This means that When you select a group (see image) an event is sent that is picked up by the tableview and so on. It works quite nice. 
During the writing of this I stumbled on Kotlin, was interested, so now part of it is in Kotlin, part in javafx. I am using [fx-guice](https://github.com/cathive/fx-guice). I was looking at rewriting the whole ui part in kotlin, but I am looking at a decent way to implement guice into it. 

Is there going to be decent hook into DI (Guice or heaven forbid spring?)

![screenshot from 2016-04-10 21-09-01](https://cloud.githubusercontent.com/assets/595350/14412326/9638f4a4-ff60-11e5-8b0b-24090bef9669.png)

**Comment by edvin** [comment]
I took a quick look at fx-guice, and it looks like it provides injection for FXML as well. Is that what you're after, or do you just want to be able to inject beans that are bound via a guice module?

**Comment by ronsmits** [comment]
I only want to inject beans (which might be javafx views) like this:

````
@Singleton
public class Main extends GuiceApplication {
    private static final Logger LOGGER = LoggerFactory.getLogger(Main.class);
    private static final String JAVA_KEEPASS_2 = "Java Keepass 2";
    @Inject
    private KeepassRepository repository;
    @Inject
    private DetailPanel detailPanel;
    @Inject
    private KeepPassPreferences preferences;
    @Inject
    private Bus bus;
    @Inject
    private ServerStart serverStart;
    @Inject
    private TreeViewFX treeView;
    @Inject
    private TableViewFX tableFx;
    private Stage stage;

    public static void main(String[] args) {
        launch(args);
    }
````

**Comment by edvin** [comment]
OK, that makes sense to me. I'll start looking into integration with other injection frameworks and integrate with Guice first :)

**Comment by ronsmits** [comment]
I have been thinking a bit more about this. and read the guice-fx code a bit more. TBH it does a lot more then I feel needed. I would love to see a DI implementation that is less heavy then guice-fx. We only want to be able to inject beans and leave the fx specific tasks (like @FXML and by fxid) to TornadoFx. We would also need some halfway decent examples. A naive attempt using guice-fx and tornado did not work the way I expected it:

````
class TestView : View() {
   lateinit var bus : Bus
      inject get
...

````

Will throw the lateinit not initialized exception

**Comment by edvin** [comment]
Yeah, I think we should leave guice-fx out of it and support guice directly. As you say, there is some cross cutting concerns with guice-fx and TornadoFX, and I can't really see why someone would use them both together.

I was thinking we could adapt the `inject` delegate to look for beans in any configured DI container before reverting to the default DI container built into TornadoFX. That would mean changing the contract a bit, so that `inject` accepts `Any` instead of `Injectable`. That's really not a problem, because it could shortcut and say that any `Injectable` (View and Controller basically) will always be fetched from the internal DI container, and other bean types would be looked up in any configured DI container. What do you think?

**Comment by ronsmits** [comment]
During the startup of the application somehow the DI container (guice, pico, spring) needs to be initialized and started. This has to be done in a such way that apart from the starting up, the DI implementation should be completely hidden.
We should also think about how to bootstrap this without adding all frameworks to tornadofx. Maybe we will have a tornadofx-guice, tornadofx-spring submodule?

**Comment by edvin** [comment]
Yes absolutely. It should be possible to do this with optional dependencies if we're a bit careful. I'm testing a theory right now, hang on!

**Comment by edvin** [comment]
OK, I committed initial support for Guice. Example:

```kotlin
interface HelloService {
    fun hello(name: String): String
}

open class HelloServiceImpl : HelloService {
    override fun hello(name: String) = "Hello there, $name"
}

class MyModule : AbstractModule() {
    override fun configure() {
        bind(app.HelloService::class.java).to(HelloServiceImpl::class.java)
    }
}
```
> A Guice service interface, implementation and module that binds them together

In your `App` class, initialize the Guice injector:

```kotlin
init {
    FX.guiceInjectors += Guice.createInjector(MyModule())
 }
```

Inject `HelloService` in a `View` or a `Controller`:

```kotlin
val helloService: HelloService by inject()
```

Does this look like what you need? If so, try it out and let me know!

**Comment by ronsmits** [comment]
I will check it tonight. First reaction though is the very tight coupling of guice and tornadofx.

**Comment by edvin** [comment]
Good :) TornadoFX does not require Guice, but if it's on the classpath, it can integrate with it. It would be impossible to integrate the two libraries without one of them having knowledge of the other. Creating a separate module for the integration would not change this really, and TornadoFX does not become heavier because it supports Guice, so I'm not sure I share your concern :) There's about 3 lines of Guice specific code in there :)

**Comment by edvin** [comment]
I removed my last comment :) Yes, there is definitely coupling there, and we could remove this by creating a separat module for the integration. After thinking about it, I do agree that this would be a better approach. Let me see if I can reduce the coupling and introduce a tornadofx-guice module.

**Comment by edvin** [comment]
The coupling is gone, we now support any injection mechanism that can be expressed via the Injector interface. The code to do so is extremely light though, so I'm not sure it warrants a separate module, but I guess it would make it a bit more accessible. What do you think?

**Comment by edvin** [comment]
I feel that the Injector interface name might not be the best. Any suggestions for a better one?

**Comment by ronsmits** [comment]
ROFL you are going so fast :+1: Injector is indeed a name that resembles guice. How about dicontainer? or something like that?

**Comment by edvin** [comment]
Hehe :) Ah, I played with the name dicontainer actually :) Allright, I will change it and update the example above.

**Comment by ronsmits** [comment]
Right.......

I made a small repo with a spring example it in. There are two branches there, master and "with-service".
the master branch works but! the injected view gets initialised twice. the branch "with-service" has a service interface with an implementation and it when running it, it gives the weirdest error:
````
/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java -Didea.launcher.port=7534 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 15.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/tools.jar:/Users/ronsmits/src/fx-spring/target/classes:/Users/ronsmits/.m2/repository/no/tornado/tornadofx/1.4.2-SNAPSHOT/tornadofx-1.4.2-SNAPSHOT.jar:/Users/ronsmits/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar:/Users/ronsmits/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.0.1-2/kotlin-stdlib-1.0.1-2.jar:/Users/ronsmits/.m2/repository/org/jetbrains/kotlin/kotlin-runtime/1.0.1-2/kotlin-runtime-1.0.1-2.jar:/Users/ronsmits/.m2/repository/org/springframework/spring-core/4.1.6.RELEASE/spring-core-4.1.6.RELEASE.jar:/Users/ronsmits/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/ronsmits/.m2/repository/org/springframework/spring-context/4.0.5.RELEASE/spring-context-4.0.5.RELEASE.jar:/Users/ronsmits/.m2/repository/org/springframework/spring-aop/4.0.5.RELEASE/spring-aop-4.0.5.RELEASE.jar:/Users/ronsmits/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/ronsmits/.m2/repository/org/springframework/spring-beans/4.0.5.RELEASE/spring-beans-4.0.5.RELEASE.jar:/Users/ronsmits/.m2/repository/org/springframework/spring-expression/4.0.5.RELEASE/spring-expression-4.0.5.RELEASE.jar:/Applications/IntelliJ IDEA 15.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain spring.Main
Apr 11, 2016 7:26:35 PM org.springframework.context.support.ClassPathXmlApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@6a6bd888: startup date [Mon Apr 11 19:26:35 CEST 2016]; root of context hierarchy
Apr 11, 2016 7:26:35 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [spring.xml]
starting centerview
Exception in Application init method
Exception in thread "main" java.lang.NoSuchMethodException: spring.Main.main([Ljava.lang.String;)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:125)
````

The repo is at https://github.com/ronsmits/fx-spring

**Comment by edvin** [comment]
The reason for this is that you have configured Spring to instantiate all the classes in the "spring" package, where you have your centerview as well as the hello-service. So, Spring instantiates centerview once (preemptively even) when the context starts, and then TornadoFX instantiates it again when it's injected.

The way I constructed the injection means that TornadoFX must construct all the Views and Controllers, and Spring can inject everything else.

Putting the Spring-stuff in another package would solve the problem.

I'm unsure if it would add any value to let Spring instantate all TornadoFX resources as well, but at the same time I can see how it is confusing having two injection frameworks at place simultaneously. What Spring does now is to preemptively create all views, which would be performance murder in a large application.

What are your thoughts?

**Comment by ronsmits** [comment]
Putting the spring service in another package solves it indeed as expected. The branch is updated to reflect that. However in several architectures (like DDD for example) where all classes related to a certain context are stored in a single package this will happen often I guess. TBH I just set it up as I often do. Packaging based on context instead of technical layering is becoming a kind of standard.

I understand the view that TornadoFX does the instantiation of Views and Controllers. How about we change the nomenclature here?

- **by fx** instantiated by TornadoFX
- **by di** instantiated by Spring or Guice

Naming is of course the important thing here, communicating what does what and when. The fx (or whatever name we come up with) is solely responsible for javafx specific injection. di (or cdi) is responsible for services, repositories and the like.

People like me :) are completely used of having everything injected when working in a EE or CDI environment. Especially when the injected functionality needs to have classes injected too. Especially when working  with business services or aggregate services this is quite common. Its what I do with the keepassJava program too. I inject a view (like DetailPanel or GroupListPanel) to make certain that the bus is injected and if needed the repository. TornadoFX and by extension the power of Kotlin make this different, not having a @Inject looks weird :). Well just some ramblings.

**Comment by ronsmits** [comment]
Also thinking about this, I actually wonder if I would use Spring in a desktop environment. It's quite heavy, it brings in 7 extra dependencies
![diagram](https://cloud.githubusercontent.com/assets/595350/14440261/6383d568-002f-11e6-8b7f-5b959d012ff2.png)

**Comment by edvin** [comment]
Yeah, there are some pitfalls here for sure. If you want to use this with a DDD or similar structure, I think the best option would be to enumerate your beans in the config instead of using component scanning. It's a bit more verbose, but it's faster and removes any doubt about where your beans are coming from.

Regarding *di* vs *fx* - the problem isn't knowing where the bean is available, I already check for this in the `inject` delegate.

It would of course be possible to have the di container introspect the TornadoFX views/controllers and support their native `@Inject` annotation, but the `inject` delegate does a pretty good job of this already with a less verbose syntax (because you have to use the *lateinit var* construct if you combine it with `@Inject`).

I guess the real question here is "What is it that TornadoFX injection doesn

**Comment by ronsmits** [comment]
This is my EE side speaking I think. I often use CDI to make different test scenarios. Where an interface will have a different implementation in a test scenario then in production. I will do some testing to see if the tornadofx injection will fullfill all my needs and then we come back to this?

**Comment by edvin** [comment]
Ah, that will be very helpful. Maybe we can make the TornadoFX more powerful, support qualifier parameters etc :)

I do think that the external di support could come in handy for people that are migrating existing apps, so we might leave it in anyways.

**Comment by ronsmits** [comment]
I dont think we should support qualifiers in TornadoFX. The current injection for Views and Controllers is working very well. I will do some tests to see if non Views and Controllers can get injected as well.

I was thinking about changing inject a tiny bit enforcing that the internal inject only injects "Injectables" and leaves all others to the external di.

**Comment by edvin** [comment]
OK. What is gained by not letting inject work for beans from the di container?

**Comment by ronsmits** [comment]
single responsibility. First of (and these are just my thoughts) TornadoFX is wonderfully light and fast. All the stuff that has been added up to now is geared towards making javafx as easy and fun to work with. So let tornadoFX handle that, the inject delegate is excellent in that.

CDI beans, services are used by a javafx application but are not part of TornadoFX. The solution you made with the DIContainer and findExternal works quite well. So let TornadoFX do its javafx thing and let CDI (Spring, pico, guice) do the other thing.

**Comment by edvin** [comment]
I agree :) Reverting inject to the way it was also makes sure you only use it with TornadoFX injectables. I will add a di delegate tonight and update the docs :) Thank you for the valuable input!

**Comment by ronsmits** [comment]
Excellent. And dont thank me, we should all thank you for the excellent work you do.

**Comment by edvin** [comment]
I'm grateful for everything you and all the others are contributing and that so many people have invested their time and effort into TornadoFX :)

I made the changes in the last commit, `inject` now only supports `Injectable`s, and `di` will only look up beans from the `dicontainer`. Let me know how this works for you!

**Comment by ronsmits** [comment]
Tested it out using both the inject and di delegates and they work fine. Closing the ticket.

**Comment by edvin** [comment]
Perfect! I'll update the documentation.
