### ISSUE TITLE
orientation parameter in field builder seem to do nothing

### ISSUE THREAD

**Issue by ngppgn** [edvin/tornadofx#790]
I'm new to both Kotlin, tornadofx and reporting issues on github, so please forgive me if I conduct myself inappropriately.

I'm creating a simple test tornadofx app and I'm facing this problem:

When field("some text") will create a field container with the "some text" label to the left of the widget. The Guide says you can pass an optional VERTICAL argument to make the label appear on top of the widget itself. 

However, using IntelliJ IDEA, field("label", orientation=Orientation.VERTICAL){ /*some widgets here*/ } produces the same layout as simply doing field("label"L){ /*some widgets here*/ }.

Any idea of what might be going on here and how can I fix/work around the issue on my end?

**Comment by edvin** [comment]
The `orientation` parameter to `field()` specifies how multiple input elements will be laid out inside of the input container. The `labelPosition` parameter to the `fieldset()` builder however, specifies the placement of the label :)

**Comment by ngppgn** [comment]
Many thanks!

**Comment by edvin** [comment]
You're welcome :)
