### ISSUE TITLE
NPE when saving null to config object.

### ISSUE THREAD

**Issue by bj0** [edvin/tornadofx#792]
When I try to set a config key to `null`, it throws a `NullPointerException`:

    val host: String? = null
    set("host" to null)

Are null values not allowed?  The signature of `set` includes `Any?` which suggests `null` is allowed.  Someone mentioned in another issue that `null` is no longer allowed, but I don't see anything about it in the guide.

**Comment by edvin** [comment]
Thanks for reporting. Actually, the underlying store is a `java.util.Properties` object, which won't allow null values, so I changed the signature of the `set` function to not allow null anymore, as it could never succeed anyway. I will update the guide as well.

**Comment by bj0** [comment]
Thanks, since this is the case, is there a way to remove a setting from config?

**Comment by edvin** [comment]
Yes, `remove(key)` is the way to remove a key from any `Map` :) If you want to be fancy about it you could also do `config -= "key"`.
