### ISSUE TITLE
CellFactory updateItem unavailable

### ISSUE THREAD

**Issue by Y2Kot** [edvin/tornadofx#795]
My case is to make cell color be changed by right mouse click.
I'm trying to write this code in Kotlin + tornadofx. however in setCellFactory there is nothing simillar. How can I correctly rewrite this code?
```
public void initialize() {
        userIdColumn.setCellFactory(tc -> {
            TableCell<User, String> cell = new TableCell<User, String>() {
                @Override
                protected void updateItem(String item, boolean empty) {
                    super.updateItem(item, empty) ;
                    setText(empty ? null : item);
                }
            };
            cell.setOnMouseClicked(e -> {
                if (! cell.isEmpty()) {
                    String userId = cell.getItem();
                }
            };
        });
    }
```

**Comment by edvin** [comment]
TornadoFX is just an API on top of JavaFX - it never hides the underlying API, so you can write exactly that same code, just with Kotlin syntax.

**Comment by Y2Kot** [comment]
I tried however it's doesn't work. Is there any method to set custom cell factory?
My code:
```
class CustomCell: TableCell<SellDepartmentTask, String>(), Callback<TableColumn<SellDepartmentTask, String>, TableCell<SellDepartmentTask, String>> {
    override fun call(param: TableColumn<SellDepartmentTask, String>?): TableCell<SellDepartmentTask, String> {
        println("check")
        return CustomCell()
    }

    override fun updateSelected(selected: Boolean) {
        super.updateSelected(selected)
        if (item == "qwe") {
            textFill = Color.CHOCOLATE
            style = "-fx-background-color: yellow"
        }
        setOnMouseClicked {
            if (it == MouseButton.SECONDARY) {
                style = "-fx-background-color: darkred"
            }
        }
        style = "-fx-background-color: yellow;"

    }
    override fun updateItem(item: String?, empty: Boolean) {
        super.updateItem(item, empty)
        if (item == "qwe") {
            textFill = Color.CHOCOLATE
            style = "-fx-background-color: yellow"
        }
        setOnMouseClicked {
            if (it == MouseButton.SECONDARY) {
                style = "-fx-background-color: darkred"
            }
        }
        style = "-fx-background-color: yellow;"
    }
}
```
And I tried to call it by:```

setCellFactory {
                CustomCell()
            }
            //or
            cellFactory = CustomCell()
```

**Comment by FTOH** [comment]
like this?
```kotlin
class SomeView : View("Test") {
    val data = listOf("qwe", "fds", "gfa", "dgc").map { SellDepartmentTask(it) }.observable()

    override val root = tableview(data) {
        selectionModel.isCellSelectionEnabled = true
        repeat(10) { _ ->
            column("Test", SellDepartmentTask::name).setCellFactory { CustomCell() }
        }
    }
}

class CustomCell : TableCell<SellDepartmentTask, String>() {

    override fun updateSelected(selected: Boolean) {
        super.updateSelected(selected)
        textFill = if (item == "qwe") Color.CHOCOLATE else Color.BLACK
    }

    override fun updateItem(item: String?, empty: Boolean) {
        super.updateItem(item, empty)
        text = item
        if (item == "qwe") {
            textFill = Color.CHOCOLATE
        }
        background = Color.YELLOW.asBackground()

        setOnMouseClicked {
            if (it.button == MouseButton.SECONDARY && !empty) {
                background = Color.RED.asBackground()
            }
        }
    }
}
```

**Comment by edvin** [comment]
The idiomatic TornadoFX approach to this would be to use a CellFragment though :)

**Comment by Y2Kot** [comment]
code above doesn't work =C

**Comment by Y2Kot** [comment]
I never thought that coloring cells will be so difficult to me =C I'm trying to color full row(I thought that it will be a bit easier). Can I do this with CellFragment?

**Comment by edvin** [comment]
Yeah, that's a little involved in JavaFX unfortunately. I think you should create a row factory instead and set the color based on the item state. I don't have an example for you right now, but you'll be able to find JavaFX based examples for this.

**Comment by Y2Kot** [comment]
Yes, I'm trying to use rowFactory for now by rewriting this code - https://stackoverflow.com/questions/44819807/how-to-change-tableview-row-color-when-some-conditions-are-valid-javafx . How ever it doesn't work for me too =C For now I'm trying to simplify my code and trying to make it change by button click:
```
testButton.setOnAction {
            testTableView.setRowFactory { _ ->
                val row = TableRow<SellDepartmentTask>()
                row.background = Color.ALICEBLUE.asBackground()
                row
            }
        }
```

**Comment by bekwam** [comment]
Don't forget about CSS when styling TableViews.  This post shows how different styles are applied to add/even rows and to selected rows.

https://courses.bekwam.net/~walkerro/bkcourse_tornadofx_style_tableview.html

This post has a .kt file referenced at the bottom with a more advanced application of TableView styling.

**Comment by edvin** [comment]
Perfect, @bekwam !

**Comment by edvin** [comment]
Just for completeness, here is an extremely dirty way to set make clicked rows green:

```kotlin
                setRowFactory { _ ->
                    object : TableRow<YourItem>() {
                        init {
                            setOnMouseClicked {
                                style {
                                    backgroundColor += Color.GREEN
                                }
                            }
                        }
                    }
                }
```

**Comment by bekwam** [comment]
Here's another snippet with an alternate syntax from Edvin's example that sets a background at the end of the updateItem().  After you get something going, you'll want to replace the setter calls with Type Safe CSS.

        tableview(c.data) {

            column("Date", Commit::commitDateProperty) {
                converter(LocalDateTimeStringConverter())
            }
            column("Committer", Commit::committerProperty)
            column("Log", Commit::logEntryProperty)

            rowFactory = Callback {
                val tr = object : TableRow<Commit>() {
                    override fun updateItem(item: Commit?, empty: Boolean) {
                        super.updateItem(item, empty)
                        // set your logic and style-mapping here
                        background = Color.YELLOW.asBackground()
                    }
                }
                tr
            }

            vgrow = Priority.ALWAYS
        }

**Comment by Y2Kot** [comment]
Thanks for help. I got some problems with coloring text in the row. But I found solution (if anyone will need it):
```
class MyStyles: Stylesheet() {
    companion object { val notIdentified by csspseudoclass() }

    init {
        notIdentified {
            cell {
                textFill = Color.BLACK
            }
        }
    }
}
```
Great thanks for helping!
