### ISSUE TITLE
tab reordering

### ISSUE THREAD

**Issue by tsbonev** [edvin/tornadofx#800]
Is there an easy way to make tabs reorderable via dragging and dropping?

**Comment by edvin** [comment]
There is no built in functionality for this, but it seems many have done it in JavaFX:

https://stackoverflow.com/questions/41473987/how-to-drag-and-drop-tabs-of-the-same-tabpane

If you write som Kotlin code do to this for TornadoFX, feel free to post it here. Maybe we can generalize and include it as a function in the framework?

**Comment by tsbonev** [comment]
I'll see what I can do.

**Comment by tsbonev** [comment]
Seems like it would be a pain to implement, would be easier if the tabs in the tabpane were Nodes instead of just event targets.

**Comment by edvin** [comment]
Nothing we can do about that in TornadoFX, since we're basically an API on top of JavaFX :)
