### ISSUE TITLE
rowExpander breaks with themes

### ISSUE THREAD

**Issue by MicleBrick** [edvin/tornadofx#803]
I wanted to make a new private use tool I was making visual rather than console base, so I thought I'd give desktop applications a try. TornadoFX seemed like the best option for Kotlin so I went with that. It's been nice so far. One issue I'm having is that the row expander thing seems to break with things like JMetro and other themes.

**Comment by edvin** [comment]
Can you create a minimal sample app that fails, and describe how it fails? If not it's going to be hard to debug.

**Comment by Miclebrick** [comment]
I can try making one that just uses the example code from the site as that originally broke as well

**Comment by Miclebrick** [comment]
@edvin https://github.com/Miclebrick/ExpanderBug/tree/master

**Comment by Miclebrick** [comment]
Before click:
![image](https://user-images.githubusercontent.com/6323125/45767810-2ff34600-bc09-11e8-8343-9f37893eee38.png)
After click:
![image](https://user-images.githubusercontent.com/6323125/45767818-38e41780-bc09-11e8-9bf0-d54975be69fe.png)
The name and country of the row disappears, and the contract button doesn't work properly

It gets even better if you fool with it a bit...
![image](https://user-images.githubusercontent.com/6323125/45767871-5b763080-bc09-11e8-9e80-4c664ae295e4.png)

**Comment by ctadlock** [comment]
How is this a tornadofx issue?
