### ISSUE TITLE
JavaFX moving at near the speed of JDK

### ISSUE THREAD

**Issue by nwillc** [edvin/tornadofx#804]
According to https://openjfx.io they've got the decoupled JavaFX 11  built on Java 11 generally available. 

Maybe this is a good next goal target?   I've fully shaken out Kotlin passed JDK 1.8 so I'm not personally sure it Java 11 adds further hurdles just around Kotlin let alone JavaFX.

**Comment by edvin** [comment]
We are working on it in a separate branch :)

**Comment by claudiug** [comment]
@edvin hello, sorry to out of the blue, there is any roadmap for this?

**Comment by edvin** [comment]
No there is not, but the work is mostly done. Testing is the most important factor now, and I'm very pressed for time myself. If you can, check out the jdk10 branch and test it against your projects and report back :)
