### ISSUE TITLE
ConfigProperties.string has wrong (inferred) return type.

### ISSUE THREAD

**Issue by bj0** [edvin/tornadofx#805]
The function is:

    fun string(key: String, defaultValue: String? = null) = getProperty(key, defaultValue)

So it can obviously return a null value, but the Kotlin compiler infers its type as `String!`, probably because it doesn't understand the java function `getProperty`.  It should probably be explicitly marked as `String?` for null safety.

**Comment by edvin** [comment]
To avoid irritation when you actually supply a non-null String value I propose to add an overload:

```kotlin
fun string(key: String, defaultValue: String): String = getProperty(key, defaultValue)
fun string(key: String): String? = getProperty(key)
```

What do you think?

**Comment by bj0** [comment]
That would be fine.  In my case I am checking for a key which may not be present, so I am doing a null check and the linter is complaining about me null checking a non-nullable return type (that I know is nullable).

**Comment by ruckustboom** [comment]
Should this be applied to the other functions as well? `boolean`, `double`, and `int` all take nullable defaults.
