### ISSUE TITLE
TableView builder from Map<String, String?> (or better Map<T, K> for general use)

### ISSUE THREAD

**Issue by LittleLightCz** [edvin/tornadofx#807]
Currently I have a need to dynamically re-render `tableview {}` according to `List<Map<String, String?>>` where each Map actually  corresponds to a ResultSet fetched from the DB. This means I also want my table to dynamically change column count/names. I was able to mimic this behaviour using `dynamicContent {}` and `cellFormat {}` (you wouldn't like to see that hack), but only for a single row :laughing:. Is there any simple way how to achieve it for multiple rows right now or would it need some new builder?

Thanks in advance!

**Comment by edvin** [comment]
You'd probably have to remove the old columns and call the `column()` builder to create new columns. It should be pretty straight forward if you have the data type information and column names. If you change the records as well you might be better of with just creating a new tableview and swapping out the old though.

**Comment by AntoninBrettsnajdrONSEMI** [comment]
Hmh, you're right, it seems I finally made it work like this:

```kotlin
import javafx.application.Application
import javafx.beans.property.SimpleStringProperty
import javafx.scene.control.TableColumn
import tornadofx.*

typealias Row = Map<String, String>

class TestView : View() {

    private val rows = listOf(
            mapOf("A" to "a1", "B" to "b1"),
            mapOf("A" to "a2", "B" to "b2")
    ).observable()

    override val root = vbox {
        prefWidth = 400.0
        prefHeight = 400.0

        tableview(rows) {
            rows.first().keys.forEach { columnName ->
                column(columnName) { cell: TableColumn.CellDataFeatures<Row, String> ->
                    SimpleStringProperty(cell.value[columnName])
                }
            }
        }
    }

}

class TestApp : App(TestView::class) {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            Application.launch(TestApp::class.java)
        }
    }
}
```

**Comment by edvin** [comment]
You don't need to create the cellValueFactory yourself, but unfortunately you'd then have to specify the column type, which really sucks in your case since your values are of type `Map<String, String>` , but it's still a better solution:

```kotlin
class TestView : View() {

    private val rows = listOf(
            mapOf("A" to "a1", "B" to "b1"),
            mapOf("A" to "a2", "B" to "b2")
    ).observable()

    override val root = tableview(rows) {
        setPrefSize(400.0, 400.0)
        rows.first().keys.forEach { columnName ->
            column<Map<String, String>, String>(columnName) { 
                SimpleStringProperty(it.value[columnName]) 
            }
        }
    }

}

class TestApp : App(TestView::class)

fun main(args: Array<String>) {
    launch<TestApp>(args)
}
```

**Comment by LittleLightCz** [comment]
Thanks a lot, that looks better :-). Yeah, that's why I created a `typealias Row = Map<String, String>` for that so it looks a bit better, however I am afraid I have no other choice than to use Map here, since I am dealing with ResultSet from the DB and multiple different tables, so it's quite a lot "dynamic" in this particular case. Also thanks for the `setPrefSize`, from now on I will start using that :grin:

**Comment by edvin** [comment]
Sweet :) You might be able to clean it up with a custom class, but I guess there isn't much to gain :) Great work, by the way!

**Comment by ctadlock** [comment]
Answered, closing.
