### ISSUE TITLE
enableWhen does not work with workspace buttons when called from init

### ISSUE THREAD

**Issue by adam-arold** [edvin/tornadofx#808]
I'm trying to configure when the workspace buttons are enabled with this:

```
class MyView : View(TITLE) {

    init {
        workspace.deleteButton.enableWhen(selectedFlow.itemProperty.isNotNull)
    }
}
```

My problem is that this does not change the state of the `deleteButton` at all. I have another button on my UI with which the exact same function works:

```
button(DELETE) {
    enableWhen(selectedFlow.itemProperty.isNotNull)
}
```

Moving this to `onDocked` works but it should be documented that I can't do this in `init`.

There is another problem with workspace buttons: `workspace.saveButton.removeFromParent()` does not work with any of the buttons even in `onDocked`. It is implied somewhere in the docs that I should be able to do this but the only thing which works is setting the disabled state.

**Comment by edvin** [comment]
I have added a clarification to the guide about the timing of when you can modify the workspace buttons, but that said - you can not and should not try to modify the disabled/enabled state of workspace buttons, as they are managed by the workspace. Instead you should expose the corresponding built in property of the view, and the button state will be automatically updated. For example, to configure the `deleteButton` to depend on the `selectedFlow.itemProperty` of your view, simply override the `deletable` property of the view, and it will be automatically bound to the delete button:

```kotlin
override val deletable = selectedFLow.itemProperty.isNotNull
```
This is explained in the guide, along with the sibling properties `refreshable`, `savable` and `creatable`.

I have confirmed the issue with `removeFromParent`. Long story short: Use `workspace.deleteButton.hide()` instead - I'll update the guide.

**Comment by adam-arold** [comment]
Thanks! I guess I just skimmed the docs and missed the part about `deletable` but I do recall the part where `removeFromParent` was mentioned. I'll use `hide` then, thanks!
