### ISSUE TITLE
Guide is not accessible.

### ISSUE THREAD

**Issue by smaudet** [edvin/tornadofx#809]
Cannot view guide - requires an account, but the guide is legacy only, signing up for a new account does not log you into the old system and you cannot sign up for the old system anymore.

**Comment by thomasnield** [comment]
Can you not access it here? 
https://edvin.gitbooks.io/tornadofx-guide/content/

**Comment by edvin** [comment]
Thanks Thomas! I just confirmed that it's available without login. Closing :)

**Comment by smaudet** [comment]
https://www.gitbook.com/book/edvin/tornadofx-guide/details
^ this is the site guide

https://edvin.gitbooks.io/tornadofx-guide/content/

Is indeed available. Where would I go to file a bug about the site?

**Comment by smaudet** [comment]
https://github.com/edvin/tornadofx/issues/818

**Comment by edvin** [comment]
I just confirmed, it's working good on both the above links. What exactly do you see when you click the first link?
