### ISSUE TITLE
subList of SortedFilteredList is end inclusive, but should be end exclusive

### ISSUE THREAD

**Issue by lweckeck** [edvin/tornadofx#811]
According to Kotlin documentation subList should be end-exclusive [1], but the current implementation is end-inclusive.

[1] https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-list/sub-list.html

https://github.com/edvin/tornadofx/blob/0477e1876647b183c3f2e1cdce9489f227b27b78/src/main/java/tornadofx/Lib.kt#L97

**Comment by edvin** [comment]
Nicely spotted. Do you want to make a PR?
