### ISSUE TITLE
Q: Any plan to support JDK 11?

### ISSUE THREAD

**Issue by bakkiaraj** [edvin/tornadofx#817]
As oracle's announcement, JavaFX moves away from standard JDK.

JavaFX for Java 11 - https://gluonhq.com/products/javafx/ 

JDK 11 from https://adoptopenjdk.net/ 

Works fine. I mean, sample javafx app is working fine. I could not try tornodofx yet.

Is there any plan to support JDK11 / java 11? IMHO, Java 9 & Java 10 can be skipped due to the fact that Java 11 is going to be LTS.

**Comment by edvin** [comment]
Yes, we are working on the port in a separate branch. This will become then main branch when complete :)

**Comment by bakkiaraj** [comment]
Thanks Edwin :)

**Comment by travisfw** [comment]
> Yes, we are working on the port in a separate branch. This will become the main branch when complete :)

What branch? [jdk10](https://github.com/edvin/tornadofx/tree/jdk10)?

**Comment by edvin** [comment]
Correct. 2.0.0-SNAPSHOT from this branch is available in the sonatype snapshot repo as well :)

**Comment by claudiug** [comment]
hello @edvin Any new news for this issue? :)

**Comment by edvin** [comment]
No sorry, I have no time to work on this at the moment. I was hoping more people from the community would help test and give feedback though :)
