### ISSUE TITLE
Guide is not accessible from tornadofx.io

### ISSUE THREAD

**Issue by smaudet** [edvin/tornadofx#818]
https://www.gitbook.com/book/edvin/tornadofx-guide/details
^ this is the site guide link from: https://tornadofx.io/

https://edvin.gitbooks.io/tornadofx-guide/content/
Is the working link. This should be updated, when I attempt to use the gitbook.com link it starts asking me to login/create an account and never resolves to the above link (or if it does it is not accessible or obvious).

If this is not the correct place to log an issue, the issue tracker for the website is also wrong/incomplete, perhaps, and a separate issue should be filed for that in addition to fixing this link on the website.

References https://github.com/edvin/tornadofx/issues/809

**Comment by edvin** [comment]
Both links are working. Just click the READ button to read the guide :)

**Comment by smaudet** [comment]
@edvin Can you just update the link to the correct one? Otherwise you get into a loop where you try to sign up, can't get redirected to the new site, signup/login, still can't get to the old site.

**Comment by smaudet** [comment]
![image](https://user-images.githubusercontent.com/990607/47016693-719ae200-d11e-11e8-9d74-8a58f3651645.png)

**Comment by smaudet** [comment]
If you want me to open another ticket along the lines of "Your Doco UX is horrible, you seriously need to stop being lazy and update that link", I will.

:)

**Comment by edvin** [comment]
No thank you, I just committed the new URL :) Will redeploy the site now.

**Comment by edvin** [comment]
There :)
