### ISSUE TITLE
BooleanProperty enhancement using invoke() operator overload

### ISSUE THREAD

**Issue by LittleLightCz** [edvin/tornadofx#819]
Hi Edvin,

Would you consider adding the following extension function to TornadoFX?

```kotlin
import javafx.beans.property.BooleanProperty

inline operator fun BooleanProperty.invoke(block: () -> Unit) {
    set(true)
    try {
        block()
    } finally {
        set(false)
    }
}
```

There is a re-occuring pattern for loading type of actions where I want to set some BooleanProperty to `true` to indicate to other UI elements that some action is happening and then I want to make sure that even in case that the action fails, it is set back to `false`.

The above enables me to reduce that boilerplate code just to:
```kotlin
private val loading = SimpleBooleanProperty(false)

loading {
    //some code here
}
```

**Comment by edvin** [comment]
I can see that this function is handy for you, but it's not intuitive or easy to understand what it does. I could accept a function that does this on a BooleanProperty or a Property<Boolean>, but not on `invoke` directly. A better named function would make it much clearer what's going on and still give you the benefit of reusability. For example `loading.trueWhile { .. }` or something that makes it clear that it will also be set to false once the function has run perhaps?

**Comment by ruckustboom** [comment]
I agree a different name would be better, but even with that I don't really think it belongs in TornadoFX. While I can see the benefit of it, it doesn't really seem idiomatic to me from a JavaFX standpoint, and probably shouldn't be encouraged through official support. Especially since it doesn't actually provide any protection against other code changing the property. That's why both JavaFX tasks and coroutine jobs were designed with their own states. It might be worth looking into making some helper functions to create readonly properties against `Job`'s states.

**Comment by bekwam** [comment]
I think the async function or coroutines should be considered too.  If invoke() is a fast operation, then the loading flag goes from true to false in a nanosecond.  If not, then you need something async.  If that's the case -- whether JavaFX Task or coroutines -- you'll want more than just a boolean flag. You'll want properties set for progress, label, and title.

**Comment by LittleLightCz** [comment]
I agree that maybe it doesn't fully belong to the TornadoFX, but I tried to discuss it :relaxed:. It's a very specific and also very simple use case. Regarding anything else - as the progress, labels, etc. were mentioned - this I always handle manually. I was really thinking only in the scope of a very simplified true/false switch just for the `BooleanProperty`.

**Comment by ruckustboom** [comment]
Such discussions are always good. In addition to helping everyone agree on what the proper scope of TornadoFX is, I find they also often lead to either learning much better ways to do things, or finding subtler ways TornadoFX can be improved to benefit everyone. If I'm not mistaken, Scopes came out of just such a discussion.

**Comment by edvin** [comment]
Great :) Even though we won't be adding this, others can benefit from your code if they choose to. It's important to point out that the pattern is only good if you use coroutines though, as doing any kind of long running work inside the try/catch block would be bad, and the change to the property wouldn't be reflected in the UI.
