### ISSUE TITLE
openModal - onDock not being called

### ISSUE THREAD

**Issue by gtnarg** [edvin/tornadofx#820]
I have run into some odd behaviour (which I believe is a JavaFx bug).

From a TornadoFx standpoint I am trying to open a Wizard in a modal window and onDock is not being called.  Digging into the source and debugging, the onDock call is dependent on a ChangeListener on the stage.showingProperty.

I am unable (as of yet) create an SSCCE to demonstrate the behaviour but can consistently reproduce it (and the associated fix) in my application.

The following stackoverflow question demonstates almost the same behaviour ( https://stackoverflow.com/q/50280052/4931921 ).

Basically, when opening a stage, a listener for the showingProperty is not being called unless another listener (InvalidationListener or ChangeListener) is also added to the same stage.

The following change in Component.openModal is ultimately what I'm trying to achieve:

```
        // existing ChangeListener
	showingProperty().onChange { ... }

	// noop ChangeListener
	showingProperty().onChange{} //noop
	
	if (block) showAndWait() else show()
```
	
	
Would it be possible to make a reference to the modalStage available through a callback prior to it being shown as I need to add a noop invalidation listener to get onDock to be called.

Right now, my only other option is to reimplement openModal functionality myself.
	
	
Regards,
Grant

**Comment by gtnarg** [comment]
After discussing with @carlw refactoring the existing showingProperty.onChange{...} logic into the following works:

```
	setOnShown {                  
		if (owner != null) {
			x = owner.x + (owner.width / 2) - (scene.width / 2)
			y = owner.y + (owner.height / 2) - (scene.height / 2)
	       }
	      callOnDock()
	      if (FX.reloadStylesheetsOnFocus || FX.reloadViewsOnFocus) {
		  configureReloading()
	      }
         }

         setOnHidden {             
		modalStage = null
		callOnUndock()
          }
```

If this approach is acceptable - I will submit a PR.

**Comment by edvin** [comment]
Sounds good :))

**Comment by edvin** [comment]
PR merged
