### ISSUE TITLE
make openWindow() NodeOrientation the same as workspace

### ISSUE THREAD

**Issue by mostfa-ayad** [edvin/tornadofx#821]
hello 
when my app start i set the workspace NodeOrientation  and it make good over the app
when i open a new window using this
find<DailyMoveEditor>(editScope).openWindow()
the new window  NodeOrientation work with the default
 is it possible to make it inherit the workspace NodeOrientation

**Comment by edvin** [comment]
NodeOrientation is not a setting for Workspace. Exactly what setting are you configuring? :)

**Comment by mostfa-ayad** [comment]
`

import javafx.geometry.NodeOrientation
import tornadofx.*

class MyWorkspace : Workspace("My View",navigationMode = NavigationMode.Tabs) {

    init {
        add(MainMenu::class)
        root.nodeOrientationProperty().set(NodeOrientation.RIGHT_TO_LEFT)
        root.useMaxSize

    }
}
`

**Comment by mostfa-ayad** [comment]
i using this to get the nodeOrientation from the workspace and using it in the new window

`        this.nodeOrientation=workspace.root.nodeOrientation`

**Comment by edvin** [comment]
That's what you have to do I believe, there is no special support for carrying the node orientation over, but it could be implemented fairly easily. Submit a PR if you find a nice way to incorporate it?

**Comment by mostfa-ayad** [comment]
it is what i can do with it and it work nice for me 
but i think it will be nice if in the new window init  it take the orientation from where it calling automatically
thanks for interesting
