### ISSUE TITLE
How to do styling of a squeezebox

### ISSUE THREAD

**Issue by miloskov** [edvin/tornadofx#822]
Hello,
I would like to style squeezebox in order to change the background color of the fold title only. How to do that?

**Comment by edvin** [comment]
The SqueezeBox fold title is infact a JavaFX TitledPane control, so you can look up styling in the JavaFX CSS Reference:

https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html

There you'll find that the TitledPane contains an HBox, which again contains a title.

You could also disocver this by starting the built-in LayoutDebugger, just hit Meta-J from your running App :)

The SqueezeBox has a class called `squeezebox`, so you can easily target only SqueezeBox based TitledPanes. Here is an example:

```kotlin
SqueezeBoxStyles.squeezeBox child titledPane {
    title {
        backgroundColor += Color.RED
    }
}
```

**Comment by miloskov** [comment]
Hello, 
thank you for your quick reply but I still have a problem (probably because I am new to Kotlin and Tornadofx - only a few days :) ).
Here is my code:
`
```
package views

import javafx.scene.paint.Color
import tornadofx.*

class TestStyles : View("My View") {
    override val root = squeezebox {
        addClass(MyStyle.mystyle)
        fold("Title of the fold") {
            text("Fold contents")
        }
    }
}

class MyStyle: Stylesheet() {
    companion object {
        val mystyle by cssclass()
    }
    init {
        mystyle{
            SqueezeBoxStyles.squeezeBox child titledPane {
                title {
                    backgroundColor += Color.RED
                }
            }
        }
    }
}
```
`
And the background color of the fold is unchanged (still gray). What am I doing wrong?

**Comment by edvin** [comment]
You're adding the `mystyle` class to the SqueezeBox, but then you're targeting a SqueezeBox inside a class that has the `mystyle` set. Here is the correct way to target the titledPane of a SqueezeBox with a custom style class on it:
```kotlin
class TestApp : App(TestStyles::class, MyStyle::class)

class TestStyles : View("My View") {
    override val root = squeezebox {
        addClass(MyStyle.redAccordion)
        fold("Title of the fold") {
            text("Fold contents")
        }
    }
}

class MyStyle : Stylesheet() {
    companion object {
        val redAccordion by cssclass()
    }

    init {
        redAccordion {
            titledPane {
                title {
                    backgroundColor += Color.RED
                }
            }
        }
    }
```
}

**Comment by miloskov** [comment]
OK. Thank you. Now it works :)
