### ISSUE TITLE
bindSelected with `out` modifier.

### ISSUE THREAD

**Issue by IARI** [edvin/tornadofx#823]
I am using two Models that pretty much are the same in terms of data they hold, but they have to implement the same Generic interface with a different type Parameter (which is not possible to do in the same class due to type erasure).
example code to illustrate the situation:
```Kotlin
interface I<T>
interface I12
class I1 : I<Int>, I12
class I2 : I<String>, I12
class I12Model : ItemViewModel<I12>() {}
```

Now i want to bind a `TableView<I12>` to a `I12Model`.
I cannot use `bindSelected` in this case,
In order to be able to, I just slightly edited the extension function and added it to my utils
```Kotlin
fun <T> TableView<out T>.bindSelected(model: ItemViewModel<in T>) {
    selectionModel.selectedItemProperty().onChange {
        model.item = it
    }
}
```
I propose to modify the tornadofy `bindSelected` extension function like that (one modifier is actually enough).

**Comment by edvin** [comment]
Great work! This should be a backwards compatible change, so I'll commit it right away.
