### ISSUE TITLE
Can a variable of type singleAssign be passed as a parameter to a sub view?

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#826]
Hi, I have a problem with the creation of variables of type singleAssign. In the main view I have all the methods related to that window, and I only create subviews when the view is very large, but I do not have any method in subviews, only creation of objects. Now, what I need is to be able to create a control in the subview, and be able to use the singleAssign, but I have not been able to achieve it because I get errors:

```
class MainView: View("Main") {
  private var txtSearch: TextFiel by singleAssign() // TextField must be created in the subview
  override val root = vbox {
      ...                     //
      ......                  //  Creation of other controls and more
      ............             //
     add(SubView::class, mapOf(SubView::txtSearch to txtSearch)) // Trying to pass as a parameter
 }

  // This method uses the TextField
  fun requestFocusTextfieldSearch(){
      txtSearch.requestFocus()
  }
}
```
This is the subview, it should only have control creation, it should not have logic or methods:
```
class SubView: View("Sub View"){
     val txtSearch: TextField by param() // Val cannot be reassigned
//  var txtSearch: TextField by param() // If I change the type of variable to "var", I get an error that param() is only read
     override val root = vbox {
          ...
          ......
          ............
         txtSearch = textfield() // ERROR (Val cannot be reassigned)
     }
}
```

How could you pass parameters of type singleAssign and create them in a subview? Thank you

**Comment by edvin** [comment]
If you want to create it in the subview, just created it there. If you want to access it from the main view, inject the subview and access it from there, like this:

```kotlin
class MainView: View("Main") {
    val subView: SubView by inject()
    val txtSearch = subView.txtSearch

    override val root = vbox {
        add(subView)
    }
}

class SubView : View() {
    val txtSearch = TextField()
}
```

However, exposing and passing UI elements like this is almost never the right way to do it. Instead of exposing the textfield, consider adding a function to SubView:

```kotlin
function focusSearchField() {
    txtSearch.requestFocus()
}
```

Now you can just call this function from your `MainView`:

```kotlin
fun requestFocusTextfieldSearch(){
    subView.focusSearchField()
}
```

A much better solution still would be firing an event and having the SubView react to that. That way you need no coupling between your views.

**Comment by TioCoding** [comment]
thanks for the answer, could you give me a small example of the last alternative? How could I throw an event and make the subview reaction? Thank you

**Comment by edvin** [comment]
Sure :)

```kotlin
object FocusSearchField : FXEvent()

// In MainView
fire(FocusSearchField)

// In SubView
textfield {
    subscribe<FocusSearchField>() {
        requestFocus()
    }
}
```

As you can see, you don't even need to hold a reference to the search field anymore :)

**Comment by TioCoding** [comment]
very interesting, thanks, I'm going to try it. :smile:

**Comment by edvin** [comment]
You won't regret it :) hehe

**Comment by TioCoding** [comment]
Yes, one last question, I currently use RxKotlinFx. Do you know if I can also achieve the same thing using RxKotlinFx? :stuck_out_tongue_closed_eyes:

**Comment by edvin** [comment]
I know very little about RxKotlinFx or Rx really, but I don't see why not :)

**Comment by thomasnield** [comment]
@TioCoding If I'm understanding your objective correctly, yes you can use RxKotlinFX to do this. This is how I would typically do it: 

```kotlin
// You can use TornadoFX dependency injection too
object SomeController { 
     val focusRequests = PublishSubject.create<Unit>()
}
// In MainView
mySource.toObservable()
     .map { Unit } 
     .subscribe(SomeController.focusRequests)

// In SubView
textfield {
    someController.focusRequests.subscribe { requestFocus() }
}
```

**Comment by TioCoding** [comment]
Hi @thomasnield , thanks for the answer and the solution with RxKotlinFx, but the solution seems a bit forced, from where the variable `mySource` comes out? . In any case, do you recommend using in this case FXEvent () of tornadofx? Thank you
