### ISSUE TITLE
There doesn't seem to be an AnchorPane builder

### ISSUE THREAD

**Issue by t-boom** [edvin/tornadofx#84]
There also isn't anything sort of `AnchorPaneConstraints`

**Comment by thomasnield** [comment]
Yeah I had this on my todo list but never got around to it, mostly because I have little experience with AnchorPane. We can add but I probably wont get to it until this weekend. If you have a good vision on how to build it feel free to take lead again!

**Comment by t-boom** [comment]
If I get some time in the next couple of days I'll look into it.

**Comment by t-boom** [comment]
I guess I have time now :)
