### ISSUE TITLE
Widen types (e.g. label)

### ISSUE THREAD

**Issue by jschneider** [edvin/tornadofx#843]
I try to create a label with an icon. In my view model I have created a binding (Bindings.createObjectBinding(....) that contains the icon.

Unfortunately "Controls.kt:316 #label" expects a ObjectProperty.

Suggestion: Change the type of graphicProperty to "ObservableValue<Node>"

**Comment by edvin** [comment]
I did this yesterday, so it's available in the latest snapshot :)
