### ISSUE TITLE
property with `by singleAssign()` for combobox gives UnitializedPropertyAccessException 

### ISSUE THREAD

**Issue by leder11011** [edvin/tornadofx#845]
Cannot instantiate combobox as described in guide and `by singleAssign()` is unassigned:
```
package de.auticon.maven.tornadofx

import javafx.application.Platform
import javafx.beans.property.SimpleBooleanProperty
import javafx.beans.property.SimpleObjectProperty
import javafx.beans.property.SimpleStringProperty
import javafx.scene.control.Label
import javafx.scene.layout.BorderPane
import tornadofx.*

import javafx.collections.FXCollections
import javafx.scene.control.Button
import javafx.scene.control.TextField
import javafx.scene.control.ToggleGroup
import javafx.scene.layout.VBox
import javafx.scene.paint.Color

import javafx.stage.StageStyle
import java.time.LocalDate
import kotlin.concurrent.thread

class MyView1: View() {
    override val root = borderpane {
        top<TopView>()
        bottom<BottomView>()
    }
}

class TopView() : View() {

    val dateProperty = SimpleObjectProperty<LocalDate>()

    private val toggleGroup2 = ToggleGroup()
    private val toggleGroup = ToggleGroup()
    val texasCities = FXCollections.observableArrayList("Austin",
        "Dallas","Midland","San Antonio","Fort Worth")

    val selectedCity: SimpleStringProperty by singleAssign()
    val booleanProperty: SimpleBooleanProperty by singleAssign()
    var name : TextField by singleAssign()
        //get() = this.name
        //set(value) = this.name.text(value)

    override val root = vbox() {


        hbox {
            label("First Name")
            textfield("Vorname")
        }
        hbox {
            label("Last Name")
            name = textfield("Nachname") {
                textProperty().addListener { obs, old, new ->
                    println("You typed: " + new)

                }
            }
        }

        textarea("Type memo here") {
            selectAll()
        }

        datepicker(dateProperty) {
            value = LocalDate.now()
        }

        vbox {
            radiobutton("Employee", toggleGroup2)
            radiobutton("Contractor", toggleGroup2)
            radiobutton("Intern", toggleGroup2)
        }

        hbox {
            togglebutton("YES", toggleGroup)
            togglebutton("NO", toggleGroup)
            togglebutton("MAYBE", toggleGroup)
        }

        combobox(selectedCity, texasCities)

        checkbox("Admin Mode") {
            action {
                println(isSelected) //not accessible

            }
        }

        button("Press Me") {
            textFill = Color.RED
            useMaxWidth = true
            action {
                replaceWith(MyView2::class, ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.LEFT))
            }
        }


    }

    override fun onDock() {
        println("Docking MyView1!")
    }

    override fun onUndock() {
        println("Undocking MyView1!")
        println(name.text)
    }
}

class BottomView: View() {
    override val root = progressbar {
        thread {
            for (i in 1..100) {
                Platform.runLater { progress = i.toDouble() / 100.0 }
                Thread.sleep(100)
            }
        }
    }
}

class MyView2: View() {
    override val root = vbox {
        button("Go to MyView1") {
            action {
                replaceWith(MyView1::class, ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.RIGHT))
            }
        }
    }
    override fun onDock() {
        println("Docking MyView2!")
    }
    override fun onUndock() {
        println("Undocking MyView2!")
    }
}
```
[this](https://drive.google.com/open?id=1VvVEFBbxPLSHJHQweH96Qz3MIWy003C-) is my project.

thx in advance!

**Comment by edvin** [comment]
Pretty sure this is a bug in your code :) Please post a complete code example.

**Comment by edvin** [comment]
First of all, there is absolutely no need to use `singleAssign()` for properties. It makes no sense, and for some of them you never actually assigned a value, so obviously they would be undefined when you access them to create your combobox.

Just do:

```kotlin
val selectedCity = SimpleStringProperty()
```

Next, instead of creating a variable for the textfield with singleAssign, create a string property and bind to that. When you need to manipulate the value, just change the property and leave the textfield, it will update automatically.

Also, do not run loops and spawn threads directly from the UI thread. It will not give you the result you are looking for. Wrap in `runAsync`.

Incorporating these changes, and fixing some other small niggles, your code would look like this:


```kotlin
import javafx.beans.property.SimpleObjectProperty
import javafx.beans.property.SimpleStringProperty
import javafx.collections.FXCollections
import javafx.scene.control.ToggleGroup
import javafx.scene.paint.Color
import java.time.LocalDate
import kotlin.concurrent.thread

class MyView1 : View() {
    override val root = borderpane {
        top<TopView>()
        bottom<BottomView>()
    }
}

class TopView : View() {
    val dateProperty = SimpleObjectProperty<LocalDate>()

    private val toggleGroup2 = ToggleGroup()
    private val toggleGroup = ToggleGroup()
    val texasCities = FXCollections.observableArrayList("Austin",
            "Dallas", "Midland", "San Antonio", "Fort Worth")

    val selectedCity = SimpleStringProperty()
    val lastNameProperty = SimpleStringProperty()

    override val root = vbox() {


        hbox {
            label("First Name")
            textfield("Vorname")
        }
        hbox {
            label("Last Name")
            textfield(lastNameProperty) {
                textProperty().onChange {
                    println("You typed: $it")

                }
            }
        }

        textarea("Type memo here") {
            selectAll()
        }

        datepicker(dateProperty) {
            value = LocalDate.now()
        }

        vbox {
            radiobutton("Employee", toggleGroup2)
            radiobutton("Contractor", toggleGroup2)
            radiobutton("Intern", toggleGroup2)
        }

        hbox {
            togglebutton("YES", toggleGroup)
            togglebutton("NO", toggleGroup)
            togglebutton("MAYBE", toggleGroup)
        }

        combobox(selectedCity, texasCities)

        checkbox("Admin Mode") {
            action {
                println(isSelected)
            }
        }

        button("Press Me") {
            textFill = Color.RED
            useMaxWidth = true
            action {
                replaceWith<MyView2>(ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.LEFT))
            }
        }


    }

    override fun onDock() {
        println("Docking MyView1!")
    }

    override fun onUndock() {
        println("Undocking MyView1!")
        println(lastNameProperty.value)
    }
}

class BottomView : View() {
    override val root = progressbar {
        runAsync {
            thread {
                for (i in 1..100) {
                    runLater { this@progressbar.progress = i.toDouble() / 100.0 }
                    Thread.sleep(100)
                }
            }
        }
    }
}

class MyView2 : View() {
    override val root = vbox {
        button("Go to MyView1") {
            action {
                replaceWith<MyView1>(ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.RIGHT))
            }
        }
    }

    override fun onDock() {
        println("Docking MyView2!")
    }

    override fun onUndock() {
        println("Undocking MyView2!")
    }
}
```

**Comment by leder11011** [comment]
Hello Edvin,

ty for your update. Unfortunately I still get the „cycle detected“ uncaught Exception, when switching with the Buttons between views at runtime…

Bye
Gerrit

Gesendet von Mail für Windows 10

Von: Edvin Syse
Gesendet: Dienstag, 13. November 2018 15:03
An: edvin/tornadofx
Cc: leder11011; Author
Betreff: Re: [edvin/tornadofx] property with `by singleAssign()` for comboboxgives UnitializedPropertyAccessException (#845)

First of all, there is absolutely no need to use singleAssign() for properties. It makes no sense, and for some of them you never actually assigned a value, so obviously they would be undefined when you access them to create your combobox.
Just do:
val selectedCity = SimpleStringProperty()
Next, instead of creating a variable for the textfield with singleAssign, create a string property and bind to that. When you need to manipulate the value, just change the property and leave the textfield, it will update automatically.
Also, do not run loops and spawn threads directly from the UI thread. It will not give you the result you are looking for. Wrap in runAsync.
Incorporating these changes, and fixing some other small niggles, your code would look like this:
import javafx.beans.property.SimpleObjectProperty
import javafx.beans.property.SimpleStringProperty
import javafx.collections.FXCollections
import javafx.scene.control.ToggleGroup
import javafx.scene.paint.Color
import java.time.LocalDate
import kotlin.concurrent.thread

class MyView1 : View() {
    override val root = borderpane {
        top<TopView>()
        bottom<BottomView>()
    }
}

class TopView : View() {
    val dateProperty = SimpleObjectProperty<LocalDate>()

    private val toggleGroup2 = ToggleGroup()
    private val toggleGroup = ToggleGroup()
    val texasCities = FXCollections.observableArrayList("Austin",
            "Dallas", "Midland", "San Antonio", "Fort Worth")

    val selectedCity = SimpleStringProperty()
    val lastNameProperty = SimpleStringProperty()

    override val root = vbox() {


        hbox {
            label("First Name")
            textfield("Vorname")
        }
        hbox {
            label("Last Name")
            textfield(lastNameProperty) {
                textProperty().onChange {
                    println("You typed: $it")

                }
            }
        }

        textarea("Type memo here") {
            selectAll()
        }

        datepicker(dateProperty) {
            value = LocalDate.now()
        }

        vbox {
            radiobutton("Employee", toggleGroup2)
            radiobutton("Contractor", toggleGroup2)
            radiobutton("Intern", toggleGroup2)
        }

        hbox {
            togglebutton("YES", toggleGroup)
            togglebutton("NO", toggleGroup)
            togglebutton("MAYBE", toggleGroup)
        }

        combobox(selectedCity, texasCities)

        checkbox("Admin Mode") {
            action {
                println(isSelected)
            }
        }

        button("Press Me") {
            textFill = Color.RED
            useMaxWidth = true
            action {
                replaceWith<MyView2>(ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.LEFT))
            }
        }


    }

    override fun onDock() {
        println("Docking MyView1!")
    }

    override fun onUndock() {
        println("Undocking MyView1!")
        println(lastNameProperty.value)
    }
}

class BottomView : View() {
    override val root = progressbar {
        runAsync {
            thread {
                for (i in 1..100) {
                    runLater { this@progressbar.progress = i.toDouble() / 100.0 }
                    Thread.sleep(100)
                }
            }
        }
    }
}

class MyView2 : View() {
    override val root = vbox {
        button("Go to MyView1") {
            action {
                replaceWith<MyView1>(ViewTransition.Slide(0.3.seconds, ViewTransition.Direction.RIGHT))
            }
        }
    }

    override fun onDock() {
        println("Docking MyView2!")
    }

    override fun onUndock() {
        println("Undocking MyView2!")
    }
}

**Comment by edvin** [comment]
You didn't even mention that you had a problem with that, so I only looked for the issue you reported :) Will take a look at it when I have time :)

**Comment by edvin** [comment]
I looked at it quickly, and the cycle is quite apparent :) You embed TopView inside of MyView1. Then you swap out TopView for MyView2. At this stage, MyView1 is still visible, as it is the parent of MyView2, because MyView2 took the place of TopView. Then you try to replace MyView2 with MyView1, which is still the root of the hierarchy at this stage.

**Comment by leder11011** [comment]
ty, I will have a look...

**Comment by leder11011** [comment]
got it!
