### ISSUE TITLE
GUI builder mentioned in the Guide

### ISSUE THREAD

**Issue by leder11011** [edvin/tornadofx#846]
I read about the option to build GUIs in TornadoFX by Drag and Drop. Unfortunately I cannot find the reference anymore. Please provide the name of the GUI Builder for TornadoFX.

Thank you in advance!

Gerrit

**Comment by edvin** [comment]
There is no such product available, though work has started on one. Frankly, you don’t really need it, the builders are extremely concise and easy to work with in code :)
