### ISSUE TITLE
Example with kodein

### ISSUE THREAD

**Issue by georgeVasiliu** [edvin/tornadofx#850]
Hello, I'm currently trying to see if I can integrate Kodein with tornadofx (would really like the di() on my own custom components/objects/etc)

There's also another issue linked here : https://github.com/edvin/tornadofx/issues/419 that points to this, however, I guess things have changed since then or maybe I just don't have the knowledge?

I tried to first add to the build the depedency to kodein and see how I can rig up that method to handle the DI but I found that by using the guide at Kodein I get a very small library (?) and I'm not sure how to hook it up. I know it's not directly related to tornadofx, but I'd like to keep the inject() and di() from tornado and use another function for injecting other things.

This is the build file used:

```
buildscript {
    ext.kotlin_version = "1.3.10"
    ext.tornadofx_version = "1.7.17"
    ext.junit_version = "5.1.0"

    repositories {
        jcenter()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.junit.platform:junit-platform-gradle-plugin:1.1.0"
    }
}

apply plugin: "kotlin"
apply plugin: "application"
apply plugin: "org.junit.platform.gradle.plugin"

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

repositories {
    jcenter()
    mavenLocal()
    mavenCentral()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile 'org.slf4j:slf4j-api:1.7.21'
    compile 'com.lmax:disruptor:3.3.4'
    compile 'org.apache.logging.log4j:log4j-slf4j-impl:2.6.2'
    compile 'org.apache.logging.log4j:log4j-api:2.6.2'
    compile 'org.apache.logging.log4j:log4j-core:2.6.2'
    compile 'org.kodein.di:kodein-di-generic-jvm:6.0.0'

    compile "no.tornado:tornadofx:$tornadofx_version"

    testCompile "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testRuntime "org.junit.jupiter:junit-jupiter-engine:$junit_version"
}

mainClassName = "com.example.demo.app.MyApp"

jar {
    manifest {
        attributes(
                "Class-Path": configurations.compile.collect { it.getName() }.join(" "),
                "Main-Class": mainClassName
        )
    }
    from(configurations.compile.collect { entry -> zipTree(entry) }) {
        exclude "META-INF/MANIFEST.MF"
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
}
```

Looking through Intellij at external libraries to see what classes are in the kodein dependency I see:
![kodein](https://user-images.githubusercontent.com/26601265/48842570-45b5f080-ed9d-11e8-8d3e-8cb24b03e404.png)

I'm unsure how to further approach this issue and integrate it?

**Comment by gtnarg** [comment]
Hi - have you used Kodein outside of TornadoFx?  Nothing should stop you
from using it the exact same way.

The only difference is that TornadoFx components (View, Fragments, etc)
will be instantiated by TFX and your components will be instantiated by a
Kodein delegate.

You don't even need the di() delegate as issue 419 already indicated.

Grant

**Comment by georgeVasiliu** [comment]
Hello - it was something really simple and stupid, actually. I had followed the kodein getting started page in which the dependency mentioned there was "compile 'org.kodein.di:kodein-di-generic-jvm:6.0.0'".

You need to use "compile 'com.github.salomonbrys.kodein:kodein:4.1.0'" to import the actual di framework.

Don't know how I got so easily confused regarding that, guess that starting guide threw me off. Anyway, this issue can be closed.

**Comment by edvin** [comment]
Thanks for reporting back :)
