### ISSUE TITLE
ItemViewModel default values

### ISSUE THREAD

**Issue by georgeVasiliu** [edvin/tornadofx#851]
Hello, I'm trying to solve something minor here that I've had some difficulty with.
Suppose we have a simple class like
```
class GeneralSettings {
    var language by property(Locale.ENGLISH)
    fun languageProperty() = getProperty(GeneralSettings::language)

    var keyboard by property("English (United States)")
    fun keyboardProperty() = getProperty(GeneralSettings::keyboard)
}
```

And the associated ItemViewModel
```
class GeneralSettingsModel : ItemViewModel<GeneralSettings>() {
    val language = bind { item?.languageProperty() }
    val keyboard = bind { item?.keyboardProperty() }
}
```

Now, on a simple UI we have two choiceboxes which retrieve their items value and then I bind them:
```
  choiceBoxLanguage.items = controller.locales
  choiceBoxLanguage.bind(controller.generalSettings.language)
  choiceBoxKeyboard.items = controller.keyboards
  choiceBoxKeyboard.bind(controller.generalSettings.keyboard)
```

When the UI pops out I was surprised to see that their value is not set to the default one that is set in property?
![1pic](https://user-images.githubusercontent.com/26601265/49098337-540d7c00-f277-11e8-9190-0e4dd61716bc.png)

Of course, the items themselves are present: 
![2pic](https://user-images.githubusercontent.com/26601265/49098370-64255b80-f277-11e8-9bac-43c68a9b3458.png)

I thought that if the property itself has a default value to it, the binding should have defaulted to that one?
What I was expecting : the choiceBoxLanguage default value to be Locale.ENGLISH and choiceBoxKeybaord default value to be English (United States). Appears as if they are actually null.

**Comment by edvin** [comment]
Did you assign an item to your ViewModel then? :)

If you just instantiated a `GeneralSettingsModel `, it doesn't back any specific `GeneralSettings` automatically. You can either set a default item in the model, or assing one specifically. For example:

```kotlin
class GeneralSettingsModel(settings: GeneralSettings? = GeneralSettings() : ItemViewModel<GeneralSettings>(settings)
```

I also noticed that you are using outdated syntax in several places. This is the recommended syntax for properties and viewmodels:

```kotlin
class GeneralSettings {
    val languageProperty = SimpleObjectProperty(Locale.ENGLISH)
    var language by languageProperty

    val keyboardProperty = SimpleStringProperty("English (United States)")
    var keyboard by keyboardProperty
}

class GeneralSettingsModel : ItemViewModel<GeneralSettings>() {
    val language = bind(GeneralSettings::languageProperty)
    val keyboard = bind(GeneralSettings::keyboardProperty)
}
```

You should also consider using the type safe builders, where you can bind the property and assign the items in one simple sentence.

**Comment by ctadlock** [comment]
Good content here. Closing as its not active.
