### ISSUE TITLE
How can I optimize the speed when displaying a view?

### ISSUE THREAD

**Issue by TioCoding** [edvin/tornadofx#852]
Hi, maybe this question does not have much to do with Tornadofx, but it's a problem that I've been dealing with for quite some time. I have a view in which I have many controls and it has become very heavy. The problem is that when I try to show this view, the screen crashes, I use the replaceChildren method to change the windows as shown in the GIF.

```kotlin
override fun setScreenContent(view: KClass<out View>) {
   val viewNew = mapInstanceView[view] ?: find(view).apply { mapInstanceView[view] = this }
   if (paneContentView.children.none { it == viewNew.root }) {
     txtTitle.value = viewNew.title
       // this is the method that makes blocking the application when it is a big view
     paneContentView.replaceChildren(viewNew.root) // <------
   }
}
```
In this example I have a window called BigView, where when you select it in the Menu, it shows it on screen:

![gitornado](https://user-images.githubusercontent.com/22163898/49262107-ff9f0380-f412-11e8-8da9-28cc5db2e94e.gif)

(In this case, I've only added several buttons to show the problem)

I have used it on computers with less performance and the blocking of the application lasts even more :(.

My question is, is there any way to open a window with many controls without blocking my program?
What do you recommend?

Maybe I'm wrong to use several controls in a view, but I have a form with many lists, controls, animations, etc. That make the application much friendlier to the user.

I hope you can help me, thank you very much for everything

**Comment by edvin** [comment]
Looking at the size of the scroll bar when you select "Big View" it seems like you have a brutal amount of controls in there. Without knowing what these components do, there isn't much I can offer in terms of advice.

You might do something in the initialization of some of these views that takes a little bit of time, and that time adds up. You'd need to do some profiling of your app to figure out where that time is spent.

One idea that comes to mind is to only initialize the controls that are on screen right now. You might have success with ListView or DataGrid for this purpose. Make an enum that represents each item in the list, and only initialize them using `cellFormat` when they become visible.

**Comment by bekwam** [comment]
Is there any type of network, I/O, or database operations supporting BigView?  Or, are these pure UI controls built up with loops, logic, and RAM-based data structures?

**Comment by TioCoding** [comment]
No, there is no network transfer, nor any consumption of external resources, only views that delay when loading all the controls.

**Comment by TioCoding** [comment]
As I said above, the problem I have is that I use a TabPane where I have several views and controls. And the question would be, how could I just load what is in the first TAB? and the rest, no?

**Comment by TioCoding** [comment]
@bekwam The GIF is just a sample of how the application is blocked when opening the view with many controls. And it becomes slower on computers with fewer resources. The real application where I have this problem uses many TABPANE with several views and controls

**Comment by bekwam** [comment]
I'd like to put a test case together that strips out the JFoenix.  This would be a tabpane / tab structure driving the contents extracted from a Map.  What is the structure like in the contents?  Is PRODUCTOS a FlowPane and PRECIO a Button?  What's the max number of containers and controls in BIG VIEW?

**Comment by TioCoding** [comment]
Apparently it's my problem, I'm using many controls, and most do not show them, I'm going to rewrite my code to improve the performance of the application.
