### ISSUE TITLE
Adding a column of checkboxes to a TableView

### ISSUE THREAD

**Issue by BornIncompetence** [edvin/tornadofx#857]
I want to display a `Tableview` that lets me **edit** a `Checkbox` per row, so I can import it into my program. It will load in all the appointments that are selected in the `Tableview` when I click import. I'm just having trouble making the interface work. Here is my code below. 

View

    class FileExplorer : View("Import Screen") {
        private val ctrlImport: ImportController by inject()
        // private val importModel = AppointmentModel(Appointment())
        private val isOverwrite = SimpleBooleanProperty()
    
        override val root = borderpane {
            center = vbox {    
                tableview(ctrlImport.appointments) {
                    // HELP
                    column("Select", Appointment::selectedProperty).setCellFactory {
                        CheckBoxTableCell(param = Appointment::selectedProperty)
                    }
                    column("ID", Appointment::idProperty)
                    column("Title", Appointment::titleProperty)
                    column("Start Date", Appointment::startDateProperty)
                    column("End Date", Appointment::endDateProperty)
                }
                checkbox("Override pre-existing appointments", isOverwrite) {
                    isSelected = true
                }
            }
    
            bottom = hbox {    
                button("Import").action {
                    // ...
                button("Cancel").action {
                    close()
                }
            }
        }
    }

Controller

    class ImportController : Controller() {
        val appointments: ObservableList<Appointment> =
            FXCollections.observableArrayList<Appointment>()
    
        fun read(file: File) {
            appointments.clear()
            file.forEachLine { line ->
                val tokens = line.split(",")
    
                if (tokens.size != 4) {
                    throw ProjectException()
                }
    
                //val formatAMPM = SimpleDateFormat("hh:mm:ss aa")
                //val format24 = SimpleDateFormat("HH:mm:ss")
                val start = tokens[1].split(" ")
                val end = tokens[2].split(" ")
                //val startTime = format24.format(formatAMPM.parse(start[1] + start[2]))
                //val endTime = format24.format(formatAMPM.parse(end[1] + end[2]))
    
                appointments.add(
                    Appointment(
                        tokens[0],
                        LocalDate.parse(start[0]),
                        //startTime,
                        start[1],
                        LocalDate.parse(end[0]),
                        //endTime,
                        end[1],
                        tokens[3].toInt()
                    )
                )
            }
        }
    
        class ProjectException : Exception("The file is formatted incorrectly")
    }

Appointment

    class Appointment(
        title: String? = null,
        startDate: LocalDate? = null,
        startTime: String? = null,
        endDate: LocalDate? = null,
        endTime: String? = null,
        id: Int = 0
    ) {
        val titleProperty = SimpleStringProperty(this, "", title)
        var title by titleProperty
    
        val startDateProperty = SimpleObjectProperty<LocalDate>(this, "", startDate)
        var startDate by startDateProperty
    
        val endDateProperty = SimpleObjectProperty<LocalDate>(this, "", endDate)
        var endDate by endDateProperty
    
        val startTimeProperty = SimpleStringProperty(this, "", startTime)
        var startTime by startTimeProperty
    
        val endTimeProperty = SimpleStringProperty(this, "", endTime)
        var endTime by endTimeProperty
    
        val idProperty = SimpleIntegerProperty(this, "", id)
        var id by idProperty
    
        val selectedProperty = SimpleBooleanProperty()
    }

**Comment by edvin** [comment]
We have a builtin for that:

```kotlin
column("Select", Appointment::selectedProperty).useCheckbox()
```

**Comment by BornIncompetence** [comment]
I could have sword I tried getting that function to work, only to have it fail, turns out i was just one line off from what I had so far. 😅 My thanks.

**Comment by arvinrasheda** [comment]
how to get the selectedProperty @edvin ?

**Comment by arvinrasheda** [comment]
> We have a builtin for that:
> 
> ```kotlin
> column("Select", Appointment::selectedProperty).useCheckbox()
> ```

are useCheckbox() still work ? because after trying I get an error

**Comment by SchweinchenFuntik** [comment]
Please provide an example code.
