### ISSUE TITLE
Window have a different look on different Java versions.

### ISSUE THREAD

**Issue by MairwunNx** [edvin/tornadofx#858]
> It problem causes (maybe) wrong margin, and my caption looks not cool on Java 8.

Application run with Java 10:
![image](https://user-images.githubusercontent.com/39625750/49646588-8b76e800-fa30-11e8-85e7-dd88219da300.png)

Application run with Java 8:
![image](https://user-images.githubusercontent.com/39625750/49646613-9c275e00-fa30-11e8-916d-54e8f7585dd5.png)

For creating GUI i use scenebuilder (scenebuilder-10.0.0-all)

Code for starting or creating GUI:
![image](https://user-images.githubusercontent.com/39625750/49646716-00e2b880-fa31-11e8-93a6-f14cae894d30.png)

View class of TornadoFx application:
![image](https://user-images.githubusercontent.com/39625750/49646769-338cb100-fa31-11e8-9bee-edce0a9bcda2.png)

Application Compiler Java version: 1.8.0_172, 
System: Microsoft Windows NT 10.0.17134.0 X64

**Comment by bekwam** [comment]
I'm having a difficult time seeing the difference.  Is it that there is less padding in the Region Counters pane?

**Comment by MairwunNx** [comment]
I make big screen with difference windows on Java 8 and Java 10. See please.
![tornadofx-window-difference-issue](https://user-images.githubusercontent.com/39625750/49647407-7bacd300-fa33-11e8-8406-4a7c6ce46803.jpg)

**Comment by edvin** [comment]
Since you have your UI in FXML - try creating a vanilla JavaFX app and render the UI. I suspect you will see exactly the same issue. Let us know :)

**Comment by MairwunNx** [comment]
@edvin How i can render it in JavaFx? I not work with JavaFx, i'm newbie in Kotlin and in building GUI application on Java \ Kotlin. Sorry. I can load done JavaFx application and select my view?

**Comment by MairwunNx** [comment]
@edvin Thanks :) It not critical bug, but, i think, what so many people use Java 8, because i create it issue :D.

I.e i can boldly switch Java version to 10? :D (Simple i read on different forums, what TornadoFx not support Java 9 and >)

**Comment by edvin** [comment]
TornadoFX apps will not run perfectly on JDK11 yet. We're working on a port, but I'm extremely busy these days, so not much have happened for a while I'm afraid :)

**Comment by MairwunNx** [comment]
@bekwam Thanks. I also see it bug with Java Fx. Maybe it caused by setResizable.

I remove setResizable and my window do normally render, thanks. Maybe i help somebody. )))

![image](https://user-images.githubusercontent.com/39625750/49648352-89178c80-fa36-11e8-84f3-389dcb49d64b.png)

**Comment by MairwunNx** [comment]
@edvin Thanks, well... i can switch Java ver to 10? :) I stay installed Java 8 only for TornadoFx :DD

**Comment by edvin** [comment]
Great :) Closing the issue.

**Comment by edvin** [comment]
No, only Java 8 is compatible with TornadoFX. You won't notice any difference upgrading though, since we're writing in Kotlin :)

**Comment by MairwunNx** [comment]
Thanks @edvin goodluck :))
