### ISSUE TITLE
FXCollections Declarations

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx#86]
Small ask that I can implement since you all are busy with CSS DSL stuff: do you suppose there is a way we can streamline the use of FX collections a little bit in a Kotlin-esque way?

Instead of this...

```kotlin
val greekLetters = FXCollections.observableArrayList("Alpha","Beta",
        "Gamma","Delta","Epsilon")
```

Why not this?

```kotlin
val greekLetters = observableList("Alpha","Beta","Gamma","Delta","Epsilon")

```

Maybe we can add extension functions to non-FX collections as well to turn them into FX collections too? 

```kotlin
//using Google Guava collections
val greekLetters = ImmutableList.of("Alpha","Beta",
        "Gamma","Delta","Epsilon")

//turn into ObservableList
val fxGreekLetters = greekLetters.toUnmodifiableObservableList()
```

**Comment by t-boom** [comment]
I like this idea

**Comment by edvin** [comment]
Absolutely :) Btw, we already have this:

```kotlin
val greekLetters = listOf("Alpha","Beta", "Gamma", "Delta","Epsilon").observable()
```

With the right import, you can also write this today:

```kotlin
import javafx.collections.FXCollections.observableArrayList
val greekLetters = observableArrayList("Alpha","Beta", "Gamma", "Delta","Epsilon")
```

I'm not all that familiar with FXCollections so I would have to look a bit closer so we don't add stuff that's already there, or at least find the best way to add these functions :)

**Comment by thomasnield** [comment]
Oh excellent. I don't know if I agree with the word choice here. `observable()` might confuse Rx people like me and it might clash with reactive projects. Of course the `Observable` type itself is competed over by many domains including `java.util` haha. 

Do you think we can be more explicit and specify it as `observableList()` instead of `observable()`? I don't think it hurts to add the `observableList()` standalone function either since that feels intuitive and Kotlin-esque. I'll let you guys decide.

**Comment by edvin** [comment]
I see :) Well, apart from being slightly more verbose, I don't mind changing it to `observableList` if that really helps. But does it really? As you pointed out, there are several different notions about what an observable is. In JavaFX context (and therefore TornadoFX) this means one thing, in Kotlin it means another, heck, even `java.util` has an Observable :)

The reason I named it `observable` was that it is a function on a `List`, that makes the list observable (in JavaFX speak):

```kotlin
fun <T> List<T>.observable() = FXCollections.observableList(this)
```

You know more about RX than me, so if changing the function will help prevent confusion I'm all for it. We should however deprecate the old name and delete it later. Your call, @thomasnield! :)

**Comment by thomasnield** [comment]
Well I guess it could be viewed either way. I'm kind of changing my mind. One thing I learned early in the RxKotlinFX project is Kotlin can make some tasks so trivial it's barely worth creating a library. I'm beginning to wonder if that's the case here.

I can always whip up my own ad hoc extension functions in my own projects. It's not always worthwhile to impose a flavor for something so simple to implement on your own domain. That's the nice thing about Kotlin. It reduces the need to create centralized APIs for everything and allows you to be more tactical.
Unless anybody feels differently Im okay with dropping this.

**Comment by edvin** [comment]
I totally agree with that assessment, Thomas :) Closing.
