### ISSUE TITLE
Rest class should not need a working Fx platform

### ISSUE THREAD

**Issue by Romanow88** [edvin/tornadofx#861]
Right now the Rest class requires an initialized toolkit to be able to function. This is done to wrap the ongoingRequests collection mutations into Platfrom.runLater, which looks like a concurrency workaround. Proposal - replace the backing impl to a concurrent one and remove the .runLater.

This will allow for more separation and will simplify writing tests involving the Rest class. 

Possible issues: There maybe implementations that use the Rest.ongoingRequests and expect the change to be processed on the FX thread.

**Comment by edvin** [comment]
Reporting to `ongoingRequests` has nothing to do with a workaround, but is there to allow the UI to report on ongoing requests. See `RestProgressBar`. I believe there were issues with adding items on an observable collection on any other thread, so I'm not sure how to work around it. For tests we could of course skip this step by setting a flag, but that would actually break a couple of tests already in place. 

What's the problem with initializing the toolkit in your tests? A call to `FxToolkit.registerPrimaryStage()` is all you need, and that's what we're doing to be able to test almost anything in TornadoFX.

**Comment by Romanow88** [comment]
I am using now `registerPrimaryStage` to make the test work. That causes a dependency to `testfx` as well as starting up the platform, which cant be undone without recreating the JVM. 

If the wrapping was done as a design decision than it's totally fine, we can just put the test to the integration target.

**Comment by edvin** [comment]
Tip: If you don't use testfx (in any test in the module) and don't want the dependency you can instantiate a `JFXPanel()` instead, it will have the same effect :)
