### ISSUE TITLE
Maybe non-compliant opening tree views elements.

### ISSUE THREAD

**Issue by MairwunNx** [edvin/tornadofx#865]
When i clicking fast (i.e double click), my treeview item open good and successfully.
When i click not fast (i.e one click), my treeview item not opened, and it no good i think.

If i not true think, can you add bool property "openedOnClick". Thanks!
![treeviewmaybeissue](https://user-images.githubusercontent.com/39625750/50174504-6c6b3680-030b-11e9-9a6f-11bbc9c9c4c7.gif)

**Comment by edvin** [comment]
This is the behavior of the JavaFX TreeView: Double click expands or collapses, single click does nothing, expect when you click on the icon - then it only requires a single click to expand/collapse.

If you want to change this behavior you can add a mouse event handler to the treeview, like this:

```kotlin
setOnMouseClicked {
    with (selectionModel.selectedItem) {
        isExpanded = !isExpanded
    }
}
```

**Comment by MairwunNx** [comment]
Thanks @edvin ! **Good solution**, you can mark it issue as question 👍 

And one more question: How i can get "`IsHeaderItem`" or "`IsExpandableItem`"?

**Comment by edvin** [comment]
`TreeView` has an `isLeaf()` function and a corresponding `isLeafProperty` :)

**Comment by MairwunNx** [comment]
thanks @edvin ! Good Job! You can close the issue.

**Comment by edvin** [comment]
Great! Are you using a theme for your app or did you write the CSS from scratch yourself? Looks nice :)

**Comment by ruckustboom** [comment]
Looks like the [JFXtras JMetro dark theme](https://github.com/JFXtras/jfxtras-styles). Is that right?

**Comment by MairwunNx** [comment]
@edvin no, it JFXtras JMetro dark theme, but with my edits. 

https://github.com/JFXtras/jfxtras-styles/issues/22

**Comment by MairwunNx** [comment]
@ruckustboom yes :)
