### ISSUE TITLE
Form as dialog that can be submitted with Enter

### ISSUE THREAD

**Issue by Warkst** [edvin/tornadofx#867]
I've tried creating a builder for showing a form in a dialog. The result is a builder function called `formdialog`, which aims to replace `form`. It takes a lambda, creates a `Form()` and applies the lambda on the form object, but also injects a submit button which can be triggered by pressing Enter anywhere in the form (inspired by #310).
Other than `form`, `formdialog` expects an object that extends ViewModel, which can be accessed from within the lambda using the variable `model`. There's also an extension function that allows you to define a custom callback when the form is submitted. Submission is blocked when the model is not valid.

I've attached the code in a file (don't forget to change the extension to kt) and an example of how the code can be used.

[FormDialog.txt](https://github.com/edvin/tornadofx/files/2695659/FormDialog.txt)

A custom viewmodel:
```
class MyModel(name: String = "Jane Doe", date: LocalDate = LocalDate.now()): ViewModel(){
    val nameProperty = bind {SimpleStringProperty(name)}
    val dateProperty = bind {SimpleObjectProperty(date)}
}
```

Somewhere in your view code:
```
button("Create new...") {
    action {
        formdialog(MyModel(), "New person") {
            fieldset {
                field("Name") {
                    textfield(model.nameProperty) {
                        required()
                    }
                }
                field("Date") {
                    datepicker(model.dateProperty) {
                        required()
                    }
                }
            }
            submit {
                println("Form was submitted: $model")
            }
        }
    }
}
```
Because the builder calls `openModal`, it really only makes sense to specify it in a callback from e.g. a button.

I would like some feedback on this.

**Comment by edvin** [comment]
We already have a builder for this, it's called `dialog`. To make a button trigger when you press enter, just configure it's `defaultButton` property.

**Comment by Warkst** [comment]
Shit, I feel so stupid... I'm trying to sprint before I can walk properly, but I'm just very excited about all the cool new stuff I'm discovering using TornadoFX!

**Comment by edvin** [comment]
Hey, don't feel bad about the time you put in - I bet you learned something from it :) I do the same thing with every framework I come across :) hehe
