### ISSUE TITLE
Release TornadoFX 1.4.2

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#87]
I would like to do a release as soon as possible because of a critical bug in the HttpURLConnection based implementation of `Rest.Engine`.

I realise that we have some issues that are "half done" like [Some More Control Builders](https://github.com/edvin/tornadofx/issues/76), but I don't think it's problematic to do a release with the completed features and get the last batch into the next release.

Please comment here if you have uncompleted features that should go into this release or if you have comments!

**Comment by thomasnield** [comment]
Sounds good to me. Other builders can wait for next release.

**Comment by edvin** [comment]
Cool, I'm releasing 1.4.2 now :) I will dedicate more time to documentation, I have a lot of catching up to do for the past 3 releases :) I'm also going to involve myself a little more with the [CSS DSL](https://github.com/edvin/tornadofx/issues/80) in the coming week.
