### ISSUE TITLE
tab(String, Node) creates two tabs

### ISSUE THREAD

**Issue by hudsonb** [edvin/tornadofx#876]
```
tabpane { tab("Foo", label("Foo")) }
```

Results in two tabs being added to the tabpane. One titled "Foo" as expected, but another named something like "Label@12345[styleClass=label]'Foo'".

**Comment by edvin** [comment]
That is as expected, since both builder calls are executed on the tab pane. Builder calls for any node called on a tab pane will be wrapped in a tab :)
