### ISSUE TITLE
Prefix path for FXML files in TornadoFX

### ISSUE THREAD

**Issue by Chatatata** [edvin/tornadofx#879]
Copying my own question from [StackOverflow.com](https://stackoverflow.com/questions/54064398/prefix-path-for-fxml-files-in-tornadofx)

> Is there a way to provide a path prefix for FXML files, used by TornadoFX, with using its convention `by fxml()`?
>
> Normally, TornadoFX conventionally tries to locate the FXML resources in `src/main/resources`, however, our application is large and this might now be the best idea. In our case, we would like to maintain the files in a subdirectory, i.e. `src/main/resources/fxml`.
> 
> We would like to set it up during application startup. Is this possible, currently?

I could make a pull request, if you could provide me some background about pulling the data from the `App` object to the `UIComponent#fxml(...)`.

Totally new in TornadoFX, by the way.

**Comment by edvin** [comment]
Hi! I added a way to override the default location, see my answer on SO. Will that work for you?

**Comment by Chatatata** [comment]
Yep, it's completely up to you to close this issue. Thanks again, for your decent solution.

**Comment by edvin** [comment]
Great :)
