### ISSUE TITLE
Dont Understand why my ItemViewModel dosent work. Help please

### ISSUE THREAD

**Issue by cyyprezz** [edvin/tornadofx#882]
Can you say me what im doing wrong? 
Nothing works with the Itemviewmodel like commits or take the data to the other view. 
Thats my Code: 

```kotlin
    class app : App(Workspace::class){

    override fun createPrimaryScene(view: UIComponent) = Scene(view.root, 1000.0,600.0)

    override fun onBeforeShow(view: UIComponent) {

        with(workspace){
                dock<mitarbeiterlist>()
                menubar{
                    menu("Lagerverwaltung"){
                        menuitem("Waren"){
                            dock<ArtikellistView>()
                        }
                    }
                }

           /* textfield {
                promptText = "Search"
                */
            }
        }
    }
  class Lageritems(id : Int,maskenkey : String,artbez : String? ,eancode : String?) {

    val idProperty = SimpleIntegerProperty(id)
    var id by idProperty

    val maskenkeyProperty = SimpleStringProperty(maskenkey)
    var maskenkey by maskenkeyProperty

    val artbezProperty = SimpleStringProperty(artbez)
    var arbez by artbezProperty

    val eancodeProperty = SimpleStringProperty(eancode)
    var eancode by eancodeProperty

}



   class Lagermodel : ItemViewModel<Lageritems>() {

    val artikel = SortedFilteredList<Lageritems>()
    val controller: Lagercontroller by inject()
    val selectedid = bind ( Lageritems::idProperty )
    val selectedmaskenkey = bind ( Lageritems::maskenkeyProperty)
    val selctedartbez = bind ( Lageritems::artbezProperty )
    val selctedEANCODE = bind ( Lageritems::eancodeProperty )


    override fun onCommit(commits: List<Commit>) {
        commits.findChanged(selctedEANCODE)?.let { println("Name chanced from ${it.second} to ${it.first}") }
    }

    private fun <T> List <Commit>.findChanged(ref: Property<T>): Pair<T, T>?{
        val commit = find {it.property == ref && it.changed}
        return commit?.let { (it.newValue as T) to(it.oldValue as T) }
    }
    fun refresh(){
        runAsync {
            updateMessage("loading")
            updateProgress(0.4, 1.0)
            controller.load()
            artikel.clear()
        } ui {
            artikel.addAll(controller.artikel.observable())
        }

    }


}



class Lagercontroller : Controller() {

    val artikel = SortedFilteredList<Lageritems>()
        fun load() =
            con.select("SELECT * FROM BSA")
                .toSequence {
                    Lageritems(
                        id = it.getInt("id"),
                        maskenkey = it.getString("maskenkey"),
                        artbez = it.getString("artbez"),
                        eancode = "eancode")
                }.forEach { t -> artikel.add(t)}

class ArtikellistView : View("Artikel-Liste") {


    val status: TaskStatus by inject()
    val model: Lagermodel by inject()


    override val root = vbox {
        tableview(model.artikel) {
            column("Nummer", Lageritems::maskenkeyProperty)
            column("Artikel-Bez.", Lageritems::artbezProperty)
            column("EAN", Lageritems::eancodeProperty).makeEditable()

            bindSelected(model)
            onUserSelect { workspace.dock(ArtikelView()) }
        }
    }

    override fun onRefresh() {
        model.refresh()
    }

    override fun onSave() {
        model.commit()
    }

    override fun onDock() {
        with(workspace) {
            hbox {
                progressbar(status.progress)
                label(status.message)
                visibleWhen { status.running }
                paddingAll = 4
            }
            textfield {
                model.artikel.filterWhen(textProperty(), { query, item -> item.maskenkey.contains(query, true) })

            }
        }
    }
}


class ArtikelView : View("Artikel"){

    val model : Lagermodel by inject()
    override val savable = model.dirty

    override val root = field {
        fieldset("Artikel-Daten"){
            field("Art-Bez") {
                textfield(model.selctedartbez)
            }
            field("EAN"){
                textfield(model.selctedEANCODE)
            }
        }
    }

    override fun onSave() {
        model.commit()
    }
}
```

**Comment by edvin** [comment]
This code is not runnable and also relies upon database access. Can you make it runnable so we can test it? `mitarbeiterlist` is missing as well, and there seems to be something missing in `Lagercontroller`, it's not terminated correctly.

**Comment by cyyprezz** [comment]
Halllo, thanks for your answer. I solved the problem by installing the tornadofx plugin. Without the plugin only 1 itemviewmodel worked per project. Now everything works fine with the plugin. What is missing in the Lagercontroller?
I have a question how to search without SortedFilteredList in a tableview (dataset)? 
Becouse im using fxml now, like that: 

class Artikel_List_View : View("Hello TornadoFX") {

    val db: DB by inject()

    override val root: SplitPane by fxml("/Views/Artikel_List_View.fxml")
    val button_save: Button by fxid()
    val button_refresh: Button by fxid()
    val button_rollback: Button by fxid()
    //var data = SortedFilteredList<Datensatz_Waren>()
    val mymodel: Datensatz_Waren_Model by inject()
    val textfield_input_ean: TextField by fxid()
    val textfield_search_ean: TextField by fxid()
    val tableview_artikel: TableView<Datensatz_Waren> by fxid()
    val einzellagermodel: Datensatz_Einzellager_Model by inject()
    val imageview_artikelbild : ImageView by fxid()

    init {
        with(tableview_artikel) {
            column("ID", Datensatz_Waren::idProperty)
            column("Artikelnummer", Datensatz_Waren::maskenkeyProperty)
            column("Bezeichnung", Datensatz_Waren::artbezProperty)
            column("EAN-Nummer", Datensatz_Waren::eancodeProperty)
            rowExpander(expandOnDoubleClick = true) {
                val items = db.List_Datensatz_Einzellager(it.id)
                tableview(items){
                    column("Bezeichnung",Datensatz_EinzelLager::bezProperty)
                    column("Bestand",Datensatz_EinzelLager::listProperty).cellFormat {
                        text = it.toString()
                        style{
                            if(it.toInt() > 0 ){
                                backgroundColor += Color.WHITE
                                textFill = Color.BLACK
                            }
                            else{
                                backgroundColor += c("#8b0000")
                                textFill = Color.WHITE
                            }
                        }
                    }
                    columnResizePolicy = SmartResize.POLICY
                    bindSelected(einzellagermodel)

                }
            }
                smartResize()
                subscribe<Datensatz_Waren_Addet> { onRefresh() }
                bindSelected(mymodel)
                onUserSelect {
                    imageview_artikelbild.image =

                }
            }
            with(textfield_input_ean) {
                textfield_input_ean.bind(mymodel.secean)
            }
        }
        fun save() {
            runAsync { db.update_Datensatz_Waren_EAN(textfield_input_ean.text, mymodel.secid.value.toInt()) }
        }

        fun rollback() {
            mymodel.rollback()
        }

        fun refresh() {
            tableview_artikel.asyncItems { db.List_Datensatz_Waren() }
        }

        override fun onDock() {
            with(textfield_search_ean) {
                
                
            }
        }

    }



Is there a easy way without usin SortedFilteredList?
