### ISSUE TITLE
tree(table)view, populate, lists and the swap method

### ISSUE THREAD

**Issue by Warkst** [edvin/tornadofx#884]
I found that, when swapping two elements in an observable list using the `swap` method, a tree(table)view observing that list in its populate method is not synchronized correctly. However, using 2 seperate calls to remove either element and then reinsert it in the correct place does work. I just wanted to report this so perhaps swap can be supported at some point.

**Comment by edvin** [comment]
We would need to make a special case for observable lists, something like this:

```kotlin
fun <T> MutableList<T>.swap(indexOne: Int, indexTwo: Int) {
    if (this is ObservableList<*>) {
        // Manually move and swap here
    } else {
        Collections.swap(this, indexOne, indexTwo)
    }
}
```

Would you like to submit a PR perhaps?

**Comment by Warkst** [comment]
Sure, but I'm not sure about the file to put it in. Where would you prefer?

**Comment by edvin** [comment]
You should create a PR where you change the existing code. If you want, you can also post the code here and I can update it of course.
