### ISSUE TITLE
How to handle exceptions in App successor?

### ISSUE THREAD

**Issue by Aqluse** [edvin/tornadofx#885]
I've got a nonnull property in my main view class, something like this:
```
class MainView : View("Name") {
    private val model =
            <property initialization code> ?: throw RuntimeException("Pls choose files!")
}
```
I want to catch this exception in my App class and relaunch an application, but seems like it handled in start(Stage) of parent, so I can't handle it this way.

**Comment by edvin** [comment]
Wrap access to the property in try/catch or call a function if that gives you issues. Should be nothing special needed here, other than catching the exception explicitly. It might be cleaner to call a function that handles the missing property and showing the correct ui instread of throwing an exception perhaps.

**Comment by bekwam** [comment]
This link shows how to use AOP to catch exceptions.  There's also setDefaultUncaughtExceptionHandler in TornadoFX itself.

https://courses.bekwam.net/public_tutorials/bkcourse_tornadofx_globalhandlerapp.html

**Comment by Aqluse** [comment]
@edvin my solution was to copy your `DefaultErrorHandler` and catch my exception in its method. I set this class by `Thread.setDefaultUncaughtExceptionHandler(handler)`. It works as intended. Could I ask you to make class `DefaultErrorHandler` opened to avoid making whole copy of it?
