### ISSUE TITLE
Fieldset "title" text is removed in combination with bindChildren

### ISSUE THREAD

**Issue by Warkst** [edvin/tornadofx#887]
What the title says: a fieldset that is data driven with `bindChildren` loses its title. Perhaps a call to `addLegend` after the new children have been inserted could do the trick?

**Comment by edvin** [comment]
Can you provide some sample code that showcases the issue?

**Comment by edvin** [comment]
There are a couple of issues with your code. A fieldset is a custom VBox, and by default it adds a label for the legend etc. When you call `bindChildren` inside of a fieldset, you will remove the custom layout components and only add the ones you supply through the `bindChildren` callback. Furthermore, you're actually calling the `field` builder on the `fieldset`, not just generating and returning a `field` which then `bindChildren` should attach to the parent.

To support bindChildren like you would except, it would have to have custom support for `Fieldset`. Let me see if that's something we can add easily.

**Comment by Warkst** [comment]
I see. But if I swap the builders for constructor calls like `Field().apply{...}`, then no nodes are shown at all. Is there a suggested way to bind the contents of a form such that it dynamically adapts when a backing observable map/list is changed, or would it be best to use a fragment rather than a view and just building building a new instance instead?

**Comment by edvin** [comment]
A simple solution would be to wrap the `bindChildren` call in a `vbox { }`. That would make sure that you don't interfere what the `Fieldset` expects. I want to clarify that it's completely acceptable to place arbitrary layout components inside a `Fieldset`. This is typically used to create custom form layouts.

**Comment by Warkst** [comment]
Ooh okay, that works, thanks!

**Comment by edvin** [comment]
I'm looking into making `bindChildren` work for `Fieldset` now :)

**Comment by Warkst** [comment]
That's okay - I blame the missing documentation on `bindChildren` and seeing as I butchered it in my implementation I think it's good I didn't end up writing a section about for the guide ^^

**Comment by edvin** [comment]
I think integral components like `Form` really should support `bindChildren` out of the box though :)

**Comment by Warkst** [comment]
Final question on this: you mentioned it's not right to use the `field` builder function inside `bindChildren`, yet I can't get the nodes to appear by swapping to a constructor call (`Field().apply{...}`). How should I do this properly?
