### ISSUE TITLE
Properly resetting table cell css class with cellFormat

### ISSUE THREAD

**Issue by Warkst** [edvin/tornadofx#888]
I'm using a dandy `cellFormat` to give cells conditional colors, but when the rows of the tableview are altered (e.g. by filtering), the empty cells keep their css classes. Judging from the code, changes have to be made to the implementation of `cellFormat` so the user can define some action in case the cell is reclaimed. Currently, we have:

```
fun <S, T> TreeTableColumn<S, T>.cellFormat(formatter: (TreeTableCell<S, T>.(T) -> Unit)) {
    cellFactory = Callback { column: TreeTableColumn<S, T> ->
        object : TreeTableCell<S, T>() {
            override fun updateItem(item: T, empty: Boolean) {
                super.updateItem(item, empty)

                if (item == null || empty) {
                    text = null
                    graphic = null
                } else {
                    formatter(this, item)
                }
            }
        }
    }
}
```
I suppose a solution could be to add a second callback with default value {} which is called in case item is null. If you agree, let me know and I'll cook up a PR.

**Comment by edvin** [comment]
Yeah, an optional callback for null items would be sweet!

**Comment by Warkst** [comment]
In light of #892, i'm closing this.
