### ISSUE TITLE
TableView smartResize ignores invisible columns

### ISSUE THREAD

**Issue by Warkst** [edvin/tornadofx#889]
I noticed that invisible columns (`isVisible = false`) are not taken into account when using `smartResize()` in a `TableView`. I want to leave the user the ability to show/hide columns (I have `isTableMenuButtonVisible` set to `true` for this reason) and I'd like the columns to auto resize to fit the table when a column is shown/hidden.
The behavior I'm after is achievable with using the constrained resize policy, though this doesn't respect `weightedWidth` settings or the width of the row expander column. Is this intended?

**Comment by edvin** [comment]
SmartResize doesn't consider invisible columns by design. If you show/hide columns however, SmartResize should kick in and perform a resize. If it doesn't, we should probably listen to column changes and call resize.

**Comment by Warkst** [comment]
It makes sense to me that SmartResize ignores hidden columns when doing its layout magic, but it is possible that columns that are set to invisible by default (inside the column builder block) are considered in its initial pass?

**Comment by Warkst** [comment]
Also I noticed I mixed up the constructor args for `Thang` (a maps to c and vice versa) - might I suggest that, when you use the IDEA option to "transform all properties to TornadoFX properties", the constructor args are kept (and stripped from things like val/var)? Right now the constructor arg list is cleared and needs to be re-added manually.

**Comment by edvin** [comment]
I've committed a fix for the resize issue, please try with latest head now :)

The IDEA plugin should know how to convert constructor parameters, and keep constructor args. Maybe a bug has sneaked in there :)

**Comment by Warkst** [comment]
Thanks Edvin, working perfectly 👍 

![image](https://user-images.githubusercontent.com/1039594/51249606-1930e600-1994-11e9-888a-f1f784cdfe71.png)
