### ISSUE TITLE
"lateinit property primaryStage has not been initialized"

### ISSUE THREAD

**Issue by radicaled** [edvin/tornadofx#89]
The class:
```kotlin
class NewDocumentDialog : Fragment() {
    override val root = HBox(Label("Hello world"))
}
```

The invocation:

```kotlin
// inside of a regular javafx controller
fun newFolder() {
    val ndd = NewDocumentDialog()
    ndd.openModal()
}
```

The error:

```
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property primaryStage has not been initialized
	at tornadofx.FX$Companion.getPrimaryStage(FX.kt:16)
	at tornadofx.UIComponent.openModal(Component.kt:128)
	at tornadofx.UIComponent.openModal$default(Component.kt:110)
	at com.radwriter.controllers.ApplicationController.newFolder(ApplicationController.kt:113)
```

**Comment by radicaled** [comment]
I'm trying to integrate tornadofx piecemeal into this existing project, so right now NewDocumentModal is the only piece of tornadofx-specific code in use.

**Comment by radicaled** [comment]
Looks like you can set `FX.primaryStage` inside of your existing `Application`-derived class and modals will work fine. This is probably a result of me not converting my application class to inherit from tornadofx's "App" yet. I'm trying to avoid a big wholesale rewrite, so for now this gets me going.

Sorry for any annoying emails this issue generated.

```
class OldFashionedApp : Application() {
  override fun start(primaryStage: stage {
     // ... (setup, icons, harvest festival, etc)
     // required to get modals working without converting OldFashionedApp to use tornadofx.App
     FX.primaryStage = primaryStage
   }
}
```

**Comment by edvin** [comment]
Hi Arron,

This is very interesting actually. It would be nice if TornadoFX could be used inside an existing application with minimal effort, so if we can do anything to make the transition easier please let me know.

TornadoFX requires minimal bootstrapping as you have noticed, so using it the way you do here is totally fine.

You might also want to assign `FX.dicontainer`if you use an existing dependency injection framework and would like to access beans from that in your new Views as you go along.

**Comment by edvin** [comment]
I added a convenience function to allow easier integration with existing apps and wrote a section about it in [the docs](https://github.com/edvin/tornadofx/wiki/Integrate-with-existing-JavaFX-Applications). This feature will be in TornadoFX 1.4.3 :)

Thanks again for reporting this, it just spawned significantly better "existing app integration"!

@thomasnield Something for the guide? :)

**Comment by edvin** [comment]
I made the integration even smoother, docs updated :)

**Comment by radicaled** [comment]
Cool, glad I could help in some way. :)
