### ISSUE TITLE
isEditable doesn't work for DatePicker

### ISSUE THREAD

**Issue by Y2Kot** [edvin/tornadofx#893]
```
datepicker(taskMenuModel.timeConstraints) {
                    isEditable = false
                    useMaxWidth = true
                    value = LocalDate.now()
                }
```

I'm trying to disable editing for datepicker, however it doesn't work

**Comment by Y2Kot** [comment]
Is any way to disable calendar button?

**Comment by edvin** [comment]
Not via a public API as far as I know. You might be able to hack it, but it wouldn't be future proof. If you don't need the button, you don't need DatePicker, so choose another control is my suggestion :)

**Comment by Y2Kot** [comment]
Ok, I tried to maximum simplified the form. However if it doesn't possible I'll make a property to check if this form is new or edit and substitute datepicker to textfield (they r more similar then label). Thanks for advice

**Comment by edvin** [comment]
My pleasure :)
