### ISSUE TITLE
togglebutton

### ISSUE THREAD

**Issue by thlinde** [edvin/tornadofx#896]
I can't use toggle button in version 1.7.18.

Kotlin: Overload resolution ambiguity: 
public fun EventTarget.togglebutton(text: ObservableValue<String>? = ..., group: ToggleGroup? = ..., selectFirst: Boolean = ..., value: Any? = ..., op: ToggleButton.() -> Unit = ...): ToggleButton defined in tornadofx
public fun EventTarget.togglebutton(text: String? = ..., group: ToggleGroup? = ..., selectFirst: Boolean = ..., value: Any? = ..., op: ToggleButton.() -> Unit = ...): ToggleButton defined in tornadofx

With version 1.7.17 there is no problem.

**Comment by edvin** [comment]
Please post your code :)

**Comment by thlinde** [comment]
Here is the example wich produces the error:

`
class MainView : View("Hello TornadoFX") {
override val root = hbox {
togglebutton {
isselected = true
}
}
}
`

When I do

`        togglebutton("") {
            isselected = true
        }
`

it works

In my real project I use it without the text-label and in version 1.7.17 it works without (""). Sorry, but I haven't realized that. It's no problem to change the code in my real project.
Thanks, Thomas.

**Comment by edvin** [comment]
Ah, we now have an overload where the `text` is an `ObservableValue<String>` to make binding easier, so you have to choose. Are you creating toggle buttons without a label? If so, your workaround should be just fine :)

**Comment by thlinde** [comment]
I'll do it with the empty string. Thanks again.

**Comment by HoldYourWaffle** [comment]
The example in the [guide](https://edvin.gitbooks.io/tornadofx-guide/content/part1/4. Basic Controls.html) still shows the (now broken) usage without parameters:

```
togglebutton {
    val stateText = selectedProperty().stringBinding {
        if (it == true) "ON" else "OFF"
    }
    textProperty().bind(stateText)
}
```

Since this "more idiomatic way to control the button" is now broken, what would be the current best approach?

**Comment by edvin** [comment]
Thanks for pointing that out. I guess we could always pull a Toni Braxton and unbreak the togglebutton:

```kotlin
fun EventTarget.togglebutton(
        group: ToggleGroup? = getToggleGroup(),
        selectFirst: Boolean = true,
        value: Any? = null,
        op: ToggleButton.() -> Unit = {}
) = ToggleButton().attachTo(this, op) {
    it.properties["tornadofx.toggleGroupValue"] = value
    if (group != null) it.toggleGroup = group
    if (it.toggleGroup?.selectedToggle == null && selectFirst) it.isSelected = true
}
```

I hate to duplicate that code, but that's the easy fix at least.
