### ISSUE TITLE
ToggleButton binding bug

### ISSUE THREAD

**Issue by Aqluse** [edvin/tornadofx#897]
Soon as I add 'bind'-call line, it works fine, except I can't change pressed/unpressed state from GUI
```
togglebutton("sometext"){
                    selectedProperty().bind(model.flag)
                }
```

**Comment by edvin** [comment]
You're explicitly telling it to bind unidirectional to the model.flag property. What you want to do is bind it bidirectionally:

```kotlin
togglebutton("sometext"){
    selectedProperty().bindBidirectional(model.flag)
}
```

**Comment by Aqluse** [comment]
@edvin oh sh~, sorry for my stupidity

**Comment by edvin** [comment]
Haha, not to worry, I can understand why you're confused. Most of the TornadoFX builders allow you to pass in a property in the builder constructor which will automatically be bound to the input. So most of the time you won't have to write that long incantation.
