### ISSUE TITLE
incapsulate a custom `ListCell`

### ISSUE THREAD

**Issue by voddan** [edvin/tornadofx#90]
I am trying to incapsulate a custom `ListCell` in a class. 

Now I have (btw, it works):
```
class MyListView(list: List<Int>): ListView<Int>() {
    init {
        items.addAll(list)
        
        setCellFactory { listView ->
            object : ListCell<Int>() {
                override fun updateItem(item: Int?, empty: Boolean) {
                    super.updateItem(item, empty)
                    if(item == null || empty) return

                    graphic = HBox().apply {.....}  // gonna incapsulate that in a UI element somehow 
                }
            }
        }
    }
}
```
I tried to create a `class ListItemView : View() {override val root = ...}`, but the problem is that `View` is somehow not a `Node`, so it is impossible to pass it there.

What is the recommended way?

**Comment by edvin** [comment]
A `View` has a `root` property of type `Node`. This `Node` can be inserted into any scene graph, but you need to remember that `View` is a singleton, so the `root` of a `View` should never go into a `ListCell`.

A `Fragemnt` however is "prototype" scoped, and can be used that way.

That said, I think you are going about this the wrong way. Normally, you would create a `View` and let the ListView be your `root` node. The above code would look like this using the type safe builders:

```kotlin
class MyListView(items: ObservableList<String>) : Fragment() {
    override val root = ListView<String>(items)

    init {
        root.cellFormat {
            graphic = HBox().apply { ... }
        }
    }
}
```

As you can see, the `cellFormat` function takes all the grunt work out of creating ListCells. You don't need to check if the item is null etc, just configure that text/graphic you want when there is an actual entry for the current cell.

I didn't quite grasp what you're trying to accomplish at the `graphic = ` line. Please elaborate, and I'll show you "the TornadoFX" way :)

**Comment by edvin** [comment]
I updated my answer above, hopefully this is what you're looking for :)

**Comment by voddan** [comment]
Thanks! Looks good!

The initial idea was that the `HBox().apply { ... }` is relatively complex, and may be reused in different list views, or even be displayed on its own.

**Comment by voddan** [comment]
not sure why I closed it. May you reopen it?
I still think that `Fragment` could be `Node` in some way

**Comment by edvin** [comment]
I understand why you feel that way, and I've contemplated it myself. However, that would completely remove the barrier behind the view (Node) and the view logic (code you put in the View/Fragment).

Having to write `graphic = fragment.root` vs ` graphic = fragment` is a small price to pay for that I think :)

**Comment by edvin** [comment]
There might be a way to arrange this via a delegate though.. Let me play with some ideas :)

**Comment by edvin** [comment]
By the way, for containers, you can use a much nicer syntax:

```kotlin
val hbox = HBox()
val myFragment = MyFragment()

hbox += myFragment
```
