### ISSUE TITLE
Replacing view with workspace

### ISSUE THREAD

**Issue by Warkst** [edvin/tornadofx#901]
I have a log in screen which I want to replace by a workspace when the log in is successful. Right now I start my `App` (not a `WorkspaceApp`, because I don't want workspace stuff in my log in screen!) with some log in view as default view, and try to replace it by my "main" workspace on successful log in with `replaceView`, but it seems like my workspace's `onBeforeShow` isn't being called. I'm guessing I'm either not doing it right (again haha) or I'm not supposed to switch a view to a workspace...

MVC:

```
package com.example.demo.app

import javafx.util.Duration
import tornadofx.*

class Issue901: App(BootView::class)

class LogInController: Controller() {
    private fun showMainView(){
//        find<BootView>().replaceWith(AfterBootWorkspace())
        find<BootView>().replaceWith(find<AfterBootWorkspace>())
    }

    fun spoofLogin(){
        println("Starting login spoof")
        runLater(Duration.seconds(1.0)) {
            println("\"Logged in\" ;)")
            showMainView()
        }
    }
}

class BootView: View("Booting") {
    private val loginController by inject<LogInController>()
    override val root = label("Hello Edvin")

    override fun onDock() {
        loginController.spoofLogin()
    }
}

class AfterBootWorkspace: Workspace("Booted") {
    override fun onBeforeShow() {
        println("OnBeforeShow")
        dock<SecretHideout>()
    }

    override fun onDock() {
        println("OnDock")
    }
}

class SecretHideout: View("Super Sikrit"){
    override val root = label("Where should I be docked?")
}
```

Note that when using the commented out method (i.e. manually instantiating the workspace rather than using `find`), the `onDock` callback isn't called either.

How would I do this properly?

Bonus round: how do I set my workspace as the "default" workspace (in the current scope)? I did: 

```
    init { scope.workspace = this }
```
in `AfterBootWorkspace`. Is that right?

**Comment by edvin** [comment]
If you configure the default workspace type, you can access the workspace from any view and simply show it when needed. To get rib of the boot screen, just hide it.

```kotlin
class IssueXa: App(BootView::class) {
    init {
        FX.defaultWorkspace = AfterBootWorkspace::class
    }
}

class LogInController: Controller() {
    val bootView: BootView by inject()

    private fun showMainView(){
        bootView.currentWindow?.hide()
        workspace.openWindow()
    }

    fun spoofLogin(){
        println("Starting login spoof")
        runLater(1.seconds) {
            println("\"Logged in\" ;)")
            showMainView()
        }
    }
}
```

Does that work the way you want it to?

**Comment by Warkst** [comment]
Yyyes, it does, perfect! I didn't know I could hide the primary window (stage?) without the app shutting down... If you'd indulge me, what exactly was wrong with my attempt? I would have expected it to work and I don't really understand why `replaceWith` didn't do what I wanted it to do. I'll go ahead and close this meanwhile, since the initial "issue" is addressed.

**Comment by edvin** [comment]
You can control what happens when you close the primary (or only) Stage with `Platform.setImplicitExit()`, but if you open a new window in the same pulse, you wouldn't exit anyway :)

`onBeforeShow()` is called on a UIComponent when the stage it is connected to is first shown. So this callback would have been delivered to your `BootView` when it was first shown. Replacing a root view for a Stage does not call `onBeforeShow` again, it wouldn't fit with the semantics of the callback :)

If you had moved the `dock<SecretHideout>()` call to `onDock` and done `bootView.replaceWith(workspace)` inside of `showMainView()` you would have gotten about the same result with two differences:

1. `onBeforeShow()` is not called
2. The window would not automatically resize to the space needed for the workspace

Pt 2 could be overcome by calling `workspace.currentStage?.sizeToScene()` in `showMainView()`.

Does that make sense?

**Comment by bekwam** [comment]
onDock() corresponds to the JavaFX Stage lifecycle "shown" which is when the OS window resources get allocated.  init{} is too early and certain things won't be there, most notably the Stage.  onBeforeShow() is too early also if you need to work with screen geometry,

**Comment by bekwam** [comment]
Here's an alternate approach where you can start with one View and transition to another View, closing the first.  The key is owner=null

````
class LoginView : View("Login") {

    override val root = vbox {
        label("Login")
        button("Login") {
            action {
                val w = find<ContentView>().openWindow(owner = null)
            }
        }
        prefHeight = 320.0
        prefWidth = 480.0
    }
}

class ContentView : View("Content") {

    override val root = vbox {
        label("Content here")

        prefHeight = 768.0
        prefWidth = 1024.0
    }

    override fun onDock() {
        find<LoginView>().currentStage!!.hide()
    }
}

class LoginDemo : App(LoginView::class)

fun main(args: Array<String>) {
    launch<LoginDemo>(args)
}
````

**Comment by Warkst** [comment]
I think I get it, though I'm still not sure as to why my old code which docked views inside `init` actually worked.
I did all my UI navigation using `replaceWith`, but I will start leveraging `openWindow` and `hide` to navigate between "app states" (i.e. not logged in, select a project, project editor) and limit `replaceWith` to switching the active editor within a single app state (if needed, because workspaces already provide practically all I need). The only place I still use `replaceWith` now, after some refactoring, is to fill in the detail part of a master-detail view for which the master consists of a treeview of heterogeneous items. Okay maybe this is a bit TMI, but thanks for all the help anyway :) :+1:

**Comment by edvin** [comment]
To be clear, there is absolutely nothing wrong with using `replaceWith`, but for top level windows you just have to be aware that it will not resize the window for you, and of course `onBeforeShow` is not called. That's not a big issue, you could just as well put your code in `onDock`. I would prefer to use `replaceWith` over closing and showing a new stage every time as long as it doesn't cause any problems :) If the top level UI changes dramatically it might be a good call to use close/hide, also so you can keep those hidden windows and show them again later if you need.
