### ISSUE TITLE
TableViewCell pseudoclass "selected" not set when installing custom cell factory

### ISSUE THREAD

**Issue by Warkst** [edvin/tornadofx#905]
I've added a custom cell factory to some of the columns of a table view and I found that the custom style classes I'm adding are working, though the `selected` pseudoclass is not. MVC:

```
import javafx.beans.property.SimpleStringProperty
import javafx.scene.control.TableCell
import javafx.util.Callback
import tornadofx.*

class TVApp : App(MV::class, MS::class)

class MV: View(""){
    override val root = tableview(observableListOf(DC("a1", "a2"), DC("b1","b2"))) {
        column("c1", DC::c1Prop)
        column("c2", DC::c2Prop).cellFactory = Callback {
            object : TableCell<DC, String?>() {
                val defaultStyleClass = listOf(*styleClass.toTypedArray())
                val defaultStyle = style
                override fun updateItem(item: String?, empty: Boolean) {
                    super.updateItem(item, empty)
                    if (item == null || empty) {
                        text = null
                        graphic = null
                        style = defaultStyle
                        styleClass.setAll(defaultStyleClass)
                    } else {
                        text = item
                        toggleClass(MS.a, item.contains('2'))
//                        togglePseudoClass(Stylesheet.selected.name, isSelected)
                    }
                }
            }
        }
    }
}

class DC(c1: String, c2: String) {
    val c1Prop = SimpleStringProperty(c1)

    val c2Prop = SimpleStringProperty(c2)
}

class MS : Stylesheet() {
    companion object {
        val a by cssclass()
    }

    init {
        a {
            backgroundColor += c("red")
            and(selected) {
                backgroundColor += c("green")
            }
        }
    }
}
```

I would expect that, if a row is selected, the background color of the selected row's cell in column "c2" is green, instead of red, but as you can see on the screenshot, this does not seem to happen:

![image](https://user-images.githubusercontent.com/1039594/51753055-2d25c780-20b9-11e9-9a87-c4e017fa4a7e.png)

I tried manually setting the pseudoclass as well, but it makes no different (I left the code in comment in the MVC).

Is something wrong with my code?

**Comment by Warkst** [comment]
I'm not sure how to solve this. I've tried implementing a class extending table cell rather than using an anonymous object and I've tried writing a custom pseudoclass and toggling that depending on `isSelected` inside the `updateItem` function, but neither did the trick. I'm especially confused because the style class is working, but the selected state isn't. With the debugger I was able to verify that the pseudo classes "even", "odd" and "filled" are set correctly, though. Do you have any suggested actions I could try?

**Comment by ruckustboom** [comment]
I'd recommend reading through `modena.css` to figure out what rule(s) result in that text color, and make yours match, with the addition of your class to make it more specific.

**Comment by Warkst** [comment]
And if I add 
```
    init {
        addPseudoClass("selected")
    }
```
to each `TableCell` instance that is created by my custom factory, I get:

![uhh](https://user-images.githubusercontent.com/1039594/51765472-222e5f80-20d8-11e9-8775-7c0112138ea1.png)

**Comment by Warkst** [comment]
I was able to get what I wanted by adding 
```
toggleClass(Stylesheet.selected, tableRow?.selectedProperty()?:SimpleBooleanProperty(false))
```

I discovered I needed to call `enableCellEditing` before table cells would have their selected state change, so I started looking into the direction of table row.
