### ISSUE TITLE
Documentation - Section 11 Editing Models and Validation fixes

### ISSUE THREAD

**Issue by dustincjensen** [edvin/tornadofx#907]
### Section - Introducing ViewModel

The class implementation of `PersonModel` does not seem to work at all at this point in the documentation. If you put a `var` on the person in the constructor, you can get it to compile, but it won't function correctly. I had to dig a bit further and find the `item` property and use `item = selectedPerson ?: Person()` in the rebind for the TableView.

### Section - OnCommit callback

The code example shows `override val onCommit(commits: List<Commit>) {` but should be `override fun onCommit`

Also your println's say "changed from newValue to oldValue". Minor, but you could saw the `findChanged` extension function to return the parameters in the opposite order, or change the println's in the `onCommit` override.

### Section - TableViewEditModel

The code sample for the `Customer` class has `SimpleStringPorperty`.

**Comment by edvin** [comment]
Thanks, I've pushed a fix for these now :)
