### ISSUE TITLE
Binding support

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#91]
Every Control has a property that represents the value of the component. The syntax for binding is a bit verbose, and in many cases sane defaults can reduce boilerplate considerably.

Examples before special binding support:

```kotlin
val name = SimpleStringProperty()
val age = SimpleDoubleProperty(42.0)

// Bind name readwrite to textfield
textfield.textProperty().bindBidirectional(name)

// Bind name readonly to textfield
textfield.textProperty().bind(name)

// Bind age to textfield
textfield.textProperty().bindBidirectional(age, NumberStringConverter())
```

Examples with proposed binding support:

```kotlin
// Bind name readwrite to textfield
textfield.bind(name)

// Bind name readonly to textfield
textfield.bind(name, true)

// Bind age to textfield, converter extracted from type of 'age'
textfield.bind(age)

// Bind age to textfield, custom converter
textfield.bind(age, converter = myCustomConverter)
```

You no longer need to keep track of what property inside the control is representing the value. Consider CheckBox:

```kotlin
val chosen = SimpleBooleanProperty()

// Without binding support
checkbox.selectedProperty().bindBidirectional(chose)

// With binding support
checkbox.bind(chosen)
```

**Comment by edvin** [comment]
Please take a look at the implementation, comments and suggestions are welcome!

https://github.com/edvin/tornadofx/blob/master/src/main/java/tornadofx/Binding.kt

**Comment by picoworm** [comment]
cool!

**Comment by edvin** [comment]
I'm wondering if the boolean parameter to specify readonly or readwrite is a bit confusing. Maybe we should introduce an enum? `enum class BindingMode { RO, RW }` and default it to `RW`?

```kotlin
// ReadWrite via default
textfield(bind)

// ReadWrite explicitly
textfield(bind, RW)

// ReadOnly
textfield(bind, RO)
```

Alternative enum names could be `ReadOnly/ReadWrite`. Any feelings or input?

**Comment by t-boom** [comment]
I think the Boolean is fine. One nice advantage of Kotlin is you could simply say
``` kotlin
textfield.bind(property, readonly = true)
```
if you want to be extra clear.

**Comment by edvin** [comment]
That's a good point @t-boom :) I'll close this for now.

**Comment by thomasnield** [comment]
I was just thinking about this subconsciously this morning. Good initiative.

**Comment by edvin** [comment]
I think it turned out quite good. I wanted to do something with the `fxid` delegate to somehow do the binding at the same time, but I don't think it's possible with a delegate.

Dream:

```kotlin
class CustomerEditor(val customer: Customer) : Fragment() {
    override val root: Node by fxml()
    val nameField: TextField by fxid(customer.nameProperty())
}
```

It could however be done by using a function instead of a delegate:

```kotlin
class CustomerEditor(val customer: Customer) : Fragment() {
    override val root: Node by fxml()
    val nameField = getAndBind("nameField", customer.nameProperty())
}
```

But that's ugly :(

**Comment by t-boom** [comment]
Could you not just have `fxml()` accept both a `String?` and a `Property<*>?`? Then, after the `value = xmlLoader!!.load()` line you could bind it. There would be a lot of branches, but you could try something like

``` kotlin
when (value) {
    is DatePicker -> { value.bind(property) }  // Probably need to check if property is Property<LocalDate>
}
```

**Comment by edvin** [comment]
The `fxml` is "once per view` and refers to the FXML document. The `fxid` is once per component you look up from the loaded FXML.

The `fxml` loads immediately, while the `fxid` properties are only consulted if they are ever referenced in the View code.

There might be a way to store the ref in the `fxid` delegate and retrieve it after the view has loaded though.

**Comment by t-boom** [comment]
Ah, I read that completely wrong. That makes a lot more sense now.

**Comment by edvin** [comment]
Haha, OK :) I will play with this a little more, but if I can't find a better solution, I'm happy for now.
