### ISSUE TITLE
node.viewOrder() alternative ?

### ISSUE THREAD

**Issue by Balthov60** [edvin/tornadofx#912]
Hi!

I am currently working on an application and I'd like to use a "z-index" concept like without using a StackPane. After quick search I saw that javafx 9 added Node.viewOrder() but it isn't currently implemented in TornadoFx. So I'd like to know if there is an other way to achieve it or if you planned to implement it in a near future? 

Thanks for your time!

**Comment by ruckustboom** [comment]
There's no alternative. When TornadoFX gains JavaFX 11 support, `viewOrder` will come along with it. In the meantime, there's no way around it other than to manually adjust children orders.

**Comment by yay** [comment]
Is there any ongoing work on JavaFX 11 support?

**Comment by edvin** [comment]
It's basically done, just needs more testing. Please check out the jdk10 branch and try it against your projects if you can.

**Comment by edvin** [comment]
Great! I'm working on converting a large CRM app to the jdk11 version myself. It will give a strong indicator about readyness. In any case we'll do a RC soon.

**Comment by Balthov60** [comment]
Thanks for your answers ! I'll try with the jdk10 branch !
