### ISSUE TITLE
style property not can be used with css variables from another libs

### ISSUE THREAD

**Issue by MairwunNx** [edvin/tornadofx#915]
I have library JMetro, what resolve self css variables, "`accent_color`", "`background_color`" and etc

```
            pane {
                this.style = "-fx-background-color: accent_color"
                this.maxHeight = 65.0
                this.minHeight = 65.0
            }
```

But when i try apply value to my pane or another element i get error

```
Feb 07, 2019 3:27:04 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve 'accent_color' while resolving lookups for '-fx-background-color' from inline style on Pane@2e7df5a1

Feb 07, 2019 3:27:04 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve 'JMETRO_BLUE' while resolving lookups for '-fx-background-color' from inline style on Pane@2e7df5a1
```

`JMETRO_BLUE` it's value of variable `accent_color`, what contains color, i.e `JMETRO_BLUE: #111`

**Comment by edvin** [comment]
This doesn't appear to be related to TornadoFX, as you're just setting an unsafe string into the `style` property of a Pane. I suspect you'd get the exact same issue in a plain JavaFX app. I don't have any experience with JMetro, but I would think somebody in the JMetro community can point you towards a solution :)

**Comment by MairwunNx** [comment]
@edvin  I help the developer JMetro, and I saw that the problem is really in JMetro, it does not load the necessary css files, I realized when I checked them

```
        stage.scene.root.stylesheets.forEach {
            println(it)
        }
```

Thanks, sorry for not correct issue

**Comment by edvin** [comment]
Great, thanks for reporting back :)
