### ISSUE TITLE
Straight copy and paste from guide not working

### ISSUE THREAD

**Issue by robert-cronin** [edvin/tornadofx#916]
I'm sure this is just my lack of understanding so please enlighten me on my mistake if there is one. The example at the end of part 11 in the guide is not allowing edits to the model, this is the code I tried:
```
import tornadofx.*

class MyApp: App(MyView::class)
class MyView : View("My View") {

    val controller: CustomerController by inject()
    var tableViewEditModel: TableViewEditModel<Customer> by singleAssign()

    override val root =  borderpane {
        top = buttonbar {
            button("COMMIT").setOnAction {
                tableViewEditModel.commit()
            }
            button("ROLLBACK").setOnAction {
                tableViewEditModel.rollback()
            }
        }
        center = tableview<Customer> {

            items = controller.customers
            isEditable = true

            column("ID",Customer::idProperty)
            column("FIRST NAME", Customer::firstNameProperty).makeEditable()
            column("LAST NAME", Customer::lastNameProperty).makeEditable()

            enableCellEditing() //enables easier cell navigation/editing
            enableDirtyTracking() //flags cells that are dirty

            tableViewEditModel = editModel
        }
    }
}

class CustomerController : Controller() {
    val customers = listOf(
            Customer(1, "Marley", "John"),
            Customer(2, "Schmidt", "Ally"),
            Customer(3, "Johnson", "Eric")
    ).observable()
}

class Customer(id: Int, lastName: String, firstName: String) {
    val lastNameProperty = SimpleStringProperty(this, "lastName", lastName)
    var lastName by lastNameProperty
    val firstNameProperty = SimpleStringProperty(this, "firstName", firstName) 
    var firstName by firstNameProperty
    val idProperty = SimpleIntegerProperty(this, "id", id) 
    var id by idProperty
}
```
It is just reverting back to the original data whenever I try to edit or commit the model.
I am on tornadofx version 1.7.17

**Comment by edvin** [comment]
I just ran that exact code, it seems to work fine. What is not working for you? Both edit/commit/rollback seems to work as it should.

**Comment by robert-cronin** [comment]
hmm I'm not sure, I will try to run it again from a fresh project

**Comment by robert-cronin** [comment]
I am still not able to change anything on the table, this what I am seeing:
![test](https://user-images.githubusercontent.com/8540764/52840014-f29cd100-3132-11e9-90d7-c6b858004a39.gif)

**Comment by edvin** [comment]
That's because you cancel the edit by clicking outside the cell instead of hitting enter to commit the edit event. I agree that this might be confusing, and that other frameworks allow you to keep the edit when clicking outside the cell, but unfortunately that's not how JavaFX does it.

**Comment by robert-cronin** [comment]
ahh that makes sense! is there any workaround to bind a custom event to commit, like exiting the cell?

**Comment by edvin** [comment]
Yes, it is possible, but I don't think we have a sweet workaround in the framework. I found some solutions in this SO post:

https://stackoverflow.com/questions/23632884/how-to-commit-when-clicking-outside-an-editable-tableview-cell-in-javafx

It would be a nice addition to have a simple function call to configure this behavior for sure.

**Comment by robert-cronin** [comment]
Thanks Edvin, I'll look into it and post back if I find anything useful

**Comment by edvin** [comment]
Perfect, thanks :)
