### ISSUE TITLE
The [link](https://tornadofx.io/felix-bundle.zip) to the zip file containing the OSGi bundles is broken.

### ISSUE THREAD

**Issue by npatelksy** [edvin/tornadofx#917]
getting error page on clicking "Download OSGi Bundle" 

Error Message : 
java.io.FileNotFoundException: http://www-eu.apache.org/dist/felix/org.apache.felix.main.distribution-6.0.1.zip
	sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
	sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	java.net.URL.openStream(URL.java:1038)
	io.tornadofx.admin.felix.FelixDownloadServlet.doGet(FelixDownloadServlet.kt:43)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	io.tornadofx.admin.RedirectFilter.doFilter(RedirectFilter.kt:22)

**Comment by edvin** [comment]
Fixed :) The way I've set it up I have to update versions whenever they change in the felix repo. Quite brittle, but I haven't gotten around to checking for the available version instead. The code that handles this is here:

https://github.com/edvin/tornadofx-web/blob/master/src/main/java/io/tornadofx/admin/felix/FelixDownloadServlet.kt

If anybody wants to improve this to detect the version available from http://www-eu.apache.org/dist/felix/ that would be most welcome :)

**Comment by ctadlock** [comment]
Closing
