### ISSUE TITLE
View is losing event subscriptions upon onUndock

### ISSUE THREAD

**Issue by Keelar** [edvin/tornadofx#918]
After looking at the Component class for a bit, this seems to be the intended behavior, but I'll try to explain my issue.

My application currently has two stages, both of which have an abstract `LockableView` class as the scene root. The purpose of this class is to provide a dimmed(dark and transparent) overlay along with a message which prevents interacting with other UI elements under it when the window is waiting for an input.

This class subscribes to two events, `LockRequest` and `UnlockRequest`, which obviously enables or disables the overlay. My issue is that it works as expected when the application initially runs, but after closing the application to the system tray(using the provided trayicon function in the Application class), onUndock gets called which causes the `LockableView`s to remove their subscriptions. After redisplaying the application, firing the `LockRequest` and `UnlockRequest` events does nothing because the `LockableView`s lost their subscriptions.

Am I going about this whole 'lockable' stage thing wrong from a design perspective? Am I misusing events? Or is something else going on here? Any help would be appreciated.

**Comment by edvin** [comment]
I'm not sure I understand why this becomes a problem. Wouldn't you set up the subscription in onDock, so even if onUndock unregisters it, you would resubscribe if the window is shown again?

Alternatively, you don't need to close the screen when you minimize to the systray, you could just hide it.

Perhaps you can post a minimal sample app so we can look at how you're approaching this?

**Comment by Keelar** [comment]
I do register them in onDock(), but for some reason onDock() is never called when the stage is reshown after minimizing to the system tray. So when I minimize to the system tray onUndock() gets called but onDock() never gets called when I show the primary stage again.

I will try to setup a minimal application later that demonstrates the issue.

**Comment by edvin** [comment]
I believe ondock should not be called, because the view is not undocked if you simply hide it. Curious to see why undock is called though.

**Comment by Keelar** [comment]
This reproduces the issue for me:

    class Application : App(MainView::class) {
        override fun start(stage: Stage) {
            super.start(stage)

            trayicon(resources.stream("/icon.png"), "Test application") {
                fun show() {
                    FX.primaryStage.show()
                    FX.primaryStage.toFront()
                }

                setOnMouseClicked(fxThread = true) {
                    show()
                }

                menu("Test application") {
                    item("Show...") {
                        setOnAction(fxThread = true) {
                            show()
                        }
                    }

                    item("Exit") {
                        setOnAction(fxThread = true) {
                            Platform.exit()
                        }
                    }
                }
            }
        }
    }

    class MainView : View() {
        override val root = button("Test button") {}

        override fun onDock() {
            println("onDock()")
        }

        override fun onUndock() {
            println("onUndock()")
        }
    }

    fun main() {
        launch<Application>()
    }

When 'closing' the application onUndock() gets called but onDock() never gets called after showing it again.

**Comment by edvin** [comment]
I found that the onUndock is called because of a special case performed on line 527 in Component.kt. To get an onDock callback as well, we could change it like this:

```kotlin
runLater {
    if (!it && isDocked) callOnUndock()
    if (it && !isDocked) callOnDock()
}
```

This might have unwanted side effects, and I'm currently on vacation abroad/unable to verify.

**Comment by Keelar** [comment]
I just tested that out and one side effect is that callOnDock gets called twice on start, once when the stage is shown and once during application start in App.kt starting at line 97:

    if (view !is NoPrimaryViewSpecified && shouldShowPrimaryStage()) show()
    view.callOnDock()

 I was able to fix that by only invoking callOnDock during application start if the stage is not shown since it'll be called by the showingProperty listener:

    if (view !is NoPrimaryViewSpecified && shouldShowPrimaryStage())
        show()
    else
        view.callOnDock()

All tests still pass. Do you see any potential issues that my changes don't consider? If it looks good should I create a pull request? This would be my first open source contribution so if I'm doing anything wrong just point me in the right direction.

No rush obviously since you're on vacation and can't verify it right now.

**Comment by edvin** [comment]
I can't find any issues with it, so I merged now. Will test some more before release though :)
