### ISSUE TITLE
mail lists needed - dev and user

### ISSUE THREAD

**Issue by ph-hs** [edvin/tornadofx#92]
Suggest GoogleGroups, which does a reasonable job of protecting email addresses of senders, and marshaling spam into a quarantine place.

In order to move to mainstream usage, TornadoFX needs mail lists. Issues (like this one), PRs, and tweets are a poor place to collaborate, and that also be a record for posterity.  In particular dialectic discussion that proceeds action, just can't be done that way.  If there's a dev team that can look above a desk partition to discuss things, that's all well and good, but it's a walled garden that is a huge barrier to other participating.  

For example, the AngularJS mail archives go back to 2009 - https://groups.google.com/forum/#!searchin/angular/hammant$202009/angular/665HQTQ24BA/Ft9u5hDC56AJ

- Paul

**Comment by edvin** [comment]
Hi Paul,

Thanks for explaining and elaborating on this. I totally agree with your assessment. I will get the mailing list up and running and report back here!

**Comment by ph-hs** [comment]
:-)

**Comment by edvin** [comment]
Looking at it now. I don't have much experience with Google Groups. I wonder if the web forum mode would be a good fit for TornadoFX. Do you have any insight? :)

**Comment by edvin** [comment]
Ah, it looks like the modes are mostly a template for selecting different options. Will set it up now :)

**Comment by ph-hs** [comment]
You're gunna get the web forum for free - my personal focus would be the SMTP side of it :)

**Comment by edvin** [comment]
Groups created:

[TornadoFX User Forum](https://groups.google.com/forum/#!forum/tornadofx)
[TornadoFX Dev Forum](https://groups.google.com/forum/#!forum/tornadofx-dev)

Thanks again, @ph-hs :)
