### ISSUE TITLE
What's the proper way of using Exposed with ViewModel?

### ISSUE THREAD

**Issue by Defman21** [edvin/tornadofx#921]
I tried to bind properties of the VM to the ODA representing the table (`val id = bind(User::id)` etc), but whenever I commit my changes (`model.commit()`), I receive an error that tells me that I'm trying to change a model outside of a transaction.  I didn't find any examples on how to make these two work together. 

I thought about creating a data class that will act as a proxy between the model and the VM.
The idea is to bind the VM to the data class and when the VM changes the data class, it reflects the changes in a transaction, but it sounds very hacky. Perhaps there's another way to achieve that?

**Comment by Defman21** [comment]
Okay, I made a function that just wraps `for (facade in commitThese)` loop in a `transaction` block and that works.

@edvin perhaps there should be a way to somehow override `.commit` behavior (it's `final` atm), or add an argument that will wrap the loop.

**Comment by edvin** [comment]
It sounds like what you need is just a way to wrap the commit functionality in a transaction, right? If so, we could just let you configure a commit wrapper function, and even configure a default function so you don't need to specifically call `transaction {}` for every domain object. What do you think?

**Comment by Defman21** [comment]
Yes, that's what I need.

**Comment by edvin** [comment]
OK. Does `transaction` take any parameters or does it return anything? Can you show me the signature of this function?

**Comment by Defman21** [comment]
```kotlin
fun <T> transaction(db: Database? = null, statement: Transaction.() -> T): T = transaction(TransactionManager.manager.defaultIsolationLevel, TransactionManager.manager.defaultRepetitionAttempts, db, statement)


fun <T> transaction(transactionIsolation: Int, repetitionAttempts: Int, db: Database? = null, statement: Transaction.() -> T): T {
```

You can return pretty much anything from it, I guess.

**Comment by Defman21** [comment]
The reason I wanted to move the `prop.value = facade.value` to a dedicated function is because I don't think there's a way to write a type-safe argument that would accept any function literal (they all have different arguments, etc.), but there's a way to write a function that will accept a list of commits so you can manipulate on them using any functions/literals. But I'm not that familiar with Kotlin, so I might be wrong.

I just want something like `onCommit` which will be called to **do** the commit. That would give me much more control than an argument that will be used as a wrapper to the commit mechanic.

**Comment by edvin** [comment]
So you could really just add save() function to your domain objects and do the work there then?

**Comment by Defman21** [comment]
`commit` changes `prop.value` which causes my ORM to panic because it happens outside of a transaction, so no, I can't do that. Or do you mean that I should not call `commit` at all and write my own implementation of assigning new values to the `propertyMap` of a view?

**Comment by edvin** [comment]
I’m suggesting that you add a save function which does transaction { commit() }. Wouldn’t that work?

**Comment by Defman21** [comment]
Nope :( The only way is to wrap the for loop, where the actual assignments are.

**Comment by edvin** [comment]
Why?

**Comment by Defman21** [comment]
I don't know, that's how Exposed works I guess.

**Comment by edvin** [comment]
What is the exact issue you run into if you wrap transaction around commit? In any case, it would not be a good solution to save directly to the db while committing, as the commit has to happen on the UI thread, and that’s no place for external io. Perhaps a DTO is better for you, if you could find a way to integrate it in the domain object perhaps.

**Comment by bekwam** [comment]
Maybe this save() implementation can help?  I keep a record of changes and then when the user finishes the edit, the backend call is made.  All of the accrued actions can be in the same transaction.  A real-world save() would be in a Task (runAsync / ui).

https://courses.bekwam.net/public_tutorials/bkcourse_tornadofx_journalingapp.html

**Comment by Defman21** [comment]
>What is the exact issue you run into if you wrap transaction around commit?

An exception that tells me I cannot change a model outside of a transaction.

>In any case, it would not be a good solution to save directly to the db while committing, as the commit has to happen on the UI thread.

Why should it happen on the UI thread though? I run my commits via `runAsync`.

>Perhaps a DTO is better for you, if you could find a way to integrate it in the domain object perhaps.

Do you mean something like this?

```kotlin
class Entity : SomeDBEntity

data class EntityDTO {
  val nameProperty = SimpleStringProperty()
  var name by nameProperty

  fun save() {
    async save to db
  }
}

class EntityModel {
  val name = bind(EntityDTO::nameProperty)
}

// somewhere in the code

model.commit()
model.item.save()
```

?

**Comment by Defman21** [comment]
> Maybe this save() implementation can help? I keep a record of changes and then when the user finishes the edit, the backend call is made. All of the accrued actions can be in the same transaction. A real-world save() would be in a Task (runAsync / ui).
> 
> https://courses.bekwam.net/public_tutorials/bkcourse_tornadofx_journalingapp.html

I'll look into it, thanks.

**Comment by Defman21** [comment]
I achieved what I wanted! Thanks @edvin and @bekwam :)

Here's the implementation.

```kotlin
object Entries : IntIdTable() {
    val name = varchar("name", 200).index()
    val password = varchar("password", 4096)
}

class Entry(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Entry>(Entries)

    var name by Entries.name
    var password by Entries.password
}

data class EntryDTO(val entry: Entry) {
    val nameProperty = SimpleStringProperty(entry.name)
    var name by nameProperty

    val passwordProperty = SimpleStringProperty(entry.password)
    var password by passwordProperty

    fun save() {
        transaction {
            entry.name = name
            entry.password = password
        }
    }

    fun delete() {
        transaction {
            entry.delete()
        }
    }
}

class EntryModel : ItemViewModel<EntryDTO>() {
    val name = bind(EntryDTO::nameProperty)
    val password = bind(EntryDTO::passwordProperty)
}
```

On the UI side, I'm doing `runAsync { Entry.all().map { EntryDTO(it) } } ui { items = it }` and display it in a list view.
