### ISSUE TITLE
importStylesheet for resources files not work??

### ISSUE THREAD

**Issue by coyool** [edvin/tornadofx#922]
maybe my mistake?

>         
        val f = File("D:\\KtCode\\tornadofx-samples\\kfx01\\resources\\aaa.css")
        print("absolutePath = ${f.absolutePath}\r\n")
        print("readText = ${f.readText()}\r\n")
        importStylesheet(f.absolutePath)
> 
二月 20, 2019 8:09:55 下午 tornadofx.FXKt importStylesheet
警告: Unable to find stylesheet at D:\KtCode\tornadofx-samples\kfx01\resources\aaa.css - check that the path is correct

**Comment by coyool** [comment]
when I load from http url , it woks perfect
        importStylesheet("http://127.0.0.1:8066/aaa.css")

**Comment by edvin** [comment]
`importStylesheet` requires a url string, not a file path, so you can do like this:

```kotlin
val f = Paths.get("D:\\KtCode\\tornadofx-samples\\kfx01\\resources\\aaa.css")
importStylesheet(f.toUri().toURL().toExternalForm())
```

But referring to a file on your local filesystem doesn't make much sense in a portable application, and it seems you already have this file in your resource folder inside our project folder, so instead you can simply do `importStylesheet("/aaa.css")`, provided that your `resources` folder is copied to your target (would be default in most build systems).

**Comment by lazaronixon** [comment]
Not working here too.. 
Unable to find stylesheet at /fonts/poppins.css - check that the path is correct

src/main/resources/fonts/poppins.css
```
importStylesheet("/fonts/poppins.css")
```
