### ISSUE TITLE
Async function background clashes with Region.background

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#93]
I ran into a problem where it became impossible to invoke a function asynchronously because the call to `background` would clash with the `Region.background` getter:

```kotlin
    override val root = VBox()

    init {
        with(root) {
            hbox {
                button("Login") {
                    setOnAction {
                        background {  // Compile error
                        }
                    }
                }
            }
        }
    }
```

You can always call a function to do the background work (and you probably should), but this got me thinking of wether `background` is the best word for invoking async operations. I wanted to use `async` initially, but that's reserved.

Should we leave this as is or introduce another name for `background` and possibly deprecate the old?

**Comment by thomasnield** [comment]
I say rename and deprecate.

**Comment by edvin** [comment]
PS: This only happens in SingleViewApp, not in a View. Do you have suggestions for a better name?

**Comment by thomasnield** [comment]
backgroundAsync(), runAsync() ?

**Comment by edvin** [comment]
I like `runAsync`. It matches our `runAndWait`.

**Comment by edvin** [comment]
Thanks for the input Thomas :) Added runAsync and deprecated background. It will give a nice explanatory compiler warning now :)

**Comment by thomasnield** [comment]
Awesome!
