### ISSUE TITLE
Create function for creating list bindings

### ISSUE THREAD

**Issue by LittleLightCz** [edvin/tornadofx#930]
Analogically to `stringBinding(...) {}` I would find a use for creating an `ObservableList` binding which reacts on any number of observable lists or values. It could be named e.g. `listBinding` and my use case is a filtered list which reacts both to original list changes as well as filter changes.

Pseudo code:
```kotlin
val original = mutableListOf<String>().observable()
val filter = SimpleStringProperty("")

val filtered: ObseravebleList<String> = listBinding(original, filter) {
    if (filter.get().isBlank()) this else filter { filter.get() in it }
}
```

**Note:** There is already `SortedFilteredList` (https://github.com/edvin/tornadofx/wiki/Utilities), but it doesn't follow the "chained data flow" convention as I am used with what `ObservableValue` has. It would be nice to unite these approaches for `ObservableList` as well.

**Comment by edvin** [comment]
I'm not sure it would make sense to return an `ObservableList<String>` in your use case, remember that kind of list is also mutable. I can't think of a use case for that. However, you can create a binding, maybe something like `objectBinding(original, filter)  {}` does what you want?

**Comment by LittleLightCz** [comment]
Thanks Edvin, I've done a little test now and noticed that both `listview {}` and `tableview {}` can take `ObservableValue<ObservableList<T>>` as a parameter too. However there was one trick - I was getting compilation error until I discovered I have to use `nonNullObjectBinding` instead :grin: . So for anyone who might stumble across this issue, this is the example code that seems to work perfectly:

```kotlin
class TestView : View() {
    private val original = listOf(1,2,3,4,5).observable()
    private val filter = SimpleStringProperty("")

    private val filteredList = nonNullObjectBinding(original, filter) {
        if (filter.get().isBlank()) this
        else filter { it == filter.get().toIntOrNull() ?: 0 }.observable()
    }

    override val root = vbox {
        textfield(filter)
        listview(filteredList)
    }

}

class TestApp : App(TestView::class)

fun main() {
    launch<TestApp>()
}
```

I haven't tried mutating the `original` list, but I believe it would work too :relaxed:

**Comment by edvin** [comment]
Perfect. Thanks for sharing your code :)
