### ISSUE TITLE
Overwrite default form values on file load

### ISSUE THREAD

**Issue by mcred** [edvin/tornadofx#932]
I've tried this a few different ways based on other issues and sample projects, but I can't seem to get thing wired correctly. I have a form set up in a View bound to a data model. I'd like to overwrite the default values when a file is loaded. If that's not the best or recommended solution, what would be the best way to create a data model, attach it to a form for viewing and editing, and populate that data model from a file service/static file?

```kotlin
class StatsView : View("My View") {
    private val ctrl: StatsController by inject()
    private val stats = StatsModel(ctrl.stats.first())

    override val root = form {
        fieldset("Character Stats") {
            field("HP") {
                textfield(stats.hp)
            }
        }
    }
}
```

```kotlin
class StatsController: Controller() {
    val stats = FXCollections.observableArrayList<Stats>()

    init {
        stats.add(Stats(0))
    }
}
```

```kotlin
class Stats(){
    constructor(hp: Int): this() {
        this.hp = hp
    }

    val hpProperty = SimpleIntegerProperty()
    var hp by hpProperty
}

class StatsModel(stats: Stats? = null) : ItemViewModel<Stats>(stats) {
    val hp = bind(Stats::hpProperty)
}
```

```kotlin
//FileService.kt
    fun openFile(targetFile: File? = null) {
        val file: File = when (targetFile) {
            null -> getFile() ?: return
            else -> targetFile
        }

        try {
            val saveFile = File(file.toString()).inputStream()
            val card = Card.load(file.toString(), saveFile)
            println(card.slots[1])
            //This is where I fail to overwrite the default values. This code does not work.
            val ctrl: StatsController by inject()
            val stats = StatsModel(ctrl.stats.first())
            stats.hp.setValue(12)
        } catch (e: Exception) {
            println(e)
        }
    }
```

**Comment by edvin** [comment]
You can only use `inject` to assign to properties, so either add `val ctrl` and `val stats` as class members, or use `find` to locate them. Creating a new model will not magically make it into the model you created in your View, this would be a new instance, so there is no way for the binding to update.

What you should do instead is to explicitly create the StatsModel and push it into the Scope, and then use inject or find to get access to that instance.

**Comment by mcred** [comment]
Is there an example of that anywhere in the [Samples Repo](https://github.com/edvin/tornadofx-samples) or another issues that covers this? I've been reading through them and they are helpful. I'm familiar with DI, so creating the StatsModel first and then pushing it into the Scope makes sense, but the syntax for TornadoFX is new to me. 

I did have a thought to create the FileService as a Component(), but `object FileService: Component() ` had issues when using `val ctrl: StatsController by inject()`. I has a `Type inference failed.` error.

**Comment by mcred** [comment]
I think I found it. Would the "Keeping State in Scopes" section of the [Tornado FX Guide](https://edvin.gitbooks.io/tornadofx-guide/content/part2/Scopes.html) be what I'm looking for?

**Comment by mcred** [comment]
Thank you! I was able to get it to work. I was very close and adding the scope was the final piece. For those that want to know, here is how the solution looks:

```kotlin
class Stats(){
    constructor(hp: Int): this() {
        this.hp = hp
    }

    val hpProperty = SimpleIntegerProperty()
    var hp by hpProperty
}

class StatsModel(stats: Stats? = null) : ItemViewModel<Stats>(stats) {
    val hp = bind(Stats::hpProperty)
}

class StatsScope : Scope() {
    val stats = StatsModel()
}
```

```kotlin
object FileService: Component() {
    private val statsCtrl: StatsController by inject()
    private val stats = statsCtrl.stats

    fun openFile() {
        try {
            stats.hp.setValue(12)
        } catch (e: Exception) {
            println(e)
        }
    }
}
```

```kotlin
class StatsController: Controller() {
    val statsScope = StatsScope()
    val stats = statsScope.stats

    init {
        stats.hp.setValue(0)
    }
}
```

```kotlin
class StatsView : View("My View") {
    private val statsCtrl: StatsController by inject()
    private val stats = statsCtrl.stats

    override val root = form {
        fieldset("Character Stats") {
            field("HP") {
                textfield(stats.hp)
            }
        }
    }
}
```

When the form is initially rendered, the value for HP is 0, but when the file is loaded it will update to 12 as expected.
