### ISSUE TITLE
Add function builders/factories for all SimpleXXXProperty classes

### ISSUE THREAD

**Issue by LittleLightCz** [edvin/tornadofx#933]
**Proposal:** When I declare my properties in a View, I find the starting word *Simple* quite annoying and unaesthetic. For example:

```kotlin
private val name = SimpleStringProperty("")
```

I wanted to use `StringProperty`, but it's abstract. So I was thinking, wouldn't it be a good idea to add function builders/factories for all SimpleXXXProperty classes, so that we could define our properties in a much simpler way, e.g.:

```kotlin
private val name = stringProperty("")
```

Where example implementation would be just:

```kotlin
fun stringProperty(value: String) = SimpleStringProperty(value)
```

Or maybe (since the functions will start with lowercase) we could go even further and simplify it as extremely as:

```kotlin
private val name = string("")
private val age = int(10)
```

But in this case I am not sure there won't be any naming collisions with something else - this is up to be discussed.

What is your opinion about this?

**Comment by LittleLightCz** [comment]
Ah, the `object()` would collide with `object` keyword in Kotlin. Unless it would be called e.g. `any()`, but that would break naming consistency with `SimpleObjectProperty`. So perhaps the form of `objectProperty()` is in play now, but if it was me, I wouldn't mind `any()` as far as that is concerned :laughing:

**Comment by edvin** [comment]
`stringProperty` and friends is a good idea, also because it matches our existing collection builders. You want to create a PR?

**Comment by LittleLightCz** [comment]
Great :-). Ok, I will look at it probably tomorrow and submit a PR when
done.
