### ISSUE TITLE
Restrict form field to Integers with range limit

### ISSUE THREAD

**Issue by mcred** [edvin/tornadofx#934]
How can you restrict a field to only accept Integers and then limit the range of accepted inputs? For instance, how would you create a form field for an 8bit value, only accept integers as input and restrict the range from 0-255? 

This mock code, but I think illustrates the basics of my question:
```kotlin
field ("8bit") {
    intfield { boundproperty, lowerLimit = 0, upperLimit = 255}
}
```

This is an html example:
```html
<form action="/submit">
  <input type="number" name="quantity" min="1" max="5"><br>
  <input type="submit">
</form>
```

**Comment by edvin** [comment]
You could add a custom filterInput to take care of this:

```kotlin
filterInput { change ->
    !change.isAdded || change.controlNewText.let {
        it.isInt() && it.toInt() in 0..255
    }
}
```

Your HTML example doesn't restrict the input, it merely validates it to be within the range. If that's what you want you should instead use a `validator` of course :)

**Comment by mcred** [comment]
That'll do it. Thank you!

**Comment by mcred** [comment]
How could the filterInput be parameterized so that it could be reusable?

```kotlin
field ("8bit") {
    textfield {
        filterInput {
            change -> !change.isAdded || change.controlNewText.let {
                it.isInt() && it.toInt() in 0..255
            }
        }
    }
}
```
to something like
```kotlin
val 8BitFilter =  change -> !change.isAdded || change.controlNewText.let {
                it.isInt() && it.toInt() in 0..255
            }
field ("8bit") {
    textfield {
        filterInput {8BitFilter}
    }
}
```

**Comment by edvin** [comment]
```kotlin
val EightBitFilter: (TextFormatter.Change) -> Boolean = { change ->
    !change.isAdded || change.controlNewText.let {
        it.isInt() && it.toInt() in 0..255
    }
}
```

And you'd use it like this:

```kotlin
textfield {
    filterInput(EightBitFilter)
}
```

**Comment by mcred** [comment]
This is awesome and very useful. If you point me in the right direction, I'll write this up and create a PR for documentation. Tell me where you want it and I'll see what I can do.

**Comment by edvin** [comment]
Sweet! You can either add it to Snippets, or at the end of the part describing Form :)

https://github.com/edvin/tornadofx-guide/blob/master/part3/Snippets.md
