### ISSUE TITLE
Better way to create ItemViewModel with many values

### ISSUE THREAD

**Issue by mcred** [edvin/tornadofx#938]
I can't seem to think of a better way to set up an ItemViewModel with many values that are bound. How can I refactor this when there are many more than 7 items? It looks like at around 130 or so items, it won't compile because the resulting method is too large. 

```kotlin
class TestModel(test: Test? = null) : ItemViewModel<Test>(test) {
    val item1 = bind(Test::item1)
    val item2 = bind(Test::item2)
    val item3= bind(Test::item3)
    val item4 = bind(Test::item4)
    val item5 = bind(Test::item5)
    val item6 = bind(Test::item6)
    val item7 = bind(EquTestpment::item7)
    ...
}
```

**Comment by edvin** [comment]
It seems a bit excessive to have a model with more than 130 fields, what's the use case for something like that? Perhaps there is a better way to tackle the issue. When your class becomes to large to compile, that's usually an indication of something fishy IMO :)

**Comment by mcred** [comment]
I agree. This app is a file editor. It opens up files from your disk, maps values from the file into bound form fields, allows them to be edited and then writes them back to the file. It's rather simple, each form field represents a binary address in the file, displays the current value and the name for the value. E.g. "Save Count" is located as 0x220C and has a value of 12. The mapping and form is rather simple, there are just several hundred individual values that can be edited. I've tried a few different approaches to dynamic generate the forms and models based on the individual locations, but so far I haven't been successful. I'm very happy to do this in a different way, lol.

**Comment by mcred** [comment]
I know that I can continue to break the items down into smaller groups, but I wanted to look for a better more programatic way to load the values before doing that.

**Comment by edvin** [comment]
You're not going to edit them all at once, so you should definitely create form fields for them when needed. You could probably have a single viewmodel with a single field for this.

**Comment by mcred** [comment]
Based on the program that created the file, the items are grouped together in a logical manner and in a way that users will expect them. There is a potential for one form to have a few hundred items, all very small and with an 8Bit value, but unique ID.

**Comment by edvin** [comment]
It sounds like a form is not the right UI for editing the data. Maybe a TableView with editable columns would be a better fit?

**Comment by mcred** [comment]
I agree. I think a TableView will be a better layout for this. 

Would `ItemViewModel<Test>(test)` still be required? So far it hasn't been the form where the issue is, it's creating the `ItemViewModel` with the multitude of `val item1 = bind(Test::item1)` where the compiling issue happens.

**Comment by edvin** [comment]
You probably don't need a viewmodel, and you also probably don't need any field members for each data chunk. Hard to recommend something without seeing the data though.

**Comment by mcred** [comment]
I was trying to ask my questions as generically as possible so any answers might be helpful to more people than just myself. If you want, I can share the project repo. Just didn't want to start posting links to outside projects without a request.

**Comment by edvin** [comment]
Maybe we could make this thread even more helpful if even the data was generic then? :) Try to make a small code sample where you load the data and a description of how you envision the ui.

**Comment by mcred** [comment]
I'll try to set up the scenario as generically as possible. 

```
//Sample File Data
00 00 42 88 A5 9C 00 D8 C0 FC DC BE 80 81 80 82 CD 
90 76 95 18 92 1F 93 48 B1 2E CA F6 CE 7B EF 00 00 
00 10 EE 1D 00 00 00 00 00 E1 ED DC 01 00 00 10 11 
DD CE EF 1D 00 00 D1 CD E2 FC 11 1D 00 00 10 1D CD 
1F 99 1C 00 00 10 5D D1 91 A5 01 00 00 11 DD 15 11 
15 12 00 10 22 EE 52 11 11 DE 01 10 D1 22 91 D1 11
```

```kotlin
//Define how to read the file
data class Location(
    val address: Int,
    val length: Int = 0,
    val reverseBytes: Boolean = false,
    val type: String = "Numeric"
) {
    fun getRange(): IntRange {
        return address..(address + length)
    }
}

//Map specific file locations to their User Friendly name
data class TestMap (
    val firstVal: Location = Location(0x001, 1, true),
    val secondVal: Location = Location(0x002, 1, true),
    val thirdVal: Location = Location(0x003, 1, true),
    val fourthVal: Location = Location(0x004, 1, true)
)
```
```kotlin
class Test(
    firstVal: Int,
    secondVal: Int,
    thirdVal: Int,
    fourthVal: Int
){
    val firstValProperty = SimpleIntegerProperty()
    var firstVal by firstValProperty
    val secondValProperty = SimpleIntegerProperty()
    var secondVal by secondValProperty
    val thirdValProperty = SimpleIntegerProperty()
    var thirdVal by thirdValProperty
    val fourthValProperty = SimpleIntegerProperty()
    var fourthVal by fourthValProperty
}

class TestModel(test: Test? = null) : ItemViewModel<Test>(test) {
    val firstVal = bind(Test::firstValProperty)
    val secondVal = bind(Test::secondValProperty)
    val thirdVal = bind(Test::thirdValProperty)
    val fourthVal = bind(Test::fourthValProperty)
}

class TestScope : Scope() {
    val test = TestModel()
}
```
```kotlin
class TestController: Controller() {
    val testScope = TestScope()
    val testMap = TestMap()
    val test = testScope.test

    init {
        test.firstVal.setValue(0)
        test.secondVal.setValue(0)
        test.thirdVal.setValue(0)
        test.fourthVal.setValue(0)
    }

    fun loadFromSlot(file: FileHelper) {
        test.firstVal.setValue(file.read(testMap.firstVal))
        test.HPMax.setValue(file.read(testMap.secondVal))
        test.Hearts.setValue(file.read(testMap.thirdVal))
        test.HeartsMax.setValue(file.read(testMap.fourthVal))
    }

    fun writeToSlot(file: SlFileHelpert) {
        file.write(testMap.firstVal, test.firstVal.value.toInt())
        file.write(testMap.secondVal, test.secondVal.value.toInt())
        file.write(testMap.thirdVal, test.thirdVal.value.toInt())
        file.write(testMap.fourthVal, test.fourthVal.value.toInt())
    }
}
```
```kotlin
class TestView : View("My View") {
    private val testCtrl: TestController by inject()
    private val test = testCtrl.test


    private val eightBitFilter: (TextFormatter.Change) -> Boolean = { change ->
        !change.isAdded || change.controlNewText.let {
            it.isInt() && it.toInt() in 0..255
        }
    }

    override val root = tabpane {
        useMaxWidth = true
        form {
            fieldset("Tests") {
                field("firstVal") { textfield(test.firstVal) { filterInput(eightBitFilter) } }
                field("secondVal") { textfield(test.secondVal) { filterInput(eightBitFilter) } }
                field("thirdVal") { textfield(test.thirdVal) { filterInput(eightBitFilter) } }
                field("fourthVal") { textfield(test.fourthVal) { filterInput(eightBitFilter) } }
            }
        }
    }
}
```
That's a lot of setup, but here's the run down. Based on the documentation, examples, and some Q&A, the above code creates a creates a TestModel and pushes it up into the root scope. The TestController pulls in the modelScope and, with the FileHelper, sets the value of items in the TestModel from the file. Not to get distracted by that part, the FileHelper has a few methods that know how to read the hex value based on the Location class and the Map. The TestView injects the TestController and binds the Model values to form fields. 

All of this is working. Where it fails is at scale. There is a limit to the amount of items that can be added to `ItemViewModel<Test>(test)` using this approach, but each address, `0x0001` is a unique enitity to the user and has a common name, like firstVal. The user doesn't have any context of how the data is stored in the file, they just know what it means in relation to the Form Field. So the potential exists for each hex address to represent a unique entity and would need to be an individual entitry on the Form. 

Hopefully that preamble makes sense. I know there must be a better, scalable way to get the data out of the file, by address, display it on a form and then put changes to the address back into the file. I've tried a few different ways, like looping through the model to generate the bindings, but I can't seem to make any of them work. Most of my struggle with this project is getting all of the TornadoFX pieces playing together. 

I'm open to any suggestions on how to improve this basic setup.

**Comment by edvin** [comment]
This code is not runnable, as several references classes are missing. Seems to me like you should just have a list of `Location` objects, but skip creating a data class and use observable properties instead.

Bind these to a TableView and you should be good to go. No need for ViewModel or Form.

**Comment by mcred** [comment]
I tried to simplify the setup to show the idea. I'll dig into TableViews and using observable properties this weekend. I really appreciate the time you took to look through this and offer advice.

**Comment by mcred** [comment]
Thanks again for the suggestion. It looks like using TableViews in combination with binding and unbinding items when they need to be edited will work. It's not the UX I had in mind, but it's something that I can work with.
