### ISSUE TITLE
Consider moving typesafe builders and stylesheets into a separate project

### ISSUE THREAD

**Issue by raniejade** [edvin/tornadofx#94]
They can be very useful outside tornadofx :)

**Comment by edvin** [comment]
You can use almost any part of TornadoFX in existing apps without embracing the whole structure. The features you mention actually make up about half the size of the library (300k), so separating them doesn't make that much sense IMHO.

Think about Google Guava - most people pull in a 2.2MB dependency for a couple of convenience functions for Lists. They use a very small percentage of the library, but drag along the whole monster anyway :)

Would this work for you?

You can also use View/Fragment standalone, and put the root node inside other Nodes that are not part of TornadoFX. Would you care to elaborate on what parts of TornadoFX you don't like/don't want to use in your apps? That would be very helpful.

**Comment by raniejade** [comment]
I guess that would work. I just want to use the typesafe builders and stylesheets in an experiment I'm doing (https://github.com/raniejade/zerofx).

Here are a few things in my mind.

1. I'm not really into **MVC** when writing JavaFX applications, things get complicated when you start embedding views. Views are hard (sometimes nearly impossible) to unit tests. **MVC** is not really suitable for desktop applications, **MVP** or **MVVM** is probably a better choice.

2. TornadoFX's DI support wouldn't work well (plausible but with some hacks) with static DI frameworks like [Dagger 2](http://google.github.io/dagger/)

**Comment by edvin** [comment]
OK, thanks for the insight :) Feel free to report any issues you come across while using TornadoFX adhoc, either here or on the mailing list :)
