### ISSUE TITLE
Tab.visibleWhen() throws NPE when trying to make the tab visible again

### ISSUE THREAD

**Issue by lion7** [edvin/tornadofx#942]
Because tabs can't be made (in)visible (they're not a node) a workaround is used where tabs are removed/added from the parent tabpane. The parent `tabPane` is accessed through the `tabPane` property on the `Tab` instance itself.

The problem is that after removing the tab from its parent the `tabPane` property of the `Tab` instance is set to null:
https://github.com/edvin/tornadofx/blob/1eec3eb5f694cf55d9f3c567130df873167d9b88/src/main/java/tornadofx/TabPane.kt#L61

This causes a NPE when trying to add the tab to the parent again, as happens here:
https://github.com/edvin/tornadofx/blob/1eec3eb5f694cf55d9f3c567130df873167d9b88/src/main/java/tornadofx/TabPane.kt#L62

I geuss a quick solution is to store the `tabPane` in a local variable in the extension method, I'll attach an PR to illustrate this.

**Comment by ctadlock** [comment]
Working, this issue can be closed
