### ISSUE TITLE
Equivalent for `SplitPane.setResizableWithParent(Node node, Boolean value)`?

### ISSUE THREAD

**Issue by nlbuescher** [edvin/tornadofx#945]
There doesn't seem to be any equivalent for the function `SplitPane.setResizableWithParent(Node node, Boolean value)`. Based on other Controls/Layouts, this would probably fall under `splitpaneConstrains`, but currently (1.7.18) there's no such thing.

**Comment by edvin** [comment]
I'm not sure I understand - you can just call this function as is. What do you hope to gain by adding an equivalent somewhere else?

**Comment by nlbuescher** [comment]
That is true. :) I personally dislike the inconsistency, so I implemented `splitpaneConstraints` in my project. So I would hope to gain consistency.

**Comment by edvin** [comment]
OK. This is not a constraint per se, so I don't see it as an inconsistency at all :) If a user knows the JavaFX API I think he would be surprised to find this in something called `splitpaneConstraints` which isn't a JavaFX construct. It seems to me you'd end up writing more code to call the same function by adding `splitpaneConstraints`, so I don't really like it :)

**Comment by nlbuescher** [comment]
So to illustrate my reasoning:
1. Qualities like margins or vgrow for children of VBox are set in JavaFX with static methods on VBox which accept the child node as a parameter (`public static void setMargin(Node child, Insets value)`). 
2. These static methods are implemented as contraints builders in TornadoFX. So in order so set the margins for the child of a VBox, you would use:
```kotlin
vbox {
    button {
        vboxConstraints {
            margin = insets(10)
        }
    }
}
```
3. This also applies to constraints whose children cannot have margins, such as AnchorPane:
```kotlin
anchorpane {
    button {
        anchorpaneConstraints {
            topAnchor = 10
        }
    }
}
```
4. `setResizableWithParent` is a constraint unique to `SplitPane` (nothing like it is found anywhere else in JavaFX)

Worth mentioning are `hgrow` and `vgrow`. They are implemented as both constraints, and as general extension properties on `Node`.

So based on these points I believe there is a good argument for implementing `isResizableWithParent: Boolean` as either a `splitpaneConstraint` (it would be the only one since `SplitPane` only has that one static method), an extension property on `Node`, or both.

**Comment by edvin** [comment]
Fair point. Though with only one function it is still more cumbersome to use than just calling the function directly, but for the sake of consistency I agree that it wouldn't hurt to add it, especially since it doesn't obfuscate the existing function. Feel free to submit a PR for it :)
