### ISSUE TITLE
Bind ToggleGroup selected property to external property in the DSL builder

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [edvin/tornadofx#956]
Considering this scenario:

```kotlin
    val selectedOrientationProperty = SimpleObjectProperty<Orientation>()

    togglegroup {
        radiobutton("Vertical", value = Orientation.VERTICAL)
        radiobutton("Horizontal", value = Orientaion.HORIZONTAL)
    }
```

There's no simple way to bind the `selectedOrientationProperty` to the selection of the `togglegroup`. I think something like this should exist:

```kotlin
    val selectedOrientationProperty = SimpleObjectProperty<Orientation>()

    togglegroup(selectedOrientationProperty) {
        radiobutton("Vertical", value = Orientation.VERTICAL)
        radiobutton("Horizontal", value = Orientaion.HORIZONTAL)
    }
```

Which would be a shorthand for something like:
```kotlin
    val selectedOrientationProperty = SimpleObjectProperty<Orientation>()

    togglegroup {
        selectedOrientationProperty.bind(selectedValueProperty())
        radiobutton("Vertical", value = Orientation.VERTICAL)
        radiobutton("Horizontal", value = Orientaion.HORIZONTAL)
    }
```

If this issue is confirmed,  I could try and make it happen.

**Comment by edvin** [comment]
I'd say `bind(selectedOrientationProperty)` is simple enough :)

But you're right, there is no reason not to include a builder parameter for the property, so I've commited this addition now. You can now do:

```kotlin
togglegroup(selectedOrientationProperty) {
}
```

**Comment by aleksandar-stefanovic** [comment]
Excellent, thanks!

I think that it is more about consistency, because other controls have the option to bind the property in their builders.
