### ISSUE TITLE
Component.configPath is breaking when Application cannot be cast to tornadofx.App

### ISSUE THREAD

**Issue by gabrielpaim** [edvin/tornadofx#957]
Hello there,

I'm experiencing some issues to use Component.config on an Application that is not directly a tornadofx App. Specifically, the configPath is trying to cast my entry Application class from the default scope to tornadofx.App, which breaks. I'm following [this](https://edvin.gitbooks.io/tornadofx-guide/content/part2/Integration.html) to integrate tornadofx with my app (I'm refactoring code to tornadofx, but it's still incomplete). Additionally, this post may be related to [this](https://github.com/edvin/tornadofx/issues/335).

Here is some code to reproduce the problem:

```
import javafx.application.Application
import javafx.stage.Stage
import tornadofx.*

class MyApp: Application() {
    override fun start(stage: Stage) {
        FX.registerApplication(this, stage)
        find<MyController>()
    }
}

class MyController: Controller() {
    init {
        println(configPath)
    }
}
```

I'm using tornadofx 1.7.17, java 1.8.0_181, kotlin 1.3.21.
Did I forget anything? Does someone have an ideia to deal with this issue?
Thanks a lot, have a nice day!

**Comment by edvin** [comment]
Since `configPath` is a property on `tornadofx.App`, you simply can't use this from a non-native app right now. However, I bet you can just let `MyApp` extend `tornadofx.App` instead, even though it's not a Kotlin class. I believe this should work just fine.

**Comment by bekwam** [comment]
Are you able to start with the TornadoFX App subclass and integrate your legacy code?

**Comment by gabrielpaim** [comment]
Nice, it worked!
Thank you @edvin and @bekwam. It took me a little extra effort because the simplest test case didn't fully represent my scenario. I'm currently using [Mvvmfx](https://github.com/sialcasa/mvvmFX), and I was already extending a base Application class from it. I needed to create another class that extended from tornadofx.App and 'merged' both implementations (My current Application process and theirs). 

It seems to be alright now, thanks again!

**Comment by edvin** [comment]
Great, thanks for reporting back!
