### ISSUE TITLE
readonlyColumn displays wrong values when using Pojo's in observable

### ISSUE THREAD

**Issue by ronsmits** [edvin/tornadofx#959]
Created a small project to show the issue at  https://github.com/ronsmits/readonlybug.git.

When Pojo attributes are wrapped in an observable to show fine in a normal column in a tableview they show wrong when used in a readonlyColumn:
```
class PersonModel(person: Person) : ItemViewModel<Person>(person) {
    val firstname = observable(person, Person::getFirstname, Person::setFirstname)
    val lastname = observable(person, Person::getLastname, Person::setLastname)
}
class LeftView : View() {
    override val root = tableview(personList) {
        column("first name", PersonModel::firstname)
        column("last name", PersonModel::lastname)
    }
}
class RightView : View() {
    override val root = tableview(personList) {
        readonlyColumn("first name", PersonModel::firstname)
        readonlyColumn("last name", PersonModel::lastname)
    }
}
```
![2019-03-24 01_44_24-](https://user-images.githubusercontent.com/595350/54873434-73a45380-4dd6-11e9-8795-8798b1560276.png)

**Comment by edvin** [comment]
The bug is in your code, Ron :) As the docs state, `readonlyColumn` is for converting an non-observable column to an observable, and you are referencing observable properties in a ViewModel :)

**Comment by ronsmits** [comment]
you are right its in the documentation, the property itself was just accepted though, which is why I did not check the documentation

**Comment by ronsmits** [comment]
Unsupported [reference to the synthetic extension property for a Java get/set method]

**Comment by edvin** [comment]
What do you do to get that message?

**Comment by ronsmits** [comment]
this was in the popup of intellij when I hovered over the red squiggle

**Comment by edvin** [comment]
Not sure I follow. Exactly what LOC do you get this on?

**Comment by ronsmits** [comment]
I got it once but was not able to reproduce it. (it was late and the stuff
that the anesthesiologist put in me was not completely gone).

The main problem is that readonlyColumn does not seem to work with a java
pojo.The error I get is
"Error:(31, 38) Kotlin: Type mismatch: inferred type is KFunction1<Person,
String!> but KProperty1<Person, ???> was expected"

The code is on github and this is the MyApp.kt

**Comment by edvin** [comment]
Aha. You might need to use the builder that accepts a getter and setter reference for java pojos :)

**Comment by ronsmits** [comment]
you mean the columnBuilder?

**Comment by edvin** [comment]
Yes, you should be able to do `column( "Name", MyPojo::getName)` etc

**Comment by ronsmits** [comment]
works
