### ISSUE TITLE
In Wizard, the "Next" button doesn't appear disabled even when incomplete

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [edvin/tornadofx#960]
When using the Wizard, and overriding the `complete` expression, the button is disarmed when the expression is `false`, but it doesn't appear as disabled.
![Screenshot from 2019-03-25 18 12 00](https://user-images.githubusercontent.com/6058082/54939593-4320fe80-4f29-11e9-8fac-8fd94188d831.png)

**Comment by edvin** [comment]
Can you post some code showing the issue?

**Comment by aleksandar-stefanovic** [comment]
I've created a minimal example:

```kotlin
import javafx.beans.property.SimpleBooleanProperty
import tornadofx.*

class MyWizard : Wizard() {

    init {
        add(WizardStep1::class)
        add(WizardStep2::class)
    }
}

class WizardStep1 : View("Step 1") {

    override val complete = SimpleBooleanProperty(false)

    override val root = vbox { }

}

class WizardStep2 : View("Step 2") {
    override val root = vbox {}
}
```

In this example, the "Next" Button appears as not disabled, even though pressing it does nothing. If you change the property to `true`, the button works as expected (it goes to the next step when pressed)

**Comment by aleksandar-stefanovic** [comment]
Upon further investigation, these are the culprits:

Wizard.kt, (line ~168):

```kotlin
 enableWhen(canGoNext.and(hasNext))
```

Seems good, but then, 
```kotlin
open val canGoNext: BooleanExpression = hasNext
```

**Comment by edvin** [comment]
The issue is that the `enableWhen` expression should also account for `currentPageComplete`. I've committed a fix now :)

**Comment by aleksandar-stefanovic** [comment]
Thank you!

**Comment by edvin** [comment]
Thanks for reporting :))
