### ISSUE TITLE
Auto-select new item in ListView

### ISSUE THREAD

**Issue by sderosiaux** [edvin/tornadofx#962]
Hi!

New user here, thanks for TornadoFX, it's amazing to work with.

I have one question about selections. I have a listview and a button to add items like this:

edit: i've added a gist to copy/paste/run https://gist.github.com/sderosiaux/87c88ab905c05d922d0abe7fcd1c8fd6

```kotlin
val selection: ItemModel by inject()

list = jfxlistview(data) {
  bindSelected(selection)
  cellFragment(MyFragment::class)
}
```
```kotlin
button("Add an item") {
  action {
    val newItem = controller.create()
    data.add(newItem)
    selection.item = newItem
    // list.selectionModel.select(newItem)
  }
}
```

The selection works properly when I do select the items in the list.
But I'd like my listview to automatically select the new item (you know, the focused color) when one is added. I thought that because it's bind (`bindSelected`) it would work automatically but no. I need to select it manually to force the list focus to change (the commented line). Is this expected? Is there a more automated way to do this?

Thanks for your help

**Comment by ronsmits** [comment]
If this is the complete code then the new item is not in the "items"
attribute of the listView,

**Comment by sderosiaux** [comment]
@ronsmits My bad, it is missing a little part. `controller.create()` adds it to the `data` ObservableList.

**Comment by edvin** [comment]
Yes, this is as expected. The binding is one way only. You can verify this by looking at the source code for the `bindSelected` function:

```kotlin
fun <T> ListView<T>.bindSelected(property: Property<T>) {
    selectionModel.selectedItemProperty().onChange {
        property.value = it
    }
}
```

**Comment by sderosiaux** [comment]
Yes @edvin. `selectedItem` is a `ReadOnlyObjectWrapper` hence it's inherently a one-way only. Thanks!
