### ISSUE TITLE
Problem with transparent background

### ISSUE THREAD

**Issue by NanoNik** [edvin/tornadofx#966]
I have a transparent stage and a view with the image as a background, but when I call replaceWith with transition or open an internal window transparency breaks.

Before opening internal window:
![image](https://user-images.githubusercontent.com/11991329/55641246-bea66980-57cd-11e9-860e-96346625a8fd.png)

After:
![image](https://user-images.githubusercontent.com/11991329/55641262-c6fea480-57cd-11e9-9c99-476705be7875.png)

To make my scene transparent I use this code:
Inside App
`override fun createPrimaryScene(view: UIComponent) = super.createPrimaryScene(view).apply {
    fill = Color.TRANSPARENT
}`

And this inside view:
`root.style {
     backgroundColor += Color.TRANSPARENT
}`

How can I fix it?

**Comment by aleksandar-stefanovic** [comment]
This probably belongs on StackOverflow, since GitHub Issues is the place for posting bugs in the TornadoFX itself (and not user help).

**Comment by ruckustboom** [comment]
@aleksandar-stefanovic Did you verify this isn't a bug?
