### ISSUE TITLE
Allow to specify the index for the new tab created inside the TabPane

### ISSUE THREAD

**Issue by zshamrock** [edvin/tornadofx#969]
Currently `TabPane.tab` extensions add the new tab by default to the end of the tabs list. 

Could be good to add a few more extensions where the index can be passed specifying the location of the new tab.

One of the possible use case where it might be handy is when you duplicate the current tab, and want it to be inserted just after the current one, like here https://github.com/zshamrock/dynoman/commit/ef0f45d87435a50d9cad3fdc31d5a5c7edc453a1#diff-8249fde5cb547e044e20aa28212c3ddfR56.

**Comment by edvin** [comment]
If we can add an index parameter without breaking backwards compatibility that would be nice. If not, it's pretty straight forward to do this explicitly:

```kotlin
class MyView : View("My View") {
    override val root = tabpane {
        tab("First") {
            label("I'm first")
        }
        tab("Second") {
            label("I'm second")
        }
        tab("1.5") {
            label("I'm in between")
            tabs.move(this, 1)
        }
    }
}
```

**Comment by zshamrock** [comment]
Will it break the backward compatibility, as I imagined these will be the new separate extensions in addition to the existing ones.

Also thanks for the `move`, didn't notice it there. Use it now instead of `replace & add` (which is actually what `move` does, but just out of the box).

**Comment by edvin** [comment]
Merged :)
