### ISSUE TITLE
Dev mode

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#97]
It will probably become a common pattern to do something like this to enable hot reloading of stylesheets and views:

```kotlin
class MyApp : App() {
...
    override fun start(stage: Stage) {
        if (parameters.named["devmode"] == "true") {
            reloadStylesheetsOnFocus()
            reloadViewsOnFocus()
        }
        super.start(stage)    
    }
}
```

Maybe this functionality should be included inn `App` by default, for example if the app i started with the program parameter `--tornadofx-devmode=true` or something like that?

**Comment by thomasnield** [comment]
That would make sense.

**Comment by ronsmits** [comment]
As long as the option stays to turn it on or off without the "devmode==true" I agree.

**Comment by t-boom** [comment]
I agree. Another feature I would like to see (only if others would think it is useful) is to dump the stylesheet to the terminal on reload when in dev mode.

**Comment by edvin** [comment]
Cool! OK, I'll make this happen. Come to think if it, we don't need to add `=true`, just the presence of the parameters will do. 

Can you guys help me with good parameter names? We have a couple of options.

1. `--devmode` (turns both stylesheet and view reloading on)
2. -`-reload-stylesheets --reload-views` (two separate parameters)
3. Either 1 or 2, but with some kind of prefix to not muck up the parameter names, like for example `--tornadofx-devmode` etc. Probably not necessary, right?

For dumping the stylesheet we could add `--dump-stylesheets`. This will dump the stylesheet the first time it's loaded as well.

**Comment by edvin** [comment]
@ronsmits Yes, we'll keep the programmatic control :)

**Comment by edvin** [comment]
I've implemented Option two, together with dump-stylesheets just to check how it feels, and it feels fine. We could keep it, and also add --devmode as short alternative that enables everything?

**Comment by t-boom** [comment]
Personally I would prefer something like `--live-stylesheets` over `--reload-stylesheets` as the latter doesn't really give an indication that it happens more than once, but considering how specific this use case is, I don't think it matters much.

**Comment by edvin** [comment]
I like it :) live-stylesheets is kind of catchy :)

**Comment by t-boom** [comment]
For the views, I don't know if you would use `--live-views`, `--live-layout`, or what. You don't distinguish between structures created through DSL or FXML, do you?

**Comment by edvin** [comment]
No, we reload the whole view so DSL = FXML. --live-views should be good.

**Comment by t-boom** [comment]
That's what I was thinking. In that case, I agree with `--live-views`.

**Comment by edvin** [comment]
I have updated the Wiki as well:

https://github.com/edvin/tornadofx/wiki/Application-Startup#built-in-startup-parameters
