### ISSUE TITLE
Fragments/Views inside another UIComponent should not be reloaded

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofx#98]
Only the top level Fragment or View should be reloaded, as this will also reload any containing UIComponents. However, Views found inside other UIComponents should still be removed from FX.components so that they will be recreated.

**Comment by voddan** [comment]
it is not clear how it should work with pack/unpack for those views

**Comment by edvin** [comment]
No, that's a very good point. Avoiding the duplicate reloading also "avoids" reloading the state.

**Comment by edvin** [comment]
We could save the state of the child in the parent, and when the parent loads the child, it could fetch that data and call unpack. Currently there are probably no hooks available to make this happen, and we'd need some kind of datastructure to put into the parent.properties to make sure we reinstate the correct state. A map of <KClass<UIComponent>, Any> won't do, because a Fragment can potentially be used multiple times inside another UIComponent.

I think this will get a bit messy, so I wonder if we should just support state reloading in the top most view and avoid duplicate recreation of nested views. This is how it works in HEAD right now.

**Comment by ronsmits** [comment]
Hmmz

Even the supporting of state on the top level sounds a bit messy. Maybe first define the usecase we are trying to solve before going further down this route?

The loading/reloading during development is an excellent idea. I don't know if a reloading like this would be advisable in a production environment?

Apart from that what are the architectural constraints that will be 'forced' upon users of this? I feel that tornadofx would become a bit opionated towards a single form of architecture with this. 

Just my 0.02cents

**Comment by edvin** [comment]
This feature is only available in debugging mode, so it won't even work in production. The reason for pack/unpack is simply to make it possible to recreate the state of the ui component values after a reload. I don't think it will be used much, and maybe you're right - maybe it's just too complex and really not needed. After all, the point of the view reload is just to see what your changes meant to the ui itself. If you entered something in an input field, maybe it doesn't help you to get that value back when you changed the UI. It might even be impossible, because you could have removed something that unpack relies on, and then it would fail causing the reload to fail as well.

Should we remove pack/unpack? @voddan this was your baby, what do you think?

**Comment by voddan** [comment]
In my current TornadoFX project the state is kept in a separate singleton, so reloading does not affect it. My initial idea was that pack/unpack are trivial to implement. If they are not, then better to remove them all together, otherwise we risk to get a counterintuitive design.

**Comment by edvin** [comment]
OK, I'll remove it then :) For development it's probably easier doing what you're doing now.
