### ISSUE TITLE
How to change the controller default path?

### ISSUE THREAD

**Issue by MindFlare56** [edvin/tornadofx#983]
Error:
SEVERE: Uncaught error
java.lang.IllegalArgumentException: FXML not found for class controllers.adapters.Loading in Loading.fxml

I've seen this:
override val configBasePath: Paths.get("/etc/myapp/conf")

But I don't find the class Paths with a method get.

The problem happens when I try to move the controller.

![Capture](https://user-images.githubusercontent.com/35500233/57184992-18b05280-6e92-11e9-924e-c2ea0fe07b36.PNG)

**Comment by edvin** [comment]
Since you moved the `loading.fxml` file to `/` and renamed it from `Loading.fxml`, you need to do one of two things:

1. Pass the path of the fxml resource to the fxml delegate: `by fxml("/loading.fxml")`
2. Configure the `FX.fxmlLocator` callback to convert to your desired file name/path convention, something like:

`FX.fxmlLocator = { component, location ->
    val targetLocation = location ?: "/" + component.javaClass.simpleName.toLowerCase() + ".fxml"
    requireNotNull(component.resources.url(targetLocation)) { "FXML not found for ${component.javaClass} in $targetLocation" }
}
```

Beware that approach no 2 will get you into trouble if you name two ui components in different packages the same, since you've removed the folder hierarchy.

Also, why would you call UI components for `controllers`? Controllers should not load fxml. Actually, nobody should, get on the type safe builder train already! :)

**Comment by MindFlare56** [comment]
Oh so I just needed to add the path here: 
override val root: VBox by fxml("/loading.fxml")
Thank you!

I'll look for the TypeSafe builder for sure.
I am still new to JavaFX, tornadofx and Kotlin so I am trying to learn all of these for a special work at my school where we have to make a JavaFX application. tornadoFx seemed like a nice modern framework to use. I really appreciate the quick answer thank you!

**Comment by edvin** [comment]
Yes, that will work. Alternatively, move and rename to `resources/controllers/adapters/Loading.fxml`. But again, calling an UIComponent `Controller` is very confusing. If you're just starting out there is absolutely no need to learn FXML, I urge you to look into builders asap :)
