### ISSUE TITLE
Why openInternalWindow() is protected in UIComponent?

### ISSUE THREAD

**Issue by Mesayah** [edvin/tornadofx#989]
Is there any reason this function is protected? I wanted to separate my UI definition with logic and put button action implementation, which opens a Fragment in a new internal window, in dedicated Controller, but I can't call openInternalWindow() from there because it's protected member of UIComponent class.

Surprisingly openModal() and openWindow() are public.

**Comment by edvin** [comment]
They do very different things. `openWindow()` opens the UIComponent in a new window, while `openInternalWindow()` opens another window inside the current, so it normally makes less sense to be calling that from the outside. However, it would not be problematic to make `openInternalWindow()` public, so we can absolutely do that. As a workaround you can make a simple function in your UICompoenent which in turn calls `openInternalWindow()`.

**Comment by ronsmits** [comment]
IS this already in the .19 release?

**Comment by edvin** [comment]
No, it's in 1.7.20-SNAPSHOT, but the workaround is quite simple luckily :)
