### ISSUE TITLE
Tableview column not correctly binding to underlying property

### ISSUE THREAD

**Issue by alexheim** [edvin/tornadofx#99]
When you bind columns of a tableview to a properties of a data class, the view is not updated on value changes. However, if you define the binding via the property name (as String) it's working.

As an example, look at this data class (just like in the demo application)
```kotlin
class TestData(a: String, b: String) {
    var a by property<String>()
    fun aProperty() = getProperty(TestData::a)

    var b by property<String>()
    fun bProperty() = getProperty(TestData::b)

    init { this.a = a; this.b = b; }
}
```
And define the view with a table and a button, which, when pressed updates the item in the view:
```kotlin
class ColTestView : View() {

    override val root = VBox()
    private val testItems = FXCollections.observableArrayList<TestData>(TestData("a", "b"))

    init {
        with(root) {
            alignment = Pos.CENTER
            tableview<TestData> {
                items = testItems
                column("Property A", TestData::a)            // NOT WORKING 
                column<TestData, String>("Property B", "b")  // WORKING
            }
            button { // Press the button to update the item's values
                text = "Change Data"
                onAction = EventHandler<ActionEvent> {
                    testItems[0].a += " - changed"
                    testItems[0].b += " - changed"
                }
            }
        }
    }
}
```
Run the example with some main class, and you'll see that only the "b" column will reflect the update.
```kotlin
class ColTestApp : App() {
    override val primaryView = ColTestView::class

    companion object {
        @JvmStatic fun main(args: Array<String>) { launch(ColTestApp::class.java)}
    }
}

**Comment by edvin** [comment]
You need to bind to the property, not the variable :) So simply change the binding to this:

```kotlin
column("Property A", TestData::aProperty)
```

And you should be golden :)

When you bind to `TestData:a`, that would be the same as binding to a non-observable `getter/setter` pair. Does that make sense?

**Comment by edvin** [comment]
I just saw that the TableView examples in the Wiki made the same mistake, I've corrected it now. @thomasnield heads up: You need to bind to the function that returns the property to have changes in the data model reflected in the tableview. I think we need to clarify this further, could you add a line to the wiki and possibly mention it in the guide? :) My wording is a bit clumsy, so I think we'll have better success if you write a line or two about it :)

**Comment by alexheim** [comment]
Sure... works like a charm . Indeed, I took the code sample from your Wiki, and didn't notice that it must obviously be the property, to bind to. Thanks for your quick help!

**Comment by edvin** [comment]
Perfect! Thanks for reporting this :)

**Comment by thomasnield** [comment]
Sure let me see what I can do...

**Comment by edvin** [comment]
Thank you Thomas :))

**Comment by thomasnield** [comment]
I'm a little confused. Are you referring to this page?
https://github.com/edvin/tornadofx/wiki/Type-Safe-Builders

The example seems to follow the convention you pointed out...

```kotlin
class MyView : View() {

    override val root = VBox()

    private val persons = FXCollections.observableArrayList<Person>(
            Person(1,"Samantha Stuart",LocalDate.of(1981,12,4)),
            Person(2,"Tom Marks",LocalDate.of(2001,1,23)),
            Person(3,"Stuart Gills",LocalDate.of(1989,5,23)),
            Person(3,"Nicole Williams",LocalDate.of(1998,8,11))
    )

    init {
        with(root) {
            tableview(persons) {
                column("ID", Person::idProperty)
                column("Name", Person::nameProperty)
                column("Birthday", Person::birthdayProperty)
                column("Age", Person::ageProperty)
            }
        }
    }
}
```

**Comment by edvin** [comment]
That's correct :) I changed them an hour ago :)

"I just saw that the TableView examples in the Wiki made the same mistake, I've corrected it now."

**Comment by edvin** [comment]
We just need to clarify that happens when you bind to "id" instead of "idProperty". My english is so clumsy, so I'll probably make it worse if I try to elaborate myself :) hehe

**Comment by thomasnield** [comment]
Oh okay, awesome.
