### ISSUE TITLE
How to use tableview with fxml file?

### ISSUE THREAD

**Issue by maccadoo** [edvin/tornadofx#990]
I will transportat to TornadoFX PG from JavaFX.
But I want to use fxml file and tableview.

I can not insert to tableview with new data.

for example.
this blog use fxml and tableview with JavaFX.
https://courses.bekwam.net/public_tutorials/bkcourse_simpletableapp_kotlin.html

I use the same fxml file and the same Data Class in this blog.

this is the Main and Application Subclass rewriten by me.

```
class SimpleTableApp : App(SimpleTableController::class)
```

Controller

```
class SimpleTableController: View("SimpleTableApp") {
  override val root: VBox by fxml("/SimpleTable.fxml")
  var tcScreenName = TableColumn<Participant, String>() by fxid<String>()
  var tblParticipants = TableView<Participant>() by fxid<Participant>()

  init {
    tcScreenName.cellValueFactory = PropertyValueFactory<Participant, String>("screenName")
  }

  fun refresh() {

    val task = object : Task<List<Participant>> () {
      override fun call(): List<Participant> {
        return fetchData()
      }

      override fun succeeded() {
        tblParticipants.items.clear()
        tblParticipants.items.addAll( value )
      }
    }

    Thread(task).start()

  }

  var counter = 1

  fun fetchData() : List<Participant> {

    val participants = listOf(
            Participant("Carl" + counter++),
            Participant("Wanda" + counter++),
            Participant("Peter" + counter++)
    )

    return participants
  }
}
```

The IDE tell me the error that "Unresolved reference: by"

How do I fix my code?

**Comment by edvin** [comment]
Import `tornadofx.*` :)

**Comment by maccadoo** [comment]
Sorry, Although I omitted, the following has already been imported

```
import javafx.concurrent.Task
import javafx.scene.control.TableColumn
import javafx.scene.control.TableView
import javafx.scene.control.cell.PropertyValueFactory
import javafx.scene.layout.VBox
import tornadofx.*
```

**Comment by edvin** [comment]
Can you check in your code to a github repo perhaps, including the deployment descriptor?

That said, please not that FXML is not the way to go for TornadoFX. You should really look into the type safe builders and never think about FXML again :)

**Comment by maccadoo** [comment]
Sorry, But I want to use TornadoFX, Please tell me.
I make a github repo and upload to this repo.
git@github.com:maccadoo/SimpleTableApp.git

**Comment by bekwam** [comment]
Hi,

The blog post you cited doesn't use TornadoFX; it's plain JavaFX with Kotlin.  Although FXML will work with TornadoFX, you'll hit a wall quickly once you start nesting your components.  I concur with Edvin that you should be using the Type Safe Builders (rather than FXML).  On the courses.bekwam.net site, look for examples with "TornadoFX" in the title.

**Comment by maccadoo** [comment]
I understood.
I give up to use FXML with TornadoFX.
I try to use the Type Safe Builders.

Thanks for edvin and bekwam.
