### ISSUE TITLE
Generic HttpEntity support in HttpClientRequest

### ISSUE THREAD

**Issue by ppslim** [edvin/tornadofx#996]
The `HttpClientRequest` Rest engine already leverages `org.apache.http.HttpEntity` in `HttpClientRequest#execute` for the items supported via `StringEntity`, but misses an extremely cheap chance for wider support via `is HttpEntity-> r.entity = entity`

Due to the lack of open classes, it is current required to clone `HttpClientEngine`, `HttpClientRequest` & `HttpClientResponse` (plus ext functions on `Rest.post`) in order to support generic HttpEntity support.

In my use case, I have a single call requirement (application login) that involves multipart. Rest provides all the support I need except this.

With the engine/request/response cloned, I am now able to leverage the Apache clients `MultipartEntityBuilder`

**Comment by edvin** [comment]
I've added support for passing HttpEntity along like you suggested :)

**Comment by ctadlock** [comment]
Closing as resolved
